CREATE TABLE transaction (
  id serial primary key,
  invoiceId double,
  moveId varchar,
  languageCode int,
  brandId mediumint,
  levelId bit,
  dialCode real,
  creditCard serial,
  apiKey boolean,
  moduleId bit,
  metaKeywords float,
  isArchived enum,
  group serial,
  accountType blob,
  customerGroup float,
  dateFormat decimal,
  analyticsId date
);

CREATE TABLE tblproductextra2024 (
  id serial primary key,
  logLevel blob,
  postalCode mediumint,
  dueDateAt datetime,
  longitude blob,
  machineId tinyint,
  title real,
  copyRight float,
  keywords tinyint,
  createdAt set,
  contactEmail tinyint
);

CREATE TABLE account (
  id serial primary key,
  lockoutEnd set,
  fileType time,
  appVersion mediumint,
  entityId bigint,
  colorCode tinyint,
  creditScore bit,
  metadata enum,
  fileName datetime,
  sessionId datetime,
  emailStatus float,
  employeeCode blob,
  completedAt int,
  loginCount text,
  deactivatedAt text
);

CREATE TABLE tmp_customer (
  id serial primary key,
  loginCount bit,
  connectionString bit,
  defaultValue smallint,
  password int,
  accountNumber decimal,
  joinDate binary,
  couponCode float,
  countryCode real,
  lastLoginAt tinyint,
  blogId timestamp,
  employeeId float,
  metaDescription smallint,
  folderPath decimal,
  documentId point,
  costCenter timestamp,
  updatedAt timestamp,
  checkInTime binary,
  name set,
  dailyLimit decimal,
  deactivatedAt boolean,
  forwardTo varchar,
  department serial
);

CREATE TABLE tmp_product (
  id serial primary key,
  validUntil timestamp,
  country smallint,
  linkId bigint,
  metaTitle bigint,
  ipAddress geometry,
  depositAmount binary,
  defaultLang varchar,
  checkOutTime enum,
  category time,
  machineId int
);

CREATE TABLE orderdivtemp (
  id serial primary key,
  backupEmail date,
  bannerImage datetime,
  moveId date,
  certificateId datetime,
  inactiveAt float,
  apiKey binary,
  mainImage varchar,
  contactName point,
  industryType timestamp,
  dashboardId bit,
  claimId point,
  latitude decimal,
  isHidden datetime,
  sku real,
  updatedAt binary,
  currency text,
  category double,
  dimension tinyint,
  description datetime,
  attemptCount double,
  address enum,
  shippingAddress tinyint
);

CREATE TABLE stg_organization (
  id serial primary key,
  updatedAt blob,
  cancelReason date,
  birthDate serial,
  title bigint,
  metaTitle bigint,
  deletedAt real,
  levelId bit,
  keywords double,
  createdAt tinyint,
  moveId time,
  authToken serial,
  customerGroup tinyint,
  copyRight int,
  isFeatured real,
  emailStatus decimal,
  uuid tinyint,
  paymentMethod time,
  errorCode mediumint,
  priority tinyint,
  dashboardId date
);

CREATE TABLE transaction (
  id serial primary key,
  merchantId int,
  deviceToken boolean,
  startDate decimal,
  deviceId enum,
  listingId mediumint,
  languageCode double,
  errorCode mediumint,
  cardHolder smallint,
  logLevel binary,
  amount varchar,
  clientId serial,
  signature enum,
  accountType float,
  appVersion bit,
  status bit,
  email time,
  value time
);

CREATE TABLE ref_account_temp (
  id serial primary key,
  email datetime,
  addressLine2 set,
  metadata text,
  flagged blob,
  dateFormat time,
  jobTitle point,
  fromDate point,
  geoLocation bit,
  taxRate real
);

CREATE TABLE payment (
  id serial primary key,
  exchangeRate date,
  productCode bit,
  birthDate bigint,
  name bit,
  discountCode binary,
  flagged smallint,
  duration enum,
  defaultValue bigint,
  minValue date,
  salary date,
  downloadCount datetime,
  expiryDate float,
  inactiveAt smallint,
  maritalStatus text,
  attemptCount bigint,
  articleId int,
  firstName bigint,
  globalId varchar,
  mimeType bigint,
  bluetoothId enum,
  childId varchar,
  orderStatus boolean,
  fontFamily date,
  actionType varchar,
  feedbackId decimal,
  feedId text,
  buildNumber int,
  dateFormat date
);

CREATE TABLE fact_company (
  id serial primary key,
  weight tinyint,
  birthDate text,
  content bigint,
  isEnabled smallint,
  grade serial,
  amount date,
  uuid point,
  errorMessage binary,
  machineId date,
  maritalStatus set,
  headerImage serial,
  instructorId real,
  description point,
  merchantId binary,
  validUntil datetime,
  createdAt timestamp,
  hostName tinyint,
  dialCode float,
  ipAddress time,
  size decimal,
  checkOutTime decimal,
  chargeId decimal,
  insertedAt datetime,
  accessLevel varchar,
  fingerprint double,
  accountType tinyint,
  value time,
  manufacturerId text,
  username time,
  guestId real
);

CREATE TABLE tblproduct (
  id serial primary key,
  isBillable point,
  industryType tinyint,
  hourlyRate geometry,
  url datetime,
  departmentCode bigint,
  education mediumint,
  incidentId time,
  insuranceId bigint,
  deactivatedAt geometry,
  amount smallint,
  salary int,
  dailyLimit smallint,
  depositAmount geometry,
  dialCode time,
  value boolean,
  checkInTime real,
  accountType date,
  brandId decimal,
  birthDate boolean,
  channelId decimal,
  createdAt text,
  address decimal,
  fileSize serial,
  phone blob,
  height date
);

CREATE TABLE pubconfigstatusv2 (
  id serial primary key,
  actionType varchar,
  isDefault tinyint,
  name enum,
  title text,
  abandonedCartId int,
  agentId bigint,
  memberCount double,
  maritalStatus varchar,
  dimension blob,
  gameId serial,
  modifiedAt smallint,
  inactiveAt bigint,
  isBillable point,
  connectionString boolean,
  email varchar,
  dateFormat int,
  discount tinyint,
  middleName geometry,
  customField2 bit
);

CREATE TABLE organization (
  id serial primary key,
  dimension varchar,
  mapId tinyint,
  birthDate smallint,
  filterType varchar,
  cloudId double,
  joinDate blob,
  postalCode int,
  age timestamp,
  isRequired timestamp,
  gateId binary,
  title set,
  employeeId varchar,
  version tinyint,
  maxValue datetime,
  defaultLang bigint,
  paymentMethod text,
  endPoint geometry,
  group bigint
);

CREATE TABLE factaccount (
  id serial primary key,
  country double,
  avatar date,
  accessLevel blob,
  fileSize real,
  completionRate timestamp,
  isRequired double,
  firstName datetime,
  manufacturerId blob,
  fontSize varchar,
  countryCode text,
  accountNumber varchar,
  validUntil set,
  dependentId date,
  entityId enum,
  rating real,
  mimeType time,
  geoLocation float,
  comment varchar,
  deletedAt date,
  createdAt text,
  apiKey bigint,
  localeId text,
  birthDate serial,
  deviceToken set,
  attemptCount real,
  postalCode tinyint,
  expiryDate serial
);

CREATE TABLE transaction_v2 (
  id serial primary key,
  minLimit datetime,
  startDate geometry,
  moduleId mediumint,
  instanceId boolean,
  ipAddress binary,
  fingerprint blob,
  claimId float,
  completionRate smallint,
  metadata bigint,
  cardHolder mediumint,
  errorCode geometry,
  zipCode boolean,
  mobileNumber bit,
  buildNumber point,
  deviceToken set,
  bannerImage int,
  shippingAddress varchar,
  dialCode double,
  priority boolean,
  entityId time,
  manufacturerId double,
  activeDevices mediumint,
  followCount timestamp,
  companyName float,
  licenseKey datetime,
  department bigint,
  signature bit
);

CREATE TABLE company (
  id serial primary key,
  linkId blob,
  accessLevel blob,
  category set,
  rating date,
  monthlyRate int,
  avatar geometry,
  invoiceId set,
  contactName blob,
  metaDescription datetime,
  employmentDate float,
  isEnabled binary,
  layerId double,
  discountCode real,
  flagged time,
  balance geometry,
  dueDateAt blob,
  email set,
  exchangeRate real,
  checkOutTime decimal,
  distributorId int,
  abandonedCartId bigint,
  maskType binary,
  integrationId real,
  budgetCode geometry
);

CREATE TABLE srcrecord (
  id serial primary key,
  minValue blob,
  exchangeRate datetime,
  contactPhone smallint,
  isBillable timestamp,
  buildNumber boolean,
  exportId bit,
  paymentMethod bit,
  checkInTime datetime,
  value binary,
  groupName bit,
  gender datetime,
  abandonedCartId bigint,
  contractId smallint,
  bannerImage text,
  invoiceId double,
  isSystem bit,
  latitude decimal,
  createdAt varchar
);

CREATE TABLE tmpcustomer (
  id serial primary key,
  groupName varchar,
  clockIn bit,
  companyLogo bigint,
  deliveryDate timestamp,
  messageId varchar,
  lastLoginAt datetime,
  employeeCode set,
  dialCode decimal,
  gameId real,
  hiddenAt tinyint,
  uuid bit,
  metadata tinyint,
  status boolean,
  loadTime geometry
);

CREATE TABLE inventory_out (
  id serial primary key,
  errorCode enum,
  deviceToken date,
  abandonedCartId set,
  apiVersion point,
  sku decimal,
  itemCount float,
  buildNumber geometry,
  employmentDate binary,
  appVersion date,
  filterType blob,
  createdAt set,
  editedAt smallint,
  companyName int,
  forwardTo geometry,
  category serial,
  minLimit text,
  chargeId double,
  distributorId real,
  unit point,
  listId mediumint,
  dailyLimit text,
  email smallint,
  gameId timestamp,
  metadata set,
  industryType tinyint,
  orderStatus double,
  firmwareVersion time,
  moduleId bit,
  status text
);

CREATE TABLE inventory (
  id serial primary key,
  cvv mediumint,
  duration enum,
  localeId enum,
  createdAt enum,
  albumId binary,
  price geometry,
  contractId date,
  fromDate date,
  isDraft geometry,
  orderStatus float,
  amount enum,
  lastSeenAt bigint,
  paymentMethod mediumint
);

CREATE TABLE user (
  id serial primary key,
  amount binary,
  downloadCount float,
  shippingAddress text,
  jobTitle timestamp,
  keywords text,
  url date,
  machineId float,
  entryPoint decimal,
  messageId timestamp,
  domainName timestamp,
  signature time,
  meterNumber double,
  abandonedCartId bit,
  memberCount text,
  authMethod boolean,
  currencyCode geometry,
  locationId real,
  deletedAt datetime,
  id bigint,
  mimeType decimal,
  campaignId bit,
  phone bigint,
  cardHolder time,
  faxNumber double,
  marketId tinyint,
  contactPhone smallint,
  isVerified float,
  title int,
  cvv decimal
);

CREATE TABLE payment_2024 (
  id serial primary key,
  maritalStatus date,
  accountNumber enum
);

CREATE TABLE inventory_log (
  id serial primary key,
  channelId binary,
  contentType float,
  homePhone bit,
  postalCode point,
  score serial,
  endDate set,
  isAdmin real,
  inactiveAt tinyint,
  contactEmail timestamp,
  forwardTo geometry,
  phone real,
  updatedAt datetime,
  isVerified double,
  menuId bit,
  analyticsId mediumint,
  frameRate text,
  deviceId int,
  listId binary,
  name serial,
  street real,
  discountCode datetime,
  department datetime,
  chargeId blob,
  coordinateX serial,
  tags real,
  machineId time,
  latitude float,
  countryCode date
);

CREATE TABLE ref_inventory (
  id serial primary key,
  modifiedAt bigint,
  email text,
  id timestamp,
  marketId geometry,
  headerImage varchar,
  claimId binary,
  country smallint,
  employeeId set,
  age smallint,
  ipAddress float,
  hashKey serial,
  jobTitle bit,
  clockIn time,
  thumbnail enum,
  earnedPoints point,
  accessLevel geometry,
  alertType date,
  minValue timestamp
);

CREATE TABLE tmp_organization_meta (
  id serial primary key,
  metaDescription double,
  username set,
  cloudId varchar,
  address int,
  sku text,
  gateId float,
  minLimit blob,
  orderId float,
  feedId time,
  creditScore decimal,
  customField2 float,
  bannerImage smallint,
  sessionId varchar,
  employeeId point,
  category serial,
  moveId enum
);

CREATE TABLE companyinfo (
  id serial primary key,
  orderStatus smallint,
  salary geometry,
  role enum,
  mainImage time,
  adminNotes time,
  gateId serial,
  lockoutEnd blob,
  longitude bigint,
  discountCode float,
  forwardTo float,
  maxLimit binary,
  name real,
  token mediumint,
  messageId float,
  chatId datetime,
  status bit,
  bookingDate serial,
  avatar binary,
  budgetCode datetime,
  likeCount blob,
  apiKey int
);

CREATE TABLE ver_config_type_v2 (
  id serial primary key,
  customerGroup point,
  hiddenAt time,
  avatar float,
  deviceId bigint,
  companyName mediumint,
  albumId text,
  flagged timestamp,
  defaultLang blob,
  completedAt double,
  minLimit text,
  distributorId geometry,
  homePhone blob,
  isEnabled smallint,
  courseId geometry,
  linkId boolean,
  businessType timestamp,
  type smallint,
  keywords time,
  referralCode datetime,
  isDeleted real,
  connectionString real
);

CREATE TABLE exttransaction (
  id serial primary key,
  algorithm real,
  mapId point,
  category timestamp,
  headerImage smallint,
  birthDate bigint,
  entryPoint float,
  state smallint
);

CREATE TABLE auditv1 (
  id serial primary key,
  orderStatus boolean,
  industryType bit,
  dataSource varchar,
  createdAt blob,
  companyName real,
  isHidden date,
  endPoint double
);

CREATE TABLE ver_transaction (
  id serial primary key,
  maritalStatus decimal,
  firmwareVersion serial,
  chatId geometry,
  deviceId boolean,
  languageCode enum,
  avatar varchar,
  lastSeenAt bigint,
  amount timestamp,
  floorNumber varchar,
  employeeCode smallint,
  gameId bigint,
  isHidden time,
  mainImage timestamp
);

CREATE TABLE src_order (
  id serial primary key,
  category date,
  maskType serial,
  chargeId smallint,
  referralCode geometry,
  createdAt point,
  countryCode mediumint,
  fontFamily double,
  iconPath datetime,
  marketId date,
  checkInTime timestamp,
  moveId point,
  grade datetime
);

CREATE TABLE ref_config (
  id serial primary key,
  mapId enum,
  creditScore date,
  createdAt double,
  gameId blob,
  dialCode tinyint,
  value double,
  orderStatus smallint,
  exchangeRate mediumint,
  connectionString set,
  homePhone smallint,
  courseId date,
  password set,
  languageCode boolean,
  thumbnail geometry,
  customerId smallint,
  meterNumber date
);

CREATE TABLE log_customer (
  id serial primary key,
  budgetCode boolean,
  actionType bit,
  listingId date,
  itemCount binary,
  taxRate blob,
  token int,
  marketId decimal,
  logLevel time,
  status mediumint,
  deliveryDate int,
  handlerId serial,
  forwardTo decimal,
  fileType enum,
  meterNumber geometry,
  username serial
);

CREATE TABLE payment (
  id serial primary key,
  locationId text,
  listingId double,
  currencyCode bigint,
  machineId text,
  managerId double,
  authMethod smallint,
  postalCode time,
  loginAttempts geometry,
  priority boolean,
  cardNumber timestamp,
  accountType mediumint,
  itemCount timestamp,
  bankAccount binary,
  hostName int,
  referralCode tinyint,
  claimId time,
  birthDate blob,
  guestId boolean,
  discount boolean,
  invoiceId datetime,
  longitude date,
  status real,
  customField1 varchar,
  maxLimit geometry,
  chatId boolean,
  firstName date,
  creditScore enum,
  entryPoint binary,
  deactivatedAt time,
  isActive geometry
);

CREATE TABLE inventory (
  id serial primary key,
  employmentDate serial,
  extractId point,
  domainName date,
  authToken point,
  customerId tinyint,
  currencyCode mediumint,
  logLevel datetime,
  createdAt date,
  companyName boolean,
  brandId tinyint,
  bankAccount boolean,
  algorithm geometry,
  billingCycle mediumint,
  friendId bigint,
  cityName date,
  title datetime,
  deviceToken datetime,
  checkInTime varchar,
  isActive geometry
);

CREATE TABLE stgproductv1 (
  id serial primary key,
  handlerId enum,
  endPoint text,
  houseNumber float,
  instructorId smallint,
  metaKeywords blob,
  folderPath smallint,
  accessLevel timestamp,
  status int,
  invoiceId point,
  incidentId smallint,
  emergencyContact enum,
  accountType set,
  cardNumber text,
  linkId double,
  age decimal,
  countryCode time,
  faxNumber time,
  extractId real,
  guestId text,
  description enum,
  couponCode timestamp
);

CREATE TABLE payment_new (
  id serial primary key,
  expiryYear timestamp,
  foregroundColor geometry,
  creditScore real,
  agentId text,
  id float,
  avatar set,
  cvv bit,
  costCenter tinyint,
  emergencyContact real,
  domainName tinyint,
  deviceId binary,
  instanceId tinyint,
  departmentCode blob,
  dimension set
);

CREATE TABLE olktransaction (
  id serial primary key,
  birthDate mediumint,
  cloudId set,
  apiVersion bit,
  phone varchar,
  clockOut datetime,
  employmentDate geometry,
  dependentId real,
  accessLevel binary,
  albumId serial,
  iconPath timestamp,
  labelText timestamp,
  metadata serial,
  childId set,
  clockIn enum,
  maritalStatus geometry,
  creditLimit date
);

CREATE TABLE productv2 (
  id serial primary key,
  buildNumber timestamp,
  firstName datetime,
  metaDescription mediumint,
  checkInTime float,
  longitude smallint,
  fontSize double,
  channelId serial,
  mainImage float,
  mapId enum,
  balance real,
  dimension real
);

CREATE TABLE record (
  id serial primary key,
  endDate float,
  isHidden varchar
);

CREATE TABLE stgcustomer (
  id serial primary key,
  duration int,
  indexKey enum,
  deactivatedAt real,
  avatar varchar,
  instructorId float
);

CREATE TABLE pub_inventory_new (
  id serial primary key,
  filterType blob,
  minValue bit,
  accessLevel decimal,
  forwardTo tinyint,
  balance smallint,
  fromDate decimal,
  alertType bigint,
  isDeleted bigint,
  comment text,
  languageCode date,
  integrationId blob,
  analyticsId boolean,
  address timestamp,
  group int,
  discountCode tinyint,
  locationId smallint,
  metaDescription point,
  middleName varchar,
  checkOutTime serial,
  blogId date,
  contactEmail boolean,
  companyName binary,
  expiryMonth tinyint
);

CREATE TABLE core_user (
  id serial primary key,
  comment varchar,
  dependentId varchar,
  salary boolean,
  addressLine2 bit,
  feedbackId point,
  chargeId decimal,
  keyId enum,
  password geometry
);

CREATE TABLE dim_payment_archive (
  id serial primary key,
  indexKey real,
  mimeType serial,
  globalId set,
  isRequired enum,
  checkInTime geometry,
  cloudId int,
  depositAmount binary,
  countryCode serial,
  insertedAt blob,
  actionType bit,
  copyRight set,
  metaTitle blob,
  chatId smallint,
  memberCount enum,
  moduleId date,
  brandId real
);

CREATE TABLE tmporganization (
  id serial primary key,
  favoriteCount decimal,
  department serial,
  extractId date,
  feedId bigint,
  exportId bit,
  deactivatedAt bigint,
  entityId mediumint,
  email varchar,
  username float,
  category mediumint,
  addressLine1 int,
  authToken smallint,
  joinDate smallint,
  country smallint,
  expiryDate datetime,
  lockoutEnd binary,
  isArchived set,
  address float,
  completionRate time,
  phone point,
  fileSize real,
  isDraft timestamp
);

CREATE TABLE audit (
  id serial primary key,
  rating serial,
  friendId binary,
  likeCount timestamp,
  employmentDate bigint,
  orderStatus geometry,
  deviceId bigint,
  invoiceId float,
  importId mediumint,
  lockoutEnd serial,
  courseId int,
  attemptCount binary,
  department text,
  customField1 enum,
  keywords timestamp,
  price real,
  id int,
  checkOutTime smallint,
  moduleId tinyint,
  totalAmount time,
  longitude text,
  middleName boolean,
  insuranceId bit,
  creditLimit decimal,
  balance serial,
  hashKey datetime,
  password set,
  ipAddress double,
  contractId smallint,
  companyLogo bit,
  dueDateAt int,
  clientId text
);

CREATE TABLE transaction_meta (
  id serial primary key,
  creditLimit decimal,
  tags boolean,
  cacheKey bigint,
  createdAt float,
  localeId varchar,
  alertType real,
  maxLimit varchar,
  mimeType tinyint,
  city text,
  fontSize int,
  name double,
  shippingAddress enum,
  unit timestamp,
  isRequired enum,
  companyId point
);

CREATE TABLE dst_organization (
  id serial primary key,
  meterNumber double,
  awardDate date,
  title boolean,
  creditScore blob,
  companyId bit
);

CREATE TABLE inventory (
  id serial primary key,
  isBillable timestamp,
  fromDate varchar,
  hashKey boolean,
  adminNotes decimal
);

