CREATE TABLE user (
  id serial primary key,
  fontSize serial,
  metadata date,
  authorId tinyint,
  birthDate tinyint
);

CREATE TABLE inventory_out (
  id serial primary key,
  keywords timestamp,
  downloadCount blob,
  businessType geometry,
  companyName smallint,
  contactPhone date,
  defaultValue point,
  id bit,
  maxLimit double,
  phone set,
  cardHolder date,
  category text,
  articleId geometry,
  contactName mediumint,
  cardNumber float,
  modifiedAt datetime,
  earnedPoints tinyint,
  isFeatured varchar,
  fileName tinyint,
  dataSource decimal,
  childId float,
  certificateId binary,
  countryCode smallint,
  customField1 binary
);

CREATE TABLE account_2024 (
  id serial primary key,
  metaTitle float,
  invoiceId double,
  username text,
  courseId blob,
  billingCycle timestamp,
  street smallint
);

CREATE TABLE transactiondiv (
  id serial primary key,
  password datetime,
  name binary,
  deactivatedAt mediumint,
  address date,
  industryType serial,
  batchId timestamp,
  isAdmin bit
);

CREATE TABLE organization (
  id serial primary key,
  referralCode varchar,
  fontFamily timestamp,
  height smallint,
  size varchar,
  contactEmail smallint,
  dueDateAt datetime,
  authMethod binary,
  comment bigint,
  category point,
  dimension enum,
  ipAddress timestamp,
  city timestamp,
  enrollmentDate enum,
  title binary,
  endDate decimal,
  geoLocation real,
  id float,
  emailStatus point,
  enabledAt bigint
);

CREATE TABLE inventory (
  id serial primary key,
  fileSize timestamp,
  blogId enum,
  instanceId bit,
  firmwareVersion float,
  ipAddress float,
  fromDate bigint,
  frameRate tinyint
);

CREATE TABLE paymentnotifications (
  id serial primary key,
  metadata date,
  bankAccount date,
  enrollmentDate enum,
  indexKey text,
  depositAmount serial,
  status varchar,
  dataSource boolean,
  customerGroup decimal,
  guestId enum,
  gender varchar,
  sessionId point,
  geoLocation decimal,
  faxNumber blob,
  coordinateX timestamp,
  postalCode decimal,
  signature text,
  sku blob,
  contentType set,
  defaultValue date,
  dialCode datetime,
  campaignId float
);

CREATE TABLE order_log (
  id serial primary key,
  companyLogo set,
  fontSize text,
  cacheKey datetime,
  invoiceId set,
  taxRate tinyint,
  password bigint
);

CREATE TABLE company_type (
  id serial primary key,
  authMethod varchar,
  defaultValue tinyint,
  fileType real,
  companyName boolean,
  currency mediumint,
  depositAmount datetime,
  discountCode time,
  taxRate real,
  deviceToken bit,
  countryCode float,
  height enum,
  childId decimal,
  homePhone decimal,
  sessionId smallint,
  foregroundColor date,
  bannerImage timestamp,
  guestId blob,
  isArchived bigint,
  dataSource geometry,
  createdAt binary,
  totalAmount decimal,
  postalCode datetime,
  fontSize bigint
);

CREATE TABLE organizationmeta (
  id serial primary key,
  amount set,
  isDefault tinyint,
  sessionId bigint,
  category float,
  metaKeywords varchar,
  comment smallint,
  cardNumber varchar,
  employeeCode int,
  editedAt bigint,
  contactEmail set,
  backupEmail boolean,
  enabledAt datetime,
  fileSize set,
  coordinateX set,
  latitude text,
  documentId date,
  dailyLimit smallint,
  gender int,
  dependentId decimal,
  campaignId real
);

CREATE TABLE tblcustomerseg (
  id serial primary key,
  floorNumber text,
  earnedPoints binary,
  maskType double,
  token varchar,
  houseNumber tinyint,
  domainName boolean,
  faxNumber float,
  flagged double,
  billingCycle binary,
  latitude double,
  handlerId boolean,
  iconPath mediumint,
  insuranceId bit,
  companyId binary,
  editedAt date
);

CREATE TABLE vw_payment_type (
  id serial primary key,
  email timestamp,
  updatedAt blob,
  linkId serial,
  middleName double,
  isPublic serial,
  driverLicense binary,
  locationId float,
  coordinateY blob,
  isAdmin smallint,
  meterNumber boolean,
  folderPath real,
  languageCode boolean,
  integrationId int,
  employeeCode text,
  amount double,
  createdAt point,
  address geometry
);

CREATE TABLE vwconfig (
  id serial primary key,
  street time,
  connectionString serial,
  uuid bigint,
  accountStatus binary,
  state text,
  isAdmin bigint,
  fontSize mediumint,
  buildNumber blob,
  marketId text,
  claimId decimal,
  agentId real,
  browserType date,
  nickname smallint,
  role smallint,
  memberCount geometry,
  errorMessage blob,
  hostName double,
  contractId smallint,
  insuranceId boolean,
  employmentDate bit,
  courseId date,
  productCode tinyint,
  billingFrequency int,
  cvv text,
  minLimit time,
  longitude datetime,
  indexKey int,
  cancelReason int,
  monthlyRate text,
  bluetoothId point,
  updatedAt decimal
);

CREATE TABLE config_type (
  id serial primary key,
  defaultLang varchar,
  customerId mediumint,
  forwardTo date,
  maxValue bigint,
  deactivatedAt bit,
  postalCode geometry,
  creditLimit varchar,
  entityId decimal,
  completedAt mediumint,
  expiryYear geometry,
  errorCode timestamp,
  address set,
  inactiveAt date,
  nickname bigint,
  duration decimal,
  longitude boolean,
  hiddenAt varchar,
  itemCount varchar
);

CREATE TABLE stgproductrel (
  id serial primary key,
  accessLevel boolean,
  discountCode real,
  maritalStatus set,
  addressLine2 datetime,
  industryType tinyint,
  ipAddress bigint,
  dateFormat mediumint,
  unit point,
  firstName bit,
  expiryMonth double,
  dialCode point,
  completedAt varchar,
  analyticsId geometry
);

CREATE TABLE record (
  id serial primary key,
  coverImage text,
  group varchar,
  updatedAt float,
  deactivatedAt smallint,
  batchId mediumint,
  documentId varchar,
  bankAccount decimal,
  latitude bit
);

CREATE TABLE transaction (
  id serial primary key,
  name enum,
  state smallint,
  address enum,
  labelText serial,
  ipAddress datetime,
  bannerImage mediumint,
  bankAccount timestamp,
  keywords blob,
  contactName blob,
  lastName smallint,
  companyName bigint,
  email binary,
  groupName decimal,
  entryPoint mediumint,
  cityName time,
  firstName boolean,
  deviceId double,
  analyticsId varchar,
  joinDate varchar,
  accessLevel serial,
  age varchar,
  completedAt float,
  totalAmount time
);

CREATE TABLE fact_product_2024 (
  id serial primary key,
  accountStatus double,
  avatar enum,
  cardHolder geometry,
  exportId datetime,
  thumbnail tinyint,
  batchId mediumint,
  status set,
  childId timestamp,
  bluetoothId varchar,
  actionType point,
  startDate real,
  deviceId geometry,
  emailStatus blob,
  isRequired bigint,
  eventDate bigint,
  description point,
  languageCode tinyint,
  maxValue text,
  modifiedAt float,
  latitude float,
  address serial,
  middleName point
);

CREATE TABLE audit (
  id serial primary key,
  languageCode smallint,
  fromDate bigint,
  referralCode timestamp,
  expiryYear varchar,
  coordinateX smallint,
  contactPhone geometry,
  emergencyContact enum
);

CREATE TABLE pub_user (
  id serial primary key,
  uuid text,
  gender timestamp,
  city date,
  mimeType serial,
  creditLimit real,
  costCenter boolean,
  deviceToken boolean,
  apiVersion tinyint,
  password binary,
  dependentId boolean,
  campaignId mediumint
);

CREATE TABLE transaction_data (
  id serial primary key,
  taxRate time,
  id text,
  deliveryDate enum,
  createdAt int,
  contactName smallint,
  clockOut smallint,
  metaKeywords real,
  coverImage time,
  shippingAddress datetime,
  floorNumber float
);

CREATE TABLE sys_product (
  id serial primary key,
  attemptCount bigint,
  nickname int,
  deletedAt decimal,
  customerId mediumint,
  accountType tinyint,
  lastName varchar,
  defaultLang varchar,
  enabledAt datetime,
  rating serial,
  middleName serial,
  isEnabled binary,
  creditLimit blob,
  cloudId geometry,
  code float,
  analyticsId blob,
  currencyCode smallint,
  cardNumber mediumint,
  abandonedCartId tinyint,
  comment point,
  cacheKey time,
  courseId tinyint,
  labelText real,
  locationId binary,
  longitude time,
  isHidden timestamp,
  uuid tinyint
);

CREATE TABLE cpy_payment (
  id serial primary key,
  dealerId geometry,
  timezone varchar,
  height timestamp,
  rating text,
  duration enum,
  emailStatus tinyint,
  checkInTime point,
  floorNumber text,
  fileHash datetime,
  claimId blob,
  password time,
  homePhone tinyint,
  formatType real,
  geoLocation smallint,
  middleName bigint
);

CREATE TABLE audit_info_temp (
  id serial primary key,
  industryType date,
  coordinateY float,
  clockIn double,
  copyRight set,
  accountType binary,
  state float,
  moduleId boolean,
  metaKeywords point,
  merchantId boolean,
  accessLevel point,
  startDate smallint,
  bankAccount binary,
  token boolean,
  departmentCode geometry
);

CREATE TABLE src_transaction (
  id serial primary key,
  referralCode set,
  isLocked bit,
  ipAddress binary,
  category bigint,
  endPoint text,
  domainName binary,
  validUntil decimal,
  phone smallint,
  actionType tinyint,
  hiddenAt bigint,
  certificateId varchar,
  amount date,
  buildNumber blob,
  isRequired datetime,
  authMethod decimal,
  signature datetime
);

CREATE TABLE src_audit (
  id serial primary key,
  address date,
  balance int,
  customField2 mediumint,
  insertedAt datetime,
  localeId text,
  metaKeywords set,
  fingerprint float,
  meterNumber double,
  taxRate float,
  fontSize serial,
  authorId tinyint,
  clientId text,
  createdAt bigint,
  audioUrl set,
  discount text,
  completedAt date,
  description enum,
  depositAmount set,
  discountCode decimal,
  iconPath bigint,
  addressLine2 boolean,
  deliveryDate point,
  coverImage time,
  dealerId enum,
  latitude time,
  configId date,
  extractId date,
  defaultLang varchar
);

CREATE TABLE dst_transaction (
  id serial primary key,
  employeeCode int,
  longitude binary,
  state geometry,
  latitude boolean,
  grade text,
  iconPath bigint,
  cardNumber real,
  instanceId set,
  updatedAt varchar,
  dependentId serial,
  hourlyRate decimal,
  faxNumber bit,
  size float,
  isRequired timestamp,
  enrollmentDate timestamp,
  name enum,
  ipAddress float,
  eventDate varchar,
  referralCode blob,
  childId geometry,
  paymentMethod real,
  duration text,
  houseNumber point,
  hiddenAt bigint,
  code boolean,
  isBillable set,
  maritalStatus decimal,
  email datetime
);

CREATE TABLE pubinventorytemp (
  id serial primary key,
  weight point,
  labelText timestamp,
  geoLocation tinyint,
  claimId blob,
  comment geometry,
  listId serial,
  priority time,
  title point,
  code real,
  id mediumint,
  token boolean,
  channelId mediumint,
  shippingAddress text,
  gameId date,
  cartId decimal,
  taxRate mediumint,
  monthlyRate geometry,
  errorMessage mediumint,
  courseId serial,
  mimeType text,
  logLevel boolean,
  email point,
  couponCode set,
  levelId timestamp,
  coverImage smallint,
  inactiveAt float,
  buildNumber text,
  address timestamp,
  ipAddress text
);

CREATE TABLE factpayment (
  id serial primary key,
  clockIn tinyint,
  hostName bit,
  coverImage smallint,
  isVerified timestamp,
  foregroundColor bit,
  dateFormat text,
  jobTitle binary,
  bankAccount text,
  title bigint,
  employmentDate blob,
  isBillable date,
  likeCount serial,
  description tinyint,
  businessType serial,
  colorCode bit,
  billingFrequency blob,
  brandId timestamp,
  status decimal,
  price timestamp,
  cvv double,
  joinDate timestamp,
  clientId decimal,
  group geometry,
  customField1 mediumint,
  productCode int,
  companyLogo binary,
  comment time,
  cacheKey time
);

CREATE TABLE customer_legacy (
  id serial primary key,
  customerId smallint,
  mimeType binary,
  keyId blob,
  token binary,
  tags mediumint,
  appVersion geometry,
  levelId boolean,
  cloudId geometry,
  departmentCode tinyint,
  hashKey geometry,
  bannerImage binary,
  companyId int,
  version double,
  formatType bigint,
  postalCode varchar,
  listId float,
  feedId varchar,
  abandonedCartId float,
  isDeleted date,
  importId blob
);

CREATE TABLE config_out (
  id serial primary key,
  insuranceId timestamp,
  cardNumber set,
  employeeId double,
  importId set,
  metaTitle enum,
  checkInTime tinyint,
  age double,
  couponCode binary
);

CREATE TABLE fact_payment (
  id serial primary key,
  age blob,
  isDefault int,
  hostName boolean,
  inactiveAt varchar,
  productCode tinyint,
  thumbnail real,
  errorCode text,
  authMethod binary,
  friendId timestamp,
  fileName real,
  createdAt decimal,
  favoriteCount bit,
  contactPhone mediumint,
  childId date,
  score int,
  feedbackId double,
  messageId time,
  sessionId bigint,
  actionType time
);

CREATE TABLE src_company_rel (
  id serial primary key,
  copyRight decimal,
  itemCount binary,
  createdAt boolean,
  content bit,
  authMethod tinyint
);

CREATE TABLE tmp_record (
  id serial primary key,
  channelId timestamp,
  locationId tinyint,
  completedAt bigint,
  browserType smallint,
  city datetime
);

CREATE TABLE app_organization (
  id serial primary key,
  isRequired date,
  coverImage int,
  audioUrl int,
  loginCount mediumint,
  cardNumber smallint,
  title boolean,
  unit geometry,
  country varchar,
  downloadCount tinyint,
  sku set,
  dailyLimit datetime,
  analyticsId set,
  avatar serial,
  completionRate int,
  headerImage date
);

CREATE TABLE srccompany (
  id serial primary key,
  billingFrequency blob,
  layerId text,
  state bigint,
  configId decimal,
  deviceToken bigint,
  geoLocation blob,
  fontFamily int,
  currency mediumint,
  status time,
  education int,
  startDate smallint,
  latitude real,
  ipAddress int,
  exportId bigint,
  jobTitle bit,
  buildNumber float,
  category bigint,
  languageCode text
);

CREATE TABLE record_new (
  id serial primary key,
  currencyCode double,
  username set
);

CREATE TABLE organizationdata (
  id serial primary key,
  dimension timestamp,
  isActive int,
  bannerImage binary,
  phone real,
  description int,
  campaignId text,
  deviceToken enum,
  driverLicense geometry,
  totalAmount double,
  isDeleted double,
  cardNumber point,
  metadata datetime,
  importId int,
  extractId real,
  guestId real,
  merchantId smallint,
  exportId set,
  minLimit int,
  size decimal,
  entityId enum,
  createdAt point,
  companyName serial
);

CREATE TABLE inventory_temp (
  id serial primary key,
  cityName geometry,
  priority text,
  hashKey real,
  languageCode bigint,
  startDate mediumint,
  metaTitle binary,
  orderStatus enum,
  grade date,
  flagged serial,
  totalAmount time,
  signature binary,
  paymentMethod decimal,
  description double,
  exchangeRate double,
  accountNumber timestamp,
  street set,
  batchId point,
  nickname float
);

CREATE TABLE olkpayment (
  id serial primary key,
  apiVersion set,
  completedAt int,
  name bit,
  type tinyint,
  houseNumber enum,
  agentId blob,
  dealerId timestamp,
  cancelReason serial,
  managerId real,
  isActive binary,
  balance text,
  dashboardId blob,
  errorMessage date,
  accessLevel float,
  locationId decimal,
  memberCount bigint,
  fingerprint serial,
  street geometry,
  dueDateAt time,
  orderId smallint,
  followCount real,
  contactPhone set,
  cartId binary,
  batchId int
);

CREATE TABLE fact_organization (
  id serial primary key,
  amount boolean,
  fromDate datetime,
  listingId real,
  clientId varchar,
  forwardTo bigint,
  metaDescription enum,
  productCode bigint,
  insertedAt serial,
  blogId float,
  distributorId varchar,
  description blob,
  actionType text,
  chargeId binary,
  isFeatured serial,
  floorNumber text,
  brandId tinyint,
  firstName enum,
  bookingDate enum,
  tags date,
  isArchived decimal,
  checkInTime smallint,
  hourlyRate int,
  minValue decimal,
  cardHolder mediumint,
  comment mediumint,
  currencyCode datetime,
  feedbackId set,
  accountType smallint,
  facilityId double,
  costCenter tinyint,
  deviceId tinyint
);

CREATE TABLE transaction (
  id serial primary key,
  coverImage decimal,
  endDate bit,
  layerId bigint,
  connectionString real,
  tags boolean,
  itemCount timestamp
);

CREATE TABLE dim_audit_temp (
  id serial primary key,
  chatId time,
  instructorId time,
  nickname point,
  isRequired decimal,
  clientId enum,
  errorMessage float,
  signature bit,
  businessType decimal,
  age mediumint,
  certificateId tinyint,
  employeeId serial,
  maxValue point,
  flagged bit,
  clockIn binary,
  fileHash boolean,
  role varchar,
  endPoint geometry,
  fontSize enum,
  priority serial,
  albumId blob,
  marketId text,
  entityId int,
  contractId bit,
  floorNumber date,
  expiryMonth mediumint,
  couponCode text,
  dialCode mediumint,
  comment datetime,
  id date,
  contactEmail binary
);

CREATE TABLE sys_record (
  id serial primary key,
  chargeId int,
  type varchar,
  coordinateX datetime,
  indexKey float,
  moveId real,
  marketId float,
  discount float,
  age date,
  timezone datetime,
  errorMessage decimal,
  balance point,
  algorithm time,
  logLevel time,
  avatar date,
  exportId smallint
);

CREATE TABLE user (
  id serial primary key,
  companyId enum,
  isEnabled smallint,
  languageCode boolean,
  nickname datetime,
  bluetoothId text,
  description real,
  dataSource blob,
  isDeleted serial,
  shippingAddress varchar,
  value datetime,
  blogId bit,
  group smallint,
  category int,
  code binary,
  levelId timestamp,
  quantity text,
  faxNumber boolean,
  avatar datetime,
  currencyCode blob,
  globalId enum,
  lockoutEnd date,
  role text,
  geoLocation text,
  orderStatus binary
);

CREATE TABLE fact_order_div (
  id serial primary key,
  keywords serial,
  metaKeywords int,
  authorId bit,
  feedId double
);

CREATE TABLE coreorganization (
  id serial primary key,
  editedAt binary,
  linkId bit,
  locationId bit,
  dependentId varchar,
  password mediumint,
  chargeId mediumint,
  defaultValue binary,
  foregroundColor bit,
  loginAttempts text,
  layerId set,
  ipAddress text,
  updatedAt varchar,
  macAddress text,
  duration int,
  tags real,
  albumId geometry,
  clockOut blob,
  createdAt int,
  gameId timestamp,
  name varchar,
  lastLoginAt real,
  displayName enum,
  postalCode enum,
  alertType blob,
  balance boolean,
  departmentCode tinyint,
  dateFormat smallint
);

CREATE TABLE cpy_transaction_seg (
  id serial primary key,
  password varchar,
  defaultValue bit,
  isDeleted int,
  token serial,
  totalAmount bit,
  latitude point,
  insuranceId serial,
  ipAddress bigint,
  coverImage real,
  filterType double,
  state blob,
  expiryYear time,
  startDate bigint,
  minLimit varchar,
  avatar geometry,
  status point,
  exchangeRate text,
  isArchived serial,
  score date,
  maxValue int,
  claimId float
);

CREATE TABLE organization_temp (
  id serial primary key,
  deactivatedAt double,
  manufacturerId smallint,
  mimeType float,
  localeId smallint,
  authorId datetime,
  modifiedAt int,
  country set,
  firmwareVersion enum,
  fromDate geometry,
  balance text,
  category smallint
);

CREATE TABLE audit (
  id serial primary key,
  awardDate mediumint,
  mapId time
);

