CREATE TABLE paymentdiv (
  id serial primary key,
  dialCode float,
  connectionString blob,
  gateId datetime,
  isDeleted varchar,
  houseNumber serial,
  contactName text,
  attachmentUrl datetime,
  buildNumber datetime,
  mobileNumber timestamp,
  keywords binary,
  type boolean,
  eventDate tinyint,
  addressLine2 smallint,
  importId point,
  hourlyRate decimal,
  depositAmount smallint,
  latitude datetime,
  paymentMethod varchar,
  lastLoginAt datetime,
  lastSeenAt mediumint,
  priority geometry,
  isHidden float,
  category date,
  certificateId tinyint,
  insuranceId date,
  bannerImage boolean,
  hashKey int,
  courseId geometry
);

CREATE TABLE user_meta_v1 (
  id serial primary key,
  geoLocation time,
  alertType bit,
  filterType smallint,
  endDate enum,
  isArchived set,
  weight real,
  manufacturerId datetime,
  depositAmount serial,
  middleName datetime,
  title float,
  city geometry,
  domainName binary,
  maskType float,
  fileHash tinyint,
  comment binary,
  lastName time,
  tags binary
);

CREATE TABLE tblorderinfo (
  id serial primary key,
  fontSize smallint,
  isFeatured binary,
  isLocked double,
  insuranceId timestamp,
  createdAt int,
  followCount smallint,
  checkOutTime set,
  dialCode set,
  apiVersion varchar,
  isEnabled serial,
  albumId binary,
  billingCycle blob,
  managerId serial,
  weight point,
  hiddenAt blob,
  cartId timestamp,
  displayOrder enum,
  role bigint,
  coordinateX enum,
  rating text,
  blogId date,
  feedbackId real,
  salary timestamp,
  isRequired real,
  isBillable binary,
  referralCode binary,
  integrationId geometry
);

CREATE TABLE organization (
  id serial primary key,
  companyId binary,
  accountType boolean,
  brandId set,
  id varchar,
  fontFamily time,
  cancelReason binary,
  bluetoothId double
);

CREATE TABLE product (
  id serial primary key,
  groupName decimal,
  documentId datetime
);

CREATE TABLE fact_inventory_info (
  id serial primary key,
  ipAddress double,
  addressLine2 point,
  browserType smallint,
  mimeType int,
  avatar real,
  password blob,
  priority tinyint,
  category date,
  type geometry,
  earnedPoints set,
  bookingDate text,
  minValue tinyint,
  accessLevel decimal,
  isHidden real,
  feedId binary,
  phone real,
  orderId int,
  labelText boolean,
  expiryMonth float
);

CREATE TABLE rel_payment (
  id serial primary key,
  activeDevices timestamp,
  dependentId timestamp,
  maxValue tinyint,
  appVersion blob,
  height bit,
  guestId timestamp,
  eventDate point,
  gender point,
  addressLine2 int,
  macAddress date,
  industryType tinyint,
  facilityId mediumint
);

CREATE TABLE dimconfigextra (
  id serial primary key,
  isActive point,
  customerId binary,
  longitude bigint,
  group smallint,
  fromDate geometry,
  abandonedCartId tinyint,
  deviceType geometry,
  friendId varchar,
  token serial,
  accountType date,
  depositAmount datetime,
  licenseKey enum,
  isAdmin date,
  discount timestamp,
  bankAccount enum,
  height varchar,
  balance decimal,
  algorithm decimal,
  coordinateX bigint,
  machineId tinyint,
  accessLevel binary,
  hashKey varchar,
  gateId boolean,
  jobTitle geometry
);

CREATE TABLE audit_log (
  id serial primary key,
  employeeCode serial,
  cvv bit,
  errorMessage text,
  lastName real,
  forwardTo smallint,
  isArchived time,
  currency enum,
  discountCode point,
  billingCycle timestamp,
  distributorId serial,
  fileName point,
  integrationId point,
  comment date,
  deviceType boolean,
  awardDate mediumint,
  createdAt bigint,
  tags serial,
  accountType real
);

CREATE TABLE src_transaction (
  id serial primary key,
  content point,
  fontSize text,
  entityId binary,
  creditScore point,
  labelText bigint
);

CREATE TABLE fact_user (
  id serial primary key,
  colorCode time,
  avatar geometry,
  accountNumber datetime,
  floorNumber tinyint,
  fontFamily mediumint,
  articleId decimal,
  layerId varchar,
  facilityId float,
  likeCount varchar,
  grade binary,
  cardHolder double,
  maxValue blob,
  hourlyRate float,
  isPublic datetime,
  validUntil bit,
  name int,
  weight timestamp,
  feedId bit,
  batchId smallint,
  integrationId point,
  insuranceId datetime,
  itemCount int
);

CREATE TABLE pub_company (
  id serial primary key,
  contactEmail datetime,
  completedAt real,
  metaTitle decimal,
  downloadCount int,
  endDate bigint,
  insuranceId decimal,
  chargeId mediumint,
  description bit,
  dealerId blob,
  frameRate set
);

CREATE TABLE productinfo (
  id serial primary key,
  headerImage boolean,
  importId timestamp,
  exchangeRate mediumint,
  apiVersion timestamp,
  backupEmail time,
  deletedAt serial,
  deviceToken datetime,
  costCenter text,
  customerGroup binary,
  chatId datetime,
  authMethod smallint,
  coordinateX tinyint,
  groupName timestamp,
  amount varchar,
  companyLogo varchar,
  billingFrequency text,
  postalCode varchar,
  unit bigint,
  checkOutTime enum,
  avatar float,
  duration decimal,
  maritalStatus boolean,
  nickname blob,
  isDraft smallint,
  department smallint,
  forwardTo time,
  dailyLimit datetime
);

CREATE TABLE cpyinventory (
  id serial primary key,
  lockoutEnd enum,
  email smallint
);

CREATE TABLE fact_config (
  id serial primary key,
  tags smallint,
  manufacturerId date,
  brandId timestamp,
  avatar boolean,
  authMethod bigint,
  education tinyint,
  campaignId timestamp,
  balance point
);

CREATE TABLE vwcustomer (
  id serial primary key,
  certificateId text,
  dealerId blob,
  followCount geometry,
  createdAt boolean,
  fileSize bigint,
  metaTitle tinyint,
  status float,
  weight bigint,
  faxNumber set,
  attachmentUrl tinyint,
  avatar serial,
  gender bigint,
  companyId text,
  fileType smallint,
  folderPath date,
  driverLicense real,
  facilityId date,
  contactPhone int,
  handlerId smallint,
  floorNumber float,
  authMethod double,
  coordinateY bigint,
  hostName set,
  isEnabled decimal,
  managerId geometry,
  connectionString date,
  isDraft bigint,
  cartId decimal,
  name blob,
  defaultValue double
);

CREATE TABLE audit_data (
  id serial primary key,
  batchId double,
  instanceId binary,
  email bit,
  shippingAddress time,
  documentId geometry,
  postalCode text,
  clientId tinyint,
  maritalStatus real,
  chatId point,
  houseNumber datetime,
  sessionId varchar,
  expiryDate geometry,
  creditCard decimal,
  appVersion geometry,
  extractId blob,
  articleId point,
  employeeId mediumint,
  bluetoothId bigint,
  companyLogo set
);

CREATE TABLE company_new (
  id serial primary key,
  gateId text,
  defaultValue tinyint,
  updatedAt int,
  accountType mediumint,
  hashKey real,
  contactEmail bigint,
  extractId enum,
  password date,
  copyRight tinyint,
  quantity timestamp,
  lastLoginAt point,
  token decimal,
  completedAt tinyint,
  category blob,
  creditLimit real,
  validUntil point,
  clientId binary,
  blogId point,
  accountNumber bit,
  displayOrder blob,
  cancelReason double,
  layerId datetime,
  formatType timestamp,
  bluetoothId decimal
);

CREATE TABLE sys_payment_extra (
  id serial primary key,
  id datetime,
  actionType real,
  adminNotes blob,
  buildNumber boolean,
  comment smallint,
  driverLicense double,
  lastLoginAt varchar,
  discountCode bigint,
  firmwareVersion decimal,
  favoriteCount binary,
  dialCode point,
  companyId enum,
  fingerprint binary,
  likeCount set,
  importId float
);

CREATE TABLE tmpcustomer (
  id serial primary key,
  layerId point,
  levelId mediumint,
  token enum,
  entityId timestamp,
  dueDateAt enum,
  adminNotes set,
  comment int,
  hiddenAt decimal
);

CREATE TABLE organizationdatav2 (
  id serial primary key,
  departmentCode timestamp,
  contactEmail boolean,
  billingFrequency serial,
  domainName smallint,
  marketId bigint,
  middleName bigint,
  colorCode decimal
);

CREATE TABLE stgconfig (
  id serial primary key,
  isDefault time,
  fontSize double,
  messageId date,
  password real,
  expiryDate mediumint,
  address set,
  comment set,
  moduleId bit,
  entryPoint smallint,
  value mediumint,
  employmentDate bigint,
  maskType bigint,
  postalCode mediumint,
  inactiveAt geometry,
  accessLevel decimal,
  description datetime,
  department set,
  orderStatus int,
  category enum,
  username geometry,
  mobileNumber real,
  deviceToken date,
  formatType int,
  gameId varchar,
  chargeId datetime,
  bluetoothId mediumint
);

CREATE TABLE tbl_account (
  id serial primary key,
  indexKey time,
  comment tinyint,
  moveId tinyint,
  articleId date,
  balance bit,
  enrollmentDate bit,
  hourlyRate real,
  lastLoginAt varchar,
  email enum,
  copyRight real,
  phone date,
  contentType float,
  errorMessage geometry,
  managerId blob,
  clockOut timestamp,
  status set,
  geoLocation boolean,
  depositAmount binary,
  city point,
  metaKeywords time,
  listId bigint,
  quantity text,
  globalId set,
  keywords timestamp
);

CREATE TABLE tmprecordtemp (
  id serial primary key,
  billingFrequency datetime,
  lastSeenAt timestamp,
  isVerified double,
  licenseKey date,
  languageCode int,
  longitude int,
  password mediumint,
  errorCode decimal,
  configId tinyint,
  campaignId int,
  batchId bit,
  frameRate mediumint,
  messageId varchar,
  blogId decimal,
  maritalStatus float,
  unit enum,
  zipCode text,
  downloadCount tinyint
);

CREATE TABLE tmp_account_v1 (
  id serial primary key,
  exportId blob,
  ipAddress tinyint,
  firstName mediumint,
  createdAt date,
  customField2 smallint,
  couponCode datetime,
  mainImage smallint,
  birthDate varchar,
  mimeType boolean,
  companyLogo datetime,
  sku varchar,
  phone enum,
  lockoutEnd varchar,
  unit point,
  fingerprint enum,
  discountCode blob,
  displayName date,
  faxNumber varchar,
  browserType boolean,
  brandId time,
  errorCode binary
);

CREATE TABLE tmp_product_new (
  id serial primary key,
  clientId time,
  clockOut tinyint,
  checkOutTime bigint,
  eventDate real,
  chargeId smallint,
  channelId datetime,
  keyId float,
  guestId varchar,
  bannerImage set
);

CREATE TABLE core_config (
  id serial primary key,
  metaDescription date,
  geoLocation bit,
  mobileNumber set,
  longitude int,
  avatar float,
  feedId int,
  claimId datetime,
  moveId text,
  integrationId point,
  articleId blob,
  emailStatus geometry,
  isBillable mediumint,
  documentId int,
  enrollmentDate float,
  actionType point,
  status datetime,
  apiVersion decimal,
  instanceId smallint
);

CREATE TABLE payment_info (
  id serial primary key,
  amount boolean,
  balance float,
  longitude datetime,
  addressLine2 text,
  comment blob,
  jobTitle tinyint,
  currency double,
  isActive text,
  attemptCount decimal,
  category decimal,
  rating enum,
  cancelReason real,
  expiryYear double,
  dialCode date,
  addressLine1 float,
  hourlyRate blob,
  quantity geometry,
  guestId tinyint,
  alertType int,
  orderId geometry,
  brandId tinyint
);

CREATE TABLE productarchivelegacy (
  id serial primary key,
  metaKeywords geometry,
  itemCount time,
  gender binary,
  address boolean,
  contactEmail double,
  creditLimit real,
  id bigint
);

CREATE TABLE order_legacy (
  id serial primary key,
  addressLine1 point,
  billingCycle smallint,
  isLocked timestamp,
  timezone datetime,
  apiKey blob,
  avatar bit,
  createdAt geometry,
  localeId varchar,
  contractId real,
  longitude double,
  name mediumint,
  category real,
  street float,
  birthDate tinyint,
  houseNumber smallint,
  score smallint,
  brandId decimal,
  cancelReason decimal,
  documentId point,
  albumId decimal,
  customField2 int,
  loginAttempts binary
);

CREATE TABLE log_product (
  id serial primary key,
  groupName text,
  amount text,
  unit int,
  lastName boolean,
  accountNumber int
);

CREATE TABLE diminventory (
  id serial primary key,
  department float,
  customerId set,
  group time,
  instructorId enum,
  eventDate smallint,
  role tinyint,
  ipAddress bit,
  fileName date,
  businessType date,
  marketId set,
  errorMessage float,
  entityId timestamp,
  middleName int,
  expiryDate serial,
  uuid double,
  rating smallint,
  isArchived int,
  audioUrl blob,
  earnedPoints varchar,
  comment datetime,
  id binary,
  dialCode int,
  levelId tinyint,
  insertedAt datetime,
  cartId smallint,
  contactName float,
  insuranceId smallint,
  countryCode real,
  height enum
);

CREATE TABLE transaction_seg (
  id serial primary key,
  certificateId binary,
  batchId geometry,
  fontSize blob,
  completedAt decimal,
  campaignId blob,
  lastSeenAt varchar,
  score decimal,
  endPoint blob,
  metaDescription boolean,
  minValue serial,
  dateFormat blob,
  licenseKey blob,
  businessType smallint,
  updatedAt int,
  coordinateX datetime,
  isVerified datetime
);

CREATE TABLE organization (
  id serial primary key,
  discount point,
  friendId timestamp,
  localeId serial,
  gender text,
  isSystem serial,
  companyName int,
  albumId timestamp,
  isLocked timestamp,
  fingerprint varchar,
  colorCode varchar,
  feedId datetime,
  phone serial,
  loginCount set,
  comment timestamp,
  unit int,
  grade point,
  cancelReason smallint,
  isDraft varchar,
  entityId float,
  validUntil enum,
  deviceId binary,
  state double,
  inactiveAt serial,
  homePhone double,
  group text,
  clientId smallint,
  exchangeRate boolean,
  deactivatedAt bit,
  driverLicense enum,
  childId float
);

CREATE TABLE inventory_seg_v1 (
  id serial primary key,
  managerId date,
  isDeleted datetime,
  brandId bigint,
  hiddenAt double,
  loginAttempts timestamp,
  fileType int,
  blogId decimal
);

CREATE TABLE config (
  id serial primary key,
  avatar smallint,
  duration tinyint,
  managerId mediumint,
  updatedAt datetime,
  iconPath tinyint,
  campaignId bigint,
  address smallint
);

CREATE TABLE order_v2 (
  id serial primary key,
  isArchived float,
  incidentId real,
  firstName int,
  price timestamp,
  dimension serial,
  countryCode bit,
  email datetime
);

CREATE TABLE companyrel (
  id serial primary key,
  instanceId bigint,
  dependentId datetime,
  driverLicense enum,
  displayName date,
  hourlyRate text,
  configId enum,
  companyName datetime,
  fileType boolean,
  password binary,
  city timestamp,
  emailStatus real,
  cacheKey geometry,
  maxValue bigint,
  gateId geometry,
  courseId point,
  labelText serial,
  fingerprint enum,
  errorMessage point,
  avatar binary,
  email mediumint,
  editedAt serial,
  isSystem varchar,
  authToken binary,
  salary decimal,
  isBillable double,
  clientId mediumint,
  accountType boolean,
  accountNumber set
);

CREATE TABLE payment (
  id serial primary key,
  machineId date,
  age time,
  accountNumber bigint,
  cartId set,
  companyName set,
  forwardTo float,
  blogId serial,
  entryPoint datetime,
  indexKey tinyint,
  budgetCode decimal,
  formatType real,
  dueDateAt date,
  minValue mediumint
);

CREATE TABLE refcustomerstatusv1 (
  id serial primary key,
  longitude blob,
  copyRight tinyint,
  browserType date,
  exchangeRate int,
  loginAttempts boolean,
  contentType mediumint,
  brandId set,
  labelText float,
  content tinyint,
  username timestamp,
  companyName varchar,
  balance bigint,
  addressLine1 set,
  isArchived tinyint,
  createdAt varchar,
  address datetime,
  moduleId double,
  category decimal,
  title blob,
  costCenter timestamp
);

CREATE TABLE payment (
  id serial primary key,
  orderId date,
  channelId bit,
  logLevel datetime,
  companyLogo time,
  claimId smallint,
  itemCount time,
  avatar float,
  category geometry,
  earnedPoints bit,
  emergencyContact geometry,
  bookingDate boolean,
  minLimit set,
  status double
);

CREATE TABLE account_type (
  id serial primary key,
  balance blob,
  dimension text,
  menuId bit,
  copyRight smallint,
  comment float,
  sessionId smallint,
  expiryMonth point,
  weight tinyint,
  blogId bit,
  firmwareVersion smallint,
  completionRate tinyint,
  creditScore double,
  chargeId time,
  duration decimal,
  displayOrder varchar,
  group bit,
  code float,
  filterType serial,
  avatar timestamp,
  token real
);

CREATE TABLE organization (
  id serial primary key,
  countryCode tinyint,
  deviceId point,
  amount smallint,
  filterType decimal,
  maskType varchar,
  browserType double,
  cloudId double,
  deletedAt tinyint,
  contactEmail time,
  rating set,
  checkInTime time,
  billingCycle timestamp,
  comment bigint,
  dateFormat boolean,
  coordinateX boolean,
  id text
);

CREATE TABLE core_payment_new (
  id serial primary key,
  itemCount bigint,
  longitude float,
  maritalStatus blob,
  adminNotes datetime,
  completedAt geometry,
  gateId geometry,
  deactivatedAt mediumint,
  deviceType text,
  billingFrequency datetime,
  metaTitle double,
  listingId time,
  metadata float,
  dateFormat mediumint,
  metaDescription boolean,
  addressLine2 real,
  contactPhone bigint,
  weight binary,
  birthDate real,
  education bigint,
  orderStatus serial,
  isVerified float,
  thumbnail decimal,
  creditCard time,
  entityId real,
  latitude varchar,
  customField2 enum,
  address time
);

CREATE TABLE transactionnew (
  id serial primary key,
  feedId date,
  isSystem tinyint,
  group double,
  category bigint,
  exchangeRate smallint,
  businessType int,
  channelId double,
  isDeleted timestamp,
  instanceId datetime,
  friendId boolean,
  token double,
  merchantId bit,
  followCount decimal,
  errorMessage enum,
  amount binary,
  state enum,
  status bit,
  accessLevel time,
  priority blob,
  billingCycle datetime,
  flagged time,
  dialCode mediumint,
  displayOrder binary
);

CREATE TABLE transaction2024 (
  id serial primary key,
  coordinateX enum,
  latitude text,
  layerId bigint,
  incidentId set,
  domainName boolean,
  addressLine1 real,
  keyId int,
  zipCode time,
  alertType decimal,
  insuranceId date,
  merchantId bit,
  appVersion blob,
  contactEmail double,
  updatedAt double,
  state point,
  postalCode enum,
  bannerImage decimal,
  contentType decimal,
  clockOut real,
  type decimal,
  downloadCount boolean,
  deliveryDate smallint
);

CREATE TABLE loguser (
  id serial primary key,
  department datetime,
  emergencyContact boolean,
  creditCard decimal,
  formatType mediumint,
  signature smallint,
  birthDate bit,
  accountNumber date,
  mimeType mediumint,
  country decimal,
  taxRate binary,
  algorithm mediumint,
  grade geometry,
  creditLimit serial,
  loginCount decimal,
  fileHash timestamp,
  connectionString real
);

CREATE TABLE dst_company (
  id serial primary key,
  folderPath real,
  education real,
  creditLimit binary,
  managerId real
);

CREATE TABLE priv_company (
  id serial primary key,
  feedbackId date,
  keyId serial,
  folderPath double,
  isEnabled text,
  dashboardId enum,
  filterType mediumint,
  employmentDate float,
  distributorId float,
  claimId float,
  iconPath mediumint,
  fileName bit,
  domainName tinyint,
  deviceId bigint,
  category int,
  education date,
  globalId mediumint,
  foregroundColor tinyint,
  ipAddress enum,
  errorCode smallint,
  avatar tinyint,
  orderStatus tinyint,
  alertType text,
  lockoutEnd bigint,
  budgetCode decimal
);

CREATE TABLE stg_account_data_v2 (
  id serial primary key,
  flagged bit,
  duration time,
  description varchar,
  token varchar,
  folderPath float,
  followCount set,
  isPublic datetime
);

