CREATE TABLE ver_payment (
  id serial primary key,
  budgetCode set,
  comment serial,
  driverLicense set,
  cloudId tinyint,
  levelId text,
  addressLine2 boolean,
  endDate bit,
  moduleId datetime,
  employeeCode datetime,
  token time,
  companyId set,
  isActive datetime,
  expiryDate geometry,
  coordinateX double,
  geoLocation set,
  orderStatus int,
  loginCount binary,
  feedbackId binary,
  priority real,
  displayName int,
  validUntil date,
  couponCode enum,
  cancelReason serial
);

CREATE TABLE olk_user (
  id serial primary key,
  mainImage decimal,
  contactName boolean,
  languageCode mediumint,
  name float,
  isActive tinyint,
  errorCode float,
  appVersion real,
  maskType mediumint,
  levelId double,
  state geometry,
  cartId boolean,
  fingerprint bigint,
  licenseKey time
);

CREATE TABLE cpy_record (
  id serial primary key,
  priority point,
  maskType binary,
  minValue real,
  dealerId point,
  mainImage enum,
  isLocked datetime,
  title mediumint,
  cardNumber binary,
  tags bigint,
  hourlyRate real,
  companyName date,
  email bigint,
  monthlyRate float,
  dialCode time,
  browserType text,
  hiddenAt point,
  homePhone bigint,
  bankAccount point,
  name mediumint,
  group decimal,
  amount int
);

CREATE TABLE payment (
  id serial primary key,
  avatar enum,
  batchId geometry
);

CREATE TABLE privproducttemp (
  id serial primary key,
  modifiedAt real,
  price double,
  expiryMonth serial,
  houseNumber int,
  isPublic smallint,
  exchangeRate text,
  monthlyRate mediumint,
  bookingDate mediumint,
  floorNumber real,
  globalId float,
  rating tinyint,
  feedbackId varchar,
  age geometry,
  accountStatus enum,
  accountNumber enum,
  gameId enum,
  mainImage point,
  emailStatus time,
  activeDevices mediumint
);

CREATE TABLE record (
  id serial primary key,
  group blob,
  fileSize set,
  companyName binary,
  fileHash decimal,
  backupEmail boolean,
  machineId enum,
  coordinateY bit,
  keyId date,
  comment set,
  ipAddress date,
  dataSource double,
  folderPath binary,
  address int,
  couponCode blob,
  manufacturerId tinyint,
  emergencyContact datetime,
  category double,
  formatType binary,
  employmentDate int,
  maskType time,
  maxLimit set,
  connectionString tinyint,
  moduleId real,
  deletedAt text,
  contentType set,
  appVersion float,
  coverImage smallint,
  contactEmail mediumint,
  messageId mediumint,
  houseNumber set,
  city int
);

CREATE TABLE stg_user (
  id serial primary key,
  distributorId decimal,
  role set,
  integrationId double,
  status serial,
  hashKey serial,
  country enum,
  discount tinyint,
  licenseKey datetime,
  uuid varchar,
  code enum,
  salary time,
  productCode int,
  blogId enum,
  marketId mediumint,
  dateFormat smallint
);

CREATE TABLE orderstatus (
  id serial primary key,
  customField2 mediumint,
  emailStatus datetime,
  loadTime int,
  isDeleted enum,
  code set,
  expiryYear blob,
  creditCard decimal,
  lastSeenAt text,
  firmwareVersion blob,
  lastLoginAt set,
  depositAmount timestamp,
  campaignId tinyint,
  monthlyRate geometry,
  timezone serial,
  cartId timestamp,
  batchId double
);

CREATE TABLE record (
  id serial primary key,
  flagged date,
  balance double,
  username time,
  customField2 decimal,
  lastSeenAt blob,
  street real,
  authorId serial,
  maskType boolean,
  role bit,
  dueDateAt bigint,
  currencyCode real,
  updatedAt mediumint,
  age time,
  documentId smallint,
  contactPhone enum,
  facilityId datetime,
  postalCode point
);

CREATE TABLE transaction_info (
  id serial primary key,
  lastLoginAt text,
  extractId bit,
  token binary,
  enrollmentDate geometry,
  memberCount timestamp,
  contactEmail tinyint,
  cartId decimal,
  size serial,
  sku enum,
  dashboardId boolean,
  employeeId geometry,
  contractId tinyint,
  completedAt enum,
  distributorId tinyint,
  activeDevices bigint,
  feedbackId geometry,
  labelText mediumint
);

CREATE TABLE account_2025 (
  id serial primary key,
  maxValue binary,
  logLevel bigint,
  isSystem timestamp,
  creditScore bigint,
  updatedAt point,
  birthDate binary,
  instructorId int,
  createdAt date,
  businessType timestamp,
  accessLevel geometry,
  creditLimit int,
  isArchived time,
  employeeCode float,
  amount varchar,
  budgetCode geometry,
  deviceId time,
  adminNotes bit,
  integrationId smallint,
  totalAmount real,
  isPublic real,
  isActive smallint,
  incidentId real,
  dueDateAt blob,
  startDate real,
  documentId time,
  isDefault binary
);

CREATE TABLE config (
  id serial primary key,
  feedbackId real,
  state enum,
  mobileNumber smallint,
  copyRight float,
  grade text,
  description int,
  loginCount int,
  clientId time,
  avatar varchar,
  followCount enum,
  homePhone real,
  ipAddress binary,
  channelId timestamp,
  analyticsId set,
  latitude float,
  firmwareVersion float
);

CREATE TABLE audit (
  id serial primary key,
  itemCount geometry,
  customField2 real,
  companyName datetime,
  authorId binary,
  currencyCode timestamp,
  maskType timestamp,
  exchangeRate datetime,
  city geometry,
  labelText tinyint
);

CREATE TABLE user_v1 (
  id serial primary key,
  currencyCode binary,
  isRequired time,
  formatType double,
  exchangeRate float,
  accessLevel set,
  blogId set,
  loginCount datetime,
  salary date,
  authToken mediumint,
  isDefault timestamp,
  managerId text,
  addressLine1 timestamp,
  name datetime,
  age serial,
  guestId datetime,
  address set,
  tags tinyint,
  filterType time,
  analyticsId time,
  dashboardId bigint,
  timezone double,
  attemptCount timestamp
);

CREATE TABLE configlegacy (
  id serial primary key,
  activeDevices decimal,
  bankAccount float,
  sku binary,
  tags text,
  middleName boolean,
  localeId int,
  type smallint,
  distributorId binary,
  gender decimal,
  accessLevel date,
  awardDate smallint,
  faxNumber serial,
  buildNumber geometry,
  enabledAt float,
  certificateId tinyint,
  licenseKey mediumint,
  lastSeenAt serial,
  flagged datetime,
  expiryMonth serial
);

CREATE TABLE orderdiv2025 (
  id serial primary key,
  username text,
  languageCode text,
  chatId double,
  labelText blob,
  isAdmin bit,
  blogId timestamp,
  menuId datetime,
  cancelReason geometry,
  tags serial,
  gender float,
  awardDate int,
  mapId bigint,
  marketId timestamp,
  clockIn mediumint,
  inactiveAt serial,
  cartId blob,
  isLocked time,
  linkId double,
  emergencyContact tinyint,
  department text,
  deactivatedAt text,
  fontSize int,
  appVersion real
);

CREATE TABLE stg_organization (
  id serial primary key,
  accountType float,
  logLevel int,
  mimeType int,
  costCenter double,
  bannerImage bigint,
  driverLicense time,
  size tinyint
);

CREATE TABLE pub_config_2025 (
  id serial primary key,
  status enum,
  menuId bigint,
  startDate tinyint,
  houseNumber mediumint,
  companyName serial
);

CREATE TABLE transaction (
  id serial primary key,
  avatar float,
  dialCode enum,
  amount geometry,
  algorithm double,
  isFeatured text,
  createdAt enum,
  clockOut time,
  shippingAddress tinyint,
  lockoutEnd float,
  code varchar,
  contentType smallint
);

CREATE TABLE organization (
  id serial primary key,
  marketId double,
  zipCode double,
  sessionId time,
  checkInTime int,
  group int,
  configId binary,
  errorCode binary,
  dependentId smallint,
  employmentDate time,
  exchangeRate smallint,
  colorCode real,
  middleName real,
  title int,
  eventDate mediumint,
  isArchived text,
  password float,
  defaultLang geometry,
  deactivatedAt timestamp,
  city datetime,
  accountType real
);

CREATE TABLE transactionlog (
  id serial primary key,
  employmentDate date,
  merchantId set,
  coordinateX serial,
  analyticsId mediumint,
  algorithm blob,
  adminNotes datetime,
  defaultValue varchar,
  maxValue decimal,
  coordinateY serial,
  listId double,
  driverLicense blob,
  checkOutTime binary
);

CREATE TABLE dim_record (
  id serial primary key,
  metaKeywords point,
  description set
);

CREATE TABLE transaction (
  id serial primary key,
  cardHolder geometry,
  followCount decimal,
  listId enum,
  bluetoothId boolean,
  accountType set,
  referralCode enum,
  productCode set,
  fileHash blob,
  age point,
  hourlyRate varchar,
  weight set,
  expiryYear decimal,
  clockIn boolean,
  coverImage serial,
  updatedAt decimal,
  validUntil enum,
  unit float,
  companyName geometry,
  completedAt smallint,
  isEnabled tinyint,
  dealerId serial,
  maxLimit blob,
  category binary,
  fileType decimal,
  accountStatus serial,
  dependentId blob,
  dueDateAt time,
  headerImage binary,
  priority point,
  abandonedCartId set
);

CREATE TABLE fact_customer (
  id serial primary key,
  extractId double,
  coordinateX bigint,
  listingId double,
  driverLicense enum,
  deactivatedAt varchar,
  fileHash double,
  certificateId point,
  guestId binary,
  updatedAt geometry,
  formatType binary,
  isLocked tinyint,
  address tinyint,
  signature int,
  metaDescription tinyint,
  shippingAddress mediumint,
  category int,
  keywords real,
  isVerified varchar,
  brandId serial,
  fileSize decimal
);

CREATE TABLE inventory (
  id serial primary key,
  authToken bit,
  discount bit,
  expiryMonth geometry,
  avatar set,
  phone date,
  articleId set,
  headerImage bit,
  enrollmentDate time,
  homePhone tinyint,
  startDate time,
  logLevel text
);

CREATE TABLE extproduct (
  id serial primary key,
  id datetime,
  algorithm real,
  dashboardId date,
  completedAt serial,
  tags varchar,
  rating serial,
  campaignId mediumint,
  appVersion real,
  clockIn mediumint,
  createdAt double,
  macAddress text,
  flagged varchar,
  accountType time,
  title boolean,
  logLevel set,
  type serial,
  faxNumber geometry,
  jobTitle datetime,
  maxValue real,
  amount varchar,
  coordinateX smallint,
  hourlyRate serial,
  zipCode set,
  age bigint,
  forwardTo real,
  billingFrequency text,
  fingerprint bigint,
  contactName point,
  state boolean,
  extractId decimal
);

CREATE TABLE agg_audit (
  id serial primary key,
  feedId bigint,
  id time,
  birthDate int,
  algorithm date,
  menuId int,
  domainName mediumint,
  dimension smallint,
  endPoint tinyint,
  dependentId blob,
  apiVersion smallint,
  errorMessage point,
  bookingDate serial,
  password decimal,
  filterType float,
  memberCount set,
  isDeleted boolean,
  gender text
);

CREATE TABLE recordv1 (
  id serial primary key,
  completedAt binary,
  isEnabled serial,
  likeCount boolean,
  companyName double,
  password boolean,
  maritalStatus boolean,
  amount datetime,
  id time,
  loginCount geometry,
  avatar enum,
  feedId geometry,
  content text
);

CREATE TABLE tblcustomerdiv (
  id serial primary key,
  taxRate real,
  attachmentUrl bigint,
  locationId timestamp,
  amount float,
  gateId blob,
  indexKey bigint,
  enrollmentDate binary,
  token decimal,
  url binary,
  version double,
  childId double,
  cloudId blob,
  endDate smallint,
  meterNumber set,
  facilityId geometry,
  certificateId blob,
  entityId datetime,
  accessLevel set
);

CREATE TABLE customer (
  id serial primary key,
  jobTitle timestamp,
  totalAmount datetime,
  salary mediumint,
  cardHolder serial,
  listingId text,
  departmentCode set,
  clientId serial,
  code set,
  courseId point,
  authMethod point,
  mobileNumber varchar,
  cvv bigint,
  merchantId mediumint,
  id datetime,
  description date,
  hashKey enum,
  amount timestamp,
  name double
);

CREATE TABLE company_rel (
  id serial primary key,
  accountStatus boolean,
  coordinateX bit,
  maskType tinyint,
  inactiveAt mediumint,
  isLocked time,
  age timestamp,
  createdAt smallint,
  checkOutTime mediumint,
  employeeId blob,
  awardDate enum
);

CREATE TABLE stg_config (
  id serial primary key,
  modifiedAt time,
  phone tinyint,
  isDefault time,
  deletedAt binary,
  mapId datetime,
  errorCode bigint,
  earnedPoints tinyint,
  menuId varchar,
  loginCount datetime,
  currencyCode boolean,
  indexKey decimal,
  isLocked bigint,
  keywords timestamp,
  completedAt serial,
  apiVersion double,
  foregroundColor geometry
);

CREATE TABLE audit (
  id serial primary key,
  isLocked bit,
  grade boolean,
  deletedAt date,
  faxNumber mediumint,
  labelText time,
  avatar set,
  levelId bit,
  description smallint,
  firstName point,
  tags int,
  employmentDate varchar,
  isPublic datetime,
  cloudId blob,
  integrationId text
);

CREATE TABLE tmptransaction (
  id serial primary key,
  cloudId mediumint,
  editedAt real,
  version enum,
  isArchived enum,
  awardDate bigint,
  creditScore datetime,
  endPoint boolean,
  nickname time,
  accessLevel time,
  expiryMonth real,
  isActive enum,
  metaDescription point,
  costCenter geometry,
  errorMessage varchar,
  isDefault int,
  loginCount varchar,
  code timestamp,
  totalAmount varchar,
  distributorId decimal
);

CREATE TABLE dim_transaction (
  id serial primary key,
  lastLoginAt bigint,
  thumbnail decimal,
  discount smallint,
  authToken int,
  comment enum,
  colorCode timestamp,
  contactEmail varchar,
  updatedAt text,
  postalCode timestamp,
  accountType decimal,
  frameRate datetime,
  configId datetime,
  loadTime mediumint,
  zipCode datetime,
  createdAt enum,
  memberCount decimal,
  contractId decimal,
  houseNumber double,
  title set,
  dueDateAt time,
  instanceId datetime,
  endDate int,
  username date
);

CREATE TABLE log_audit_status_2024 (
  id serial primary key,
  attachmentUrl mediumint,
  licenseKey mediumint,
  keywords date,
  formatType tinyint,
  folderPath bigint,
  deviceType timestamp,
  isRequired date,
  isLocked double,
  comment serial,
  password timestamp,
  category set,
  globalId boolean,
  analyticsId varchar,
  fingerprint time
);

CREATE TABLE user_info_temp (
  id serial primary key,
  algorithm smallint,
  metaTitle timestamp,
  monthlyRate blob,
  insertedAt bit,
  meterNumber int,
  joinDate bigint,
  birthDate binary,
  dataSource bit,
  ipAddress int,
  expiryDate varchar,
  analyticsId binary,
  productCode varchar,
  priority time,
  amount mediumint,
  languageCode binary,
  jobTitle blob,
  earnedPoints int
);

CREATE TABLE tbl_organization_rel (
  id serial primary key,
  backupEmail binary,
  accessLevel varchar,
  name bigint,
  billingCycle enum,
  hourlyRate text,
  foregroundColor float,
  incidentId float,
  deletedAt real,
  age bigint,
  fileHash real,
  apiVersion real,
  tags smallint,
  countryCode smallint,
  folderPath blob,
  insertedAt double,
  contactName text,
  accountStatus mediumint,
  latitude double,
  linkId bit,
  extractId point,
  contractId varchar,
  brandId decimal,
  completionRate real
);

CREATE TABLE user_hist (
  id serial primary key,
  bannerImage tinyint,
  totalAmount varchar,
  id float,
  errorMessage bit,
  status mediumint,
  displayOrder int,
  clientId enum,
  employeeId date,
  score serial,
  foregroundColor tinyint,
  articleId serial,
  locationId datetime,
  globalId time,
  geoLocation time
);

CREATE TABLE audit (
  id serial primary key,
  errorCode date,
  dealerId datetime,
  messageId serial,
  audioUrl int,
  alertType mediumint,
  emergencyContact blob,
  loginAttempts blob,
  cardNumber enum,
  appVersion smallint,
  accountType time,
  longitude text,
  folderPath timestamp,
  thumbnail text,
  paymentMethod decimal,
  email binary,
  modifiedAt decimal,
  cardHolder bigint,
  birthDate geometry,
  metadata varchar,
  countryCode smallint,
  apiKey set,
  clockOut mediumint,
  tags geometry
);

CREATE TABLE transaction_out (
  id serial primary key,
  accountNumber double,
  hiddenAt real,
  fingerprint date,
  activeDevices double,
  title bit,
  accountStatus point,
  faxNumber float,
  labelText decimal,
  courseId varchar,
  formatType point,
  cloudId boolean,
  listingId mediumint,
  bannerImage mediumint,
  id enum,
  dueDateAt set
);

CREATE TABLE order (
  id serial primary key,
  itemCount blob,
  category point,
  followCount geometry,
  instructorId double,
  bannerImage bit,
  dealerId text,
  lastName real,
  copyRight real
);

CREATE TABLE user_map (
  id serial primary key,
  mobileNumber int,
  folderPath boolean,
  middleName point,
  emailStatus text,
  bluetoothId int,
  address binary,
  updatedAt point,
  gender tinyint,
  longitude boolean,
  flagged mediumint,
  defaultLang bit,
  isAdmin timestamp,
  amount datetime,
  fileHash text,
  version date,
  dialCode blob,
  sku binary
);

CREATE TABLE olk_company (
  id serial primary key,
  isAdmin tinyint,
  attachmentUrl bit,
  fileSize bigint,
  longitude float,
  checkInTime blob,
  price date,
  duration int,
  budgetCode text,
  deviceType varchar,
  accountType bigint,
  mimeType binary,
  frameRate timestamp,
  keywords decimal,
  sessionId datetime,
  filterType float
);

CREATE TABLE company_2024 (
  id serial primary key,
  category point,
  accessLevel boolean,
  merchantId int,
  brandId bit,
  grade varchar,
  campaignId date,
  longitude point,
  alertType varchar,
  hiddenAt bigint,
  cartId int,
  addressLine2 point,
  headerImage enum,
  documentId blob,
  channelId datetime,
  insertedAt geometry,
  feedbackId varchar,
  logLevel date,
  agentId blob,
  chargeId tinyint,
  dailyLimit bit,
  bluetoothId timestamp,
  weight boolean,
  emailStatus decimal,
  taxRate decimal,
  title tinyint,
  isHidden bit
);

CREATE TABLE productlog (
  id serial primary key,
  buildNumber enum,
  fileHash tinyint,
  minLimit text,
  startDate real,
  size float,
  postalCode bigint,
  version timestamp,
  ipAddress date,
  taxRate enum,
  endDate decimal,
  certificateId float,
  courseId bigint,
  moduleId bit,
  timezone decimal,
  fontFamily date,
  emailStatus bit,
  activeDevices bit,
  errorCode int,
  floorNumber time,
  priority binary,
  memberCount time,
  brandId float,
  contractId bigint,
  token binary,
  actionType mediumint,
  isHidden mediumint,
  orderStatus blob,
  loginCount binary,
  deviceId enum
);

CREATE TABLE src_customer_seg (
  id serial primary key,
  cvv mediumint,
  customField1 enum,
  geoLocation int,
  adminNotes double,
  fromDate tinyint,
  accountType enum,
  configId boolean,
  isRequired set,
  longitude double,
  errorCode enum,
  countryCode set,
  token blob,
  downloadCount serial,
  floorNumber float,
  chatId enum,
  maxLimit tinyint,
  sessionId set,
  defaultValue enum,
  taxRate varchar,
  companyName geometry,
  locationId smallint,
  billingCycle time,
  cartId text,
  gameId geometry,
  name int,
  insertedAt tinyint,
  brandId geometry,
  menuId geometry,
  enabledAt serial,
  status binary
);

CREATE TABLE corepaymentmap (
  id serial primary key,
  shippingAddress bit,
  claimId bit,
  companyName datetime,
  education float,
  earnedPoints geometry,
  documentId datetime,
  cancelReason bit,
  iconPath geometry,
  group float
);

CREATE TABLE tmp_company (
  id serial primary key,
  status date,
  keywords time,
  contactName mediumint,
  accessLevel set,
  score bigint,
  createdAt serial,
  indexKey date,
  listingId mediumint,
  latitude bigint,
  currency geometry,
  maskType text,
  metaKeywords serial,
  comment set,
  title tinyint,
  languageCode boolean,
  isPublic date,
  content time,
  referralCode text,
  isArchived bigint
);

CREATE TABLE vwrecord2024 (
  id serial primary key,
  completedAt binary,
  hostName float,
  expiryYear varchar,
  id double,
  fileHash float,
  shippingAddress boolean,
  comment smallint,
  dateFormat decimal,
  deviceId bigint,
  status float,
  isDraft double,
  depositAmount set,
  monthlyRate float,
  fontFamily binary,
  deletedAt binary,
  name mediumint,
  houseNumber varchar,
  minLimit point,
  chatId enum,
  deactivatedAt bit,
  customerId binary,
  description smallint,
  metaTitle tinyint,
  licenseKey mediumint,
  locationId double,
  discountCode tinyint,
  adminNotes set,
  grade mediumint,
  accountType time
);

