CREATE TABLE log_payment (
  id serial primary key,
  integrationId real,
  buildNumber real,
  chargeId int,
  hostName mediumint,
  lockoutEnd date,
  ipAddress boolean,
  guestId blob,
  machineId blob,
  avatar varchar,
  claimId float,
  listId smallint,
  password varchar,
  mobileNumber time,
  endDate serial,
  description real,
  jobTitle set,
  employeeId timestamp,
  loginCount date,
  alertType varchar,
  contactName int,
  accountStatus serial,
  customField2 bit,
  cancelReason enum,
  keywords tinyint,
  dealerId tinyint,
  joinDate boolean,
  deviceType decimal,
  phone binary
);

CREATE TABLE tbl_inventory_new (
  id serial primary key,
  checkInTime binary,
  actionType bigint,
  entryPoint set,
  extractId point,
  category set,
  middleName boolean,
  address bigint,
  handlerId real,
  authToken tinyint,
  languageCode varchar,
  fileType datetime,
  globalId timestamp,
  customField2 blob,
  linkId set,
  depositAmount enum,
  sessionId datetime,
  creditCard serial,
  loadTime text,
  manufacturerId double,
  uuid serial,
  indexKey timestamp,
  createdAt datetime,
  lastLoginAt decimal
);

CREATE TABLE aggpaymentseg (
  id serial primary key,
  birthDate varchar,
  contactEmail float,
  earnedPoints time,
  isEnabled datetime,
  displayName date,
  hourlyRate point,
  bannerImage int,
  authToken float,
  deviceToken tinyint,
  salary date
);

CREATE TABLE inventory_rel (
  id serial primary key,
  coordinateY set,
  agentId boolean,
  iconPath bit
);

CREATE TABLE payment_legacy (
  id serial primary key,
  folderPath boolean,
  mainImage float,
  accessLevel blob,
  cardHolder varchar,
  frameRate point,
  fileType double,
  audioUrl double,
  ipAddress decimal,
  isDraft bigint,
  deletedAt int,
  manufacturerId time,
  backupEmail float,
  metaKeywords tinyint,
  version real,
  height int
);

CREATE TABLE dstcompany (
  id serial primary key,
  lastLoginAt blob,
  shippingAddress geometry,
  mainImage decimal,
  authMethod set,
  orderId tinyint,
  industryType boolean,
  browserType int,
  thumbnail serial,
  taxRate smallint,
  updatedAt date,
  phone set,
  errorMessage mediumint,
  quantity text,
  importId tinyint,
  fontFamily binary,
  isDraft set,
  managerId bit,
  languageCode date,
  faxNumber point,
  memberCount int,
  currencyCode time,
  joinDate binary,
  lastSeenAt date,
  accessLevel datetime,
  couponCode timestamp,
  version binary,
  driverLicense date,
  customerGroup date,
  amount datetime,
  articleId tinyint
);

CREATE TABLE rel_config_v2 (
  id serial primary key,
  discountCode tinyint,
  countryCode double,
  price time,
  colorCode int,
  uuid smallint,
  password point,
  checkInTime bit,
  invoiceId datetime,
  filterType binary,
  customerGroup enum,
  expiryYear serial,
  token time,
  ipAddress int,
  description point,
  appVersion varchar,
  isVerified bit,
  memberCount smallint,
  lastName text,
  adminNotes blob,
  moduleId serial,
  loginAttempts blob,
  dataSource boolean,
  middleName boolean,
  distributorId text,
  instructorId boolean,
  weight tinyint,
  displayOrder tinyint,
  accountNumber datetime,
  email boolean,
  completionRate mediumint,
  comment date
);

CREATE TABLE tmp_record (
  id serial primary key,
  maskType mediumint,
  courseId datetime,
  country tinyint,
  signature smallint,
  attachmentUrl set,
  name point,
  state date,
  customField2 smallint,
  dealerId bigint,
  id blob,
  employeeId date,
  type geometry,
  listingId tinyint,
  folderPath date,
  entityId serial,
  followCount real,
  latitude enum,
  accountNumber text
);

CREATE TABLE account_out (
  id serial primary key,
  companyId int,
  defaultValue point,
  hourlyRate text
);

CREATE TABLE userv1 (
  id serial primary key,
  actionType double,
  salary datetime,
  addressLine2 varchar,
  loginCount text,
  documentId text,
  floorNumber int,
  longitude varchar
);

CREATE TABLE customer (
  id serial primary key,
  driverLicense datetime,
  nickname float,
  departmentCode geometry,
  instructorId time
);

CREATE TABLE product_status_v2 (
  id serial primary key,
  appVersion timestamp,
  category varchar,
  geoLocation tinyint,
  configId boolean,
  balance boolean,
  endDate decimal,
  username int,
  state real,
  deviceId smallint,
  cartId float,
  isActive tinyint,
  moveId varchar,
  value datetime,
  abandonedCartId binary
);

CREATE TABLE tblaudittemp (
  id serial primary key,
  guestId boolean,
  machineId bigint,
  gameId date,
  sku bigint,
  maxLimit tinyint,
  phone boolean,
  signature smallint,
  layerId int,
  attachmentUrl binary,
  weight date,
  birthDate time,
  logLevel serial,
  documentId boolean,
  dialCode datetime,
  listingId bigint,
  fromDate float,
  handlerId tinyint,
  marketId smallint,
  cartId enum,
  type datetime,
  claimId blob,
  checkInTime varchar,
  moveId binary,
  appVersion binary,
  priority enum,
  awardDate boolean,
  actionType real,
  middleName time,
  batchId timestamp
);

CREATE TABLE product_v1 (
  id serial primary key,
  articleId float,
  middleName bit,
  creditScore mediumint,
  group serial,
  hourlyRate double,
  attemptCount point,
  expiryMonth point,
  managerId blob,
  earnedPoints point,
  id real,
  linkId datetime,
  favoriteCount decimal,
  copyRight date,
  certificateId binary,
  attachmentUrl binary
);

CREATE TABLE cpyorderdiv (
  id serial primary key,
  amount blob,
  dimension tinyint,
  alertType int,
  latitude enum,
  certificateId geometry,
  sessionId boolean,
  dailyLimit boolean,
  contentType bit,
  cartId int,
  isArchived time,
  weight date,
  entityId decimal,
  hiddenAt datetime,
  adminNotes varchar,
  description binary,
  configId smallint,
  isHidden int,
  category time,
  forwardTo geometry,
  longitude double,
  costCenter bigint,
  clientId double,
  deviceToken set
);

CREATE TABLE organization_meta (
  id serial primary key,
  fileSize int,
  token date,
  couponCode geometry,
  status smallint,
  category serial,
  inactiveAt float,
  title decimal,
  phone int,
  postalCode varchar,
  longitude blob,
  forwardTo serial,
  isDefault int,
  integrationId int,
  email datetime
);

CREATE TABLE dsttransaction (
  id serial primary key,
  companyName real,
  errorMessage boolean
);

CREATE TABLE configinfov1 (
  id serial primary key,
  cancelReason float,
  coordinateX varchar,
  moduleId timestamp,
  inactiveAt double,
  childId float,
  firmwareVersion enum,
  avatar point,
  customField2 bigint,
  password mediumint,
  indexKey bigint,
  hourlyRate boolean,
  address text,
  city text,
  latitude tinyint,
  chatId bigint,
  firstName mediumint,
  authMethod blob,
  handlerId boolean,
  totalAmount timestamp,
  menuId time,
  contactPhone set,
  code smallint,
  accessLevel boolean,
  blogId tinyint,
  status boolean,
  nickname tinyint,
  channelId serial,
  locationId float,
  metaKeywords bit,
  importId boolean,
  adminNotes datetime
);

CREATE TABLE relcustomer (
  id serial primary key,
  startDate date,
  floorNumber bigint,
  copyRight smallint,
  dimension serial,
  orderId set,
  editedAt bit,
  sku blob,
  coverImage date,
  isPublic double,
  activeDevices boolean
);

CREATE TABLE inventory_type (
  id serial primary key,
  paymentMethod enum,
  firmwareVersion blob,
  name int,
  monthlyRate bit,
  downloadCount float,
  feedbackId set,
  isBillable boolean,
  domainName bigint,
  guestId float,
  displayName blob,
  addressLine1 tinyint,
  clockIn varchar,
  inactiveAt double,
  labelText geometry
);

CREATE TABLE customer (
  id serial primary key,
  billingCycle bit,
  employeeCode boolean,
  apiVersion set,
  inactiveAt serial,
  salary boolean,
  dashboardId time
);

CREATE TABLE order2024 (
  id serial primary key,
  token geometry,
  costCenter timestamp,
  errorCode geometry,
  enrollmentDate set,
  messageId binary,
  analyticsId geometry,
  discountCode set,
  dataSource enum,
  loginCount bigint,
  itemCount bigint,
  editedAt geometry,
  headerImage mediumint,
  merchantId text,
  algorithm varchar
);

CREATE TABLE account_meta (
  id serial primary key,
  cvv blob,
  bluetoothId mediumint,
  value bit,
  faxNumber serial,
  isSystem set,
  orderId float,
  handlerId mediumint,
  metadata point,
  certificateId blob,
  cacheKey text,
  fontSize varchar,
  isDeleted set,
  hiddenAt serial,
  feedId real,
  paymentMethod time,
  linkId enum,
  browserType text,
  foregroundColor date,
  accountType tinyint,
  driverLicense mediumint,
  category geometry,
  minLimit serial,
  token date,
  comment mediumint,
  name serial,
  entryPoint varchar
);

CREATE TABLE transaction (
  id serial primary key,
  companyId tinyint,
  domainName enum,
  name varchar,
  maxValue blob,
  invoiceId enum,
  fingerprint enum,
  sessionId smallint
);

CREATE TABLE stgorder (
  id serial primary key,
  dataSource smallint,
  balance tinyint,
  configId smallint,
  employmentDate bit,
  birthDate boolean,
  defaultLang mediumint,
  discount datetime,
  keyId serial,
  apiVersion blob,
  maxLimit time,
  buildNumber set,
  companyLogo smallint,
  integrationId float,
  adminNotes blob,
  accessLevel point,
  latitude geometry,
  followCount set,
  longitude enum,
  enrollmentDate tinyint,
  merchantId point,
  currencyCode text,
  discountCode set,
  itemCount smallint,
  avatar tinyint,
  createdAt set,
  referralCode blob,
  billingFrequency bit,
  id date,
  jobTitle varchar
);

CREATE TABLE customer (
  id serial primary key,
  checkInTime float,
  group enum,
  linkId date,
  discount text,
  geoLocation blob,
  floorNumber bigint,
  isArchived int,
  title time,
  hiddenAt text,
  instructorId bit,
  logLevel serial,
  shippingAddress serial,
  hourlyRate int,
  copyRight serial,
  type mediumint,
  isSystem text,
  feedbackId smallint,
  analyticsId decimal,
  email double,
  albumId blob,
  firstName tinyint,
  minLimit tinyint,
  documentId datetime
);

CREATE TABLE coreorganizationarchive (
  id serial primary key,
  listingId point,
  employmentDate tinyint,
  clockOut geometry,
  comment double,
  price bigint,
  billingCycle varchar,
  dateFormat float,
  actionType mediumint,
  dueDateAt varchar,
  apiVersion bit,
  fileName geometry,
  merchantId text,
  hourlyRate decimal,
  tags boolean,
  dealerId blob,
  blogId varchar,
  title bit,
  modifiedAt blob,
  completedAt mediumint,
  cartId time,
  id blob,
  documentId datetime,
  metaKeywords enum,
  avatar varchar,
  accountType smallint,
  costCenter timestamp
);

CREATE TABLE organization (
  id serial primary key,
  authorId geometry,
  alertType bit,
  createdAt int,
  invoiceId real,
  productCode serial,
  sessionId decimal,
  billingFrequency set,
  expiryDate mediumint,
  fileType time,
  departmentCode float,
  checkInTime tinyint,
  lastSeenAt boolean,
  sku blob,
  maskType blob,
  coordinateY mediumint,
  customerGroup decimal,
  hourlyRate binary,
  accountNumber float,
  driverLicense tinyint,
  birthDate datetime,
  copyRight double,
  messageId real,
  coverImage datetime,
  localeId int,
  faxNumber mediumint
);

CREATE TABLE dst_account (
  id serial primary key,
  defaultLang blob,
  metaDescription mediumint,
  businessType real,
  totalAmount int,
  bankAccount varchar,
  state real,
  phone bit,
  sku tinyint,
  isPublic float,
  audioUrl time,
  articleId bigint,
  companyName enum,
  postalCode float,
  creditScore binary,
  validUntil float,
  employmentDate set,
  hourlyRate binary,
  size boolean,
  itemCount text,
  longitude int,
  agentId set,
  frameRate datetime,
  homePhone mediumint,
  endPoint bit,
  shippingAddress int,
  createdAt tinyint,
  childId boolean,
  isEnabled tinyint,
  latitude text
);

CREATE TABLE ver_config_archive (
  id serial primary key,
  type text,
  favoriteCount boolean
);

CREATE TABLE olk_company (
  id serial primary key,
  agentId set,
  fontSize point,
  buildNumber geometry,
  createdAt mediumint,
  isFeatured mediumint,
  loadTime enum,
  apiKey binary,
  username tinyint,
  macAddress timestamp,
  amount text,
  headerImage blob,
  cancelReason real,
  invoiceId date,
  group double,
  filterType int,
  address time,
  enrollmentDate decimal,
  alertType decimal,
  accessLevel time,
  shippingAddress varchar
);

CREATE TABLE inventory (
  id serial primary key,
  instructorId time,
  companyName int,
  paymentMethod time
);

CREATE TABLE customer_info (
  id serial primary key,
  dependentId smallint,
  firstName boolean,
  lastSeenAt timestamp,
  colorCode serial,
  downloadCount blob,
  flagged varchar,
  cacheKey float,
  likeCount text,
  name varchar,
  middleName decimal,
  itemCount smallint
);

CREATE TABLE auditv1 (
  id serial primary key,
  dueDateAt timestamp,
  feedId decimal,
  feedbackId timestamp,
  amount blob,
  foregroundColor timestamp,
  createdAt int,
  firstName serial,
  age timestamp,
  url datetime,
  distributorId blob,
  metaKeywords serial,
  gameId float,
  downloadCount tinyint,
  accessLevel serial,
  audioUrl int,
  country text,
  activeDevices text,
  isRequired blob,
  checkInTime float,
  fontFamily serial,
  keywords real,
  insertedAt varchar,
  logLevel blob,
  couponCode date,
  memberCount float
);

CREATE TABLE log_user (
  id serial primary key,
  domainName tinyint,
  defaultLang time,
  orderStatus bit
);

CREATE TABLE sys_payment (
  id serial primary key,
  emailStatus int,
  indexKey set,
  locationId set,
  orderStatus decimal,
  metaDescription float,
  isLocked datetime,
  memberCount timestamp,
  licenseKey time,
  maxValue point,
  messageId bigint,
  latitude real,
  address point,
  updatedAt boolean,
  fileSize set,
  forwardTo enum,
  balance float,
  sessionId smallint,
  deletedAt smallint,
  frameRate date,
  version float,
  status geometry
);

CREATE TABLE organization_2025 (
  id serial primary key,
  fontFamily set,
  languageCode time,
  levelId point,
  isEnabled binary,
  shippingAddress varchar,
  keyId time,
  eventDate enum,
  fileName datetime,
  amount mediumint,
  authMethod blob,
  phone tinyint,
  instanceId set,
  customerGroup mediumint,
  articleId int,
  longitude set,
  moduleId timestamp,
  clientId datetime,
  metaDescription serial,
  hourlyRate text,
  maxValue date,
  priority boolean,
  entityId boolean,
  firmwareVersion mediumint,
  cityName decimal,
  description varchar,
  alertType binary
);

CREATE TABLE user (
  id serial primary key,
  awardDate decimal,
  cityName smallint,
  maxValue binary,
  cvv binary,
  id float,
  street binary,
  frameRate smallint,
  endDate point,
  checkInTime datetime,
  contactEmail geometry,
  checkOutTime datetime,
  shippingAddress boolean,
  levelId serial,
  insuranceId datetime,
  ipAddress geometry,
  isEnabled binary,
  name binary,
  emergencyContact time,
  comment boolean,
  mapId double,
  creditLimit bit,
  cardHolder boolean,
  dealerId double,
  isDraft serial,
  minLimit boolean,
  countryCode serial,
  dueDateAt timestamp
);

CREATE TABLE account_info (
  id serial primary key,
  isSystem varchar,
  insuranceId tinyint,
  isAdmin geometry,
  accessLevel boolean,
  email tinyint,
  size boolean,
  dialCode time,
  feedbackId point,
  amount float,
  blogId real,
  paymentMethod smallint,
  couponCode tinyint,
  totalAmount point,
  frameRate serial,
  attachmentUrl bit,
  password real
);

CREATE TABLE ext_order (
  id serial primary key,
  billingFrequency bigint,
  instanceId text,
  endPoint smallint,
  managerId int,
  inactiveAt serial,
  downloadCount mediumint,
  forwardTo decimal,
  dateFormat varchar,
  discount timestamp,
  middleName binary,
  contactEmail boolean,
  comment tinyint,
  deactivatedAt mediumint,
  groupName text,
  customField1 int,
  houseNumber float,
  token boolean,
  childId tinyint,
  dealerId point,
  appVersion double,
  isFeatured boolean,
  title varchar,
  bannerImage double,
  alertType geometry,
  contactName datetime,
  metaTitle timestamp,
  companyName binary,
  dependentId binary
);

CREATE TABLE coreaccount (
  id serial primary key,
  version enum,
  indexKey real,
  inactiveAt text,
  description mediumint,
  comment enum,
  buildNumber real,
  gameId serial,
  password enum,
  merchantId datetime,
  isLocked double,
  firstName timestamp,
  editedAt enum,
  adminNotes bigint,
  itemCount tinyint,
  lockoutEnd mediumint,
  linkId float,
  expiryMonth enum,
  lastSeenAt bigint,
  email timestamp,
  bookingDate serial,
  gateId double,
  clockOut bigint,
  amount enum,
  faxNumber text,
  grade date,
  timezone geometry,
  hostName set
);

CREATE TABLE cpy_organization_v1 (
  id serial primary key,
  fileName bigint,
  loadTime binary,
  buildNumber point,
  forwardTo serial,
  maxLimit enum,
  unit float,
  longitude text,
  createdAt smallint,
  manufacturerId binary,
  couponCode bigint
);

CREATE TABLE core_user (
  id serial primary key,
  awardDate mediumint,
  version tinyint
);

CREATE TABLE customer (
  id serial primary key,
  forwardTo point,
  dashboardId timestamp,
  title real,
  houseNumber time,
  id time,
  messageId time,
  currency bit,
  jobTitle varchar,
  menuId timestamp,
  albumId decimal,
  updatedAt boolean,
  clockIn int,
  apiVersion time,
  languageCode binary,
  localeId datetime,
  foregroundColor text,
  hostName bigint,
  salary bit,
  isAdmin binary
);

CREATE TABLE dst_config (
  id serial primary key,
  lastSeenAt bit,
  timezone double,
  machineId float,
  localeId set,
  accountNumber int,
  mimeType enum,
  accountStatus int,
  cvv double,
  isRequired time,
  insuranceId binary
);

CREATE TABLE payment (
  id serial primary key,
  iconPath varchar,
  isArchived time,
  appVersion float,
  messageId timestamp,
  driverLicense point,
  defaultValue smallint,
  browserType mediumint,
  size enum,
  maxLimit boolean,
  editedAt date,
  token varchar,
  totalAmount double,
  isDefault binary,
  listingId bigint,
  coordinateY decimal,
  isEnabled tinyint,
  eventDate date,
  favoriteCount time
);

CREATE TABLE pub_user (
  id serial primary key,
  thumbnail smallint,
  industryType varchar,
  costCenter bit,
  metadata blob,
  minValue real
);

CREATE TABLE tmp_user (
  id serial primary key,
  incidentId tinyint,
  menuId time,
  isSystem bigint,
  quantity point,
  country int,
  category bigint,
  licenseKey timestamp,
  authMethod set,
  alertType tinyint,
  description set,
  latitude varchar,
  dimension text,
  accountStatus float,
  password geometry,
  extractId time,
  authorId float,
  group bit,
  filterType datetime,
  gameId decimal,
  street float,
  amount text,
  costCenter set,
  deviceToken tinyint,
  customField1 varchar,
  colorCode tinyint,
  endDate timestamp,
  mapId double,
  invoiceId varchar,
  courseId datetime,
  levelId binary
);

CREATE TABLE logconfig (
  id serial primary key,
  latitude enum,
  birthDate smallint,
  uuid set,
  authMethod point,
  accountNumber real,
  minLimit point,
  title bigint,
  industryType mediumint,
  inactiveAt point,
  firstName binary,
  balance date,
  taxRate point,
  amount real,
  itemCount set,
  attachmentUrl timestamp,
  foregroundColor decimal,
  floorNumber boolean
);

CREATE TABLE dst_company_type (
  id serial primary key,
  defaultValue boolean,
  loginCount decimal,
  hourlyRate tinyint,
  authMethod enum,
  machineId smallint,
  completionRate binary,
  ipAddress decimal,
  country varchar,
  licenseKey mediumint,
  displayName datetime,
  entryPoint varchar,
  authorId date,
  localeId datetime,
  configId date,
  balance timestamp,
  companyName date,
  bankAccount timestamp,
  id date,
  maskType int,
  errorMessage mediumint,
  contactName smallint,
  maxValue smallint,
  cloudId datetime,
  followCount geometry,
  longitude varchar
);

