CREATE TABLE vw_user_temp (
  id serial primary key,
  department timestamp,
  contentType time,
  maxLimit double,
  completionRate boolean,
  address date,
  isPublic varchar,
  buildNumber timestamp,
  fileName text,
  costCenter time,
  accountType double,
  hourlyRate timestamp,
  coordinateX double,
  locationId int,
  isDraft int,
  maritalStatus datetime,
  metadata datetime,
  apiKey date,
  validUntil bit,
  balance int,
  indexKey boolean,
  hashKey decimal,
  category timestamp,
  campaignId bit,
  score varchar,
  chargeId time,
  lastSeenAt time
);

CREATE TABLE inventory (
  id serial primary key,
  email date,
  documentId set,
  emailStatus blob,
  isEnabled decimal,
  group set,
  likeCount varchar,
  height real,
  marketId bit,
  metaTitle varchar,
  monthlyRate binary,
  creditCard enum,
  invoiceId time,
  comment geometry,
  customField2 set,
  gameId timestamp
);

CREATE TABLE core_payment (
  id serial primary key,
  addressLine1 bit,
  dependentId double,
  chargeId enum,
  awardDate date
);

CREATE TABLE sys_payment_temp (
  id serial primary key,
  taxRate bit,
  category decimal,
  authMethod date,
  bannerImage smallint,
  displayName mediumint,
  modifiedAt int,
  bankAccount int,
  billingFrequency enum
);

CREATE TABLE dst_customer_div (
  id serial primary key,
  phone serial,
  apiVersion real,
  homePhone blob,
  dataSource boolean,
  email real,
  maxLimit text,
  longitude binary,
  handlerId boolean
);

CREATE TABLE src_config (
  id serial primary key,
  enabledAt decimal,
  description binary,
  expiryYear timestamp,
  referralCode set,
  memberCount real,
  alertType geometry,
  isAdmin point,
  authMethod serial
);

CREATE TABLE company (
  id serial primary key,
  costCenter blob,
  audioUrl int,
  paymentMethod date,
  updatedAt serial,
  cityName smallint,
  instanceId mediumint,
  importId int,
  isDraft decimal,
  downloadCount smallint,
  forwardTo double,
  fileSize bit,
  category boolean,
  isRequired blob,
  deletedAt enum,
  dashboardId date,
  browserType float
);

CREATE TABLE agg_company_status (
  id serial primary key,
  isSystem date,
  fingerprint point,
  forwardTo decimal,
  cacheKey set,
  lastName float,
  foregroundColor point,
  loginAttempts float,
  labelText date,
  formatType set,
  languageCode mediumint,
  group varchar,
  errorMessage smallint,
  geoLocation int,
  deviceId text,
  gender set,
  loginCount tinyint,
  maritalStatus set,
  balance mediumint,
  exchangeRate time,
  status datetime
);

CREATE TABLE dstorder (
  id serial primary key,
  lockoutEnd text,
  city set
);

CREATE TABLE tmp_record_type_temp (
  id serial primary key,
  authorId tinyint,
  expiryDate set,
  gateId bigint
);

CREATE TABLE privconfig (
  id serial primary key,
  emergencyContact point,
  monthlyRate tinyint,
  grade tinyint,
  followCount tinyint,
  feedId mediumint,
  alertType geometry,
  token serial,
  bookingDate datetime,
  inactiveAt decimal,
  departmentCode text
);

CREATE TABLE factproduct (
  id serial primary key,
  metaDescription real,
  contactEmail set,
  macAddress double,
  coordinateX float,
  enrollmentDate blob,
  batchId bit
);

CREATE TABLE vw_transaction (
  id serial primary key,
  albumId set,
  channelId binary,
  avatar smallint,
  age date,
  loginCount enum,
  apiKey int,
  authMethod serial,
  flagged boolean,
  integrationId binary,
  minLimit blob,
  formatType enum,
  fileType bigint,
  facilityId float,
  companyLogo date,
  password timestamp,
  thumbnail double,
  hourlyRate float
);

CREATE TABLE agguserlog (
  id serial primary key,
  employmentDate tinyint,
  password tinyint,
  bluetoothId bigint,
  checkOutTime decimal,
  mimeType text,
  title real,
  layerId point,
  mobileNumber boolean,
  currencyCode mediumint,
  browserType text,
  isDraft point,
  fileHash point
);

CREATE TABLE cpy_organization_extra (
  id serial primary key,
  minValue enum,
  domainName decimal,
  referralCode float,
  accessLevel float,
  ipAddress set,
  title set,
  maskType float,
  enrollmentDate text,
  fileType date,
  checkOutTime binary
);

CREATE TABLE config (
  id serial primary key,
  domainName float,
  incidentId tinyint,
  emailStatus mediumint,
  accountNumber varchar,
  discount decimal,
  businessType decimal,
  filterType date,
  authToken real,
  name set,
  cardHolder set,
  expiryMonth date,
  middleName boolean,
  coordinateY double,
  deletedAt float,
  ipAddress float,
  updatedAt enum,
  isRequired varchar,
  shippingAddress float,
  birthDate time,
  amount date,
  completedAt int,
  macAddress datetime,
  albumId date,
  flagged decimal,
  bluetoothId binary,
  unit boolean,
  height serial,
  homePhone enum,
  guestId float
);

CREATE TABLE vw_company (
  id serial primary key,
  avatar float,
  checkInTime time,
  homePhone int,
  lastName decimal,
  keywords smallint,
  businessType boolean,
  size float,
  fontSize smallint,
  friendId time,
  group bit,
  endPoint geometry,
  clientId double
);

CREATE TABLE record_hist (
  id serial primary key,
  isSystem time,
  fromDate serial,
  discountCode serial,
  incidentId tinyint
);

CREATE TABLE company (
  id serial primary key,
  linkId float,
  floorNumber bit,
  incidentId timestamp,
  dailyLimit float,
  tags datetime,
  balance int,
  isDraft datetime,
  dataSource bigint,
  backupEmail smallint,
  department decimal,
  accountStatus geometry,
  address serial,
  insuranceId bigint,
  fileHash text,
  connectionString point,
  macAddress double,
  fileSize tinyint,
  moduleId real,
  expiryMonth serial,
  emergencyContact real,
  fingerprint datetime,
  keyId mediumint
);

CREATE TABLE dimrecordv1 (
  id serial primary key,
  referralCode float,
  listId point,
  accountType point,
  shippingAddress set
);

CREATE TABLE transactioninfolegacy (
  id serial primary key,
  checkOutTime boolean,
  companyName text,
  metadata varchar,
  url int,
  age bigint,
  isBillable boolean,
  moduleId smallint,
  value point,
  businessType decimal,
  isActive real
);

CREATE TABLE app_transaction (
  id serial primary key,
  listingId tinyint,
  hourlyRate decimal,
  maxValue enum,
  contactName timestamp,
  abandonedCartId smallint,
  fileType real,
  nickname date,
  type serial,
  phone date,
  insertedAt mediumint,
  isPublic boolean,
  depositAmount binary,
  entryPoint geometry
);

CREATE TABLE app_user (
  id serial primary key,
  defaultLang mediumint,
  balance time,
  isBillable int,
  cardHolder timestamp,
  token int,
  avatar date,
  expiryYear enum,
  size tinyint,
  endDate mediumint,
  listingId float,
  bluetoothId float
);

CREATE TABLE order (
  id serial primary key,
  sessionId enum,
  lastSeenAt binary,
  productCode varchar,
  faxNumber set,
  comment boolean,
  marketId set,
  metaKeywords tinyint,
  metaDescription enum,
  maskType real,
  createdAt real,
  likeCount real,
  articleId blob,
  startDate mediumint,
  customerId date,
  dialCode text,
  size float,
  algorithm double,
  certificateId date,
  accountType geometry,
  loginCount timestamp,
  education point,
  listingId decimal,
  deliveryDate timestamp,
  nickname decimal,
  departmentCode timestamp,
  loginAttempts serial,
  password real,
  avatar double
);

CREATE TABLE ver_company (
  id serial primary key,
  dueDateAt blob,
  value varchar,
  geoLocation blob,
  password bigint,
  keyId datetime,
  referralCode bit,
  sku geometry,
  metaKeywords binary,
  bookingDate decimal,
  iconPath varchar
);

CREATE TABLE tblaccountstatus (
  id serial primary key,
  merchantId blob,
  avatar binary,
  mapId mediumint,
  age time,
  faxNumber double,
  gameId bigint,
  claimId real,
  actionType time,
  salary mediumint,
  deactivatedAt decimal,
  expiryMonth time,
  dataSource bigint,
  keyId boolean,
  employeeId real,
  clockOut set,
  languageCode real,
  depositAmount enum,
  category set,
  hourlyRate bit,
  moduleId decimal,
  handlerId enum,
  deviceId point,
  albumId datetime,
  awardDate tinyint,
  memberCount text,
  isSystem boolean
);

CREATE TABLE sysproduct (
  id serial primary key,
  monthlyRate int,
  houseNumber smallint,
  updatedAt mediumint,
  status float,
  cvv tinyint,
  metaKeywords time,
  amount serial,
  activeDevices binary,
  certificateId double,
  bluetoothId real,
  title point,
  completedAt decimal,
  deviceId timestamp,
  hiddenAt tinyint
);

CREATE TABLE inventory (
  id serial primary key,
  licenseKey enum,
  updatedAt double,
  mapId decimal,
  deletedAt int,
  latitude mediumint,
  title text,
  linkId time,
  deviceId varchar,
  guestId double
);

CREATE TABLE agg_transaction_temp (
  id serial primary key,
  category timestamp,
  backupEmail mediumint,
  shippingAddress timestamp,
  gateId enum,
  phone geometry,
  groupName varchar,
  street text,
  dailyLimit varchar,
  cardNumber decimal,
  addressLine1 float,
  currencyCode serial,
  albumId geometry,
  tags datetime,
  defaultValue real,
  isAdmin float,
  billingCycle int,
  favoriteCount tinyint,
  title serial,
  joinDate real,
  contentType bigint,
  configId time
);

CREATE TABLE record (
  id serial primary key,
  documentId varchar,
  price text,
  email serial,
  content mediumint,
  cancelReason varchar,
  accountNumber bigint,
  fontSize tinyint,
  birthDate bigint,
  articleId bigint
);

CREATE TABLE transaction (
  id serial primary key,
  updatedAt decimal,
  nickname binary,
  street timestamp,
  cloudId date,
  attachmentUrl tinyint,
  gender datetime,
  eventDate blob,
  companyName real,
  accessLevel mediumint,
  description bigint,
  contactEmail binary,
  validUntil timestamp
);

CREATE TABLE customerstatus (
  id serial primary key,
  fontFamily float,
  maritalStatus blob,
  cloudId geometry,
  companyName geometry,
  metaTitle datetime,
  instanceId blob,
  emergencyContact tinyint,
  unit tinyint,
  id geometry,
  accountType varchar,
  name timestamp,
  expiryDate text,
  hiddenAt smallint,
  taxRate mediumint,
  colorCode text,
  fingerprint float,
  email timestamp,
  mapId decimal,
  mobileNumber point,
  certificateId datetime
);

CREATE TABLE dstrecordinfotemp (
  id serial primary key,
  addressLine2 bit,
  accountType point,
  orderId datetime,
  validUntil enum,
  displayName serial,
  incidentId decimal,
  dependentId set,
  fontFamily datetime,
  uuid serial,
  copyRight geometry,
  firstName set,
  campaignId blob,
  minLimit serial,
  createdAt date,
  avatar set,
  password smallint,
  isEnabled decimal,
  isRequired blob,
  fontSize double,
  agentId float,
  lastLoginAt set,
  id timestamp,
  isBillable tinyint,
  departmentCode int,
  entityId mediumint,
  contentType real,
  deviceToken timestamp,
  gameId bigint
);

CREATE TABLE transactionmap (
  id serial primary key,
  comment decimal,
  errorCode float,
  mapId decimal,
  phone float,
  dialCode time,
  productCode smallint,
  itemCount time,
  deviceId tinyint,
  dueDateAt bit,
  eventDate bit,
  totalAmount bit,
  validUntil tinyint,
  fileSize tinyint,
  cloudId int,
  businessType text,
  amount binary,
  insuranceId datetime,
  adminNotes boolean,
  isDraft float
);

CREATE TABLE payment (
  id serial primary key,
  taxRate real,
  errorMessage double,
  dashboardId real,
  insertedAt boolean,
  category double,
  manufacturerId double,
  documentId float,
  deviceToken point,
  merchantId point,
  alertType mediumint,
  bankAccount blob,
  chatId timestamp,
  earnedPoints time,
  clientId bigint
);

CREATE TABLE aggcustomer (
  id serial primary key,
  fontFamily serial,
  paymentMethod date,
  flagged float,
  firstName text,
  eventDate tinyint,
  hashKey mediumint,
  loginAttempts mediumint,
  configId set,
  customField1 blob,
  completedAt text,
  courseId bit,
  exportId tinyint,
  billingFrequency time,
  faxNumber decimal,
  contractId time,
  creditScore enum,
  authorId binary,
  followCount smallint,
  amount date,
  token tinyint,
  integrationId set,
  employeeId date,
  priority text,
  billingCycle smallint
);

CREATE TABLE verorder (
  id serial primary key,
  education float,
  createdAt date,
  zipCode float,
  productCode timestamp,
  backupEmail blob,
  earnedPoints geometry,
  lastLoginAt binary,
  brandId real,
  industryType boolean,
  signature blob,
  hourlyRate serial,
  latitude geometry
);

CREATE TABLE app_product (
  id serial primary key,
  manufacturerId int,
  fileType float,
  groupName timestamp
);

CREATE TABLE product_status (
  id serial primary key,
  brandId real,
  metadata date,
  productCode text,
  quantity serial,
  groupName double,
  thumbnail bigint,
  city enum,
  loadTime float,
  facilityId real,
  departmentCode timestamp,
  claimId real,
  displayName tinyint,
  maskType double,
  merchantId blob,
  lastName binary,
  isHidden enum,
  accessLevel float,
  customField2 date,
  token datetime,
  businessType real,
  age timestamp,
  entityId float,
  score int,
  agentId tinyint,
  price timestamp,
  invoiceId mediumint,
  faxNumber varchar,
  moduleId time,
  updatedAt varchar,
  alertType enum,
  moveId time
);

CREATE TABLE vwpayment (
  id serial primary key,
  employeeId int,
  accountNumber date,
  isSystem real,
  emergencyContact point,
  loginAttempts float,
  courseId timestamp,
  companyName timestamp,
  earnedPoints mediumint,
  currencyCode varchar,
  fileName binary,
  isArchived bigint,
  isEnabled serial,
  domainName set,
  updatedAt binary,
  tags mediumint,
  category datetime,
  content boolean,
  password boolean,
  grade datetime,
  globalId tinyint,
  levelId set,
  address enum,
  completedAt tinyint,
  accessLevel blob,
  faxNumber real,
  endPoint varchar,
  insuranceId bigint
);

CREATE TABLE pub_inventory_data (
  id serial primary key,
  enabledAt decimal,
  gateId varchar,
  avatar mediumint,
  longitude blob,
  memberCount mediumint,
  managerId set,
  backupEmail boolean,
  latitude date,
  agentId text,
  cloudId decimal,
  expiryDate text,
  signature datetime,
  dependentId bigint,
  code blob,
  modifiedAt decimal,
  bannerImage blob,
  password serial,
  fileName decimal
);

CREATE TABLE coreaudit2024 (
  id serial primary key,
  dealerId geometry,
  fileSize date,
  completedAt text,
  endPoint set,
  firmwareVersion boolean,
  comment varchar,
  description float,
  domainName decimal,
  departmentCode datetime,
  name set,
  awardDate geometry,
  deletedAt text,
  distributorId blob,
  cvv datetime,
  url text,
  isArchived boolean,
  companyId enum,
  clockIn double,
  street real,
  layerId tinyint,
  apiKey real,
  employeeCode decimal,
  gender int,
  bluetoothId timestamp,
  invoiceId smallint,
  createdAt varchar
);

CREATE TABLE rel_payment (
  id serial primary key,
  cancelReason bit,
  salary time,
  eventDate time,
  copyRight double,
  licenseKey enum,
  followCount binary,
  endDate smallint,
  albumId real,
  isArchived float,
  macAddress double,
  emailStatus int,
  managerId decimal,
  value timestamp,
  price mediumint,
  machineId timestamp,
  campaignId enum,
  isDefault boolean,
  addressLine1 mediumint,
  budgetCode real,
  referralCode blob,
  companyName time,
  description date,
  grade bit,
  deviceType enum,
  connectionString blob,
  longitude double,
  avatar mediumint,
  username varchar
);

CREATE TABLE order_archive (
  id serial primary key,
  addressLine1 text,
  avatar date,
  cardNumber enum,
  enrollmentDate datetime,
  apiVersion blob,
  contactEmail decimal,
  password point,
  deletedAt double,
  contactPhone timestamp,
  entryPoint point,
  ipAddress tinyint,
  role real,
  value enum,
  isArchived smallint,
  lockoutEnd boolean,
  frameRate tinyint,
  category bit,
  dashboardId timestamp,
  longitude geometry,
  flagged date,
  keywords serial,
  entityId text,
  shippingAddress decimal,
  merchantId blob,
  authMethod real,
  isFeatured date,
  department point,
  deviceToken binary,
  score enum,
  signature tinyint
);

CREATE TABLE customer (
  id serial primary key,
  contactName int,
  metaTitle binary,
  entryPoint text,
  accountStatus float,
  modifiedAt timestamp,
  deviceType set,
  feedId serial,
  maxLimit serial,
  authMethod datetime,
  linkId int,
  facilityId binary,
  entityId blob,
  managerId time,
  homePhone date,
  marketId serial,
  exchangeRate time,
  dailyLimit int,
  paymentMethod real,
  thumbnail blob,
  enrollmentDate timestamp,
  cancelReason tinyint,
  title float
);

CREATE TABLE verrecord (
  id serial primary key,
  amount bigint,
  courseId geometry,
  token text,
  address blob,
  buildNumber text,
  entryPoint double,
  country boolean,
  likeCount datetime,
  dependentId decimal,
  accountNumber set,
  employeeId enum,
  createdAt enum,
  hostName int,
  avatar point,
  colorCode real,
  exportId timestamp,
  isBillable enum,
  cityName blob,
  email timestamp,
  accountStatus int,
  firstName decimal,
  city enum,
  creditCard decimal,
  longitude binary,
  firmwareVersion geometry,
  friendId time,
  customerGroup text,
  content text,
  name time,
  signature bit
);

CREATE TABLE usertemp (
  id serial primary key,
  price serial,
  email serial,
  isVerified text,
  minValue decimal,
  mapId set,
  avatar point,
  brandId decimal,
  fileName double,
  height boolean,
  updatedAt set,
  version bigint,
  currencyCode smallint,
  billingFrequency text,
  isRequired smallint,
  machineId real,
  entityId int,
  creditLimit time,
  username double,
  isAdmin smallint,
  isBillable time,
  startDate mediumint,
  activeDevices decimal,
  discount blob,
  phone double
);

CREATE TABLE organization (
  id serial primary key,
  articleId blob,
  dialCode geometry,
  industryType real,
  deviceToken binary,
  employeeId mediumint,
  bluetoothId time,
  zipCode real,
  instanceId double,
  loginCount int,
  exportId mediumint,
  favoriteCount decimal,
  firmwareVersion boolean,
  enabledAt datetime,
  value enum,
  bankAccount bigint,
  timezone serial,
  type text,
  isLocked datetime,
  cardHolder timestamp,
  downloadCount decimal,
  isEnabled smallint,
  flagged real,
  departmentCode timestamp
);

CREATE TABLE appproductstatus (
  id serial primary key,
  displayName text,
  indexKey binary,
  lockoutEnd bit,
  hourlyRate int,
  updatedAt datetime,
  loadTime bigint,
  enabledAt set,
  alertType varchar,
  description boolean,
  dependentId bigint,
  brandId real,
  middleName bit,
  accessLevel enum,
  agentId timestamp,
  clockIn bigint,
  companyId time
);

CREATE TABLE transaction (
  id serial primary key,
  moduleId tinyint,
  deliveryDate varchar,
  insuranceId text,
  sku real,
  deviceId binary,
  comment enum,
  documentId varchar,
  attemptCount smallint,
  isPublic set,
  id varchar,
  completionRate binary,
  contactEmail tinyint,
  defaultValue datetime,
  checkInTime date,
  category time,
  companyLogo timestamp,
  faxNumber geometry,
  zipCode geometry,
  mimeType real,
  attachmentUrl point,
  address blob,
  licenseKey timestamp,
  type serial,
  levelId bigint,
  ipAddress datetime
);

