CREATE TABLE fact_account_type (
  id serial primary key,
  timezone varchar,
  exchangeRate bit,
  handlerId serial,
  email geometry,
  currency datetime,
  emailStatus datetime,
  minValue binary,
  checkOutTime point,
  couponCode blob,
  integrationId int,
  lastName float,
  expiryMonth datetime,
  title real,
  keyId blob,
  createdAt point,
  phone enum,
  version text,
  avatar decimal,
  deviceId real
);

CREATE TABLE tmpuser (
  id serial primary key,
  completedAt blob,
  mapId int,
  cvv decimal,
  maritalStatus serial,
  itemCount decimal,
  countryCode bit,
  salary decimal,
  isDraft timestamp,
  clientId timestamp,
  currency text,
  iconPath serial,
  creditLimit tinyint,
  macAddress tinyint,
  contractId blob,
  email double,
  backupEmail date,
  licenseKey set,
  enabledAt set,
  fromDate mediumint,
  customField1 timestamp
);

CREATE TABLE payment (
  id serial primary key,
  labelText binary,
  metaTitle tinyint,
  cardHolder date,
  longitude blob,
  merchantId timestamp,
  certificateId real,
  group tinyint,
  messageId decimal,
  downloadCount timestamp,
  grade tinyint,
  dealerId enum,
  currencyCode enum,
  macAddress bigint,
  checkInTime varchar
);

CREATE TABLE company (
  id serial primary key,
  expiryDate varchar,
  group decimal,
  firstName real,
  domainName int,
  levelId enum,
  department geometry,
  groupName point,
  cartId time,
  meterNumber decimal,
  entityId date,
  folderPath bit,
  accountType time,
  fingerprint datetime,
  contactEmail serial,
  deactivatedAt varchar,
  shippingAddress tinyint,
  dialCode int
);

CREATE TABLE account (
  id serial primary key,
  role int,
  accountType timestamp,
  billingCycle bit,
  listId double,
  fileHash double,
  maskType boolean,
  claimId boolean,
  invoiceId date,
  editedAt double,
  phone float,
  filterType varchar,
  maritalStatus time,
  maxLimit point,
  status geometry,
  listingId real,
  city smallint,
  exportId timestamp,
  isRequired time,
  firstName bit,
  indexKey enum,
  password tinyint
);

CREATE TABLE company (
  id serial primary key,
  labelText text,
  memberCount double,
  contactName tinyint,
  cardHolder time,
  domainName bigint,
  billingCycle mediumint,
  courseId bigint,
  folderPath set,
  duration bigint,
  customerGroup time,
  street binary,
  attachmentUrl point,
  exchangeRate blob
);

CREATE TABLE app_user_notifications (
  id serial primary key,
  courseId blob,
  coverImage time,
  bookingDate tinyint,
  name bigint,
  listingId date,
  locationId tinyint,
  authorId timestamp,
  comment bigint,
  category bit,
  costCenter timestamp,
  contactEmail real,
  hashKey varchar,
  fromDate point,
  cardHolder blob
);

CREATE TABLE transaction (
  id serial primary key,
  merchantId blob,
  isArchived blob,
  birthDate float,
  metaTitle bigint,
  loginAttempts date,
  mainImage bit,
  dealerId real,
  isDraft boolean,
  manufacturerId real,
  clockIn boolean,
  entryPoint decimal,
  iconPath varchar,
  updatedAt binary
);

CREATE TABLE config (
  id serial primary key,
  height smallint,
  invoiceId double,
  longitude geometry,
  accountNumber boolean,
  customerGroup varchar,
  fromDate bigint,
  birthDate serial,
  group decimal,
  thumbnail binary,
  domainName double,
  cacheKey datetime,
  middleName set,
  entityId point,
  backupEmail geometry,
  loginCount double,
  documentId time,
  customField2 binary,
  signature varchar,
  costCenter real,
  validUntil boolean,
  memberCount text,
  minLimit mediumint
);

CREATE TABLE product (
  id serial primary key,
  department datetime,
  instanceId binary,
  isRequired datetime,
  productCode int,
  flagged geometry,
  errorCode varchar,
  exchangeRate mediumint,
  maritalStatus real,
  isSystem double,
  isVerified varchar,
  creditLimit varchar
);

CREATE TABLE log_audit_notifications (
  id serial primary key,
  contactName int,
  nickname set,
  billingCycle date,
  completedAt serial,
  algorithm varchar,
  hiddenAt double,
  balance time,
  avatar bigint,
  flagged timestamp,
  education bit,
  apiKey set,
  isDefault blob,
  indexKey smallint,
  blogId time,
  dashboardId decimal
);

CREATE TABLE fact_record (
  id serial primary key,
  latitude point,
  certificateId decimal,
  isEnabled timestamp,
  department binary,
  itemCount point,
  deletedAt geometry,
  depositAmount float,
  fontSize bigint,
  accessLevel mediumint,
  version boolean
);

CREATE TABLE tmp_config_meta (
  id serial primary key,
  mapId boolean,
  addressLine2 real,
  dateFormat boolean,
  countryCode enum,
  cvv date,
  discount double
);

CREATE TABLE tmp_audit_new (
  id serial primary key,
  hashKey enum,
  configId real,
  customerGroup date,
  faxNumber point
);

CREATE TABLE vworder2025 (
  id serial primary key,
  mobileNumber float,
  colorCode varchar,
  certificateId bigint,
  foregroundColor boolean,
  facilityId binary,
  isDefault enum,
  contactName geometry,
  title point,
  entryPoint smallint,
  adminNotes geometry
);

CREATE TABLE pubuserrel (
  id serial primary key,
  algorithm time,
  countryCode boolean,
  incidentId datetime,
  isFeatured serial,
  bluetoothId tinyint,
  lastName date,
  mobileNumber smallint,
  lastLoginAt blob,
  fingerprint datetime,
  activeDevices int,
  licenseKey int,
  entryPoint serial,
  documentId tinyint,
  integrationId boolean,
  city timestamp,
  forwardTo text,
  contractId point,
  dailyLimit boolean,
  score mediumint,
  fileType smallint,
  isDeleted datetime,
  balance bigint,
  salary date,
  isEnabled bigint,
  dimension time,
  companyName geometry
);

CREATE TABLE fact_config_archive_legacy (
  id serial primary key,
  globalId text,
  isEnabled timestamp,
  clockIn date,
  certificateId mediumint,
  addressLine2 smallint,
  address enum,
  accessLevel varchar,
  dailyLimit boolean,
  shippingAddress decimal,
  updatedAt mediumint,
  mimeType bit,
  size geometry,
  attemptCount datetime,
  minLimit binary,
  messageId point,
  logLevel date,
  contactEmail set,
  exchangeRate bit,
  instanceId float
);

CREATE TABLE dst_audit_2024 (
  id serial primary key,
  thumbnail boolean,
  balance set,
  merchantId varchar,
  enabledAt datetime,
  countryCode text
);

CREATE TABLE vw_product (
  id serial primary key,
  employmentDate serial,
  moveId serial,
  age real,
  validUntil point,
  gameId decimal,
  marketId timestamp,
  productCode time,
  name decimal,
  campaignId decimal,
  paymentMethod enum,
  manufacturerId time,
  backupEmail bit,
  ipAddress timestamp
);

CREATE TABLE ver_order (
  id serial primary key,
  lastSeenAt text,
  logLevel int,
  taxRate boolean,
  forwardTo real,
  loadTime int,
  coordinateY double,
  cardHolder point,
  linkId blob,
  fileHash smallint,
  addressLine2 float
);

CREATE TABLE record_seg (
  id serial primary key,
  unit tinyint,
  expiryDate serial,
  campaignId double,
  geoLocation timestamp,
  gender point,
  accountNumber tinyint,
  isRequired tinyint,
  createdAt int,
  displayOrder serial,
  downloadCount float,
  floorNumber geometry,
  group set,
  jobTitle mediumint,
  hiddenAt enum,
  abandonedCartId text,
  accountType geometry,
  fileType boolean,
  emergencyContact timestamp,
  accessLevel tinyint,
  marketId set,
  customerId double,
  avatar blob,
  dailyLimit time,
  price blob,
  actionType blob,
  linkId enum,
  url int,
  version mediumint,
  category int,
  billingCycle mediumint,
  isDraft double
);

CREATE TABLE transaction_new (
  id serial primary key,
  content datetime,
  balance double,
  errorCode date,
  dependentId int,
  id binary,
  hashKey boolean,
  managerId int,
  licenseKey enum,
  joinDate bit,
  customerGroup timestamp
);

CREATE TABLE tmp_audit (
  id serial primary key,
  ipAddress timestamp,
  geoLocation varchar,
  discountCode float,
  title float,
  emailStatus point,
  isLocked double,
  linkId varchar,
  integrationId tinyint,
  creditCard geometry,
  tags decimal,
  mimeType double,
  password enum,
  group geometry,
  cardNumber geometry,
  mapId blob
);

CREATE TABLE fact_audit_2024 (
  id serial primary key,
  entityId enum,
  coverImage text,
  editedAt serial,
  longitude float,
  balance bigint,
  height serial,
  coordinateY point,
  indexKey int,
  machineId bigint,
  lastLoginAt double,
  group date,
  faxNumber point,
  state real,
  guestId point,
  accountType bit,
  hiddenAt real,
  enabledAt datetime,
  agentId text,
  friendId bigint,
  address decimal,
  dialCode text,
  lastName text,
  loadTime serial,
  errorCode datetime,
  avatar blob,
  customField1 date,
  endDate varchar,
  attachmentUrl varchar,
  analyticsId blob,
  content bigint,
  feedId enum
);

CREATE TABLE transaction (
  id serial primary key,
  backupEmail int,
  instanceId time,
  department serial,
  timezone datetime,
  type bit,
  isBillable geometry,
  tags smallint,
  macAddress date,
  category point,
  isPublic bit,
  expiryYear real,
  isRequired time,
  dailyLimit tinyint,
  childId float,
  description boolean,
  password decimal,
  loginAttempts text,
  indexKey serial,
  downloadCount blob,
  deactivatedAt boolean,
  machineId bigint,
  address bigint,
  score datetime,
  fileName bigint,
  content blob,
  amount mediumint,
  loginCount bit
);

CREATE TABLE transaction_log (
  id serial primary key,
  fileHash mediumint,
  cityName mediumint,
  currencyCode boolean,
  mimeType set,
  education enum,
  courseId smallint,
  errorCode tinyint,
  fromDate date,
  faxNumber decimal,
  manufacturerId blob,
  gender real,
  moduleId bigint,
  contractId real,
  floorNumber boolean,
  coverImage bigint,
  defaultValue bit,
  likeCount tinyint,
  customerId bit,
  accountType blob,
  layerId tinyint,
  homePhone timestamp,
  city mediumint
);

CREATE TABLE record (
  id serial primary key,
  isDraft float,
  browserType blob,
  coordinateY smallint,
  shippingAddress set,
  balance text,
  orderId text,
  title binary,
  cardHolder boolean,
  fromDate datetime,
  password bigint,
  deliveryDate blob,
  companyLogo mediumint,
  isSystem set,
  loginCount datetime,
  incidentId date,
  attemptCount date,
  homePhone mediumint,
  dailyLimit float,
  chatId decimal,
  cloudId mediumint,
  memberCount double,
  version varchar,
  zipCode tinyint,
  country serial,
  likeCount date
);

CREATE TABLE cpyorganizationhist (
  id serial primary key,
  facilityId date,
  customField2 bit,
  attemptCount point,
  middleName mediumint,
  articleId binary,
  gameId blob,
  itemCount varchar,
  fromDate smallint,
  currencyCode point,
  category timestamp,
  campaignId bigint,
  dependentId mediumint,
  budgetCode point,
  comment date,
  indexKey timestamp,
  id bigint,
  expiryYear double,
  authMethod binary,
  isBillable datetime,
  depositAmount enum,
  jobTitle real,
  version set,
  isEnabled datetime,
  token datetime,
  amount datetime,
  createdAt binary,
  deletedAt blob,
  creditLimit float,
  mimeType time,
  priority date,
  isDefault boolean
);

CREATE TABLE fact_company (
  id serial primary key,
  category time,
  uuid geometry,
  employeeId tinyint,
  totalAmount point,
  coordinateY blob,
  fingerprint real,
  meterNumber blob,
  albumId timestamp,
  isDeleted date,
  coordinateX bit,
  contactPhone date,
  name datetime,
  logLevel tinyint,
  memberCount datetime,
  createdAt geometry,
  phone enum,
  password boolean,
  exchangeRate bit,
  isBillable binary,
  lastName text,
  isHidden double,
  currencyCode smallint,
  customField1 boolean
);

CREATE TABLE inventory_archive_2024 (
  id serial primary key,
  id decimal,
  phone serial,
  currencyCode smallint,
  marketId text,
  cacheKey serial,
  dimension real,
  attemptCount text,
  accountType enum,
  instructorId smallint,
  accountStatus varchar,
  fromDate blob,
  contactEmail serial,
  username decimal,
  birthDate date,
  folderPath int,
  displayOrder float,
  departmentCode date,
  industryType bigint,
  dataSource date,
  isActive decimal,
  locationId binary,
  facilityId point,
  discount binary,
  colorCode timestamp,
  dealerId double,
  apiVersion int,
  postalCode smallint,
  inactiveAt bigint,
  group tinyint
);

CREATE TABLE user (
  id serial primary key,
  url double,
  mainImage text,
  feedbackId double,
  menuId varchar,
  completedAt time,
  lastLoginAt blob,
  machineId geometry,
  isRequired enum,
  batchId float,
  insertedAt binary,
  zipCode boolean,
  rating mediumint,
  salary date,
  weight point,
  city binary,
  costCenter time,
  isAdmin double,
  expiryDate timestamp,
  avatar mediumint,
  maxLimit serial,
  discountCode point,
  employeeId timestamp
);

CREATE TABLE log_user (
  id serial primary key,
  birthDate double,
  updatedAt binary,
  houseNumber enum,
  quantity double,
  downloadCount bit,
  fontSize real,
  isFeatured float,
  albumId bigint,
  contentType date,
  eventDate serial,
  apiKey bigint,
  score mediumint,
  currency double,
  bluetoothId bit,
  moveId int,
  keyId boolean,
  group enum,
  deviceType double
);

CREATE TABLE pub_account_new (
  id serial primary key,
  bluetoothId set,
  email geometry,
  duration bit,
  folderPath binary,
  monthlyRate mediumint,
  completedAt boolean,
  street point,
  thumbnail mediumint,
  metaDescription serial,
  employeeCode mediumint,
  keyId bit,
  campaignId boolean,
  coordinateY serial,
  addressLine1 varchar,
  validUntil bit,
  uuid int,
  isArchived geometry,
  countryCode double,
  isHidden mediumint,
  budgetCode bigint
);

CREATE TABLE vw_transaction (
  id serial primary key,
  expiryDate smallint,
  groupName set,
  minLimit geometry,
  defaultLang blob,
  entityId enum,
  tags serial,
  isFeatured enum,
  contentType blob,
  checkOutTime decimal,
  levelId smallint,
  endPoint double,
  linkId varchar,
  deviceToken text,
  ipAddress text,
  phone text,
  clockIn mediumint,
  bookingDate tinyint,
  articleId varchar,
  updatedAt serial,
  insuranceId set,
  inactiveAt bigint,
  alertType bit,
  category boolean
);

CREATE TABLE tmp_account_seg (
  id serial primary key,
  currency blob,
  budgetCode mediumint,
  dimension binary,
  dataSource text,
  apiKey varchar,
  fontSize mediumint,
  deviceType real,
  chatId blob,
  employeeId mediumint,
  appVersion time,
  deletedAt binary,
  customField2 serial,
  username decimal,
  loginCount time,
  type blob,
  employmentDate double,
  childId tinyint,
  emailStatus boolean,
  gateId text
);

CREATE TABLE transaction (
  id serial primary key,
  email enum,
  addressLine1 mediumint,
  attachmentUrl tinyint,
  monthlyRate date,
  employeeCode float,
  cardNumber datetime,
  listingId mediumint,
  fontSize float,
  memberCount float,
  displayName varchar,
  activeDevices enum,
  budgetCode text
);

CREATE TABLE agg_config_seg (
  id serial primary key,
  accessLevel double,
  businessType bit,
  messageId time,
  deliveryDate double,
  checkInTime serial,
  chargeId text,
  manufacturerId double,
  contactEmail binary,
  facilityId binary,
  authorId real,
  apiKey geometry,
  attemptCount point,
  countryCode boolean,
  houseNumber enum,
  deviceType bit,
  distributorId double
);

CREATE TABLE order (
  id serial primary key,
  loginAttempts tinyint,
  listId binary,
  fontFamily mediumint,
  content decimal,
  earnedPoints text,
  comment smallint,
  metaDescription binary,
  apiKey bit,
  status time,
  bannerImage bigint
);

CREATE TABLE cpy_payment_v2 (
  id serial primary key,
  dimension set,
  algorithm timestamp,
  customField2 real,
  errorMessage point,
  contractId binary,
  metaTitle real,
  feedId real,
  instanceId point,
  maxLimit smallint,
  exportId set,
  creditScore text,
  cartId point,
  cardNumber enum,
  endPoint time,
  backupEmail decimal,
  floorNumber float,
  completedAt enum,
  value set,
  favoriteCount binary,
  lastSeenAt bigint,
  inactiveAt smallint,
  shippingAddress decimal,
  coordinateX point,
  loadTime mediumint,
  fileName mediumint,
  abandonedCartId mediumint,
  chatId serial,
  paymentMethod bigint,
  coordinateY bigint,
  nickname bit
);

CREATE TABLE user (
  id serial primary key,
  lastSeenAt varchar,
  deviceToken point,
  currency float,
  token set,
  apiKey datetime,
  coordinateX datetime,
  cardNumber bit,
  createdAt mediumint,
  attachmentUrl boolean,
  friendId date,
  cardHolder blob,
  maritalStatus int,
  dashboardId smallint,
  metaTitle bit,
  creditLimit double,
  itemCount double,
  category tinyint,
  distributorId double,
  licenseKey bigint,
  accessLevel float,
  email bit,
  expiryYear double,
  address smallint,
  floorNumber timestamp,
  sku time,
  albumId blob,
  orderId serial,
  street int,
  rating mediumint,
  phone binary
);

CREATE TABLE config_map (
  id serial primary key,
  isPublic bigint,
  appVersion set,
  fileSize enum,
  authMethod geometry,
  isRequired blob,
  expiryMonth enum,
  postalCode tinyint,
  agentId text,
  macAddress blob
);

CREATE TABLE src_record_info (
  id serial primary key,
  metaKeywords date,
  token double,
  insuranceId point,
  guestId mediumint,
  iconPath varchar,
  dependentId mediumint,
  audioUrl decimal,
  appVersion date,
  quantity enum,
  endPoint bigint,
  isDeleted float,
  menuId serial,
  inactiveAt point,
  handlerId time,
  content geometry,
  url date,
  isVerified binary,
  linkId date,
  fingerprint set,
  industryType enum,
  deliveryDate real,
  cardNumber mediumint,
  attachmentUrl serial,
  messageId double,
  unit bit,
  birthDate bit,
  height bit,
  editedAt varchar,
  weight point,
  homePhone bigint,
  zipCode bit
);

CREATE TABLE rel_user_map (
  id serial primary key,
  coverImage enum,
  age enum,
  formatType double,
  claimId datetime,
  appVersion set,
  addressLine1 real,
  invoiceId float,
  endPoint set,
  indexKey serial
);

CREATE TABLE transaction (
  id serial primary key,
  errorCode date,
  group varchar,
  exchangeRate blob,
  name bigint,
  deliveryDate date,
  billingFrequency datetime,
  contractId bit,
  creditLimit text,
  phone int,
  insuranceId boolean,
  domainName binary
);

CREATE TABLE rel_record_meta (
  id serial primary key,
  coordinateX blob,
  url blob,
  height blob,
  paymentMethod bit,
  loginAttempts serial,
  expiryYear boolean,
  dialCode varchar,
  customField2 float,
  priority double,
  employeeCode boolean,
  companyLogo mediumint,
  metadata decimal,
  rating serial,
  expiryMonth blob,
  isAdmin smallint,
  employeeId datetime,
  password int,
  isEnabled date,
  actionType set,
  completionRate bigint,
  tags timestamp,
  clockIn bit,
  isBillable date,
  gameId bigint,
  accountType text,
  completedAt date,
  cvv time,
  deactivatedAt timestamp,
  monthlyRate serial,
  maskType date
);

CREATE TABLE user_archive_2025 (
  id serial primary key,
  localeId decimal,
  folderPath set,
  currencyCode varchar,
  dimension mediumint,
  country mediumint,
  completionRate smallint
);

CREATE TABLE orderstatus (
  id serial primary key,
  apiVersion binary,
  expiryMonth time,
  expiryYear int,
  city smallint,
  cloudId binary,
  buildNumber date,
  minLimit serial,
  education tinyint,
  billingCycle timestamp,
  zipCode time,
  awardDate int,
  actionType text,
  comment time,
  description double,
  authMethod varchar,
  ipAddress enum,
  creditLimit double
);

CREATE TABLE transaction (
  id serial primary key,
  monthlyRate binary,
  discountCode int,
  street mediumint,
  copyRight real,
  labelText tinyint,
  friendId decimal,
  completedAt double,
  version bigint,
  uuid serial,
  colorCode bit,
  accountType real,
  apiKey int,
  isDraft bit,
  creditCard timestamp,
  driverLicense blob,
  ipAddress int,
  eventDate serial,
  countryCode smallint,
  name mediumint,
  dependentId varchar,
  macAddress bit,
  createdAt tinyint,
  type timestamp,
  mobileNumber mediumint,
  globalId mediumint
);

CREATE TABLE payment (
  id serial primary key,
  indexKey timestamp,
  productCode mediumint,
  certificateId enum,
  enabledAt time,
  amount float,
  customField1 serial
);

CREATE TABLE tmp_company_div (
  id serial primary key,
  comment serial,
  alertType float,
  employeeCode binary,
  meterNumber serial,
  foregroundColor binary,
  isArchived serial,
  name serial,
  clockIn geometry,
  claimId blob,
  url bigint,
  metaKeywords real,
  logLevel real,
  keywords time,
  completionRate datetime,
  age real,
  maxLimit real,
  mapId serial,
  fingerprint int,
  email serial,
  latitude enum,
  costCenter boolean,
  authMethod serial,
  price bit,
  configId varchar,
  extractId time,
  deviceToken int,
  address decimal,
  mimeType serial,
  maskType bigint
);

