CREATE TABLE company (
  id serial primary key,
  discount point,
  accountType timestamp,
  birthDate boolean,
  version tinyint,
  courseId serial
);

CREATE TABLE dst_record_archive (
  id serial primary key,
  couponCode enum,
  flagged text,
  domainName datetime
);

CREATE TABLE priv_user (
  id serial primary key,
  forwardTo varchar,
  hiddenAt decimal,
  hashKey bit,
  employeeCode bigint,
  machineId geometry,
  unit date,
  isAdmin geometry,
  bannerImage varchar,
  employeeId timestamp,
  firmwareVersion date,
  minValue geometry,
  cardNumber mediumint,
  gateId text,
  gameId serial,
  audioUrl decimal,
  exchangeRate time,
  houseNumber double,
  email geometry,
  errorMessage tinyint,
  birthDate blob
);

CREATE TABLE product (
  id serial primary key,
  content binary,
  defaultLang serial
);

CREATE TABLE organization (
  id serial primary key,
  isBillable decimal,
  driverLicense enum,
  expiryDate smallint,
  countryCode serial,
  analyticsId float,
  completedAt text,
  isLocked enum,
  listId enum,
  token serial,
  companyName blob,
  invoiceId mediumint,
  bankAccount varchar,
  orderStatus bit,
  cancelReason binary,
  audioUrl float,
  salary boolean,
  content date,
  email varchar,
  isHidden bigint,
  currencyCode bigint,
  handlerId set,
  accessLevel set,
  discount date,
  clockIn point,
  firstName double,
  buildNumber bit,
  metadata enum,
  displayOrder binary,
  unit text,
  description timestamp,
  dailyLimit bigint
);

CREATE TABLE ver_user_status (
  id serial primary key,
  globalId bit,
  authToken boolean,
  keyId decimal,
  connectionString int,
  loadTime smallint,
  cloudId smallint,
  createdAt varchar,
  endPoint timestamp,
  faxNumber binary,
  department datetime,
  price tinyint,
  bluetoothId binary,
  apiVersion real,
  currencyCode float,
  configId set,
  isBillable real
);

CREATE TABLE config_out (
  id serial primary key,
  firstName point,
  billingFrequency blob,
  comment smallint,
  isEnabled float,
  fileSize timestamp,
  isSystem boolean,
  copyRight bigint,
  firmwareVersion int,
  ipAddress boolean,
  apiKey tinyint,
  isVerified tinyint,
  mainImage datetime,
  contactName bit,
  incidentId serial
);

CREATE TABLE customer2025 (
  id serial primary key,
  postalCode text,
  handlerId text,
  formatType text,
  deletedAt text,
  version geometry,
  itemCount text,
  costCenter point,
  companyName float,
  code bigint,
  startDate bit,
  authMethod real,
  unit bit,
  alertType real,
  signature set,
  dataSource real,
  firstName double,
  discount boolean,
  accountType bit,
  contactName geometry,
  importId date,
  birthDate smallint,
  departmentCode decimal
);

CREATE TABLE company_legacy (
  id serial primary key,
  isEnabled float,
  billingFrequency float,
  password serial,
  listId serial,
  incidentId boolean,
  facilityId real,
  comment mediumint,
  geoLocation real,
  employeeCode boolean,
  isActive timestamp,
  age text,
  dateFormat float,
  depositAmount blob,
  createdAt serial,
  employeeId date,
  contentType real,
  messageId varchar,
  maritalStatus int,
  category text
);

CREATE TABLE tmp_record_v2 (
  id serial primary key,
  invoiceId binary,
  algorithm float,
  orderId smallint,
  customField1 blob,
  validUntil time,
  createdAt serial,
  username date,
  zipCode mediumint,
  addressLine1 datetime,
  cloudId varchar,
  blogId serial,
  fingerprint float,
  education datetime,
  mobileNumber decimal,
  batchId smallint,
  facilityId geometry,
  moveId varchar,
  listId time,
  updatedAt point,
  thumbnail set,
  fileHash bit,
  folderPath text,
  foregroundColor blob,
  campaignId text,
  creditCard timestamp,
  memberCount varchar
);

CREATE TABLE record_2024 (
  id serial primary key,
  country mediumint,
  value time,
  cardHolder varchar,
  depositAmount real,
  entityId mediumint,
  isDeleted point,
  likeCount point,
  fileType bit,
  status real,
  quantity text,
  modifiedAt timestamp,
  fromDate enum,
  fileSize serial,
  apiVersion blob,
  handlerId smallint,
  size mediumint,
  weight timestamp,
  discountCode serial,
  token timestamp,
  avatar int,
  costCenter double,
  dealerId date,
  fileName timestamp,
  actionType binary
);

CREATE TABLE product (
  id serial primary key,
  apiVersion tinyint,
  integrationId set,
  title double
);

CREATE TABLE transactiondata (
  id serial primary key,
  quantity bigint,
  firmwareVersion bigint,
  lockoutEnd date,
  documentId serial,
  companyName int,
  zipCode float,
  category double,
  email timestamp,
  headerImage serial,
  linkId int,
  hostName boolean,
  endPoint tinyint,
  deliveryDate binary,
  firstName binary,
  postalCode time,
  dashboardId serial,
  city geometry,
  managerId timestamp,
  hashKey double,
  layerId int,
  name blob,
  bookingDate varchar,
  appVersion set,
  checkOutTime double,
  floorNumber time,
  customField1 serial
);

CREATE TABLE customer (
  id serial primary key,
  algorithm varchar,
  monthlyRate serial,
  instanceId decimal,
  handlerId text,
  isActive serial,
  amount mediumint,
  followCount tinyint,
  description serial,
  companyId smallint,
  isRequired blob,
  addressLine1 date,
  completedAt int,
  connectionString geometry,
  labelText datetime,
  category mediumint,
  type decimal,
  lastName boolean,
  ipAddress smallint,
  batchId mediumint,
  importId mediumint,
  coordinateY set,
  fromDate blob,
  likeCount int,
  fingerprint varchar
);

CREATE TABLE dst_order (
  id serial primary key,
  modifiedAt date,
  geoLocation smallint,
  itemCount time,
  managerId double,
  middleName enum,
  companyLogo point,
  duration boolean,
  salary timestamp,
  listingId binary,
  blogId real,
  defaultLang timestamp,
  apiKey set,
  facilityId date,
  instanceId enum,
  timezone smallint,
  accountNumber time,
  discountCode time,
  cacheKey geometry,
  contactName tinyint,
  attachmentUrl binary,
  merchantId text,
  expiryDate time,
  algorithm tinyint,
  taxRate int,
  mobileNumber enum,
  metaKeywords serial,
  incidentId blob,
  education boolean,
  addressLine2 mediumint
);

CREATE TABLE src_company_archive (
  id serial primary key,
  orderId timestamp,
  startDate timestamp,
  emailStatus serial,
  balance bit,
  discount enum
);

CREATE TABLE usertype (
  id serial primary key,
  group bit,
  depositAmount text,
  country smallint,
  companyName geometry,
  gateId time,
  avatar text,
  completedAt datetime,
  lastSeenAt decimal,
  phone double,
  id geometry,
  dailyLimit decimal,
  dashboardId text,
  adminNotes blob,
  postalCode text,
  insertedAt binary,
  instanceId tinyint,
  employeeCode set,
  orderId set
);

CREATE TABLE account (
  id serial primary key,
  accountNumber date,
  localeId tinyint,
  expiryMonth double,
  forwardTo geometry,
  flagged enum,
  homePhone set,
  defaultValue boolean,
  friendId bigint,
  paymentMethod enum,
  mobileNumber tinyint,
  middleName date,
  displayOrder time,
  listId decimal,
  childId int,
  feedbackId set
);

CREATE TABLE audit (
  id serial primary key,
  enrollmentDate varchar,
  metaDescription set,
  cardHolder set,
  isRequired geometry,
  sessionId binary,
  customField1 set,
  favoriteCount double,
  avatar smallint,
  maritalStatus text,
  nickname binary,
  category geometry,
  managerId int,
  isActive time,
  completionRate timestamp,
  isEnabled bit
);

CREATE TABLE company (
  id serial primary key,
  floorNumber geometry,
  incidentId enum,
  accountType point,
  billingFrequency text,
  employeeId bit,
  keywords serial,
  maritalStatus double,
  clientId set,
  eventDate blob
);

CREATE TABLE config (
  id serial primary key,
  awardDate real,
  cityName boolean,
  email geometry,
  emergencyContact smallint,
  mimeType int,
  friendId bigint,
  fileSize int,
  comment time,
  handlerId enum,
  documentId blob,
  token binary,
  channelId decimal,
  id geometry,
  locationId varchar,
  likeCount set,
  customField1 double,
  status smallint,
  group blob,
  sku varchar,
  backupEmail real,
  expiryDate boolean,
  cloudId time,
  paymentMethod text,
  mainImage timestamp,
  licenseKey set
);

CREATE TABLE src_user (
  id serial primary key,
  ipAddress int,
  quantity tinyint,
  courseId geometry,
  comment tinyint,
  url smallint,
  homePhone int,
  loadTime time,
  addressLine2 serial,
  errorCode datetime,
  completedAt point,
  balance timestamp,
  handlerId set,
  clockOut bigint,
  latitude datetime,
  adminNotes geometry,
  employeeId boolean,
  grade text,
  entryPoint time,
  deactivatedAt enum,
  isBillable date,
  cacheKey smallint
);

CREATE TABLE ref_order (
  id serial primary key,
  channelId time,
  amount set
);

CREATE TABLE pub_audit (
  id serial primary key,
  countryCode datetime,
  sessionId point,
  grade double,
  accountNumber decimal,
  displayOrder time,
  title boolean,
  foregroundColor geometry,
  contentType timestamp,
  companyLogo datetime,
  address enum,
  layerId smallint,
  endPoint bigint,
  shippingAddress binary,
  levelId bigint,
  deliveryDate text,
  invoiceId mediumint,
  longitude mediumint,
  description real,
  analyticsId int,
  handlerId int,
  isDefault float,
  coverImage enum,
  completedAt boolean,
  dailyLimit geometry
);

CREATE TABLE customer_v1 (
  id serial primary key,
  departmentCode serial,
  browserType time,
  maritalStatus timestamp
);

CREATE TABLE inventory (
  id serial primary key,
  chargeId varchar,
  businessType tinyint,
  address float,
  logLevel varchar,
  integrationId blob,
  name date,
  createdAt mediumint,
  emailStatus decimal,
  title tinyint,
  maskType bit,
  deviceId date
);

CREATE TABLE core_order_log (
  id serial primary key,
  category blob,
  paymentMethod timestamp,
  gender int,
  country point,
  expiryMonth bit,
  role boolean,
  employmentDate int,
  inactiveAt double,
  version geometry,
  url real,
  name point,
  invoiceId varchar,
  taxRate smallint,
  sessionId mediumint,
  signature geometry,
  configId set,
  completedAt real,
  itemCount point,
  homePhone set,
  avatar decimal,
  employeeCode serial,
  orderId binary,
  enrollmentDate blob,
  moveId set,
  merchantId int,
  houseNumber decimal,
  lastSeenAt datetime,
  dashboardId enum,
  courseId time,
  dataSource text,
  bookingDate timestamp
);

CREATE TABLE sys_inventory (
  id serial primary key,
  couponCode int,
  isEnabled geometry,
  expiryMonth decimal,
  accountNumber boolean,
  extractId datetime,
  lockoutEnd float,
  birthDate datetime,
  isDeleted decimal,
  contactName bigint,
  localeId date,
  education date,
  marketId mediumint,
  group serial,
  displayName boolean,
  integrationId mediumint,
  size enum,
  feedbackId int,
  copyRight timestamp,
  flagged timestamp,
  createdAt varchar,
  firmwareVersion real,
  authMethod double,
  insuranceId bigint,
  machineId serial,
  fileType smallint,
  dashboardId enum,
  coordinateY blob,
  dimension set,
  maxLimit date,
  latitude real
);

CREATE TABLE tbl_organization (
  id serial primary key,
  alertType time,
  metaTitle bigint,
  bookingDate time,
  category boolean,
  cityName date,
  street text,
  earnedPoints bigint,
  incidentId bit,
  forwardTo tinyint,
  accessLevel blob,
  amount double,
  paymentMethod mediumint,
  accountType geometry,
  role int,
  id double,
  childId varchar,
  channelId binary,
  insuranceId timestamp,
  age bigint,
  contactName bigint
);

CREATE TABLE fact_organization (
  id serial primary key,
  ipAddress int,
  name smallint,
  checkOutTime boolean,
  score boolean,
  description bigint,
  customField2 mediumint,
  latitude datetime,
  displayOrder bigint,
  layerId serial,
  manufacturerId serial,
  fingerprint datetime,
  category time,
  id smallint,
  analyticsId real,
  enrollmentDate boolean,
  thumbnail boolean,
  entryPoint smallint,
  isLocked set
);

CREATE TABLE customer_status (
  id serial primary key,
  emergencyContact point,
  lastLoginAt geometry,
  incidentId boolean,
  isVerified timestamp,
  dataSource geometry,
  instructorId boolean,
  id blob,
  costCenter bigint,
  deactivatedAt smallint,
  downloadCount varchar,
  amount real,
  email mediumint,
  modifiedAt datetime,
  dashboardId tinyint,
  merchantId date,
  loadTime date,
  industryType smallint,
  contentType bit,
  indexKey tinyint,
  gender float,
  orderStatus double,
  latitude real,
  type real,
  earnedPoints datetime,
  handlerId time,
  name blob
);

CREATE TABLE customer (
  id serial primary key,
  addressLine2 binary,
  cancelReason smallint,
  dailyLimit time,
  earnedPoints double,
  flagged set,
  contactName serial,
  checkOutTime int,
  displayName datetime,
  timezone timestamp,
  analyticsId set,
  dialCode boolean,
  title int,
  sessionId double,
  loadTime enum,
  facilityId datetime,
  dealerId double,
  dependentId text,
  depositAmount tinyint,
  group text,
  ipAddress real,
  longitude serial,
  gender float,
  forwardTo int,
  comment int,
  metaKeywords varchar,
  configId mediumint
);

CREATE TABLE dim_record_seg (
  id serial primary key,
  macAddress point,
  errorMessage timestamp,
  labelText time,
  audioUrl mediumint,
  completionRate bigint,
  departmentCode int,
  isLocked geometry,
  loadTime bigint,
  street int,
  ipAddress set,
  bankAccount float,
  fileName time,
  shippingAddress double
);

CREATE TABLE priv_account (
  id serial primary key,
  friendId boolean,
  gateId float,
  customerGroup real,
  grade float,
  metaTitle boolean,
  referralCode mediumint,
  password mediumint,
  homePhone real,
  isVerified decimal,
  algorithm decimal,
  contentType tinyint,
  avatar time,
  enabledAt text,
  clientId geometry,
  updatedAt set,
  ipAddress float,
  houseNumber varchar,
  authToken decimal,
  favoriteCount point,
  memberCount boolean,
  addressLine1 time,
  mapId float,
  browserType mediumint,
  maritalStatus int,
  creditLimit bit,
  likeCount real,
  isDraft geometry,
  attemptCount time,
  cancelReason enum,
  accountStatus tinyint,
  sku point
);

CREATE TABLE user (
  id serial primary key,
  avatar real,
  endDate text,
  loginAttempts mediumint,
  entryPoint int,
  displayName bit,
  instanceId smallint,
  distributorId mediumint,
  industryType date,
  homePhone decimal,
  managerId text,
  chargeId mediumint,
  companyName smallint,
  bankAccount datetime,
  id mediumint,
  appVersion time,
  description tinyint,
  amount blob,
  fromDate time,
  latitude binary
);

CREATE TABLE dstcompany (
  id serial primary key,
  isRequired serial,
  emergencyContact date,
  exchangeRate real,
  isEnabled bit,
  referralCode timestamp,
  campaignId enum,
  facilityId enum,
  extractId bigint,
  earnedPoints geometry,
  certificateId smallint,
  grade smallint,
  friendId set,
  maxLimit binary,
  bookingDate double
);

CREATE TABLE order (
  id serial primary key,
  audioUrl decimal,
  createdAt smallint,
  isArchived mediumint,
  amount double,
  dailyLimit tinyint,
  formatType decimal,
  licenseKey bigint,
  deviceId date,
  businessType timestamp,
  dependentId int,
  defaultLang geometry,
  status enum,
  instanceId date,
  comment text,
  customField2 time,
  addressLine1 text,
  deviceType enum,
  lastName text,
  menuId time,
  gameId tinyint
);

CREATE TABLE company (
  id serial primary key,
  token boolean,
  defaultValue point,
  listingId varchar
);

CREATE TABLE company (
  id serial primary key,
  deviceType text,
  maxValue decimal,
  entryPoint real,
  globalId timestamp,
  departmentCode real,
  metadata serial
);

CREATE TABLE company (
  id serial primary key,
  url boolean,
  isBillable tinyint,
  firstName binary,
  incidentId serial,
  avatar time,
  employeeCode mediumint,
  discount varchar,
  industryType timestamp,
  checkInTime double,
  paymentMethod point,
  shippingAddress decimal,
  departmentCode text,
  creditScore bigint,
  updatedAt tinyint,
  group mediumint,
  moduleId real,
  facilityId blob,
  apiKey int,
  fileType bigint,
  lastSeenAt mediumint
);

CREATE TABLE dim_organization_out (
  id serial primary key,
  claimId bigint,
  addressLine2 bigint,
  bankAccount point,
  mapId varchar,
  itemCount date,
  alertType timestamp,
  createdAt mediumint,
  blogId datetime,
  entryPoint date,
  url varchar,
  incidentId binary,
  chargeId mediumint,
  algorithm boolean,
  editedAt enum,
  coordinateY enum,
  fileName serial,
  isAdmin mediumint,
  gameId mediumint,
  industryType bit,
  bannerImage binary,
  endPoint float,
  backupEmail datetime,
  isVerified smallint,
  moveId int,
  dataSource time,
  isSystem blob,
  role serial
);

CREATE TABLE fact_product_seg (
  id serial primary key,
  category point,
  distributorId double,
  businessType text,
  height datetime,
  contactName smallint,
  deviceType mediumint,
  macAddress real,
  priority point,
  displayName datetime,
  education decimal,
  enrollmentDate bigint,
  articleId smallint,
  exportId boolean,
  updatedAt date,
  creditLimit point,
  cardNumber int,
  email timestamp,
  importId set,
  geoLocation datetime,
  joinDate datetime,
  comment binary,
  currency point,
  hashKey set
);

CREATE TABLE src_transaction_new (
  id serial primary key,
  insuranceId blob,
  cartId point,
  loginAttempts bit,
  isDefault blob,
  authMethod double,
  defaultLang enum,
  lastName enum,
  depositAmount serial,
  creditLimit real,
  deletedAt smallint,
  dueDateAt boolean,
  agentId smallint,
  phone bigint,
  facilityId tinyint,
  validUntil geometry,
  moveId text,
  nickname enum,
  street varchar
);

CREATE TABLE company_div (
  id serial primary key,
  role decimal,
  isDeleted geometry,
  nickname point,
  size mediumint,
  childId bit,
  dateFormat float,
  sessionId mediumint,
  category point,
  dailyLimit datetime,
  globalId serial,
  isHidden geometry,
  billingFrequency mediumint,
  validUntil smallint,
  discount tinyint,
  forwardTo date,
  orderStatus point,
  username datetime,
  age varchar,
  eventDate bit,
  bannerImage set,
  comment timestamp,
  businessType smallint,
  fromDate smallint,
  machineId int,
  ipAddress enum,
  alertType tinyint
);

CREATE TABLE rel_account_notifications (
  id serial primary key,
  hashKey bit,
  email date,
  address text,
  age boolean,
  latitude text,
  isFeatured enum,
  zipCode enum,
  displayName enum,
  merchantId varchar,
  country int,
  city bigint,
  analyticsId point,
  faxNumber boolean,
  expiryMonth geometry,
  createdAt int,
  phone decimal,
  orderId smallint,
  displayOrder date,
  timezone smallint,
  minValue real,
  birthDate enum,
  customerGroup time
);

CREATE TABLE reforganization (
  id serial primary key,
  companyLogo mediumint,
  signature smallint,
  managerId time,
  cvv date,
  groupName double,
  lastName boolean,
  endDate mediumint,
  entryPoint time,
  editedAt timestamp,
  id real,
  emailStatus time,
  departmentCode smallint,
  avatar binary,
  clientId int,
  deviceType bit,
  meterNumber date,
  apiKey bigint,
  country mediumint,
  addressLine2 boolean,
  timezone point,
  moveId blob,
  instructorId float,
  authorId time,
  errorCode enum,
  city double,
  keyId tinyint,
  entityId date
);

CREATE TABLE user (
  id serial primary key,
  buildNumber text,
  age binary,
  deviceId varchar,
  category datetime,
  completedAt bigint,
  maritalStatus enum
);

CREATE TABLE transaction_legacy (
  id serial primary key,
  completedAt mediumint,
  actionType bit,
  keyId bit
);

CREATE TABLE account_legacy (
  id serial primary key,
  displayName tinyint,
  size smallint,
  role double,
  clockIn int,
  companyLogo enum,
  productCode date,
  updatedAt boolean,
  metadata bit,
  expiryYear enum,
  incidentId date,
  machineId enum,
  linkId real,
  contactName text,
  status text,
  endPoint smallint,
  houseNumber tinyint,
  category tinyint,
  paymentMethod serial,
  instructorId timestamp,
  group time,
  email enum
);

CREATE TABLE aggorder (
  id serial primary key,
  departmentCode float,
  clockOut text,
  fontFamily decimal,
  backupEmail enum,
  managerId tinyint,
  costCenter smallint,
  buildNumber datetime,
  loginAttempts real,
  bookingDate mediumint,
  hashKey int,
  moveId float,
  cacheKey double,
  orderId real,
  latitude varchar,
  batchId varchar,
  companyId time,
  education date,
  albumId datetime,
  authMethod point,
  isDeleted real,
  iconPath blob,
  companyName date,
  guestId float,
  dashboardId text,
  depositAmount geometry,
  configId binary
);

