CREATE TABLE ext_record (
  id serial primary key,
  fontSize bigint,
  firmwareVersion bit,
  levelId bit,
  phone bit,
  bluetoothId int,
  feedId varchar,
  driverLicense set,
  clientId decimal,
  birthDate bigint,
  integrationId point,
  value bit,
  deviceType text,
  forwardTo binary,
  apiKey time,
  accountType int,
  updatedAt datetime,
  dealerId float,
  cvv boolean,
  maskType double,
  maritalStatus int,
  fromDate binary,
  isVerified binary,
  coordinateY set,
  comment boolean,
  alertType bigint,
  uuid mediumint,
  customerId tinyint
);

CREATE TABLE customer (
  id serial primary key,
  customerId bigint,
  floorNumber date,
  billingCycle bit,
  folderPath int,
  cityName mediumint
);

CREATE TABLE core_payment (
  id serial primary key,
  faxNumber tinyint,
  category varchar,
  checkOutTime text,
  coordinateY float,
  linkId double,
  facilityId varchar
);

CREATE TABLE vw_record_meta_v2 (
  id serial primary key,
  customField1 tinyint,
  lastName date,
  creditScore int,
  enrollmentDate serial,
  billingCycle int
);

CREATE TABLE sysaudit (
  id serial primary key,
  age timestamp,
  latitude point,
  updatedAt bit,
  endDate time,
  facilityId decimal,
  password time,
  defaultValue datetime,
  mimeType mediumint,
  documentId time
);

CREATE TABLE customer (
  id serial primary key,
  levelId int,
  friendId blob,
  education set,
  errorMessage datetime,
  contractId smallint,
  fileName timestamp,
  entryPoint bigint,
  clockOut point,
  bluetoothId int,
  meterNumber bit,
  alertType real,
  authToken real,
  city serial,
  actionType boolean,
  keywords mediumint,
  guestId smallint,
  downloadCount smallint,
  geoLocation serial,
  metadata boolean,
  metaKeywords binary,
  isHidden bigint,
  localeId geometry,
  group enum,
  version decimal,
  ipAddress timestamp,
  name real,
  bannerImage time,
  businessType point,
  rating text
);

CREATE TABLE config (
  id serial primary key,
  menuId set,
  emailStatus boolean,
  phone tinyint,
  score smallint,
  billingFrequency serial,
  accessLevel decimal,
  weight tinyint,
  state enum,
  audioUrl double,
  creditLimit enum,
  unit bit,
  clientId boolean,
  maxValue float
);

CREATE TABLE account (
  id serial primary key,
  maxLimit varchar,
  isFeatured float,
  password bigint,
  awardDate int,
  hashKey decimal,
  balance double,
  brandId binary,
  isVerified date,
  isActive double,
  editedAt varchar,
  quantity double,
  feedId set,
  attemptCount real,
  analyticsId binary,
  foregroundColor text,
  avatar bit,
  sku timestamp,
  phone set,
  isDeleted real,
  orderStatus smallint
);

CREATE TABLE olk_account_data (
  id serial primary key,
  password real,
  campaignId date,
  localeId enum,
  orderStatus enum,
  importId datetime,
  customField1 smallint,
  email binary,
  countryCode enum,
  category date,
  gameId datetime,
  deliveryDate tinyint,
  metadata float,
  title time,
  minValue time,
  avatar varchar,
  companyName float,
  entryPoint real,
  gender set,
  isHidden float,
  albumId binary,
  deletedAt decimal,
  configId double,
  clockIn tinyint,
  messageId enum,
  languageCode geometry,
  employeeCode varchar,
  creditCard timestamp,
  distributorId bigint,
  zipCode double,
  copyRight mediumint
);

CREATE TABLE recordlegacy (
  id serial primary key,
  accountType decimal,
  uuid timestamp,
  email time,
  state set
);

CREATE TABLE logcompany2025 (
  id serial primary key,
  iconPath float,
  isRequired datetime,
  invoiceId decimal,
  loginCount bit,
  size varchar,
  comment timestamp,
  customerGroup real,
  updatedAt real,
  contactPhone text,
  tags enum,
  contactName binary,
  logLevel text,
  fileHash serial,
  isVerified int,
  modifiedAt point,
  ipAddress blob,
  domainName boolean
);

CREATE TABLE order_data (
  id serial primary key,
  accessLevel binary,
  rating timestamp,
  errorCode time,
  documentId set,
  endPoint time,
  billingCycle point,
  defaultValue point,
  alertType bigint,
  completedAt binary,
  mainImage serial,
  expiryYear decimal,
  isAdmin datetime,
  discount serial,
  analyticsId point,
  sessionId point,
  browserType tinyint,
  firstName set,
  geoLocation blob,
  employmentDate point,
  monthlyRate point,
  createdAt timestamp,
  clockIn date,
  password bit,
  creditLimit datetime
);

CREATE TABLE record (
  id serial primary key,
  levelId double,
  homePhone enum,
  gateId tinyint,
  moveId mediumint,
  cloudId time,
  isVerified smallint
);

CREATE TABLE audit_seg (
  id serial primary key,
  appVersion datetime,
  hashKey serial,
  companyName tinyint,
  uuid geometry,
  rating datetime,
  campaignId geometry,
  articleId real,
  maxValue datetime,
  guestId mediumint,
  feedbackId point,
  title text,
  employeeCode binary,
  integrationId time,
  role float,
  localeId float,
  status decimal,
  couponCode bit,
  department float,
  accessLevel timestamp,
  defaultValue set,
  paymentMethod double,
  createdAt smallint,
  contentType blob,
  messageId decimal,
  importId enum,
  fileSize timestamp,
  education real
);

CREATE TABLE olkinventorylegacy (
  id serial primary key,
  firmwareVersion blob,
  attemptCount mediumint,
  updatedAt serial
);

CREATE TABLE src_transaction_2024 (
  id serial primary key,
  addressLine1 set,
  merchantId text,
  mainImage set,
  cancelReason blob,
  instructorId tinyint,
  education time,
  maskType decimal,
  orderStatus smallint,
  startDate smallint,
  algorithm bit,
  domainName double,
  signature time,
  companyName datetime,
  locationId blob,
  description blob,
  deletedAt double,
  enrollmentDate text,
  expiryYear blob,
  exchangeRate datetime,
  contractId int,
  isAdmin serial,
  role real,
  machineId varchar,
  customerGroup blob
);

CREATE TABLE stg_company_notifications (
  id serial primary key,
  fileName bit,
  isLocked mediumint,
  clientId real,
  frameRate geometry,
  billingFrequency geometry,
  size mediumint,
  employeeId smallint,
  phone tinyint,
  title date,
  displayName int,
  cancelReason float,
  creditScore set,
  certificateId int,
  avatar bit,
  guestId serial,
  instanceId timestamp,
  instructorId bigint,
  machineId varchar,
  isRequired mediumint,
  deviceType blob,
  ipAddress enum,
  authMethod datetime,
  code decimal,
  cvv double,
  postalCode tinyint,
  inactiveAt float,
  itemCount serial,
  hashKey datetime,
  tags decimal
);

CREATE TABLE transaction (
  id serial primary key,
  name set,
  referralCode double,
  contactEmail varchar,
  email enum,
  createdAt time,
  filterType tinyint,
  gameId time,
  dealerId float,
  audioUrl date,
  coordinateY point,
  moduleId time,
  insertedAt smallint,
  role datetime,
  latitude date,
  middleName smallint,
  feedId enum,
  size geometry,
  orderId bigint,
  deliveryDate varchar,
  group varchar,
  managerId mediumint,
  actionType varchar
);

CREATE TABLE record_hist (
  id serial primary key,
  deletedAt blob,
  gameId geometry,
  addressLine1 time,
  machineId time,
  department float,
  maritalStatus boolean,
  homePhone date,
  cityName double,
  authMethod datetime,
  fileName time,
  birthDate geometry,
  listId real,
  audioUrl datetime,
  headerImage real
);

CREATE TABLE ref_record (
  id serial primary key,
  name blob,
  cvv time,
  creditLimit datetime,
  hiddenAt text,
  maritalStatus real,
  isBillable int,
  group text,
  joinDate text
);

CREATE TABLE tmp_record (
  id serial primary key,
  title decimal,
  name bit,
  dashboardId blob,
  sessionId blob,
  deactivatedAt bigint,
  birthDate time
);

CREATE TABLE payment (
  id serial primary key,
  countryCode serial,
  employeeId real,
  category blob
);

CREATE TABLE user_archive (
  id serial primary key,
  companyId set,
  orderStatus geometry,
  uuid blob,
  rating int
);

CREATE TABLE logrecordtype (
  id serial primary key,
  likeCount decimal,
  fileHash real,
  machineId point,
  latitude decimal,
  backupEmail decimal
);

CREATE TABLE sys_transaction_2024 (
  id serial primary key,
  incidentId varchar,
  status tinyint,
  currency time,
  emergencyContact double,
  budgetCode smallint,
  id geometry,
  birthDate mediumint,
  weight decimal,
  metaTitle tinyint,
  coverImage int,
  completedAt point,
  hashKey bit,
  maxValue geometry,
  merchantId varchar,
  duration blob,
  expiryDate text,
  customerGroup timestamp,
  version blob,
  managerId varchar,
  contentType boolean,
  password geometry,
  lastLoginAt date,
  minValue enum,
  groupName boolean,
  listId blob,
  friendId time,
  category binary,
  referralCode datetime
);

CREATE TABLE stgauditextralegacy (
  id serial primary key,
  claimId bigint,
  mimeType geometry,
  attachmentUrl datetime,
  coordinateY text,
  size varchar,
  chatId smallint,
  cacheKey text,
  lastName decimal,
  expiryDate decimal,
  cartId tinyint,
  username decimal,
  deviceToken point,
  unit mediumint,
  flagged serial,
  batchId decimal,
  coordinateX datetime,
  deviceId binary,
  displayOrder enum,
  referralCode bigint,
  marketId tinyint,
  cloudId text,
  gender boolean,
  updatedAt decimal,
  mainImage bigint,
  entryPoint serial,
  taxRate blob
);

CREATE TABLE refrecord (
  id serial primary key,
  driverLicense enum,
  keywords timestamp,
  avatar geometry,
  companyId boolean,
  country set,
  campaignId varchar,
  education int,
  endDate tinyint,
  bluetoothId text,
  gender bit,
  mapId binary,
  contractId int,
  courseId datetime,
  comment geometry,
  frameRate tinyint,
  version decimal,
  currency datetime,
  colorCode int,
  enabledAt smallint,
  copyRight binary,
  bookingDate double,
  audioUrl varchar,
  isRequired text,
  isVerified bigint,
  orderStatus serial,
  deliveryDate mediumint,
  street smallint,
  type point
);

CREATE TABLE user (
  id serial primary key,
  isBillable enum,
  companyName decimal,
  indexKey tinyint,
  phone set,
  cancelReason timestamp,
  gateId enum
);

CREATE TABLE productlog (
  id serial primary key,
  emailStatus int,
  password decimal,
  configId datetime,
  homePhone set,
  countryCode float,
  copyRight geometry,
  labelText date,
  maskType varchar,
  budgetCode bigint,
  gender geometry,
  albumId time,
  exchangeRate binary,
  zipCode serial,
  createdAt timestamp,
  contactName timestamp,
  defaultLang boolean,
  fileHash blob,
  deletedAt text,
  state int,
  appVersion time,
  currencyCode date
);

CREATE TABLE src_product (
  id serial primary key,
  isHidden decimal,
  completedAt varchar,
  marketId tinyint,
  isLocked mediumint,
  facilityId tinyint,
  email date,
  merchantId double,
  memberCount set,
  phone datetime,
  clientId double,
  expiryYear set,
  deliveryDate point,
  fontFamily bigint,
  inactiveAt blob,
  isAdmin geometry,
  enrollmentDate binary,
  maxLimit serial,
  copyRight binary,
  currency point,
  groupName binary,
  postalCode smallint,
  avatar text,
  mimeType timestamp,
  title real,
  macAddress enum,
  gender text,
  metaTitle int,
  domainName varchar
);

CREATE TABLE customer (
  id serial primary key,
  clientId time,
  analyticsId geometry,
  email blob,
  marketId tinyint,
  businessType int,
  updatedAt geometry,
  billingFrequency bigint,
  mobileNumber boolean,
  discountCode decimal,
  unit boolean,
  shippingAddress decimal,
  height float,
  maritalStatus enum,
  signature set,
  referralCode real,
  lastLoginAt serial,
  minValue timestamp,
  duration text,
  instructorId timestamp,
  domainName varchar,
  currencyCode bigint,
  version decimal,
  itemCount varchar,
  title set,
  audioUrl set,
  feedId date,
  priority double
);

CREATE TABLE config (
  id serial primary key,
  username binary,
  dataSource date,
  loginAttempts boolean,
  employeeId mediumint,
  abandonedCartId boolean,
  taxRate datetime,
  minValue varchar,
  bankAccount blob,
  articleId smallint,
  agentId decimal,
  listId set,
  favoriteCount smallint,
  firstName binary,
  facilityId time,
  metaKeywords bit,
  locationId real,
  departmentCode time
);

CREATE TABLE ref_transaction (
  id serial primary key,
  accountStatus geometry,
  addressLine1 text,
  displayName decimal,
  completedAt enum,
  locationId varchar,
  hostName double,
  fileHash varchar
);

CREATE TABLE tmp_customer (
  id serial primary key,
  claimId binary,
  monthlyRate date,
  maxLimit time,
  copyRight geometry,
  birthDate point,
  state timestamp,
  age datetime,
  latitude set,
  machineId datetime,
  hiddenAt datetime,
  homePhone bigint,
  foregroundColor varchar,
  moduleId mediumint,
  entityId varchar,
  expiryYear decimal,
  mimeType varchar,
  comment set,
  maxValue decimal,
  metadata varchar,
  balance set,
  blogId set,
  billingCycle mediumint,
  size decimal,
  feedbackId bit
);

CREATE TABLE transaction_extra (
  id serial primary key,
  employmentDate bigint,
  maritalStatus enum,
  creditLimit bit,
  bluetoothId bit,
  orderId datetime,
  audioUrl double,
  hiddenAt decimal,
  apiVersion blob,
  guestId enum,
  loadTime int
);

CREATE TABLE account (
  id serial primary key,
  authMethod double,
  addressLine1 decimal,
  dealerId float,
  industryType real,
  orderId point,
  creditLimit point,
  deactivatedAt geometry,
  fileHash datetime
);

CREATE TABLE privuser (
  id serial primary key,
  backupEmail timestamp,
  birthDate enum,
  friendId decimal,
  bookingDate int,
  firmwareVersion serial,
  buildNumber datetime,
  browserType blob,
  minValue date,
  likeCount time,
  deliveryDate enum,
  followCount bigint,
  joinDate real,
  labelText bigint,
  currency serial,
  colorCode point,
  address binary,
  faxNumber tinyint,
  country smallint,
  ipAddress int,
  category point,
  accountType timestamp,
  metaKeywords double,
  totalAmount date,
  moduleId enum,
  favoriteCount serial,
  creditScore timestamp,
  localeId decimal,
  countryCode serial,
  metadata boolean
);

CREATE TABLE dst_inventory (
  id serial primary key,
  agentId bit,
  enabledAt smallint,
  password real,
  dealerId enum,
  completedAt smallint,
  title time,
  validUntil float,
  latitude text,
  isVerified point,
  courseId binary,
  buildNumber binary,
  grade mediumint,
  description text,
  guestId varchar,
  exportId real,
  claimId datetime,
  manufacturerId enum,
  category bigint,
  awardDate float,
  contentType smallint,
  fingerprint decimal
);

CREATE TABLE record_status (
  id serial primary key,
  blogId timestamp,
  dialCode int,
  creditCard bigint,
  cancelReason mediumint,
  street float,
  isHidden smallint,
  monthlyRate boolean,
  channelId tinyint,
  maxValue datetime,
  currency decimal,
  attemptCount time,
  amount set
);

CREATE TABLE dim_payment (
  id serial primary key,
  layerId point,
  chargeId decimal,
  maxLimit mediumint,
  balance varchar,
  cityName time,
  houseNumber decimal,
  department blob,
  endPoint blob,
  size timestamp,
  status text,
  maskType double,
  groupName float,
  employmentDate geometry,
  customerId time,
  education set,
  instanceId smallint,
  configId set,
  bankAccount bigint,
  browserType enum,
  maritalStatus decimal,
  title tinyint,
  orderId set,
  isArchived mediumint,
  phone point,
  hiddenAt time
);

CREATE TABLE pub_organization (
  id serial primary key,
  enabledAt float,
  updatedAt geometry,
  domainName boolean,
  hostName timestamp,
  customField2 bigint,
  favoriteCount varchar,
  fileType double,
  middleName binary,
  phone binary,
  hourlyRate boolean,
  clockIn datetime,
  thumbnail enum,
  deliveryDate decimal,
  meterNumber datetime,
  deletedAt blob,
  longitude varchar,
  lastName timestamp,
  actionType boolean,
  brandId smallint,
  isFeatured double,
  dealerId decimal,
  coverImage set,
  bluetoothId varchar,
  metaDescription mediumint,
  mobileNumber double,
  discount float
);

CREATE TABLE dim_account (
  id serial primary key,
  fingerprint timestamp,
  height boolean,
  apiKey decimal,
  marketId varchar,
  coverImage float,
  username mediumint,
  abandonedCartId time,
  balance text
);

CREATE TABLE audit_new (
  id serial primary key,
  quantity datetime,
  grade enum,
  colorCode time,
  deliveryDate bit,
  isLocked decimal,
  content double,
  machineId smallint,
  accountNumber bit,
  keywords real,
  marketId geometry,
  creditCard geometry,
  fileSize date,
  chatId blob,
  certificateId serial,
  childId boolean
);

CREATE TABLE sys_record_rel (
  id serial primary key,
  title smallint,
  dataSource real,
  abandonedCartId int,
  phone bit,
  loginAttempts mediumint,
  clientId blob,
  budgetCode varchar,
  middleName double,
  costCenter geometry,
  id float,
  creditLimit date,
  iconPath smallint,
  billingFrequency blob,
  businessType timestamp,
  age set
);

CREATE TABLE log_transaction_out (
  id serial primary key,
  coverImage double,
  email float,
  customerId binary,
  cartId date,
  coordinateY text,
  downloadCount text,
  couponCode double,
  cardNumber text,
  defaultLang serial,
  extractId set,
  category date,
  checkInTime point,
  appVersion tinyint,
  type decimal,
  memberCount smallint,
  isDraft date,
  avatar enum,
  phone date,
  connectionString set,
  companyName text
);

CREATE TABLE order (
  id serial primary key,
  campaignId blob,
  maritalStatus timestamp,
  cardNumber bit,
  token point,
  validUntil serial,
  expiryDate boolean,
  domainName datetime,
  bankAccount real,
  articleId tinyint,
  contactPhone serial,
  isAdmin mediumint,
  favoriteCount bigint,
  friendId point
);

CREATE TABLE ver_config_temp (
  id serial primary key,
  city real,
  metadata tinyint,
  fileHash decimal,
  address binary,
  score set,
  menuId bit,
  foregroundColor time,
  maxLimit bit,
  dialCode serial,
  country smallint,
  endPoint real,
  errorMessage mediumint,
  adminNotes geometry,
  appVersion blob,
  ipAddress int,
  clockOut int,
  isDeleted smallint,
  algorithm int,
  isLocked tinyint,
  importId blob,
  domainName float,
  bankAccount text,
  errorCode timestamp,
  formatType varchar,
  itemCount boolean,
  group tinyint,
  loginAttempts decimal,
  hourlyRate date,
  status binary,
  displayOrder double
);

CREATE TABLE account (
  id serial primary key,
  sku varchar,
  maritalStatus enum,
  isVerified point,
  insuranceId tinyint,
  jobTitle bigint,
  houseNumber int,
  billingCycle decimal,
  flagged mediumint,
  timezone int,
  status geometry,
  middleName text,
  comment tinyint,
  quantity text,
  configId real,
  deactivatedAt geometry,
  currencyCode tinyint,
  displayOrder time,
  rating geometry,
  maxLimit bit,
  fileType timestamp,
  category float,
  isFeatured real,
  metaDescription enum,
  role set,
  grade datetime,
  eventDate timestamp,
  updatedAt binary,
  isDraft datetime,
  employeeId real,
  education int,
  brandId enum
);

CREATE TABLE ver_account (
  id serial primary key,
  entityId real,
  accountNumber timestamp,
  expiryMonth point,
  createdAt varchar,
  defaultValue binary,
  expiryYear time,
  status bigint,
  insuranceId real,
  fileSize set,
  maskType double,
  marketId bigint,
  comment smallint,
  postalCode datetime,
  headerImage smallint,
  currency geometry,
  clockIn tinyint,
  mimeType boolean,
  metaKeywords serial,
  role timestamp,
  cvv smallint,
  bookingDate serial,
  loginCount binary,
  floorNumber point,
  incidentId decimal
);

CREATE TABLE fact_account (
  id serial primary key,
  email time,
  loadTime boolean,
  referralCode timestamp,
  logLevel point,
  comment boolean,
  salary double,
  size geometry,
  endDate varchar,
  importId double,
  code decimal,
  enrollmentDate double,
  checkInTime tinyint,
  budgetCode set,
  headerImage real,
  colorCode geometry,
  albumId tinyint,
  batchId int,
  defaultLang text,
  accessLevel bigint,
  contactPhone geometry,
  orderId float
);

