CREATE TABLE vwuser (
  id serial primary key,
  accountType text,
  totalAmount point,
  hourlyRate datetime,
  costCenter geometry,
  batchId binary,
  currency text,
  paymentMethod smallint,
  companyName time,
  bankAccount mediumint,
  depositAmount tinyint
);

CREATE TABLE olk_payment (
  id serial primary key,
  billingCycle float,
  awardDate serial,
  contractId point,
  loadTime real,
  defaultLang geometry,
  phone enum,
  isEnabled time,
  audioUrl tinyint,
  city geometry,
  startDate time,
  id binary,
  updatedAt blob,
  category float,
  currencyCode double,
  errorMessage float,
  customField2 date,
  accessLevel enum,
  modifiedAt double,
  downloadCount int,
  instructorId bit,
  dailyLimit smallint,
  isPublic smallint
);

CREATE TABLE product (
  id serial primary key,
  createdAt mediumint,
  distributorId serial
);

CREATE TABLE vwinventory (
  id serial primary key,
  mainImage set,
  layerId int,
  ipAddress bit,
  lockoutEnd datetime,
  machineId binary,
  postalCode serial,
  documentId decimal,
  street varchar,
  enrollmentDate double
);

CREATE TABLE payment (
  id serial primary key,
  fontFamily tinyint,
  attemptCount varchar,
  levelId set,
  instanceId enum,
  gateId smallint,
  claimId serial,
  productCode tinyint,
  hashKey serial,
  managerId text,
  countryCode text,
  cancelReason blob,
  clockOut serial,
  departmentCode text,
  integrationId blob,
  flagged tinyint,
  salary bigint,
  industryType double,
  copyRight set,
  importId real,
  billingFrequency boolean,
  comment real,
  createdAt boolean,
  fontSize blob,
  handlerId bit,
  couponCode varchar,
  weight timestamp,
  shippingAddress serial,
  abandonedCartId enum,
  lastLoginAt binary,
  state double
);

CREATE TABLE src_audit (
  id serial primary key,
  discount timestamp,
  keywords mediumint,
  accountNumber smallint,
  orderId decimal,
  authToken timestamp,
  fileName set,
  algorithm binary,
  contactName real,
  creditCard text,
  employmentDate decimal,
  tags blob,
  hashKey bit,
  taxRate binary,
  authorId decimal
);

CREATE TABLE user_v2 (
  id serial primary key,
  tags geometry,
  uuid binary,
  monthlyRate decimal,
  loginAttempts datetime,
  id blob,
  customField2 binary,
  mapId geometry,
  value boolean,
  avatar real,
  accessLevel set,
  discount serial,
  category tinyint,
  accountNumber text,
  addressLine1 decimal,
  countryCode text,
  amount time,
  isPublic point,
  department float,
  minLimit datetime,
  emergencyContact point,
  grade decimal,
  displayName point,
  friendId decimal,
  isArchived set
);

CREATE TABLE core_customer (
  id serial primary key,
  grade point,
  fileType int,
  token tinyint,
  hostName boolean,
  unit mediumint,
  endDate point,
  moveId serial,
  fromDate double,
  authMethod date,
  domainName bit,
  flagged int,
  homePhone varchar,
  customerGroup tinyint,
  costCenter datetime,
  age float,
  birthDate decimal,
  password bigint,
  albumId blob,
  loginCount point,
  appVersion blob,
  billingFrequency mediumint,
  filterType enum,
  invoiceId float,
  currencyCode binary,
  articleId tinyint,
  metadata boolean
);

CREATE TABLE sys_payment (
  id serial primary key,
  accessLevel tinyint,
  description double,
  cancelReason time,
  documentId point,
  nickname date,
  firmwareVersion bigint,
  content text,
  enabledAt datetime,
  driverLicense timestamp
);

CREATE TABLE tmpaccounttypenew (
  id serial primary key,
  creditScore smallint,
  customField1 mediumint,
  contactEmail bit,
  keyId tinyint,
  campaignId date,
  flagged text,
  isLocked double,
  managerId binary,
  isAdmin smallint,
  token serial,
  thumbnail timestamp,
  longitude timestamp,
  instructorId float,
  chatId mediumint,
  insuranceId bit,
  marketId datetime,
  albumId decimal,
  iconPath set,
  moveId int,
  deviceId int,
  guestId decimal,
  claimId tinyint,
  dimension set,
  itemCount tinyint,
  sku enum,
  buildNumber tinyint
);

CREATE TABLE fact_record_archive (
  id serial primary key,
  hourlyRate smallint,
  city geometry,
  email boolean,
  contactPhone float,
  faxNumber geometry,
  managerId blob
);

CREATE TABLE ext_config_rel (
  id serial primary key,
  creditLimit geometry,
  geoLocation time,
  nickname text,
  avatar datetime,
  longitude enum,
  entryPoint set,
  comment time,
  insuranceId smallint,
  customField2 decimal,
  deviceId geometry,
  completionRate bit,
  token tinyint,
  cancelReason time,
  deviceType point,
  activeDevices double,
  languageCode enum,
  apiVersion bit,
  status date,
  driverLicense set,
  accountType datetime,
  handlerId datetime,
  balance binary,
  keyId serial,
  dueDateAt real,
  homePhone enum,
  addressLine1 point,
  folderPath serial
);

CREATE TABLE app_config_notifications (
  id serial primary key,
  brandId varchar,
  activeDevices timestamp,
  listId point,
  homePhone float,
  endDate text,
  balance timestamp,
  size bigint,
  accountType mediumint,
  comment point,
  phone set,
  exportId varchar,
  isActive point,
  isBillable boolean,
  isAdmin blob,
  inactiveAt tinyint,
  cityName real,
  priority real,
  endPoint date,
  createdAt serial,
  emailStatus point,
  metaDescription tinyint,
  role serial,
  contractId mediumint,
  lastLoginAt boolean,
  accountNumber bit,
  incidentId smallint,
  type smallint,
  isRequired blob,
  geoLocation binary,
  fingerprint int
);

CREATE TABLE tmp_payment (
  id serial primary key,
  totalAmount int,
  abandonedCartId mediumint,
  cityName point,
  browserType int,
  activeDevices smallint,
  token point,
  channelId boolean,
  enrollmentDate serial,
  lastLoginAt bigint,
  cartId smallint,
  countryCode real,
  creditCard double,
  guestId decimal,
  validUntil real,
  uuid binary,
  password smallint,
  billingFrequency geometry,
  url bigint,
  tags text,
  couponCode text,
  machineId geometry,
  isEnabled bigint,
  endPoint point,
  email timestamp,
  isActive mediumint
);

CREATE TABLE facttransaction2024 (
  id serial primary key,
  batchId time,
  managerId enum,
  expiryYear boolean,
  isBillable int,
  status datetime,
  contactPhone blob,
  lastName date,
  maxLimit bit,
  insuranceId point,
  coverImage varchar
);

CREATE TABLE vw_record (
  id serial primary key,
  agentId boolean,
  maskType set,
  salary datetime,
  contractId smallint,
  flagged bit,
  defaultValue bit,
  mainImage float
);

CREATE TABLE productv2 (
  id serial primary key,
  billingFrequency binary,
  checkOutTime bigint,
  batchId float,
  gameId text,
  menuId smallint,
  joinDate float,
  emergencyContact double,
  isDeleted date,
  manufacturerId int,
  companyId boolean,
  description blob,
  cancelReason double,
  comment tinyint,
  deletedAt mediumint,
  size time,
  accountType boolean,
  dimension enum,
  title point,
  createdAt geometry,
  clientId mediumint,
  monthlyRate int,
  marketId mediumint,
  contentType blob,
  avatar decimal
);

CREATE TABLE tmp_order_notifications_2024 (
  id serial primary key,
  chargeId enum,
  lastSeenAt point,
  handlerId real,
  accessLevel mediumint,
  cancelReason boolean
);

CREATE TABLE transaction (
  id serial primary key,
  weight varchar,
  languageCode tinyint,
  phone real,
  isRequired binary,
  gender geometry,
  houseNumber serial,
  fileHash float,
  maritalStatus boolean,
  checkInTime boolean,
  unit geometry,
  tags varchar,
  authToken date,
  bluetoothId time,
  couponCode mediumint,
  startDate enum,
  hiddenAt date,
  firstName point,
  completedAt float,
  discount set,
  endDate text,
  listId time,
  copyRight geometry,
  flagged time,
  lastName geometry,
  linkId timestamp,
  username varchar
);

CREATE TABLE rel_transaction_log_legacy (
  id serial primary key,
  maskType smallint,
  expiryYear smallint,
  chargeId enum,
  listingId time,
  completedAt point,
  friendId mediumint,
  loginAttempts bit,
  email blob,
  eventDate tinyint,
  keywords decimal,
  password mediumint,
  isDefault timestamp,
  blogId time,
  taxRate datetime,
  totalAmount tinyint,
  dimension bigint,
  moduleId point,
  listId int,
  foregroundColor real,
  coordinateX blob,
  accessLevel text,
  companyName bit,
  category enum,
  age timestamp
);

CREATE TABLE inventory (
  id serial primary key,
  orderStatus int,
  category point,
  industryType double,
  machineId int,
  contactEmail tinyint,
  city boolean,
  customField1 timestamp,
  avatar geometry,
  firstName point,
  errorMessage point,
  joinDate time,
  salary text,
  cartId double,
  addressLine2 bit,
  isAdmin date,
  zipCode enum,
  mimeType real,
  coordinateX smallint,
  flagged time,
  guestId varchar,
  version timestamp,
  companyName enum,
  globalId boolean,
  fingerprint time,
  linkId int,
  latitude real,
  groupName int,
  bankAccount bit,
  minLimit tinyint,
  name time
);

CREATE TABLE ext_organization (
  id serial primary key,
  code real,
  hashKey tinyint,
  quantity point,
  modifiedAt mediumint,
  cloudId date,
  cardHolder double,
  accountStatus bit,
  appVersion boolean,
  activeDevices enum,
  isSystem blob,
  checkInTime smallint,
  companyLogo point,
  loginAttempts time,
  forwardTo int,
  industryType mediumint,
  meterNumber geometry,
  documentId boolean,
  fontFamily geometry,
  chatId mediumint,
  fontSize text,
  category serial,
  customerGroup smallint,
  lastName double,
  entryPoint boolean,
  locationId serial,
  addressLine2 set,
  unit boolean
);

CREATE TABLE configlegacy (
  id serial primary key,
  cvv float,
  layerId serial,
  latitude datetime,
  value text,
  monthlyRate serial,
  modifiedAt text,
  phone date,
  customField1 tinyint,
  feedId date,
  messageId double,
  createdAt mediumint,
  displayOrder geometry,
  id double,
  name binary,
  cardNumber smallint,
  deliveryDate smallint,
  expiryMonth timestamp,
  levelId timestamp,
  distributorId mediumint,
  enrollmentDate date,
  billingCycle date
);

CREATE TABLE ver_company_data (
  id serial primary key,
  currency decimal,
  completedAt binary,
  fontFamily float,
  cloudId blob,
  updatedAt mediumint,
  zipCode boolean,
  height boolean,
  checkOutTime tinyint,
  uuid int,
  moduleId timestamp,
  loadTime double,
  department bigint,
  displayOrder smallint,
  budgetCode bigint,
  contactPhone time,
  status text,
  dailyLimit serial
);

CREATE TABLE inventory (
  id serial primary key,
  insertedAt time,
  dateFormat real,
  metadata tinyint,
  billingFrequency timestamp,
  forwardTo tinyint
);

CREATE TABLE sysaccountmeta (
  id serial primary key,
  addressLine2 time,
  metaKeywords real,
  checkOutTime bigint,
  depositAmount enum
);

CREATE TABLE account (
  id serial primary key,
  agentId blob,
  status binary,
  isPublic smallint,
  employmentDate float,
  entryPoint decimal,
  latitude blob,
  description geometry,
  moveId text,
  lastLoginAt timestamp,
  accessLevel datetime,
  bannerImage geometry,
  endDate serial,
  inactiveAt boolean,
  errorMessage timestamp,
  role decimal,
  groupName serial,
  deviceToken geometry,
  listingId serial,
  iconPath bigint,
  priority float
);

CREATE TABLE company_status_v2 (
  id serial primary key,
  courseId tinyint,
  mapId set,
  checkInTime mediumint,
  chatId float,
  orderId enum,
  licenseKey real,
  industryType bit,
  isAdmin bigint,
  friendId float,
  avatar int,
  salary datetime,
  invoiceId smallint,
  token tinyint,
  firstName decimal,
  id enum,
  contactPhone enum,
  ipAddress enum,
  updatedAt mediumint,
  indexKey text,
  chargeId point,
  fileSize varchar,
  dueDateAt bit,
  logLevel binary,
  costCenter blob,
  score blob,
  copyRight binary,
  employmentDate set
);

CREATE TABLE tmporganization (
  id serial primary key,
  layerId blob,
  avatar point,
  followCount time,
  extractId time,
  appVersion point,
  rating blob,
  linkId float,
  headerImage serial,
  languageCode real,
  meterNumber varchar,
  copyRight time,
  facilityId smallint,
  insuranceId smallint,
  mimeType tinyint,
  likeCount int,
  clockIn bigint,
  minLimit mediumint,
  analyticsId blob,
  token bit,
  address datetime
);

CREATE TABLE tbl_order (
  id serial primary key,
  appVersion date,
  isActive bit,
  gateId varchar,
  category real,
  taxRate time,
  forwardTo smallint,
  currency date,
  grade double,
  keywords set,
  folderPath bigint,
  billingFrequency time,
  isFeatured bit,
  logLevel geometry,
  unit smallint
);

CREATE TABLE product (
  id serial primary key,
  blogId int,
  creditCard bit,
  employmentDate real,
  accessLevel set,
  accountType blob,
  completedAt mediumint,
  customerGroup varchar,
  creditScore binary,
  sessionId decimal,
  activeDevices text,
  orderStatus text,
  exportId blob,
  copyRight enum,
  employeeCode mediumint,
  licenseKey double,
  channelId double,
  hourlyRate boolean,
  mainImage text,
  maskType point,
  grade bigint,
  completionRate date,
  firstName bigint,
  companyName decimal,
  currencyCode bigint,
  fontSize point,
  moveId time
);

CREATE TABLE app_user (
  id serial primary key,
  departmentCode time,
  name tinyint,
  depositAmount binary,
  childId serial,
  signature enum
);

CREATE TABLE transaction_type (
  id serial primary key,
  analyticsId binary,
  favoriteCount text,
  fromDate mediumint,
  score geometry,
  dailyLimit datetime,
  isDraft decimal,
  isFeatured timestamp,
  globalId double,
  cityName text,
  fileName timestamp,
  monthlyRate serial,
  agentId datetime,
  contentType enum,
  authToken int,
  endDate float,
  accountNumber set,
  address tinyint,
  manufacturerId decimal,
  geoLocation timestamp,
  awardDate bit,
  fileHash tinyint,
  birthDate tinyint,
  hourlyRate text
);

CREATE TABLE transaction (
  id serial primary key,
  ipAddress real,
  isDeleted blob,
  totalAmount boolean,
  cancelReason varchar,
  deviceType bigint
);

CREATE TABLE extcompanytemp (
  id serial primary key,
  licenseKey decimal,
  childId set,
  algorithm geometry,
  validUntil tinyint,
  password enum,
  postalCode mediumint,
  integrationId bigint,
  loginCount geometry,
  industryType mediumint,
  dateFormat blob,
  mobileNumber tinyint,
  deactivatedAt date,
  dashboardId bigint,
  longitude enum,
  price double,
  claimId geometry,
  isArchived boolean,
  addressLine1 set,
  birthDate set,
  attemptCount float,
  meterNumber varchar,
  rating varchar,
  dueDateAt bit,
  emergencyContact binary
);

CREATE TABLE payment (
  id serial primary key,
  fingerprint binary,
  email geometry,
  creditCard smallint,
  joinDate varchar,
  listingId smallint,
  homePhone decimal,
  likeCount serial,
  listId point,
  comment date,
  forwardTo serial,
  fontSize datetime,
  fileSize set,
  budgetCode time,
  fileType text,
  status set,
  eventDate blob,
  orderId date,
  creditScore int
);

CREATE TABLE transaction_seg_temp (
  id serial primary key,
  enrollmentDate date,
  merchantId time,
  lockoutEnd text,
  fileName mediumint,
  articleId smallint,
  productCode smallint,
  address double,
  fileType enum,
  filterType point,
  actionType int,
  flagged binary,
  dailyLimit decimal,
  minValue binary,
  favoriteCount blob,
  isSystem text,
  locationId binary,
  completedAt binary,
  keywords date,
  configId binary,
  comment geometry,
  role set,
  checkOutTime mediumint,
  firstName point,
  buildNumber varchar,
  cardNumber smallint,
  maxLimit datetime
);

CREATE TABLE order (
  id serial primary key,
  domainName smallint,
  exportId bigint,
  defaultValue smallint,
  dependentId time,
  department binary,
  errorCode mediumint,
  name enum,
  companyLogo float,
  insertedAt int
);

CREATE TABLE transaction (
  id serial primary key,
  albumId real,
  downloadCount boolean,
  postalCode double,
  isFeatured serial,
  longitude mediumint,
  defaultLang smallint,
  gender point,
  accountStatus tinyint,
  isArchived tinyint,
  taxRate set,
  endDate boolean,
  countryCode bigint,
  importId set,
  feedbackId decimal,
  cvv decimal,
  street timestamp,
  jobTitle varchar,
  enabledAt varchar,
  analyticsId float,
  creditLimit bit,
  title bigint,
  clientId double,
  deviceId binary,
  logLevel serial,
  contactPhone decimal,
  copyRight enum,
  isLocked mediumint,
  cardHolder point,
  bluetoothId timestamp,
  state bit
);

CREATE TABLE payment_hist (
  id serial primary key,
  displayOrder enum,
  isLocked real,
  isFeatured float,
  loginCount real,
  balance mediumint,
  name real,
  customField1 boolean,
  articleId enum,
  minLimit date,
  clientId float,
  mobileNumber real,
  postalCode point,
  driverLicense int,
  employmentDate enum,
  age float,
  attachmentUrl decimal,
  facilityId set,
  priority serial,
  isDefault bit,
  displayName serial,
  comment enum,
  adminNotes decimal,
  emailStatus geometry,
  cartId decimal
);

CREATE TABLE transaction (
  id serial primary key,
  createdAt enum,
  rating smallint,
  checkInTime datetime,
  avatar boolean,
  fontFamily time,
  followCount geometry,
  version set,
  foregroundColor smallint,
  accessLevel enum,
  priority text,
  address decimal
);

CREATE TABLE record (
  id serial primary key,
  cancelReason float,
  latitude text,
  city boolean,
  dashboardId datetime,
  signature set
);

CREATE TABLE audit (
  id serial primary key,
  displayName bit,
  latitude blob,
  group mediumint,
  dealerId int
);

CREATE TABLE inventory (
  id serial primary key,
  shippingAddress text,
  lastSeenAt tinyint,
  isRequired float,
  bankAccount decimal,
  cloudId bigint,
  isDeleted serial,
  middleName tinyint,
  exchangeRate double,
  age int,
  listId enum,
  customField1 geometry,
  amount set,
  actionType enum,
  isAdmin smallint,
  sessionId binary,
  clockIn text,
  password varchar,
  completedAt time,
  groupName date,
  currencyCode timestamp,
  dealerId mediumint,
  unit point
);

CREATE TABLE orderv1 (
  id serial primary key,
  thumbnail text,
  contactName varchar,
  billingCycle text,
  group timestamp,
  coordinateY point,
  latitude datetime,
  accountNumber float,
  driverLicense enum,
  maxValue double,
  handlerId text,
  batchId bit,
  deviceId enum,
  grade time,
  longitude int,
  clockOut date,
  isDraft boolean
);

CREATE TABLE core_payment_hist (
  id serial primary key,
  deviceId date,
  courseId timestamp,
  creditScore timestamp,
  dailyLimit serial,
  coordinateY tinyint,
  mapId text,
  machineId geometry,
  marketId int,
  actionType double
);

CREATE TABLE stg_config_notifications (
  id serial primary key,
  connectionString point,
  gender double,
  sessionId boolean,
  authorId serial,
  type float,
  isDefault text,
  manufacturerId real,
  formatType blob,
  productCode set,
  zipCode binary,
  mimeType binary,
  comment set,
  languageCode text,
  configId enum,
  brandId double,
  endPoint time,
  defaultLang datetime,
  maxValue boolean,
  email geometry,
  cardHolder varchar,
  orderId time,
  fileSize enum,
  accountType int,
  password geometry,
  id decimal
);

CREATE TABLE relpaymenttype (
  id serial primary key,
  updatedAt mediumint,
  menuId text,
  driverLicense tinyint,
  isArchived datetime,
  invoiceId varchar,
  state double,
  configId text,
  isDraft tinyint,
  creditLimit date,
  customerGroup date,
  balance timestamp,
  comment enum,
  hashKey blob,
  feedId time,
  isLocked date,
  customerId time,
  enrollmentDate bigint,
  token time
);

CREATE TABLE dst_order_v1 (
  id serial primary key,
  facilityId text,
  attemptCount geometry,
  status blob,
  authMethod mediumint,
  incidentId date,
  claimId serial,
  endDate int,
  customerGroup smallint,
  activeDevices bigint,
  browserType tinyint,
  age text,
  expiryDate real
);

CREATE TABLE pub_inventory_2024 (
  id serial primary key,
  price blob,
  createdAt decimal,
  fontSize datetime,
  metadata time,
  firmwareVersion bigint,
  checkOutTime varchar
);

