CREATE TABLE tmp_record_2024 (
  id serial primary key,
  hashKey blob,
  metaKeywords float,
  industryType enum,
  fileName bit,
  attachmentUrl timestamp,
  certificateId serial,
  salary timestamp,
  brandId enum,
  abandonedCartId datetime,
  comment double,
  currency double,
  headerImage text,
  education time
);

CREATE TABLE user (
  id serial primary key,
  dataSource point,
  fontSize bigint,
  flagged bigint,
  entryPoint decimal,
  languageCode geometry,
  authToken mediumint,
  levelId int,
  campaignId text,
  depositAmount binary,
  amount boolean,
  endDate bit,
  firmwareVersion tinyint,
  managerId blob,
  createdAt double,
  industryType tinyint,
  cardNumber geometry,
  hiddenAt boolean,
  content point,
  middleName double,
  tags geometry,
  priority varchar
);

CREATE TABLE rel_audit (
  id serial primary key,
  bluetoothId geometry,
  geoLocation text,
  companyLogo geometry,
  employmentDate datetime,
  creditCard boolean,
  favoriteCount enum,
  machineId serial,
  version int,
  instanceId binary,
  cancelReason date,
  isAdmin binary,
  industryType binary,
  importId set,
  token real,
  driverLicense int,
  extractId datetime,
  salary datetime,
  indexKey serial,
  entryPoint geometry,
  lastLoginAt timestamp,
  totalAmount mediumint,
  apiVersion int,
  hostName tinyint
);

CREATE TABLE agg_product_seg (
  id serial primary key,
  mobileNumber timestamp,
  minLimit tinyint,
  certificateId geometry,
  extractId binary,
  eventDate binary,
  creditLimit int,
  emailStatus bit,
  bluetoothId enum,
  exchangeRate real,
  attachmentUrl tinyint,
  articleId boolean,
  url decimal,
  deletedAt bigint,
  content timestamp,
  orderId double,
  channelId int,
  flagged point,
  displayOrder varchar,
  id varchar,
  state date,
  orderStatus binary,
  customField1 blob,
  configId smallint,
  insertedAt serial,
  isDeleted tinyint,
  maxValue int,
  isRequired smallint,
  contactEmail int
);

CREATE TABLE record (
  id serial primary key,
  currency timestamp,
  accessLevel timestamp,
  followCount datetime,
  checkInTime text,
  price decimal,
  fileName blob,
  amount text,
  keyId blob,
  minLimit text,
  gateId text,
  address text,
  maxLimit bit,
  levelId binary,
  phone smallint,
  street bit,
  weight tinyint,
  firmwareVersion enum,
  layerId boolean,
  earnedPoints enum,
  value timestamp,
  discountCode time,
  comment geometry,
  expiryYear tinyint,
  enabledAt double,
  dueDateAt decimal,
  city time,
  token int,
  minValue datetime,
  billingFrequency binary,
  group decimal
);

CREATE TABLE dim_transaction (
  id serial primary key,
  loadTime tinyint,
  menuId boolean,
  city time,
  companyName set,
  url smallint,
  latitude real,
  expiryDate timestamp,
  addressLine1 tinyint,
  clockIn timestamp,
  companyLogo int,
  forwardTo decimal,
  moveId bigint,
  downloadCount float,
  chargeId blob,
  orderId blob,
  customField2 date,
  weight time,
  isVerified datetime,
  channelId real,
  address binary,
  postalCode real,
  defaultValue boolean,
  startDate date,
  integrationId geometry,
  incidentId int
);

CREATE TABLE fact_order (
  id serial primary key,
  colorCode geometry,
  displayName bit,
  fontSize tinyint,
  childId text,
  category timestamp,
  productCode real,
  middleName point,
  sessionId blob,
  courseId real,
  manufacturerId time,
  url timestamp,
  bookingDate datetime,
  feedbackId serial,
  bluetoothId set,
  metaKeywords varchar,
  guestId point,
  mimeType smallint,
  lastName tinyint,
  fromDate serial,
  flagged bit,
  currencyCode point,
  maxValue decimal,
  completedAt mediumint,
  rating boolean,
  levelId double,
  gender tinyint,
  fileName decimal,
  distributorId varchar,
  amount decimal,
  logLevel blob,
  id varchar
);

CREATE TABLE record (
  id serial primary key,
  checkInTime boolean,
  filterType serial,
  completedAt serial,
  authMethod point,
  fromDate float,
  isRequired varchar,
  amount bit,
  configId time,
  logLevel set,
  token set,
  billingCycle binary,
  companyId bit,
  earnedPoints tinyint,
  downloadCount varchar
);

CREATE TABLE priv_audit (
  id serial primary key,
  isPublic bigint,
  size real,
  shippingAddress varchar,
  referralCode date,
  exportId real,
  driverLicense boolean,
  mimeType boolean,
  lastName datetime,
  memberCount time,
  languageCode smallint,
  birthDate binary,
  clockIn decimal,
  title geometry,
  documentId enum,
  messageId tinyint,
  guestId time,
  education blob,
  salary time,
  listId timestamp,
  filterType blob,
  downloadCount timestamp,
  instanceId blob,
  rating decimal,
  importId datetime,
  group blob,
  dailyLimit timestamp,
  inactiveAt point
);

CREATE TABLE privconfigextra2024 (
  id serial primary key,
  industryType mediumint,
  cardHolder binary,
  paymentMethod point,
  buildNumber enum
);

CREATE TABLE payment (
  id serial primary key,
  address time,
  courseId decimal,
  incidentId text,
  chatId blob,
  hostName boolean,
  channelId timestamp,
  totalAmount serial,
  group blob,
  name enum,
  validUntil enum,
  hourlyRate bit,
  fileSize text,
  hashKey text,
  attachmentUrl time,
  localeId date,
  metadata enum,
  keyId double,
  endPoint bigint,
  state binary,
  code int,
  rating bigint,
  entityId time,
  birthDate mediumint,
  actionType mediumint,
  addressLine1 binary
);

CREATE TABLE order (
  id serial primary key,
  globalId date,
  folderPath float,
  claimId serial,
  companyName boolean,
  latitude geometry,
  cloudId point,
  lockoutEnd point,
  contactPhone decimal,
  cityName set,
  authToken real,
  score datetime,
  education blob,
  accountStatus bigint,
  labelText blob,
  attemptCount boolean,
  updatedAt geometry,
  priority varchar,
  insertedAt text,
  isVerified tinyint,
  jobTitle binary,
  metaTitle date,
  address boolean,
  content int,
  cardHolder serial,
  managerId bigint,
  chargeId date,
  entityId decimal,
  abandonedCartId float
);

CREATE TABLE transaction_legacy (
  id serial primary key,
  shippingAddress blob,
  currencyCode decimal,
  certificateId blob,
  isPublic time,
  balance serial,
  apiVersion set,
  isArchived geometry,
  accessLevel bigint,
  deletedAt blob,
  category serial
);

CREATE TABLE product (
  id serial primary key,
  country datetime,
  errorCode time,
  content time,
  customerGroup geometry,
  dimension set,
  cityName set,
  languageCode int,
  thumbnail boolean,
  loadTime smallint,
  gateId bit,
  status geometry,
  dateFormat float,
  deliveryDate boolean,
  lastSeenAt bigint,
  avatar real
);

CREATE TABLE inventorylog (
  id serial primary key,
  coverImage text,
  endPoint float
);

CREATE TABLE record (
  id serial primary key,
  gateId serial,
  dataSource tinyint,
  accountNumber bit,
  licenseKey blob,
  expiryYear serial,
  flagged enum,
  salary geometry,
  category smallint,
  deviceToken serial,
  faxNumber binary,
  entityId bit
);

CREATE TABLE account_status_v2 (
  id serial primary key,
  mainImage float,
  maxLimit smallint,
  weight float,
  isVerified bigint,
  contentType decimal,
  expiryMonth varchar,
  currencyCode decimal,
  monthlyRate serial,
  companyName datetime,
  levelId timestamp,
  mimeType time,
  longitude set,
  defaultLang date,
  campaignId tinyint,
  claimId enum,
  messageId boolean,
  audioUrl serial,
  sku decimal,
  chargeId serial,
  minValue timestamp,
  albumId mediumint
);

CREATE TABLE order (
  id serial primary key,
  isVerified date,
  employeeCode timestamp,
  accessLevel bit
);

CREATE TABLE privproduct (
  id serial primary key,
  alertType set,
  firstName text,
  inactiveAt tinyint,
  browserType real,
  deliveryDate real,
  certificateId mediumint,
  errorCode blob,
  keywords boolean,
  quantity double,
  name boolean,
  folderPath bit,
  deactivatedAt binary,
  isVerified float,
  checkOutTime time,
  status enum,
  metaDescription point,
  integrationId double,
  address smallint,
  shippingAddress datetime,
  dateFormat serial,
  machineId timestamp,
  accountNumber time,
  dialCode geometry,
  globalId binary,
  avatar point,
  creditLimit set,
  earnedPoints serial,
  locationId real,
  dimension int,
  feedbackId point,
  facilityId geometry
);

CREATE TABLE customer_seg (
  id serial primary key,
  username date,
  displayName time,
  group date,
  loginAttempts float,
  createdAt smallint,
  dailyLimit point,
  documentId real,
  price float,
  abandonedCartId bigint,
  frameRate timestamp,
  facilityId mediumint,
  url double,
  companyLogo boolean,
  certificateId time,
  managerId datetime,
  courseId date,
  dependentId text,
  authorId serial,
  latitude double,
  dimension geometry,
  driverLicense blob,
  validUntil double
);

CREATE TABLE coreusermeta (
  id serial primary key,
  countryCode enum,
  articleId boolean,
  analyticsId bigint,
  minValue datetime,
  creditLimit geometry,
  adminNotes float,
  isPublic time,
  menuId smallint,
  facilityId timestamp,
  quantity enum,
  checkInTime blob,
  isAdmin decimal,
  age decimal,
  accountType date,
  clockOut text,
  birthDate bit,
  manufacturerId point,
  totalAmount blob,
  comment datetime,
  clientId bit,
  incidentId text
);

CREATE TABLE puborganizationstatus (
  id serial primary key,
  completedAt blob,
  contactPhone enum,
  claimId float,
  password mediumint,
  mimeType varchar,
  defaultLang float,
  itemCount enum,
  connectionString datetime,
  managerId int,
  paymentMethod geometry,
  address bit,
  agentId set,
  avatar decimal,
  childId text,
  hostName datetime,
  accountType point,
  displayOrder mediumint,
  email double,
  group boolean,
  isPublic date,
  firmwareVersion int,
  lastSeenAt float,
  cartId enum,
  employeeId decimal
);

CREATE TABLE tbl_audit_v1 (
  id serial primary key,
  updatedAt geometry,
  group geometry,
  attemptCount time,
  createdAt datetime,
  type text,
  blogId time,
  articleId date,
  localeId real,
  ipAddress tinyint,
  marketId double,
  hiddenAt double,
  dueDateAt point,
  friendId blob,
  gender real,
  documentId double,
  lastName enum,
  avatar set,
  name bit,
  firstName set,
  endPoint tinyint,
  fromDate bit,
  defaultValue geometry,
  analyticsId float,
  amount float,
  discountCode serial,
  value blob,
  bannerImage binary,
  cancelReason binary
);

CREATE TABLE userarchive (
  id serial primary key,
  alertType timestamp,
  content float,
  postalCode int,
  size boolean,
  globalId time,
  algorithm time,
  groupName geometry,
  companyName set,
  macAddress bit,
  maxLimit time,
  metaDescription decimal,
  role varchar,
  isDefault binary,
  entityId datetime,
  gameId decimal,
  comment time,
  authMethod date,
  currencyCode varchar,
  salary varchar,
  entryPoint tinyint,
  levelId timestamp,
  fingerprint bigint,
  guestId boolean,
  lockoutEnd timestamp
);

CREATE TABLE aggorganizationtype (
  id serial primary key,
  lastName boolean,
  browserType datetime,
  domainName time,
  cloudId text,
  authorId timestamp,
  endDate smallint,
  phone geometry,
  clockOut serial,
  size boolean,
  enabledAt time,
  fingerprint tinyint,
  exchangeRate timestamp,
  connectionString varchar,
  albumId serial,
  isDeleted tinyint,
  actionType mediumint,
  dependentId bigint,
  password boolean,
  cityName mediumint
);

CREATE TABLE inventoryseg (
  id serial primary key,
  group double,
  balance boolean,
  childId smallint,
  creditCard binary
);

CREATE TABLE agg_company_2024 (
  id serial primary key,
  moduleId set,
  comment float,
  jobTitle text,
  displayName date,
  houseNumber geometry,
  title set,
  phone time,
  checkInTime real,
  labelText time,
  isPublic geometry,
  loginAttempts decimal,
  folderPath time,
  appVersion binary,
  joinDate time,
  channelId varchar,
  age varchar,
  dialCode date,
  mainImage mediumint,
  merchantId timestamp,
  globalId int,
  apiVersion tinyint,
  token varchar,
  inactiveAt real,
  flagged smallint,
  addressLine2 varchar,
  lastLoginAt double,
  accessLevel real,
  status varchar,
  expiryYear date
);

CREATE TABLE inventory_log_legacy (
  id serial primary key,
  phone binary,
  alertType timestamp,
  campaignId bigint,
  labelText boolean,
  manufacturerId date,
  blogId int,
  errorMessage date,
  comment date,
  mimeType bigint,
  enrollmentDate binary,
  email bigint,
  copyRight tinyint,
  depositAmount tinyint,
  height real,
  moduleId int,
  actionType double,
  guestId bit,
  cityName timestamp,
  shippingAddress float,
  hourlyRate geometry,
  accountType varchar,
  weight double,
  totalAmount smallint,
  driverLicense mediumint,
  messageId enum,
  likeCount set,
  channelId bit
);

CREATE TABLE app_inventory_legacy (
  id serial primary key,
  emergencyContact mediumint,
  discountCode real,
  integrationId datetime,
  hiddenAt varchar
);

CREATE TABLE product (
  id serial primary key,
  authorId varchar,
  fileSize varchar,
  languageCode smallint,
  lastSeenAt timestamp,
  uuid float,
  hostName time
);

CREATE TABLE dim_config_seg (
  id serial primary key,
  menuId blob,
  maritalStatus geometry,
  currency double,
  status binary,
  isFeatured bigint,
  token mediumint,
  brandId binary,
  favoriteCount bigint,
  departmentCode serial,
  domainName set,
  deliveryDate set,
  accessLevel time,
  enabledAt text,
  contactName text,
  weight bit,
  gender binary,
  comment bigint,
  defaultValue real,
  id text
);

CREATE TABLE fact_transaction (
  id serial primary key,
  dashboardId datetime,
  type bit,
  completedAt bit,
  authToken geometry,
  middleName timestamp,
  employmentDate boolean,
  zipCode int,
  birthDate tinyint,
  geoLocation bit,
  certificateId mediumint,
  fingerprint varchar
);

CREATE TABLE account_type_legacy (
  id serial primary key,
  isDefault mediumint,
  metaDescription bit,
  deliveryDate blob,
  alertType text,
  avatar double,
  longitude text,
  eventDate enum,
  age boolean,
  checkOutTime datetime,
  updatedAt varchar,
  errorCode double
);

CREATE TABLE organization_v2 (
  id serial primary key,
  managerId float,
  productCode decimal,
  deactivatedAt serial,
  deviceId mediumint,
  downloadCount point,
  flagged bit,
  shippingAddress decimal,
  licenseKey float,
  bluetoothId blob,
  fileName float,
  customField1 serial,
  attemptCount float,
  coordinateY set,
  emergencyContact varchar,
  coordinateX boolean,
  hiddenAt geometry,
  birthDate enum
);

CREATE TABLE app_payment (
  id serial primary key,
  metadata real,
  dataSource set,
  chargeId text,
  cartId date,
  algorithm varchar
);

CREATE TABLE pub_organization_v1 (
  id serial primary key,
  folderPath mediumint,
  machineId int,
  updatedAt enum,
  customField2 point,
  facilityId time,
  listId bigint,
  fileHash serial,
  forwardTo geometry,
  metadata bit,
  countryCode double,
  bookingDate tinyint,
  minLimit boolean,
  clockOut boolean,
  coordinateY int,
  isFeatured enum,
  coverImage timestamp,
  modifiedAt geometry
);

CREATE TABLE customer (
  id serial primary key,
  batchId float,
  menuId datetime,
  loginCount bit,
  employmentDate text,
  coordinateY bit,
  version enum,
  errorMessage int,
  albumId real,
  messageId bit,
  linkId boolean,
  moveId binary,
  facilityId enum,
  folderPath boolean,
  customField1 double,
  education bit,
  entityId boolean,
  appVersion set,
  dialCode bit,
  customField2 serial,
  validUntil set
);

CREATE TABLE transaction_info (
  id serial primary key,
  phone datetime,
  clockIn geometry,
  blogId point,
  nickname decimal,
  maxLimit boolean,
  username blob,
  group decimal,
  size geometry,
  paymentMethod blob,
  name datetime,
  state int,
  token float,
  category mediumint,
  isBillable decimal,
  status varchar,
  coordinateY decimal,
  password boolean,
  startDate boolean,
  completedAt text,
  value binary,
  rating datetime,
  followCount geometry,
  tags varchar,
  balance datetime,
  authMethod float,
  homePhone tinyint,
  contactPhone varchar,
  agentId binary,
  avatar blob,
  sku geometry
);

CREATE TABLE vwconfigdiv (
  id serial primary key,
  completionRate int,
  languageCode geometry
);

CREATE TABLE account (
  id serial primary key,
  signature geometry,
  accessLevel tinyint,
  createdAt decimal,
  city time,
  abandonedCartId decimal,
  grade time,
  isFeatured timestamp,
  exchangeRate decimal,
  frameRate boolean,
  bookingDate text,
  jobTitle point,
  referralCode varchar
);

CREATE TABLE user_seg (
  id serial primary key,
  sku bigint,
  cityName mediumint,
  group blob,
  analyticsId blob,
  buildNumber enum,
  expiryMonth real,
  modifiedAt point,
  id binary,
  name varchar,
  followCount smallint,
  domainName bit,
  attachmentUrl smallint,
  geoLocation decimal,
  cancelReason decimal,
  amount int,
  loadTime mediumint,
  hostName serial,
  moduleId date,
  connectionString text,
  childId time,
  username timestamp,
  activeDevices date
);

CREATE TABLE fact_inventory (
  id serial primary key,
  isDefault smallint,
  paymentMethod boolean,
  name double,
  phone mediumint,
  copyRight real,
  enabledAt text,
  globalId real
);

CREATE TABLE payment_temp (
  id serial primary key,
  distributorId varchar,
  discount binary,
  activeDevices double,
  accountType real,
  department bigint,
  signature timestamp,
  companyLogo varchar
);

CREATE TABLE tblcompany (
  id serial primary key,
  appVersion binary,
  sku bit,
  locationId bit,
  authMethod date,
  couponCode binary,
  courseId datetime,
  name geometry,
  earnedPoints bigint,
  cancelReason serial
);

CREATE TABLE ext_product (
  id serial primary key,
  isHidden serial,
  domainName bigint,
  taxRate float,
  balance double,
  keyId bit,
  signature mediumint,
  updatedAt float,
  houseNumber serial,
  cartId binary,
  companyName decimal,
  dialCode bigint,
  metaDescription time,
  phone date,
  gameId boolean,
  startDate int,
  enabledAt mediumint
);

CREATE TABLE transactiontype (
  id serial primary key,
  fileSize bit,
  coordinateY set,
  accountType timestamp,
  manufacturerId timestamp,
  role int,
  displayOrder float,
  monthlyRate point,
  dateFormat mediumint,
  importId boolean
);

CREATE TABLE tmptransactionrel (
  id serial primary key,
  joinDate double,
  importId blob,
  dailyLimit serial,
  cartId datetime,
  description mediumint,
  errorMessage timestamp,
  cardHolder geometry,
  authMethod boolean,
  isDefault mediumint,
  latitude timestamp
);

CREATE TABLE userdata (
  id serial primary key,
  minLimit smallint,
  memberCount geometry,
  mimeType point,
  deactivatedAt smallint,
  enabledAt enum,
  contentType varchar,
  avatar serial,
  listingId set,
  labelText smallint,
  distributorId set,
  orderId tinyint,
  phone text,
  minValue varchar,
  maxValue point,
  longitude smallint,
  analyticsId text,
  authMethod varchar,
  accountType mediumint,
  marketId serial,
  firstName smallint,
  createdAt varchar,
  chatId set,
  accessLevel bit
);

CREATE TABLE company (
  id serial primary key,
  forwardTo double,
  password serial,
  phone datetime,
  description bigint
);

CREATE TABLE dim_audit (
  id serial primary key,
  category geometry,
  accountType decimal,
  cartId double,
  sku smallint,
  country boolean,
  homePhone smallint,
  version varchar,
  street datetime,
  id point,
  education float,
  employeeCode real,
  firmwareVersion binary,
  metadata boolean,
  inactiveAt datetime,
  name decimal,
  favoriteCount serial,
  lastLoginAt smallint,
  mainImage float,
  validUntil binary,
  analyticsId geometry
);

