CREATE TABLE tmp_company (
  id serial primary key,
  inactiveAt float,
  extractId double,
  validUntil real,
  distributorId double,
  education datetime,
  discountCode serial,
  accountStatus decimal,
  id date,
  mimeType datetime,
  campaignId blob,
  listingId datetime,
  checkInTime bit,
  weight datetime,
  updatedAt enum,
  productCode timestamp,
  height bit,
  defaultLang smallint,
  bookingDate date,
  handlerId varchar,
  expiryYear varchar,
  isArchived int,
  locationId decimal,
  signature time,
  connectionString set,
  jobTitle smallint,
  facilityId smallint,
  email timestamp,
  completedAt binary,
  adminNotes float,
  taxRate geometry,
  apiKey timestamp
);

CREATE TABLE payment (
  id serial primary key,
  channelId binary,
  endDate serial,
  cartId blob,
  blogId float,
  price time,
  cvv set,
  hostName real,
  displayOrder smallint,
  phone point,
  currencyCode binary,
  monthlyRate time,
  isDeleted geometry,
  earnedPoints boolean,
  flagged date,
  mobileNumber datetime,
  favoriteCount datetime,
  birthDate decimal,
  colorCode bit,
  depositAmount smallint,
  chatId boolean,
  dealerId boolean,
  domainName boolean,
  minLimit text,
  latitude set,
  deviceId set,
  employeeCode text
);

CREATE TABLE payment (
  id serial primary key,
  listId decimal,
  feedId blob,
  customField2 decimal,
  sessionId enum,
  name set,
  flagged varchar,
  audioUrl real,
  sku point,
  domainName text,
  facilityId date,
  companyName time,
  id serial,
  code serial,
  layerId boolean,
  cardNumber smallint,
  integrationId point,
  checkInTime date,
  email text,
  bannerImage int,
  employeeId bigint,
  enabledAt bit,
  deliveryDate enum,
  bankAccount bit,
  maritalStatus binary,
  gateId timestamp,
  startDate real,
  endPoint varchar
);

CREATE TABLE cpy_payment (
  id serial primary key,
  accountNumber real,
  accountStatus blob,
  latitude time,
  fileSize varchar,
  likeCount set,
  appVersion datetime,
  avatar serial,
  alertType time,
  firstName tinyint,
  industryType geometry,
  customerGroup enum,
  category timestamp,
  cartId real,
  attemptCount bit,
  emailStatus date,
  isPublic text,
  driverLicense date,
  productCode serial,
  dependentId text,
  score geometry,
  hourlyRate int,
  creditScore date,
  name datetime,
  emergencyContact double,
  clockIn real,
  globalId geometry,
  isDefault set,
  priority date,
  cacheKey geometry,
  paymentMethod date
);

CREATE TABLE audit_hist (
  id serial primary key,
  isEnabled tinyint,
  handlerId enum,
  frameRate set,
  cartId bigint,
  phone date,
  comment geometry,
  employmentDate set,
  authorId float,
  version datetime,
  connectionString smallint,
  orderStatus mediumint,
  accessLevel bigint,
  isBillable bit,
  enrollmentDate timestamp,
  insertedAt date,
  token datetime,
  isSystem bit,
  nickname datetime,
  cardHolder time
);

CREATE TABLE payment_seg (
  id serial primary key,
  isDefault datetime,
  albumId time,
  address int,
  bookingDate real,
  avatar text,
  title enum,
  machineId point,
  middleName binary,
  configId timestamp,
  validUntil float,
  integrationId decimal,
  loginAttempts boolean,
  hostName float,
  nickname float,
  tags double,
  contactPhone serial,
  priority binary,
  gameId date,
  jobTitle set,
  faxNumber geometry,
  price serial
);

CREATE TABLE tmpproductmeta (
  id serial primary key,
  url smallint,
  contactEmail geometry,
  companyName smallint,
  street enum,
  homePhone bit,
  entryPoint timestamp,
  cardHolder float,
  fileSize serial,
  email datetime,
  contactName varchar,
  shippingAddress blob,
  code datetime,
  folderPath real,
  favoriteCount real,
  dataSource boolean
);

CREATE TABLE dstinventorystatuslegacy (
  id serial primary key,
  duration datetime,
  employeeId serial,
  url double,
  shippingAddress serial,
  forwardTo decimal,
  email varchar,
  entryPoint bit,
  incidentId text
);

CREATE TABLE transaction (
  id serial primary key,
  audioUrl date,
  productCode geometry,
  title double,
  flagged point,
  adminNotes bigint,
  birthDate smallint,
  formatType set,
  groupName smallint,
  ipAddress boolean,
  friendId boolean,
  cacheKey real,
  jobTitle blob,
  dueDateAt timestamp,
  exchangeRate blob,
  isDefault point,
  albumId double,
  gameId int,
  bluetoothId int,
  driverLicense date,
  favoriteCount float,
  merchantId double
);

CREATE TABLE configseg (
  id serial primary key,
  completedAt datetime,
  childId bit,
  id datetime,
  loginCount double,
  hiddenAt int,
  url set,
  machineId timestamp,
  dateFormat binary,
  albumId timestamp,
  emergencyContact real,
  weight binary,
  audioUrl serial,
  bankAccount set,
  status decimal,
  menuId varchar
);

CREATE TABLE tmp_inventory (
  id serial primary key,
  currencyCode decimal,
  role text,
  amount set,
  isArchived int,
  driverLicense binary,
  manufacturerId double,
  editedAt float,
  size serial,
  unit datetime,
  customerId text,
  postalCode boolean,
  completedAt binary,
  lastSeenAt blob,
  activeDevices smallint,
  marketId geometry,
  authorId timestamp,
  depositAmount time
);

CREATE TABLE dim_transaction_new (
  id serial primary key,
  expiryDate float,
  price set,
  fontSize double,
  handlerId bigint,
  phone serial,
  labelText point,
  avatar datetime,
  importId bit,
  backupEmail binary,
  addressLine2 varchar,
  creditLimit set,
  password time,
  authToken enum,
  loginCount serial,
  keywords text,
  url serial,
  incidentId mediumint
);

CREATE TABLE privinventory (
  id serial primary key,
  audioUrl point,
  dueDateAt enum,
  blogId varchar,
  importId date,
  macAddress datetime,
  attemptCount decimal,
  channelId bit,
  hostName tinyint,
  latitude timestamp,
  moveId set,
  earnedPoints serial,
  groupName int,
  cacheKey blob,
  dateFormat datetime,
  bankAccount date,
  name geometry,
  lastSeenAt bigint,
  customField1 datetime,
  amount double,
  dialCode blob,
  companyLogo enum
);

CREATE TABLE config_archive (
  id serial primary key,
  clockOut set,
  documentId blob,
  joinDate blob,
  domainName bit,
  isDeleted datetime,
  friendId serial,
  homePhone set,
  cardHolder real,
  chargeId boolean,
  errorMessage timestamp,
  lastName point,
  validUntil varchar,
  addressLine1 tinyint,
  cancelReason point,
  contactEmail double,
  listId real,
  countryCode serial,
  unit tinyint,
  editedAt double,
  role blob,
  title datetime,
  comment double,
  authorId timestamp,
  accessLevel tinyint,
  brandId timestamp,
  campaignId set,
  maritalStatus decimal,
  errorCode point
);

CREATE TABLE tmp_config (
  id serial primary key,
  unit bigint,
  dueDateAt decimal,
  bankAccount tinyint,
  quantity enum,
  costCenter text,
  clockOut double,
  isArchived serial,
  comment set,
  groupName blob,
  moduleId decimal,
  listingId serial,
  metaKeywords geometry,
  locationId blob,
  memberCount datetime,
  avatar date,
  referralCode varchar,
  coordinateY boolean,
  incidentId tinyint,
  isRequired set,
  minValue double,
  discountCode datetime,
  batchId geometry,
  uuid varchar,
  latitude tinyint,
  chatId double,
  appVersion datetime,
  certificateId timestamp,
  instructorId smallint
);

CREATE TABLE ext_company (
  id serial primary key,
  title decimal,
  countryCode decimal,
  dueDateAt timestamp,
  globalId point,
  completedAt double
);

CREATE TABLE paymentnotifications (
  id serial primary key,
  cityName text,
  albumId binary,
  bannerImage geometry,
  discount float,
  audioUrl double,
  score time,
  costCenter mediumint,
  mapId binary,
  feedId binary,
  clockIn decimal,
  childId double,
  companyLogo int,
  deviceId real,
  phone bigint,
  longitude bigint,
  apiKey varchar
);

CREATE TABLE corecompany (
  id serial primary key,
  globalId text,
  entityId timestamp,
  isAdmin decimal,
  address smallint,
  deviceType double,
  activeDevices bit,
  licenseKey time,
  ipAddress smallint,
  updatedAt geometry,
  apiKey geometry,
  cardHolder bigint,
  gender tinyint,
  deviceId point,
  firstName smallint,
  age varchar,
  floorNumber datetime,
  discountCode double,
  group float,
  education time,
  status binary,
  incidentId text,
  languageCode tinyint,
  avatar binary,
  phone text,
  geoLocation enum,
  backupEmail set,
  dependentId bit,
  meterNumber point,
  billingFrequency varchar,
  createdAt double,
  contractId smallint
);

CREATE TABLE transaction (
  id serial primary key,
  deletedAt date,
  licenseKey bit,
  listingId point,
  firmwareVersion tinyint,
  maritalStatus decimal,
  instructorId int,
  facilityId mediumint,
  duration bigint,
  dueDateAt text
);

CREATE TABLE transaction (
  id serial primary key,
  balance text,
  hiddenAt bigint,
  awardDate datetime,
  bluetoothId date,
  configId geometry,
  cartId mediumint,
  expiryYear point,
  street datetime,
  education point,
  age tinyint,
  type text,
  adminNotes smallint,
  dashboardId tinyint,
  cardHolder point,
  followCount serial,
  couponCode text,
  endDate float,
  comment int,
  isRequired datetime,
  meterNumber date,
  address real,
  firstName point,
  cityName mediumint,
  defaultLang binary
);

CREATE TABLE ver_record_hist (
  id serial primary key,
  listId binary,
  longitude point,
  appVersion bit,
  modifiedAt varchar,
  editedAt decimal,
  fromDate real,
  checkInTime bit,
  country set,
  connectionString float,
  buildNumber point,
  isDraft set,
  depositAmount text,
  grade text,
  feedbackId varchar,
  firstName smallint,
  costCenter mediumint,
  productCode enum,
  gender geometry,
  customerGroup timestamp,
  bluetoothId set,
  alertType decimal,
  signature time,
  discountCode decimal
);

CREATE TABLE auditinfo (
  id serial primary key,
  cancelReason text,
  currency int,
  buildNumber binary,
  likeCount smallint,
  attemptCount tinyint,
  age blob,
  alertType datetime,
  extractId set,
  fontSize timestamp,
  isEnabled timestamp,
  blogId decimal,
  state set,
  fingerprint tinyint,
  localeId decimal,
  earnedPoints serial,
  addressLine2 datetime,
  street text,
  houseNumber binary,
  isBillable geometry,
  sku int,
  feedbackId smallint,
  instructorId set,
  accountType decimal,
  lastSeenAt enum,
  orderStatus blob,
  moveId decimal,
  name tinyint,
  createdAt date
);

CREATE TABLE account (
  id serial primary key,
  isDefault timestamp,
  manufacturerId serial,
  jobTitle real,
  sku datetime,
  algorithm smallint,
  orderStatus enum,
  incidentId int,
  companyId float,
  employeeId serial,
  managerId int,
  contactPhone enum,
  rating geometry,
  macAddress blob,
  apiVersion varchar,
  costCenter bit,
  menuId double,
  floorNumber datetime,
  hashKey point,
  version geometry,
  avatar real,
  isDeleted set,
  maxLimit bigint,
  bluetoothId time,
  contactEmail varchar,
  fromDate double,
  zipCode varchar,
  copyRight float,
  updatedAt enum,
  mainImage set,
  code timestamp
);

CREATE TABLE tmp_product (
  id serial primary key,
  quantity float,
  fromDate float,
  languageCode set,
  id timestamp
);

CREATE TABLE record_notifications (
  id serial primary key,
  chargeId decimal,
  businessType geometry,
  updatedAt real,
  errorMessage timestamp,
  isSystem decimal,
  checkInTime datetime,
  bookingDate binary,
  isBillable serial,
  category tinyint
);

CREATE TABLE transaction_map (
  id serial primary key,
  manufacturerId text,
  dependentId smallint,
  isFeatured int,
  chargeId set,
  billingFrequency timestamp,
  facilityId enum,
  latitude mediumint,
  fingerprint set,
  filterType varchar,
  displayName blob,
  accountType decimal,
  homePhone enum,
  education mediumint,
  longitude real,
  companyLogo enum,
  contactEmail point,
  avatar serial,
  instanceId real,
  isDraft enum,
  accountStatus binary,
  jobTitle mediumint,
  companyName int,
  contactName bigint
);

CREATE TABLE tmp_payment (
  id serial primary key,
  driverLicense enum,
  status int,
  email double,
  currencyCode varchar,
  attemptCount int,
  likeCount mediumint,
  agentId float,
  longitude real,
  feedbackId mediumint,
  addressLine2 smallint,
  expiryDate real,
  isPublic real,
  username varchar,
  exportId serial,
  expiryYear text,
  deactivatedAt blob,
  brandId smallint,
  messageId blob,
  contactPhone binary,
  attachmentUrl date,
  unit blob,
  cvv decimal,
  couponCode time,
  businessType bit,
  marketId decimal
);

CREATE TABLE organization (
  id serial primary key,
  weight varchar,
  folderPath bigint,
  completedAt tinyint,
  dataSource geometry,
  maritalStatus real,
  discountCode geometry,
  height decimal,
  customField1 serial,
  configId time,
  courseId bigint,
  avatar timestamp
);

CREATE TABLE payment (
  id serial primary key,
  cacheKey varchar,
  sku blob,
  employeeId decimal,
  code decimal,
  customerId real,
  isActive binary,
  accountNumber geometry,
  phone real,
  endDate timestamp,
  comment int,
  layerId float,
  fingerprint bigint,
  minValue varchar,
  handlerId bit,
  cvv varchar,
  alertType decimal,
  referralCode tinyint,
  linkId set,
  geoLocation varchar,
  isAdmin float,
  keywords set,
  title decimal,
  depositAmount datetime,
  version time,
  salary text,
  bannerImage blob,
  city enum,
  type boolean,
  lastName bigint
);

CREATE TABLE transactionarchive (
  id serial primary key,
  contentType decimal,
  likeCount geometry,
  updatedAt real,
  address boolean,
  modifiedAt datetime,
  insuranceId binary,
  firstName double,
  dimension decimal,
  colorCode enum,
  bannerImage mediumint,
  chargeId float,
  fileType blob,
  actionType text,
  channelId time,
  invoiceId date,
  ipAddress blob,
  integrationId bigint
);

CREATE TABLE priv_organization (
  id serial primary key,
  ipAddress point,
  city smallint,
  mainImage float,
  eventDate time
);

CREATE TABLE olk_config (
  id serial primary key,
  tags blob,
  billingFrequency bit,
  lockoutEnd decimal,
  defaultLang real,
  content date,
  geoLocation date,
  frameRate set,
  listId bit,
  discountCode blob,
  homePhone decimal,
  favoriteCount tinyint,
  token varchar,
  value bigint
);

CREATE TABLE organizationnew (
  id serial primary key,
  contractId point,
  sku date,
  password varchar,
  entryPoint real,
  macAddress datetime,
  gender datetime,
  downloadCount time,
  id tinyint,
  enabledAt int,
  createdAt date,
  minLimit text
);

CREATE TABLE record (
  id serial primary key,
  dataSource mediumint,
  mapId binary,
  metaDescription text,
  feedId smallint,
  isLocked float,
  eventDate tinyint,
  activeDevices binary,
  isDefault enum,
  accountType int,
  editedAt point,
  hourlyRate float,
  joinDate int,
  endDate varchar
);

CREATE TABLE record (
  id serial primary key,
  rating int,
  duration point,
  signature binary,
  deactivatedAt double,
  contentType datetime,
  metadata bit,
  isFeatured smallint,
  thumbnail blob,
  minValue date,
  headerImage point,
  token bigint,
  mimeType bit,
  endDate varchar,
  batchId enum,
  couponCode real,
  discount timestamp,
  configId int,
  displayOrder int,
  firstName mediumint,
  salary double
);

CREATE TABLE priv_user (
  id serial primary key,
  status boolean,
  street text,
  isDeleted boolean,
  geoLocation float,
  updatedAt double,
  ipAddress point,
  expiryYear time,
  menuId geometry,
  coordinateX decimal,
  metaTitle mediumint,
  amount enum,
  group time,
  awardDate geometry,
  completedAt date,
  backupEmail float,
  accountNumber float,
  dimension enum
);

CREATE TABLE stgrecord (
  id serial primary key,
  mobileNumber boolean,
  brandId enum,
  moduleId binary,
  timezone tinyint,
  signature double,
  isActive tinyint,
  customField1 time,
  country set,
  thumbnail real,
  forwardTo binary
);

CREATE TABLE srcrecordstatustemp (
  id serial primary key,
  cityName enum,
  height datetime,
  costCenter datetime,
  attemptCount datetime,
  handlerId datetime,
  accountType tinyint,
  isArchived time,
  description blob,
  albumId double,
  channelId int,
  birthDate time,
  gender blob,
  folderPath boolean,
  employeeId time,
  memberCount geometry,
  priority boolean,
  lockoutEnd float,
  analyticsId bit,
  fileHash int,
  isBillable tinyint,
  earnedPoints set,
  deactivatedAt boolean,
  messageId set,
  formatType serial,
  certificateId enum,
  quantity tinyint,
  address bigint,
  comment bit,
  dealerId float,
  audioUrl double,
  activeDevices time
);

CREATE TABLE account (
  id serial primary key,
  listingId int,
  checkOutTime time,
  enabledAt boolean,
  appVersion tinyint,
  editedAt tinyint,
  expiryYear float,
  lastLoginAt decimal,
  jobTitle float,
  sku tinyint,
  maxValue decimal
);

CREATE TABLE transactionnotifications (
  id serial primary key,
  deactivatedAt double,
  enrollmentDate text,
  fontFamily time,
  customField2 varchar,
  exportId timestamp,
  insertedAt mediumint,
  coverImage timestamp,
  startDate bigint,
  deliveryDate serial,
  backupEmail geometry
);

CREATE TABLE factorderextra (
  id serial primary key,
  currency boolean,
  priority enum,
  avatar blob,
  amount int,
  brandId decimal,
  minValue serial
);

CREATE TABLE transaction_map (
  id serial primary key,
  discountCode enum,
  importId bit,
  formatType time,
  employmentDate int,
  campaignId float,
  algorithm set,
  isHidden double,
  itemCount serial,
  messageId real,
  analyticsId float,
  accountStatus date,
  connectionString double,
  accountType datetime,
  maxValue double,
  frameRate enum,
  buildNumber timestamp,
  nickname double,
  insuranceId time,
  exchangeRate double,
  abandonedCartId blob,
  integrationId bigint,
  cacheKey blob
);

CREATE TABLE payment_info (
  id serial primary key,
  languageCode bit,
  fromDate double
);

CREATE TABLE ref_order (
  id serial primary key,
  metaKeywords binary,
  accountType timestamp,
  completedAt bit,
  levelId date,
  listId text,
  grade bit,
  orderId mediumint
);

CREATE TABLE ver_product (
  id serial primary key,
  instructorId binary,
  browserType float,
  isBillable blob,
  bankAccount bit,
  status geometry,
  minValue binary,
  managerId date,
  geoLocation enum,
  birthDate mediumint
);

CREATE TABLE tmp_payment_status (
  id serial primary key,
  maxLimit real,
  itemCount binary,
  appVersion varchar,
  facilityId bigint,
  group double,
  title bit,
  agentId point,
  balance text,
  mapId serial,
  category real,
  latitude boolean,
  currency set,
  dueDateAt bigint
);

CREATE TABLE transaction_map (
  id serial primary key,
  flagged set,
  ipAddress set,
  editedAt smallint,
  cacheKey bigint,
  campaignId point,
  accountStatus time,
  mainImage mediumint,
  fingerprint serial,
  dataSource real,
  deviceId bigint,
  fontSize timestamp,
  inactiveAt boolean,
  addressLine2 datetime,
  accountType text,
  latitude int,
  updatedAt set,
  avatar decimal,
  title geometry,
  content timestamp,
  cancelReason text,
  category decimal,
  dealerId smallint,
  isEnabled geometry
);

CREATE TABLE config_seg (
  id serial primary key,
  likeCount decimal,
  isDraft varchar,
  localeId int,
  latitude binary,
  metadata double,
  customerId bigint,
  departmentCode bigint,
  memberCount text,
  emailStatus timestamp,
  startDate bit,
  isAdmin serial,
  facilityId bigint,
  domainName mediumint,
  sku boolean,
  managerId geometry,
  companyName float,
  channelId geometry
);

CREATE TABLE priv_customer (
  id serial primary key,
  isAdmin serial,
  age decimal,
  type geometry,
  grade datetime,
  keywords bigint,
  dashboardId int,
  endPoint timestamp,
  attachmentUrl decimal,
  enrollmentDate double,
  taxRate double,
  homePhone binary,
  memberCount serial,
  description binary,
  accountType binary,
  isBillable date,
  defaultValue time,
  category date,
  duration varchar,
  updatedAt binary,
  dealerId timestamp,
  coverImage blob
);

CREATE TABLE organization_v1 (
  id serial primary key,
  balance varchar,
  password timestamp,
  adminNotes point,
  buildNumber enum,
  cardHolder text,
  quantity time,
  checkInTime decimal,
  labelText set,
  name tinyint,
  agentId bit,
  hiddenAt date,
  analyticsId time,
  minValue serial,
  startDate geometry,
  priority real,
  flagged double,
  updatedAt date,
  phone bit,
  cloudId binary,
  dataSource geometry,
  budgetCode mediumint,
  employmentDate tinyint
);

