CREATE TABLE recordmap (
  id serial primary key,
  country time,
  cardNumber point,
  phone boolean
);

CREATE TABLE olk_company_info (
  id serial primary key,
  loginCount serial,
  layerId timestamp,
  currency double,
  cancelReason timestamp,
  nickname geometry,
  uuid enum,
  merchantId geometry,
  isPublic real,
  instanceId datetime,
  blogId float,
  fromDate geometry,
  dateFormat point
);

CREATE TABLE transaction_rel_v2 (
  id serial primary key,
  discountCode float,
  customField1 boolean,
  bookingDate set,
  favoriteCount float,
  coverImage decimal,
  balance smallint
);

CREATE TABLE tmpcompany (
  id serial primary key,
  articleId binary,
  middleName tinyint,
  employmentDate mediumint,
  authMethod bit,
  jobTitle double,
  billingCycle int,
  loginAttempts datetime,
  department real,
  bookingDate binary
);

CREATE TABLE payment (
  id serial primary key,
  buildNumber datetime,
  createdAt binary,
  floorNumber boolean,
  authToken text,
  id varchar,
  merchantId geometry,
  isDefault int,
  companyLogo tinyint,
  email bigint,
  contentType binary,
  department time,
  browserType decimal,
  signature mediumint,
  isSystem double,
  deletedAt binary,
  fromDate binary
);

CREATE TABLE company (
  id serial primary key,
  isDefault blob,
  description date,
  clockIn decimal,
  shippingAddress tinyint,
  weight tinyint,
  favoriteCount double,
  metaTitle smallint,
  fileType set,
  gameId boolean
);

CREATE TABLE tmpcustomerv1 (
  id serial primary key,
  zipCode mediumint,
  updatedAt time,
  timezone tinyint,
  discount varchar,
  adminNotes tinyint,
  expiryDate decimal,
  inactiveAt datetime,
  phone double,
  monthlyRate time,
  dataSource time,
  manufacturerId double,
  latitude double,
  handlerId datetime,
  street varchar,
  followCount time,
  creditCard boolean,
  courseId bigint,
  department serial,
  batchId date,
  enrollmentDate date,
  comment int,
  defaultLang smallint
);

CREATE TABLE dimorganization2025 (
  id serial primary key,
  exchangeRate geometry,
  weight point,
  instanceId decimal,
  metaKeywords geometry,
  group set,
  street decimal,
  customField1 text,
  updatedAt boolean,
  firmwareVersion serial,
  phone double,
  creditScore double,
  isBillable smallint,
  password time,
  isDefault serial,
  addressLine1 date,
  completionRate real,
  gateId double,
  linkId geometry,
  bankAccount mediumint,
  couponCode float,
  inactiveAt smallint,
  longitude timestamp,
  industryType smallint
);

CREATE TABLE rel_user (
  id serial primary key,
  maritalStatus boolean,
  completedAt varchar,
  lockoutEnd boolean,
  middleName set,
  albumId geometry,
  handlerId varchar,
  filterType time,
  grade binary,
  batchId timestamp,
  content geometry,
  cacheKey set,
  documentId binary,
  downloadCount real,
  creditCard bit,
  creditScore decimal,
  deactivatedAt smallint,
  deviceType timestamp,
  feedId binary,
  bankAccount geometry,
  uuid time
);

CREATE TABLE customer (
  id serial primary key,
  dueDateAt varchar,
  batchId float,
  instanceId binary,
  updatedAt float,
  createdAt int,
  facilityId point,
  hostName mediumint,
  customerGroup tinyint
);

CREATE TABLE app_organization (
  id serial primary key,
  eventDate time,
  creditLimit datetime,
  creditCard decimal,
  listingId boolean,
  frameRate double,
  isDefault int,
  itemCount date,
  hourlyRate decimal,
  deviceType decimal,
  editedAt point,
  isRequired int,
  documentId point,
  modifiedAt int,
  blogId double,
  timezone boolean,
  billingFrequency set,
  agentId timestamp
);

CREATE TABLE user (
  id serial primary key,
  agentId serial,
  macAddress float,
  dependentId real,
  metaTitle time,
  feedbackId text,
  metaDescription blob,
  courseId timestamp,
  downloadCount float,
  balance boolean,
  deviceId tinyint,
  hashKey date,
  manufacturerId text,
  accountStatus real,
  distributorId bigint,
  version point,
  validUntil binary,
  mainImage mediumint,
  rating decimal,
  albumId binary,
  companyName bigint,
  flagged bigint,
  frameRate set,
  itemCount text,
  billingFrequency float,
  buildNumber int,
  exportId point,
  priority float,
  gameId date
);

CREATE TABLE factcustomer (
  id serial primary key,
  comment text,
  keyId binary,
  age double,
  guestId serial,
  minLimit timestamp,
  batchId text,
  zipCode smallint,
  deletedAt double,
  checkOutTime blob,
  group bit,
  customField2 double,
  defaultValue int,
  budgetCode decimal,
  name real,
  isHidden timestamp,
  eventDate serial,
  iconPath bit,
  isPublic decimal,
  machineId real,
  deliveryDate mediumint,
  accountNumber smallint,
  fileName blob,
  cardHolder set
);

CREATE TABLE payment_log (
  id serial primary key,
  macAddress decimal,
  isArchived tinyint,
  avatar geometry,
  globalId binary,
  role double,
  description double,
  value smallint,
  logLevel mediumint,
  email point,
  height real,
  contactName double,
  fontSize bigint,
  formatType serial,
  maxLimit boolean,
  clockIn boolean,
  instanceId blob,
  geoLocation bit,
  analyticsId datetime,
  foregroundColor decimal,
  completedAt decimal,
  handlerId real,
  middleName binary,
  cityName set,
  deviceId date,
  orderStatus text,
  category serial,
  forwardTo blob
);

CREATE TABLE fact_product_2024 (
  id serial primary key,
  grade decimal,
  listId point,
  bookingDate bigint,
  connectionString boolean,
  addressLine1 timestamp,
  chargeId binary,
  geoLocation date,
  groupName decimal,
  phone binary,
  latitude text,
  accountNumber binary,
  password geometry,
  clientId date,
  couponCode bit,
  globalId time
);

CREATE TABLE customer_log (
  id serial primary key,
  layerId decimal,
  floorNumber mediumint,
  batchId bigint,
  menuId tinyint,
  shippingAddress double,
  isActive bit,
  clockIn tinyint,
  buildNumber serial,
  clientId date,
  minValue double,
  authorId tinyint,
  budgetCode set,
  orderId float,
  actionType bit,
  latitude enum,
  bankAccount time,
  displayOrder date,
  instructorId double,
  score mediumint,
  description geometry,
  completedAt geometry
);

CREATE TABLE audit (
  id serial primary key,
  unit point,
  isDefault smallint,
  maxValue enum,
  localeId geometry,
  documentId tinyint,
  title varchar,
  editedAt text,
  referralCode binary,
  inactiveAt double
);

CREATE TABLE privaccount2024 (
  id serial primary key,
  entryPoint decimal,
  defaultLang timestamp,
  exchangeRate binary,
  addressLine2 bit,
  age enum,
  accessLevel bit,
  totalAmount int,
  marketId double,
  earnedPoints geometry,
  contactName time,
  billingCycle bit,
  iconPath bit,
  checkOutTime int,
  isDraft date,
  cardNumber boolean,
  claimId real,
  mobileNumber float,
  createdAt time
);

CREATE TABLE order_notifications (
  id serial primary key,
  group double,
  clockOut smallint,
  dialCode decimal,
  isAdmin geometry,
  claimId boolean,
  budgetCode enum,
  deactivatedAt bit,
  earnedPoints blob,
  gateId mediumint
);

CREATE TABLE customer_new (
  id serial primary key,
  value text,
  loadTime varchar,
  cvv serial,
  contactName double,
  createdAt point,
  token varchar,
  discount mediumint,
  salary enum,
  awardDate double
);

CREATE TABLE stg_order_map (
  id serial primary key,
  middleName set,
  startDate timestamp,
  insertedAt bit,
  firstName blob,
  fontFamily date,
  adminNotes bit,
  createdAt boolean,
  coverImage geometry,
  albumId timestamp,
  domainName decimal,
  moveId blob,
  username time,
  orderStatus geometry,
  folderPath serial,
  type boolean,
  listingId int,
  score decimal,
  geoLocation mediumint,
  levelId float,
  lastLoginAt bit,
  mobileNumber double,
  instanceId set
);

CREATE TABLE product_v2 (
  id serial primary key,
  appVersion geometry,
  instructorId timestamp,
  accessLevel datetime,
  accountType geometry,
  awardDate decimal,
  email geometry,
  balance point,
  version tinyint,
  errorMessage varchar,
  lastName float,
  licenseKey decimal,
  value tinyint,
  countryCode boolean,
  password varchar,
  isSystem geometry,
  employmentDate blob,
  role timestamp,
  coordinateX datetime,
  eventDate date
);

CREATE TABLE config (
  id serial primary key,
  contactEmail double,
  timezone binary,
  clockOut point,
  createdAt date,
  accountNumber timestamp,
  eventDate timestamp,
  couponCode enum,
  layerId timestamp,
  hostName geometry,
  quantity timestamp,
  batchId bit,
  signature time,
  category geometry,
  lastSeenAt smallint,
  bannerImage set,
  entityId binary,
  employeeId enum,
  clockIn decimal,
  name boolean
);

CREATE TABLE olk_inventory_status (
  id serial primary key,
  currency decimal,
  mapId serial,
  linkId binary,
  cardHolder smallint,
  cvv smallint,
  dueDateAt float,
  taxRate real,
  comment set,
  abandonedCartId serial,
  description binary,
  adminNotes bigint,
  connectionString time,
  unit varchar,
  signature blob,
  address binary,
  deactivatedAt datetime,
  guestId serial,
  lastLoginAt set,
  fileHash time,
  industryType datetime,
  createdAt blob,
  handlerId datetime
);

CREATE TABLE vw_transaction_seg (
  id serial primary key,
  id geometry,
  activeDevices geometry,
  latitude blob,
  creditCard decimal,
  isDefault tinyint,
  signature varchar,
  layerId text
);

CREATE TABLE order (
  id serial primary key,
  cloudId float,
  folderPath date,
  awardDate binary,
  firstName enum,
  claimId binary,
  group varchar,
  uuid geometry,
  configId date,
  monthlyRate float,
  keywords mediumint,
  dealerId date,
  emailStatus bit,
  instanceId set,
  licenseKey bigint,
  status varchar,
  maxLimit enum,
  instructorId float,
  loginAttempts bigint,
  enrollmentDate float,
  displayOrder decimal,
  machineId double,
  favoriteCount boolean,
  orderId point
);

CREATE TABLE user (
  id serial primary key,
  joinDate point,
  certificateId smallint,
  listId time,
  id blob,
  description datetime,
  linkId date,
  department enum,
  isAdmin tinyint,
  state bit,
  endDate varchar,
  category int
);

CREATE TABLE log_company (
  id serial primary key,
  fileType date,
  loginAttempts text,
  companyLogo set,
  isEnabled set,
  isFeatured blob,
  deliveryDate double
);

CREATE TABLE ext_company_extra (
  id serial primary key,
  clockOut mediumint,
  metaTitle geometry,
  addressLine2 geometry,
  defaultValue bigint,
  firstName double,
  companyName binary,
  dimension geometry,
  longitude bit,
  fontSize mediumint,
  creditLimit geometry,
  bankAccount timestamp,
  contentType enum,
  isActive blob,
  nickname enum,
  earnedPoints enum,
  birthDate bigint,
  isHidden geometry
);

CREATE TABLE transaction_data (
  id serial primary key,
  expiryYear serial,
  description binary,
  hostName date,
  emergencyContact boolean,
  name datetime,
  businessType binary,
  completedAt varchar,
  billingCycle boolean,
  avatar varchar,
  latitude bit,
  configId time,
  cartId tinyint,
  type smallint,
  entryPoint datetime,
  thumbnail enum,
  isFeatured serial,
  marketId real,
  mainImage real,
  instructorId real,
  isSystem set,
  isEnabled datetime,
  isVerified datetime,
  browserType timestamp,
  globalId float,
  invoiceId binary,
  version int,
  campaignId float,
  depositAmount bigint
);

CREATE TABLE core_payment (
  id serial primary key,
  coordinateX point,
  phone text,
  firstName text,
  street tinyint,
  apiVersion real,
  likeCount bigint,
  moduleId bit,
  height timestamp,
  cardHolder bigint,
  zipCode decimal,
  actionType boolean,
  copyRight blob,
  companyLogo time,
  uuid float
);

CREATE TABLE organization (
  id serial primary key,
  isVerified boolean,
  employmentDate smallint,
  address mediumint,
  name set,
  isAdmin int,
  balance enum,
  blogId date,
  driverLicense tinyint,
  checkInTime varchar,
  email bit,
  street set,
  forwardTo double,
  levelId bigint,
  formatType serial,
  cancelReason mediumint,
  shippingAddress decimal,
  comment double,
  orderId smallint,
  height tinyint,
  depositAmount date,
  creditLimit time,
  customerId geometry,
  billingFrequency boolean,
  loginCount datetime,
  memberCount geometry,
  startDate decimal,
  errorCode date,
  layerId text,
  fingerprint real,
  apiVersion double
);

CREATE TABLE inventory (
  id serial primary key,
  dealerId blob,
  height time,
  isBillable time,
  importId set,
  accessLevel serial,
  age int,
  content geometry,
  followCount mediumint,
  orderStatus float,
  code geometry,
  creditLimit tinyint,
  url time,
  articleId float,
  password int,
  batchId enum,
  integrationId smallint,
  minLimit tinyint,
  birthDate varchar,
  departmentCode int,
  updatedAt float,
  claimId point,
  defaultLang mediumint,
  mobileNumber decimal,
  copyRight datetime,
  deliveryDate bit,
  gateId point
);

CREATE TABLE tmpconfig (
  id serial primary key,
  hourlyRate geometry,
  chargeId set,
  modifiedAt timestamp,
  defaultLang timestamp,
  keyId decimal,
  amount text,
  clockIn int,
  eventDate float,
  earnedPoints enum,
  employeeId date,
  uuid serial,
  integrationId enum,
  avatar date,
  iconPath binary,
  hiddenAt text,
  agentId bigint,
  firstName varchar,
  browserType varchar,
  displayName real,
  checkInTime time,
  buildNumber decimal
);

CREATE TABLE priv_user (
  id serial primary key,
  errorCode text,
  hashKey enum,
  avatar int,
  deviceToken mediumint,
  headerImage set,
  thumbnail date,
  apiVersion binary,
  connectionString mediumint,
  clockIn date,
  group timestamp,
  companyLogo enum,
  orderId real,
  likeCount datetime,
  isActive bit,
  creditLimit mediumint,
  mobileNumber enum,
  itemCount text,
  faxNumber time,
  levelId date,
  creditScore varchar,
  signature real
);

CREATE TABLE company (
  id serial primary key,
  dataSource boolean,
  articleId date,
  maritalStatus time,
  age text,
  accessLevel bit,
  fontFamily float,
  linkId bigint,
  category double,
  merchantId double,
  fromDate binary,
  folderPath time,
  duration varchar,
  certificateId serial,
  token double,
  bannerImage enum,
  insertedAt set,
  code text,
  expiryYear time,
  fileHash binary,
  displayOrder mediumint,
  paymentMethod varchar,
  distributorId bigint,
  zipCode decimal,
  latitude time,
  bookingDate bit
);

CREATE TABLE user_type_v2 (
  id serial primary key,
  discountCode bit,
  dashboardId tinyint,
  creditLimit serial
);

CREATE TABLE product_div (
  id serial primary key,
  amount float,
  fromDate serial,
  languageCode varchar,
  thumbnail double,
  instanceId blob,
  bluetoothId timestamp,
  updatedAt int,
  countryCode serial,
  feedId mediumint,
  code timestamp,
  completedAt point,
  downloadCount enum,
  cartId bit,
  budgetCode text,
  copyRight geometry,
  birthDate double,
  endPoint datetime,
  deviceType double
);

CREATE TABLE olk_audit (
  id serial primary key,
  cloudId float,
  middleName bigint,
  isBillable serial,
  deactivatedAt serial,
  type decimal,
  avatar binary,
  foregroundColor boolean,
  isDefault float,
  address boolean,
  documentId double,
  hashKey serial,
  weight geometry,
  isSystem enum,
  entryPoint smallint,
  cardHolder varchar,
  ipAddress serial,
  insuranceId datetime,
  cacheKey int,
  firstName binary,
  loginCount real
);

CREATE TABLE organization (
  id serial primary key,
  password boolean,
  extractId bit,
  authorId mediumint,
  guestId float
);

CREATE TABLE product_v1 (
  id serial primary key,
  email binary,
  facilityId binary,
  longitude time,
  sessionId int,
  fontSize bigint
);

CREATE TABLE fact_record (
  id serial primary key,
  contactEmail timestamp,
  configId binary,
  paymentMethod float,
  geoLocation enum,
  bankAccount binary,
  companyName double,
  addressLine1 boolean,
  isDraft decimal,
  keyId time,
  deviceToken real,
  businessType timestamp,
  productCode date,
  clockIn decimal,
  education geometry,
  completedAt boolean,
  analyticsId varchar,
  groupName text,
  costCenter binary,
  zipCode point,
  feedbackId set,
  locationId serial,
  adminNotes geometry,
  courseId enum,
  rating geometry,
  fontFamily varchar,
  startDate geometry,
  referralCode enum,
  faxNumber tinyint,
  accessLevel set,
  height tinyint,
  eventDate geometry
);

CREATE TABLE fact_company (
  id serial primary key,
  invoiceId bit,
  metadata geometry,
  attemptCount bigint,
  insuranceId bit,
  fileType text,
  department mediumint,
  joinDate int,
  downloadCount float,
  age set,
  instructorId enum,
  gameId bit,
  currencyCode set,
  jobTitle tinyint,
  driverLicense bigint,
  extractId enum,
  accessLevel time,
  employmentDate int,
  documentId text
);

CREATE TABLE user (
  id serial primary key,
  createdAt bigint,
  street decimal,
  friendId smallint,
  category double,
  bookingDate smallint,
  password double,
  localeId tinyint,
  contactName bigint,
  value geometry,
  licenseKey tinyint,
  latitude geometry,
  fileType smallint,
  meterNumber tinyint,
  updatedAt bit
);

CREATE TABLE account (
  id serial primary key,
  quantity smallint,
  companyId timestamp,
  bannerImage boolean,
  lastSeenAt geometry,
  cloudId real,
  expiryDate smallint,
  title float,
  postalCode date,
  gateId varchar,
  referralCode boolean
);

CREATE TABLE user_hist (
  id serial primary key,
  maxLimit boolean,
  editedAt mediumint,
  displayName text,
  defaultValue point,
  discountCode blob,
  globalId boolean,
  currency boolean,
  cityName point,
  cardHolder bit,
  dependentId double
);

CREATE TABLE company_out_2025 (
  id serial primary key,
  title blob,
  metaDescription text,
  cardHolder set,
  minLimit tinyint,
  password enum,
  creditCard boolean,
  contactEmail decimal,
  checkInTime set,
  industryType decimal,
  documentId mediumint,
  dealerId enum,
  paymentMethod int,
  facilityId blob,
  companyId enum,
  itemCount blob,
  contactName timestamp,
  duration time,
  moveId geometry,
  backupEmail float,
  iconPath int,
  levelId timestamp,
  meterNumber geometry,
  displayName text,
  dueDateAt time
);

CREATE TABLE app_organization (
  id serial primary key,
  companyLogo geometry,
  backupEmail mediumint,
  claimId float,
  errorMessage datetime,
  createdAt enum,
  price bigint,
  uuid int,
  name point,
  attachmentUrl bigint,
  headerImage enum,
  referralCode smallint,
  alertType time,
  depositAmount real,
  linkId bit,
  defaultLang set,
  employeeCode bit,
  exportId blob,
  middleName binary,
  accountType double,
  orderId date
);

CREATE TABLE payment (
  id serial primary key,
  attemptCount enum,
  latitude int,
  middleName geometry,
  shippingAddress double,
  expiryMonth time
);

CREATE TABLE transaction (
  id serial primary key,
  errorMessage tinyint,
  group real,
  depositAmount int,
  accessLevel text,
  instructorId binary,
  type date,
  endDate enum,
  dateFormat varchar,
  companyName enum
);

