CREATE TABLE organization (
  id serial primary key,
  version point,
  maritalStatus geometry,
  itemCount varchar,
  bluetoothId datetime,
  completedAt tinyint,
  height smallint,
  costCenter double,
  dialCode tinyint,
  accountType double,
  channelId decimal,
  logLevel bigint,
  coordinateX bigint,
  enrollmentDate point,
  deletedAt binary,
  tags boolean,
  merchantId tinyint,
  frameRate blob,
  guestId int,
  maxLimit geometry,
  birthDate bit,
  layerId decimal,
  minValue decimal,
  configId enum,
  certificateId double,
  errorCode smallint,
  hourlyRate timestamp
);

CREATE TABLE log_audit (
  id serial primary key,
  hiddenAt smallint,
  category serial,
  fileName mediumint,
  couponCode boolean,
  deviceType decimal,
  deviceToken geometry
);

CREATE TABLE olk_config_type_v2 (
  id serial primary key,
  state mediumint,
  price timestamp,
  incidentId binary,
  guestId point,
  contactEmail tinyint,
  hourlyRate geometry,
  isSystem real,
  title text,
  customField1 date,
  nickname timestamp,
  favoriteCount set,
  isLocked text,
  cartId real,
  loadTime text,
  paymentMethod point,
  agentId real,
  activeDevices point,
  username real,
  description datetime,
  weight float,
  validUntil date,
  audioUrl timestamp,
  messageId binary,
  labelText tinyint
);

CREATE TABLE tblcompanyrellegacy (
  id serial primary key,
  loginCount mediumint,
  inactiveAt smallint,
  status serial,
  indexKey float,
  campaignId smallint,
  latitude double,
  endPoint timestamp,
  sku double,
  apiVersion real,
  companyName time,
  cvv date,
  deviceType enum,
  expiryDate real,
  quantity mediumint,
  alertType text
);

CREATE TABLE order_archive (
  id serial primary key,
  balance date,
  instructorId bit,
  clockIn bit,
  isArchived int,
  attachmentUrl float,
  handlerId serial,
  childId geometry,
  id bigint,
  batchId mediumint,
  referralCode point,
  dependentId mediumint,
  mimeType datetime,
  adminNotes blob,
  enrollmentDate varchar,
  isActive bigint,
  street varchar,
  floorNumber binary,
  industryType bigint,
  updatedAt date,
  loginAttempts timestamp,
  joinDate bigint,
  couponCode time
);

CREATE TABLE product (
  id serial primary key,
  bookingDate bit,
  department smallint,
  cloudId real,
  maxLimit serial,
  dialCode timestamp,
  loadTime point,
  maritalStatus double,
  productCode serial,
  agentId decimal,
  appVersion blob,
  orderId timestamp,
  gender datetime,
  fileHash timestamp,
  headerImage binary
);

CREATE TABLE priv_user (
  id serial primary key,
  defaultValue bigint,
  listId text,
  id bigint,
  amount bigint,
  endPoint decimal,
  itemCount bit,
  billingCycle serial,
  mapId date,
  deviceType blob,
  mainImage float,
  dateFormat serial,
  cancelReason set,
  houseNumber int,
  headerImage int,
  creditLimit real,
  hiddenAt boolean,
  flagged time,
  employeeCode text,
  documentId datetime,
  dialCode varchar,
  endDate double,
  group tinyint,
  guestId tinyint,
  sku tinyint,
  name date,
  accessLevel int
);

CREATE TABLE cpy_product_seg_legacy (
  id serial primary key,
  value time,
  postalCode decimal,
  type datetime,
  copyRight point,
  fingerprint varchar,
  dependentId mediumint,
  gameId float
);

CREATE TABLE audit_seg (
  id serial primary key,
  duration int,
  bannerImage blob,
  timezone int,
  isDraft smallint,
  birthDate point,
  enabledAt varchar
);

CREATE TABLE priv_order (
  id serial primary key,
  middleName bigint,
  analyticsId set,
  state tinyint,
  blogId geometry,
  contactPhone bit,
  campaignId varchar,
  deletedAt enum,
  headerImage set,
  dueDateAt datetime,
  lastName set,
  friendId bigint,
  clockOut real,
  checkInTime blob,
  totalAmount text,
  meterNumber time,
  buildNumber double,
  coordinateX mediumint,
  groupName text,
  accountStatus text,
  email timestamp,
  isDefault mediumint,
  displayName bit,
  fileName bit,
  discountCode boolean,
  budgetCode tinyint,
  emergencyContact smallint
);

CREATE TABLE account_seg (
  id serial primary key,
  alertType time,
  uuid timestamp,
  localeId blob,
  status serial,
  birthDate bigint,
  shippingAddress text,
  dueDateAt varchar,
  invoiceId bigint,
  orderStatus set,
  weight int,
  taxRate varchar,
  zipCode timestamp,
  billingCycle bigint,
  type text,
  mapId boolean,
  macAddress boolean,
  marketId text,
  entryPoint serial
);

CREATE TABLE ext_company_v2 (
  id serial primary key,
  marketId geometry,
  fingerprint int,
  value bigint,
  guestId int,
  adminNotes enum,
  category bigint,
  itemCount point,
  frameRate double,
  minLimit smallint,
  updatedAt decimal,
  isBillable varchar,
  isRequired smallint,
  companyName tinyint,
  metaDescription real,
  colorCode mediumint,
  languageCode binary,
  contactName tinyint,
  thumbnail bigint,
  isDefault bigint,
  isAdmin geometry,
  dimension smallint,
  completionRate mediumint,
  isActive timestamp
);

CREATE TABLE dst_product_meta (
  id serial primary key,
  eventDate float,
  completedAt int,
  fontSize text,
  labelText boolean,
  sessionId enum,
  folderPath time,
  albumId serial,
  discount mediumint,
  claimId bit,
  deviceId datetime,
  accountType smallint,
  referralCode serial,
  token float,
  dueDateAt varchar,
  cloudId time,
  email varchar,
  orderId double,
  joinDate decimal,
  checkOutTime bigint,
  macAddress serial,
  accountNumber serial,
  formatType decimal
);

CREATE TABLE company_2025 (
  id serial primary key,
  createdAt set,
  linkId date,
  dataSource timestamp,
  uuid datetime,
  distributorId time,
  handlerId double,
  homePhone time,
  group bigint,
  id bigint,
  followCount set
);

CREATE TABLE log_customer (
  id serial primary key,
  rating geometry,
  weight double,
  password int,
  displayOrder enum,
  budgetCode smallint,
  enabledAt decimal,
  completionRate enum,
  copyRight set,
  amount point,
  cardHolder blob,
  joinDate blob,
  adminNotes boolean,
  title enum,
  logLevel bit,
  value bigint,
  loginAttempts timestamp,
  driverLicense point,
  manufacturerId smallint,
  phone datetime,
  childId time
);

CREATE TABLE stg_config (
  id serial primary key,
  type real,
  attachmentUrl date,
  businessType blob,
  childId real,
  age varchar,
  attemptCount bigint,
  dateFormat datetime,
  category smallint,
  title bit,
  marketId geometry,
  languageCode binary,
  dealerId int,
  middleName int,
  facilityId text,
  status enum,
  isAdmin double,
  avatar double,
  meterNumber mediumint
);

CREATE TABLE refordernew (
  id serial primary key,
  joinDate tinyint,
  cloudId blob
);

CREATE TABLE tmp_organization (
  id serial primary key,
  fromDate varchar,
  shippingAddress blob,
  geoLocation double,
  fileSize bigint,
  token time,
  instanceId tinyint,
  coordinateY int,
  isRequired bigint,
  driverLicense set,
  orderId enum,
  minLimit point,
  macAddress enum,
  tags blob,
  moduleId decimal,
  taxRate double,
  quantity bit,
  invoiceId boolean,
  completedAt serial,
  thumbnail decimal,
  isArchived smallint,
  defaultLang tinyint,
  id varchar
);

CREATE TABLE log_payment_seg (
  id serial primary key,
  referralCode serial,
  accessLevel real,
  appVersion set,
  machineId tinyint,
  age varchar,
  comment tinyint,
  bannerImage timestamp,
  validUntil double,
  checkOutTime bigint,
  discountCode geometry,
  isDefault binary,
  mainImage double,
  gateId enum,
  avatar bigint,
  maxValue bigint,
  indexKey set,
  city text,
  group date,
  description set,
  moduleId geometry
);

CREATE TABLE app_config (
  id serial primary key,
  id datetime,
  deliveryDate varchar,
  education smallint,
  macAddress tinyint,
  completionRate timestamp,
  minValue varchar,
  accessLevel text,
  description smallint,
  accountType binary,
  comment smallint,
  articleId text,
  checkInTime decimal,
  frameRate timestamp,
  distributorId time
);

CREATE TABLE company_out (
  id serial primary key,
  size smallint,
  longitude timestamp,
  cartId blob,
  analyticsId set,
  iconPath mediumint,
  attemptCount time,
  messageId time,
  amount serial,
  linkId text,
  latitude bit,
  layerId timestamp,
  extractId set,
  depositAmount real,
  indexKey float,
  bookingDate boolean,
  addressLine1 serial,
  monthlyRate float,
  dailyLimit float,
  code binary,
  foregroundColor smallint,
  childId mediumint,
  addressLine2 mediumint,
  courseId bit,
  articleId tinyint,
  campaignId text,
  email text
);

CREATE TABLE coreinventory (
  id serial primary key,
  isVerified timestamp,
  channelId binary,
  billingCycle datetime,
  name enum,
  downloadCount varchar,
  latitude serial,
  duration point,
  category blob,
  status mediumint,
  paymentMethod tinyint,
  keyId tinyint,
  clockOut float,
  hashKey bit,
  updatedAt bigint,
  alertType bit,
  thumbnail geometry,
  gateId float,
  hiddenAt serial,
  code point,
  marketId bigint,
  entityId decimal,
  favoriteCount mediumint,
  licenseKey bigint,
  gender datetime,
  orderStatus float,
  title mediumint,
  group mediumint,
  floorNumber real,
  metaKeywords mediumint
);

CREATE TABLE logorderout (
  id serial primary key,
  id binary,
  defaultLang float,
  taxRate text,
  listId serial,
  earnedPoints set,
  minValue serial,
  isHidden decimal,
  childId real,
  type smallint,
  fontFamily point,
  loadTime time,
  displayName date,
  completionRate time,
  faxNumber real,
  inactiveAt date
);

CREATE TABLE rel_order_rel (
  id serial primary key,
  gateId smallint,
  downloadCount binary,
  tags decimal,
  longitude bigint,
  signature datetime,
  clockOut point,
  entryPoint smallint,
  floorNumber real,
  monthlyRate text,
  mapId enum,
  id bigint
);

CREATE TABLE vw_account_hist (
  id serial primary key,
  totalAmount text,
  geoLocation int,
  jobTitle smallint,
  contactEmail datetime,
  isRequired enum,
  depositAmount binary,
  id timestamp,
  domainName timestamp,
  chatId double,
  enrollmentDate float,
  isAdmin blob,
  value binary,
  contentType smallint,
  driverLicense serial,
  updatedAt geometry,
  customField1 date,
  albumId binary,
  exchangeRate bit,
  dimension blob,
  maskType blob,
  listingId binary,
  cityName int,
  taxRate text,
  batchId blob,
  maxLimit double,
  balance decimal,
  floorNumber date,
  documentId geometry,
  deletedAt datetime,
  loginAttempts real,
  employeeCode enum
);

CREATE TABLE transaction (
  id serial primary key,
  thumbnail datetime,
  dialCode real,
  entityId text,
  amount date,
  mobileNumber set,
  expiryDate real,
  token geometry,
  countryCode set,
  size real,
  hourlyRate datetime,
  username bigint,
  referralCode datetime,
  distributorId bit,
  latitude timestamp,
  childId tinyint,
  role varchar,
  createdAt datetime,
  contactEmail timestamp,
  shippingAddress serial,
  agentId enum,
  joinDate date,
  cartId float,
  driverLicense timestamp,
  category bigint,
  type set,
  bankAccount boolean,
  addressLine2 date
);

CREATE TABLE transaction_v1 (
  id serial primary key,
  agentId real,
  token varchar,
  chatId double,
  driverLicense double,
  layerId bigint,
  value text,
  couponCode varchar,
  mapId time,
  bluetoothId smallint,
  group binary,
  marketId real,
  shippingAddress float,
  discountCode time,
  country tinyint,
  loadTime time,
  dependentId time,
  height bigint,
  priority blob,
  latitude bit,
  isHidden tinyint,
  departmentCode date,
  firmwareVersion timestamp,
  backupEmail real,
  isRequired tinyint,
  moduleId bit,
  quantity boolean,
  cloudId set,
  street enum,
  cityName varchar
);

CREATE TABLE record (
  id serial primary key,
  taxRate double,
  mimeType smallint,
  balance datetime,
  folderPath time,
  group varchar,
  instructorId mediumint,
  name date,
  editedAt binary,
  businessType binary,
  isVerified float,
  contentType binary,
  cardHolder serial,
  sku date,
  unit geometry,
  ipAddress decimal,
  deliveryDate serial,
  cacheKey decimal,
  referralCode decimal
);

CREATE TABLE cpy_customer (
  id serial primary key,
  contentType geometry,
  amount date,
  role real,
  folderPath int,
  localeId bigint,
  frameRate time,
  feedId set,
  dependentId bigint,
  sku bigint,
  defaultValue binary
);

CREATE TABLE product (
  id serial primary key,
  attemptCount float,
  licenseKey bit,
  endDate point
);

CREATE TABLE tmppayment (
  id serial primary key,
  fontFamily float,
  size varchar,
  filterType decimal,
  creditScore int,
  firmwareVersion binary,
  age binary,
  coverImage real,
  productCode real,
  deviceId varchar,
  authToken int,
  currencyCode blob
);

CREATE TABLE payment (
  id serial primary key,
  isArchived enum,
  isRequired binary,
  totalAmount enum,
  sessionId varchar,
  buildNumber double,
  indexKey blob,
  deviceId enum,
  bankAccount decimal,
  folderPath blob,
  channelId decimal
);

CREATE TABLE paymentlegacy (
  id serial primary key,
  companyName boolean,
  depositAmount real,
  blogId date,
  employeeId bit,
  backupEmail binary,
  courseId binary,
  minLimit bigint,
  buildNumber double,
  dataSource timestamp,
  expiryMonth int
);

CREATE TABLE transaction (
  id serial primary key,
  clockOut mediumint,
  dateFormat binary,
  updatedAt varchar,
  completedAt enum,
  isSystem binary,
  albumId tinyint,
  deviceId double,
  filterType bigint,
  department float,
  machineId boolean,
  orderId blob,
  certificateId geometry,
  name serial,
  startDate point,
  exportId double,
  feedId smallint,
  fileName boolean,
  balance mediumint,
  entryPoint double,
  configId date
);

CREATE TABLE account_seg (
  id serial primary key,
  budgetCode serial,
  incidentId text,
  hashKey float,
  merchantId text
);

CREATE TABLE inventory (
  id serial primary key,
  manufacturerId serial,
  courseId set,
  memberCount serial,
  itemCount enum,
  department varchar,
  lastName geometry,
  locationId real
);

CREATE TABLE company (
  id serial primary key,
  age point,
  fromDate text,
  shippingAddress datetime,
  price bit,
  isVerified double,
  category enum,
  departmentCode bit,
  balance text,
  apiKey timestamp,
  group blob,
  type double,
  minLimit enum,
  importId timestamp,
  cardNumber geometry,
  documentId smallint,
  title real,
  companyName real,
  inactiveAt tinyint,
  zipCode text,
  comment enum,
  feedbackId real,
  billingFrequency point,
  feedId tinyint,
  creditCard set,
  isSystem serial,
  accountNumber decimal,
  managerId decimal
);

CREATE TABLE core_transaction_type (
  id serial primary key,
  businessType binary,
  isHidden double,
  configId decimal,
  chatId decimal,
  balance datetime,
  title binary,
  contactEmail tinyint,
  globalId bigint,
  foregroundColor varchar,
  postalCode blob,
  hiddenAt double,
  unit timestamp,
  ipAddress int,
  mimeType float,
  integrationId mediumint,
  orderStatus geometry,
  customerGroup bigint,
  accessLevel geometry
);

CREATE TABLE audit (
  id serial primary key,
  floorNumber geometry,
  creditLimit bit,
  entityId boolean
);

CREATE TABLE vwrecord (
  id serial primary key,
  audioUrl decimal,
  joinDate datetime,
  balance point,
  depositAmount text,
  orderStatus text,
  hashKey tinyint,
  abandonedCartId float,
  merchantId int,
  buildNumber real,
  insuranceId datetime,
  childId geometry,
  accountType tinyint,
  password decimal,
  enrollmentDate binary,
  deletedAt serial,
  houseNumber date,
  city tinyint,
  username varchar,
  countryCode boolean,
  businessType tinyint,
  isDraft boolean,
  dialCode binary,
  timezone geometry,
  likeCount datetime,
  isAdmin blob
);

CREATE TABLE extcustomer2024 (
  id serial primary key,
  channelId real,
  lastLoginAt bit,
  ipAddress binary,
  itemCount set,
  listId bit,
  chargeId boolean,
  domainName varchar
);

CREATE TABLE transaction (
  id serial primary key,
  adminNotes real,
  username timestamp,
  hashKey boolean,
  isSystem geometry,
  createdAt point,
  metaDescription text,
  hiddenAt bit,
  endDate decimal,
  productCode bigint,
  formatType float,
  contactPhone varchar,
  abandonedCartId real,
  cartId bit,
  fingerprint text,
  couponCode blob,
  isAdmin tinyint,
  phone point,
  companyId blob,
  contentType binary,
  chatId smallint,
  authToken smallint,
  completionRate serial,
  dueDateAt blob
);

CREATE TABLE tbl_record (
  id serial primary key,
  cardNumber float,
  childId real,
  clockIn blob,
  cancelReason tinyint,
  validUntil float,
  completionRate smallint,
  listingId text,
  signature double,
  browserType binary,
  firmwareVersion time,
  checkOutTime bit,
  createdAt real,
  category serial,
  facilityId text,
  customerId binary,
  education bit,
  addressLine2 tinyint,
  coordinateX time,
  loginAttempts enum,
  creditScore timestamp
);

CREATE TABLE transaction (
  id serial primary key,
  fingerprint serial,
  costCenter enum,
  actionType point,
  longitude decimal,
  password text,
  group text,
  driverLicense point,
  employeeId set,
  loadTime decimal,
  lastName geometry,
  abandonedCartId point,
  isLocked float,
  configId time,
  coordinateX set,
  email timestamp,
  fileName geometry,
  score date,
  isArchived int,
  alertType datetime,
  referralCode point,
  checkInTime date
);

CREATE TABLE inventorylog (
  id serial primary key,
  dealerId double,
  dependentId point,
  dimension blob,
  audioUrl decimal,
  maritalStatus date,
  education point,
  gender serial,
  status decimal,
  linkId boolean,
  rating enum,
  category double,
  likeCount int,
  maxLimit int,
  departmentCode varchar,
  folderPath enum,
  dueDateAt smallint,
  integrationId datetime,
  iconPath int,
  dateFormat time,
  checkOutTime decimal,
  marketId time
);

CREATE TABLE record (
  id serial primary key,
  metadata timestamp,
  contractId real,
  amount text,
  importId tinyint,
  couponCode blob,
  shippingAddress enum,
  enabledAt boolean,
  coverImage geometry,
  jobTitle datetime,
  lastSeenAt decimal,
  deliveryDate int,
  maxLimit mediumint,
  maritalStatus decimal
);

CREATE TABLE pub_product_type (
  id serial primary key,
  keywords binary,
  comment double,
  awardDate set,
  alertType bigint,
  age smallint,
  orderId datetime,
  countryCode boolean,
  browserType varchar,
  unit int,
  quantity blob,
  linkId boolean,
  isDraft int,
  education timestamp,
  amount real,
  companyName tinyint
);

CREATE TABLE company (
  id serial primary key,
  contactName int,
  cardNumber point,
  isArchived serial,
  city decimal,
  metaTitle float,
  contactPhone mediumint,
  weight geometry,
  flagged binary,
  marketId serial,
  maskType double,
  mimeType point,
  emailStatus time,
  completedAt set,
  checkOutTime tinyint,
  isPublic enum,
  gender text,
  signature real,
  birthDate date,
  deviceId blob,
  homePhone set,
  agentId date,
  contractId float,
  foregroundColor enum,
  fromDate timestamp,
  cacheKey tinyint,
  backupEmail boolean,
  updatedAt set,
  metaDescription serial,
  street int,
  audioUrl bit,
  isActive set
);

CREATE TABLE customertemp (
  id serial primary key,
  gender geometry,
  firmwareVersion set,
  totalAmount bit,
  cvv date
);

CREATE TABLE agg_payment_out (
  id serial primary key,
  handlerId datetime,
  zipCode bit,
  fileHash tinyint,
  insuranceId int,
  configId real,
  title varchar,
  sessionId point,
  meterNumber decimal,
  abandonedCartId double,
  favoriteCount smallint
);

