CREATE TABLE company (
  id serial primary key,
  title boolean,
  editedAt varchar,
  weight binary,
  category time,
  ipAddress int,
  keywords blob,
  customerGroup mediumint,
  exportId tinyint,
  campaignId geometry,
  emailStatus blob,
  status set,
  isArchived double,
  latitude datetime,
  dataSource point,
  quantity text,
  moduleId datetime,
  colorCode datetime,
  priority timestamp,
  nickname point,
  actionType blob,
  code varchar,
  country serial,
  token boolean,
  childId text,
  brandId int
);

CREATE TABLE audit_type (
  id serial primary key,
  connectionString decimal,
  balance mediumint,
  id bigint,
  companyLogo float,
  enrollmentDate decimal,
  cardNumber float,
  referralCode bit
);

CREATE TABLE payment (
  id serial primary key,
  dailyLimit mediumint,
  emergencyContact blob,
  cvv point,
  isDraft enum,
  fontFamily point,
  longitude timestamp,
  browserType geometry,
  totalAmount text,
  checkInTime date,
  title timestamp,
  keyId bigint,
  unit text,
  address mediumint,
  hourlyRate double,
  createdAt text,
  loadTime decimal,
  completionRate enum,
  dimension real,
  mapId enum,
  brandId int,
  height bit
);

CREATE TABLE inventory (
  id serial primary key,
  bannerImage geometry,
  token text,
  actionType boolean,
  loadTime time,
  logLevel bit,
  metaDescription bit,
  sku set,
  cardHolder text,
  licenseKey serial,
  isBillable text,
  accessLevel timestamp,
  ipAddress mediumint,
  faxNumber text,
  exportId smallint,
  manufacturerId datetime,
  backupEmail time,
  signature mediumint,
  marketId real,
  password timestamp,
  mobileNumber timestamp
);

CREATE TABLE transaction_meta_v1 (
  id serial primary key,
  eventDate float,
  cardNumber varchar,
  salary date,
  campaignId real,
  bookingDate decimal,
  bluetoothId time,
  discount serial,
  comment bigint,
  email bit,
  metaKeywords blob,
  formatType datetime,
  licenseKey serial,
  macAddress boolean,
  listingId smallint,
  isHidden decimal,
  gameId binary,
  frameRate binary,
  balance varchar
);

CREATE TABLE dst_account_status (
  id serial primary key,
  analyticsId mediumint,
  apiKey date,
  employeeId geometry,
  avatar double,
  macAddress text,
  weight point,
  sessionId double,
  coverImage tinyint,
  type tinyint,
  fingerprint date,
  fileType mediumint,
  blogId geometry,
  balance point,
  channelId bigint,
  maxValue decimal,
  isEnabled decimal,
  contractId decimal,
  completionRate bit,
  billingFrequency smallint,
  accountType float,
  createdAt timestamp,
  zipCode tinyint,
  isDefault double,
  coordinateY varchar,
  clientId float
);

CREATE TABLE cpyrecordout (
  id serial primary key,
  shippingAddress boolean,
  state enum,
  clockIn point
);

CREATE TABLE record (
  id serial primary key,
  budgetCode text,
  amount bigint,
  fileHash float,
  salary int,
  layerId binary,
  foregroundColor time,
  creditLimit set,
  accountType decimal,
  cvv geometry,
  currency timestamp,
  quantity int,
  articleId tinyint,
  deviceToken int,
  apiKey bigint,
  dashboardId decimal,
  type tinyint,
  endPoint decimal,
  memberCount varchar,
  loginCount double,
  email float,
  customField2 int,
  shippingAddress smallint,
  monthlyRate mediumint,
  isHidden enum
);

CREATE TABLE tmporder (
  id serial primary key,
  checkInTime float,
  nickname geometry,
  score enum,
  latitude enum,
  companyLogo decimal,
  dailyLimit time,
  discountCode real,
  likeCount enum,
  listId date,
  mobileNumber date,
  distributorId smallint,
  followCount real,
  linkId date,
  blogId datetime,
  chargeId text,
  loginCount boolean,
  businessType varchar,
  department bit,
  status tinyint,
  group tinyint
);

CREATE TABLE exttransaction (
  id serial primary key,
  orderStatus point,
  addressLine2 bit,
  description time,
  maritalStatus real,
  countryCode time,
  token time,
  budgetCode timestamp,
  role boolean,
  priority timestamp,
  bluetoothId blob,
  orderId smallint,
  isEnabled smallint,
  messageId tinyint,
  marketId boolean,
  documentId int,
  isRequired decimal,
  cloudId varchar,
  folderPath time,
  articleId datetime,
  rating binary,
  attemptCount geometry,
  importId geometry,
  linkId double,
  nickname datetime,
  fontSize int,
  productCode int,
  createdAt binary,
  contactPhone smallint,
  moduleId real
);

CREATE TABLE config (
  id serial primary key,
  creditLimit date,
  employeeId set,
  priority double,
  customerId smallint,
  tags serial,
  entryPoint real,
  awardDate serial,
  isActive time,
  displayName timestamp,
  customField2 blob,
  productCode smallint,
  mapId float,
  email blob,
  status time,
  dialCode smallint,
  cartId boolean,
  licenseKey geometry,
  favoriteCount datetime,
  city smallint,
  accessLevel int,
  dateFormat mediumint,
  flagged smallint,
  analyticsId serial,
  updatedAt datetime,
  earnedPoints double,
  isDraft boolean,
  lockoutEnd binary,
  isRequired set,
  channelId enum,
  emergencyContact serial
);

CREATE TABLE olkconfig (
  id serial primary key,
  editedAt decimal,
  cardNumber text,
  avatar blob,
  category real,
  maskType date,
  lastName varchar,
  labelText text,
  albumId real,
  contactEmail date,
  isFeatured timestamp,
  title date,
  errorCode decimal,
  fontSize blob,
  companyName binary,
  isSystem bit
);

CREATE TABLE coreaccountextrav1 (
  id serial primary key,
  version int,
  batchId bit,
  deviceToken timestamp,
  customField1 smallint,
  insertedAt time,
  accessLevel boolean,
  eventDate varchar,
  dimension serial,
  code real,
  labelText time,
  expiryYear int,
  status timestamp,
  currencyCode double,
  isFeatured real,
  longitude decimal,
  integrationId datetime,
  isActive decimal,
  incidentId real,
  apiVersion enum,
  blogId blob,
  employmentDate bit,
  timezone set,
  monthlyRate bigint,
  forwardTo int,
  buildNumber blob
);

CREATE TABLE rel_audit_meta (
  id serial primary key,
  password blob,
  isDraft set,
  integrationId time,
  currency bigint,
  listId double,
  checkOutTime enum,
  fontFamily point,
  filterType serial,
  importId serial,
  id smallint,
  browserType real,
  algorithm bigint,
  expiryDate mediumint,
  isEnabled double,
  memberCount binary,
  fileSize date,
  completionRate double,
  phone bit,
  clockIn date,
  startDate bit,
  businessType timestamp,
  childId geometry,
  deviceId timestamp,
  longitude time,
  loadTime int,
  campaignId date,
  isRequired geometry,
  gateId bigint,
  lastName time,
  exportId double,
  loginCount point
);

CREATE TABLE cpy_config_notifications (
  id serial primary key,
  colorCode varchar,
  isHidden geometry,
  token tinyint,
  tags mediumint,
  lastSeenAt int,
  metaKeywords geometry,
  dashboardId set,
  name time,
  employeeId float,
  dataSource blob,
  handlerId datetime
);

CREATE TABLE auditsegtemp (
  id serial primary key,
  endDate text,
  maskType varchar
);

CREATE TABLE product (
  id serial primary key,
  cardNumber blob,
  expiryDate binary,
  creditScore blob
);

CREATE TABLE vwinventory (
  id serial primary key,
  accountNumber blob,
  colorCode serial,
  appVersion geometry,
  attachmentUrl point,
  deviceType set,
  firstName serial,
  metaKeywords blob,
  exportId tinyint,
  budgetCode timestamp,
  documentId double,
  zipCode binary
);

CREATE TABLE user_status_temp (
  id serial primary key,
  marketId binary,
  mainImage bigint,
  completedAt geometry,
  gateId bigint,
  cacheKey date,
  name varchar,
  accountStatus mediumint,
  isBillable blob,
  isDefault date,
  cancelReason serial,
  clockIn blob,
  formatType set,
  listId bigint,
  authMethod timestamp,
  foregroundColor bigint,
  jobTitle point,
  hashKey set,
  apiKey blob,
  gender time,
  version date,
  totalAmount set,
  billingCycle set,
  comment enum,
  feedbackId float,
  group set,
  defaultValue boolean
);

CREATE TABLE transaction_extra_2025 (
  id serial primary key,
  avatar time,
  rating text,
  salary float,
  articleId date,
  orderId binary,
  industryType timestamp,
  departmentCode tinyint,
  certificateId blob,
  comment mediumint,
  hashKey serial,
  title double
);

CREATE TABLE tbl_payment_status_v1 (
  id serial primary key,
  value bigint,
  deactivatedAt boolean,
  createdAt text,
  maxValue decimal,
  endPoint decimal,
  abandonedCartId enum,
  productCode set,
  isActive timestamp,
  authToken bit,
  creditLimit mediumint,
  deviceToken mediumint,
  cvv bit,
  merchantId timestamp,
  favoriteCount smallint,
  forwardTo double,
  moveId bigint,
  priority tinyint,
  copyRight datetime,
  fontSize text
);

CREATE TABLE order_info (
  id serial primary key,
  password timestamp,
  customerGroup mediumint,
  favoriteCount bit,
  businessType geometry,
  addressLine1 mediumint,
  dealerId timestamp,
  loginAttempts bit,
  dataSource varchar,
  fontFamily varchar,
  creditCard bit,
  category enum
);

CREATE TABLE order (
  id serial primary key,
  currencyCode real,
  quantity smallint,
  dateFormat binary,
  accessLevel timestamp,
  status bigint,
  inactiveAt varchar,
  monthlyRate set,
  taxRate text,
  apiKey decimal,
  listId int,
  dailyLimit enum,
  gameId mediumint,
  companyLogo date,
  hashKey enum,
  entryPoint int,
  token smallint
);

CREATE TABLE payment (
  id serial primary key,
  phone boolean,
  grade binary,
  orderStatus datetime,
  headerImage boolean,
  birthDate tinyint,
  moveId varchar,
  localeId serial,
  industryType varchar,
  listId serial,
  mimeType set,
  value geometry,
  title boolean,
  validUntil timestamp,
  expiryYear serial,
  mobileNumber blob,
  brandId point,
  fingerprint decimal,
  emergencyContact blob,
  shippingAddress real,
  expiryMonth bit,
  contractId bit,
  listingId double,
  ipAddress tinyint,
  insertedAt point,
  deliveryDate point,
  content real,
  documentId timestamp,
  downloadCount bit
);

CREATE TABLE account (
  id serial primary key,
  longitude smallint,
  loadTime binary
);

CREATE TABLE order_2024 (
  id serial primary key,
  listingId tinyint,
  mobileNumber int,
  amount float,
  deliveryDate datetime,
  fontSize time,
  dealerId set,
  addressLine1 bigint,
  orderId decimal,
  balance double,
  phone blob,
  accountType decimal,
  dependentId text,
  title blob,
  zipCode blob,
  defaultValue blob,
  avatar boolean,
  contractId bigint,
  inactiveAt smallint,
  costCenter enum,
  integrationId double,
  comment real,
  isArchived point,
  paymentMethod decimal,
  updatedAt enum,
  completedAt boolean,
  flagged smallint,
  firmwareVersion double,
  metaKeywords point
);

CREATE TABLE tmp_account (
  id serial primary key,
  dashboardId tinyint,
  isPublic blob,
  group date,
  marketId datetime,
  authToken date,
  machineId boolean,
  managerId float,
  totalAmount date,
  localeId smallint,
  albumId binary,
  companyName boolean,
  createdAt text,
  buildNumber geometry
);

CREATE TABLE apprecordstatus (
  id serial primary key,
  isBillable timestamp,
  bankAccount varchar,
  totalAmount datetime
);

CREATE TABLE order_meta_2024 (
  id serial primary key,
  fontSize float,
  joinDate set,
  copyRight smallint,
  maxValue boolean,
  cancelReason set,
  completionRate timestamp,
  fileSize smallint,
  sessionId time,
  startDate serial,
  extractId blob,
  email tinyint,
  customerId decimal,
  address time,
  ipAddress blob,
  status blob,
  clientId varchar,
  contentType int,
  department varchar,
  weight blob,
  bankAccount boolean,
  isActive enum,
  colorCode date,
  articleId float,
  contactPhone time,
  isAdmin timestamp
);

CREATE TABLE dim_inventory (
  id serial primary key,
  postalCode bigint,
  isHidden blob,
  avatar float,
  displayOrder boolean,
  isDefault int
);

CREATE TABLE config_log (
  id serial primary key,
  meterNumber mediumint,
  ipAddress text,
  cardNumber decimal,
  id int,
  batchId smallint,
  chargeId geometry,
  creditCard datetime,
  username decimal,
  errorCode int,
  code serial,
  configId double,
  messageId point,
  linkId date,
  feedbackId serial,
  enabledAt text,
  displayOrder mediumint,
  exportId point,
  customField1 double,
  birthDate decimal,
  shippingAddress time,
  status timestamp,
  url geometry,
  memberCount smallint,
  machineId geometry,
  dialCode enum,
  iconPath mediumint,
  discountCode date,
  isAdmin mediumint,
  dashboardId float,
  expiryMonth time
);

CREATE TABLE organization_log (
  id serial primary key,
  endPoint bit,
  value enum,
  monthlyRate point,
  sku mediumint,
  expiryYear double,
  maxValue boolean,
  gateId smallint,
  groupName double,
  height binary,
  completedAt point,
  fileName geometry,
  role datetime,
  friendId bit,
  integrationId mediumint,
  adminNotes float,
  dataSource point,
  channelId mediumint,
  isVerified int,
  employeeCode varchar,
  keywords bit,
  score date,
  lastSeenAt smallint,
  fileSize serial,
  updatedAt timestamp,
  businessType blob,
  cloudId bit,
  postalCode mediumint,
  linkId real,
  department boolean,
  isHidden date,
  deliveryDate bit
);

CREATE TABLE vw_account_legacy (
  id serial primary key,
  albumId bit,
  dateFormat point,
  priority real,
  localeId serial,
  score text,
  checkOutTime bigint,
  downloadCount set,
  feedbackId boolean,
  content serial,
  clockOut set,
  moveId point,
  signature binary,
  maxLimit datetime,
  exchangeRate bit
);

CREATE TABLE tmp_payment (
  id serial primary key,
  sessionId geometry,
  cartId smallint,
  apiVersion timestamp,
  keywords blob,
  exchangeRate blob,
  isDraft timestamp,
  description tinyint,
  priority geometry,
  frameRate int,
  mobileNumber blob,
  maxValue real,
  score blob,
  moveId bigint,
  middleName tinyint,
  actionType enum,
  cancelReason enum,
  keyId point,
  isHidden int,
  completedAt smallint,
  chargeId timestamp,
  companyLogo point,
  groupName set,
  referralCode bit,
  deletedAt mediumint,
  merchantId bit,
  exportId bigint,
  isEnabled bit,
  taxRate blob,
  apiKey date
);

CREATE TABLE aggcompanymeta (
  id serial primary key,
  marketId time,
  houseNumber double,
  isFeatured real,
  meterNumber serial,
  awardDate bit,
  layerId text,
  lastName date,
  hostName smallint,
  documentId text,
  username real,
  metadata bigint,
  paymentMethod datetime,
  inactiveAt geometry,
  authMethod serial,
  brandId double,
  isPublic decimal,
  headerImage int
);

CREATE TABLE stgcustomer (
  id serial primary key,
  loadTime serial,
  shippingAddress varchar,
  itemCount timestamp,
  campaignId timestamp,
  deviceId bit,
  expiryYear smallint,
  listId smallint,
  orderStatus geometry,
  type decimal,
  layerId text,
  accountType decimal,
  rating varchar,
  cvv datetime,
  followCount text,
  cardHolder varchar,
  street serial,
  maxLimit datetime,
  accessLevel timestamp,
  marketId datetime,
  enabledAt mediumint,
  linkId boolean,
  contentType bigint,
  avatar smallint
);

CREATE TABLE payment (
  id serial primary key,
  levelId bigint,
  isVerified boolean,
  ipAddress decimal,
  attemptCount decimal,
  manufacturerId text,
  isBillable serial,
  appVersion float,
  score double,
  signature point,
  amount mediumint,
  cardNumber mediumint,
  abandonedCartId time,
  fontFamily point,
  creditLimit smallint,
  macAddress bigint,
  createdAt decimal,
  latitude point,
  fingerprint datetime,
  managerId real,
  fileName real,
  extractId blob,
  title mediumint,
  token serial,
  discountCode set,
  couponCode binary,
  contactPhone boolean,
  accountNumber point,
  feedbackId point
);

CREATE TABLE dimproduct (
  id serial primary key,
  invoiceId datetime,
  orderId datetime,
  instructorId boolean,
  buildNumber bigint,
  batchId mediumint,
  levelId boolean,
  password set,
  height int,
  maskType set,
  companyName blob,
  cartId int,
  description tinyint,
  lastLoginAt varchar,
  messageId blob,
  fileName real,
  bankAccount point,
  accessLevel real,
  creditCard geometry,
  unit mediumint,
  address date,
  articleId geometry,
  facilityId serial,
  customField1 serial,
  validUntil serial,
  certificateId real
);

CREATE TABLE tmppayment (
  id serial primary key,
  ipAddress tinyint,
  startDate enum,
  jobTitle binary,
  companyName date,
  category text,
  authorId time,
  handlerId timestamp,
  maxLimit bigint
);

CREATE TABLE audit_type_v1 (
  id serial primary key,
  isVerified time,
  maxLimit float,
  weight timestamp,
  albumId point,
  timezone datetime,
  title float,
  manufacturerId mediumint,
  comment varchar,
  education date,
  headerImage datetime,
  thumbnail point,
  accountType double,
  customerGroup mediumint,
  cloudId mediumint,
  coordinateY decimal,
  password time,
  createdAt bigint,
  avatar set
);

CREATE TABLE organization (
  id serial primary key,
  isVerified int,
  startDate point,
  maskType float,
  messageId int,
  maxLimit serial,
  articleId boolean,
  agentId text,
  accessLevel geometry,
  contactName boolean,
  longitude bigint,
  content bit,
  keyId int,
  comment bit,
  role boolean,
  checkInTime blob,
  category decimal,
  feedbackId point,
  businessType float,
  monthlyRate boolean,
  actionType time,
  albumId set,
  fileHash real,
  forwardTo varchar,
  isEnabled smallint,
  orderId set
);

CREATE TABLE order_notifications (
  id serial primary key,
  blogId serial,
  middleName serial,
  abandonedCartId set
);

CREATE TABLE syscompanynew (
  id serial primary key,
  street tinyint,
  forwardTo tinyint,
  houseNumber real,
  avatar boolean,
  faxNumber mediumint,
  errorCode decimal,
  audioUrl int,
  friendId boolean,
  creditLimit text,
  chargeId point,
  paymentMethod mediumint,
  alertType point,
  messageId int,
  customerGroup timestamp,
  amount time,
  attachmentUrl bigint,
  backupEmail double,
  frameRate blob,
  awardDate enum,
  taxRate serial,
  score point,
  metaDescription decimal,
  age timestamp,
  totalAmount varchar,
  latitude serial,
  version point,
  businessType text,
  checkInTime timestamp
);

CREATE TABLE rel_order_meta (
  id serial primary key,
  inactiveAt point,
  chatId bigint,
  cardNumber set,
  paymentMethod decimal,
  authorId timestamp,
  mainImage double,
  exchangeRate tinyint,
  duration boolean,
  isFeatured text,
  maskType double,
  isDeleted int,
  comment geometry,
  price serial,
  exportId serial,
  completionRate text,
  headerImage mediumint,
  weight enum,
  modifiedAt double,
  endPoint binary,
  maxLimit tinyint,
  coordinateY boolean,
  checkOutTime geometry,
  documentId decimal,
  customerId text
);

CREATE TABLE record (
  id serial primary key,
  industryType real,
  entityId time,
  eventDate boolean,
  hostName text,
  signature decimal,
  connectionString real,
  emailStatus varchar
);

CREATE TABLE company (
  id serial primary key,
  cloudId geometry,
  downloadCount binary,
  enrollmentDate real,
  authMethod tinyint,
  group timestamp,
  score decimal,
  updatedAt real,
  accountNumber blob,
  eventDate varchar,
  documentId serial,
  frameRate bit,
  bankAccount blob,
  dashboardId serial,
  levelId date,
  claimId enum,
  minValue enum,
  isLocked serial,
  address bit,
  minLimit smallint,
  gateId enum,
  maxLimit date,
  incidentId time
);

CREATE TABLE dst_record (
  id serial primary key,
  amount date,
  monthlyRate boolean,
  clockIn datetime,
  awardDate text,
  activeDevices bit,
  listingId point,
  cloudId int,
  code geometry,
  nickname serial,
  loginCount datetime,
  cardNumber timestamp,
  age real,
  frameRate geometry,
  creditLimit double,
  feedId geometry,
  companyName int,
  comment int,
  loadTime float,
  tags enum,
  jobTitle blob,
  countryCode smallint,
  errorMessage tinyint,
  cacheKey set,
  clientId tinyint,
  hiddenAt boolean,
  dimension int,
  depositAmount date,
  education binary,
  menuId set
);

CREATE TABLE olk_record (
  id serial primary key,
  group blob,
  cloudId tinyint,
  customerGroup datetime,
  discountCode mediumint,
  creditLimit enum,
  joinDate bit,
  localeId float,
  lastSeenAt point,
  metaKeywords tinyint,
  password mediumint,
  lastName double,
  appVersion smallint,
  priority double,
  industryType bit,
  courseId double,
  middleName datetime,
  cardHolder timestamp,
  address real,
  validUntil mediumint,
  earnedPoints double
);

CREATE TABLE ref_record (
  id serial primary key,
  integrationId bigint,
  displayOrder datetime,
  cancelReason set
);

CREATE TABLE product (
  id serial primary key,
  ipAddress bit,
  orderStatus text,
  email date,
  fontSize set,
  batchId decimal,
  middleName boolean,
  merchantId double
);

