CREATE TABLE sysproduct (
  id serial primary key,
  address decimal,
  category geometry,
  firmwareVersion smallint,
  errorCode text,
  editedAt datetime,
  password geometry
);

CREATE TABLE inventory (
  id serial primary key,
  filterType decimal,
  analyticsId mediumint,
  category text,
  insuranceId binary,
  endDate smallint,
  email float,
  token decimal,
  backupEmail geometry,
  labelText serial,
  group datetime
);

CREATE TABLE logauditdata (
  id serial primary key,
  meterNumber bit,
  companyLogo int,
  age blob,
  copyRight binary,
  incidentId boolean,
  token timestamp,
  cacheKey point,
  mimeType date,
  expiryDate blob,
  billingCycle tinyint,
  latitude point,
  cityName text,
  id real,
  cardNumber int,
  extractId time,
  height int,
  customerId date,
  fromDate real,
  driverLicense real,
  cancelReason datetime,
  weight bigint,
  dependentId varchar,
  value bit,
  enrollmentDate date,
  agentId smallint,
  homePhone time
);

CREATE TABLE tmppayment (
  id serial primary key,
  gender mediumint,
  insuranceId geometry,
  manufacturerId time,
  city double,
  backupEmail time,
  lockoutEnd binary
);

CREATE TABLE agg_company_status (
  id serial primary key,
  modifiedAt enum,
  dueDateAt tinyint,
  childId datetime,
  coverImage text,
  emailStatus enum,
  countryCode set,
  referralCode bit
);

CREATE TABLE customer_status_v2 (
  id serial primary key,
  customerGroup time,
  hiddenAt enum,
  certificateId serial,
  joinDate bit,
  groupName decimal,
  accountType binary,
  authToken float,
  loadTime text,
  comment varchar,
  age decimal,
  friendId blob,
  errorMessage text,
  likeCount tinyint,
  messageId binary
);

CREATE TABLE inventory_info (
  id serial primary key,
  id smallint,
  loginCount timestamp,
  bookingDate timestamp
);

CREATE TABLE inventory (
  id serial primary key,
  awardDate varchar,
  iconPath real,
  memberCount point,
  isBillable int,
  listId binary,
  geoLocation decimal,
  state int,
  fontSize decimal,
  mapId bigint,
  editedAt boolean,
  zipCode time,
  displayOrder smallint,
  isDraft geometry,
  isRequired bit,
  url geometry,
  keyId text,
  distributorId binary,
  analyticsId tinyint,
  duration binary,
  companyLogo int,
  metaTitle real,
  instanceId set,
  hourlyRate float,
  comment text,
  latitude timestamp,
  headerImage bigint,
  blogId float,
  gameId serial
);

CREATE TABLE order (
  id serial primary key,
  licenseKey mediumint,
  address text,
  folderPath timestamp,
  cardNumber mediumint,
  bookingDate binary,
  isPublic enum,
  salary mediumint,
  moduleId decimal,
  documentId text,
  unit serial,
  height serial,
  bannerImage blob,
  fromDate serial,
  firmwareVersion binary,
  localeId varchar,
  editedAt bit,
  status tinyint,
  avatar int,
  clockIn text,
  priority smallint,
  joinDate smallint,
  category real,
  employeeId mediumint
);

CREATE TABLE companymeta (
  id serial primary key,
  merchantId decimal,
  comment boolean,
  budgetCode float,
  documentId int,
  expiryYear datetime,
  maskType serial,
  listingId int,
  accountNumber blob,
  algorithm point,
  paymentMethod bit,
  insuranceId blob,
  linkId smallint,
  feedbackId varchar,
  cardHolder blob,
  enabledAt date,
  isFeatured varchar,
  invoiceId text,
  totalAmount real,
  analyticsId point,
  employeeId decimal,
  creditLimit real,
  completionRate date
);

CREATE TABLE ext_order_hist (
  id serial primary key,
  browserType point,
  firmwareVersion enum,
  attemptCount time,
  balance float,
  awardDate bigint,
  contactEmail varchar,
  cardHolder bigint
);

CREATE TABLE pub_account (
  id serial primary key,
  sku date,
  listingId serial,
  fileType float,
  businessType smallint,
  errorMessage timestamp,
  lastName text,
  address point,
  domainName timestamp,
  bankAccount decimal,
  locationId datetime,
  customField2 smallint,
  itemCount bit,
  lastSeenAt enum,
  faxNumber point,
  browserType varchar,
  groupName blob,
  longitude tinyint,
  cloudId date,
  updatedAt serial,
  authToken date,
  algorithm float,
  version blob,
  dashboardId enum
);

CREATE TABLE inventory (
  id serial primary key,
  currencyCode enum,
  productCode serial,
  state blob,
  phone decimal,
  expiryMonth float,
  avatar boolean,
  validUntil time,
  isFeatured smallint,
  minLimit bit,
  updatedAt real,
  accountStatus serial,
  creditCard blob,
  content point,
  incidentId enum,
  certificateId decimal,
  endPoint blob,
  deviceToken point,
  birthDate serial,
  deviceType binary
);

CREATE TABLE cpyconfig (
  id serial primary key,
  version int,
  enrollmentDate time,
  ipAddress text,
  sessionId blob,
  salary serial,
  customerGroup binary,
  loginAttempts mediumint,
  isAdmin set,
  lastName set,
  importId varchar,
  category double,
  isBillable set
);

CREATE TABLE factusertype2025 (
  id serial primary key,
  customField2 binary,
  dimension geometry,
  foregroundColor time,
  keyId real,
  geoLocation blob,
  id decimal,
  errorCode smallint,
  listId set,
  ipAddress float,
  fontFamily boolean,
  connectionString bit,
  deviceType mediumint,
  exchangeRate date,
  token datetime,
  globalId real,
  algorithm float,
  timezone real,
  messageId double,
  amount text,
  title boolean,
  fontSize real,
  accountStatus int
);

CREATE TABLE audit (
  id serial primary key,
  cityName bigint,
  category set,
  url serial,
  score bit,
  integrationId tinyint,
  token varchar,
  currencyCode decimal,
  flagged binary,
  age binary,
  billingCycle timestamp,
  discount geometry,
  iconPath mediumint,
  feedbackId text,
  name binary,
  connectionString boolean,
  cancelReason real,
  actionType serial,
  enabledAt datetime,
  dealerId bit,
  merchantId varchar,
  logLevel smallint,
  exportId date,
  metaTitle set,
  machineId set,
  expiryMonth geometry,
  sessionId datetime,
  domainName smallint,
  completedAt serial,
  attachmentUrl blob
);

CREATE TABLE vw_customer (
  id serial primary key,
  apiVersion date,
  coordinateX int,
  customField2 varchar,
  domainName datetime
);

CREATE TABLE olk_company (
  id serial primary key,
  channelId float,
  title bit,
  manufacturerId geometry,
  cacheKey bit,
  maritalStatus bit,
  comment bit,
  listId geometry,
  foregroundColor varchar,
  moveId time,
  thumbnail set,
  mimeType mediumint,
  exportId geometry,
  facilityId float,
  licenseKey tinyint,
  height bigint,
  deviceType text,
  referralCode text,
  maxValue date,
  bankAccount geometry,
  driverLicense binary,
  isDefault float,
  alertType bit,
  localeId boolean,
  dialCode binary,
  fromDate time,
  name serial,
  cancelReason double
);

CREATE TABLE stg_transaction_v1 (
  id serial primary key,
  mimeType time,
  phone float,
  defaultLang mediumint,
  frameRate real,
  password date,
  hostName enum,
  cityName real,
  maxValue date,
  locationId real,
  attemptCount datetime,
  category float,
  listingId bigint,
  dialCode point,
  endPoint timestamp,
  flagged bigint,
  analyticsId binary,
  enabledAt point,
  content geometry,
  keywords real,
  inactiveAt real,
  creditLimit text,
  moduleId set,
  fromDate point,
  listId text,
  isDefault double,
  channelId bigint,
  referralCode blob
);

CREATE TABLE audit_div (
  id serial primary key,
  address datetime,
  messageId tinyint,
  costCenter varchar,
  completedAt decimal,
  machineId set,
  status mediumint,
  feedId timestamp,
  entryPoint boolean,
  salary smallint,
  maxValue float,
  grade float,
  description boolean,
  productCode int,
  taxRate smallint,
  score time,
  employeeId tinyint,
  authToken text,
  sku tinyint,
  campaignId serial,
  accountStatus binary,
  importId geometry
);

CREATE TABLE sys_record_rel (
  id serial primary key,
  dependentId varchar,
  flagged time,
  dueDateAt double,
  customField2 point,
  fileSize bit,
  maritalStatus binary,
  folderPath real,
  role boolean,
  street varchar,
  forwardTo boolean,
  driverLicense decimal,
  clockOut blob,
  ipAddress geometry,
  apiVersion smallint,
  handlerId double,
  formatType point,
  cardNumber smallint,
  accessLevel time,
  moduleId double,
  budgetCode date,
  content boolean,
  companyName real,
  expiryMonth point,
  browserType float
);

CREATE TABLE cpy_account (
  id serial primary key,
  height binary,
  gameId mediumint,
  updatedAt float,
  postalCode real,
  hiddenAt serial,
  articleId binary,
  nickname int,
  avatar mediumint,
  certificateId set,
  albumId real,
  mapId time,
  group double,
  isBillable timestamp,
  title mediumint,
  employeeCode real,
  forwardTo boolean,
  dealerId text,
  contractId smallint
);

CREATE TABLE olk_order_info (
  id serial primary key,
  thumbnail serial,
  forwardTo double,
  instructorId varchar,
  category enum,
  colorCode enum,
  deliveryDate text,
  mapId real,
  menuId bit,
  domainName point,
  group tinyint,
  expiryYear timestamp,
  facilityId varchar,
  eventDate timestamp,
  updatedAt smallint,
  timezone decimal,
  metaKeywords geometry,
  isLocked boolean,
  deactivatedAt double,
  title boolean,
  firmwareVersion mediumint,
  feedbackId varchar,
  dateFormat timestamp,
  completionRate tinyint,
  entryPoint tinyint,
  lastSeenAt boolean
);

CREATE TABLE vwcompanystatus (
  id serial primary key,
  firstName geometry,
  cartId date,
  childId timestamp,
  isActive geometry,
  longitude tinyint,
  incidentId varchar,
  budgetCode double,
  browserType time,
  group mediumint,
  logLevel int,
  indexKey text,
  displayOrder bit,
  lockoutEnd varchar
);

CREATE TABLE pubusernew (
  id serial primary key,
  grade serial,
  batchId boolean,
  moveId float,
  checkInTime boolean,
  avatar boolean,
  browserType smallint,
  completedAt datetime,
  isDefault varchar,
  comment geometry,
  adminNotes mediumint,
  gameId bit,
  dependentId float,
  salary geometry,
  updatedAt geometry,
  childId tinyint,
  maxLimit serial,
  sku point,
  attemptCount float,
  listId varchar,
  linkId timestamp,
  companyLogo int,
  handlerId int,
  loginCount decimal,
  cloudId bigint,
  earnedPoints serial,
  integrationId point,
  inactiveAt int
);

CREATE TABLE agg_config_rel (
  id serial primary key,
  frameRate real,
  meterNumber enum,
  apiVersion boolean,
  cardHolder text,
  defaultLang real,
  bookingDate time,
  unit text,
  certificateId boolean,
  filterType tinyint,
  balance enum,
  jobTitle geometry,
  rating point,
  moveId datetime,
  firstName float,
  countryCode decimal,
  audioUrl smallint,
  deliveryDate time,
  actionType enum,
  cacheKey serial,
  copyRight serial,
  updatedAt datetime,
  contactPhone boolean
);

CREATE TABLE tmp_config_v2 (
  id serial primary key,
  mobileNumber smallint,
  currency date
);

CREATE TABLE factorganization (
  id serial primary key,
  contractId binary,
  layerId timestamp,
  priority text,
  comment blob,
  cardNumber geometry
);

CREATE TABLE olk_inventory_log_v2 (
  id serial primary key,
  likeCount geometry,
  weight real,
  isDraft datetime,
  companyId tinyint,
  downloadCount double,
  costCenter datetime,
  activeDevices datetime,
  role serial,
  metadata text,
  dealerId point,
  machineId smallint,
  signature serial,
  awardDate enum,
  listingId set,
  status timestamp,
  dailyLimit geometry,
  updatedAt int,
  forwardTo double,
  cardNumber enum,
  certificateId enum,
  isAdmin varchar,
  fontFamily enum,
  fromDate bigint,
  countryCode blob
);

CREATE TABLE tmpaccount (
  id serial primary key,
  isActive datetime,
  orderStatus real,
  favoriteCount real,
  incidentId set,
  dealerId serial,
  minLimit enum,
  updatedAt blob,
  referralCode float,
  maritalStatus timestamp,
  endDate smallint,
  price timestamp,
  indexKey date,
  instructorId mediumint,
  fingerprint bit,
  cardHolder blob,
  levelId tinyint,
  shippingAddress bigint,
  latitude datetime,
  email binary,
  contactPhone datetime,
  lockoutEnd float,
  deviceId int,
  backupEmail binary,
  title float,
  dashboardId bit,
  awardDate decimal,
  completedAt float,
  dependentId boolean,
  nickname text
);

CREATE TABLE organization_temp (
  id serial primary key,
  checkInTime real,
  weight text,
  fontFamily point,
  labelText datetime,
  firstName boolean,
  ipAddress tinyint,
  formatType enum,
  monthlyRate time,
  bookingDate set,
  dimension smallint
);

CREATE TABLE stg_account (
  id serial primary key,
  email enum,
  bannerImage geometry,
  dialCode datetime
);

CREATE TABLE customer (
  id serial primary key,
  authorId serial,
  brandId varchar,
  defaultLang geometry,
  status int,
  currency int,
  enrollmentDate serial,
  birthDate decimal,
  feedId decimal,
  coordinateX binary
);

CREATE TABLE order (
  id serial primary key,
  marketId bit,
  defaultLang enum,
  dueDateAt bit,
  updatedAt tinyint,
  formatType bigint,
  content enum,
  flagged date,
  priority datetime,
  bookingDate boolean,
  name decimal
);

CREATE TABLE ver_audit_log_2025 (
  id serial primary key,
  followCount point,
  priority smallint,
  unit int,
  budgetCode float,
  emergencyContact smallint,
  alertType int,
  mobileNumber bit,
  street binary,
  fileHash decimal,
  insertedAt boolean
);

CREATE TABLE ref_transaction_meta (
  id serial primary key,
  age decimal,
  amount smallint,
  joinDate serial,
  clockIn blob,
  emailStatus real,
  bannerImage timestamp,
  albumId geometry,
  addressLine2 real,
  cancelReason datetime,
  category serial,
  filterType float,
  expiryDate datetime,
  orderId geometry,
  isSystem serial,
  errorCode set,
  nickname varchar,
  id float,
  dailyLimit bigint,
  iconPath serial,
  guestId date,
  isVerified boolean,
  authorId boolean,
  mapId bigint,
  timezone binary,
  hashKey point,
  quantity enum
);

CREATE TABLE inventory_data_2024 (
  id serial primary key,
  createdAt geometry,
  errorMessage int,
  isLocked int,
  billingCycle int,
  fontFamily bigint,
  feedbackId mediumint,
  grade binary,
  floorNumber varchar
);

CREATE TABLE core_customer_notifications_legacy (
  id serial primary key,
  balance set,
  cloudId enum,
  duration double,
  coordinateY enum,
  accessLevel blob,
  coordinateX double,
  amount set,
  quantity timestamp,
  metaDescription boolean,
  priority text,
  dimension datetime,
  integrationId tinyint,
  dashboardId double,
  nickname set,
  education tinyint,
  chargeId smallint,
  cvv decimal,
  expiryYear int,
  type date,
  clientId datetime,
  emailStatus boolean,
  metaTitle varchar,
  birthDate geometry,
  connectionString bit,
  avatar decimal,
  dailyLimit int,
  isBillable smallint,
  ipAddress tinyint
);

CREATE TABLE inventory (
  id serial primary key,
  avatar enum,
  isVerified boolean,
  currencyCode int,
  authToken point,
  driverLicense tinyint,
  group date,
  actionType real,
  flagged blob,
  budgetCode decimal,
  chargeId real,
  token text,
  ipAddress tinyint,
  cardHolder binary,
  jobTitle float,
  insuranceId timestamp,
  entryPoint double,
  keyId int,
  dailyLimit int,
  hashKey bigint,
  likeCount decimal,
  joinDate float,
  value bit,
  billingFrequency binary,
  expiryMonth int,
  marketId real,
  indexKey real,
  cartId datetime,
  domainName varchar,
  rating text
);

CREATE TABLE vw_company (
  id serial primary key,
  completionRate mediumint,
  domainName boolean,
  id point,
  longitude time,
  costCenter varchar,
  likeCount int,
  grade geometry
);

CREATE TABLE vw_user (
  id serial primary key,
  thumbnail serial,
  shippingAddress point,
  invoiceId varchar,
  headerImage set,
  fingerprint boolean,
  importId text,
  integrationId time,
  completedAt date,
  education real,
  bankAccount blob,
  layerId bigint,
  jobTitle serial,
  depositAmount mediumint,
  firstName datetime,
  firmwareVersion bigint,
  customField1 text,
  fileName timestamp,
  comment decimal,
  timezone varchar,
  batchId datetime,
  companyName time,
  creditScore tinyint,
  editedAt geometry,
  tags date,
  loadTime blob,
  dateFormat blob
);

CREATE TABLE organization (
  id serial primary key,
  clientId serial,
  agentId geometry,
  metaDescription smallint,
  avatar mediumint,
  startDate bigint,
  cardHolder point,
  deactivatedAt mediumint,
  albumId smallint,
  filterType set,
  dependentId blob,
  isDraft geometry,
  comment point,
  password blob,
  deviceId boolean,
  driverLicense point,
  employeeId smallint,
  mimeType smallint,
  accessLevel geometry,
  unit bit,
  education set,
  thumbnail float,
  folderPath varchar,
  ipAddress time,
  rating varchar,
  sessionId geometry,
  creditLimit mediumint
);

CREATE TABLE tbl_product (
  id serial primary key,
  memberCount tinyint,
  linkId mediumint,
  birthDate binary,
  billingCycle float,
  instructorId point,
  couponCode tinyint,
  itemCount mediumint,
  claimId float,
  errorCode geometry,
  emergencyContact timestamp,
  authorId mediumint,
  id enum,
  fromDate varchar,
  appVersion tinyint,
  modifiedAt serial,
  handlerId binary,
  signature binary,
  campaignId serial,
  loadTime float,
  password varchar,
  nickname date,
  batchId set,
  agentId binary,
  hashKey int,
  audioUrl set,
  status geometry,
  phone smallint,
  machineId int,
  description point,
  creditScore float
);

CREATE TABLE stg_customer_archive (
  id serial primary key,
  balance real,
  geoLocation bigint,
  discount timestamp,
  locationId binary,
  password tinyint,
  description text,
  country set,
  handlerId point,
  mainImage smallint,
  address bigint,
  deviceId blob,
  entryPoint boolean,
  moduleId serial,
  manufacturerId tinyint,
  connectionString text,
  isDefault int,
  isVerified bit,
  maskType date,
  uuid set,
  orderId bigint,
  latitude datetime
);

CREATE TABLE app_audit (
  id serial primary key,
  houseNumber int,
  email int,
  employeeCode real,
  keyId double,
  score text,
  mimeType boolean,
  departmentCode datetime,
  maxValue point,
  address bit,
  creditCard bigint,
  alertType tinyint,
  cardHolder real,
  category datetime,
  browserType boolean,
  completionRate real,
  price bigint,
  city bigint,
  frameRate bit,
  isLocked date,
  discountCode bigint
);

CREATE TABLE customer (
  id serial primary key,
  instanceId real,
  dialCode int,
  localeId serial,
  abandonedCartId tinyint,
  thumbnail real,
  lastSeenAt boolean,
  paymentMethod binary,
  coordinateX time,
  discountCode text
);

CREATE TABLE privauditv1 (
  id serial primary key,
  lastSeenAt tinyint,
  actionType binary,
  clientId decimal,
  cityName mediumint,
  flagged point,
  amount binary,
  layerId mediumint,
  likeCount geometry,
  isEnabled geometry,
  moveId point,
  handlerId timestamp,
  claimId geometry,
  lastName decimal,
  agentId date,
  levelId set,
  latitude mediumint,
  nickname set,
  macAddress datetime,
  displayOrder enum,
  inactiveAt decimal,
  joinDate int
);

CREATE TABLE tbl_audit (
  id serial primary key,
  batchId text,
  contactPhone real,
  headerImage serial,
  locationId float,
  eventDate bigint,
  awardDate serial,
  apiKey double,
  firstName date,
  country binary,
  deviceId datetime,
  mimeType text,
  age datetime,
  discount blob,
  friendId blob,
  completedAt smallint,
  username set,
  itemCount blob,
  importId decimal,
  avatar point,
  size serial
);

CREATE TABLE order_info (
  id serial primary key,
  comment date,
  geoLocation mediumint,
  abandonedCartId set,
  brandId text,
  feedId point,
  fontFamily boolean,
  updatedAt real,
  contractId time,
  hashKey varchar,
  username mediumint,
  dealerId int,
  paymentMethod text,
  fontSize geometry,
  apiVersion real,
  weight float,
  department set,
  quantity timestamp,
  dependentId serial,
  type varchar,
  deviceId bigint,
  companyName int,
  startDate set
);

CREATE TABLE product_map (
  id serial primary key,
  backupEmail point,
  completionRate serial,
  mobileNumber smallint,
  avatar varchar,
  completedAt point,
  creditCard tinyint,
  url blob,
  bannerImage geometry,
  inactiveAt mediumint,
  isBillable point,
  businessType smallint,
  fontSize serial,
  keyId timestamp,
  languageCode smallint,
  expiryYear enum,
  title geometry,
  latitude blob,
  campaignId date,
  alertType binary,
  industryType varchar,
  size serial,
  audioUrl time,
  height smallint,
  checkInTime blob
);

