CREATE TABLE product_v2 (
  id serial primary key,
  courseId date,
  headerImage float,
  logLevel smallint,
  appVersion bigint
);

CREATE TABLE paymentv1 (
  id serial primary key,
  version serial,
  budgetCode bigint
);

CREATE TABLE user (
  id serial primary key,
  shippingAddress decimal,
  labelText binary,
  hostName date,
  authorId binary,
  inactiveAt real,
  amount point,
  employeeCode datetime,
  deactivatedAt varchar,
  department enum,
  sessionId double,
  accountType float,
  countryCode varchar,
  errorMessage date,
  firmwareVersion blob,
  height double,
  username set,
  isLocked blob,
  defaultValue text,
  isEnabled smallint,
  marketId real
);

CREATE TABLE customer_new (
  id serial primary key,
  indexKey geometry,
  email serial,
  shippingAddress datetime,
  isEnabled geometry,
  enrollmentDate bit,
  totalAmount geometry,
  friendId int,
  hiddenAt serial,
  avatar smallint
);

CREATE TABLE transaction (
  id serial primary key,
  deletedAt time,
  isVerified time,
  fontSize real,
  authorId datetime,
  floorNumber varchar,
  driverLicense text,
  cancelReason text,
  password bigint,
  claimId serial,
  chatId geometry,
  gameId point,
  balance varchar,
  isEnabled bigint,
  checkInTime real,
  cacheKey tinyint,
  metaKeywords blob,
  emailStatus time,
  metaDescription smallint,
  maskType double,
  email varchar,
  houseNumber geometry,
  contactPhone set,
  layerId set
);

CREATE TABLE config_map (
  id serial primary key,
  maskType smallint,
  appVersion bigint,
  maxLimit blob,
  role datetime,
  creditLimit decimal,
  isFeatured decimal,
  accountType timestamp,
  weight decimal,
  contentType smallint
);

CREATE TABLE customer (
  id serial primary key,
  minValue bit,
  instanceId text,
  fingerprint bigint,
  productCode mediumint,
  analyticsId double,
  articleId bigint,
  latitude set,
  countryCode datetime,
  adminNotes varchar,
  displayOrder bigint,
  isActive double,
  homePhone double,
  mainImage double,
  referralCode enum,
  name double,
  deviceType mediumint,
  birthDate point,
  education date,
  avatar binary,
  isDeleted serial,
  minLimit enum,
  integrationId double,
  id bit,
  signature date,
  ipAddress enum,
  exchangeRate blob,
  createdAt real,
  dialCode blob,
  enrollmentDate binary,
  dueDateAt timestamp,
  campaignId double
);

CREATE TABLE src_audit_meta (
  id serial primary key,
  loginCount set,
  emergencyContact blob,
  address set,
  instructorId decimal,
  completionRate blob,
  quantity real,
  groupName bigint,
  fileHash mediumint,
  meterNumber double,
  middleName bigint,
  loginAttempts enum,
  isEnabled double,
  completedAt set,
  favoriteCount serial,
  sku boolean,
  messageId int,
  flagged real,
  hostName point,
  updatedAt decimal,
  importId serial,
  isLocked decimal,
  deviceToken date,
  machineId blob
);

CREATE TABLE company (
  id serial primary key,
  version smallint,
  apiKey bit,
  description blob,
  balance double,
  distributorId binary,
  albumId real,
  loginCount tinyint,
  group date,
  departmentCode boolean,
  entityId geometry,
  startDate date,
  deviceId tinyint,
  companyLogo tinyint,
  sku blob
);

CREATE TABLE ref_audit_notifications_2024 (
  id serial primary key,
  isBillable boolean,
  code boolean,
  accessLevel float,
  zipCode boolean,
  grade bigint,
  awardDate timestamp,
  isDeleted mediumint,
  driverLicense date,
  gateId datetime,
  hashKey tinyint,
  algorithm serial,
  emailStatus serial,
  houseNumber datetime
);

CREATE TABLE order (
  id serial primary key,
  distributorId float,
  orderId text,
  comment real,
  token timestamp,
  username mediumint,
  cacheKey double,
  updatedAt bigint,
  loginAttempts point,
  title real,
  latitude tinyint,
  currencyCode tinyint,
  meterNumber date,
  eventDate decimal
);

CREATE TABLE log_order (
  id serial primary key,
  price time,
  balance double,
  joinDate real,
  address datetime,
  bookingDate bigint,
  loginAttempts set,
  cardNumber datetime,
  firstName serial,
  foregroundColor set,
  username tinyint,
  version date,
  lastName mediumint,
  employeeCode decimal,
  activeDevices float,
  moveId bit,
  middleName real,
  creditScore serial,
  depositAmount varchar,
  minLimit real
);

CREATE TABLE product_2025 (
  id serial primary key,
  height real,
  frameRate blob,
  courseId int,
  customField1 varchar,
  endPoint date,
  articleId tinyint,
  monthlyRate double,
  abandonedCartId time,
  coordinateX mediumint
);

CREATE TABLE stgcustomerv1 (
  id serial primary key,
  instanceId enum,
  title varchar,
  geoLocation geometry,
  coordinateY real,
  employeeCode time,
  password bit,
  longitude varchar
);

CREATE TABLE order_meta (
  id serial primary key,
  billingFrequency set,
  cityName date,
  quantity double,
  accountType tinyint,
  coverImage date,
  lastSeenAt time,
  folderPath real,
  firstName datetime,
  age tinyint,
  group int,
  orderId blob,
  marketId geometry,
  minLimit point,
  accountStatus timestamp,
  weight int,
  addressLine2 text,
  clockOut point,
  contentType enum,
  attemptCount serial,
  homePhone decimal,
  phone geometry,
  businessType binary,
  campaignId mediumint,
  salary varchar,
  fingerprint text,
  friendId real,
  authorId real,
  billingCycle boolean
);

CREATE TABLE organization (
  id serial primary key,
  errorMessage blob,
  frameRate geometry,
  dialCode binary,
  employeeId mediumint,
  isRequired bit,
  homePhone time,
  backupEmail int,
  logLevel bigint,
  domainName bit,
  billingFrequency geometry,
  itemCount text
);

CREATE TABLE dst_record_v2 (
  id serial primary key,
  creditCard mediumint,
  followCount decimal,
  fingerprint time,
  weight binary,
  authorId tinyint,
  localeId tinyint,
  fromDate bit,
  status point,
  isFeatured float,
  category date,
  couponCode boolean,
  address decimal
);

CREATE TABLE agg_config_rel_2024 (
  id serial primary key,
  claimId text,
  shippingAddress binary,
  rating blob,
  isDraft date,
  flagged boolean,
  isLocked mediumint,
  macAddress mediumint,
  gateId blob,
  fileSize varchar,
  title timestamp,
  extractId int,
  duration real,
  mimeType bit,
  layerId binary,
  dailyLimit double,
  listId date,
  licenseKey int,
  metaKeywords varchar,
  latitude mediumint
);

CREATE TABLE dimcustomer (
  id serial primary key,
  countryCode bigint,
  agentId serial,
  address timestamp,
  cvv set,
  folderPath int,
  productCode datetime,
  alertType bit,
  geoLocation real,
  actionType varchar,
  budgetCode set,
  isSystem binary,
  companyLogo geometry,
  password float,
  updatedAt date,
  companyId set,
  followCount geometry,
  category int,
  validUntil datetime,
  industryType real,
  enabledAt bit,
  cloudId set,
  longitude bit,
  appVersion mediumint
);

CREATE TABLE audit_extra (
  id serial primary key,
  connectionString set,
  completionRate date,
  exportId set,
  machineId decimal,
  moduleId mediumint,
  ipAddress tinyint,
  isPublic double,
  gender point,
  homePhone float,
  totalAmount serial,
  sku text,
  quantity bit
);

CREATE TABLE vw_company (
  id serial primary key,
  likeCount double,
  channelId int,
  accountNumber float,
  deviceToken time,
  code smallint,
  currencyCode enum,
  isRequired enum,
  addressLine2 float,
  certificateId timestamp,
  budgetCode double,
  clientId text,
  isBillable smallint,
  sku smallint,
  longitude double,
  hostName time,
  companyName double,
  accountType text,
  copyRight blob,
  errorCode binary,
  duration serial
);

CREATE TABLE sysaudit (
  id serial primary key,
  cardNumber mediumint,
  agentId blob,
  companyName datetime,
  priority serial,
  creditScore blob,
  enabledAt tinyint,
  grade serial,
  accountType smallint,
  discountCode bigint,
  loginCount boolean,
  dealerId decimal,
  amount bit,
  alertType enum,
  messageId serial,
  fingerprint real,
  memberCount boolean,
  importId tinyint,
  orderId time,
  appVersion float,
  postalCode mediumint,
  uuid binary,
  merchantId smallint,
  address double,
  companyId binary,
  isSystem point,
  awardDate text,
  manufacturerId timestamp,
  actionType boolean,
  maxValue datetime
);

CREATE TABLE customer (
  id serial primary key,
  emailStatus blob,
  layerId bit,
  mimeType timestamp,
  audioUrl int,
  companyLogo boolean,
  chargeId bit,
  feedId time,
  articleId mediumint,
  score varchar,
  marketId date,
  connectionString blob,
  code smallint,
  companyName mediumint,
  creditScore time,
  signature varchar,
  dateFormat blob,
  customField1 tinyint,
  clockOut text,
  createdAt smallint,
  eventDate double,
  lastSeenAt point,
  avatar varchar,
  menuId geometry,
  email blob
);

CREATE TABLE account (
  id serial primary key,
  name point,
  isEnabled binary,
  metadata serial,
  expiryYear set,
  mapId tinyint,
  completedAt bigint,
  facilityId smallint,
  labelText bit,
  status time,
  category double,
  eventDate enum,
  cvv serial,
  fileSize set,
  defaultLang text,
  fileHash bigint,
  abandonedCartId bigint,
  mobileNumber boolean,
  creditLimit decimal,
  lastSeenAt boolean,
  filterType smallint,
  domainName smallint,
  maxValue decimal,
  houseNumber binary,
  homePhone decimal,
  indexKey mediumint,
  address time
);

CREATE TABLE organizationsegv2 (
  id serial primary key,
  createdAt date,
  importId set,
  cardHolder time,
  education date,
  layerId tinyint,
  title bigint,
  albumId float,
  iconPath time,
  startDate tinyint,
  cvv tinyint,
  facilityId datetime,
  downloadCount boolean,
  isVerified int,
  marketId binary,
  itemCount varchar,
  address text,
  password mediumint,
  activeDevices float,
  entryPoint tinyint,
  cancelReason date,
  appVersion smallint,
  isAdmin varchar,
  completedAt bigint,
  gateId blob,
  uuid real,
  locationId decimal,
  balance enum,
  deviceId enum
);

CREATE TABLE inventory (
  id serial primary key,
  mimeType varchar,
  uuid set,
  status decimal,
  thumbnail double,
  campaignId bit,
  accessLevel float,
  id float,
  coordinateX enum,
  checkOutTime text,
  createdAt serial,
  fileHash point,
  contractId double,
  size time,
  contactName tinyint,
  referralCode double,
  integrationId bit,
  state serial
);

CREATE TABLE src_transaction (
  id serial primary key,
  state point,
  dateFormat time,
  deviceId set,
  driverLicense date,
  exportId blob,
  contractId time,
  email float,
  completedAt varchar,
  linkId double,
  mobileNumber mediumint,
  audioUrl datetime,
  mimeType binary,
  salary tinyint,
  homePhone boolean,
  description varchar,
  browserType time,
  budgetCode mediumint,
  extractId tinyint,
  group enum,
  priority text,
  licenseKey geometry,
  category boolean,
  fontFamily bigint,
  cardNumber boolean,
  height date,
  nickname varchar,
  feedbackId blob,
  metaTitle float,
  minValue timestamp,
  content timestamp
);

CREATE TABLE user_new (
  id serial primary key,
  fontSize point,
  minValue decimal,
  lastSeenAt decimal,
  companyLogo datetime,
  localeId decimal,
  birthDate point,
  frameRate bigint,
  listingId tinyint,
  isFeatured geometry,
  loginCount float,
  machineId varchar,
  priority varchar,
  browserType serial,
  companyId float,
  createdAt tinyint,
  phone boolean,
  dashboardId tinyint,
  gateId mediumint,
  gameId set,
  dateFormat serial,
  loginAttempts geometry
);

CREATE TABLE customer (
  id serial primary key,
  category float,
  accountNumber bigint,
  education bigint,
  exchangeRate set,
  isPublic double,
  quantity blob,
  displayOrder time,
  manufacturerId enum,
  authorId smallint,
  mainImage time,
  errorCode real,
  alertType double,
  downloadCount mediumint,
  metaKeywords geometry,
  loadTime time,
  dimension bigint,
  errorMessage point,
  phone text,
  description tinyint,
  name int,
  rating real,
  clockIn point
);

CREATE TABLE stg_customer (
  id serial primary key,
  claimId geometry,
  articleId boolean,
  courseId time,
  authorId real,
  duration smallint,
  signature binary,
  alertType binary,
  loginCount enum,
  longitude text
);

CREATE TABLE extcustomermap (
  id serial primary key,
  authorId set,
  addressLine2 point,
  countryCode real,
  fontFamily datetime,
  group real,
  courseId int,
  rating decimal,
  exchangeRate timestamp,
  deviceId blob,
  comment int,
  metaKeywords real,
  expiryMonth geometry,
  updatedAt real,
  entryPoint text,
  audioUrl real,
  lastLoginAt smallint,
  browserType geometry,
  zipCode real,
  ipAddress boolean,
  token point,
  totalAmount set,
  apiKey smallint,
  batchId time,
  salary smallint
);

CREATE TABLE tblconfig (
  id serial primary key,
  facilityId serial,
  filterType geometry,
  budgetCode geometry,
  expiryMonth smallint,
  id varchar,
  clockIn smallint,
  priority int,
  shippingAddress serial,
  houseNumber varchar,
  description bit,
  businessType timestamp,
  isDraft text,
  password bit,
  createdAt float,
  blogId serial,
  layerId text,
  invoiceId blob,
  customField1 time,
  displayName double,
  deviceId serial,
  dateFormat bit
);

CREATE TABLE order_extra (
  id serial primary key,
  flagged tinyint,
  employeeId blob,
  bankAccount datetime,
  machineId date,
  headerImage point,
  taxRate set,
  version mediumint,
  type datetime,
  entryPoint boolean,
  state bit,
  cacheKey date,
  isDraft varchar,
  channelId geometry,
  isBillable boolean,
  height varchar,
  menuId serial,
  description boolean,
  dataSource serial,
  departmentCode enum,
  bookingDate int,
  importId point,
  referralCode text,
  houseNumber decimal,
  activeDevices time,
  fileHash smallint,
  companyLogo bigint,
  dependentId bigint,
  companyName timestamp,
  articleId date,
  moveId serial
);

CREATE TABLE srcorganizationv1 (
  id serial primary key,
  currencyCode boolean,
  value smallint,
  abandonedCartId time,
  currency serial,
  latitude set,
  weight timestamp,
  budgetCode double,
  awardDate tinyint
);

CREATE TABLE config (
  id serial primary key,
  blogId bit,
  discount set,
  uuid double,
  dependentId bigint,
  fingerprint datetime,
  apiVersion set,
  folderPath float,
  expiryDate float,
  machineId set
);

CREATE TABLE account (
  id serial primary key,
  errorCode float,
  deviceType boolean,
  colorCode double
);

CREATE TABLE config (
  id serial primary key,
  hostName blob,
  employmentDate smallint,
  metadata int,
  completionRate point,
  chatId float,
  rating point,
  articleId decimal,
  homePhone boolean,
  cancelReason real,
  isVerified blob,
  endPoint date,
  isDraft bit,
  paymentMethod smallint,
  balance real,
  username tinyint,
  groupName datetime,
  url smallint,
  fileType date,
  fileName bigint,
  name text,
  mimeType smallint,
  age mediumint,
  gameId tinyint,
  keywords blob,
  accessLevel decimal,
  awardDate boolean,
  industryType tinyint,
  description time
);

CREATE TABLE record_v1 (
  id serial primary key,
  longitude real,
  monthlyRate double,
  campaignId enum,
  groupName timestamp,
  companyId date,
  category bigint,
  validUntil datetime,
  instructorId mediumint,
  comment boolean,
  loginAttempts time,
  lastLoginAt date,
  claimId boolean,
  importId float,
  distributorId tinyint,
  dealerId double,
  latitude double,
  isArchived point,
  bookingDate smallint,
  homePhone varchar,
  priority geometry,
  firmwareVersion set,
  createdAt serial,
  headerImage smallint,
  expiryDate date,
  title enum,
  businessType enum,
  deliveryDate bigint,
  displayOrder set
);

CREATE TABLE inventory (
  id serial primary key,
  addressLine2 time,
  actionType time,
  dialCode decimal,
  appVersion real,
  chargeId bigint,
  minLimit smallint,
  maskType point,
  indexKey tinyint,
  domainName float,
  employeeCode serial,
  eventDate time,
  deliveryDate geometry,
  groupName real,
  accessLevel bit,
  isArchived date,
  cancelReason binary,
  balance geometry
);

CREATE TABLE audit_archive (
  id serial primary key,
  customField1 set,
  loginAttempts text,
  followCount bigint,
  createdAt datetime,
  agentId real,
  endDate float,
  favoriteCount time,
  isEnabled float,
  category geometry,
  cloudId enum,
  maxLimit int,
  contentType enum,
  dependentId int,
  machineId decimal,
  title decimal,
  distributorId binary,
  minLimit bit,
  dialCode timestamp,
  chatId tinyint,
  likeCount double,
  exportId date,
  isLocked binary,
  insuranceId mediumint,
  lockoutEnd serial,
  depositAmount int
);

CREATE TABLE dim_account (
  id serial primary key,
  version mediumint,
  ipAddress int,
  emailStatus decimal,
  linkId int,
  articleId point,
  taxRate serial,
  avatar real,
  distributorId date,
  emergencyContact boolean,
  value mediumint,
  managerId tinyint,
  companyName timestamp,
  accountStatus decimal,
  gameId smallint,
  currency date,
  colorCode datetime,
  memberCount decimal,
  title mediumint,
  amount datetime,
  deactivatedAt bit,
  menuId boolean,
  apiKey real,
  chatId bigint
);

CREATE TABLE auditv2 (
  id serial primary key,
  memberCount text,
  editedAt real,
  address geometry,
  updatedAt geometry,
  tags enum,
  lastSeenAt mediumint,
  uuid decimal,
  metaTitle bit,
  cacheKey real,
  state binary,
  fileHash time,
  comment real,
  moduleId smallint,
  isArchived timestamp,
  hashKey text,
  signature blob,
  errorMessage set,
  lastLoginAt bigint,
  category decimal,
  orderId smallint,
  cartId bit,
  folderPath set,
  timezone binary,
  role date,
  size decimal
);

CREATE TABLE customer_v1 (
  id serial primary key,
  signature time,
  houseNumber double,
  analyticsId datetime,
  score time,
  connectionString text,
  abandonedCartId smallint,
  invoiceId point,
  editedAt int,
  authMethod text,
  url real,
  instanceId time,
  layerId point,
  category datetime,
  contractId point,
  alertType double,
  errorCode serial,
  firmwareVersion decimal,
  adminNotes mediumint,
  email bigint,
  costCenter double,
  maxLimit serial,
  cityName boolean
);

CREATE TABLE pub_inventory_data (
  id serial primary key,
  isEnabled int,
  thumbnail bit,
  accessLevel blob,
  distributorId text
);

CREATE TABLE company_notifications (
  id serial primary key,
  displayOrder double,
  timezone varchar,
  entryPoint geometry,
  modifiedAt serial
);

CREATE TABLE stg_transaction_data (
  id serial primary key,
  code datetime,
  merchantId time,
  state text,
  insertedAt set,
  languageCode geometry,
  dimension date,
  inactiveAt timestamp,
  cityName bit,
  exchangeRate text,
  companyName float
);

CREATE TABLE ver_organization_seg (
  id serial primary key,
  cacheKey bit,
  deactivatedAt varchar,
  status mediumint,
  customField1 text,
  locationId mediumint,
  bannerImage decimal,
  metaKeywords set,
  orderId decimal,
  comment set,
  instanceId timestamp,
  amount varchar,
  entryPoint tinyint,
  lastLoginAt binary,
  channelId enum,
  group point,
  clientId float,
  password boolean,
  customerGroup smallint,
  loadTime set,
  weight enum,
  depositAmount smallint,
  driverLicense smallint,
  phone boolean
);

CREATE TABLE ext_customer (
  id serial primary key,
  cloudId date,
  role serial,
  weight decimal,
  bankAccount varchar
);

CREATE TABLE organization (
  id serial primary key,
  phone varchar,
  modifiedAt binary
);

CREATE TABLE inventoryv1 (
  id serial primary key,
  feedbackId boolean,
  managerId boolean,
  completedAt set,
  apiVersion double,
  menuId datetime,
  latitude blob
);

