CREATE TABLE order_legacy (
  id serial primary key,
  isBillable point,
  name mediumint,
  paymentMethod set,
  connectionString float,
  deviceId binary,
  enrollmentDate bigint,
  campaignId binary,
  fontFamily geometry,
  isHidden geometry,
  productCode real,
  rating time,
  uuid mediumint,
  hiddenAt varchar,
  ipAddress geometry,
  updatedAt date,
  dashboardId tinyint,
  configId text,
  phone float,
  dealerId enum,
  companyName decimal,
  headerImage blob,
  customerGroup double,
  longitude blob,
  meterNumber set,
  taxRate geometry,
  batchId time,
  isPublic mediumint,
  bankAccount double,
  category tinyint,
  childId datetime
);

CREATE TABLE tmpordermeta (
  id serial primary key,
  token date,
  mimeType set,
  listingId float,
  formatType varchar,
  dueDateAt set,
  downloadCount bit,
  metadata geometry,
  isFeatured point,
  itemCount enum,
  completedAt binary,
  grade time,
  distributorId varchar,
  enabledAt datetime,
  metaKeywords enum,
  quantity timestamp,
  deviceType double,
  dealerId bigint,
  browserType time,
  fontFamily real,
  version binary,
  id double,
  agentId float,
  category set,
  metaDescription geometry,
  marketId float,
  maxValue double,
  value binary
);

CREATE TABLE tbl_order (
  id serial primary key,
  frameRate float,
  extractId bit,
  endPoint decimal,
  sessionId real,
  minValue real,
  maxLimit int,
  iconPath set,
  dialCode point,
  folderPath decimal,
  accountType tinyint,
  deletedAt set,
  price timestamp,
  currencyCode float,
  email smallint,
  dimension bigint
);

CREATE TABLE rel_config_extra (
  id serial primary key,
  priority real,
  marketId tinyint,
  firstName int,
  fingerprint serial,
  productCode int,
  companyLogo geometry,
  menuId point,
  blogId point,
  machineId bigint,
  cityName int,
  ipAddress decimal,
  isDraft text,
  isVerified binary,
  loginAttempts varchar,
  cacheKey float,
  name decimal,
  languageCode timestamp,
  duration real,
  instructorId blob,
  address serial,
  lastLoginAt enum,
  role double,
  exchangeRate geometry,
  discount float,
  deviceType float,
  createdAt serial,
  accessLevel point,
  jobTitle datetime
);

CREATE TABLE record_hist (
  id serial primary key,
  isAdmin mediumint,
  createdAt boolean,
  frameRate decimal,
  postalCode real,
  dealerId real,
  labelText set,
  inactiveAt text,
  age binary,
  latitude text,
  instructorId serial,
  department bit,
  employmentDate point,
  isArchived set,
  apiKey date,
  shippingAddress blob,
  bookingDate geometry,
  referralCode smallint,
  mobileNumber text,
  articleId time,
  fileHash serial,
  browserType float,
  lastSeenAt timestamp,
  minValue enum,
  childId mediumint,
  lockoutEnd smallint,
  backupEmail time,
  cardHolder date,
  authMethod datetime,
  channelId time,
  listingId text
);

CREATE TABLE vw_record_legacy (
  id serial primary key,
  editedAt time,
  cartId datetime,
  iconPath text,
  phone varchar,
  category binary,
  chargeId mediumint,
  longitude geometry,
  instanceId varchar,
  displayOrder text,
  email varchar,
  loginCount enum,
  messageId timestamp,
  globalId float,
  zipCode tinyint,
  totalAmount smallint,
  defaultLang double,
  modifiedAt blob,
  isRequired datetime,
  friendId smallint,
  levelId double
);

CREATE TABLE extuser (
  id serial primary key,
  keywords decimal,
  faxNumber bit,
  childId date,
  taxRate enum,
  itemCount geometry,
  password geometry,
  metaDescription text,
  companyLogo enum,
  backupEmail point,
  status serial,
  bannerImage smallint,
  coordinateX blob,
  domainName int,
  groupName mediumint,
  modifiedAt text,
  validUntil timestamp,
  isFeatured real,
  adminNotes double,
  folderPath int,
  completedAt int,
  currencyCode int,
  completionRate point,
  discount smallint,
  avatar point,
  licenseKey bit
);

CREATE TABLE tmp_customer_meta (
  id serial primary key,
  mobileNumber bit,
  isFeatured varchar,
  copyRight int,
  departmentCode tinyint,
  creditScore mediumint,
  gateId decimal,
  dashboardId set,
  moduleId bigint,
  latitude text,
  address boolean,
  fileSize smallint,
  itemCount enum,
  password blob,
  endPoint tinyint,
  metaTitle text,
  keywords enum,
  age float,
  orderId timestamp,
  deviceType enum,
  dealerId mediumint
);

CREATE TABLE vw_user_archive_temp (
  id serial primary key,
  cacheKey bit,
  folderPath binary,
  status real,
  isDeleted tinyint
);

CREATE TABLE audit_2024 (
  id serial primary key,
  browserType enum,
  batchId blob,
  labelText tinyint
);

CREATE TABLE usermetanew (
  id serial primary key,
  hostName text,
  deletedAt geometry,
  labelText varchar,
  hashKey boolean,
  password tinyint,
  logLevel set,
  insuranceId point,
  guestId timestamp,
  groupName tinyint,
  localeId geometry,
  gateId double,
  lastName datetime,
  displayName geometry
);

CREATE TABLE tmprecord (
  id serial primary key,
  lockoutEnd binary,
  birthDate set,
  countryCode bit,
  dashboardId time,
  description bigint,
  forwardTo enum,
  jobTitle serial
);

CREATE TABLE organizationmeta (
  id serial primary key,
  localeId float,
  mainImage date
);

CREATE TABLE record (
  id serial primary key,
  role bigint,
  copyRight point,
  dealerId float,
  maritalStatus float,
  companyName decimal,
  customerGroup bigint,
  cvv boolean,
  version smallint,
  comment int,
  followCount boolean,
  hashKey serial,
  lastLoginAt point,
  sessionId double,
  inactiveAt geometry,
  chargeId float,
  fontSize smallint,
  title datetime,
  isSystem datetime,
  hostName binary
);

CREATE TABLE product (
  id serial primary key,
  email text,
  employeeId varchar,
  appVersion date
);

CREATE TABLE organization_2024 (
  id serial primary key,
  importId enum,
  url tinyint,
  customField1 double,
  avatar binary,
  maskType float,
  fileName decimal,
  jobTitle bigint,
  dependentId point,
  meterNumber timestamp,
  eventDate datetime,
  connectionString date,
  distributorId double,
  deviceType tinyint,
  insertedAt bigint
);

CREATE TABLE config (
  id serial primary key,
  billingFrequency decimal,
  manufacturerId enum,
  dashboardId date,
  password bigint,
  isSystem float,
  hashKey date,
  sessionId tinyint,
  signature date,
  dataSource smallint,
  locationId date
);

CREATE TABLE organization_map (
  id serial primary key,
  keywords point,
  editedAt mediumint,
  alertType blob,
  messageId tinyint,
  deviceType enum,
  endDate enum
);

CREATE TABLE organization (
  id serial primary key,
  lockoutEnd mediumint,
  mobileNumber real,
  fileType timestamp,
  localeId double,
  billingCycle datetime,
  createdAt mediumint,
  name serial,
  role set,
  expiryYear mediumint,
  longitude double,
  isDefault point,
  age double,
  loginCount date,
  countryCode point,
  orderId binary,
  flagged double,
  id binary,
  postalCode decimal,
  gender real,
  guestId float,
  contractId int,
  formatType blob,
  licenseKey bigint,
  albumId set,
  state real,
  completedAt timestamp,
  discountCode mediumint
);

CREATE TABLE pub_product (
  id serial primary key,
  sessionId time,
  dateFormat binary,
  productCode tinyint,
  cardNumber date,
  browserType double,
  isAdmin binary,
  signature geometry,
  firmwareVersion point,
  gender mediumint,
  dataSource int,
  comment geometry,
  accountStatus boolean,
  albumId blob,
  isLocked enum,
  contactName binary
);

CREATE TABLE pubaccount (
  id serial primary key,
  isDraft text,
  downloadCount text,
  isEnabled smallint,
  id date,
  cardNumber set,
  dashboardId float,
  age date,
  longitude geometry,
  entityId int,
  deliveryDate text,
  latitude binary,
  billingCycle float,
  phone geometry,
  deviceId bigint,
  headerImage point,
  folderPath text
);

CREATE TABLE dim_payment (
  id serial primary key,
  height datetime,
  childId set,
  deactivatedAt mediumint,
  token binary,
  entryPoint bigint,
  accessLevel varchar,
  colorCode varchar,
  paymentMethod set,
  downloadCount bit,
  loginCount geometry,
  role blob,
  hourlyRate smallint,
  memberCount double,
  companyLogo enum,
  category real,
  authorId boolean,
  clockOut bit,
  createdAt enum,
  analyticsId binary,
  deviceToken smallint,
  balance datetime,
  machineId point,
  handlerId timestamp,
  status date
);

CREATE TABLE privorganizationlegacy (
  id serial primary key,
  bookingDate time,
  phone binary,
  street timestamp
);

CREATE TABLE user_status_temp (
  id serial primary key,
  exchangeRate tinyint,
  expiryYear int,
  height int,
  lastSeenAt datetime,
  cacheKey serial,
  maxLimit bit,
  description double,
  configId bigint,
  employmentDate double,
  analyticsId bigint,
  dealerId time,
  orderStatus mediumint,
  loginCount mediumint,
  clockIn serial,
  displayOrder real,
  metaDescription float,
  deviceType bit,
  actionType real,
  isLocked point,
  customField2 datetime,
  customerGroup enum,
  id set,
  itemCount set
);

CREATE TABLE account (
  id serial primary key,
  avatar point,
  metaKeywords int,
  monthlyRate bit,
  fromDate date,
  keywords geometry,
  bankAccount time,
  houseNumber set,
  checkInTime varchar,
  name smallint,
  industryType geometry,
  startDate int,
  group blob,
  lastName geometry,
  paymentMethod bit,
  handlerId smallint,
  longitude point,
  modifiedAt boolean
);

CREATE TABLE rel_customer (
  id serial primary key,
  category enum,
  name binary,
  defaultLang bigint,
  cacheKey enum,
  distributorId double,
  content mediumint,
  activeDevices serial,
  avatar text,
  addressLine1 bit,
  lockoutEnd serial,
  hiddenAt time,
  dataSource boolean,
  maritalStatus real,
  itemCount time,
  firmwareVersion float,
  email int,
  managerId boolean,
  actionType datetime
);

CREATE TABLE tblcompany (
  id serial primary key,
  frameRate text,
  weight enum,
  linkId blob,
  analyticsId binary,
  attachmentUrl blob,
  isDefault decimal,
  attemptCount boolean,
  folderPath point,
  itemCount double,
  loginAttempts float,
  deletedAt float,
  status timestamp,
  invoiceId real
);

CREATE TABLE user (
  id serial primary key,
  currencyCode tinyint,
  frameRate bit,
  importId blob,
  layerId time,
  inactiveAt point,
  dataSource mediumint,
  sessionId enum,
  title smallint,
  isFeatured serial,
  eventDate smallint,
  category smallint,
  depositAmount blob,
  updatedAt float,
  dimension blob,
  expiryYear boolean,
  status decimal,
  firmwareVersion text
);

CREATE TABLE dim_company_archive (
  id serial primary key,
  defaultLang geometry,
  gameId time,
  importId text,
  fileSize int
);

CREATE TABLE product (
  id serial primary key,
  balance varchar,
  id bigint,
  lastName text,
  updatedAt time
);

CREATE TABLE config (
  id serial primary key,
  completionRate decimal,
  filterType date,
  nickname mediumint,
  fontSize boolean,
  awardDate varchar,
  cardHolder mediumint,
  hiddenAt date,
  customerId int,
  facilityId varchar,
  industryType float,
  labelText tinyint,
  creditScore blob,
  meterNumber real,
  duration bigint,
  billingFrequency text,
  description tinyint,
  metadata tinyint,
  fingerprint date,
  ipAddress smallint,
  marketId binary,
  inactiveAt set
);

CREATE TABLE ext_transaction_notifications (
  id serial primary key,
  group text,
  itemCount datetime,
  comment date,
  avatar serial,
  updatedAt double,
  dimension geometry,
  budgetCode varchar,
  inactiveAt enum,
  id time,
  monthlyRate bigint,
  customerId enum,
  latitude real,
  clientId set,
  isFeatured tinyint,
  logLevel binary,
  name serial,
  entryPoint datetime,
  analyticsId boolean,
  sku boolean,
  paymentMethod point,
  checkOutTime real,
  maxValue mediumint,
  contactPhone set,
  birthDate double,
  importId decimal
);

CREATE TABLE tmp_customer (
  id serial primary key,
  validUntil float,
  earnedPoints mediumint,
  listingId blob,
  longitude geometry,
  clientId text,
  version int,
  keyId timestamp,
  createdAt float,
  languageCode tinyint,
  moveId decimal,
  contractId date,
  levelId point,
  bankAccount blob,
  albumId time,
  email enum,
  education enum,
  deviceType text,
  comment varchar,
  orderStatus real,
  contactPhone set,
  indexKey varchar
);

CREATE TABLE product (
  id serial primary key,
  clockOut int,
  title date,
  faxNumber mediumint,
  maxLimit real,
  defaultLang float,
  eventDate time,
  expiryMonth real,
  analyticsId decimal,
  locationId tinyint,
  bankAccount real,
  firstName bigint,
  headerImage smallint,
  minLimit time,
  discountCode serial,
  accountStatus varchar,
  url serial,
  accountType mediumint,
  middleName serial,
  shippingAddress smallint,
  score enum,
  endDate blob,
  price real,
  lastName bit,
  age bigint
);

CREATE TABLE payment (
  id serial primary key,
  favoriteCount datetime,
  dailyLimit date,
  contentType boolean,
  currencyCode point,
  locationId point,
  hiddenAt float,
  metadata int,
  isAdmin double,
  extractId int,
  countryCode datetime,
  emailStatus int,
  title geometry
);

CREATE TABLE log_payment_div (
  id serial primary key,
  insuranceId enum,
  managerId binary,
  frameRate serial,
  expiryYear varchar,
  displayName double,
  companyName blob,
  manufacturerId point,
  dateFormat blob,
  expiryDate boolean,
  accessLevel text,
  checkInTime time,
  displayOrder int,
  attachmentUrl float,
  clockIn decimal,
  likeCount enum,
  entryPoint datetime,
  completedAt bigint,
  isBillable decimal,
  comment serial,
  title set,
  locationId date,
  configId tinyint,
  apiVersion timestamp,
  mapId varchar,
  listId smallint,
  contactEmail enum,
  abandonedCartId tinyint,
  labelText datetime,
  followCount double,
  creditCard date
);

CREATE TABLE src_audit (
  id serial primary key,
  loginCount set,
  isRequired float,
  paymentMethod tinyint,
  currencyCode bit,
  customerId binary,
  currency binary,
  defaultLang float,
  isSystem timestamp,
  marketId binary,
  authToken serial,
  lastSeenAt blob,
  displayOrder date,
  cardNumber blob,
  id boolean,
  sku set,
  latitude geometry,
  appVersion int,
  token point,
  machineId double,
  createdAt bit,
  monthlyRate blob,
  albumId smallint,
  attachmentUrl point,
  deactivatedAt binary,
  height mediumint,
  houseNumber varchar
);

CREATE TABLE company_legacy (
  id serial primary key,
  distributorId mediumint,
  indexKey double,
  locationId datetime,
  exportId int,
  bookingDate varchar,
  version timestamp,
  keywords decimal,
  firstName mediumint,
  messageId boolean,
  isLocked text,
  status blob,
  minLimit bigint,
  isRequired mediumint,
  description blob,
  moduleId set,
  thumbnail point,
  ipAddress real,
  accountType double,
  customerId datetime
);

CREATE TABLE pub_inventory (
  id serial primary key,
  isLocked enum,
  endDate varchar,
  education point,
  birthDate smallint,
  cancelReason bit,
  zipCode point,
  insertedAt point,
  dateFormat text,
  extractId serial,
  lastName datetime,
  layerId point,
  certificateId geometry,
  dependentId geometry,
  email smallint,
  isDefault blob,
  department bit,
  fingerprint blob,
  updatedAt blob,
  companyLogo bit,
  clientId geometry,
  logLevel serial,
  avatar int,
  deliveryDate smallint,
  colorCode date
);

CREATE TABLE app_product (
  id serial primary key,
  nickname time,
  hostName enum
);

CREATE TABLE customer_2024 (
  id serial primary key,
  weight datetime,
  isSystem date,
  metaDescription time,
  customerGroup tinyint,
  ipAddress varchar,
  isArchived smallint,
  street real,
  createdAt enum,
  listingId date,
  accountStatus set,
  campaignId bit,
  childId text,
  type date,
  isRequired tinyint,
  batchId set,
  expiryDate mediumint,
  comment smallint,
  size mediumint
);

CREATE TABLE pubproduct (
  id serial primary key,
  instanceId bigint,
  filterType binary,
  displayName text,
  metaDescription timestamp,
  completedAt bit,
  id time,
  albumId time,
  companyLogo decimal,
  contentType float,
  accountType blob,
  houseNumber serial,
  itemCount set,
  customerId varchar,
  state bit,
  distributorId float,
  keywords point,
  billingCycle serial,
  isPublic tinyint,
  category double,
  headerImage int
);

CREATE TABLE company (
  id serial primary key,
  groupName blob,
  mobileNumber point
);

CREATE TABLE order (
  id serial primary key,
  domainName decimal,
  documentId geometry,
  isFeatured timestamp
);

CREATE TABLE payment (
  id serial primary key,
  isDeleted point,
  clockIn bigint,
  type date,
  departmentCode bigint,
  courseId float,
  cvv date,
  browserType blob,
  attachmentUrl float,
  errorCode double,
  insertedAt set,
  coordinateY mediumint,
  lockoutEnd enum,
  feedbackId varchar,
  priority blob,
  duration smallint,
  levelId binary,
  lastSeenAt serial,
  errorMessage bit,
  fileName mediumint,
  price geometry,
  paymentMethod text,
  metadata datetime,
  tags geometry,
  mainImage int,
  checkOutTime tinyint,
  couponCode mediumint,
  sessionId smallint,
  id date,
  albumId bit,
  loginAttempts tinyint,
  copyRight blob
);

CREATE TABLE accountout (
  id serial primary key,
  moveId bigint,
  validUntil varchar,
  mapId serial,
  bluetoothId datetime,
  checkInTime datetime,
  dueDateAt real,
  expiryDate bit,
  marketId tinyint,
  alertType point,
  postalCode timestamp,
  linkId mediumint,
  browserType serial,
  bannerImage enum,
  merchantId smallint,
  accountStatus time,
  password real,
  campaignId mediumint,
  price tinyint,
  isAdmin bit,
  dashboardId smallint,
  dateFormat point,
  deliveryDate point,
  customField2 float,
  handlerId enum,
  incidentId datetime,
  emailStatus smallint,
  firstName point,
  uuid real,
  agentId boolean,
  employeeId binary,
  insuranceId datetime
);

CREATE TABLE payment (
  id serial primary key,
  deletedAt decimal,
  foregroundColor time,
  customerId binary,
  zipCode tinyint,
  birthDate float,
  invoiceId set,
  articleId real,
  eventDate point,
  description datetime,
  emailStatus serial,
  creditLimit serial,
  apiVersion real,
  dataSource time,
  employmentDate real,
  insuranceId bit,
  companyLogo binary,
  size real,
  price int,
  courseId date,
  downloadCount enum,
  addressLine1 time,
  age text,
  floorNumber real
);

CREATE TABLE stg_payment_2025 (
  id serial primary key,
  maskType int,
  orderStatus float,
  apiVersion time,
  state text,
  mapId point,
  labelText point,
  loginCount tinyint,
  productCode varchar,
  expiryDate smallint,
  amount double,
  guestId geometry,
  lastLoginAt mediumint,
  dateFormat set,
  dialCode varchar,
  batchId binary,
  deletedAt smallint,
  adminNotes point,
  nickname blob,
  postalCode time,
  invoiceId enum,
  bluetoothId geometry,
  completedAt date
);

CREATE TABLE pub_account (
  id serial primary key,
  dialCode decimal,
  insertedAt bigint,
  geoLocation float,
  agentId varchar,
  creditCard smallint,
  likeCount varchar,
  loginAttempts enum,
  fileSize mediumint,
  endDate time,
  updatedAt double,
  contactName boolean,
  labelText double,
  formatType time,
  customerId int,
  salary varchar,
  checkInTime varchar,
  emailStatus date,
  forwardTo bit,
  dailyLimit bigint,
  phone boolean,
  foregroundColor serial,
  expiryMonth double,
  description bigint,
  longitude date
);

CREATE TABLE customer_hist (
  id serial primary key,
  joinDate set,
  latitude enum,
  attachmentUrl int,
  minValue tinyint,
  fingerprint timestamp,
  emergencyContact text,
  locationId smallint,
  fileSize int
);

