CREATE TABLE srcaccount (
  id serial primary key,
  creditScore float,
  defaultValue date,
  cancelReason decimal,
  contactEmail blob,
  department mediumint,
  enrollmentDate real,
  status boolean,
  errorMessage double,
  weight tinyint,
  bluetoothId timestamp,
  configId boolean,
  lockoutEnd binary,
  distributorId mediumint,
  costCenter date,
  state set,
  salary mediumint,
  content date,
  copyRight smallint,
  bookingDate real,
  endPoint text,
  albumId double,
  metadata text,
  middleName text,
  foregroundColor binary,
  macAddress real,
  displayName int,
  eventDate bigint
);

CREATE TABLE dim_product_extra (
  id serial primary key,
  metadata real,
  floorNumber serial,
  fontFamily mediumint,
  colorCode enum,
  employmentDate date,
  addressLine2 time,
  age blob,
  manufacturerId bit,
  uuid timestamp,
  value time,
  budgetCode datetime,
  token real,
  attemptCount text,
  employeeCode blob,
  bankAccount mediumint
);

CREATE TABLE tmp_inventory_hist (
  id serial primary key,
  mimeType date,
  costCenter binary,
  group int,
  configId double,
  duration serial,
  feedId timestamp,
  iconPath serial,
  productCode blob,
  analyticsId double,
  value boolean,
  friendId datetime,
  bannerImage bit,
  minLimit set,
  lastName enum,
  thumbnail double,
  url set,
  addressLine1 geometry,
  metaTitle enum,
  facilityId blob,
  labelText float,
  expiryDate binary,
  licenseKey timestamp,
  lastLoginAt blob,
  dependentId blob,
  height int,
  bankAccount smallint
);

CREATE TABLE product (
  id serial primary key,
  depositAmount date,
  creditCard time,
  deactivatedAt int,
  maritalStatus binary,
  formatType date,
  group boolean,
  fileType set
);

CREATE TABLE record_archive (
  id serial primary key,
  avatar smallint,
  courseId datetime,
  formatType bigint,
  updatedAt double,
  accessLevel timestamp,
  logLevel bigint,
  firstName binary,
  countryCode point,
  validUntil boolean
);

CREATE TABLE audit (
  id serial primary key,
  invoiceId mediumint,
  countryCode binary,
  brandId tinyint,
  metaDescription int
);

CREATE TABLE tblconfig (
  id serial primary key,
  cartId int,
  code enum
);

CREATE TABLE transactionseg (
  id serial primary key,
  contractId int,
  domainName smallint,
  coordinateY binary,
  gateId int,
  certificateId binary
);

CREATE TABLE record (
  id serial primary key,
  geoLocation mediumint,
  fileHash tinyint,
  street enum,
  hiddenAt set,
  apiVersion geometry,
  coverImage bigint,
  cvv binary,
  merchantId binary,
  flagged set,
  sessionId blob,
  incidentId real,
  priority real,
  fromDate bit,
  cardNumber smallint,
  agentId text,
  configId enum,
  currencyCode enum,
  messageId text,
  facilityId text,
  paymentMethod real,
  itemCount double,
  albumId varchar,
  signature decimal,
  phone bit,
  batchId decimal,
  dataSource decimal
);

CREATE TABLE olk_audit_notifications (
  id serial primary key,
  bluetoothId bigint,
  metaDescription text,
  attachmentUrl mediumint,
  title blob,
  labelText bit,
  updatedAt text,
  downloadCount serial,
  url time,
  orderStatus smallint,
  feedbackId varchar,
  houseNumber bigint,
  apiKey varchar,
  rating time,
  age real,
  backupEmail date,
  currency float,
  country boolean,
  filterType binary,
  channelId bit,
  campaignId int,
  salary blob,
  articleId mediumint,
  tags set,
  avatar point,
  geoLocation bit,
  state time
);

CREATE TABLE aggtransaction (
  id serial primary key,
  description binary,
  actionType tinyint,
  likeCount real,
  appVersion bigint,
  globalId mediumint,
  isHidden datetime,
  lastLoginAt varchar,
  coverImage binary,
  productCode smallint,
  connectionString datetime,
  childId boolean,
  groupName enum,
  sku tinyint,
  adminNotes double,
  salary datetime,
  cvv enum,
  amount varchar,
  insertedAt boolean,
  employeeCode double
);

CREATE TABLE tmp_order_type (
  id serial primary key,
  importId blob,
  lastSeenAt bit,
  albumId point,
  bannerImage timestamp,
  fingerprint set,
  entryPoint float,
  batchId double,
  rating set,
  ipAddress time,
  articleId boolean
);

CREATE TABLE exttransaction (
  id serial primary key,
  emergencyContact enum,
  mainImage decimal
);

CREATE TABLE organization_type (
  id serial primary key,
  coordinateX bigint,
  emergencyContact timestamp,
  country geometry,
  activeDevices real,
  domainName boolean,
  completedAt serial,
  blogId varchar,
  amount binary,
  industryType geometry,
  password text,
  licenseKey timestamp,
  marketId real,
  importId real,
  budgetCode set,
  frameRate decimal,
  startDate time,
  cancelReason mediumint,
  groupName geometry,
  description set,
  defaultValue float,
  claimId bit
);

CREATE TABLE product_v1 (
  id serial primary key,
  dimension decimal,
  comment tinyint,
  unit decimal,
  createdAt mediumint,
  menuId datetime,
  mainImage date,
  awardDate mediumint,
  forwardTo bigint
);

CREATE TABLE olk_organization (
  id serial primary key,
  address mediumint,
  expiryYear varchar,
  expiryDate blob,
  cartId enum,
  clockIn date,
  rating boolean,
  modifiedAt geometry,
  hiddenAt smallint,
  phone geometry,
  cardHolder double,
  licenseKey bit,
  exchangeRate serial,
  isVerified real
);

CREATE TABLE transaction (
  id serial primary key,
  minValue boolean,
  menuId serial,
  dimension mediumint,
  marketId timestamp,
  uuid timestamp
);

CREATE TABLE account_legacy (
  id serial primary key,
  content mediumint,
  contentType boolean,
  authToken decimal,
  fileType real,
  apiVersion tinyint,
  id tinyint,
  batchId varchar,
  guestId boolean,
  instanceId point,
  handlerId blob,
  isVerified point,
  houseNumber time,
  deviceType bit,
  formatType mediumint,
  country varchar,
  contactEmail int,
  frameRate set,
  emergencyContact blob,
  machineId binary,
  alertType boolean,
  isDefault point,
  localeId int,
  isFeatured blob,
  incidentId bit,
  feedbackId real,
  loginCount serial,
  lastSeenAt timestamp,
  isLocked time,
  salary varchar,
  sku varchar
);

CREATE TABLE user_archive (
  id serial primary key,
  hourlyRate serial,
  loadTime boolean,
  timezone time,
  isVerified enum,
  expiryDate point,
  expiryYear bigint,
  discountCode date,
  employeeId decimal,
  addressLine2 bigint,
  minValue smallint
);

CREATE TABLE account_status (
  id serial primary key,
  endPoint decimal,
  productCode datetime,
  facilityId bigint,
  accessLevel int,
  linkId date,
  updatedAt mediumint,
  customerId varchar,
  eventDate enum,
  loginCount set,
  password int,
  instanceId tinyint,
  dataSource boolean
);

CREATE TABLE payment_rel (
  id serial primary key,
  employmentDate enum,
  budgetCode geometry,
  createdAt mediumint,
  coordinateX enum,
  metaDescription serial,
  distributorId varchar,
  birthDate bit,
  claimId mediumint,
  eventDate geometry,
  sessionId double,
  likeCount binary,
  isArchived int,
  size geometry,
  content bigint,
  emergencyContact date,
  cancelReason tinyint,
  levelId smallint,
  bookingDate date,
  firstName time,
  street int,
  status set,
  age date,
  token smallint,
  authMethod smallint,
  country double,
  alertType serial,
  addressLine1 time
);

CREATE TABLE record (
  id serial primary key,
  facilityId real,
  companyLogo blob,
  gateId datetime,
  endPoint smallint,
  group bigint,
  menuId mediumint,
  homePhone mediumint,
  version blob,
  url datetime,
  minLimit date
);

CREATE TABLE transactionseg (
  id serial primary key,
  coordinateY timestamp,
  messageId bigint,
  attachmentUrl point,
  moveId set,
  dailyLimit geometry,
  companyLogo bit,
  bluetoothId boolean,
  feedbackId int,
  ipAddress bit,
  apiVersion blob,
  claimId boolean,
  cityName real,
  manufacturerId float,
  contactPhone binary,
  url serial,
  errorMessage text,
  budgetCode varchar,
  score smallint,
  discount time,
  expiryMonth blob,
  employmentDate timestamp,
  earnedPoints bigint,
  group real,
  entryPoint bigint,
  defaultLang geometry,
  emailStatus datetime
);

CREATE TABLE cpy_organization_legacy (
  id serial primary key,
  authToken boolean,
  fingerprint smallint,
  isSystem timestamp,
  billingFrequency blob,
  moduleId serial,
  comment varchar,
  contactName date,
  buildNumber tinyint,
  age binary,
  connectionString int,
  completionRate timestamp,
  bookingDate point,
  deviceId blob,
  metaKeywords tinyint,
  extractId boolean,
  chatId smallint,
  attachmentUrl real,
  amount int,
  metaTitle smallint,
  channelId datetime,
  phone real,
  couponCode text,
  token decimal,
  description datetime,
  itemCount real,
  coverImage float,
  industryType float,
  customerId real,
  accessLevel datetime,
  name int
);

CREATE TABLE ver_user_v2 (
  id serial primary key,
  employeeCode varchar,
  bankAccount enum,
  comment bigint,
  loginCount binary,
  category bit,
  isDraft double,
  courseId real,
  checkInTime bit
);

CREATE TABLE rel_record (
  id serial primary key,
  status text,
  value bit,
  cancelReason real,
  taxRate bit,
  longitude point,
  errorCode date
);

CREATE TABLE dstaccount (
  id serial primary key,
  mainImage time,
  coverImage real,
  deletedAt enum,
  creditLimit date,
  jobTitle binary,
  phone text,
  dataSource real,
  comment double,
  tags real,
  messageId time,
  fontFamily double,
  duration enum,
  longitude smallint,
  currency varchar,
  authToken int,
  employeeId time,
  alertType set,
  token bit,
  attemptCount varchar,
  likeCount mediumint,
  email enum,
  articleId timestamp,
  driverLicense timestamp,
  mimeType serial,
  deviceType binary,
  employeeCode datetime,
  description point,
  salary text,
  address int,
  employmentDate float
);

CREATE TABLE sys_record_map_v1 (
  id serial primary key,
  longitude real,
  downloadCount float,
  updatedAt binary,
  extractId date,
  value tinyint,
  comment int,
  brandId double,
  isSystem time,
  analyticsId decimal,
  floorNumber float,
  state float,
  ipAddress timestamp,
  budgetCode float,
  abandonedCartId timestamp,
  levelId float,
  paymentMethod real,
  education point,
  orderId double,
  managerId mediumint,
  name timestamp,
  quantity bit,
  childId blob,
  deviceId timestamp,
  sessionId datetime
);

CREATE TABLE record (
  id serial primary key,
  authMethod timestamp,
  exchangeRate datetime,
  uuid float,
  status geometry,
  token varchar,
  isHidden int,
  street boolean,
  isAdmin blob,
  globalId blob,
  thumbnail bit,
  fileHash point,
  bookingDate text,
  createdAt int,
  houseNumber double,
  messageId datetime,
  checkInTime boolean,
  cvv bit,
  grade float,
  feedId boolean,
  merchantId date,
  contactPhone mediumint
);

CREATE TABLE user_extra (
  id serial primary key,
  extractId geometry,
  blogId text,
  updatedAt date,
  uuid enum,
  loginCount timestamp,
  errorMessage date,
  expiryDate serial,
  businessType boolean,
  activeDevices enum,
  token timestamp,
  tags time,
  hourlyRate smallint,
  zipCode text,
  childId real,
  likeCount text,
  maxLimit real,
  contactEmail point,
  content timestamp,
  billingFrequency float,
  cloudId smallint,
  isDraft boolean
);

CREATE TABLE tmp_user (
  id serial primary key,
  brandId bit,
  currencyCode mediumint,
  logLevel geometry,
  courseId point,
  email real,
  creditScore geometry
);

CREATE TABLE tbl_organization_meta (
  id serial primary key,
  alertType smallint,
  creditLimit geometry,
  username blob,
  dataSource tinyint,
  description mediumint,
  companyLogo real,
  loginCount blob,
  actionType bigint,
  authToken smallint,
  timezone decimal,
  token varchar,
  country timestamp,
  accessLevel point,
  lastSeenAt decimal
);

CREATE TABLE ver_payment_seg_v2 (
  id serial primary key,
  totalAmount time,
  updatedAt point,
  education time,
  endPoint set,
  lastLoginAt binary,
  copyRight float,
  expiryYear time,
  clockIn decimal,
  checkInTime enum,
  filterType binary,
  activeDevices double,
  exportId decimal,
  dailyLimit smallint,
  iconPath smallint,
  integrationId text,
  token geometry,
  globalId timestamp,
  deactivatedAt timestamp,
  minLimit enum,
  birthDate datetime,
  mainImage date,
  orderId serial,
  dimension int,
  mobileNumber blob
);

CREATE TABLE dim_user (
  id serial primary key,
  levelId varchar,
  activeDevices smallint,
  isDraft float,
  keywords date,
  middleName float,
  apiKey set,
  zipCode binary,
  creditLimit decimal,
  downloadCount varchar,
  companyLogo binary,
  group bigint,
  completedAt mediumint,
  modifiedAt geometry,
  layerId real,
  insertedAt decimal
);

CREATE TABLE tbl_product (
  id serial primary key,
  endDate decimal,
  loginAttempts blob,
  group point,
  listId varchar,
  paymentMethod binary,
  agentId datetime,
  updatedAt timestamp,
  handlerId boolean,
  lastLoginAt binary,
  customField2 double,
  exchangeRate datetime,
  departmentCode float,
  fileType varchar,
  amount binary,
  tags text,
  memberCount real,
  globalId serial,
  listingId serial,
  dueDateAt datetime,
  lockoutEnd bit,
  version date,
  fontSize decimal,
  clockIn bigint,
  checkInTime enum,
  languageCode decimal,
  attachmentUrl time,
  defaultValue timestamp,
  zipCode float,
  marketId set,
  value bigint
);

CREATE TABLE tmp_audit (
  id serial primary key,
  homePhone mediumint,
  joinDate blob,
  childId time,
  machineId real,
  accountStatus serial,
  companyName date,
  messageId text,
  awardDate tinyint,
  editedAt smallint,
  dailyLimit bigint,
  listingId serial,
  addressLine2 bit,
  feedId enum,
  signature serial,
  displayOrder set,
  attachmentUrl geometry,
  macAddress set,
  entityId decimal,
  totalAmount tinyint,
  productCode enum,
  clientId bigint
);

CREATE TABLE audit2024 (
  id serial primary key,
  geoLocation float,
  weight decimal,
  feedId binary,
  copyRight bigint,
  meterNumber date
);

CREATE TABLE customer (
  id serial primary key,
  indexKey bit,
  deviceType bit,
  handlerId tinyint,
  keywords binary,
  size set,
  avatar blob,
  accountStatus text,
  downloadCount time,
  firstName bigint,
  feedId real,
  endDate text,
  isActive point,
  memberCount float
);

CREATE TABLE record_legacy (
  id serial primary key,
  blogId point,
  globalId datetime,
  distributorId bit,
  salary int,
  frameRate blob,
  minValue set,
  dashboardId double,
  checkOutTime geometry,
  loginCount geometry,
  faxNumber double,
  costCenter double,
  firmwareVersion float,
  discount decimal,
  defaultValue datetime,
  price enum,
  url timestamp,
  messageId bigint,
  audioUrl time,
  likeCount blob,
  algorithm blob,
  listId int,
  monthlyRate point,
  managerId set,
  accountType int,
  facilityId double,
  avatar double,
  discountCode smallint
);

CREATE TABLE inventory (
  id serial primary key,
  name date,
  latitude time,
  startDate datetime,
  title decimal,
  floorNumber double,
  hourlyRate decimal,
  status float,
  actionType smallint,
  dealerId datetime,
  content varchar,
  incidentId geometry,
  couponCode blob,
  dateFormat float,
  description text,
  clockIn real,
  companyName datetime,
  sessionId double,
  facilityId bigint,
  ipAddress decimal,
  uuid tinyint,
  channelId varchar,
  category datetime,
  configId decimal,
  completedAt mediumint,
  duration timestamp,
  role blob,
  address date,
  managerId timestamp
);

CREATE TABLE ext_user_out (
  id serial primary key,
  machineId geometry,
  configId text,
  awardDate double,
  connectionString mediumint,
  macAddress set,
  currencyCode date,
  monthlyRate bigint,
  activeDevices varchar,
  amount blob,
  checkOutTime point,
  comment double,
  title bit,
  name point,
  type mediumint,
  mapId datetime,
  dealerId int,
  timezone decimal,
  cartId date,
  signature set,
  listId serial
);

CREATE TABLE audit (
  id serial primary key,
  size geometry,
  title enum,
  currency text,
  audioUrl decimal,
  customerId date,
  isDefault time,
  updatedAt timestamp,
  isFeatured serial,
  email real,
  postalCode int,
  quantity bigint,
  deviceId mediumint,
  campaignId text,
  orderId mediumint,
  listId time,
  handlerId point,
  bannerImage binary,
  category varchar,
  defaultValue smallint,
  accountNumber set,
  lockoutEnd blob
);

CREATE TABLE stgcompanymap (
  id serial primary key,
  errorCode geometry,
  id int,
  completedAt varchar,
  colorCode bit,
  forwardTo datetime,
  state text,
  followCount set,
  authMethod decimal,
  accountStatus varchar,
  token date,
  title timestamp,
  contentType timestamp,
  value geometry,
  channelId decimal,
  avatar point,
  iconPath mediumint,
  billingFrequency point,
  buildNumber date,
  middleName blob,
  size set,
  loginCount date,
  agentId varchar,
  awardDate enum,
  machineId time,
  latitude binary,
  linkId float,
  isBillable text,
  orderId varchar,
  education smallint,
  actionType datetime,
  billingCycle real
);

CREATE TABLE product (
  id serial primary key,
  instructorId date,
  keyId boolean,
  appVersion serial,
  phone smallint,
  buildNumber double,
  sessionId decimal,
  metaKeywords tinyint,
  flagged date,
  postalCode bigint,
  handlerId datetime,
  extractId decimal,
  birthDate smallint,
  minValue enum,
  timezone geometry,
  meterNumber date,
  password decimal,
  isLocked double,
  businessType double,
  messageId smallint,
  floorNumber geometry,
  email set,
  gateId int,
  hostName int,
  downloadCount blob,
  maxLimit bit
);

CREATE TABLE cpyconfigout (
  id serial primary key,
  enabledAt binary,
  coordinateX bigint,
  flagged binary,
  feedbackId text,
  customerGroup float,
  colorCode int,
  bannerImage date,
  latitude timestamp,
  analyticsId binary,
  contentType date,
  billingFrequency varchar,
  timezone bigint,
  instanceId mediumint,
  instructorId time,
  deviceId serial,
  bankAccount binary
);

CREATE TABLE sysauditout (
  id serial primary key,
  totalAmount date,
  algorithm point,
  role date,
  dateFormat set,
  code enum,
  joinDate enum,
  value binary,
  billingCycle time,
  discountCode enum
);

CREATE TABLE transaction (
  id serial primary key,
  group boolean,
  clockIn enum,
  feedbackId real,
  fontFamily binary,
  errorCode smallint,
  taxRate float,
  articleId smallint,
  id boolean,
  dateFormat double,
  customerGroup real,
  accessLevel geometry,
  customerId time,
  validUntil decimal,
  connectionString float,
  insertedAt enum,
  isRequired bit,
  postalCode decimal,
  contactEmail set,
  earnedPoints mediumint,
  fromDate mediumint,
  dataSource decimal,
  floorNumber tinyint,
  entityId bit,
  balance serial,
  timezone smallint,
  description enum,
  locationId varchar,
  likeCount decimal,
  title double
);

CREATE TABLE order (
  id serial primary key,
  employmentDate bit,
  faxNumber timestamp,
  cardNumber point,
  completedAt blob,
  alertType decimal,
  feedId time,
  postalCode double,
  memberCount date,
  moveId text,
  salary tinyint,
  articleId decimal,
  deviceId text,
  age tinyint,
  bluetoothId binary,
  comment float,
  brandId mediumint,
  middleName int,
  currencyCode mediumint,
  childId smallint,
  balance decimal,
  cloudId timestamp,
  id smallint,
  depositAmount geometry,
  defaultLang int,
  hiddenAt tinyint,
  endDate datetime,
  domainName binary,
  checkInTime text,
  creditCard text
);

CREATE TABLE ver_product (
  id serial primary key,
  integrationId enum,
  monthlyRate timestamp,
  feedId geometry,
  lockoutEnd serial,
  minLimit text,
  domainName tinyint
);

CREATE TABLE core_transaction_new (
  id serial primary key,
  costCenter smallint,
  defaultLang int,
  moduleId boolean,
  name real,
  machineId serial,
  activeDevices smallint,
  apiKey timestamp,
  errorMessage boolean,
  accountNumber decimal,
  createdAt mediumint,
  url timestamp,
  cityName point,
  avatar datetime,
  metadata set,
  middleName geometry,
  globalId timestamp,
  gender serial,
  indexKey decimal,
  cvv time,
  department decimal,
  monthlyRate geometry,
  lastName enum,
  addressLine2 set,
  clientId mediumint,
  articleId double,
  isHidden datetime,
  loginAttempts decimal,
  productCode binary
);

