CREATE TABLE user (
  id serial primary key,
  fileName enum,
  driverLicense mediumint,
  customerGroup bigint,
  mobileNumber bigint,
  jobTitle boolean,
  updatedAt set,
  signature smallint,
  id blob,
  incidentId blob,
  maxLimit set,
  batchId serial,
  height double,
  duration time,
  companyName varchar,
  referralCode timestamp,
  insertedAt varchar,
  memberCount datetime,
  score blob,
  rating time,
  dailyLimit smallint,
  cancelReason int,
  defaultValue blob,
  isBillable text,
  algorithm bit,
  deviceToken bit,
  connectionString mediumint,
  loginCount varchar,
  content timestamp,
  displayOrder tinyint,
  audioUrl time,
  gateId bigint
);

CREATE TABLE dim_inventory (
  id serial primary key,
  hashKey mediumint,
  category tinyint,
  type blob,
  education text,
  exportId varchar,
  attachmentUrl decimal,
  moveId boolean,
  bannerImage datetime,
  title int,
  contentType tinyint,
  companyName decimal,
  clockOut bigint,
  metaDescription bigint,
  moduleId time,
  depositAmount datetime,
  completedAt binary,
  username blob,
  downloadCount int,
  size varchar,
  albumId varchar,
  jobTitle bit,
  createdAt mediumint,
  authMethod double,
  guestId real,
  discount set,
  errorCode text
);

CREATE TABLE veruserseg (
  id serial primary key,
  groupName bit,
  customField2 geometry,
  enrollmentDate boolean,
  gameId datetime,
  cancelReason double,
  hourlyRate bigint,
  grade set,
  contactEmail real,
  fromDate int,
  isSystem int,
  isBillable point,
  companyName mediumint,
  sku float
);

CREATE TABLE transaction_2024 (
  id serial primary key,
  defaultValue boolean,
  discountCode enum,
  hourlyRate tinyint,
  cardNumber tinyint,
  rating binary,
  actionType timestamp,
  metaKeywords enum,
  completedAt double,
  balance date,
  insertedAt double,
  mobileNumber double,
  code smallint,
  clientId datetime,
  apiVersion set
);

CREATE TABLE config (
  id serial primary key,
  customField2 geometry,
  phone decimal,
  authToken point,
  completedAt date,
  courseId bigint,
  createdAt binary,
  referralCode serial,
  dataSource double,
  campaignId varchar,
  distributorId real,
  exchangeRate text,
  moveId blob,
  password mediumint,
  gameId serial,
  id point,
  configId enum,
  customField1 int,
  globalId real
);

CREATE TABLE config (
  id serial primary key,
  loginAttempts text,
  instructorId enum,
  keyId serial,
  birthDate bigint,
  coordinateX geometry,
  apiVersion double,
  globalId timestamp,
  deviceType bit,
  favoriteCount smallint,
  totalAmount double,
  formatType smallint,
  integrationId real,
  quantity float,
  managerId text,
  maxValue bit,
  gender int,
  maxLimit blob,
  metaDescription geometry
);

CREATE TABLE user (
  id serial primary key,
  accessLevel varchar,
  billingCycle binary,
  accountType bigint,
  menuId bit,
  type blob,
  creditCard smallint,
  validUntil set,
  height enum,
  deviceId tinyint,
  faxNumber real,
  costCenter real,
  size float,
  status blob,
  batchId bit,
  dialCode geometry,
  machineId text,
  folderPath float,
  token date,
  manufacturerId date,
  loginAttempts float,
  rating timestamp,
  fromDate binary,
  completionRate int,
  street tinyint,
  customerGroup bigint,
  tags blob
);

CREATE TABLE log_account_status (
  id serial primary key,
  distributorId time,
  chatId datetime,
  displayOrder smallint,
  localeId enum,
  apiVersion set,
  indexKey mediumint,
  expiryYear real,
  endPoint point,
  batchId datetime,
  cartId real,
  contactPhone bigint,
  filterType timestamp,
  lastName int,
  errorMessage set,
  enabledAt binary,
  content double,
  isRequired enum,
  loadTime binary,
  role geometry,
  bookingDate real,
  orderId bigint,
  attemptCount tinyint,
  isArchived smallint,
  memberCount datetime,
  cardHolder int,
  checkInTime datetime,
  iconPath point,
  cvv bigint,
  zipCode time,
  driverLicense geometry
);

CREATE TABLE audit (
  id serial primary key,
  departmentCode smallint,
  merchantId varchar,
  favoriteCount double,
  creditScore enum,
  fileName date,
  coordinateX double,
  phone blob,
  content boolean,
  industryType bit,
  duration date,
  birthDate float,
  startDate bigint,
  gateId bit
);

CREATE TABLE user (
  id serial primary key,
  metaDescription timestamp,
  content double,
  buildNumber datetime,
  merchantId tinyint,
  iconPath double,
  city geometry,
  category timestamp,
  frameRate serial,
  followCount varchar,
  blogId real,
  latitude varchar
);

CREATE TABLE tmp_config_info (
  id serial primary key,
  lastSeenAt set,
  rating text,
  dueDateAt tinyint,
  ipAddress timestamp,
  metaKeywords binary,
  isArchived time,
  meterNumber datetime,
  cardNumber enum,
  category decimal,
  importId smallint
);

CREATE TABLE dimauditinfo (
  id serial primary key,
  importId time,
  faxNumber blob,
  keywords time,
  filterType time,
  floorNumber datetime,
  zipCode timestamp,
  age double
);

CREATE TABLE cpy_config (
  id serial primary key,
  state int,
  filterType boolean,
  gender int,
  phone int,
  couponCode set,
  billingCycle serial
);

CREATE TABLE organizationinfo (
  id serial primary key,
  customField2 time,
  id binary,
  businessType time,
  listingId decimal,
  invoiceId boolean,
  expiryYear binary,
  birthDate blob
);

CREATE TABLE dim_config (
  id serial primary key,
  accountType point,
  fileSize bigint,
  configId datetime,
  feedbackId tinyint,
  status text,
  token text,
  attemptCount tinyint,
  password geometry,
  insertedAt bigint,
  longitude tinyint,
  isSystem set,
  incidentId smallint,
  activeDevices date,
  certificateId tinyint,
  accessLevel bit,
  latitude set,
  shippingAddress smallint,
  errorCode timestamp,
  discountCode blob,
  addressLine1 blob,
  cardHolder int,
  errorMessage datetime,
  uuid bigint,
  homePhone binary
);

CREATE TABLE record (
  id serial primary key,
  feedbackId smallint,
  gateId tinyint,
  password text
);

CREATE TABLE organization (
  id serial primary key,
  price bit,
  completedAt geometry,
  title geometry,
  street enum,
  password blob,
  macAddress float,
  metaDescription smallint,
  integrationId int,
  isLocked date,
  lastSeenAt float,
  employmentDate blob,
  createdAt blob,
  invoiceId mediumint,
  billingCycle binary,
  errorCode mediumint,
  entryPoint real,
  chatId double,
  meterNumber binary,
  isFeatured enum,
  jobTitle time,
  accountType blob,
  updatedAt date,
  downloadCount smallint,
  endDate real,
  address enum,
  category point,
  middleName real,
  isDefault datetime,
  inactiveAt date,
  linkId double,
  attemptCount tinyint
);

CREATE TABLE fact_config (
  id serial primary key,
  salary geometry,
  gender set,
  fingerprint decimal,
  authorId real,
  completedAt smallint,
  appVersion boolean,
  layerId enum,
  dashboardId decimal,
  latitude smallint,
  value set,
  metaTitle smallint,
  indexKey smallint,
  houseNumber smallint,
  errorCode time,
  authMethod decimal,
  flagged date,
  merchantId serial,
  dateFormat varchar,
  createdAt text,
  forwardTo enum,
  entryPoint date,
  deviceType tinyint
);

CREATE TABLE config (
  id serial primary key,
  state datetime,
  latitude point,
  filterType double,
  mapId double,
  formatType boolean,
  companyName mediumint,
  itemCount double,
  nickname geometry,
  indexKey real,
  customerId bit,
  cardNumber serial,
  locationId decimal,
  zipCode geometry,
  coordinateY decimal,
  coordinateX serial,
  group timestamp,
  geoLocation timestamp,
  bluetoothId bit,
  dealerId datetime,
  completedAt boolean,
  creditScore int,
  brandId boolean,
  isDefault time,
  licenseKey boolean,
  longitude real,
  thumbnail tinyint,
  title blob,
  expiryYear float,
  labelText text,
  employeeId serial,
  creditCard point
);

CREATE TABLE record_archive (
  id serial primary key,
  category text,
  fingerprint binary,
  authMethod binary,
  createdAt decimal,
  productCode point,
  displayOrder serial
);

CREATE TABLE log_record_seg (
  id serial primary key,
  cacheKey point,
  blogId double,
  avatar datetime,
  articleId real,
  appVersion blob,
  creditCard time,
  title float,
  category blob,
  birthDate real,
  frameRate enum,
  exchangeRate timestamp
);

CREATE TABLE ver_company_archive (
  id serial primary key,
  expiryYear bigint,
  loadTime boolean,
  handlerId tinyint,
  education datetime,
  cityName bit,
  clockOut float,
  age date,
  lastName varchar,
  deviceId blob,
  dashboardId blob,
  isActive enum,
  backupEmail tinyint,
  fingerprint serial,
  faxNumber real,
  floorNumber double
);

CREATE TABLE transaction (
  id serial primary key,
  browserType int,
  description set,
  macAddress int,
  menuId point,
  fileType blob,
  followCount varchar
);

CREATE TABLE customer_extra (
  id serial primary key,
  maritalStatus date,
  formatType int,
  maxLimit bit,
  balance boolean,
  expiryDate boolean,
  monthlyRate real,
  colorCode text,
  orderStatus binary,
  likeCount point,
  feedId serial,
  fromDate decimal,
  lastLoginAt set,
  addressLine2 tinyint,
  invoiceId timestamp,
  isRequired decimal,
  firstName datetime,
  url binary,
  fingerprint int,
  category bigint,
  documentId boolean,
  instanceId int,
  listId text,
  creditScore geometry,
  meterNumber set,
  keywords set,
  insertedAt datetime
);

CREATE TABLE stg_config (
  id serial primary key,
  dashboardId float,
  grade varchar,
  layerId decimal,
  lastName time,
  accountType decimal,
  exportId enum,
  lockoutEnd serial,
  errorCode real,
  authToken timestamp,
  department double,
  sessionId blob,
  jobTitle geometry,
  ipAddress decimal,
  cardHolder boolean,
  campaignId timestamp,
  channelId decimal,
  signature serial,
  incidentId time,
  joinDate real,
  isArchived binary,
  globalId enum,
  maxLimit double,
  currency serial,
  enabledAt binary,
  clockOut date,
  category real,
  employeeCode mediumint
);

CREATE TABLE company (
  id serial primary key,
  menuId point,
  modifiedAt smallint,
  city set,
  fileSize enum,
  isActive datetime,
  signature point,
  completedAt real,
  meterNumber point,
  isArchived bigint,
  bookingDate mediumint,
  batchId mediumint,
  unit tinyint,
  password geometry,
  entryPoint time,
  contentType serial,
  locationId double,
  insuranceId set,
  connectionString varchar
);

CREATE TABLE pub_company_status (
  id serial primary key,
  appVersion timestamp,
  actionType blob,
  insertedAt bigint,
  driverLicense text,
  cardHolder boolean,
  contactName decimal,
  attachmentUrl text,
  name date,
  birthDate geometry,
  depositAmount tinyint,
  isBillable enum,
  latitude geometry,
  isDefault tinyint,
  lockoutEnd text,
  expiryMonth date,
  documentId tinyint
);

CREATE TABLE inventory (
  id serial primary key,
  marketId geometry,
  expiryMonth tinyint,
  firstName enum
);

CREATE TABLE tmp_audit_legacy (
  id serial primary key,
  emailStatus date,
  authorId blob,
  locationId blob,
  managerId bit,
  coordinateY smallint,
  facilityId point,
  modifiedAt date,
  orderStatus tinyint,
  maxLimit int,
  accountNumber decimal
);

CREATE TABLE orderlog (
  id serial primary key,
  price boolean,
  modifiedAt decimal,
  contentType tinyint,
  importId smallint,
  fileHash binary,
  discountCode float,
  mainImage text,
  lockoutEnd geometry,
  coverImage point,
  category varchar,
  accountStatus decimal,
  actionType enum,
  listingId time,
  contactName double,
  weight date,
  group real,
  handlerId real,
  logLevel date,
  avatar float,
  languageCode mediumint,
  browserType time,
  monthlyRate double,
  isLocked double,
  favoriteCount time,
  loginCount bit,
  token datetime
);

CREATE TABLE transaction (
  id serial primary key,
  creditCard decimal,
  memberCount datetime,
  password blob,
  salary time,
  accountType tinyint,
  customField2 binary,
  isArchived time,
  managerId blob,
  inactiveAt float,
  grade mediumint,
  feedbackId mediumint,
  facilityId point,
  buildNumber int,
  phone tinyint,
  isDefault smallint,
  code decimal,
  batchId smallint,
  errorCode varchar,
  merchantId blob,
  isVerified real,
  customField1 int,
  priority timestamp,
  deactivatedAt text
);

CREATE TABLE tmprecord (
  id serial primary key,
  hashKey set,
  firstName timestamp,
  errorMessage varchar,
  colorCode mediumint,
  meterNumber decimal,
  dimension blob,
  version smallint,
  cacheKey time
);

CREATE TABLE tmpconfigv1 (
  id serial primary key,
  longitude int,
  editedAt bit,
  joinDate real,
  errorCode datetime,
  frameRate int,
  exchangeRate double,
  accountType bit,
  coordinateY set,
  licenseKey int,
  grade timestamp,
  isFeatured time,
  state varchar,
  businessType geometry,
  emailStatus double,
  agentId binary,
  bannerImage serial,
  filterType bigint,
  defaultValue int,
  deviceId tinyint,
  completionRate varchar,
  audioUrl binary,
  couponCode int,
  deletedAt blob,
  displayOrder geometry,
  orderId binary,
  isRequired tinyint,
  isDefault geometry,
  entityId datetime,
  feedbackId set,
  abandonedCartId bit
);

CREATE TABLE rel_company (
  id serial primary key,
  maritalStatus float,
  integrationId time,
  certificateId tinyint,
  gameId time,
  domainName datetime,
  departmentCode point,
  contactEmail float,
  errorMessage blob,
  orderStatus date,
  metaTitle float,
  accessLevel bigint,
  dataSource binary
);

CREATE TABLE tmpconfig (
  id serial primary key,
  creditLimit serial,
  startDate geometry,
  expiryMonth varchar,
  listId tinyint,
  deviceToken binary,
  email smallint,
  apiVersion serial,
  nickname bigint,
  analyticsId text,
  middleName double,
  content tinyint,
  country point,
  apiKey tinyint,
  completedAt point,
  authMethod enum,
  timezone decimal
);

CREATE TABLE ext_payment (
  id serial primary key,
  title set,
  facilityId date,
  category real,
  nickname tinyint,
  tags text,
  cvv geometry,
  documentId bit,
  claimId double,
  addressLine2 datetime,
  labelText smallint,
  accountType datetime,
  isPublic mediumint,
  coordinateY mediumint,
  apiKey float,
  email varchar,
  id boolean
);

CREATE TABLE paymentrel (
  id serial primary key,
  maskType mediumint,
  isPublic geometry,
  validUntil datetime,
  forwardTo enum,
  gateId int,
  companyId boolean,
  errorCode binary,
  sku set,
  filterType tinyint,
  languageCode bigint,
  flagged set,
  buildNumber bigint,
  importId time
);

CREATE TABLE company (
  id serial primary key,
  amount timestamp,
  metadata real,
  contactEmail date,
  awardDate tinyint,
  zipCode bit,
  authorId int,
  domainName geometry,
  mainImage enum,
  customerGroup date,
  documentId point,
  facilityId time,
  friendId double,
  value int,
  messageId bit,
  createdAt bigint,
  sessionId tinyint,
  eventDate text,
  authToken binary,
  companyName timestamp
);

CREATE TABLE core_order (
  id serial primary key,
  joinDate bigint,
  isDefault bit,
  insertedAt real,
  dependentId bit,
  gameId smallint,
  expiryDate date,
  mainImage serial,
  isPublic bit,
  guestId decimal,
  isArchived real,
  companyName geometry,
  deletedAt time,
  creditLimit serial,
  avatar tinyint,
  latitude bit,
  dailyLimit decimal,
  cvv time,
  employeeCode enum,
  friendId time,
  labelText time,
  fingerprint enum,
  employeeId time,
  isActive float,
  dueDateAt varchar,
  longitude boolean,
  loginCount tinyint,
  fontFamily binary,
  nickname date,
  audioUrl bit,
  ipAddress double,
  validUntil decimal
);

CREATE TABLE privrecordinfo (
  id serial primary key,
  employeeId timestamp,
  lastName int,
  description tinyint,
  budgetCode decimal,
  indexKey date,
  street smallint,
  isHidden set,
  latitude real,
  id date,
  countryCode real,
  blogId smallint,
  orderStatus blob,
  maskType datetime,
  age binary,
  menuId set,
  endPoint int,
  licenseKey serial,
  metaKeywords bigint
);

CREATE TABLE audit (
  id serial primary key,
  hourlyRate mediumint,
  cacheKey tinyint,
  lastLoginAt bigint,
  errorCode timestamp,
  employmentDate set,
  deviceId binary,
  coverImage smallint,
  apiKey point,
  geoLocation datetime,
  certificateId bigint,
  articleId point,
  brandId enum,
  insuranceId double,
  isDraft blob,
  indexKey bit,
  flagged tinyint,
  amount bit,
  content datetime,
  createdAt varchar,
  actionType binary,
  clientId tinyint,
  category date,
  attemptCount timestamp,
  orderId geometry,
  fileName datetime,
  accountType timestamp,
  token date
);

CREATE TABLE tbl_organization_archive (
  id serial primary key,
  mainImage date,
  weight set,
  integrationId point,
  birthDate timestamp,
  name tinyint,
  flagged varchar,
  salary bigint,
  mapId bigint,
  maxValue datetime,
  incidentId real,
  headerImage float,
  contractId real,
  errorCode time,
  fromDate decimal,
  longitude float,
  username datetime,
  joinDate bigint,
  cloudId smallint,
  audioUrl time,
  entryPoint double,
  configId double,
  employmentDate enum,
  chatId mediumint,
  languageCode real,
  fileType serial,
  content datetime,
  accountNumber boolean,
  documentId float,
  quantity timestamp,
  lastLoginAt serial
);

CREATE TABLE customer_new (
  id serial primary key,
  contactName point,
  exportId boolean,
  listingId point,
  isArchived mediumint,
  enabledAt float,
  completionRate geometry,
  enrollmentDate set,
  courseId datetime,
  currencyCode varchar,
  isHidden set,
  listId date
);

CREATE TABLE stg_order (
  id serial primary key,
  blogId double,
  isRequired varchar,
  street point,
  priority varchar,
  attachmentUrl timestamp,
  deviceId text,
  insertedAt int,
  albumId text,
  balance binary,
  awardDate varchar,
  metadata geometry,
  ipAddress point,
  localeId real,
  indexKey boolean,
  grade date,
  paymentMethod set,
  age geometry,
  deliveryDate binary,
  audioUrl double,
  authMethod bigint,
  dimension decimal,
  avatar int,
  checkInTime binary,
  companyName mediumint,
  documentId smallint,
  followCount mediumint,
  shippingAddress bit,
  copyRight double
);

CREATE TABLE audit (
  id serial primary key,
  longitude bit,
  loadTime date,
  updatedAt real,
  firstName int,
  companyName text,
  alertType mediumint,
  customerId decimal,
  distributorId bit,
  addressLine2 timestamp,
  errorMessage serial
);

CREATE TABLE core_organization_seg (
  id serial primary key,
  childId text,
  mimeType bit,
  deviceId real,
  authMethod binary,
  metadata decimal,
  isSystem timestamp,
  billingCycle blob,
  version real,
  amount bigint,
  fontSize decimal,
  attachmentUrl mediumint,
  quantity point,
  jobTitle double,
  lockoutEnd datetime,
  loginAttempts int,
  postalCode bit,
  fileName real,
  authorId real,
  maskType int,
  emailStatus datetime
);

CREATE TABLE dim_user_2025 (
  id serial primary key,
  createdAt tinyint,
  clientId date,
  audioUrl set,
  batchId smallint,
  editedAt mediumint,
  longitude real,
  completedAt real,
  contentType blob,
  incidentId bigint
);

CREATE TABLE transactionlegacy (
  id serial primary key,
  authToken enum,
  loginCount boolean,
  coordinateY time,
  metaDescription enum,
  accessLevel bigint,
  instanceId time,
  linkId tinyint,
  dateFormat blob,
  colorCode text,
  country float,
  quantity blob,
  tags double,
  listingId timestamp,
  role binary,
  lastSeenAt bit,
  menuId double,
  cloudId point,
  blogId bit,
  listId timestamp,
  group geometry,
  email point,
  bankAccount bit,
  companyName bigint,
  balance varchar,
  exportId serial,
  apiVersion blob,
  labelText serial
);

CREATE TABLE accountnotifications (
  id serial primary key,
  fromDate binary,
  comment int,
  completionRate real,
  loginAttempts real,
  linkId point,
  role time
);

CREATE TABLE apporder (
  id serial primary key,
  dependentId set,
  dateFormat double
);

