CREATE TABLE cpy_order_2024 (
  id serial primary key,
  creditLimit decimal,
  avatar text,
  token mediumint,
  maxValue timestamp,
  alertType set
);

CREATE TABLE pub_inventory_map (
  id serial primary key,
  agentId boolean,
  gender blob,
  isBillable set,
  earnedPoints smallint,
  value point,
  dealerId binary,
  emailStatus varchar,
  cityName datetime,
  isFeatured decimal,
  extractId decimal,
  authToken int,
  cardHolder int,
  role set,
  coordinateY mediumint,
  checkInTime decimal,
  mapId float,
  customField1 enum,
  foregroundColor boolean,
  filterType set,
  entryPoint time,
  height text,
  cacheKey timestamp,
  creditCard double,
  indexKey float
);

CREATE TABLE orderlegacy (
  id serial primary key,
  avatar float,
  password set,
  fromDate bigint,
  keywords serial,
  lastLoginAt enum,
  grade time,
  size time,
  firstName boolean,
  errorCode smallint,
  comment boolean,
  quantity geometry,
  incidentId binary,
  abandonedCartId real,
  insuranceId date,
  customField1 smallint,
  connectionString text,
  latitude decimal,
  shippingAddress blob,
  employeeCode bit,
  isSystem varchar,
  headerImage varchar,
  discountCode double,
  itemCount boolean,
  hiddenAt geometry,
  customerGroup serial,
  endPoint varchar,
  mainImage mediumint,
  awardDate decimal
);

CREATE TABLE config (
  id serial primary key,
  url mediumint,
  completionRate float,
  ipAddress float,
  salary boolean,
  albumId varchar,
  isArchived tinyint,
  createdAt binary,
  name float,
  insertedAt set,
  fingerprint date,
  coordinateY mediumint,
  accountNumber float,
  value float,
  longitude point,
  tags time,
  token datetime,
  street date,
  size text,
  status decimal,
  facilityId enum,
  departmentCode binary,
  articleId blob,
  amount set,
  browserType date,
  importId enum,
  isDefault datetime
);

CREATE TABLE record_legacy (
  id serial primary key,
  channelId time,
  geoLocation bigint,
  meterNumber timestamp,
  joinDate decimal,
  country float,
  couponCode varchar,
  forwardTo set,
  tags blob,
  hostName geometry,
  headerImage bigint,
  exchangeRate binary,
  foregroundColor date,
  orderStatus timestamp,
  facilityId mediumint,
  colorCode serial,
  hourlyRate bigint,
  isPublic point,
  updatedAt set,
  browserType blob,
  attachmentUrl set,
  price bit
);

CREATE TABLE extproduct (
  id serial primary key,
  accessLevel mediumint,
  isFeatured date,
  maskType boolean,
  browserType point,
  instanceId enum,
  dialCode serial,
  birthDate time,
  faxNumber tinyint,
  gameId tinyint,
  sessionId serial,
  description int,
  isAdmin mediumint,
  campaignId smallint,
  endDate varchar,
  industryType varchar,
  articleId bigint,
  listingId decimal,
  nickname smallint,
  loadTime bit
);

CREATE TABLE organization (
  id serial primary key,
  analyticsId float,
  isDeleted mediumint,
  minValue decimal,
  gender enum,
  itemCount set,
  dateFormat serial,
  price smallint,
  metaDescription real,
  guestId serial,
  machineId set,
  priority double,
  isPublic serial,
  isHidden timestamp,
  menuId datetime,
  backupEmail boolean,
  maritalStatus text,
  group datetime,
  linkId text,
  loginAttempts date,
  role double,
  sku float,
  billingFrequency geometry,
  dataSource decimal,
  coverImage decimal,
  currencyCode point,
  instructorId enum,
  copyRight int
);

CREATE TABLE inventory (
  id serial primary key,
  avatar serial,
  quantity smallint,
  fontFamily smallint,
  isFeatured float,
  completionRate varchar,
  code tinyint,
  adminNotes int,
  thumbnail time,
  longitude int,
  algorithm real,
  browserType time,
  customField2 datetime,
  apiVersion decimal,
  maritalStatus mediumint,
  companyName point,
  addressLine1 enum,
  facilityId smallint,
  dueDateAt real,
  uuid real,
  entryPoint enum,
  content date,
  title bit,
  lockoutEnd bigint,
  dependentId real,
  jobTitle geometry,
  checkOutTime decimal,
  birthDate date,
  dataSource bigint,
  addressLine2 decimal
);

CREATE TABLE inventory_v2 (
  id serial primary key,
  username geometry,
  childId point,
  amount timestamp,
  batchId geometry,
  guestId serial,
  customerId boolean,
  eventDate real,
  avatar enum,
  minLimit point,
  tags smallint,
  contentType date,
  clockOut float,
  size varchar,
  code bigint,
  earnedPoints text,
  groupName boolean,
  latitude bit,
  title time,
  customField1 point,
  editedAt timestamp,
  logLevel real,
  fingerprint geometry,
  category decimal,
  customField2 real,
  cityName smallint,
  errorMessage tinyint,
  price set
);

CREATE TABLE dst_organization_legacy (
  id serial primary key,
  integrationId point,
  localeId bigint,
  id real,
  certificateId mediumint,
  frameRate time,
  enabledAt datetime,
  category int,
  clockIn bigint,
  nickname time,
  totalAmount timestamp,
  priority text
);

CREATE TABLE tmp_account_hist (
  id serial primary key,
  minValue date,
  contactPhone text,
  machineId serial,
  customerGroup float,
  handlerId set,
  apiVersion set,
  role set,
  comment mediumint,
  meterNumber varchar,
  creditLimit blob,
  facilityId serial,
  billingFrequency mediumint,
  type time,
  latitude bit
);

CREATE TABLE account (
  id serial primary key,
  fileType datetime,
  distributorId enum,
  dialCode boolean,
  paymentMethod text,
  managerId text,
  flagged bigint,
  attachmentUrl real,
  nickname mediumint,
  minLimit decimal,
  contactPhone varchar,
  id boolean,
  maxValue bit,
  apiKey int,
  fontFamily tinyint,
  blogId bit,
  licenseKey set,
  isActive set,
  layerId boolean,
  employeeId int
);

CREATE TABLE account (
  id serial primary key,
  discountCode double,
  name tinyint,
  createdAt set,
  frameRate smallint,
  comment point,
  countryCode bit,
  fontFamily date,
  customField1 boolean,
  mapId enum,
  phone bigint,
  machineId date,
  latitude varchar,
  employeeId decimal,
  distributorId serial,
  unit varchar,
  isRequired binary,
  tags boolean,
  mimeType time,
  foregroundColor point,
  courseId point,
  currency text,
  configId bigint,
  isAdmin geometry,
  deviceType binary,
  houseNumber datetime,
  exportId date,
  title bigint,
  flagged geometry,
  longitude binary,
  gateId text,
  isEnabled double
);

CREATE TABLE config (
  id serial primary key,
  customerId bigint,
  address double,
  department set,
  createdAt double,
  paymentMethod float,
  metaDescription enum,
  marketId blob,
  gender real,
  menuId timestamp,
  state point,
  accountType enum,
  isVerified double,
  jobTitle varchar,
  dateFormat decimal,
  creditLimit serial,
  balance blob,
  latitude text,
  value int
);

CREATE TABLE record (
  id serial primary key,
  password timestamp,
  avatar decimal,
  authorId time,
  followCount mediumint,
  algorithm serial,
  entityId varchar,
  floorNumber mediumint,
  cancelReason enum,
  batchId timestamp,
  comment real,
  dateFormat geometry,
  gender smallint,
  token serial,
  companyLogo mediumint,
  feedbackId point,
  id decimal,
  marketId float,
  locationId varchar,
  keywords set,
  isFeatured geometry,
  depositAmount bigint,
  linkId float,
  sessionId tinyint,
  errorCode tinyint,
  clientId timestamp,
  hourlyRate mediumint,
  phone double,
  customField1 double
);

CREATE TABLE record (
  id serial primary key,
  keyId tinyint,
  enabledAt bigint,
  hourlyRate double
);

CREATE TABLE inventory (
  id serial primary key,
  creditCard point,
  locationId int,
  latitude timestamp,
  country date,
  employeeId datetime,
  orderId mediumint,
  ipAddress boolean,
  moduleId real,
  middleName bit,
  isFeatured enum,
  addressLine2 double,
  state mediumint,
  status varchar,
  email tinyint,
  homePhone serial,
  minValue bigint,
  city enum,
  name blob,
  errorMessage set,
  lockoutEnd float,
  authMethod geometry
);

CREATE TABLE olk_customer_new (
  id serial primary key,
  guestId float,
  comment enum,
  languageCode enum,
  contractId smallint,
  isDeleted decimal,
  companyId enum,
  eventDate timestamp,
  coordinateY enum,
  analyticsId real,
  businessType enum,
  houseNumber smallint,
  isHidden double,
  employmentDate int,
  creditCard text,
  accessLevel time,
  postalCode bit,
  keyId geometry,
  deactivatedAt time
);

CREATE TABLE account (
  id serial primary key,
  deletedAt int,
  lastLoginAt serial,
  cityName set,
  articleId float,
  lastSeenAt boolean,
  lockoutEnd int,
  signature smallint,
  backupEmail decimal,
  frameRate enum,
  dependentId boolean,
  city enum,
  moduleId point,
  amount geometry
);

CREATE TABLE core_customer (
  id serial primary key,
  email geometry,
  gender tinyint,
  customField1 date,
  title smallint,
  content date,
  group decimal,
  accessLevel geometry
);

CREATE TABLE inventory (
  id serial primary key,
  productCode real,
  dimension enum,
  id float,
  comment smallint,
  department text,
  companyLogo binary,
  name set,
  dueDateAt tinyint,
  mainImage boolean,
  signature boolean
);

CREATE TABLE cpy_inventory (
  id serial primary key,
  agentId smallint,
  productCode serial,
  displayOrder time,
  bookingDate float,
  weight blob,
  employmentDate datetime,
  budgetCode set,
  driverLicense boolean,
  deactivatedAt serial,
  exportId boolean,
  channelId geometry,
  address set,
  checkOutTime text,
  buildNumber serial,
  homePhone blob,
  locationId decimal,
  merchantId varchar,
  indexKey smallint,
  hostName text,
  mapId bigint,
  name point
);

CREATE TABLE customer (
  id serial primary key,
  enabledAt enum,
  fingerprint time,
  password set,
  displayName serial,
  createdAt int,
  handlerId int,
  age real,
  brandId date,
  indexKey set,
  eventDate real,
  lastLoginAt date,
  expiryYear boolean,
  localeId bit,
  status timestamp,
  authToken binary,
  fileType enum,
  name float,
  budgetCode real,
  accountType tinyint,
  amount enum,
  maxValue smallint,
  countryCode real
);

CREATE TABLE company (
  id serial primary key,
  loginAttempts timestamp,
  productCode point,
  dateFormat serial,
  isDeleted set,
  entryPoint smallint,
  customerGroup real,
  isVerified int,
  token date,
  browserType int
);

CREATE TABLE olk_record_data (
  id serial primary key,
  completionRate time,
  algorithm bigint,
  displayName tinyint,
  defaultValue point,
  messageId varchar,
  authorId datetime,
  albumId tinyint,
  longitude serial,
  maxValue serial,
  defaultLang point,
  fileHash point,
  type bit,
  certificateId bit,
  checkOutTime real,
  colorCode set,
  marketId smallint,
  salary set,
  status bigint,
  employmentDate real,
  ipAddress date,
  entryPoint time,
  group geometry,
  followCount binary,
  currency double,
  cardNumber text,
  orderId varchar,
  accountType smallint,
  birthDate serial,
  tags float,
  clientId timestamp,
  validUntil text
);

CREATE TABLE product (
  id serial primary key,
  nickname bigint,
  accountNumber enum,
  cardNumber bigint,
  lockoutEnd float,
  listId varchar,
  customerId binary,
  password bigint,
  inactiveAt smallint
);

CREATE TABLE priv_config_status_temp (
  id serial primary key,
  authToken float,
  folderPath date
);

CREATE TABLE tmp_company_log (
  id serial primary key,
  companyId bit,
  forwardTo enum,
  maxValue date,
  email point
);

CREATE TABLE account_notifications_2024 (
  id serial primary key,
  coverImage smallint,
  addressLine1 smallint,
  zipCode datetime,
  checkOutTime binary,
  longitude float,
  exportId datetime,
  managerId double,
  browserType tinyint,
  earnedPoints text,
  group time,
  deviceType mediumint,
  accessLevel geometry,
  gender timestamp,
  albumId int,
  feedId float,
  password timestamp,
  bankAccount time,
  address set,
  adminNotes mediumint,
  ipAddress text,
  createdAt time
);

CREATE TABLE config (
  id serial primary key,
  isDeleted double,
  cardNumber boolean,
  dailyLimit double,
  loginCount enum,
  flagged double,
  lockoutEnd timestamp,
  country real,
  coordinateX bigint
);

CREATE TABLE product (
  id serial primary key,
  likeCount time,
  moduleId set,
  instructorId point,
  channelId varchar,
  isActive decimal,
  contactPhone datetime,
  entryPoint blob,
  favoriteCount date,
  username bit
);

CREATE TABLE company (
  id serial primary key,
  editedAt bigint,
  documentId mediumint,
  addressLine2 binary,
  rating boolean,
  metaTitle enum,
  fileName point,
  industryType blob,
  headerImage tinyint,
  defaultValue bigint,
  emergencyContact time,
  minLimit binary,
  accessLevel int,
  id varchar,
  createdAt geometry
);

CREATE TABLE pub_payment (
  id serial primary key,
  friendId date,
  contentType blob,
  keywords double,
  articleId bit,
  appVersion set,
  quantity bit,
  brandId bigint,
  category geometry,
  amount date,
  comment binary,
  updatedAt serial,
  marketId boolean,
  gameId bigint,
  fingerprint blob,
  hashKey bit,
  contactName smallint
);

CREATE TABLE dimorder (
  id serial primary key,
  coverImage timestamp,
  type int,
  endPoint smallint,
  insuranceId decimal,
  isHidden mediumint,
  frameRate time,
  headerImage varchar,
  longitude set,
  levelId geometry,
  itemCount text,
  isLocked double,
  indexKey varchar,
  accountNumber binary,
  faxNumber double,
  depositAmount timestamp,
  clockIn int,
  createdAt mediumint,
  endDate date,
  timezone mediumint,
  taxRate date,
  abandonedCartId text,
  loginAttempts time,
  totalAmount decimal,
  friendId timestamp,
  clientId time,
  age date,
  size double,
  extractId date
);

CREATE TABLE pub_audit (
  id serial primary key,
  price text,
  createdAt varchar,
  keywords tinyint,
  cardNumber float,
  channelId date,
  meterNumber bit,
  isEnabled serial,
  foregroundColor boolean,
  childId mediumint,
  accountType blob,
  monthlyRate float,
  username smallint,
  errorMessage tinyint,
  latitude bit,
  invoiceId date,
  industryType bigint,
  discount smallint,
  type point,
  companyName tinyint,
  macAddress float,
  floorNumber enum,
  insertedAt smallint,
  lastLoginAt point,
  salary time
);

CREATE TABLE pub_user (
  id serial primary key,
  firmwareVersion enum,
  version datetime,
  blogId serial,
  clientId set,
  customField1 real,
  zipCode binary,
  taxRate date,
  loginAttempts float,
  foregroundColor timestamp,
  comment double,
  deviceToken set,
  adminNotes mediumint,
  signature set,
  authMethod text,
  authorId date,
  minLimit time,
  endPoint bit,
  companyId time,
  token bit,
  dimension set,
  insertedAt real,
  url boolean,
  currency double,
  indexKey time,
  password int,
  entityId date,
  rating float,
  companyName varchar
);

CREATE TABLE dst_audit (
  id serial primary key,
  accountStatus date,
  address smallint,
  maxLimit date,
  maskType bigint,
  avatar geometry,
  folderPath time,
  activeDevices date,
  brandId mediumint,
  gender mediumint,
  updatedAt smallint,
  articleId float,
  gateId real,
  id enum,
  value decimal,
  instanceId int,
  backupEmail time,
  discount int,
  incidentId varchar,
  dependentId set,
  hourlyRate blob,
  country timestamp,
  status geometry,
  cardHolder float,
  customField2 text,
  title float,
  contactPhone point,
  email geometry,
  indexKey bigint,
  floorNumber smallint
);

CREATE TABLE log_payment_temp (
  id serial primary key,
  title real,
  merchantId bit,
  isVerified enum,
  gameId set,
  mobileNumber blob,
  fingerprint serial
);

CREATE TABLE config (
  id serial primary key,
  keywords blob,
  algorithm mediumint,
  content mediumint,
  category tinyint,
  gameId enum,
  loadTime serial,
  endDate geometry,
  isEnabled set,
  loginCount geometry,
  isAdmin varchar,
  department point,
  minLimit date,
  favoriteCount set,
  discount double,
  isHidden serial,
  longitude double,
  checkOutTime bit,
  employeeId mediumint,
  campaignId date,
  meterNumber bit,
  languageCode point,
  buildNumber real,
  actionType smallint
);

CREATE TABLE paymentnotifications (
  id serial primary key,
  distributorId float,
  faxNumber bit,
  middleName int,
  actionType int,
  displayName geometry,
  dashboardId float,
  isAdmin geometry,
  emergencyContact int,
  age text,
  colorCode bigint,
  lockoutEnd float,
  addressLine2 geometry,
  channelId smallint,
  clockIn varchar,
  integrationId varchar,
  validUntil point,
  phone boolean
);

CREATE TABLE app_product_v2 (
  id serial primary key,
  authorId timestamp,
  accessLevel float,
  shippingAddress text,
  houseNumber varchar,
  isAdmin blob,
  dialCode geometry,
  merchantId date,
  filterType bit,
  iconPath tinyint,
  employeeCode double,
  itemCount point,
  maskType bigint,
  clientId time,
  code timestamp,
  isSystem serial,
  coordinateX boolean,
  insuranceId serial,
  amount geometry,
  gameId point
);

CREATE TABLE payment (
  id serial primary key,
  phone bit,
  dealerId set,
  isLocked tinyint,
  localeId geometry,
  moveId boolean
);

CREATE TABLE organization (
  id serial primary key,
  integrationId varchar,
  favoriteCount mediumint,
  contentType tinyint,
  priority boolean,
  country enum,
  hostName mediumint,
  dialCode timestamp,
  folderPath decimal,
  birthDate time,
  hourlyRate binary,
  localeId bigint,
  status time,
  name point,
  amount datetime
);

CREATE TABLE vwinventorytype (
  id serial primary key,
  cancelReason set,
  updatedAt tinyint,
  tags varchar,
  exportId real,
  street timestamp,
  creditCard enum,
  mobileNumber double,
  analyticsId blob,
  isEnabled bigint,
  cardNumber enum,
  isLocked timestamp,
  entityId varchar
);

CREATE TABLE ver_company_2025 (
  id serial primary key,
  signature time,
  facilityId mediumint,
  floorNumber binary,
  fileHash timestamp,
  lastSeenAt serial,
  loginCount point,
  tags blob,
  fileType point,
  status bigint,
  isDefault bigint,
  duration boolean,
  industryType decimal,
  name time,
  unit text
);

CREATE TABLE priv_payment (
  id serial primary key,
  email smallint,
  completionRate mediumint,
  signature enum,
  price time,
  quantity binary,
  creditLimit datetime,
  defaultLang bit,
  chargeId boolean,
  companyLogo bigint,
  loginCount time,
  category mediumint,
  score mediumint,
  checkOutTime timestamp,
  meterNumber datetime,
  activeDevices time,
  employmentDate bigint,
  companyName float,
  endDate float,
  maxLimit timestamp,
  isRequired real,
  industryType timestamp,
  id mediumint,
  forwardTo time,
  depositAmount double,
  avatar smallint,
  linkId double,
  logLevel float,
  group date
);

CREATE TABLE src_record (
  id serial primary key,
  completedAt real,
  balance text,
  importId real,
  category boolean,
  businessType double,
  activeDevices timestamp,
  localeId int,
  browserType text,
  signature varchar,
  contactPhone time,
  gameId text,
  driverLicense blob,
  exportId datetime,
  code blob,
  username decimal,
  expiryDate serial,
  dealerId smallint,
  errorMessage float,
  addressLine1 double,
  ipAddress mediumint,
  longitude real
);

CREATE TABLE sys_organization_legacy (
  id serial primary key,
  version point,
  deviceId date,
  analyticsId set,
  description float,
  customerGroup point,
  brandId binary,
  metadata float,
  lockoutEnd blob,
  contentType bigint,
  lastLoginAt bit,
  avatar text,
  minLimit bit,
  filterType double
);

CREATE TABLE organization_temp (
  id serial primary key,
  layerId set,
  isLocked timestamp,
  languageCode blob,
  globalId blob,
  emergencyContact time,
  hourlyRate double,
  billingFrequency set,
  discount time,
  listingId enum,
  isDeleted smallint,
  claimId real,
  creditScore datetime,
  isSystem point
);

CREATE TABLE verorganizationmetatemp (
  id serial primary key,
  insuranceId time,
  formatType date,
  updatedAt geometry,
  instanceId point,
  managerId blob,
  size float,
  alertType float,
  isAdmin tinyint,
  fileType serial,
  keyId boolean,
  avatar varchar,
  entityId float,
  url enum,
  loadTime date,
  role point,
  appVersion time,
  deletedAt decimal,
  description serial,
  contentType blob,
  insertedAt double,
  phone bigint,
  title float,
  minValue decimal,
  isLocked enum,
  channelId set,
  expiryMonth mediumint,
  longitude geometry,
  cardHolder timestamp,
  postalCode tinyint,
  cardNumber int,
  fileName binary
);

