CREATE TABLE privrecord (
  id serial primary key,
  amount decimal,
  age text,
  signature datetime,
  merchantId date,
  backupEmail decimal,
  contractId bit,
  exchangeRate smallint,
  creditScore varchar,
  clientId float,
  avatar int,
  documentId enum,
  expiryMonth date,
  dailyLimit geometry,
  childId time,
  hourlyRate int,
  audioUrl datetime,
  invoiceId bit
);

CREATE TABLE account_legacy (
  id serial primary key,
  algorithm double,
  priority int,
  type real,
  countryCode tinyint,
  enrollmentDate serial,
  fileType text,
  rating int,
  folderPath boolean,
  middleName varchar
);

CREATE TABLE account_2024 (
  id serial primary key,
  courseId date,
  accountNumber enum,
  earnedPoints time,
  street text,
  country real,
  instructorId float,
  expiryYear bigint,
  displayName tinyint
);

CREATE TABLE aggproduct (
  id serial primary key,
  audioUrl serial,
  coverImage int,
  firmwareVersion geometry,
  maskType bigint,
  blogId serial,
  companyName bigint,
  forwardTo double,
  customField2 text,
  title boolean,
  modifiedAt date,
  folderPath point,
  isEnabled int,
  cancelReason geometry,
  contractId decimal,
  chatId smallint,
  address mediumint,
  size binary,
  costCenter bit,
  clockIn bigint,
  buildNumber varchar,
  cardHolder varchar,
  coordinateY varchar,
  budgetCode date
);

CREATE TABLE inventory_v1 (
  id serial primary key,
  certificateId time,
  meterNumber double,
  backupEmail date,
  fromDate bit,
  startDate binary,
  longitude text,
  authToken enum,
  firmwareVersion point,
  token binary,
  frameRate real,
  emailStatus varchar,
  rating text,
  phone varchar,
  name mediumint,
  isHidden serial,
  customerGroup decimal,
  metaTitle smallint,
  childId geometry,
  handlerId text,
  billingCycle text,
  brandId float,
  integrationId float,
  completionRate float,
  creditCard double,
  linkId point,
  monthlyRate serial,
  formatType point,
  productCode time,
  employeeId smallint,
  displayOrder text
);

CREATE TABLE dst_record (
  id serial primary key,
  updatedAt geometry,
  isFeatured float,
  downloadCount smallint,
  alertType timestamp,
  bookingDate decimal,
  labelText smallint,
  bannerImage date,
  isLocked geometry,
  password text,
  accountNumber varchar,
  importId text,
  customerId double,
  startDate time,
  fileType smallint,
  distributorId bigint,
  accountType mediumint
);

CREATE TABLE tmptransaction (
  id serial primary key,
  emailStatus varchar,
  group text,
  address point,
  fileHash double,
  companyLogo set,
  locationId geometry,
  incidentId binary,
  name float,
  completedAt time
);

CREATE TABLE order (
  id serial primary key,
  thumbnail point,
  name text,
  coordinateX set,
  ipAddress date,
  errorMessage point,
  countryCode smallint
);

CREATE TABLE organization_extra (
  id serial primary key,
  accountStatus bigint,
  content timestamp,
  isActive binary,
  country set,
  loginAttempts float,
  connectionString blob,
  city int,
  billingFrequency mediumint,
  latitude smallint,
  taxRate tinyint,
  balance bit,
  loginCount blob,
  url tinyint,
  backupEmail timestamp,
  homePhone smallint,
  chargeId point,
  currencyCode double
);

CREATE TABLE app_inventory_new (
  id serial primary key,
  folderPath tinyint,
  minLimit point,
  phone point,
  orderStatus time,
  createdAt varchar,
  id date,
  gameId binary,
  entryPoint text,
  manufacturerId mediumint,
  category tinyint,
  employeeCode date,
  adminNotes bigint,
  fileSize tinyint,
  tags blob,
  accountType time,
  isEnabled serial,
  layerId datetime,
  address enum,
  lastName set,
  linkId binary,
  paymentMethod point,
  emailStatus time,
  budgetCode mediumint,
  fromDate datetime,
  code date,
  token decimal,
  endPoint decimal,
  algorithm real,
  updatedAt mediumint,
  deviceId int
);

CREATE TABLE user (
  id serial primary key,
  creditScore date,
  longitude tinyint,
  password boolean,
  bannerImage boolean,
  downloadCount mediumint,
  coverImage date,
  accountStatus bigint,
  completedAt geometry,
  isDraft binary,
  moduleId tinyint,
  status float,
  fileName serial,
  height tinyint,
  domainName varchar,
  latitude timestamp,
  geoLocation mediumint,
  sessionId binary,
  currency geometry,
  memberCount bit,
  messageId real
);

CREATE TABLE record_legacy (
  id serial primary key,
  formatType real,
  browserType int,
  bookingDate timestamp,
  firstName smallint,
  description smallint,
  isVerified smallint,
  creditScore date,
  metaKeywords boolean,
  downloadCount boolean,
  dailyLimit float,
  birthDate timestamp,
  amount time
);

CREATE TABLE dim_audit (
  id serial primary key,
  price double,
  contactName text,
  category double,
  salary bit,
  feedbackId real,
  gateId varchar,
  age text,
  ipAddress varchar,
  adminNotes geometry,
  gender tinyint,
  customerGroup bigint,
  configId double,
  isDeleted time,
  isAdmin blob,
  houseNumber timestamp,
  countryCode mediumint,
  isPublic point,
  maritalStatus float,
  endPoint tinyint,
  fileSize mediumint,
  machineId binary,
  joinDate bigint
);

CREATE TABLE rel_company_seg_new (
  id serial primary key,
  bookingDate bigint,
  metadata enum,
  discountCode geometry,
  loginAttempts varchar,
  longitude double,
  grade text,
  endDate varchar,
  tags date
);

CREATE TABLE tmp_user (
  id serial primary key,
  mobileNumber set,
  customField2 bigint,
  dialCode tinyint,
  sessionId bit,
  apiKey blob,
  checkOutTime enum,
  frameRate serial,
  messageId decimal,
  isFeatured date,
  memberCount geometry,
  email varchar,
  age bigint,
  checkInTime text,
  code binary,
  linkId serial,
  contentType mediumint,
  avatar boolean,
  manufacturerId blob,
  companyLogo text,
  amount point,
  isDefault double,
  fingerprint decimal,
  backupEmail bigint,
  cacheKey set,
  lastSeenAt set,
  middleName point,
  longitude double,
  friendId text,
  description boolean,
  priority date
);

CREATE TABLE pubinventoryseg (
  id serial primary key,
  name text,
  listingId geometry,
  browserType mediumint,
  dailyLimit timestamp,
  createdAt varchar,
  contentType varchar,
  referralCode point,
  invoiceId time,
  orderId real,
  cardHolder geometry,
  isSystem smallint
);

CREATE TABLE organization_status (
  id serial primary key,
  customField2 decimal,
  childId decimal,
  title real,
  isDeleted point,
  modifiedAt tinyint,
  grade blob,
  billingCycle real,
  menuId smallint,
  deliveryDate real,
  metaDescription varchar,
  category geometry,
  emergencyContact real,
  createdAt decimal,
  distributorId text,
  adminNotes smallint,
  completedAt serial
);

CREATE TABLE account_temp (
  id serial primary key,
  clientId int,
  username bit,
  minValue int,
  emailStatus timestamp,
  maxLimit tinyint,
  likeCount enum,
  deviceId mediumint,
  indexKey boolean,
  locationId bigint,
  dependentId date,
  eventDate bit,
  cityName float,
  mimeType text,
  costCenter geometry,
  instructorId enum,
  group bit,
  fromDate bigint,
  country date,
  expiryYear mediumint,
  headerImage geometry,
  moduleId varchar,
  endDate float,
  description time,
  lastSeenAt binary,
  comment float
);

CREATE TABLE account_new (
  id serial primary key,
  customField2 date,
  feedId time,
  floorNumber bit,
  gameId decimal,
  name set,
  birthDate blob,
  analyticsId double,
  machineId boolean,
  lockoutEnd text,
  score set,
  isLocked smallint,
  timezone point,
  status mediumint,
  maritalStatus date,
  contractId point,
  accountStatus enum,
  isDeleted timestamp,
  group float,
  cartId geometry,
  globalId boolean,
  metaTitle varchar,
  displayOrder bigint,
  thumbnail decimal,
  height bit
);

CREATE TABLE inventory_v1 (
  id serial primary key,
  deactivatedAt double,
  companyId bigint,
  isVerified timestamp,
  adminNotes time,
  startDate tinyint,
  errorMessage binary,
  modifiedAt text,
  lastName serial,
  signature float,
  houseNumber mediumint,
  category set,
  locationId double,
  address blob,
  fileSize boolean,
  downloadCount blob,
  blogId timestamp
);

CREATE TABLE stg_account_info (
  id serial primary key,
  accountType bigint,
  token boolean,
  category boolean,
  createdAt geometry,
  age set,
  sessionId varchar,
  cloudId float,
  height blob,
  metaDescription double,
  group int,
  errorCode serial,
  listId datetime,
  hostName binary,
  deliveryDate double,
  contractId bit,
  country real,
  likeCount bit,
  contactName geometry,
  priority time,
  name bit
);

CREATE TABLE record (
  id serial primary key,
  dimension timestamp,
  price set,
  endPoint text,
  address mediumint,
  accessLevel decimal,
  apiKey real,
  createdAt blob,
  couponCode time,
  gameId date,
  algorithm int,
  chargeId int,
  mimeType boolean,
  feedbackId blob,
  employmentDate int,
  insertedAt date,
  balance date,
  dealerId smallint,
  expiryMonth bit,
  minValue int,
  accountType float,
  deliveryDate mediumint,
  clockOut boolean,
  inactiveAt varchar,
  fontFamily text,
  lockoutEnd real,
  employeeCode double,
  likeCount int,
  completedAt time
);

CREATE TABLE ver_account_status (
  id serial primary key,
  faxNumber decimal,
  activeDevices set,
  keyId mediumint,
  address smallint,
  middleName int,
  abandonedCartId tinyint,
  timezone blob,
  logLevel serial
);

CREATE TABLE customer (
  id serial primary key,
  depositAmount float,
  accountNumber bigint,
  code tinyint,
  lastLoginAt mediumint,
  creditCard float,
  signature tinyint,
  gender bit,
  activeDevices double,
  amount real,
  maxValue geometry,
  extractId bit,
  dimension smallint,
  errorMessage serial,
  inactiveAt boolean,
  isDeleted int,
  isBillable bigint,
  bookingDate timestamp,
  courseId blob,
  clockIn datetime,
  value geometry,
  distributorId set,
  birthDate blob,
  copyRight time,
  postalCode date,
  importId point
);

CREATE TABLE record_2025 (
  id serial primary key,
  listingId decimal,
  name point,
  emailStatus timestamp,
  brandId smallint,
  orderStatus varchar,
  creditLimit geometry,
  alertType set,
  addressLine2 bigint,
  couponCode real,
  enabledAt mediumint
);

CREATE TABLE companymeta (
  id serial primary key,
  cardHolder int,
  contactName real,
  defaultValue real,
  channelId date,
  contentType mediumint,
  size blob,
  enabledAt real,
  endPoint enum,
  fileHash boolean,
  dimension timestamp,
  blogId varchar,
  timezone smallint,
  joinDate mediumint,
  followCount timestamp
);

CREATE TABLE dst_config (
  id serial primary key,
  url point,
  documentId time,
  billingFrequency varchar,
  comment int,
  exportId tinyint,
  type mediumint,
  macAddress bit,
  email blob,
  machineId real,
  loadTime mediumint,
  displayOrder mediumint,
  dueDateAt float,
  enrollmentDate varchar,
  amount date,
  listId text,
  articleId point,
  totalAmount enum,
  phone geometry,
  code boolean,
  connectionString double,
  name text
);

CREATE TABLE tmpuserdata (
  id serial primary key,
  group datetime,
  entryPoint blob,
  fileName point,
  accountNumber smallint,
  enrollmentDate bigint,
  displayName time,
  lastName set
);

CREATE TABLE organizationdata2025 (
  id serial primary key,
  score date,
  departmentCode enum,
  url enum,
  isHidden bigint,
  phone datetime,
  endDate double,
  isRequired enum,
  distributorId double,
  isArchived point,
  duration double
);

CREATE TABLE src_audit (
  id serial primary key,
  createdAt set,
  friendId binary,
  endDate real,
  favoriteCount smallint,
  clockOut binary,
  coordinateY bit,
  deviceId blob,
  logLevel timestamp,
  age smallint,
  driverLicense real,
  flagged datetime,
  earnedPoints timestamp,
  address boolean,
  thumbnail int,
  productCode serial,
  firmwareVersion date,
  group int,
  dependentId binary,
  alertType text,
  mobileNumber timestamp,
  foregroundColor enum,
  startDate double,
  documentId set,
  dimension binary,
  marketId time,
  cardNumber decimal,
  emergencyContact time
);

CREATE TABLE inventory_temp (
  id serial primary key,
  ipAddress tinyint,
  mobileNumber date,
  feedId binary,
  certificateId tinyint,
  exchangeRate enum,
  customField2 float,
  maxValue geometry,
  abandonedCartId float,
  dialCode time,
  nickname real,
  isDraft point,
  labelText serial,
  token set,
  comment double,
  discount mediumint
);

CREATE TABLE dim_audit_div (
  id serial primary key,
  monthlyRate int,
  attachmentUrl boolean,
  creditLimit real,
  education blob,
  maxLimit blob,
  gender point,
  exchangeRate serial,
  category datetime,
  name binary,
  defaultLang tinyint,
  description bigint,
  folderPath date,
  email varchar,
  discountCode float,
  dependentId float,
  amount date,
  companyName bigint,
  state varchar,
  checkOutTime int,
  emergencyContact real
);

CREATE TABLE customer_status (
  id serial primary key,
  cacheKey smallint,
  memberCount date,
  comment point,
  alertType int,
  batchId datetime,
  chatId timestamp,
  eventDate bigint,
  fontSize decimal,
  flagged tinyint,
  addressLine1 mediumint,
  abandonedCartId smallint,
  enabledAt smallint,
  city tinyint,
  url text,
  isSystem timestamp,
  copyRight date,
  faxNumber tinyint,
  dependentId enum,
  localeId tinyint,
  loginCount int,
  content mediumint,
  locationId datetime,
  industryType text,
  sessionId decimal,
  accountStatus date,
  articleId tinyint,
  creditScore bit,
  username boolean,
  status date
);

CREATE TABLE src_organization (
  id serial primary key,
  timezone set,
  loginAttempts binary,
  checkOutTime bigint,
  exportId timestamp,
  phone time,
  fingerprint bigint,
  messageId mediumint,
  languageCode date,
  createdAt serial,
  incidentId timestamp,
  itemCount timestamp,
  lastSeenAt time,
  earnedPoints date,
  memberCount decimal,
  agentId float,
  contentType smallint,
  category decimal,
  configId timestamp,
  group binary,
  displayName text,
  cloudId float,
  lastLoginAt set,
  isBillable int
);

CREATE TABLE fact_customer (
  id serial primary key,
  gameId varchar,
  metaTitle decimal,
  deliveryDate blob,
  dimension point,
  productCode smallint
);

CREATE TABLE order (
  id serial primary key,
  maxLimit mediumint,
  currencyCode int,
  forwardTo tinyint,
  coordinateX tinyint,
  birthDate blob,
  customField1 tinyint,
  fontFamily set,
  fileHash datetime,
  unit real,
  earnedPoints timestamp,
  cartId set,
  depositAmount time,
  dependentId float,
  billingCycle smallint,
  code serial,
  rating float,
  batchId int,
  agentId mediumint,
  balance bigint,
  createdAt mediumint,
  businessType int,
  companyId decimal,
  levelId tinyint,
  clientId timestamp,
  currency boolean,
  handlerId set,
  documentId set,
  cancelReason point,
  displayName int,
  instanceId enum,
  joinDate varchar
);

CREATE TABLE accountout (
  id serial primary key,
  lastSeenAt enum,
  isDefault timestamp,
  cloudId text,
  moveId timestamp,
  priority smallint,
  isSystem date,
  dealerId int,
  orderId bit,
  logLevel double
);

CREATE TABLE company (
  id serial primary key,
  meterNumber time,
  deactivatedAt blob,
  sku geometry,
  avatar binary,
  lastName tinyint
);

CREATE TABLE order (
  id serial primary key,
  hostName timestamp,
  instanceId date,
  levelId float,
  manufacturerId geometry,
  isDeleted time,
  abandonedCartId blob,
  expiryYear double,
  dimension bit,
  fileHash timestamp,
  middleName boolean,
  hashKey timestamp,
  thumbnail smallint,
  incidentId binary,
  deactivatedAt bit,
  accessLevel int,
  nickname bit,
  employeeId enum,
  indexKey mediumint,
  linkId bit,
  logLevel set,
  extractId blob,
  emergencyContact boolean,
  documentId geometry
);

CREATE TABLE account (
  id serial primary key,
  agentId tinyint,
  duration timestamp
);

CREATE TABLE vw_payment (
  id serial primary key,
  geoLocation int,
  memberCount set,
  moduleId mediumint,
  listId geometry,
  fileHash text,
  handlerId varchar,
  enrollmentDate boolean,
  isDefault timestamp,
  discountCode float,
  thumbnail int,
  flagged serial,
  shippingAddress date,
  accountType bit,
  checkInTime text,
  fontFamily datetime,
  mimeType date,
  amount double,
  billingCycle enum,
  version mediumint,
  extractId boolean,
  firstName set,
  currencyCode boolean,
  isHidden timestamp,
  isAdmin binary,
  deactivatedAt serial,
  ipAddress mediumint,
  alertType timestamp,
  browserType float,
  groupName binary,
  documentId double,
  id double
);

CREATE TABLE record_div (
  id serial primary key,
  email bigint,
  displayOrder blob
);

CREATE TABLE tmp_order (
  id serial primary key,
  localeId float,
  batchId tinyint,
  claimId serial,
  levelId serial,
  discountCode double,
  labelText binary,
  title bit,
  bookingDate binary,
  avatar decimal,
  billingFrequency real,
  metaKeywords float,
  totalAmount timestamp,
  minValue serial,
  isFeatured tinyint,
  childId tinyint,
  houseNumber varchar,
  companyName geometry,
  createdAt bigint,
  isDefault bit
);

CREATE TABLE refaudit (
  id serial primary key,
  state timestamp,
  logLevel geometry,
  fingerprint mediumint,
  comment enum,
  dimension varchar,
  menuId double,
  role datetime,
  updatedAt double,
  deletedAt float,
  description time,
  itemCount date,
  creditCard set,
  city text,
  enrollmentDate time,
  customField1 tinyint,
  homePhone binary,
  linkId varchar,
  createdAt binary,
  fileType date,
  contactName time,
  isActive tinyint
);

CREATE TABLE transaction_temp (
  id serial primary key,
  age text,
  name real,
  contactName time,
  extractId smallint,
  grade blob
);

CREATE TABLE account (
  id serial primary key,
  eventDate tinyint,
  mapId serial,
  folderPath double
);

CREATE TABLE payment (
  id serial primary key,
  insertedAt float,
  hostName boolean,
  ipAddress point,
  weight bigint,
  coverImage double,
  metaDescription date,
  checkInTime mediumint
);

CREATE TABLE payment_archive_temp (
  id serial primary key,
  instructorId date,
  quantity decimal,
  brandId real,
  buildNumber double,
  displayName bigint,
  loginCount mediumint,
  feedId serial,
  completionRate bit,
  languageCode mediumint,
  channelId float,
  monthlyRate smallint,
  localeId bit,
  nickname double,
  couponCode time,
  metaDescription timestamp,
  orderStatus varchar,
  certificateId text,
  folderPath double,
  invoiceId set,
  batchId smallint,
  moduleId tinyint,
  cancelReason tinyint,
  extractId binary
);

CREATE TABLE priv_order (
  id serial primary key,
  feedId blob,
  macAddress float,
  algorithm geometry,
  avatar geometry,
  buildNumber double,
  dialCode point,
  endDate date,
  joinDate float,
  age set,
  flagged mediumint,
  grade set,
  geoLocation real,
  forwardTo datetime,
  loadTime datetime,
  dataSource text,
  locationId int,
  costCenter datetime,
  category text,
  billingFrequency double,
  connectionString int
);

CREATE TABLE company (
  id serial primary key,
  flagged int,
  monthlyRate decimal,
  bankAccount real,
  headerImage int,
  clockOut real,
  deviceType enum,
  expiryYear binary,
  actionType text,
  listId time,
  coverImage point,
  domainName bit,
  contractId real,
  friendId real,
  exportId blob,
  claimId decimal,
  lastLoginAt blob,
  macAddress set,
  defaultLang point,
  messageId date,
  faxNumber serial,
  maskType double,
  budgetCode binary,
  albumId double,
  balance geometry,
  deviceToken mediumint,
  childId real,
  metadata timestamp,
  cityName binary,
  description bit,
  completedAt timestamp
);

