CREATE TABLE pubrecord (
  id serial primary key,
  bluetoothId mediumint,
  discountCode text,
  metaKeywords timestamp,
  editedAt text,
  batchId float,
  quantity int,
  accountType smallint,
  messageId bigint,
  enrollmentDate point,
  uuid date
);

CREATE TABLE inventory (
  id serial primary key,
  colorCode float,
  departmentCode timestamp,
  longitude varchar,
  expiryMonth bit,
  updatedAt tinyint,
  contactEmail float,
  contentType binary,
  fontSize smallint,
  isVerified serial,
  cancelReason float,
  employeeId datetime,
  hashKey float
);

CREATE TABLE core_customer_seg (
  id serial primary key,
  companyName tinyint,
  apiVersion time,
  avatar date,
  amount geometry,
  category float,
  editedAt int,
  exchangeRate enum,
  fileHash mediumint,
  actionType serial,
  lockoutEnd tinyint
);

CREATE TABLE company (
  id serial primary key,
  exchangeRate datetime,
  loginAttempts varchar,
  isLocked bit,
  coverImage tinyint,
  id varchar,
  signature int,
  flagged datetime,
  content binary,
  isEnabled smallint,
  expiryMonth enum,
  analyticsId mediumint,
  checkInTime float,
  globalId point,
  longitude decimal,
  country text,
  customField2 real,
  articleId bigint,
  group time,
  instructorId date,
  hostName text,
  faxNumber double,
  invoiceId double,
  postalCode bigint,
  meterNumber geometry,
  sessionId enum,
  cardHolder varchar,
  age date,
  followCount point,
  apiVersion set,
  latitude real,
  floorNumber varchar
);

CREATE TABLE agg_inventory (
  id serial primary key,
  algorithm enum,
  browserType point,
  insuranceId serial,
  connectionString enum,
  integrationId mediumint,
  comment blob
);

CREATE TABLE company (
  id serial primary key,
  menuId mediumint,
  height tinyint,
  street double,
  category float,
  code set,
  listingId real,
  connectionString float,
  meterNumber float,
  flagged mediumint,
  awardDate bit,
  maxValue timestamp,
  deviceType varchar,
  value int,
  childId enum,
  email set,
  expiryDate text,
  distributorId boolean,
  labelText decimal,
  updatedAt binary,
  coordinateY smallint,
  companyId geometry,
  fromDate set,
  type varchar,
  longitude int
);

CREATE TABLE organizationlog (
  id serial primary key,
  editedAt binary,
  companyName binary,
  username bigint,
  salary binary,
  title datetime,
  departmentCode enum,
  employeeCode smallint,
  createdAt blob,
  isAdmin binary,
  apiVersion time,
  emailStatus binary
);

CREATE TABLE order (
  id serial primary key,
  dealerId point,
  creditLimit decimal,
  channelId time,
  customerGroup bigint,
  driverLicense int,
  chatId set,
  gateId varchar,
  companyName timestamp,
  comment date,
  salary set,
  deliveryDate float,
  creditCard date,
  licenseKey mediumint,
  avatar varchar,
  completedAt geometry,
  guestId boolean,
  actionType blob,
  errorMessage smallint,
  childId tinyint,
  amount text,
  followCount set,
  fromDate double,
  formatType tinyint,
  lockoutEnd tinyint,
  title timestamp
);

CREATE TABLE src_audit_extra_2025 (
  id serial primary key,
  earnedPoints geometry,
  currency set,
  colorCode set,
  manufacturerId set,
  customField1 geometry,
  referralCode decimal,
  cardNumber geometry
);

CREATE TABLE fact_audit_2025 (
  id serial primary key,
  age point,
  menuId date,
  alertType binary,
  balance geometry,
  createdAt varchar,
  isSystem double,
  checkOutTime bigint,
  hostName enum
);

CREATE TABLE tmp_transaction (
  id serial primary key,
  macAddress text,
  companyId point,
  startDate decimal,
  firstName real,
  token bigint,
  childId timestamp,
  alertType set,
  category smallint,
  loginAttempts int,
  checkOutTime int,
  paymentMethod double,
  dimension geometry,
  orderStatus binary,
  cancelReason smallint,
  insertedAt time,
  hourlyRate serial,
  accountType point,
  appVersion blob,
  cartId date,
  age blob
);

CREATE TABLE record (
  id serial primary key,
  clientId bit,
  chatId bigint,
  email float,
  apiVersion text,
  maskType bigint,
  department set,
  floorNumber timestamp,
  actionType enum,
  cacheKey set,
  eventDate bit,
  minLimit bit,
  avatar date,
  localeId geometry,
  isDraft time,
  awardDate text,
  createdAt decimal
);

CREATE TABLE dim_transaction_log (
  id serial primary key,
  accountType text,
  name serial,
  isSystem real,
  discount enum,
  businessType enum,
  addressLine2 geometry,
  logLevel int,
  latitude int,
  billingCycle blob,
  creditScore geometry,
  customerGroup serial,
  address mediumint,
  cardNumber double,
  budgetCode time,
  certificateId datetime,
  globalId boolean,
  version float,
  hiddenAt serial,
  nickname text,
  analyticsId timestamp,
  displayOrder geometry,
  phone binary,
  labelText date,
  coordinateY float,
  customerId decimal,
  postalCode geometry,
  minLimit text,
  listId datetime,
  employeeCode float,
  group timestamp
);

CREATE TABLE account (
  id serial primary key,
  contactEmail decimal,
  deviceType mediumint,
  menuId time,
  claimId timestamp,
  emergencyContact bigint,
  fromDate timestamp,
  downloadCount set,
  url text,
  albumId datetime,
  integrationId text,
  mapId set,
  isFeatured time,
  driverLicense smallint,
  minValue float,
  deletedAt set
);

CREATE TABLE cpy_customer_status (
  id serial primary key,
  completionRate binary,
  friendId timestamp,
  authMethod serial,
  costCenter blob,
  endDate bigint,
  exportId real,
  updatedAt smallint,
  merchantId int
);

CREATE TABLE cpy_record (
  id serial primary key,
  isActive double,
  dataSource binary,
  metaKeywords tinyint,
  layerId datetime,
  keywords int,
  monthlyRate tinyint,
  algorithm bit,
  domainName binary,
  tags enum,
  formatType boolean
);

CREATE TABLE account (
  id serial primary key,
  latitude bigint,
  phone real,
  distributorId mediumint,
  group time,
  isRequired time,
  batchId mediumint,
  token tinyint,
  monthlyRate enum,
  avatar float,
  dueDateAt mediumint,
  dimension int,
  addressLine1 text,
  licenseKey date,
  authMethod time,
  homePhone bit,
  meterNumber time,
  department binary,
  employeeId mediumint,
  industryType double,
  contactPhone enum,
  enrollmentDate decimal,
  currencyCode bigint,
  cityName decimal,
  dialCode binary,
  deletedAt binary,
  alertType bit,
  favoriteCount timestamp,
  defaultValue point
);

CREATE TABLE product (
  id serial primary key,
  quantity real,
  authMethod bigint,
  group enum,
  accountStatus bit,
  browserType real,
  comment serial,
  fromDate double,
  connectionString blob,
  chatId tinyint,
  birthDate time,
  dealerId datetime,
  instanceId bit,
  coordinateY timestamp,
  friendId real,
  contractId geometry,
  meterNumber set,
  maxValue point,
  age double,
  updatedAt time,
  buildNumber bit,
  followCount bit,
  customField2 bit,
  contactPhone bigint,
  documentId real
);

CREATE TABLE aggrecord (
  id serial primary key,
  description serial,
  batchId double,
  actionType double,
  attemptCount smallint,
  status timestamp,
  enabledAt bit,
  channelId tinyint,
  keyId double,
  discountCode varchar,
  deviceId text,
  albumId int,
  authToken real,
  name varchar,
  lastSeenAt varchar,
  rating blob,
  deviceType geometry,
  adminNotes blob,
  loginAttempts geometry,
  formatType set,
  orderStatus serial,
  group timestamp,
  quantity tinyint,
  cancelReason timestamp,
  id point,
  accountType bigint
);

CREATE TABLE product_v2 (
  id serial primary key,
  modifiedAt set,
  loginCount set,
  deviceId mediumint,
  nickname double,
  gateId boolean,
  linkId geometry,
  dailyLimit set,
  budgetCode set,
  isPublic blob,
  mapId set,
  dateFormat mediumint,
  fromDate tinyint,
  loadTime datetime
);

CREATE TABLE transaction (
  id serial primary key,
  url bigint,
  accessLevel real,
  chargeId decimal,
  handlerId decimal,
  depositAmount point,
  colorCode text,
  backupEmail varchar,
  costCenter boolean,
  fileName set,
  companyName float,
  layerId boolean,
  avatar serial,
  isAdmin varchar,
  gender boolean,
  signature mediumint,
  floorNumber enum,
  isHidden enum
);

CREATE TABLE payment (
  id serial primary key,
  name binary,
  mimeType binary,
  status float,
  lastLoginAt timestamp,
  description real,
  quantity datetime,
  importId decimal,
  address geometry,
  nickname binary,
  invoiceId int,
  extractId int,
  audioUrl set,
  certificateId varchar,
  fontFamily tinyint,
  copyRight bit,
  gameId text,
  documentId date,
  phone point,
  lastName datetime,
  sku date,
  errorCode datetime,
  insuranceId text
);

CREATE TABLE ext_order (
  id serial primary key,
  defaultLang point,
  enrollmentDate geometry,
  customField1 bigint,
  isEnabled double
);

CREATE TABLE company_extra (
  id serial primary key,
  category blob,
  contactPhone boolean,
  loadTime text,
  groupName decimal,
  defaultValue boolean,
  nickname smallint,
  state time
);

CREATE TABLE pub_record_data_temp (
  id serial primary key,
  url text,
  minValue time,
  metaTitle varchar,
  dimension double,
  incidentId timestamp,
  type text,
  creditScore varchar
);

CREATE TABLE transaction (
  id serial primary key,
  value serial,
  category timestamp,
  geoLocation blob,
  albumId boolean,
  frameRate timestamp,
  cacheKey blob,
  listingId point,
  driverLicense tinyint,
  billingCycle double,
  size bit,
  checkInTime bigint,
  fontFamily mediumint,
  gateId real,
  expiryDate date,
  height tinyint,
  createdAt tinyint,
  fingerprint float,
  coordinateY binary,
  flagged serial,
  houseNumber float,
  email point,
  isActive point,
  appVersion text,
  id smallint,
  handlerId blob
);

CREATE TABLE stg_transaction_extra (
  id serial primary key,
  taxRate enum,
  loginCount set,
  metaKeywords time,
  modifiedAt decimal,
  hiddenAt enum,
  email bigint,
  middleName point,
  clockOut double,
  gameId time,
  country date,
  type time,
  dependentId mediumint,
  dashboardId float,
  audioUrl date,
  cancelReason bigint
);

CREATE TABLE config_2024 (
  id serial primary key,
  activeDevices datetime,
  discountCode int,
  productCode bigint,
  emailStatus enum,
  cardNumber datetime,
  id boolean,
  isDeleted time
);

CREATE TABLE product (
  id serial primary key,
  maskType text,
  sku varchar,
  layerId text,
  groupName set,
  filterType date,
  group boolean,
  ipAddress decimal,
  tags binary,
  addressLine1 date,
  department text,
  contentType date,
  businessType bit,
  budgetCode set,
  currencyCode serial,
  companyName decimal,
  cityName timestamp,
  isFeatured serial,
  cardHolder varchar,
  longitude date,
  signature decimal,
  cartId serial,
  isArchived text,
  contactPhone point,
  childId smallint,
  isVerified int,
  emailStatus tinyint
);

CREATE TABLE order_2025 (
  id serial primary key,
  orderId text,
  chargeId set,
  createdAt geometry,
  balance date,
  expiryYear varchar,
  checkInTime date,
  quantity time,
  value tinyint,
  phone text,
  colorCode blob,
  isRequired bigint,
  displayOrder smallint
);

CREATE TABLE ext_account_info (
  id serial primary key,
  category point,
  avatar real,
  invoiceId point,
  childId int,
  agentId decimal,
  city enum,
  accountStatus point,
  content bigint,
  fontFamily smallint,
  quantity geometry,
  extractId binary,
  dependentId double,
  joinDate blob,
  birthDate float,
  sessionId mediumint,
  metadata int,
  metaDescription blob,
  connectionString bigint,
  isLocked double,
  title text,
  authorId bit,
  lastSeenAt geometry,
  appVersion enum,
  balance datetime,
  isActive time,
  lastName bigint,
  companyName serial,
  comment serial,
  alertType mediumint,
  managerId point,
  group time
);

CREATE TABLE product (
  id serial primary key,
  keyId date,
  attachmentUrl real,
  customField1 real,
  dashboardId varchar,
  cvv decimal,
  avatar date,
  content binary,
  contactName bigint,
  instructorId boolean,
  headerImage geometry,
  machineId decimal,
  marketId datetime,
  employeeCode time,
  cartId varchar,
  sessionId decimal,
  isDraft decimal,
  longitude real,
  contractId mediumint,
  referralCode time,
  instanceId time,
  companyName bigint,
  orderStatus decimal,
  depositAmount time,
  languageCode int,
  domainName timestamp,
  latitude set,
  itemCount date,
  bankAccount smallint,
  earnedPoints point,
  deviceToken int,
  maritalStatus double
);

CREATE TABLE organization (
  id serial primary key,
  albumId bit,
  fromDate mediumint,
  mobileNumber boolean,
  size enum,
  token boolean,
  bankAccount blob,
  displayOrder binary,
  employmentDate binary,
  deviceId float,
  dimension smallint,
  metaTitle point,
  contractId tinyint,
  companyName mediumint,
  licenseKey datetime,
  deletedAt decimal,
  likeCount point,
  title text,
  frameRate enum,
  lastName int,
  alertType double,
  city mediumint,
  isEnabled tinyint,
  fileSize varchar,
  timezone datetime,
  shippingAddress float,
  status date,
  dependentId boolean,
  validUntil real,
  machineId blob
);

CREATE TABLE inventory (
  id serial primary key,
  isRequired decimal,
  macAddress bigint,
  priority set,
  deviceToken text,
  hashKey point,
  instructorId mediumint,
  lastLoginAt point,
  contentType real,
  fontSize enum,
  dateFormat serial,
  grade datetime,
  backupEmail time,
  endPoint enum,
  headerImage blob,
  accountType int,
  levelId real,
  managerId bigint,
  isFeatured tinyint
);

CREATE TABLE tmp_record_v1 (
  id serial primary key,
  headerImage set,
  employeeId blob,
  category text,
  address text,
  isPublic geometry,
  authorId timestamp,
  paymentMethod text,
  thumbnail blob,
  metaKeywords enum,
  companyId double,
  departmentCode timestamp,
  createdAt datetime
);

CREATE TABLE tbl_account_info (
  id serial primary key,
  minLimit varchar,
  albumId mediumint,
  cancelReason serial,
  addressLine1 serial,
  startDate blob,
  audioUrl decimal,
  bookingDate mediumint,
  uuid geometry,
  costCenter time,
  formatType serial,
  content bit,
  group blob,
  metaKeywords bit,
  machineId set,
  ipAddress bigint,
  maritalStatus mediumint,
  linkId decimal,
  monthlyRate bigint,
  eventDate varchar,
  longitude time,
  merchantId enum,
  street set,
  houseNumber float,
  geoLocation point,
  keywords mediumint,
  defaultValue geometry,
  keyId set,
  gameId varchar,
  fileHash real,
  maxLimit boolean,
  salary smallint
);

CREATE TABLE recordtemp (
  id serial primary key,
  cacheKey enum,
  fileName tinyint,
  mimeType real,
  discount decimal,
  name binary,
  linkId geometry,
  deletedAt text,
  indexKey date,
  joinDate binary,
  currency tinyint,
  fileSize float,
  billingCycle time,
  floorNumber double,
  startDate mediumint,
  levelId real,
  deviceType real,
  priority bigint,
  addressLine2 tinyint,
  lockoutEnd serial,
  loginAttempts tinyint,
  endDate boolean,
  country boolean,
  bookingDate decimal,
  updatedAt binary,
  lastName mediumint,
  exportId text,
  geoLocation float
);

CREATE TABLE priv_organization (
  id serial primary key,
  completedAt binary,
  maritalStatus binary,
  creditScore point,
  listId varchar,
  colorCode mediumint,
  longitude serial,
  creditCard int,
  hashKey varchar,
  isVerified decimal,
  address varchar,
  browserType enum,
  lastLoginAt tinyint,
  isRequired int,
  coverImage varchar,
  title int,
  uuid timestamp,
  channelId date,
  isAdmin blob,
  apiKey serial,
  authMethod binary,
  incidentId date,
  countryCode geometry,
  category tinyint,
  layerId enum,
  token serial,
  employeeId real,
  cardHolder set,
  shippingAddress bigint,
  dailyLimit boolean,
  hiddenAt mediumint
);

CREATE TABLE payment (
  id serial primary key,
  deliveryDate blob,
  isDeleted serial,
  maritalStatus tinyint,
  lockoutEnd bigint,
  birthDate smallint,
  enabledAt set,
  backupEmail mediumint,
  enrollmentDate tinyint,
  modifiedAt boolean,
  insertedAt varchar,
  minLimit datetime,
  password enum,
  dependentId date,
  postalCode timestamp,
  exchangeRate serial,
  keywords tinyint,
  deactivatedAt smallint,
  url timestamp,
  importId tinyint,
  coordinateY decimal,
  cacheKey serial,
  geoLocation geometry,
  isEnabled int,
  dueDateAt varchar
);

CREATE TABLE organization_info (
  id serial primary key,
  hiddenAt point,
  homePhone geometry,
  discount real,
  industryType set,
  algorithm bit,
  phone real,
  copyRight geometry,
  firmwareVersion date,
  description real,
  amount bigint,
  category real,
  isArchived int,
  email bigint,
  itemCount geometry,
  certificateId real,
  completedAt set,
  likeCount boolean,
  maritalStatus timestamp,
  floorNumber int,
  listId boolean
);

CREATE TABLE vw_payment (
  id serial primary key,
  insertedAt enum,
  thumbnail datetime,
  expiryMonth boolean,
  invoiceId text,
  bannerImage timestamp,
  appVersion text,
  displayOrder binary,
  guestId mediumint,
  name timestamp,
  menuId boolean,
  forwardTo binary,
  title tinyint,
  code real,
  minLimit real,
  paymentMethod time,
  metaKeywords bigint,
  status blob,
  comment double,
  orderId blob,
  dialCode binary,
  maskType text,
  authorId timestamp,
  address int,
  maxValue float,
  type date,
  distributorId float,
  accountType int
);

CREATE TABLE extcustomerstatus (
  id serial primary key,
  gateId serial,
  bookingDate set,
  dialCode binary,
  cvv bigint,
  name mediumint,
  gameId bigint,
  hashKey float,
  salary binary,
  sku date,
  languageCode date,
  isSystem point,
  totalAmount blob,
  shippingAddress tinyint,
  department smallint,
  childId time,
  productCode real,
  creditCard datetime,
  billingCycle text,
  taxRate mediumint,
  deactivatedAt varchar,
  customField1 bigint,
  phone timestamp,
  moduleId point,
  houseNumber int,
  address timestamp,
  actionType varchar
);

CREATE TABLE transaction_status (
  id serial primary key,
  followCount decimal,
  name mediumint,
  id text,
  comment date,
  channelId bigint,
  gateId boolean,
  score date,
  expiryYear timestamp,
  amount float,
  createdAt datetime,
  maritalStatus tinyint,
  couponCode tinyint,
  startDate point,
  joinDate varchar,
  homePhone timestamp,
  certificateId real,
  phone blob,
  driverLicense blob,
  endPoint serial,
  depositAmount enum,
  favoriteCount date,
  metadata float,
  costCenter boolean,
  mimeType real
);

CREATE TABLE tbl_customer (
  id serial primary key,
  referralCode serial,
  bluetoothId varchar,
  address set,
  channelId serial
);

CREATE TABLE privcompanyv2 (
  id serial primary key,
  cardNumber serial,
  cancelReason text,
  coverImage smallint,
  updatedAt text,
  clockOut smallint,
  authToken real,
  entryPoint text,
  bankAccount int,
  email text,
  loginCount bigint,
  invoiceId timestamp,
  fileHash geometry,
  backupEmail bit
);

CREATE TABLE inventory_type (
  id serial primary key,
  deviceId date,
  checkOutTime boolean,
  deliveryDate mediumint,
  favoriteCount date,
  completedAt decimal,
  isDeleted geometry,
  paymentMethod datetime,
  validUntil bigint,
  forwardTo bit,
  creditScore bigint,
  state datetime,
  updatedAt date,
  cardNumber datetime,
  phone boolean,
  orderStatus point,
  avatar double,
  price geometry,
  colorCode date,
  minLimit bit,
  discountCode text,
  accessLevel real,
  cityName point,
  eventDate double
);

CREATE TABLE dst_inventory_legacy (
  id serial primary key,
  appVersion bigint,
  lockoutEnd tinyint,
  displayName mediumint
);

CREATE TABLE customer_extra (
  id serial primary key,
  deviceType text,
  address boolean,
  keyId mediumint,
  downloadCount decimal,
  mimeType enum,
  insuranceId varchar,
  metaTitle blob,
  customerId real,
  name bit,
  loginCount smallint,
  modifiedAt blob,
  height point,
  loginAttempts decimal,
  inactiveAt geometry,
  unit geometry,
  fromDate time,
  abandonedCartId text,
  domainName geometry,
  businessType binary,
  size boolean,
  email point,
  alertType datetime,
  gameId time,
  cardNumber varchar,
  defaultLang set,
  incidentId float,
  loadTime timestamp
);

CREATE TABLE transactionnotifications (
  id serial primary key,
  domainName set,
  addressLine2 blob,
  duration varchar,
  importId smallint,
  authMethod double,
  enrollmentDate boolean,
  isDraft int,
  homePhone real,
  accountType decimal,
  iconPath set,
  languageCode tinyint
);

CREATE TABLE config_legacy (
  id serial primary key,
  gateId double,
  clockOut smallint,
  guestId timestamp,
  modifiedAt set,
  frameRate timestamp,
  bookingDate bigint,
  cloudId int,
  instructorId serial,
  tags date
);

