CREATE TABLE tblorderlog (
  id serial primary key,
  licenseKey bit,
  endPoint mediumint
);

CREATE TABLE src_company (
  id serial primary key,
  taxRate serial,
  dueDateAt set,
  likeCount tinyint,
  maxLimit double,
  groupName mediumint,
  weight real,
  itemCount real,
  balance geometry,
  firstName datetime
);

CREATE TABLE aggtransactionmeta (
  id serial primary key,
  companyLogo tinyint,
  geoLocation real,
  folderPath geometry,
  dashboardId int,
  languageCode set,
  discountCode blob,
  uuid boolean,
  gender decimal,
  creditScore timestamp,
  isSystem date,
  firmwareVersion datetime,
  value int,
  mobileNumber float,
  formatType set,
  paymentMethod smallint,
  contentType binary,
  errorMessage bigint,
  accountNumber time,
  cacheKey date,
  companyName varchar
);

CREATE TABLE paymentv1 (
  id serial primary key,
  sessionId varchar,
  companyName smallint,
  machineId text,
  size datetime,
  facilityId int,
  group tinyint,
  extractId boolean,
  referralCode set,
  eventDate tinyint
);

CREATE TABLE fact_order_status (
  id serial primary key,
  dailyLimit double,
  dimension bigint,
  employmentDate geometry,
  longitude set,
  hashKey boolean,
  group decimal,
  deletedAt binary,
  actionType serial
);

CREATE TABLE src_organization (
  id serial primary key,
  isPublic timestamp,
  fontFamily int,
  instructorId varchar,
  companyName serial,
  middleName smallint,
  childId real,
  createdAt mediumint,
  isFeatured tinyint,
  manufacturerId bigint,
  labelText serial,
  productCode decimal,
  browserType tinyint,
  longitude varchar,
  minValue decimal,
  attachmentUrl double,
  expiryMonth float,
  albumId geometry,
  levelId bigint,
  discount enum,
  uuid int,
  maritalStatus datetime
);

CREATE TABLE vw_user_meta (
  id serial primary key,
  middleName decimal,
  depositAmount point,
  billingFrequency int,
  employmentDate double,
  entryPoint set,
  sessionId time,
  updatedAt bigint,
  formatType varchar,
  contentType mediumint,
  completionRate bigint,
  integrationId varchar,
  exportId boolean,
  referralCode enum,
  avatar mediumint,
  companyId set,
  contactName date,
  layerId real,
  city real,
  houseNumber timestamp,
  localeId mediumint,
  flagged float,
  manufacturerId enum,
  homePhone int,
  isVerified int,
  displayOrder enum,
  orderId double,
  friendId set,
  errorMessage smallint
);

CREATE TABLE company_new (
  id serial primary key,
  campaignId real,
  title geometry,
  isPublic real,
  errorMessage double,
  claimId geometry,
  countryCode datetime,
  cartId tinyint,
  lastLoginAt boolean,
  authorId text,
  hashKey geometry,
  sku timestamp,
  followCount smallint,
  startDate timestamp,
  latitude date,
  isLocked set,
  maskType double
);

CREATE TABLE log_inventory (
  id serial primary key,
  guestId datetime,
  deactivatedAt time,
  hourlyRate float,
  authorId int,
  state blob,
  duration mediumint,
  nickname int,
  awardDate mediumint,
  instanceId float,
  incidentId enum,
  fileName serial,
  customField1 bit,
  isEnabled time,
  attachmentUrl geometry,
  timezone double,
  lastSeenAt varchar
);

CREATE TABLE user (
  id serial primary key,
  height set,
  code point,
  title boolean,
  email mediumint,
  postalCode timestamp,
  age tinyint,
  deviceToken decimal,
  unit bit,
  campaignId real,
  colorCode binary,
  distributorId date,
  audioUrl point,
  groupName serial,
  enabledAt boolean,
  deletedAt geometry,
  machineId enum,
  name text,
  nickname int,
  feedId binary,
  apiKey bit,
  attachmentUrl timestamp,
  entryPoint serial,
  contentType int
);

CREATE TABLE customerrel (
  id serial primary key,
  priority bit,
  totalAmount float,
  country timestamp,
  balance date,
  bannerImage date,
  password bigint,
  logLevel varchar,
  attemptCount real,
  instructorId bit,
  browserType point,
  loginCount boolean,
  indexKey bit,
  cartId smallint,
  uuid bigint,
  dashboardId mediumint,
  forwardTo enum,
  defaultLang bigint,
  customerGroup bit,
  memberCount geometry,
  contactPhone set,
  completionRate time,
  itemCount time,
  email geometry,
  displayName timestamp,
  foregroundColor set,
  accountType set,
  content datetime,
  ipAddress text,
  deviceType timestamp,
  cacheKey varchar
);

CREATE TABLE olk_product_meta (
  id serial primary key,
  education enum,
  mimeType mediumint,
  loginAttempts blob,
  quantity tinyint,
  maxLimit tinyint,
  itemCount timestamp,
  middleName geometry,
  integrationId timestamp,
  name datetime
);

CREATE TABLE priv_user_status (
  id serial primary key,
  clockOut mediumint,
  isVerified tinyint,
  distributorId int
);

CREATE TABLE user_2025 (
  id serial primary key,
  foregroundColor decimal,
  labelText date
);

CREATE TABLE rel_order (
  id serial primary key,
  expiryMonth tinyint,
  billingFrequency int,
  role date,
  formatType datetime,
  contractId set,
  description serial,
  cvv timestamp,
  metadata mediumint,
  feedbackId double,
  fileName tinyint,
  driverLicense boolean,
  updatedAt date,
  unit timestamp,
  comment geometry,
  balance tinyint,
  ipAddress tinyint,
  birthDate mediumint,
  isDeleted decimal,
  timezone bigint,
  listId set,
  dashboardId set,
  isLocked blob
);

CREATE TABLE core_record_log (
  id serial primary key,
  levelId float,
  eventDate geometry,
  apiKey float,
  linkId double,
  cancelReason float,
  tags bit,
  expiryYear varchar,
  couponCode point,
  accountType double,
  facilityId real,
  alertType varchar
);

CREATE TABLE stg_record_2025 (
  id serial primary key,
  insertedAt bit,
  fileSize boolean,
  metaTitle smallint,
  customField1 date,
  deviceToken binary
);

CREATE TABLE customer (
  id serial primary key,
  domainName smallint,
  maxValue smallint,
  comment geometry,
  moduleId double,
  latitude text,
  deactivatedAt binary,
  expiryMonth varchar,
  description text,
  alertType bigint,
  city time,
  addressLine1 enum,
  dashboardId point,
  category datetime,
  mainImage tinyint,
  authToken geometry,
  formatType text,
  instanceId bigint,
  avatar float,
  endDate enum,
  appVersion serial
);

CREATE TABLE vworganizationout (
  id serial primary key,
  authMethod point,
  deactivatedAt blob,
  loadTime bit,
  street real,
  addressLine1 bit,
  lastLoginAt set,
  handlerId mediumint,
  fileHash time,
  sessionId varchar,
  fontFamily enum,
  levelId bit,
  orderId date,
  indexKey smallint,
  ipAddress real,
  customField2 int
);

CREATE TABLE olkauditout (
  id serial primary key,
  flagged set,
  expiryYear enum,
  courseId enum,
  inactiveAt int,
  firmwareVersion tinyint,
  messageId point,
  mapId text,
  fontSize real,
  authToken timestamp,
  lastSeenAt bit,
  localeId enum,
  documentId smallint,
  content bigint,
  joinDate float,
  instructorId double,
  costCenter boolean
);

CREATE TABLE customer (
  id serial primary key,
  creditScore enum,
  password int,
  score varchar,
  referralCode geometry,
  accountType tinyint,
  updatedAt time,
  metaKeywords int,
  joinDate int,
  contactPhone double,
  sessionId float,
  actionType date,
  completedAt binary,
  meterNumber enum,
  status bigint,
  totalAmount timestamp,
  endDate blob,
  mapId text,
  distributorId timestamp,
  url set,
  cancelReason real,
  licenseKey date,
  fileSize timestamp
);

CREATE TABLE config (
  id serial primary key,
  attemptCount blob,
  firstName set,
  address text,
  latitude tinyint,
  amount datetime,
  gender timestamp,
  contactEmail set,
  favoriteCount enum,
  isArchived real,
  avatar timestamp,
  audioUrl point,
  forwardTo double,
  accountStatus blob,
  chatId double,
  lockoutEnd point,
  defaultValue varchar,
  chargeId serial,
  cityName mediumint,
  abandonedCartId varchar,
  content geometry
);

CREATE TABLE config_rel (
  id serial primary key,
  followCount geometry,
  adminNotes smallint,
  jobTitle date,
  unit time,
  languageCode int,
  avatar geometry,
  expiryDate serial,
  guestId time,
  maxValue bigint,
  geoLocation point,
  id time,
  frameRate boolean,
  metaKeywords timestamp,
  department timestamp,
  companyId bit,
  addressLine1 text
);

CREATE TABLE rel_customer_data_temp (
  id serial primary key,
  isActive float,
  labelText blob,
  checkInTime geometry,
  emergencyContact real,
  displayName timestamp,
  driverLicense set,
  iconPath double,
  contactName boolean,
  browserType date
);

CREATE TABLE extcompany (
  id serial primary key,
  isDefault bigint,
  nickname enum,
  chargeId float,
  lastSeenAt bigint,
  departmentCode date,
  sku decimal,
  endPoint real,
  longitude point,
  expiryDate float,
  ipAddress int,
  hiddenAt real,
  accountType varchar
);

CREATE TABLE olk_record_seg (
  id serial primary key,
  category double,
  floorNumber mediumint,
  loadTime smallint,
  totalAmount blob,
  updatedAt set,
  apiKey datetime,
  deviceType datetime,
  isAdmin boolean,
  emergencyContact binary,
  cloudId set,
  eventDate bigint,
  username smallint,
  cancelReason time,
  token enum,
  invoiceId blob,
  businessType enum,
  longitude int,
  layerId double,
  coordinateY blob,
  monthlyRate float,
  id set,
  accessLevel serial,
  machineId datetime
);

CREATE TABLE config_info (
  id serial primary key,
  emergencyContact smallint,
  accountNumber bigint,
  entryPoint varchar,
  domainName datetime,
  itemCount text,
  foregroundColor mediumint,
  managerId mediumint
);

CREATE TABLE company (
  id serial primary key,
  maxLimit text,
  articleId varchar,
  itemCount serial,
  addressLine2 binary,
  id boolean,
  maskType float,
  authToken bigint
);

CREATE TABLE systransaction (
  id serial primary key,
  accountNumber serial,
  coordinateX date,
  clientId date,
  street real,
  dueDateAt smallint,
  menuId datetime,
  lastLoginAt double,
  sku boolean,
  category real,
  hourlyRate varchar,
  height real,
  checkInTime mediumint,
  phone varchar,
  floorNumber bigint,
  createdAt binary,
  bookingDate datetime,
  friendId bigint
);

CREATE TABLE ref_payment_log_legacy (
  id serial primary key,
  cardNumber bit,
  isEnabled time,
  modifiedAt varchar
);

CREATE TABLE config (
  id serial primary key,
  isHidden date,
  sessionId text,
  minLimit boolean,
  avatar tinyint,
  likeCount int
);

CREATE TABLE veruserstatus (
  id serial primary key,
  firmwareVersion geometry,
  postalCode boolean,
  cityName float,
  comment bit,
  authorId tinyint,
  middleName bit,
  isArchived mediumint,
  status blob,
  instanceId varchar,
  longitude float,
  accountType blob,
  coordinateX boolean,
  manufacturerId double,
  apiVersion time,
  alertType date,
  messageId date,
  loadTime date,
  hostName geometry,
  filterType bigint,
  editedAt real
);

CREATE TABLE config (
  id serial primary key,
  locationId double,
  joinDate mediumint,
  postalCode date,
  lastName float,
  contactName boolean,
  mobileNumber boolean,
  deactivatedAt serial,
  id float,
  localeId decimal,
  likeCount datetime,
  labelText point,
  clockOut binary,
  employeeCode real,
  geoLocation tinyint,
  keywords mediumint,
  colorCode enum,
  favoriteCount text,
  hashKey tinyint,
  city varchar,
  entityId datetime,
  attemptCount double,
  indexKey bigint,
  updatedAt mediumint,
  displayName blob,
  firstName datetime,
  friendId int,
  category bit,
  groupName serial,
  depositAmount bigint,
  avatar bigint,
  employmentDate serial
);

CREATE TABLE olkproducthist2024 (
  id serial primary key,
  fileType smallint,
  isHidden point,
  itemCount varchar,
  manufacturerId serial,
  dataSource int,
  cloudId bigint,
  birthDate serial,
  managerId text,
  inactiveAt bit,
  instanceId boolean,
  age binary,
  weight smallint,
  messageId bit,
  downloadCount text,
  score float,
  configId date,
  globalId geometry,
  likeCount int,
  maxValue geometry,
  creditCard mediumint,
  feedId datetime,
  listingId binary,
  latitude set,
  longitude enum,
  sessionId date,
  layerId varchar,
  algorithm decimal,
  cvv mediumint,
  cartId text,
  headerImage time
);

CREATE TABLE cpy_user_2025 (
  id serial primary key,
  foregroundColor mediumint,
  certificateId double,
  endDate geometry
);

CREATE TABLE app_account_v2 (
  id serial primary key,
  friendId int,
  contentType decimal,
  version time,
  isHidden boolean,
  creditCard datetime,
  formatType date,
  foregroundColor boolean,
  bluetoothId timestamp,
  contactPhone point,
  token binary,
  levelId double,
  mapId double,
  group serial,
  isEnabled double,
  keywords blob,
  completedAt serial,
  discount mediumint,
  discountCode boolean,
  houseNumber mediumint,
  enabledAt timestamp,
  bookingDate double,
  logLevel blob,
  listingId real,
  dealerId text,
  salary enum,
  size datetime,
  cancelReason tinyint,
  deviceToken time,
  unit point
);

CREATE TABLE auditv2 (
  id serial primary key,
  iconPath double,
  lockoutEnd bit,
  loginCount varchar,
  lastName double,
  feedbackId binary,
  referralCode set,
  mobileNumber blob,
  localeId boolean,
  metaKeywords blob,
  zipCode point,
  fontFamily bit,
  createdAt point,
  cvv set,
  likeCount enum,
  customField2 set,
  folderPath text,
  signature set,
  defaultValue float,
  url tinyint,
  latitude blob,
  brandId double,
  metaDescription date,
  countryCode real
);

CREATE TABLE audit (
  id serial primary key,
  deviceType blob,
  code boolean,
  creditScore date,
  foregroundColor enum,
  balance timestamp,
  earnedPoints varchar,
  coordinateY set,
  cardNumber tinyint,
  employeeId time,
  maritalStatus geometry,
  isDraft mediumint,
  awardDate mediumint,
  isRequired bit,
  meterNumber tinyint,
  comment set,
  deviceToken decimal,
  globalId set,
  endPoint float,
  priority boolean,
  accountNumber time,
  contactName bigint,
  metaDescription time,
  itemCount enum,
  email text,
  cvv decimal,
  discount float,
  expiryDate tinyint,
  labelText timestamp,
  entityId decimal,
  loadTime bit
);

CREATE TABLE account (
  id serial primary key,
  lockoutEnd datetime,
  macAddress tinyint,
  likeCount timestamp,
  courseId int,
  creditScore blob,
  lastName binary,
  fingerprint real,
  maxValue varchar,
  enrollmentDate tinyint,
  browserType double,
  zipCode enum,
  sessionId bigint,
  amount bit,
  adminNotes geometry
);

CREATE TABLE inventory_data_v1 (
  id serial primary key,
  mapId boolean,
  coordinateY double,
  maxValue real,
  password bigint,
  fontFamily set,
  ipAddress blob,
  title tinyint,
  updatedAt time,
  deviceId real,
  city binary,
  appVersion tinyint,
  entryPoint real,
  layerId date,
  code set,
  extractId timestamp,
  feedbackId bigint,
  coverImage text,
  id decimal,
  taxRate bigint,
  linkId double,
  dueDateAt serial,
  metaDescription smallint,
  expiryMonth int,
  attemptCount time,
  isSystem double,
  insertedAt tinyint,
  friendId smallint,
  fileType double
);

CREATE TABLE company2025 (
  id serial primary key,
  unit varchar,
  alertType bit,
  expiryDate text,
  lastLoginAt timestamp,
  amount binary,
  inactiveAt datetime,
  rating blob,
  token bit,
  appVersion serial,
  deliveryDate text,
  addressLine1 mediumint,
  errorMessage boolean,
  cardNumber smallint,
  emergencyContact timestamp,
  fingerprint datetime,
  licenseKey real
);

CREATE TABLE src_organization (
  id serial primary key,
  avatar timestamp,
  age timestamp,
  friendId geometry,
  orderId text,
  brandId mediumint,
  bluetoothId time,
  hourlyRate mediumint,
  licenseKey decimal,
  editedAt double,
  favoriteCount date,
  accessLevel geometry,
  height geometry,
  instructorId date,
  listingId text,
  updatedAt mediumint,
  mobileNumber text,
  deviceId varchar,
  cardHolder float,
  deviceType timestamp
);

CREATE TABLE ver_account_data (
  id serial primary key,
  expiryYear date,
  education point,
  expiryMonth time,
  discountCode double,
  dataSource varchar
);

CREATE TABLE sys_audit_seg (
  id serial primary key,
  chargeId enum,
  group float,
  quantity geometry,
  entityId tinyint,
  insertedAt boolean,
  contentType point,
  uuid tinyint,
  description point,
  metaTitle float,
  isRequired bit,
  isAdmin bit,
  lastLoginAt smallint,
  status serial,
  address timestamp,
  couponCode set,
  billingFrequency enum,
  fileName tinyint,
  foregroundColor double,
  referralCode bigint,
  age timestamp,
  tags text,
  balance enum,
  clientId binary,
  latitude geometry,
  floorNumber point,
  dashboardId smallint,
  minValue tinyint
);

CREATE TABLE priv_account_temp (
  id serial primary key,
  licenseKey tinyint,
  enabledAt bigint,
  quantity double,
  longitude int,
  name tinyint,
  endDate decimal,
  cvv bigint,
  exchangeRate serial,
  status enum,
  expiryMonth time,
  jobTitle smallint,
  size double,
  labelText date,
  editedAt blob,
  dashboardId double,
  url boolean,
  firstName int,
  isSystem blob,
  errorMessage bit,
  deletedAt mediumint,
  avatar bit,
  incidentId text
);

CREATE TABLE account (
  id serial primary key,
  contactName boolean,
  amount boolean,
  completedAt real,
  role serial,
  longitude float,
  loginCount smallint,
  token smallint,
  creditScore point,
  firstName blob,
  dueDateAt serial,
  insertedAt double,
  id smallint
);

CREATE TABLE ext_record (
  id serial primary key,
  unit bit,
  isArchived set,
  content real,
  deliveryDate smallint,
  exportId tinyint,
  chargeId text,
  awardDate smallint,
  duration point,
  extractId datetime,
  lastLoginAt float,
  costCenter blob,
  clockOut serial,
  configId bit,
  createdAt blob,
  isDraft real,
  cardHolder int,
  filterType float,
  monthlyRate real,
  clockIn datetime,
  gateId bit,
  thumbnail time,
  fileType mediumint,
  gameId bit,
  height timestamp
);

CREATE TABLE coreorganization (
  id serial primary key,
  type blob,
  fontSize time,
  accessLevel int,
  folderPath bit,
  ipAddress text,
  instructorId double,
  mainImage point,
  sessionId binary,
  feedbackId time,
  labelText int,
  hostName smallint,
  updatedAt serial,
  companyLogo int,
  creditLimit point,
  exchangeRate set,
  contactPhone boolean,
  itemCount tinyint,
  completedAt real,
  nickname int,
  bookingDate binary,
  customField1 enum,
  phone timestamp,
  maskType point,
  fileName date,
  size binary,
  emergencyContact serial,
  authMethod real,
  copyRight text,
  password float,
  lastName point,
  isDefault serial
);

CREATE TABLE inventory_v2 (
  id serial primary key,
  salary double,
  isRequired date,
  isArchived decimal,
  linkId set,
  age binary,
  longitude date,
  uuid mediumint,
  moduleId enum,
  appVersion datetime,
  priority tinyint,
  isVerified time,
  dailyLimit mediumint,
  invoiceId point,
  keyId smallint,
  dateFormat timestamp,
  forwardTo float
);

CREATE TABLE product (
  id serial primary key,
  forwardTo text,
  distributorId time,
  feedbackId blob,
  nickname int,
  bankAccount geometry,
  enabledAt varchar
);

