CREATE TABLE customer_temp (
  id serial primary key,
  departmentCode real,
  floorNumber real,
  copyRight double,
  invoiceId binary
);

CREATE TABLE dstorganization (
  id serial primary key,
  deviceId tinyint,
  price geometry,
  adminNotes boolean,
  mobileNumber time,
  employeeId bit,
  completedAt geometry,
  phone varchar,
  currency double,
  listId timestamp,
  mainImage bit,
  feedbackId bigint,
  clockOut decimal,
  clockIn point,
  accountType boolean,
  dealerId bigint,
  keyId bit,
  companyName enum,
  dailyLimit set,
  bankAccount bit,
  isPublic float,
  modifiedAt bit,
  addressLine2 bigint,
  logLevel float,
  nickname smallint,
  validUntil date,
  enabledAt real,
  linkId time,
  fileHash text
);

CREATE TABLE transactionv1 (
  id serial primary key,
  address bit,
  dialCode real,
  avatar real,
  cardNumber bit,
  token tinyint,
  size timestamp,
  apiKey set,
  currencyCode binary,
  isVerified timestamp,
  ipAddress decimal,
  customField1 text,
  isAdmin real,
  accessLevel date,
  labelText set,
  chargeId decimal,
  incidentId bigint,
  layerId float,
  phone time,
  licenseKey set,
  logLevel real,
  deviceToken point,
  isDefault varchar,
  gender bit,
  distributorId set,
  indexKey set,
  createdAt enum,
  dashboardId bit,
  fontSize int,
  batchId bit,
  comment serial
);

CREATE TABLE dim_inventory_data (
  id serial primary key,
  maxLimit time,
  group geometry,
  hiddenAt datetime
);

CREATE TABLE tmporganizationmap (
  id serial primary key,
  content time,
  monthlyRate bit,
  houseNumber mediumint,
  comment varchar,
  displayOrder geometry,
  mapId tinyint
);

CREATE TABLE dst_record (
  id serial primary key,
  contractId timestamp,
  discount decimal,
  couponCode binary,
  authorId boolean,
  globalId text,
  code float,
  coverImage double,
  driverLicense double,
  mobileNumber serial,
  marketId bit,
  size geometry,
  metaTitle blob,
  maskType bit,
  hiddenAt boolean,
  importId bigint,
  referralCode boolean
);

CREATE TABLE transaction (
  id serial primary key,
  thumbnail double,
  buildNumber boolean,
  deliveryDate bigint,
  createdAt text,
  shippingAddress text,
  loginCount text,
  orderId bit,
  longitude bigint,
  couponCode double,
  eventDate geometry,
  phone double,
  password text,
  bookingDate text,
  isDraft int,
  updatedAt datetime,
  chargeId date,
  metaTitle decimal,
  hostName bigint,
  layerId double,
  dashboardId int,
  metadata float,
  locationId double,
  street bigint,
  balance bit,
  startDate geometry,
  avatar time,
  token point,
  dimension serial,
  birthDate set
);

CREATE TABLE customer (
  id serial primary key,
  height timestamp,
  businessType varchar,
  code geometry,
  isEnabled point,
  country timestamp,
  isVerified datetime,
  completedAt tinyint,
  isArchived bit,
  isLocked smallint,
  birthDate tinyint,
  name text,
  creditLimit binary,
  longitude set,
  fileName decimal,
  gender text,
  minLimit geometry,
  maxValue datetime,
  connectionString real,
  token date
);

CREATE TABLE payment_v2 (
  id serial primary key,
  employeeCode int,
  dataSource point,
  billingFrequency real,
  uuid enum,
  joinDate tinyint,
  domainName text,
  score set,
  cloudId decimal,
  latitude datetime,
  maskType set,
  budgetCode datetime,
  expiryMonth blob,
  keyId mediumint,
  documentId int,
  channelId float,
  quantity binary,
  currency varchar,
  role boolean,
  backupEmail set,
  globalId real,
  accountType decimal
);

CREATE TABLE organization_info (
  id serial primary key,
  floorNumber int,
  billingFrequency binary
);

CREATE TABLE cpyconfigstatus (
  id serial primary key,
  customerGroup mediumint,
  downloadCount smallint,
  hourlyRate enum,
  gender date,
  integrationId time,
  lastLoginAt smallint,
  contactPhone enum,
  height datetime,
  couponCode smallint,
  contractId mediumint,
  isEnabled float,
  itemCount set,
  email mediumint,
  dependentId time,
  menuId int,
  listingId timestamp,
  appVersion point,
  currency datetime,
  tags tinyint,
  activeDevices serial,
  adminNotes float,
  alertType mediumint,
  contactEmail geometry,
  weight tinyint,
  attemptCount datetime,
  companyName time,
  buildNumber date,
  audioUrl date,
  category decimal
);

CREATE TABLE payment_type (
  id serial primary key,
  houseNumber serial,
  orderStatus serial,
  accessLevel double,
  description smallint,
  avatar bigint,
  age serial,
  gameId geometry
);

CREATE TABLE ver_transaction (
  id serial primary key,
  email blob,
  status int,
  budgetCode int,
  cartId varchar,
  lastSeenAt mediumint,
  accessLevel float,
  formatType int,
  handlerId datetime,
  appVersion tinyint,
  fileSize blob,
  name date
);

CREATE TABLE agg_product_new (
  id serial primary key,
  completionRate int,
  companyLogo float,
  dimension time,
  appVersion binary,
  deviceId double,
  contactEmail text,
  currencyCode date,
  deliveryDate serial,
  friendId bit,
  contactName datetime,
  firmwareVersion date,
  memberCount timestamp,
  activeDevices boolean,
  latitude datetime,
  couponCode blob,
  clientId binary,
  cancelReason int,
  campaignId bit,
  firstName blob,
  fileSize bit,
  linkId geometry,
  hiddenAt decimal,
  address point,
  fromDate smallint
);

CREATE TABLE stgpayment (
  id serial primary key,
  nickname geometry,
  education text,
  zipCode tinyint,
  createdAt real,
  shippingAddress point,
  expiryMonth binary,
  customerId datetime,
  comment blob,
  colorCode timestamp,
  referralCode tinyint,
  couponCode float,
  channelId enum,
  age mediumint,
  version bit,
  machineId float,
  fromDate text
);

CREATE TABLE ref_order (
  id serial primary key,
  instructorId text,
  orderId real,
  ipAddress boolean,
  budgetCode boolean,
  depositAmount smallint,
  errorMessage geometry,
  bankAccount tinyint,
  backupEmail time,
  metaKeywords date,
  fileName point,
  contractId geometry,
  score enum
);

CREATE TABLE ref_company_legacy (
  id serial primary key,
  agentId varchar,
  guestId point,
  channelId varchar,
  marketId time,
  grade boolean,
  category mediumint,
  isFeatured point
);

CREATE TABLE fact_company (
  id serial primary key,
  machineId smallint,
  bankAccount set,
  connectionString tinyint,
  taxRate tinyint,
  maxLimit bigint,
  enrollmentDate decimal,
  emailStatus datetime,
  likeCount blob,
  metaTitle text,
  fileType binary,
  contactPhone varchar,
  mimeType int,
  mapId geometry,
  category smallint,
  phone timestamp,
  nickname bit,
  group enum,
  isVerified varchar,
  checkInTime time,
  department serial,
  currencyCode blob,
  clockIn serial,
  createdAt tinyint,
  cardHolder time
);

CREATE TABLE pub_company (
  id serial primary key,
  endDate blob,
  earnedPoints real,
  checkInTime serial,
  listId smallint,
  email geometry,
  accessLevel enum,
  currency set,
  errorMessage decimal,
  meterNumber time
);

CREATE TABLE tmp_audit (
  id serial primary key,
  apiVersion binary,
  isFeatured boolean,
  maritalStatus real,
  emergencyContact double,
  description timestamp,
  abandonedCartId real,
  copyRight decimal,
  minLimit bigint,
  gateId int,
  localeId enum,
  joinDate smallint,
  inactiveAt float,
  memberCount mediumint,
  listingId time,
  title time,
  address double,
  maxLimit binary,
  street blob
);

CREATE TABLE order (
  id serial primary key,
  connectionString timestamp,
  activeDevices smallint,
  creditCard decimal,
  awardDate enum,
  referralCode int,
  authMethod float,
  fileType serial,
  moduleId decimal,
  firmwareVersion double,
  metaDescription serial
);

CREATE TABLE dimuser (
  id serial primary key,
  address double,
  completionRate date,
  feedId bigint,
  comment boolean,
  messageId date,
  employeeCode time,
  lockoutEnd serial,
  deviceId set,
  street time,
  emailStatus binary,
  group real,
  invoiceId float,
  likeCount boolean,
  analyticsId real,
  fontFamily varchar,
  awardDate mediumint,
  importId bigint,
  addressLine1 double,
  sessionId mediumint,
  backupEmail bigint,
  chargeId timestamp,
  certificateId date,
  firmwareVersion bit,
  totalAmount date,
  dailyLimit double
);

CREATE TABLE payment_hist_temp (
  id serial primary key,
  title serial,
  isHidden text,
  checkInTime point,
  timezone enum,
  distributorId float,
  customerGroup bigint,
  clientId binary,
  businessType boolean,
  avatar boolean,
  cancelReason int,
  dialCode mediumint,
  isLocked varchar,
  groupName smallint,
  isDeleted smallint,
  updatedAt real,
  deviceId blob,
  geoLocation tinyint
);

CREATE TABLE organization (
  id serial primary key,
  employeeCode timestamp,
  address bit,
  earnedPoints set,
  companyName tinyint,
  accessLevel binary,
  addressLine2 date,
  amount geometry,
  distributorId smallint,
  inactiveAt date,
  defaultValue blob,
  dependentId decimal,
  departmentCode float,
  dateFormat enum,
  checkOutTime point,
  channelId date,
  locationId bigint,
  dailyLimit serial,
  layerId smallint,
  dialCode boolean,
  errorMessage point,
  token set,
  costCenter point,
  discountCode double,
  gender date,
  orderId real,
  metaDescription tinyint,
  isBillable smallint,
  avatar bigint,
  referralCode binary,
  height mediumint
);

CREATE TABLE transaction (
  id serial primary key,
  amount binary,
  validUntil float,
  moduleId bigint,
  dialCode bigint,
  isHidden int,
  checkOutTime decimal,
  creditScore time
);

CREATE TABLE organization_new (
  id serial primary key,
  mainImage date,
  companyId text
);

CREATE TABLE transactionv1 (
  id serial primary key,
  integrationId boolean,
  menuId time,
  locationId bit,
  sessionId bigint,
  hashKey point,
  employeeCode date,
  isLocked blob,
  likeCount varchar,
  coordinateX geometry,
  employmentDate varchar,
  monthlyRate bigint,
  incidentId tinyint,
  isFeatured decimal,
  createdAt enum,
  industryType serial,
  geoLocation tinyint,
  costCenter binary,
  deactivatedAt double,
  courseId real,
  meterNumber date,
  customField1 date,
  claimId datetime,
  completionRate text,
  city decimal,
  dealerId mediumint,
  groupName int,
  customerGroup real,
  minLimit enum,
  addressLine1 varchar,
  brandId blob,
  type geometry
);

CREATE TABLE account (
  id serial primary key,
  billingFrequency varchar,
  deviceId blob,
  expiryMonth enum,
  lockoutEnd set,
  childId varchar,
  activeDevices enum,
  createdAt bigint,
  ipAddress tinyint,
  currency float,
  batchId binary,
  city serial,
  username float,
  guestId real,
  clockIn enum,
  accountType text,
  handlerId float,
  joinDate timestamp,
  memberCount timestamp,
  clientId int,
  rating blob,
  inactiveAt float,
  distributorId mediumint,
  editedAt decimal,
  minValue double,
  merchantId smallint,
  avatar boolean,
  coordinateY tinyint,
  latitude decimal,
  coordinateX geometry,
  licenseKey float
);

CREATE TABLE inventory_2025 (
  id serial primary key,
  address boolean,
  validUntil binary,
  feedbackId boolean,
  avatar mediumint,
  defaultValue float,
  tags varchar,
  postalCode int,
  contactName set,
  taxRate point,
  weight bigint,
  flagged bigint,
  password serial,
  employeeCode set,
  isDraft blob,
  state double,
  facilityId date,
  emergencyContact bit,
  name binary,
  phone binary,
  completedAt date,
  content double,
  shippingAddress timestamp
);

CREATE TABLE log_audit (
  id serial primary key,
  employmentDate blob,
  name time,
  version timestamp,
  exportId binary,
  maxLimit int,
  quantity text,
  department blob,
  expiryMonth enum
);

CREATE TABLE ext_audit_meta (
  id serial primary key,
  category mediumint,
  country float,
  isBillable binary,
  fileSize geometry,
  phone boolean,
  paymentMethod blob,
  jobTitle boolean,
  endPoint double,
  cloudId tinyint,
  shippingAddress date,
  folderPath double,
  type enum,
  creditLimit bit,
  balance float,
  languageCode bigint,
  isFeatured timestamp,
  expiryYear boolean,
  dealerId int,
  status enum,
  likeCount real,
  currency point
);

CREATE TABLE product (
  id serial primary key,
  driverLicense real,
  endDate real,
  campaignId time,
  longitude real,
  batchId datetime,
  phone text,
  hourlyRate mediumint,
  accountType text,
  birthDate geometry,
  taxRate float,
  comment datetime,
  companyName float,
  managerId mediumint,
  exportId float,
  countryCode time,
  blogId enum
);

CREATE TABLE account (
  id serial primary key,
  entityId set,
  longitude point,
  clockOut text,
  listId smallint,
  errorMessage smallint,
  houseNumber set,
  orderStatus time,
  metadata tinyint,
  insuranceId datetime,
  exportId geometry,
  customerGroup date,
  listingId serial,
  instanceId mediumint,
  firstName binary,
  defaultLang boolean,
  brandId set,
  completedAt bigint
);

CREATE TABLE fact_inventory (
  id serial primary key,
  isBillable datetime,
  street datetime,
  fileSize mediumint,
  houseNumber date,
  phone float,
  exportId blob,
  childId boolean,
  blogId serial,
  logLevel float,
  likeCount enum,
  postalCode bigint,
  languageCode int
);

CREATE TABLE aggpayment2025 (
  id serial primary key,
  mapId date,
  dimension int,
  middleName date,
  username datetime,
  url time,
  nickname varchar,
  languageCode bigint,
  displayOrder timestamp,
  metaDescription decimal,
  discountCode smallint,
  isDeleted enum,
  totalAmount float,
  isEnabled datetime,
  ipAddress bigint,
  fileHash datetime,
  isHidden binary,
  fontFamily smallint,
  sessionId date
);

CREATE TABLE transaction (
  id serial primary key,
  labelText mediumint,
  taxRate bit,
  driverLicense set,
  apiVersion enum,
  endDate int,
  couponCode binary,
  customField2 date,
  headerImage smallint,
  forwardTo timestamp
);

CREATE TABLE user (
  id serial primary key,
  mimeType decimal,
  incidentId bit
);

CREATE TABLE record (
  id serial primary key,
  fileHash geometry,
  menuId float,
  amount serial,
  comment blob,
  expiryMonth point,
  insuranceId decimal,
  address date,
  dimension enum,
  avatar point,
  documentId timestamp,
  street decimal,
  audioUrl double,
  completedAt mediumint,
  completionRate timestamp,
  contactEmail text,
  state point,
  hashKey varchar,
  attemptCount date,
  logLevel enum,
  size tinyint,
  shippingAddress set,
  chargeId time,
  dateFormat bigint,
  actionType boolean,
  balance int,
  moduleId binary,
  mapId real,
  addressLine1 tinyint,
  managerId tinyint,
  maritalStatus set,
  friendId enum
);

CREATE TABLE src_customer_div_new (
  id serial primary key,
  name float,
  companyLogo boolean,
  headerImage varchar,
  monthlyRate enum,
  customerGroup bit,
  balance varchar,
  firstName varchar,
  creditLimit date,
  referralCode serial,
  feedId binary,
  content point,
  clientId bigint,
  businessType varchar,
  score mediumint
);

CREATE TABLE product (
  id serial primary key,
  brandId tinyint,
  loadTime blob,
  status set,
  password mediumint,
  facilityId set,
  cvv serial,
  attemptCount serial,
  shippingAddress bit,
  levelId serial,
  instructorId datetime,
  campaignId timestamp,
  jobTitle set,
  cardNumber geometry,
  languageCode set,
  description binary,
  exportId boolean,
  unit bigint,
  createdAt tinyint,
  creditLimit double,
  middleName bigint,
  creditCard varchar,
  frameRate set,
  enrollmentDate geometry,
  token smallint,
  appVersion serial,
  balance decimal
);

CREATE TABLE organization_status_legacy (
  id serial primary key,
  hostName set,
  formatType double,
  metaDescription int,
  startDate smallint,
  inactiveAt bigint,
  longitude text
);

CREATE TABLE organization_data (
  id serial primary key,
  feedbackId smallint,
  globalId enum,
  insuranceId real,
  meterNumber int,
  flagged double,
  name float,
  orderId mediumint,
  localeId datetime,
  customField2 time,
  isBillable boolean
);

CREATE TABLE logorder (
  id serial primary key,
  dateFormat date,
  memberCount decimal,
  bluetoothId tinyint,
  checkInTime real,
  customerGroup varchar,
  isHidden geometry,
  duration real,
  comment varchar,
  title bit,
  cvv datetime,
  domainName datetime,
  forwardTo tinyint,
  activeDevices bigint,
  configId point,
  fingerprint date,
  lastLoginAt set,
  moduleId bit
);

CREATE TABLE rel_company (
  id serial primary key,
  billingFrequency double,
  isPublic real,
  companyName point,
  metaTitle binary,
  sku double,
  iconPath tinyint,
  hiddenAt timestamp,
  gender decimal,
  isDefault enum,
  customerGroup double,
  accountType boolean
);

CREATE TABLE fact_customer (
  id serial primary key,
  bankAccount decimal,
  validUntil date,
  businessType binary,
  formatType geometry,
  isDeleted float,
  title timestamp,
  price set,
  cartId binary,
  feedbackId blob,
  balance boolean,
  endDate int,
  bannerImage boolean,
  budgetCode varchar,
  authToken blob,
  exchangeRate tinyint,
  channelId serial,
  localeId bigint,
  backupEmail datetime,
  id binary,
  driverLicense double,
  isEnabled varchar,
  cancelReason tinyint,
  algorithm boolean,
  lastLoginAt binary,
  documentId varchar
);

CREATE TABLE ver_account_type (
  id serial primary key,
  exportId binary,
  managerId timestamp,
  phone enum,
  algorithm tinyint,
  shippingAddress date,
  hourlyRate set,
  emergencyContact timestamp,
  contactPhone enum,
  priority decimal,
  email int,
  companyId real,
  actionType varchar,
  dataSource real,
  adminNotes time,
  domainName bit,
  id float,
  signature blob,
  address serial,
  houseNumber enum,
  dashboardId tinyint,
  businessType date,
  macAddress datetime,
  postalCode real,
  logLevel geometry,
  fingerprint geometry,
  faxNumber text
);

CREATE TABLE audit (
  id serial primary key,
  ipAddress date,
  documentId bigint,
  companyName date,
  geoLocation point,
  dialCode bit,
  listId set,
  expiryMonth geometry,
  employmentDate time,
  accountStatus serial,
  bankAccount bigint,
  attachmentUrl mediumint,
  feedId int,
  cardNumber bit,
  employeeId tinyint,
  localeId set,
  firstName set,
  signature mediumint,
  latitude real,
  fileName time,
  nickname int,
  maritalStatus tinyint
);

CREATE TABLE pub_product_status (
  id serial primary key,
  budgetCode point,
  amount geometry,
  customerGroup tinyint,
  iconPath bit,
  indexKey varchar,
  departmentCode date,
  facilityId point
);

CREATE TABLE cpyorder (
  id serial primary key,
  completedAt point,
  postalCode decimal,
  couponCode blob,
  companyName timestamp,
  size mediumint,
  appVersion geometry,
  moveId date,
  endDate decimal,
  brandId boolean,
  score datetime,
  password bigint,
  ipAddress point,
  addressLine2 bigint,
  modifiedAt boolean,
  itemCount binary,
  checkOutTime date,
  awardDate point,
  accountType point,
  machineId point,
  avatar set,
  localeId varchar,
  extractId text,
  isArchived int,
  iconPath float,
  depositAmount point,
  locationId serial,
  albumId real,
  isDefault mediumint,
  title binary
);

CREATE TABLE product_v1 (
  id serial primary key,
  expiryMonth mediumint,
  messageId time,
  middleName mediumint,
  dialCode double,
  levelId float,
  distributorId double,
  creditScore geometry,
  billingFrequency mediumint,
  globalId mediumint,
  avatar tinyint,
  domainName varchar,
  maskType smallint,
  logLevel binary,
  amount datetime,
  street float,
  balance binary,
  isDraft date
);

