CREATE TABLE order (
  id serial primary key,
  deliveryDate boolean,
  name serial,
  taxRate varchar,
  longitude date,
  brandId tinyint,
  category timestamp,
  emergencyContact tinyint,
  childId datetime,
  group point,
  maskType mediumint,
  incidentId binary,
  employeeCode datetime,
  industryType bigint,
  url set
);

CREATE TABLE fact_record_new (
  id serial primary key,
  amount tinyint,
  lastLoginAt varchar,
  orderStatus time,
  certificateId int,
  grade datetime,
  blogId int,
  price int,
  sku boolean
);

CREATE TABLE ver_config (
  id serial primary key,
  lastSeenAt date,
  friendId smallint,
  sessionId binary,
  loginAttempts time,
  logLevel real,
  status double,
  importId bigint,
  avatar enum,
  claimId point,
  timezone bit,
  cvv enum,
  integrationId boolean,
  token time,
  minLimit tinyint,
  education datetime,
  monthlyRate bigint,
  currency real,
  invoiceId bit,
  unit serial,
  orderStatus datetime,
  levelId time,
  linkId timestamp,
  loadTime serial,
  contactPhone date,
  comment bit,
  mapId geometry,
  incidentId tinyint,
  emailStatus serial,
  duration bit,
  errorMessage decimal,
  longitude tinyint
);

CREATE TABLE core_transaction (
  id serial primary key,
  unit double,
  shippingAddress smallint,
  menuId mediumint,
  password serial,
  mimeType int,
  backupEmail int,
  expiryYear bigint,
  articleId timestamp,
  meterNumber serial,
  mobileNumber real,
  endPoint bigint,
  invoiceId enum,
  formatType float,
  manufacturerId int,
  avatar double,
  errorMessage int,
  mainImage time
);

CREATE TABLE agg_product (
  id serial primary key,
  lockoutEnd point,
  followCount time,
  dealerId decimal,
  discount int,
  nickname enum
);

CREATE TABLE audit_map_2025 (
  id serial primary key,
  weight timestamp,
  lockoutEnd set,
  duration point,
  fontFamily boolean,
  metaKeywords enum
);

CREATE TABLE payment_rel_v1 (
  id serial primary key,
  isSystem text,
  bluetoothId geometry,
  latitude datetime,
  coordinateX datetime,
  defaultValue serial,
  isAdmin enum,
  maskType point,
  enabledAt mediumint,
  homePhone blob,
  businessType time,
  inactiveAt bit,
  attachmentUrl geometry,
  adminNotes double,
  employeeCode datetime,
  colorCode double
);

CREATE TABLE tmp_user (
  id serial primary key,
  floorNumber enum,
  coordinateX bigint,
  nickname double,
  longitude varchar,
  addressLine2 bit,
  cacheKey timestamp,
  localeId bigint,
  address datetime,
  feedbackId set,
  lastSeenAt enum,
  editedAt timestamp,
  metaTitle datetime
);

CREATE TABLE account (
  id serial primary key,
  fileType bit,
  faxNumber date,
  mobileNumber real,
  category int,
  birthDate blob,
  description double,
  longitude serial,
  messageId bit,
  endPoint decimal,
  authToken bit
);

CREATE TABLE order_div_v1 (
  id serial primary key,
  listingId blob,
  metaKeywords int,
  price decimal,
  hostName bit,
  favoriteCount geometry,
  isSystem tinyint,
  phone bit
);

CREATE TABLE sys_organization (
  id serial primary key,
  accountType double,
  lastSeenAt int,
  fileType blob,
  flagged date,
  lastName serial,
  homePhone real,
  colorCode blob,
  fontSize set,
  importId time,
  minLimit geometry,
  loadTime smallint,
  claimId mediumint,
  industryType point,
  name varchar,
  courseId bit,
  addressLine2 date,
  maxValue int,
  street geometry,
  integrationId binary,
  exchangeRate point,
  createdAt time,
  hiddenAt datetime,
  avatar blob
);

CREATE TABLE payment_extra (
  id serial primary key,
  friendId double,
  quantity geometry,
  companyId real,
  checkOutTime decimal,
  coordinateY text,
  enrollmentDate smallint,
  frameRate set,
  ipAddress varchar,
  deactivatedAt float,
  attemptCount float,
  phone int,
  favoriteCount real,
  jobTitle bigint,
  indexKey int,
  deviceType text,
  street varchar,
  authMethod float,
  invoiceId timestamp,
  customerGroup double,
  comment float,
  algorithm varchar,
  lastName blob,
  createdAt set,
  displayName geometry
);

CREATE TABLE tmp_account (
  id serial primary key,
  groupName boolean,
  bannerImage time,
  quantity smallint,
  group tinyint,
  gameId serial,
  frameRate timestamp,
  gender mediumint,
  messageId set,
  amount bigint,
  accountStatus boolean,
  id mediumint,
  startDate bit,
  firstName blob,
  balance blob,
  zipCode real,
  description text,
  emergencyContact decimal,
  childId binary,
  minLimit date,
  completionRate real,
  discountCode smallint,
  locationId geometry,
  friendId smallint,
  localeId varchar,
  monthlyRate point,
  address time,
  jobTitle real
);

CREATE TABLE ver_payment_info (
  id serial primary key,
  completedAt point,
  size int,
  cacheKey date,
  chargeId mediumint,
  shippingAddress blob,
  role point,
  email geometry,
  orderStatus geometry,
  password geometry,
  audioUrl geometry,
  distributorId enum,
  firmwareVersion time,
  avatar text,
  deviceId geometry,
  incidentId varchar,
  lastLoginAt mediumint,
  enrollmentDate mediumint
);

CREATE TABLE rel_company_extra (
  id serial primary key,
  firstName serial,
  category datetime,
  batchId decimal,
  mobileNumber enum,
  linkId decimal,
  machineId tinyint,
  contractId double,
  creditScore geometry,
  completedAt real,
  connectionString timestamp,
  gender point,
  phone varchar,
  headerImage date,
  insuranceId time,
  deletedAt smallint,
  keywords real,
  fileType text,
  enabledAt int,
  backupEmail datetime,
  dailyLimit decimal,
  size serial,
  mapId bigint,
  emergencyContact smallint,
  type timestamp,
  country timestamp,
  distributorId datetime,
  monthlyRate decimal,
  chatId datetime,
  gameId blob,
  guestId serial,
  accountType time
);

CREATE TABLE priv_payment (
  id serial primary key,
  apiKey enum,
  weight timestamp,
  documentId mediumint,
  age bigint,
  accessLevel binary,
  industryType real,
  group real,
  sku mediumint,
  lastName varchar,
  ipAddress double,
  currency smallint
);

CREATE TABLE dim_payment (
  id serial primary key,
  headerImage int,
  createdAt tinyint,
  enabledAt smallint,
  moduleId tinyint,
  contentType float,
  awardDate double,
  blogId mediumint,
  apiKey set,
  moveId blob,
  zipCode double,
  contactPhone bit,
  deviceId timestamp,
  password geometry,
  duration mediumint,
  endPoint boolean,
  integrationId boolean,
  content date,
  channelId int,
  nickname decimal,
  menuId binary,
  thumbnail bigint,
  url time
);

CREATE TABLE core_organization_log (
  id serial primary key,
  isVerified float,
  name time,
  certificateId boolean,
  longitude double,
  email tinyint,
  menuId enum,
  iconPath set,
  headerImage tinyint,
  isRequired boolean,
  currencyCode real,
  layerId double,
  deviceId varchar
);

CREATE TABLE stgorganizationstatus (
  id serial primary key,
  accountNumber double,
  status date,
  clockOut real,
  domainName float,
  maxLimit real,
  layerId geometry,
  password set,
  exchangeRate int,
  attachmentUrl blob
);

CREATE TABLE transaction_extra (
  id serial primary key,
  linkId datetime,
  dateFormat timestamp,
  authToken tinyint,
  groupName set,
  formatType serial,
  levelId mediumint,
  url decimal,
  version datetime,
  isBillable bigint,
  token mediumint,
  balance varchar,
  amount set,
  loginCount timestamp,
  displayOrder double,
  eventDate tinyint,
  cvv decimal,
  indexKey date,
  authMethod serial,
  dialCode binary,
  maritalStatus geometry,
  fingerprint point,
  ipAddress mediumint,
  courseId bit,
  lastSeenAt bigint
);

CREATE TABLE payment (
  id serial primary key,
  orderId timestamp,
  courseId smallint,
  addressLine1 point,
  role time,
  faxNumber double,
  minValue serial,
  updatedAt mediumint,
  group float,
  budgetCode varchar,
  department mediumint,
  addressLine2 double,
  url datetime,
  token smallint,
  creditCard varchar,
  companyName set,
  expiryMonth mediumint,
  avatar int,
  birthDate point,
  referralCode double,
  orderStatus time,
  authorId boolean,
  apiVersion double,
  sessionId double,
  nickname text,
  deviceToken serial,
  integrationId int,
  exportId time,
  foregroundColor bigint,
  description boolean,
  age decimal,
  metaKeywords smallint
);

CREATE TABLE tmp_config_v2 (
  id serial primary key,
  isLocked decimal,
  departmentCode boolean,
  colorCode set,
  fromDate float,
  creditLimit time,
  localeId date,
  appVersion blob,
  companyLogo float,
  eventDate smallint,
  checkInTime int,
  geoLocation float,
  loadTime tinyint,
  amount point,
  metaTitle date
);

CREATE TABLE pub_company (
  id serial primary key,
  taxRate bigint,
  customField2 binary,
  mimeType mediumint,
  sku text,
  comment tinyint,
  clockIn real,
  ipAddress binary,
  maritalStatus point,
  metaKeywords double,
  activeDevices blob
);

CREATE TABLE customer_2025 (
  id serial primary key,
  faxNumber text,
  sessionId geometry,
  referralCode decimal
);

CREATE TABLE audit (
  id serial primary key,
  mapId serial,
  brandId binary,
  followCount time,
  moveId set,
  eventDate serial,
  documentId real,
  countryCode decimal,
  linkId boolean,
  isBillable binary,
  priority boolean,
  zipCode blob,
  abandonedCartId varchar,
  mainImage boolean,
  companyName double,
  buildNumber mediumint,
  connectionString boolean,
  emailStatus set,
  category timestamp,
  distributorId geometry,
  isAdmin binary,
  middleName point,
  foregroundColor datetime,
  createdAt set,
  discount smallint,
  street time,
  downloadCount decimal,
  maxValue geometry,
  deliveryDate tinyint
);

CREATE TABLE inventory (
  id serial primary key,
  bankAccount time,
  displayOrder enum,
  dateFormat date,
  createdAt double,
  lastSeenAt mediumint
);

CREATE TABLE productmeta (
  id serial primary key,
  isSystem real,
  discount set,
  phone date,
  configId serial,
  billingFrequency bit,
  token tinyint,
  attachmentUrl blob,
  updatedAt text,
  description datetime
);

CREATE TABLE customerv2 (
  id serial primary key,
  earnedPoints text,
  jobTitle float,
  configId blob,
  exchangeRate bit,
  apiKey real,
  listId bigint,
  fingerprint varchar
);

CREATE TABLE pub_account (
  id serial primary key,
  contactPhone real,
  isDraft blob
);

CREATE TABLE company (
  id serial primary key,
  audioUrl bigint,
  bookingDate timestamp,
  fromDate int,
  companyLogo binary,
  authorId varchar
);

CREATE TABLE recorddata (
  id serial primary key,
  attachmentUrl double,
  dailyLimit serial,
  category blob,
  fingerprint float,
  cityName point,
  clientId binary,
  updatedAt int,
  firstName datetime,
  exportId point,
  listingId blob,
  fontFamily timestamp,
  lastName point,
  code text,
  languageCode bigint
);

CREATE TABLE ext_organization_notifications (
  id serial primary key,
  appVersion bigint,
  meterNumber date,
  password enum,
  content mediumint,
  cacheKey blob,
  validUntil binary,
  claimId text,
  tags bigint,
  documentId int,
  abandonedCartId boolean,
  token geometry,
  dailyLimit smallint,
  comment set,
  endPoint smallint,
  mainImage binary,
  sessionId smallint,
  downloadCount binary,
  layerId decimal,
  awardDate boolean
);

CREATE TABLE tbl_record (
  id serial primary key,
  url text,
  dimension bigint,
  contractId set,
  backupEmail date,
  articleId time,
  authToken double,
  billingCycle date,
  createdAt tinyint,
  employeeCode boolean,
  gateId double,
  lastName blob,
  forwardTo mediumint,
  employmentDate float,
  salary double,
  isFeatured bigint,
  attachmentUrl varchar,
  orderId int,
  loadTime smallint,
  country float,
  category enum,
  thumbnail binary,
  joinDate enum,
  customField1 date,
  isDeleted real,
  dashboardId timestamp
);

CREATE TABLE cpyrecord (
  id serial primary key,
  analyticsId decimal,
  chargeId bit,
  incidentId boolean,
  amount timestamp,
  hiddenAt smallint,
  brandId tinyint,
  endPoint time,
  algorithm text,
  accountType blob,
  url timestamp,
  fingerprint float,
  coordinateY geometry,
  defaultValue smallint,
  deviceToken date,
  timezone enum,
  startDate varchar,
  firmwareVersion time,
  city bigint,
  firstName blob,
  priority binary,
  industryType point,
  linkId int,
  comment float
);

CREATE TABLE vw_customer_2025 (
  id serial primary key,
  albumId tinyint,
  levelId float,
  connectionString bigint,
  weight smallint,
  phone date,
  listId blob,
  comment binary,
  cancelReason float,
  avatar geometry,
  minValue timestamp,
  type float,
  address float,
  status bigint,
  url real,
  balance binary,
  fromDate enum,
  faxNumber geometry,
  creditLimit tinyint,
  exportId boolean,
  discount float,
  earnedPoints tinyint,
  keywords serial,
  companyName serial,
  inactiveAt mediumint,
  coverImage real,
  chatId smallint
);

CREATE TABLE vw_audit (
  id serial primary key,
  listId set,
  createdAt date,
  abandonedCartId float,
  houseNumber blob,
  email smallint,
  contactPhone set,
  employeeCode blob,
  errorCode datetime,
  coverImage timestamp,
  hostName enum,
  fileName bit,
  accountType float,
  analyticsId blob,
  isVerified time,
  listingId bit,
  fromDate timestamp,
  handlerId set,
  middleName int
);

CREATE TABLE record (
  id serial primary key,
  customerId real,
  paymentMethod blob,
  accountType timestamp,
  ipAddress bigint,
  fontFamily time,
  employmentDate varchar,
  contactPhone decimal,
  forwardTo decimal,
  attachmentUrl geometry,
  shippingAddress decimal,
  endPoint double,
  articleId timestamp,
  gender boolean,
  referralCode serial,
  name geometry,
  minLimit real,
  fileType float,
  licenseKey boolean,
  machineId text,
  moveId float
);

CREATE TABLE tbl_payment (
  id serial primary key,
  filterType mediumint,
  dateFormat enum,
  attachmentUrl datetime,
  favoriteCount double,
  totalAmount binary,
  group timestamp,
  title double,
  followCount bigint,
  dialCode binary,
  formatType mediumint,
  backupEmail double,
  agentId blob,
  algorithm geometry
);

CREATE TABLE company (
  id serial primary key,
  duration timestamp,
  fontFamily bigint,
  importId date,
  deviceToken smallint,
  isLocked bit,
  dashboardId blob,
  expiryDate bit,
  weight double,
  abandonedCartId mediumint,
  copyRight tinyint,
  earnedPoints float,
  isDeleted double,
  insertedAt varchar,
  state text,
  menuId tinyint,
  configId serial,
  gender bigint
);

CREATE TABLE log_product_legacy (
  id serial primary key,
  albumId tinyint,
  homePhone float,
  licenseKey real,
  foregroundColor point,
  metaDescription date,
  createdAt smallint,
  isArchived timestamp,
  taxRate serial,
  contactEmail int,
  lastName varchar,
  isPublic tinyint,
  linkId date,
  title binary,
  isRequired smallint,
  password varchar,
  name bigint,
  sku point,
  alertType time,
  url mediumint,
  balance decimal
);

CREATE TABLE vw_audit (
  id serial primary key,
  messageId enum,
  metadata bigint,
  expiryDate binary,
  salary real,
  timezone point,
  expiryYear geometry,
  content int,
  moduleId set,
  errorMessage mediumint,
  birthDate timestamp,
  ipAddress decimal,
  contactName float,
  exportId enum,
  contentType enum,
  lockoutEnd float,
  brandId binary
);

CREATE TABLE logproduct (
  id serial primary key,
  contactName int,
  logLevel datetime,
  metaTitle float,
  downloadCount tinyint,
  messageId float,
  amount decimal,
  errorMessage bit,
  dialCode point,
  city real,
  creditCard set,
  isDraft varchar,
  loadTime serial,
  hostName bit,
  customerId float,
  tags tinyint,
  layerId smallint,
  joinDate boolean,
  expiryYear varchar,
  chatId serial,
  isDeleted timestamp,
  id text,
  displayName decimal,
  type mediumint
);

CREATE TABLE pub_audit_2025 (
  id serial primary key,
  layerId set,
  audioUrl varchar,
  bannerImage bit,
  username varchar,
  joinDate bit,
  billingCycle float,
  dataSource smallint,
  lockoutEnd boolean,
  price text
);

CREATE TABLE priv_order (
  id serial primary key,
  email double,
  machineId serial,
  companyId double,
  thumbnail real,
  employeeCode binary,
  expiryDate varchar,
  deliveryDate datetime,
  courseId timestamp,
  city mediumint,
  longitude tinyint,
  address point,
  houseNumber text,
  abandonedCartId geometry,
  contractId binary,
  loginAttempts smallint,
  configId time,
  cartId enum,
  budgetCode decimal,
  deviceType varchar,
  createdAt boolean
);

CREATE TABLE order (
  id serial primary key,
  state blob,
  localeId decimal,
  bannerImage double,
  contactPhone mediumint,
  houseNumber decimal,
  contactEmail enum,
  billingFrequency decimal,
  moduleId int,
  weight point,
  validUntil serial,
  integrationId point,
  createdAt text,
  keyId date,
  facilityId binary,
  currency int,
  phone set,
  forwardTo set,
  title set,
  companyName varchar,
  contractId datetime,
  mainImage double,
  street varchar,
  metadata int
);

CREATE TABLE priv_user_status (
  id serial primary key,
  rating datetime,
  expiryYear geometry,
  checkOutTime set,
  avatar binary,
  listId geometry,
  cloudId bit,
  expiryDate blob,
  clientId time,
  dueDateAt datetime,
  authorId time,
  comment bit,
  deletedAt blob,
  defaultLang point,
  unit tinyint
);

CREATE TABLE cpy_transaction_2024 (
  id serial primary key,
  employeeCode date,
  comment datetime,
  bookingDate smallint,
  geoLocation text,
  content datetime,
  code mediumint,
  shippingAddress time,
  integrationId date,
  isBillable set,
  deviceType time,
  keywords date,
  title bigint,
  activeDevices bit,
  metadata point,
  backupEmail time,
  filterType time,
  loginCount smallint,
  completedAt double,
  state int,
  isLocked bigint,
  mobileNumber blob,
  updatedAt blob,
  isEnabled smallint,
  avatar tinyint,
  coordinateY varchar,
  machineId timestamp,
  expiryDate varchar,
  username datetime,
  groupName set,
  actionType blob,
  editedAt double
);

CREATE TABLE log_order (
  id serial primary key,
  firstName geometry,
  courseId int,
  mapId smallint,
  minLimit float,
  ipAddress bit,
  orderId bigint,
  houseNumber date,
  comment bigint,
  avatar boolean,
  isDefault geometry,
  enrollmentDate bit,
  deletedAt varchar,
  attachmentUrl blob,
  brandId enum,
  token mediumint,
  menuId bigint,
  signature boolean,
  bookingDate enum,
  isBillable boolean,
  frameRate boolean
);

CREATE TABLE app_audit_archive_new (
  id serial primary key,
  isAdmin decimal,
  marketId decimal,
  coverImage timestamp
);

CREATE TABLE app_transaction (
  id serial primary key,
  cacheKey serial,
  createdAt date,
  customerId boolean,
  courseId decimal,
  companyName varchar,
  metadata boolean,
  metaTitle timestamp,
  layerId binary,
  budgetCode int,
  followCount text,
  faxNumber time,
  maxLimit mediumint,
  address datetime,
  sessionId geometry,
  deviceToken tinyint,
  fontSize decimal,
  businessType set,
  isSystem datetime,
  appVersion real,
  creditScore timestamp,
  cvv text,
  activeDevices timestamp,
  childId blob,
  state text,
  marketId serial,
  brandId binary,
  fingerprint time,
  accessLevel varchar,
  groupName double,
  enabledAt mediumint,
  timezone binary
);

