CREATE TABLE dimrecord2024 (
  id serial primary key,
  actionType int,
  awardDate timestamp,
  metaKeywords tinyint,
  age float,
  copyRight datetime,
  mapId smallint,
  attemptCount serial,
  countryCode int,
  moveId blob,
  postalCode enum,
  batchId text,
  linkId tinyint,
  middleName smallint,
  lockoutEnd bit,
  checkOutTime smallint,
  birthDate blob,
  channelId point,
  expiryMonth bigint,
  incidentId mediumint,
  metaTitle float,
  cloudId point,
  firstName double
);

CREATE TABLE factaccount (
  id serial primary key,
  longitude smallint,
  address float,
  signature enum,
  checkOutTime real,
  quantity bit,
  followCount int,
  value time,
  coverImage date,
  department decimal,
  shippingAddress bit,
  sessionId binary,
  authMethod tinyint,
  displayOrder blob
);

CREATE TABLE agg_customer (
  id serial primary key,
  licenseKey time,
  messageId boolean,
  minLimit datetime,
  enrollmentDate text,
  distributorId time,
  articleId int,
  iconPath double,
  password bit,
  cancelReason enum,
  channelId float,
  levelId date,
  companyName real,
  thumbnail decimal,
  feedId smallint,
  likeCount enum,
  size serial,
  houseNumber smallint,
  deviceType enum,
  companyId geometry,
  isDefault timestamp,
  middleName boolean,
  isAdmin boolean,
  metaKeywords boolean,
  facilityId varchar,
  customField2 real,
  emergencyContact bit,
  bookingDate timestamp,
  eventDate blob,
  name binary,
  exportId timestamp
);

CREATE TABLE stg_record (
  id serial primary key,
  connectionString datetime,
  accountNumber real,
  avatar enum,
  balance enum,
  dealerId boolean,
  flagged geometry,
  extractId datetime,
  productCode point,
  sku tinyint,
  grade text,
  groupName varchar,
  taxRate bit,
  driverLicense time,
  houseNumber double,
  accessLevel bit,
  mimeType varchar,
  cacheKey double,
  email timestamp,
  emailStatus datetime,
  configId datetime,
  dataSource smallint,
  description point,
  expiryYear mediumint,
  code smallint,
  feedbackId bigint,
  frameRate time,
  insertedAt double,
  lastName smallint,
  cityName mediumint,
  orderId point
);

CREATE TABLE account (
  id serial primary key,
  driverLicense enum,
  instanceId binary,
  analyticsId time,
  deviceToken boolean,
  budgetCode varchar
);

CREATE TABLE ver_user_type (
  id serial primary key,
  latitude tinyint,
  emergencyContact geometry,
  earnedPoints bigint,
  isHidden point,
  checkOutTime smallint,
  configId geometry,
  linkId time,
  metaTitle time
);

CREATE TABLE ordertype (
  id serial primary key,
  education time,
  version bigint,
  companyName varchar,
  actionType blob,
  grade enum,
  accountNumber timestamp,
  memberCount float,
  fileHash smallint,
  balance double,
  description geometry,
  countryCode binary
);

CREATE TABLE tbluserdata (
  id serial primary key,
  isLocked serial,
  listingId bit,
  companyId bit,
  insertedAt bigint,
  weight int
);

CREATE TABLE account_v2 (
  id serial primary key,
  creditCard text,
  age enum,
  code decimal,
  managerId datetime,
  ipAddress tinyint,
  isDeleted serial,
  enabledAt bigint,
  loadTime datetime,
  friendId float
);

CREATE TABLE payment_map (
  id serial primary key,
  customerGroup decimal,
  longitude point,
  hashKey time,
  value text,
  friendId binary,
  sessionId point,
  amount serial,
  accessLevel enum,
  height smallint,
  cardNumber int,
  billingCycle bigint
);

CREATE TABLE orderextra (
  id serial primary key,
  blogId set,
  createdAt double,
  gateId text,
  emergencyContact int,
  quantity smallint,
  comment point,
  priority bigint,
  companyLogo float,
  isPublic geometry,
  courseId smallint,
  title set
);

CREATE TABLE record_div (
  id serial primary key,
  totalAmount enum,
  albumId enum
);

CREATE TABLE organization (
  id serial primary key,
  category tinyint,
  lockoutEnd tinyint,
  actionType timestamp,
  alertType date,
  birthDate tinyint,
  employeeId blob,
  appVersion float,
  businessType text,
  instanceId bit,
  dateFormat real,
  facilityId binary,
  guestId boolean,
  size mediumint,
  amount real,
  isActive text,
  endPoint time,
  state varchar,
  deactivatedAt binary,
  dashboardId real,
  uuid bigint,
  email datetime,
  fileName int,
  attachmentUrl tinyint,
  orderId int,
  loginAttempts real,
  completionRate point,
  loginCount enum,
  colorCode mediumint,
  updatedAt geometry,
  group boolean,
  maskType bigint
);

CREATE TABLE priv_inventory (
  id serial primary key,
  algorithm enum,
  facilityId bit,
  zipCode int,
  currencyCode smallint,
  guestId int
);

CREATE TABLE cpy_company (
  id serial primary key,
  orderId bit,
  configId datetime,
  endPoint geometry,
  brandId int,
  age set,
  isHidden boolean,
  firmwareVersion binary,
  state blob,
  forwardTo date,
  layerId decimal,
  gender int,
  ipAddress smallint,
  homePhone enum,
  integrationId text,
  createdAt enum,
  campaignId timestamp,
  accessLevel int,
  indexKey bigint,
  companyLogo varchar,
  completionRate binary,
  depositAmount set,
  shippingAddress geometry,
  managerId set
);

CREATE TABLE ordermapv2 (
  id serial primary key,
  category bigint,
  creditCard bit,
  couponCode text,
  customField2 timestamp,
  distributorId decimal,
  isPublic bit,
  startDate bigint,
  isLocked set,
  courseId set
);

CREATE TABLE customer (
  id serial primary key,
  deliveryDate binary,
  size bigint,
  description int,
  accessLevel binary,
  addressLine1 real,
  faxNumber blob,
  city real,
  appVersion point,
  globalId bigint,
  clockOut tinyint
);

CREATE TABLE log_product_extra (
  id serial primary key,
  flagged date,
  status blob,
  avatar enum,
  middleName double,
  timezone geometry,
  activeDevices binary,
  channelId text,
  description varchar,
  audioUrl time,
  metaDescription decimal,
  deletedAt enum,
  analyticsId tinyint,
  name tinyint,
  dialCode real,
  foregroundColor binary,
  documentId int,
  domainName decimal,
  hashKey float,
  customerId tinyint,
  labelText double,
  layerId bit,
  dealerId point,
  extractId date,
  state tinyint,
  iconPath text
);

CREATE TABLE agg_user_rel (
  id serial primary key,
  incidentId bigint,
  displayOrder int
);

CREATE TABLE tmp_company (
  id serial primary key,
  productCode bit,
  dependentId time,
  exportId set,
  copyRight enum,
  totalAmount boolean,
  comment decimal,
  dealerId blob,
  invoiceId real,
  colorCode enum,
  isDraft set,
  fontFamily boolean,
  content timestamp,
  groupName point,
  description text,
  jobTitle timestamp,
  departmentCode enum,
  lastName geometry,
  buildNumber blob,
  clockOut mediumint,
  createdAt text,
  endDate bit,
  metaDescription blob,
  contactEmail mediumint,
  geoLocation binary,
  completedAt bit,
  customField1 bigint,
  employmentDate blob,
  moveId binary,
  shippingAddress boolean,
  sessionId serial,
  activeDevices boolean
);

CREATE TABLE fact_account_info (
  id serial primary key,
  isRequired time,
  maxLimit point,
  formatType bigint,
  latitude timestamp,
  dailyLimit set,
  status mediumint,
  awardDate set,
  title bit,
  country serial,
  content decimal,
  minValue bit,
  displayOrder time,
  fileName time,
  mainImage enum,
  downloadCount serial,
  expiryDate double,
  middleName point,
  expiryYear mediumint,
  abandonedCartId bit,
  coverImage point,
  hourlyRate text,
  hashKey float,
  keywords decimal,
  creditCard serial
);

CREATE TABLE ver_payment_meta (
  id serial primary key,
  minValue smallint,
  machineId blob,
  authMethod datetime,
  discountCode text
);

CREATE TABLE dst_record (
  id serial primary key,
  marketId binary,
  clientId geometry,
  monthlyRate blob,
  updatedAt decimal,
  foregroundColor blob,
  iconPath float
);

CREATE TABLE order (
  id serial primary key,
  guestId time,
  channelId binary,
  localeId tinyint,
  id binary,
  maxLimit enum,
  isSystem decimal,
  department timestamp,
  ipAddress geometry,
  priority set,
  gender boolean,
  grade serial,
  isRequired int,
  exportId point,
  deletedAt float,
  couponCode tinyint,
  menuId boolean,
  errorCode varchar,
  authorId enum,
  indexKey double,
  levelId datetime
);

CREATE TABLE cpy_record (
  id serial primary key,
  cityName varchar,
  dailyLimit geometry,
  accountType text,
  orderStatus bigint,
  updatedAt double,
  grade double,
  browserType float,
  checkOutTime real,
  authToken int,
  isDefault bigint,
  nickname set,
  feedId binary,
  headerImage tinyint,
  marketId set,
  username bit,
  configId varchar,
  downloadCount bit,
  fileName float,
  keyId date,
  paymentMethod boolean,
  enrollmentDate timestamp,
  accountNumber blob,
  price smallint,
  customField1 time,
  unit int,
  street varchar,
  expiryMonth point,
  education real,
  comment smallint
);

CREATE TABLE audit (
  id serial primary key,
  facilityId bigint,
  lastLoginAt geometry,
  algorithm float,
  deviceType serial,
  checkInTime timestamp,
  rating bit,
  exchangeRate tinyint,
  modifiedAt date,
  clientId varchar,
  paymentMethod real,
  brandId point,
  unit bit,
  timezone double,
  displayName geometry,
  content serial,
  businessType point,
  maritalStatus serial,
  referralCode int,
  deviceToken real,
  password bigint,
  jobTitle boolean,
  completedAt binary
);

CREATE TABLE config (
  id serial primary key,
  depositAmount set,
  address smallint,
  gameId decimal,
  actionType geometry,
  title bit,
  description boolean,
  fontSize serial,
  maxValue datetime,
  cardHolder real,
  countryCode time,
  domainName tinyint,
  birthDate time,
  createdAt serial,
  displayOrder bigint,
  isBillable smallint,
  maxLimit serial
);

CREATE TABLE app_inventory_2025 (
  id serial primary key,
  costCenter time,
  linkId timestamp,
  loadTime enum,
  salary float,
  status decimal,
  latitude binary,
  id set,
  memberCount geometry,
  ipAddress point,
  iconPath blob,
  isDraft geometry,
  fingerprint double,
  awardDate bit,
  configId smallint,
  productCode enum
);

CREATE TABLE order_rel (
  id serial primary key,
  isSystem set,
  importId boolean,
  referralCode double,
  houseNumber serial,
  bankAccount blob,
  filterType mediumint,
  managerId binary,
  minLimit varchar,
  isArchived bigint,
  buildNumber float,
  orderId timestamp,
  companyId serial,
  friendId mediumint,
  feedId bigint,
  dashboardId mediumint,
  authToken time,
  hiddenAt decimal,
  blogId tinyint,
  contactPhone double,
  batchId set,
  channelId tinyint,
  appVersion set,
  checkOutTime enum,
  copyRight boolean
);

CREATE TABLE paymentrel (
  id serial primary key,
  isBillable set,
  tags point,
  accessLevel smallint,
  isDefault binary,
  validUntil int,
  billingFrequency binary,
  fileSize date,
  dialCode blob,
  avatar time,
  username mediumint,
  insertedAt time,
  totalAmount bit,
  billingCycle bigint,
  zipCode point,
  type smallint,
  feedbackId tinyint,
  balance bigint,
  lastSeenAt decimal,
  dealerId enum
);

CREATE TABLE vertransaction (
  id serial primary key,
  accountStatus geometry,
  dealerId timestamp,
  productCode geometry,
  discountCode text,
  sessionId set,
  attachmentUrl serial,
  keyId mediumint,
  token smallint,
  companyId time,
  avatar real,
  likeCount smallint,
  actionType enum,
  displayOrder blob,
  isVerified int,
  cacheKey double,
  listingId varchar,
  birthDate float,
  longitude boolean,
  currencyCode point,
  paymentMethod point,
  weight blob,
  dueDateAt serial,
  group real,
  enrollmentDate varchar,
  emergencyContact date,
  friendId set,
  layerId varchar,
  password int,
  postalCode double
);

CREATE TABLE orderextra (
  id serial primary key,
  maxValue binary,
  appVersion datetime,
  email time,
  isBillable smallint,
  editedAt float,
  grade boolean,
  moveId real,
  dateFormat timestamp,
  shippingAddress blob,
  incidentId real,
  mainImage date,
  group enum,
  downloadCount enum,
  analyticsId smallint,
  isArchived boolean,
  createdAt time,
  department set,
  marketId tinyint,
  timezone time,
  memberCount decimal,
  isPublic date
);

CREATE TABLE vw_config_meta_2025 (
  id serial primary key,
  driverLicense mediumint,
  maxValue bit,
  followCount int,
  listId time,
  longitude smallint,
  dateFormat boolean,
  completedAt time,
  isArchived smallint,
  isFeatured smallint,
  memberCount timestamp,
  version varchar,
  brandId timestamp,
  displayName datetime,
  documentId serial,
  mapId bit,
  lastName date,
  jobTitle smallint,
  addressLine1 datetime,
  group varchar,
  endPoint blob,
  timezone float,
  foregroundColor varchar,
  insertedAt timestamp,
  description point,
  algorithm timestamp,
  code date,
  linkId int,
  expiryDate geometry
);

CREATE TABLE company (
  id serial primary key,
  countryCode binary,
  taxRate time,
  joinDate float,
  city enum,
  longitude time,
  courseId real,
  minLimit decimal,
  cloudId real,
  firstName real,
  endDate float,
  isLocked set,
  metaTitle text,
  productCode serial,
  accountType timestamp,
  dealerId set,
  analyticsId bit,
  feedbackId timestamp,
  category timestamp,
  maskType point,
  batchId timestamp,
  deletedAt timestamp,
  companyName varchar
);

CREATE TABLE config_seg (
  id serial primary key,
  loginCount mediumint,
  isArchived text,
  gender smallint,
  age float,
  addressLine1 decimal,
  browserType tinyint,
  mobileNumber smallint,
  dataSource varchar,
  cancelReason smallint,
  companyId bit,
  deviceToken timestamp,
  cacheKey serial,
  followCount bigint,
  fontSize datetime,
  name mediumint,
  exchangeRate enum,
  address geometry,
  attemptCount serial,
  likeCount time,
  title serial,
  defaultValue real,
  price smallint,
  enabledAt set,
  height timestamp,
  meterNumber float,
  managerId point,
  fromDate int,
  weight binary,
  city smallint
);

CREATE TABLE recordrel (
  id serial primary key,
  favoriteCount tinyint,
  brandId set,
  companyId enum,
  createdAt geometry,
  expiryDate blob,
  bookingDate bigint,
  iconPath text,
  contractId mediumint,
  configId time,
  grade int,
  activeDevices blob,
  moduleId int,
  layerId tinyint,
  emergencyContact boolean,
  title bigint,
  downloadCount mediumint,
  signature decimal,
  paymentMethod bigint,
  cityName int,
  fileType double,
  documentId double,
  attachmentUrl date,
  isVerified boolean,
  thumbnail real,
  expiryMonth time,
  dependentId binary,
  bannerImage smallint,
  mimeType smallint,
  fileHash blob,
  audioUrl double,
  logLevel double
);

CREATE TABLE stg_record_rel_2024 (
  id serial primary key,
  accountType real,
  height int,
  role time,
  version date,
  comment tinyint,
  dailyLimit serial,
  colorCode point,
  displayOrder datetime,
  levelId set,
  messageId boolean,
  deliveryDate point,
  budgetCode serial,
  age mediumint,
  birthDate geometry,
  certificateId float,
  instructorId bigint,
  industryType varchar,
  isSystem date,
  country decimal,
  accountStatus bigint,
  articleId bit,
  licenseKey varchar,
  sku timestamp,
  brandId tinyint,
  completedAt varchar
);

CREATE TABLE cpy_inventory (
  id serial primary key,
  defaultLang timestamp,
  deletedAt decimal
);

CREATE TABLE tmptransactionarchive (
  id serial primary key,
  token boolean,
  metaTitle blob,
  domainName int,
  address float,
  handlerId text,
  gender boolean,
  couponCode date,
  fontFamily blob,
  deviceType double,
  group date,
  password enum,
  isSystem bit,
  birthDate bit,
  latitude real,
  extractId float,
  timezone serial,
  deviceId serial,
  category datetime,
  layerId datetime,
  completedAt bigint,
  cartId tinyint,
  salary timestamp,
  orderStatus serial,
  displayName geometry,
  dateFormat decimal,
  keyId varchar,
  lockoutEnd timestamp
);

CREATE TABLE config (
  id serial primary key,
  isLocked date,
  defaultValue set,
  postalCode text,
  minLimit tinyint,
  jobTitle decimal,
  maskType boolean,
  bankAccount binary,
  metaTitle int,
  token timestamp,
  lastLoginAt enum,
  companyName real,
  amount datetime,
  colorCode geometry,
  country set,
  countryCode tinyint,
  updatedAt varchar,
  firmwareVersion varchar,
  balance smallint,
  category decimal,
  insuranceId boolean,
  nickname bit,
  loadTime mediumint,
  activeDevices serial,
  signature boolean,
  fontFamily double,
  checkOutTime varchar,
  emergencyContact int,
  apiKey serial,
  completedAt blob,
  modifiedAt mediumint
);

CREATE TABLE coreaccount (
  id serial primary key,
  fingerprint time,
  bookingDate enum,
  creditLimit smallint
);

CREATE TABLE user_status (
  id serial primary key,
  faxNumber smallint,
  dialCode text,
  locationId binary,
  bankAccount geometry,
  enrollmentDate point,
  contractId int,
  errorCode bit,
  endDate point,
  fingerprint smallint,
  clockIn point,
  productCode date,
  orderStatus binary,
  lastName set
);

CREATE TABLE ver_account_map (
  id serial primary key,
  mainImage decimal,
  checkInTime point
);

CREATE TABLE src_user_hist (
  id serial primary key,
  favoriteCount int,
  companyLogo enum,
  marketId blob,
  filterType binary,
  cardNumber decimal,
  currency datetime,
  bookingDate datetime,
  firstName double,
  agentId float,
  dueDateAt serial,
  defaultValue time,
  minValue int,
  email mediumint,
  documentId geometry,
  customField2 boolean,
  customField1 float,
  companyId datetime,
  accountNumber bit,
  paymentMethod datetime,
  couponCode varchar,
  endPoint tinyint,
  currencyCode varchar,
  state point,
  apiVersion bigint,
  abandonedCartId varchar,
  bannerImage bigint
);

CREATE TABLE olk_record (
  id serial primary key,
  channelId bit,
  sessionId bit,
  expiryMonth mediumint,
  gender point
);

CREATE TABLE ext_company (
  id serial primary key,
  clientId boolean,
  shippingAddress double
);

CREATE TABLE order (
  id serial primary key,
  blogId real,
  houseNumber decimal,
  integrationId decimal,
  fileType bigint,
  authorId date,
  contractId bigint,
  postalCode smallint,
  fileSize time,
  isRequired binary,
  name float,
  floorNumber binary,
  labelText datetime,
  indexKey point,
  middleName enum,
  paymentMethod datetime,
  accountNumber point,
  checkOutTime timestamp,
  domainName date,
  avatar bigint,
  category boolean,
  minLimit float,
  connectionString binary,
  budgetCode mediumint,
  fileName set,
  cancelReason time,
  claimId double
);

CREATE TABLE config_legacy (
  id serial primary key,
  discountCode int,
  isBillable blob,
  balance float,
  houseNumber bit,
  lastLoginAt tinyint,
  industryType date,
  expiryYear blob,
  clockOut enum,
  accountType boolean,
  exchangeRate boolean,
  instructorId enum,
  authorId tinyint,
  loadTime time,
  flagged varchar,
  monthlyRate tinyint,
  dataSource tinyint,
  longitude timestamp,
  dueDateAt tinyint
);

CREATE TABLE privorganization (
  id serial primary key,
  maskType decimal,
  metadata date,
  menuId serial,
  groupName serial,
  dialCode binary,
  thumbnail int,
  machineId set,
  distributorId datetime,
  customerGroup enum
);

CREATE TABLE dstorderextratemp (
  id serial primary key,
  department bit,
  category tinyint,
  folderPath timestamp,
  amount bigint,
  batchId double,
  copyRight blob,
  isBillable decimal,
  customField2 geometry,
  coverImage bigint,
  state double,
  age tinyint,
  courseId set,
  likeCount geometry,
  education set,
  size serial,
  certificateId date,
  costCenter point,
  insuranceId blob,
  moduleId enum,
  hashKey int,
  height blob,
  grade int,
  alertType point,
  birthDate date,
  favoriteCount smallint,
  expiryDate binary,
  validUntil geometry,
  description blob
);

