CREATE TABLE record_div (
  id serial primary key,
  companyName binary,
  amount int,
  couponCode double
);

CREATE TABLE tmp_organization (
  id serial primary key,
  contentType text,
  handlerId smallint,
  downloadCount boolean,
  longitude set,
  apiKey set,
  accountNumber date,
  isDraft double,
  gameId binary,
  orderStatus varchar,
  address varchar,
  customerId double,
  phone date,
  status datetime,
  instructorId set,
  hostName tinyint,
  fileType bit,
  alertType set,
  languageCode blob,
  distributorId set,
  joinDate float,
  avatar date
);

CREATE TABLE accounttemp (
  id serial primary key,
  contactPhone boolean,
  address boolean,
  displayName boolean,
  weight smallint,
  timezone real,
  code time,
  totalAmount mediumint,
  backupEmail decimal,
  sessionId enum,
  listingId text,
  price serial,
  meterNumber geometry,
  dataSource int,
  bookingDate serial,
  password double,
  ipAddress tinyint,
  clockOut binary,
  score smallint,
  tags serial,
  description serial,
  houseNumber double,
  accountType smallint,
  brandId boolean,
  integrationId datetime,
  favoriteCount text,
  coverImage bigint,
  orderId geometry,
  employmentDate int,
  authToken geometry,
  buildNumber bigint,
  defaultValue date
);

CREATE TABLE pub_inventory_status_v1 (
  id serial primary key,
  dimension date,
  height boolean,
  address text,
  firstName enum,
  dailyLimit enum,
  eventDate boolean
);

CREATE TABLE pub_product (
  id serial primary key,
  role binary,
  layerId timestamp,
  age decimal,
  status mediumint,
  isActive decimal,
  backupEmail timestamp,
  paymentMethod set,
  machineId mediumint,
  hashKey varchar,
  feedbackId enum,
  fileSize enum,
  invoiceId date,
  domainName blob
);

CREATE TABLE tmp_account (
  id serial primary key,
  isDraft double,
  isAdmin datetime,
  expiryDate binary,
  lastLoginAt varchar,
  completionRate binary,
  inactiveAt text,
  clockIn geometry,
  currencyCode point,
  batchId blob,
  headerImage text,
  dataSource double,
  followCount tinyint
);

CREATE TABLE olk_user (
  id serial primary key,
  birthDate real,
  agentId text,
  type bigint,
  guestId decimal,
  deviceId bit,
  accountNumber double,
  employeeId time,
  cancelReason bit,
  isActive datetime,
  currencyCode binary,
  grade serial,
  manufacturerId serial,
  entryPoint boolean,
  articleId bigint,
  fileHash datetime,
  lockoutEnd bit,
  analyticsId varchar,
  configId float,
  authorId varchar,
  licenseKey bit,
  macAddress text,
  cityName bit,
  dailyLimit time,
  group mediumint,
  globalId smallint,
  totalAmount enum,
  authMethod enum,
  facilityId time
);

CREATE TABLE fact_order (
  id serial primary key,
  deletedAt tinyint,
  url mediumint,
  agentId varchar,
  friendId point,
  isRequired date,
  group varchar,
  addressLine1 datetime,
  completedAt timestamp,
  maskType text,
  employmentDate decimal,
  currencyCode set,
  title decimal,
  alertType point,
  minValue date,
  itemCount datetime,
  latitude timestamp,
  algorithm boolean,
  phone time,
  keyId blob,
  fileName enum,
  moduleId varchar,
  dataSource boolean,
  groupName timestamp,
  contactName decimal,
  age double,
  comment text,
  metadata datetime,
  role real,
  connectionString timestamp
);

CREATE TABLE tmp_organization (
  id serial primary key,
  fileSize serial,
  menuId bigint,
  driverLicense time,
  cardNumber smallint,
  dimension smallint,
  homePhone bigint,
  filterType int,
  courseId geometry,
  campaignId serial
);

CREATE TABLE dst_company_2024 (
  id serial primary key,
  ipAddress geometry,
  bookingDate smallint,
  token binary,
  loginAttempts enum,
  companyName float,
  unit smallint,
  completionRate decimal,
  isActive decimal,
  mobileNumber varchar,
  bluetoothId time,
  state mediumint,
  connectionString mediumint,
  audioUrl geometry,
  depositAmount smallint
);

CREATE TABLE customer (
  id serial primary key,
  customerId text,
  avatar date,
  completedAt varchar,
  price binary,
  isFeatured double,
  dateFormat tinyint,
  appVersion set,
  deviceId decimal,
  cartId decimal,
  country time,
  metaKeywords set
);

CREATE TABLE config_meta (
  id serial primary key,
  sku int,
  fileName tinyint,
  adminNotes float,
  latitude tinyint,
  expiryMonth blob,
  entityId time,
  weight point,
  appVersion set,
  analyticsId timestamp,
  locationId time,
  totalAmount serial,
  zipCode timestamp,
  salary geometry,
  metaDescription bigint,
  actionType geometry,
  completedAt real,
  employeeId mediumint,
  monthlyRate real,
  password double,
  alertType geometry,
  creditCard set,
  addressLine1 date,
  facilityId set,
  exportId time,
  height bigint,
  followCount enum,
  fileSize boolean,
  clientId bigint
);

CREATE TABLE src_audit (
  id serial primary key,
  updatedAt datetime,
  lockoutEnd serial,
  accountStatus set,
  meterNumber boolean,
  isAdmin varchar,
  dependentId bigint,
  mapId blob,
  role real,
  appVersion serial,
  unit double,
  monthlyRate real,
  hostName varchar,
  isActive mediumint,
  title blob,
  taxRate varchar,
  paymentMethod real,
  salary varchar,
  endPoint timestamp,
  indexKey smallint,
  orderStatus timestamp,
  street time,
  moduleId mediumint,
  fontSize float,
  completedAt tinyint,
  logLevel datetime,
  menuId enum,
  macAddress time
);

CREATE TABLE cpy_customer (
  id serial primary key,
  enabledAt int,
  mainImage double,
  firmwareVersion float,
  mimeType datetime,
  shippingAddress bit,
  metaTitle serial,
  channelId point,
  sessionId bigint,
  companyLogo binary,
  duration bit,
  avatar time,
  age serial,
  claimId smallint,
  latitude boolean,
  exchangeRate timestamp,
  paymentMethod text,
  monthlyRate varchar,
  formatType real,
  isLocked int,
  isDefault geometry,
  title bit,
  description point,
  cacheKey enum
);

CREATE TABLE record_2025 (
  id serial primary key,
  customField1 enum,
  height timestamp,
  mobileNumber smallint,
  isFeatured datetime,
  status blob,
  gender datetime,
  keyId smallint,
  createdAt timestamp,
  discount smallint,
  instanceId tinyint,
  deliveryDate serial,
  firmwareVersion real,
  homePhone time,
  expiryYear serial,
  groupName tinyint,
  formatType datetime,
  taxRate text,
  address point,
  deviceId blob,
  orderStatus binary,
  accountType geometry,
  activeDevices bit,
  courseId decimal,
  employmentDate float,
  dependentId time,
  isAdmin double,
  depositAmount date,
  contentType text
);

CREATE TABLE producthist (
  id serial primary key,
  depositAmount smallint,
  incidentId bigint,
  meterNumber point,
  createdAt boolean,
  tags timestamp,
  minValue boolean,
  metadata blob,
  exportId float,
  password tinyint,
  lastName set,
  city timestamp,
  customerId serial,
  algorithm int,
  hashKey enum,
  enabledAt date,
  customField1 tinyint,
  isHidden int,
  emergencyContact point,
  enrollmentDate smallint,
  endPoint blob,
  earnedPoints geometry,
  email varchar,
  fileSize float,
  firstName tinyint,
  certificateId timestamp,
  brandId varchar,
  bankAccount tinyint,
  entryPoint tinyint
);

CREATE TABLE company_info (
  id serial primary key,
  industryType float,
  isActive binary,
  customerGroup point
);

CREATE TABLE agg_record (
  id serial primary key,
  authorId smallint,
  exchangeRate int,
  audioUrl real,
  amount text,
  unit double,
  street enum,
  dependentId tinyint,
  mimeType boolean,
  iconPath decimal,
  value bit,
  companyName serial,
  longitude date,
  deviceToken double
);

CREATE TABLE ver_customer_temp (
  id serial primary key,
  industryType text,
  updatedAt bit,
  address geometry,
  thumbnail mediumint,
  homePhone int,
  fileHash blob,
  latitude geometry,
  channelId timestamp,
  couponCode enum,
  companyName time,
  marketId blob,
  abandonedCartId bit,
  modifiedAt varchar,
  value enum,
  layerId mediumint,
  authorId mediumint,
  customField2 geometry,
  amount point,
  fontSize bit,
  hashKey date,
  creditLimit double,
  deletedAt point,
  gender bigint,
  globalId datetime,
  cancelReason geometry,
  name smallint,
  customerId geometry,
  comment smallint
);

CREATE TABLE tmp_user_archive (
  id serial primary key,
  modifiedAt boolean,
  minLimit binary,
  version enum,
  dimension smallint,
  feedId varchar,
  username mediumint,
  defaultLang varchar,
  apiKey varchar,
  instanceId serial
);

CREATE TABLE tmpaccountv1 (
  id serial primary key,
  paymentMethod float,
  avatar datetime,
  companyName enum,
  unit blob,
  itemCount boolean,
  deliveryDate timestamp,
  emailStatus date,
  contractId set,
  isDeleted geometry,
  fontFamily text,
  token real
);

CREATE TABLE transactionnotifications (
  id serial primary key,
  certificateId real,
  state bit,
  password set,
  groupName serial,
  authToken int,
  price smallint,
  isLocked blob,
  orderStatus mediumint,
  eventDate timestamp,
  employeeId enum,
  postalCode serial,
  coordinateY smallint,
  authMethod blob,
  comment point,
  rating bit,
  status varchar
);

CREATE TABLE record_archive (
  id serial primary key,
  dashboardId bit,
  discountCode datetime,
  domainName float,
  email tinyint,
  flagged mediumint,
  sessionId bit,
  quantity set,
  editedAt timestamp,
  folderPath datetime,
  attemptCount int,
  accountStatus blob,
  displayOrder boolean,
  amount bit,
  billingCycle double,
  birthDate blob
);

CREATE TABLE user_status (
  id serial primary key,
  avatar date,
  lastLoginAt real,
  forwardTo serial,
  deliveryDate serial,
  fileName boolean,
  isRequired timestamp,
  defaultValue smallint,
  mapId boolean,
  batchId timestamp,
  blogId decimal,
  locationId real,
  country smallint,
  validUntil double,
  dialCode double,
  username point,
  cacheKey decimal,
  name blob,
  createdAt text,
  browserType boolean,
  contentType timestamp,
  entityId geometry,
  maxValue geometry
);

CREATE TABLE sysrecord (
  id serial primary key,
  longitude float,
  nickname tinyint,
  employeeId time,
  mimeType date,
  isPublic varchar,
  couponCode date,
  levelId boolean,
  billingCycle real,
  version serial,
  sku bigint,
  keywords boolean,
  menuId set,
  filterType int,
  manufacturerId text,
  height bigint,
  moduleId boolean
);

CREATE TABLE config (
  id serial primary key,
  score blob,
  isDraft mediumint,
  timezone boolean,
  education date,
  password blob,
  title blob,
  balance enum
);

CREATE TABLE organization (
  id serial primary key,
  adminNotes real,
  thumbnail real,
  languageCode time,
  integrationId date,
  entityId double,
  lockoutEnd decimal,
  keywords int,
  code smallint,
  price datetime,
  description date,
  fileName int,
  colorCode boolean,
  channelId date,
  isPublic tinyint,
  minValue decimal,
  enrollmentDate text,
  apiKey double,
  name smallint,
  contactName geometry,
  dateFormat decimal,
  memberCount double,
  checkOutTime enum,
  lastSeenAt tinyint,
  lastName time,
  title real,
  modifiedAt point
);

CREATE TABLE tmp_config (
  id serial primary key,
  attemptCount decimal,
  deviceId enum,
  maxLimit bigint
);

CREATE TABLE order_v2 (
  id serial primary key,
  avatar set,
  expiryYear serial,
  coordinateY time,
  dependentId geometry,
  phone set,
  courseId mediumint,
  flagged decimal,
  cityName binary,
  orderId geometry,
  customerId set,
  lockoutEnd double,
  sessionId binary,
  role time,
  audioUrl decimal,
  isSystem double,
  token set,
  dashboardId bigint,
  folderPath boolean,
  validUntil time,
  mapId geometry,
  mainImage text,
  accountStatus text
);

CREATE TABLE vworder (
  id serial primary key,
  isPublic binary,
  fileType set,
  filterType geometry,
  group bit,
  connectionString double,
  audioUrl blob,
  dataSource decimal,
  companyId geometry,
  firmwareVersion bigint,
  entityId smallint,
  comment enum,
  exchangeRate timestamp,
  metaKeywords geometry,
  messageId point,
  balance bit,
  updatedAt enum,
  logLevel datetime,
  name int
);

CREATE TABLE recordtemp (
  id serial primary key,
  accountType enum,
  gateId tinyint,
  actionType varchar,
  unit time,
  folderPath text,
  discount decimal,
  instructorId smallint,
  companyName point,
  entityId geometry,
  chargeId real,
  isDefault timestamp,
  configId varchar,
  code bigint,
  coverImage float,
  incidentId time
);

CREATE TABLE record (
  id serial primary key,
  emailStatus blob,
  formatType date,
  lastLoginAt int,
  title timestamp,
  isLocked boolean,
  machineId geometry,
  chatId float,
  productCode time,
  sku blob,
  logLevel boolean,
  companyName double,
  group date,
  ipAddress float,
  deletedAt boolean,
  cacheKey smallint,
  attemptCount date,
  bookingDate smallint,
  url geometry,
  category varchar,
  dealerId set,
  exchangeRate set,
  batchId blob,
  minValue blob,
  orderId timestamp
);

CREATE TABLE record (
  id serial primary key,
  agentId boolean,
  lastLoginAt set,
  unit int,
  status datetime,
  longitude time,
  isEnabled point,
  fileType set,
  hashKey time,
  quantity smallint,
  handlerId binary,
  incidentId decimal,
  domainName timestamp,
  isBillable decimal,
  weight set,
  orderStatus bit,
  cacheKey blob,
  floorNumber point,
  deliveryDate mediumint,
  depositAmount bit,
  extractId datetime,
  creditCard timestamp,
  feedId decimal,
  accountNumber datetime
);

CREATE TABLE tmp_audit (
  id serial primary key,
  status set,
  authToken smallint,
  actionType date,
  maxValue serial,
  phone timestamp,
  instructorId date,
  username enum,
  nickname bit,
  expiryDate blob,
  bookingDate double,
  hourlyRate bit,
  cacheKey timestamp,
  metadata float,
  cardNumber int,
  layerId geometry,
  country double,
  endPoint int,
  contactPhone mediumint,
  keyId varchar,
  adminNotes mediumint,
  name real,
  deletedAt decimal,
  browserType date
);

CREATE TABLE dimproduct (
  id serial primary key,
  creditCard int,
  isSystem point,
  claimId datetime,
  entityId varchar,
  fromDate double,
  invoiceId set,
  nickname tinyint,
  isPublic boolean,
  documentId timestamp,
  longitude geometry,
  alertType serial,
  appVersion tinyint,
  courseId time,
  maxLimit enum,
  discountCode mediumint,
  isHidden decimal,
  logLevel blob,
  hourlyRate serial,
  priority serial,
  contractId smallint,
  updatedAt float,
  friendId bit
);

CREATE TABLE customerv1 (
  id serial primary key,
  accountType enum,
  postalCode double,
  description bit,
  moduleId time,
  dialCode bigint
);

CREATE TABLE product (
  id serial primary key,
  avatar blob,
  isPublic blob,
  contractId boolean,
  firmwareVersion int,
  accountStatus datetime,
  connectionString int,
  isAdmin datetime,
  claimId int,
  score smallint,
  latitude enum
);

CREATE TABLE log_organization (
  id serial primary key,
  zipCode int,
  weight binary,
  isBillable blob,
  distributorId serial,
  customerGroup decimal,
  gameId bit,
  isSystem float,
  errorCode timestamp,
  courseId bit,
  logLevel bigint,
  orderStatus timestamp,
  analyticsId bigint,
  earnedPoints blob,
  isHidden real,
  age point,
  appVersion serial,
  metadata datetime,
  feedId timestamp,
  languageCode enum,
  priority varchar,
  password decimal,
  configId enum,
  moveId geometry,
  employeeCode smallint,
  headerImage float,
  floorNumber date,
  timezone enum
);

CREATE TABLE ref_config (
  id serial primary key,
  expiryYear geometry,
  phone geometry,
  localeId text,
  browserType mediumint,
  email time,
  hiddenAt serial,
  longitude mediumint,
  awardDate text,
  costCenter geometry,
  contactPhone bigint,
  validUntil blob,
  authMethod binary,
  insertedAt datetime,
  formatType binary,
  accountNumber smallint,
  metaTitle int,
  sku float,
  address binary,
  version text,
  emergencyContact enum,
  updatedAt date,
  coverImage float
);

CREATE TABLE verorganization (
  id serial primary key,
  buildNumber bit,
  incidentId decimal,
  isActive point,
  duration datetime,
  createdAt bigint,
  isHidden tinyint,
  mimeType int,
  channelId timestamp,
  discountCode mediumint,
  firmwareVersion double,
  extractId bigint,
  clientId datetime,
  deletedAt bigint,
  comment time
);

CREATE TABLE tmp_organization (
  id serial primary key,
  logLevel set,
  gender bit,
  clockIn float,
  expiryDate binary,
  dataSource point,
  accessLevel real,
  password datetime,
  creditCard real,
  awardDate decimal,
  score int,
  depositAmount float,
  authToken decimal,
  apiKey datetime,
  labelText binary,
  tags smallint,
  colorCode time,
  orderStatus boolean,
  group smallint,
  invoiceId double,
  activeDevices serial,
  deviceType decimal,
  age timestamp,
  coverImage int,
  contactPhone blob,
  nickname double,
  downloadCount varchar,
  dependentId time,
  cancelReason time,
  layerId bit,
  appVersion boolean
);

CREATE TABLE transaction (
  id serial primary key,
  levelId bigint,
  dependentId varchar,
  courseId int,
  facilityId binary,
  analyticsId serial,
  agentId datetime
);

CREATE TABLE sys_transaction (
  id serial primary key,
  apiVersion smallint,
  mimeType binary,
  hiddenAt binary,
  cvv varchar,
  likeCount float,
  employeeId mediumint,
  campaignId decimal,
  maritalStatus blob,
  algorithm binary,
  address timestamp,
  clockIn bit,
  mapId double,
  awardDate bit
);

CREATE TABLE customerout (
  id serial primary key,
  name tinyint,
  folderPath tinyint,
  bankAccount blob,
  accountType geometry,
  billingFrequency datetime,
  amount float,
  industryType bit,
  logLevel serial,
  marketId varchar,
  iconPath set,
  balance decimal,
  gateId geometry,
  instructorId binary,
  depositAmount datetime,
  formatType boolean,
  street float,
  paymentMethod serial,
  articleId blob,
  startDate serial,
  manufacturerId timestamp,
  facilityId text
);

CREATE TABLE olk_record_rel (
  id serial primary key,
  invoiceId varchar,
  endPoint date,
  comment bigint,
  hourlyRate datetime,
  amount int,
  enrollmentDate int,
  orderStatus varchar,
  completionRate mediumint,
  height blob,
  score point,
  courseId tinyint,
  sessionId blob,
  coordinateY tinyint,
  productCode tinyint,
  accessLevel timestamp
);

CREATE TABLE stg_customer (
  id serial primary key,
  couponCode mediumint,
  password varchar,
  attemptCount float,
  employeeCode smallint,
  managerId text,
  instanceId varchar,
  homePhone float,
  deviceToken blob
);

CREATE TABLE userdata (
  id serial primary key,
  alertType set,
  createdAt blob,
  gender date,
  isHidden binary,
  foregroundColor double,
  facilityId tinyint,
  marketId boolean,
  gameId timestamp,
  productCode date,
  agentId set,
  coordinateX bit,
  taxRate boolean,
  exchangeRate bit,
  jobTitle enum,
  machineId real
);

CREATE TABLE rel_organization (
  id serial primary key,
  password varchar,
  keyId tinyint,
  displayName mediumint,
  metaDescription binary,
  description decimal,
  currency date,
  isLocked timestamp,
  menuId smallint,
  defaultLang boolean,
  type date,
  contactName date,
  avatar geometry,
  token binary,
  nickname date,
  homePhone bigint,
  currencyCode datetime,
  courseId set,
  status varchar,
  deviceToken geometry,
  zipCode boolean,
  lastLoginAt real,
  billingFrequency geometry,
  buildNumber datetime,
  campaignId timestamp,
  maskType text,
  followCount serial,
  businessType double
);

CREATE TABLE ext_audit_seg_legacy (
  id serial primary key,
  height text,
  maxLimit date,
  facilityId time,
  country boolean,
  budgetCode bit,
  customerGroup binary,
  quantity serial,
  dataSource point,
  configId int,
  endPoint bigint,
  token set,
  globalId bigint,
  maxValue int,
  algorithm real,
  employeeId bigint
);

CREATE TABLE log_order (
  id serial primary key,
  bluetoothId real,
  grade time,
  metaKeywords point
);

