CREATE TABLE company_info (
  id serial primary key,
  buildNumber boolean,
  isPublic datetime,
  companyName serial,
  earnedPoints enum,
  marketId enum,
  isEnabled point,
  globalId tinyint,
  dueDateAt smallint,
  country datetime,
  displayName real,
  contactPhone mediumint,
  birthDate double,
  algorithm binary,
  customerGroup int,
  enabledAt mediumint,
  accountType enum,
  status mediumint,
  employeeId text,
  tags double,
  dashboardId set,
  actionType text,
  phone point,
  ipAddress timestamp
);

CREATE TABLE order (
  id serial primary key,
  deviceId float,
  metaDescription geometry,
  bankAccount tinyint,
  paymentMethod point,
  contactEmail tinyint,
  memberCount double,
  driverLicense bigint,
  claimId mediumint
);

CREATE TABLE config (
  id serial primary key,
  managerId text,
  height decimal,
  certificateId datetime,
  chatId mediumint,
  forwardTo decimal,
  earnedPoints geometry,
  age decimal,
  isHidden bit,
  contractId enum,
  coordinateX blob,
  orderId date,
  city double,
  category double,
  defaultLang float,
  attachmentUrl smallint,
  id mediumint,
  defaultValue set,
  bannerImage mediumint,
  errorMessage point
);

CREATE TABLE privpayment (
  id serial primary key,
  accountStatus int,
  category bigint,
  appVersion set,
  fromDate text,
  age timestamp,
  authorId double,
  deviceToken time,
  employeeCode point,
  mobileNumber real,
  metaTitle tinyint,
  zipCode serial,
  instanceId point,
  extractId time,
  salary point,
  mainImage point,
  mapId bit,
  longitude serial,
  balance datetime,
  postalCode decimal,
  referralCode datetime,
  instructorId mediumint,
  apiVersion time,
  fontSize real,
  state set,
  meterNumber bit,
  cartId timestamp
);

CREATE TABLE core_customer (
  id serial primary key,
  handlerId date,
  feedbackId time,
  batchId tinyint,
  postalCode float,
  machineId point,
  audioUrl enum,
  longitude binary,
  id blob,
  firstName smallint,
  integrationId double,
  meterNumber geometry,
  description text,
  authorId text,
  status point,
  managerId datetime,
  bookingDate point,
  incidentId binary,
  claimId datetime,
  exportId date,
  contactPhone tinyint,
  title point,
  isDefault int,
  employeeId real,
  mobileNumber set,
  discount geometry,
  costCenter datetime,
  merchantId binary,
  sessionId point,
  expiryDate binary,
  importId decimal,
  address geometry
);

CREATE TABLE dst_customer_v2 (
  id serial primary key,
  startDate point,
  isVerified geometry,
  cancelReason boolean,
  coverImage date,
  invoiceId timestamp,
  sessionId geometry,
  grade varchar,
  category boolean,
  deliveryDate smallint,
  entryPoint serial,
  value bit,
  mobileNumber varchar,
  flagged enum,
  labelText boolean,
  isArchived geometry,
  street blob,
  apiKey point
);

CREATE TABLE pub_user_temp (
  id serial primary key,
  feedbackId varchar,
  documentId set,
  gender time,
  duration decimal,
  cancelReason decimal,
  loginAttempts mediumint,
  uuid date,
  displayOrder timestamp,
  likeCount date
);

CREATE TABLE src_customer_2025 (
  id serial primary key,
  isRequired set,
  customField2 set,
  dailyLimit float,
  marketId decimal,
  friendId binary,
  buildNumber geometry,
  deactivatedAt double,
  updatedAt real,
  rating time,
  labelText smallint,
  gender smallint,
  id geometry,
  customerId serial,
  password boolean,
  completedAt set,
  companyName set,
  favoriteCount set,
  entryPoint point,
  listingId blob,
  dataSource blob,
  isHidden enum,
  messageId double,
  handlerId serial,
  expiryYear point,
  timezone geometry
);

CREATE TABLE account (
  id serial primary key,
  deactivatedAt mediumint,
  description enum,
  orderId time,
  isPublic smallint,
  sku int,
  contractId binary,
  formatType smallint,
  cvv time,
  quantity date,
  monthlyRate enum,
  importId varchar,
  documentId tinyint,
  minValue text,
  domainName set,
  folderPath timestamp,
  menuId float,
  mapId bit,
  birthDate tinyint,
  isRequired real,
  comment blob,
  maskType float,
  employmentDate date
);

CREATE TABLE fact_company_info (
  id serial primary key,
  maskType datetime,
  jobTitle bigint,
  displayOrder decimal
);

CREATE TABLE transaction_rel (
  id serial primary key,
  geoLocation bigint,
  score time,
  abandonedCartId varchar,
  folderPath varchar,
  employeeCode boolean,
  totalAmount int,
  postalCode set,
  rating set,
  status serial,
  enrollmentDate enum,
  itemCount datetime,
  duration smallint,
  cardNumber point,
  isAdmin boolean,
  dependentId real,
  email text,
  depositAmount blob,
  insertedAt timestamp,
  accessLevel enum,
  username bigint,
  hashKey blob,
  completionRate point,
  errorCode boolean,
  companyLogo decimal,
  creditLimit datetime,
  timezone datetime,
  favoriteCount boolean,
  updatedAt blob
);

CREATE TABLE tmpconfig (
  id serial primary key,
  defaultLang geometry,
  eventDate enum
);

CREATE TABLE transaction (
  id serial primary key,
  fileType enum,
  brandId text,
  isSystem timestamp,
  isDraft time,
  batchId decimal,
  filterType tinyint,
  flagged geometry,
  countryCode varchar,
  updatedAt int,
  fromDate text,
  value boolean,
  merchantId tinyint,
  instructorId varchar,
  taxRate serial,
  contentType binary,
  name bit,
  education double,
  appVersion boolean
);

CREATE TABLE config (
  id serial primary key,
  endPoint text,
  filterType mediumint,
  contactPhone point,
  isPublic set,
  fileHash int,
  phone varchar,
  connectionString blob,
  incidentId binary,
  feedId date,
  insertedAt blob,
  startDate bigint,
  importId tinyint,
  depositAmount time,
  contactEmail datetime,
  exportId boolean,
  linkId enum,
  accountType point,
  monthlyRate geometry,
  accountNumber binary,
  status blob,
  deactivatedAt smallint,
  firmwareVersion text,
  departmentCode set,
  marketId decimal,
  downloadCount text,
  billingCycle varchar,
  clockOut binary,
  cancelReason boolean,
  actionType bit,
  accountStatus datetime,
  deviceType binary
);

CREATE TABLE account_2024 (
  id serial primary key,
  clientId smallint,
  chatId set,
  isDefault binary,
  entityId double,
  enrollmentDate bigint,
  coordinateY blob,
  exchangeRate mediumint,
  childId time,
  username serial,
  groupName float,
  moduleId datetime,
  email point,
  fileHash geometry,
  avatar geometry,
  accessLevel int,
  cvv double,
  age point,
  employmentDate decimal,
  longitude varchar,
  isDraft set,
  cancelReason timestamp,
  clockOut tinyint,
  filterType binary
);

CREATE TABLE app_company_rel_2024 (
  id serial primary key,
  distributorId bit,
  accountNumber blob,
  costCenter binary,
  quantity text,
  audioUrl smallint,
  expiryMonth varchar,
  amount varchar,
  isEnabled blob,
  latitude enum,
  updatedAt text,
  metaDescription tinyint,
  keyId text,
  groupName tinyint,
  fontSize float,
  chatId timestamp,
  fromDate decimal,
  comment geometry,
  budgetCode bit,
  title tinyint,
  status date,
  age int,
  checkOutTime int,
  accountStatus int,
  iconPath bigint,
  displayOrder enum,
  phone bit,
  jobTitle serial,
  copyRight varchar,
  group enum,
  deliveryDate datetime,
  firmwareVersion bit
);

CREATE TABLE core_audit (
  id serial primary key,
  groupName decimal,
  costCenter serial,
  balance mediumint,
  foregroundColor time,
  friendId int,
  gateId decimal,
  avatar time,
  logLevel time,
  dateFormat time,
  id datetime,
  shippingAddress tinyint,
  attemptCount smallint,
  listingId geometry,
  version int,
  browserType bit,
  apiVersion timestamp,
  middleName mediumint,
  isLocked time,
  extractId boolean,
  dimension float,
  comment text,
  chargeId float,
  businessType binary,
  apiKey double,
  salary point,
  entryPoint text,
  exportId serial,
  customerGroup int
);

CREATE TABLE log_transaction (
  id serial primary key,
  completionRate set,
  zipCode boolean,
  mimeType blob,
  ipAddress geometry,
  indexKey boolean,
  salary binary,
  isAdmin serial,
  abandonedCartId decimal,
  depositAmount blob,
  backupEmail timestamp,
  licenseKey set,
  category bigint,
  latitude bigint,
  updatedAt bit,
  endPoint double
);

CREATE TABLE tbl_order (
  id serial primary key,
  homePhone double,
  defaultLang geometry,
  dataSource boolean,
  discountCode point,
  listId point,
  cloudId point,
  name enum,
  id timestamp,
  type bigint,
  browserType geometry,
  clockOut binary,
  attemptCount boolean,
  costCenter decimal,
  levelId tinyint,
  fileHash enum,
  departmentCode time,
  insuranceId boolean,
  phone tinyint,
  articleId bigint,
  totalAmount float,
  balance datetime
);

CREATE TABLE company (
  id serial primary key,
  exchangeRate boolean,
  fromDate tinyint,
  contactName boolean,
  menuId decimal,
  group set,
  balance decimal,
  articleId real,
  priority time,
  feedbackId geometry,
  chatId mediumint,
  productCode blob,
  amount blob,
  accountType binary
);

CREATE TABLE user (
  id serial primary key,
  checkInTime time,
  cloudId int,
  costCenter varchar,
  keywords timestamp,
  quantity int,
  awardDate timestamp
);

CREATE TABLE dst_user (
  id serial primary key,
  errorCode varchar,
  menuId point,
  updatedAt boolean,
  groupName real,
  localeId datetime,
  content int,
  totalAmount real,
  filterType real,
  driverLicense int,
  integrationId decimal,
  createdAt decimal,
  listId bit,
  contactName datetime,
  mimeType bigint,
  levelId point,
  hiddenAt serial,
  audioUrl smallint,
  avatar date,
  bookingDate enum,
  metaTitle real,
  email datetime,
  employeeCode tinyint
);

CREATE TABLE dim_audit (
  id serial primary key,
  duration bigint,
  contactName enum,
  fingerprint set,
  geoLocation mediumint,
  mobileNumber real,
  category text,
  apiKey text,
  guestId real,
  courseId real,
  dimension bit,
  amount bigint,
  token smallint,
  layerId varchar,
  depositAmount enum,
  hourlyRate decimal,
  longitude double,
  globalId datetime,
  modifiedAt text,
  batchId set,
  importId bigint,
  dependentId datetime,
  maskType text,
  id set,
  isBillable enum,
  productCode tinyint,
  education bigint,
  bookingDate blob,
  street decimal
);

CREATE TABLE core_inventory_type_v1 (
  id serial primary key,
  extractId mediumint,
  password smallint,
  errorMessage timestamp,
  hostName int,
  listingId boolean,
  childId blob,
  globalId double,
  metaKeywords enum,
  score float,
  loginCount float,
  duration float,
  distributorId blob,
  metadata serial,
  favoriteCount text,
  clockIn set,
  completionRate int,
  clockOut boolean,
  orderId enum
);

CREATE TABLE transaction (
  id serial primary key,
  downloadCount float,
  manufacturerId timestamp,
  checkOutTime double,
  insertedAt tinyint,
  defaultValue enum,
  coverImage smallint,
  comment real,
  managerId blob,
  friendId set,
  expiryDate real,
  city bit,
  insuranceId mediumint,
  clientId enum,
  customField2 blob,
  fontFamily timestamp,
  education timestamp,
  mobileNumber float,
  deviceId boolean,
  attemptCount real
);

CREATE TABLE organization_v1 (
  id serial primary key,
  lastSeenAt time,
  completedAt text,
  gateId mediumint,
  startDate float
);

CREATE TABLE audit (
  id serial primary key,
  jobTitle date,
  appVersion boolean,
  ipAddress geometry,
  favoriteCount enum,
  currencyCode varchar,
  latitude set,
  agentId date,
  dueDateAt double,
  displayOrder set,
  departmentCode double,
  unit int,
  isFeatured real,
  billingCycle mediumint,
  defaultLang set,
  errorCode text,
  employeeCode timestamp,
  isActive boolean,
  hostName serial,
  cardHolder smallint,
  dashboardId time,
  likeCount binary,
  emailStatus date,
  isDeleted datetime,
  department bigint,
  languageCode enum,
  lastName real,
  modifiedAt boolean,
  flagged tinyint,
  companyId bit,
  isBillable text
);

CREATE TABLE log_organization_status (
  id serial primary key,
  lastLoginAt double,
  modifiedAt time,
  isFeatured point,
  foregroundColor serial,
  expiryYear smallint,
  followCount serial,
  hiddenAt real,
  createdAt timestamp,
  ipAddress geometry,
  appVersion timestamp,
  bannerImage geometry,
  buildNumber mediumint,
  address float,
  dueDateAt tinyint,
  distributorId point,
  hourlyRate boolean,
  latitude smallint,
  email smallint,
  errorMessage binary,
  insertedAt point
);

CREATE TABLE config_log (
  id serial primary key,
  listingId set,
  awardDate point,
  appVersion point,
  employeeId float,
  avatar point
);

CREATE TABLE transactionarchive (
  id serial primary key,
  avatar mediumint,
  birthDate datetime,
  address binary,
  description enum,
  tags date,
  completionRate int,
  dealerId tinyint,
  employmentDate time
);

CREATE TABLE customerout (
  id serial primary key,
  contractId date,
  backupEmail tinyint,
  sku mediumint,
  displayName datetime,
  agentId binary,
  entryPoint text,
  comment bigint,
  discountCode bigint,
  copyRight text,
  deletedAt bit,
  activeDevices double,
  age date,
  height enum
);

CREATE TABLE dst_organization (
  id serial primary key,
  cartId set,
  companyName date,
  phone decimal,
  listId time,
  channelId set,
  group tinyint,
  localeId date,
  paymentMethod int,
  brandId time,
  completedAt binary,
  city datetime,
  adminNotes mediumint,
  completionRate mediumint,
  totalAmount time,
  exportId binary,
  maskType binary,
  dealerId serial,
  timezone int,
  batchId double,
  status smallint,
  dimension set,
  mobileNumber blob,
  fromDate smallint,
  distributorId geometry,
  longitude bit,
  dailyLimit time,
  memberCount time,
  loadTime bigint,
  createdAt serial,
  hourlyRate boolean,
  title smallint
);

CREATE TABLE config_temp (
  id serial primary key,
  configId decimal,
  taxRate date,
  albumId bit,
  ipAddress decimal,
  avatar decimal,
  displayOrder bigint,
  companyLogo binary,
  createdAt set,
  flagged date,
  checkOutTime binary,
  customField2 serial,
  status serial,
  cardHolder timestamp,
  hiddenAt bit,
  fileName bit,
  discount text,
  street blob,
  mainImage enum,
  levelId point,
  errorMessage real,
  clockOut datetime,
  activeDevices real,
  isActive datetime,
  browserType tinyint,
  dialCode boolean,
  listId smallint,
  authMethod varchar,
  dueDateAt text,
  referralCode geometry
);

CREATE TABLE core_transaction_extra (
  id serial primary key,
  downloadCount set,
  contactEmail blob,
  longitude double,
  fileHash datetime,
  address boolean,
  addressLine2 double,
  feedbackId time,
  customField1 timestamp,
  contactName bigint,
  dueDateAt geometry
);

CREATE TABLE orderstatus (
  id serial primary key,
  minLimit geometry,
  version mediumint,
  deletedAt point,
  countryCode boolean,
  accountNumber datetime,
  certificateId binary,
  metaTitle varchar,
  phone binary,
  latitude time
);

CREATE TABLE product (
  id serial primary key,
  abandonedCartId time,
  filterType blob,
  apiVersion binary,
  messageId serial,
  expiryYear int,
  lockoutEnd mediumint,
  discountCode real,
  weight binary,
  departmentCode text
);

CREATE TABLE pub_payment (
  id serial primary key,
  contactEmail point,
  mobileNumber mediumint,
  exchangeRate time,
  isPublic date,
  addressLine1 boolean,
  name date,
  department set,
  country bit,
  costCenter date,
  instanceId bigint,
  couponCode time,
  description point,
  duration set,
  title int,
  creditScore double,
  distributorId set,
  claimId binary,
  ipAddress geometry,
  errorMessage mediumint,
  courseId varchar,
  creditLimit blob,
  manufacturerId double,
  geoLocation decimal,
  eventDate timestamp,
  handlerId blob,
  nickname serial,
  earnedPoints tinyint,
  address boolean,
  currency timestamp,
  blogId blob,
  locationId time
);

CREATE TABLE order_temp (
  id serial primary key,
  lastSeenAt enum,
  price double
);

CREATE TABLE company_meta (
  id serial primary key,
  actionType binary,
  createdAt blob,
  avatar float,
  status blob,
  insertedAt enum,
  addressLine1 varchar,
  chargeId time,
  address point,
  dateFormat date,
  token geometry,
  dataSource varchar,
  content blob,
  enrollmentDate point,
  machineId set,
  dueDateAt enum,
  role date,
  languageCode blob,
  integrationId datetime,
  duration geometry,
  contractId set,
  minLimit blob,
  minValue datetime,
  category smallint,
  editedAt date,
  appVersion varchar,
  url date,
  checkInTime point
);

CREATE TABLE olkrecord (
  id serial primary key,
  duration boolean,
  gameId binary,
  customerGroup int,
  distributorId real,
  role bigint,
  blogId time,
  cartId datetime,
  quantity mediumint,
  brandId tinyint,
  dailyLimit bit,
  machineId real,
  globalId float,
  fileType time,
  campaignId serial,
  checkInTime float,
  hiddenAt boolean,
  billingFrequency geometry,
  loginAttempts geometry,
  password date,
  analyticsId decimal,
  creditLimit decimal
);

CREATE TABLE rel_record (
  id serial primary key,
  lockoutEnd datetime,
  expiryDate bigint,
  brandId serial,
  meterNumber int,
  insuranceId time,
  accountStatus geometry,
  machineId float,
  hostName enum,
  campaignId blob,
  cartId decimal,
  floorNumber bit,
  importId decimal,
  depositAmount time,
  deviceToken text,
  education bigint,
  clockIn int,
  checkInTime double,
  indexKey timestamp,
  code point,
  departmentCode bigint,
  apiKey date,
  duration date,
  backupEmail date,
  authorId geometry,
  hashKey double,
  friendId bit
);

CREATE TABLE src_customer_legacy (
  id serial primary key,
  itemCount smallint,
  errorCode binary,
  jobTitle smallint,
  backupEmail text,
  avatar bigint,
  isEnabled binary,
  cancelReason set,
  priority serial,
  abandonedCartId bit,
  agentId real,
  shippingAddress double,
  gateId boolean,
  contactPhone enum,
  moduleId varchar,
  dialCode datetime,
  metaDescription datetime,
  status bigint,
  businessType bigint,
  entityId bit,
  description mediumint,
  loginAttempts smallint,
  latitude decimal,
  levelId mediumint,
  deviceType int,
  comment bigint,
  macAddress text,
  code blob
);

CREATE TABLE payment (
  id serial primary key,
  password timestamp,
  name geometry,
  claimId binary,
  fileSize geometry,
  comment blob,
  dialCode varchar,
  appVersion double,
  age real,
  creditScore double,
  globalId datetime
);

CREATE TABLE ver_customer_status (
  id serial primary key,
  paymentMethod bit,
  feedId blob,
  filterType binary,
  downloadCount date,
  itemCount tinyint,
  content time,
  companyLogo blob
);

CREATE TABLE customer_notifications (
  id serial primary key,
  deletedAt bit,
  loginAttempts enum,
  isBillable mediumint,
  entryPoint time,
  adminNotes enum,
  metaDescription text,
  languageCode double,
  role set,
  listingId set,
  longitude enum,
  cloudId smallint,
  amount float,
  displayOrder mediumint,
  username timestamp,
  coverImage bigint,
  maritalStatus date,
  firmwareVersion blob,
  minLimit time,
  activeDevices text,
  password decimal,
  budgetCode date,
  completionRate bit,
  middleName date
);

CREATE TABLE config (
  id serial primary key,
  authMethod serial,
  inactiveAt smallint,
  expiryMonth bigint,
  age datetime,
  clockOut decimal,
  likeCount blob,
  levelId binary,
  dateFormat set,
  email timestamp,
  couponCode enum,
  insuranceId decimal,
  abandonedCartId boolean,
  title datetime,
  companyName bit,
  sessionId decimal,
  importId float,
  apiKey serial,
  clientId set,
  url decimal,
  checkOutTime varchar,
  createdAt float,
  authorId geometry,
  startDate date,
  name blob
);

CREATE TABLE app_customer (
  id serial primary key,
  isAdmin bigint,
  contactPhone real,
  metaTitle date,
  attachmentUrl mediumint,
  maskType set,
  audioUrl timestamp,
  apiVersion point,
  name boolean,
  certificateId geometry,
  password blob,
  listId int,
  couponCode smallint,
  firmwareVersion blob,
  documentId bigint,
  employeeId time,
  companyId bigint,
  machineId tinyint,
  iconPath binary,
  fileHash int,
  cancelReason tinyint,
  emailStatus real,
  cartId boolean,
  gateId boolean,
  gender text,
  layerId int
);

CREATE TABLE companyextra (
  id serial primary key,
  contactPhone serial,
  accountType point,
  avatar decimal,
  linkId geometry,
  jobTitle varchar,
  expiryMonth set
);

CREATE TABLE tmp_user (
  id serial primary key,
  authorId enum,
  orderId set,
  shippingAddress text,
  foregroundColor mediumint,
  address mediumint,
  enrollmentDate timestamp,
  metadata binary,
  isSystem bit,
  metaKeywords set,
  isDefault binary,
  checkOutTime serial,
  email timestamp,
  isDraft timestamp,
  marketId smallint,
  title real,
  discountCode int,
  duration double,
  attemptCount timestamp,
  courseId blob,
  cardNumber double,
  filterType float,
  sku blob,
  domainName decimal,
  bookingDate serial,
  macAddress real,
  nickname float,
  startDate double,
  zipCode point
);

CREATE TABLE dim_product (
  id serial primary key,
  password serial,
  certificateId decimal,
  audioUrl bit,
  modifiedAt date,
  blogId bigint,
  amount bit,
  marketId mediumint,
  domainName bit,
  contentType float,
  id serial,
  foregroundColor time,
  avatar decimal,
  updatedAt float,
  friendId bit
);

