CREATE TABLE customer (
  id serial primary key,
  agentId tinyint,
  loginCount datetime,
  activeDevices mediumint,
  cardNumber decimal,
  accessLevel float,
  appVersion time,
  lockoutEnd smallint,
  monthlyRate set,
  rating int,
  childId text,
  score binary,
  ipAddress decimal,
  deletedAt blob,
  itemCount varchar
);

CREATE TABLE vw_user_notifications (
  id serial primary key,
  updatedAt time,
  invoiceId smallint,
  gender timestamp,
  attemptCount time,
  value real,
  exportId set,
  group bit,
  duration enum,
  status enum,
  entryPoint set,
  isDraft bit,
  defaultLang enum,
  listId smallint,
  brandId point,
  dueDateAt datetime,
  depositAmount point,
  moveId real,
  validUntil text,
  companyLogo geometry,
  coordinateX int
);

CREATE TABLE app_company (
  id serial primary key,
  channelId text,
  type text,
  updatedAt int,
  discount mediumint,
  age serial,
  content point,
  discountCode time,
  isPublic point,
  geoLocation date
);

CREATE TABLE srcpayment (
  id serial primary key,
  validUntil int,
  mobileNumber decimal,
  mapId mediumint,
  courseId real,
  isFeatured binary,
  postalCode text,
  frameRate smallint,
  macAddress int,
  contactEmail geometry,
  isActive datetime,
  domainName double,
  keywords blob,
  menuId text,
  clientId smallint,
  globalId float,
  isDefault real,
  dashboardId smallint,
  chatId text,
  creditLimit text,
  integrationId timestamp,
  channelId datetime,
  zipCode smallint,
  quantity enum,
  isVerified enum,
  manufacturerId date,
  articleId bit,
  age timestamp,
  discountCode bigint,
  avatar timestamp
);

CREATE TABLE order_status (
  id serial primary key,
  totalAmount bit,
  username datetime,
  companyName blob,
  isDefault date,
  dimension real,
  dashboardId real,
  fileSize tinyint,
  metaDescription bit,
  homePhone date,
  deviceType int,
  authMethod blob,
  isPublic bigint,
  listId enum,
  instanceId float,
  messageId binary,
  albumId boolean
);

CREATE TABLE product_type (
  id serial primary key,
  bankAccount bit,
  isLocked time,
  isDeleted bigint,
  isActive boolean,
  username binary,
  contactEmail binary,
  batchId datetime,
  state mediumint,
  locationId point,
  checkOutTime decimal,
  guestId bit,
  entryPoint point,
  chatId int,
  coverImage set,
  deliveryDate decimal,
  firstName blob,
  startDate tinyint,
  claimId geometry,
  authorId blob,
  mapId blob,
  deactivatedAt timestamp
);

CREATE TABLE corepayment (
  id serial primary key,
  clockOut timestamp,
  authMethod double,
  thumbnail double,
  accountType time,
  firmwareVersion double,
  managerId point,
  discountCode bigint,
  contactEmail smallint,
  floorNumber double,
  employeeCode time,
  globalId bit,
  birthDate binary,
  apiKey mediumint,
  dependentId enum,
  creditLimit geometry,
  longitude bit
);

CREATE TABLE tmp_company_meta (
  id serial primary key,
  sessionId double,
  dateFormat double
);

CREATE TABLE customer (
  id serial primary key,
  instanceId mediumint,
  sessionId timestamp,
  orderStatus bit,
  gender date,
  shippingAddress time,
  rating varchar,
  age boolean,
  creditLimit boolean,
  certificateId mediumint,
  indexKey decimal,
  state smallint,
  code mediumint,
  category point,
  messageId time,
  importId set
);

CREATE TABLE record (
  id serial primary key,
  followCount tinyint,
  loadTime timestamp,
  defaultValue tinyint,
  startDate decimal,
  fileHash bit,
  category int,
  fileName tinyint,
  phone tinyint,
  url double,
  employmentDate int,
  editedAt bit,
  validUntil time
);

CREATE TABLE src_inventory_extra (
  id serial primary key,
  address double,
  isRequired float,
  zipCode double,
  size smallint,
  linkId geometry,
  dealerId tinyint,
  comment float,
  firstName set,
  lastLoginAt bigint,
  avatar geometry,
  merchantId boolean,
  jobTitle date,
  customField1 binary,
  groupName boolean,
  status bit,
  cartId binary,
  menuId serial,
  uuid binary,
  forwardTo real,
  username text
);

CREATE TABLE payment (
  id serial primary key,
  cardHolder decimal,
  addressLine2 smallint,
  countryCode time,
  title tinyint,
  size float,
  currencyCode bit,
  memberCount mediumint,
  budgetCode double,
  apiVersion enum,
  endPoint serial,
  minLimit varchar,
  isDeleted blob,
  hourlyRate enum,
  validUntil real,
  iconPath point,
  maskType timestamp,
  startDate mediumint,
  dealerId smallint,
  id float,
  cardNumber varchar,
  latitude boolean,
  algorithm time,
  status date,
  gateId decimal,
  extractId date,
  chargeId smallint
);

CREATE TABLE refpayment (
  id serial primary key,
  avatar bigint,
  endDate time,
  status blob,
  isPublic smallint,
  birthDate binary,
  entryPoint tinyint,
  costCenter smallint,
  currency tinyint,
  email blob
);

CREATE TABLE payment (
  id serial primary key,
  likeCount double,
  balance binary,
  hashKey datetime,
  category decimal,
  validUntil bigint,
  comment double,
  adminNotes bigint
);

CREATE TABLE ver_record_rel (
  id serial primary key,
  latitude text,
  uuid tinyint,
  metadata real,
  orderId blob,
  fontSize decimal,
  metaKeywords decimal,
  amount bit,
  houseNumber enum,
  depositAmount date,
  state bit,
  duration time,
  chatId datetime,
  flagged serial,
  contentType datetime,
  errorCode date,
  insuranceId smallint,
  homePhone serial,
  hourlyRate geometry,
  category bit,
  industryType double,
  deactivatedAt real,
  browserType time,
  title time,
  itemCount boolean,
  costCenter real,
  token serial,
  isActive tinyint,
  middleName datetime
);

CREATE TABLE account (
  id serial primary key,
  adminNotes boolean,
  content enum
);

CREATE TABLE tmprecord (
  id serial primary key,
  fileType bit,
  instructorId mediumint,
  hiddenAt date,
  insuranceId bit,
  dataSource geometry,
  colorCode timestamp,
  address boolean,
  globalId double,
  lastSeenAt binary,
  certificateId tinyint,
  folderPath set,
  rating smallint,
  dashboardId float,
  isHidden datetime
);

CREATE TABLE sys_account (
  id serial primary key,
  createdAt datetime,
  connectionString point,
  earnedPoints bit,
  isPublic serial,
  fileType tinyint,
  balance decimal,
  depositAmount bigint,
  attachmentUrl serial,
  isFeatured text,
  checkInTime boolean,
  forwardTo smallint,
  email float,
  contractId real,
  brandId date,
  quantity real,
  coordinateY double,
  token smallint,
  businessType decimal,
  coordinateX real,
  houseNumber serial,
  birthDate blob,
  password point,
  creditScore blob,
  followCount date,
  friendId smallint
);

CREATE TABLE priv_product (
  id serial primary key,
  fingerprint bit,
  accessLevel decimal,
  countryCode text,
  name double,
  certificateId serial,
  entryPoint enum,
  deviceToken serial,
  fileHash double,
  endPoint serial,
  expiryYear datetime,
  departmentCode int,
  licenseKey set,
  filterType decimal,
  lastName enum,
  amount int,
  currency set,
  coordinateY int,
  moduleId binary,
  expiryMonth datetime,
  businessType binary,
  startDate tinyint,
  folderPath text,
  cartId boolean,
  albumId mediumint,
  loginCount boolean,
  accountType float,
  ipAddress boolean,
  email bigint,
  longitude serial,
  contactName real
);

CREATE TABLE core_organization (
  id serial primary key,
  id int,
  insertedAt enum,
  entityId bit,
  content serial,
  chargeId varchar,
  isDraft date,
  taxRate varchar,
  minLimit float
);

CREATE TABLE account (
  id serial primary key,
  isArchived time,
  homePhone binary,
  updatedAt point,
  contractId boolean,
  latitude geometry,
  email real,
  lastName double,
  deviceType date,
  headerImage blob,
  entityId geometry,
  hashKey timestamp,
  memberCount bit,
  frameRate varchar,
  exportId mediumint,
  age blob,
  isPublic smallint,
  unit timestamp,
  minValue smallint,
  groupName double,
  dependentId tinyint,
  favoriteCount boolean,
  abandonedCartId enum
);

CREATE TABLE factinventoryextra (
  id serial primary key,
  grade date,
  updatedAt geometry,
  insuranceId date,
  exchangeRate blob,
  priority serial,
  fileType binary,
  fingerprint bit,
  articleId timestamp,
  faxNumber serial,
  abandonedCartId timestamp,
  creditScore boolean,
  formatType real,
  token blob,
  driverLicense date
);

CREATE TABLE product (
  id serial primary key,
  customerGroup bit,
  maskType bit,
  quantity datetime,
  labelText serial,
  meterNumber point,
  isAdmin boolean,
  claimId real,
  isLocked bit,
  version mediumint,
  insertedAt timestamp,
  department timestamp
);

CREATE TABLE coreaccountdiv (
  id serial primary key,
  isLocked blob,
  cancelReason blob,
  adminNotes datetime,
  likeCount enum,
  deactivatedAt float,
  value smallint,
  insertedAt float,
  middleName real,
  state double
);

CREATE TABLE recordstatus (
  id serial primary key,
  contactName varchar,
  customField1 set,
  cardHolder bigint,
  city serial,
  comment time,
  ipAddress timestamp,
  employeeId double,
  avatar bit,
  abandonedCartId enum
);

CREATE TABLE olk_account_info (
  id serial primary key,
  hiddenAt datetime,
  customerGroup varchar,
  instanceId real,
  dateFormat decimal,
  content point,
  depositAmount float,
  customField2 point,
  keywords blob,
  checkOutTime double,
  filterType datetime,
  moduleId boolean,
  locationId blob,
  lastLoginAt decimal,
  algorithm binary,
  dimension date,
  latitude int,
  name binary
);

CREATE TABLE core_customer_rel (
  id serial primary key,
  metaDescription int,
  bannerImage datetime,
  incidentId timestamp,
  grade timestamp,
  updatedAt bigint,
  dealerId real
);

CREATE TABLE user_out (
  id serial primary key,
  isLocked decimal,
  eventDate point,
  accountNumber date,
  birthDate date,
  chatId tinyint,
  analyticsId double,
  frameRate timestamp,
  locationId decimal,
  dashboardId blob,
  instructorId enum,
  isVerified real,
  status boolean,
  cartId bigint,
  buildNumber int,
  flagged serial
);

CREATE TABLE record_status (
  id serial primary key,
  url set,
  fontSize int,
  adminNotes float,
  weight time,
  fromDate date,
  monthlyRate enum,
  phone datetime,
  cardNumber set,
  avatar bit,
  lastSeenAt datetime,
  metaTitle double,
  authToken varchar,
  campaignId blob,
  attachmentUrl tinyint,
  downloadCount boolean,
  depositAmount double,
  awardDate float,
  coordinateY decimal,
  configId smallint,
  driverLicense int,
  coverImage timestamp,
  isSystem mediumint,
  employeeCode enum,
  instructorId smallint,
  createdAt decimal,
  gameId datetime,
  headerImage bit,
  enrollmentDate date
);

CREATE TABLE account (
  id serial primary key,
  cartId real,
  mimeType text,
  group timestamp,
  clientId int,
  cloudId bigint,
  gender datetime,
  abandonedCartId enum,
  customField2 serial,
  weight timestamp,
  emailStatus set,
  algorithm set,
  authToken double,
  dataSource real,
  phone timestamp,
  connectionString decimal,
  clockIn smallint,
  costCenter date,
  memberCount varchar,
  accountType bigint,
  startDate set,
  balance tinyint,
  isHidden set,
  chatId enum,
  certificateId bigint,
  password binary,
  manufacturerId smallint
);

CREATE TABLE customer (
  id serial primary key,
  clockOut geometry,
  checkOutTime decimal,
  category serial,
  checkInTime set,
  role timestamp,
  description timestamp,
  machineId tinyint,
  accountNumber timestamp,
  houseNumber tinyint,
  cityName text,
  deactivatedAt tinyint,
  facilityId set,
  guestId serial,
  dataSource point,
  metaDescription datetime,
  algorithm real,
  weight bit,
  mapId timestamp,
  isAdmin timestamp
);

CREATE TABLE core_user_legacy (
  id serial primary key,
  companyName datetime,
  businessType tinyint,
  status bit,
  cloudId text,
  iconPath time,
  favoriteCount text,
  linkId float,
  height float,
  education set,
  customField2 binary,
  city enum,
  costCenter date,
  managerId bigint,
  isDraft geometry,
  flagged real,
  fontSize bigint,
  bankAccount double,
  department geometry,
  countryCode varchar
);

CREATE TABLE product (
  id serial primary key,
  moveId decimal,
  jobTitle timestamp,
  attemptCount boolean,
  state decimal,
  expiryYear int,
  contactEmail int,
  version real,
  isAdmin float,
  balance enum,
  headerImage varchar,
  companyName text,
  currencyCode timestamp,
  customField2 decimal
);

CREATE TABLE factrecordextra (
  id serial primary key,
  feedbackId float,
  validUntil tinyint,
  instanceId blob,
  coverImage int,
  errorCode real,
  eventDate enum,
  integrationId varchar,
  isDraft enum,
  hashKey boolean,
  downloadCount float,
  depositAmount bit,
  frameRate serial,
  completionRate time,
  thumbnail blob,
  password datetime,
  forwardTo set,
  displayName int,
  employeeCode bigint,
  formatType decimal,
  discount time,
  taxRate datetime,
  checkOutTime date,
  metaDescription mediumint,
  cvv set,
  configId mediumint,
  levelId real,
  expiryDate point
);

CREATE TABLE user_log (
  id serial primary key,
  isDraft bit,
  type geometry,
  monthlyRate double,
  fontFamily real,
  jobTitle smallint,
  description float,
  createdAt date,
  listingId date,
  browserType bigint,
  emergencyContact binary,
  expiryYear datetime,
  homePhone double,
  address decimal,
  couponCode set,
  dashboardId tinyint,
  geoLocation bigint,
  authorId double,
  score serial,
  brandId text,
  companyName time,
  height date,
  dateFormat serial,
  itemCount smallint
);

CREATE TABLE olktransactionmap (
  id serial primary key,
  accountNumber tinyint,
  clockIn serial,
  labelText point,
  password float,
  isActive boolean,
  discount boolean,
  country geometry,
  departmentCode datetime,
  latitude date,
  algorithm real,
  chatId float,
  totalAmount blob,
  metaKeywords mediumint,
  lastSeenAt double,
  lockoutEnd decimal,
  dimension varchar,
  ipAddress date,
  phone datetime,
  avatar tinyint,
  chargeId text,
  importId bigint,
  foregroundColor decimal,
  currencyCode text,
  domainName geometry,
  billingFrequency date,
  isSystem bigint,
  authorId mediumint,
  minLimit real,
  bluetoothId bigint,
  shippingAddress set
);

CREATE TABLE reltransaction (
  id serial primary key,
  apiVersion geometry,
  favoriteCount bit,
  isArchived timestamp,
  isDraft date,
  billingFrequency bigint
);

CREATE TABLE product (
  id serial primary key,
  street text,
  metadata float,
  dependentId double,
  size date,
  blogId bit,
  dailyLimit date,
  customerGroup datetime,
  enabledAt binary
);

CREATE TABLE inventory_temp (
  id serial primary key,
  completionRate text,
  balance binary,
  headerImage float,
  clientId enum,
  machineId tinyint,
  awardDate time,
  creditScore enum,
  cloudId mediumint,
  isHidden point,
  isBillable tinyint,
  isDefault float,
  enrollmentDate blob,
  dashboardId datetime,
  metaTitle enum,
  maxLimit date,
  metadata bigint,
  mapId timestamp,
  actionType enum,
  amount blob,
  nickname time,
  status serial,
  errorMessage point,
  emergencyContact enum,
  completedAt set,
  fingerprint float,
  maxValue enum,
  managerId datetime,
  currencyCode geometry,
  description text,
  addressLine1 date,
  colorCode mediumint
);

CREATE TABLE transaction_2024 (
  id serial primary key,
  instanceId bit,
  metaKeywords varchar,
  forwardTo point,
  hostName point,
  deviceId mediumint,
  backupEmail bit,
  deviceToken int,
  firmwareVersion set,
  abandonedCartId int,
  authorId text,
  referralCode set,
  facilityId geometry,
  rating double,
  awardDate real,
  contactName binary,
  email mediumint,
  configId mediumint,
  category real,
  customField2 bit,
  shippingAddress geometry,
  gender mediumint,
  entityId geometry,
  completionRate bit,
  isDefault bit,
  currencyCode boolean,
  homePhone bigint,
  totalAmount point
);

CREATE TABLE record (
  id serial primary key,
  errorCode binary,
  keyId blob,
  longitude mediumint,
  discountCode serial,
  albumId geometry,
  bankAccount time,
  followCount bigint,
  group smallint,
  maxLimit timestamp,
  code real,
  validUntil float,
  email bit,
  companyName boolean
);

CREATE TABLE product_rel (
  id serial primary key,
  certificateId real,
  eventDate timestamp,
  duration real,
  version tinyint,
  foregroundColor set,
  chargeId smallint,
  channelId tinyint,
  phone set,
  isArchived int,
  companyId varchar,
  guestId boolean,
  fileType text,
  flagged time,
  forwardTo smallint,
  ipAddress int
);

CREATE TABLE companyhist (
  id serial primary key,
  customField1 boolean,
  totalAmount bigint,
  certificateId tinyint,
  eventDate geometry
);

CREATE TABLE account (
  id serial primary key,
  authToken text,
  discountCode bit,
  backupEmail binary,
  downloadCount varchar,
  street point,
  bookingDate float,
  billingFrequency smallint,
  name binary,
  chatId timestamp,
  entryPoint varchar,
  insertedAt double,
  joinDate int,
  ipAddress boolean,
  bluetoothId boolean,
  age varchar,
  formatType double,
  awardDate datetime,
  certificateId time,
  longitude varchar,
  couponCode geometry,
  moduleId float,
  salary serial,
  eventDate timestamp,
  dependentId smallint,
  brandId point,
  listingId time
);

CREATE TABLE relaccountdata2024 (
  id serial primary key,
  shippingAddress boolean,
  fileName blob,
  flagged mediumint,
  password varchar,
  faxNumber enum,
  metadata point,
  zipCode timestamp,
  endPoint bit,
  taxRate blob,
  exchangeRate varchar
);

CREATE TABLE src_account (
  id serial primary key,
  moduleId double,
  group mediumint,
  username smallint,
  copyRight blob,
  gateId set,
  discountCode date,
  displayName boolean,
  currencyCode decimal,
  companyId blob,
  zipCode binary,
  emailStatus date,
  emergencyContact blob,
  favoriteCount blob,
  industryType point
);

CREATE TABLE product_map (
  id serial primary key,
  title binary,
  description smallint
);

CREATE TABLE tmp_order_type_2024 (
  id serial primary key,
  nickname double,
  coverImage real,
  gateId smallint,
  companyName geometry,
  completionRate geometry,
  address bigint,
  avatar int,
  copyRight text,
  feedId decimal,
  category varchar,
  fileHash timestamp,
  deactivatedAt bigint,
  fingerprint serial,
  mimeType point,
  emailStatus binary,
  price text,
  checkInTime datetime,
  modifiedAt blob,
  duration double
);

CREATE TABLE extproductlegacy (
  id serial primary key,
  browserType bigint,
  labelText real,
  moduleId boolean,
  endPoint serial,
  eventDate datetime,
  discount decimal,
  coordinateY date,
  hiddenAt enum,
  state set,
  favoriteCount tinyint,
  instructorId text,
  lastName blob,
  unit binary,
  url varchar,
  insuranceId time,
  localeId geometry,
  createdAt serial,
  price timestamp,
  attachmentUrl bigint,
  handlerId bit,
  merchantId boolean,
  chatId geometry
);

CREATE TABLE audit_v1 (
  id serial primary key,
  layerId tinyint,
  feedId text,
  fileType bigint,
  token date,
  levelId bit,
  audioUrl mediumint,
  unit set
);

