CREATE TABLE payment (
  id serial primary key,
  fileSize mediumint,
  avatar geometry,
  isSystem enum,
  title mediumint,
  analyticsId varchar,
  firmwareVersion tinyint,
  integrationId enum,
  merchantId set,
  managerId decimal,
  customerId bit,
  houseNumber serial,
  billingFrequency int,
  ipAddress date,
  validUntil decimal,
  bannerImage time,
  code mediumint,
  employmentDate time,
  content varchar,
  description serial,
  exchangeRate timestamp,
  discount date,
  hourlyRate time
);

CREATE TABLE tblrecorddata (
  id serial primary key,
  customField1 int,
  displayOrder real,
  cancelReason bit,
  balance blob,
  status text,
  likeCount serial,
  exportId varchar,
  latitude date,
  gameId enum,
  expiryYear int,
  entityId binary
);

CREATE TABLE company (
  id serial primary key,
  audioUrl timestamp,
  foregroundColor point,
  formatType text,
  friendId bit,
  dependentId varchar,
  createdAt bigint,
  companyName geometry,
  listingId tinyint,
  cloudId float,
  nickname blob,
  keywords datetime,
  postalCode decimal,
  groupName float,
  billingCycle real,
  firstName tinyint
);

CREATE TABLE payment_map (
  id serial primary key,
  adminNotes bit,
  listId set,
  state int,
  phone timestamp,
  inactiveAt datetime,
  name date,
  hiddenAt boolean,
  clockOut time,
  id binary,
  avatar decimal,
  address smallint,
  ipAddress smallint,
  category point,
  articleId binary,
  exportId double,
  salary tinyint,
  endDate text,
  customerGroup tinyint,
  filterType time,
  domainName set,
  longitude binary,
  companyName enum,
  startDate text,
  password int,
  groupName bit,
  browserType date,
  errorCode serial,
  messageId bit,
  code text,
  isPublic date
);

CREATE TABLE usermeta (
  id serial primary key,
  discountCode time,
  loadTime int,
  addressLine2 varchar,
  lastSeenAt tinyint,
  formatType float,
  size enum,
  itemCount set,
  isFeatured date,
  contactName time,
  username text,
  status mediumint,
  country blob,
  password bit,
  id enum,
  insertedAt enum,
  inactiveAt time,
  fileName smallint,
  avatar serial,
  exportId date,
  currencyCode bigint,
  amount timestamp,
  languageCode mediumint,
  employmentDate int,
  creditLimit float,
  albumId decimal,
  algorithm tinyint
);

CREATE TABLE ver_user_log (
  id serial primary key,
  enrollmentDate datetime,
  instanceId enum,
  updatedAt int,
  displayName point,
  department boolean,
  companyId bigint,
  contactEmail enum,
  isSystem bigint,
  postalCode decimal,
  gameId enum,
  isActive bigint,
  isDeleted geometry,
  authMethod point,
  floorNumber real,
  avatar date,
  firmwareVersion serial,
  departmentCode real,
  rating enum,
  expiryYear point,
  lastLoginAt int,
  role float,
  metadata time,
  mapId datetime,
  hourlyRate int,
  childId serial,
  token point,
  id time,
  size date,
  status real,
  isLocked double,
  coverImage decimal
);

CREATE TABLE customer (
  id serial primary key,
  avatar double,
  incidentId date,
  defaultValue decimal,
  url decimal,
  bankAccount datetime,
  keyId int,
  expiryYear float,
  billingFrequency datetime,
  folderPath point,
  flagged decimal,
  extractId tinyint,
  timezone varchar,
  friendId binary,
  comment serial,
  customField2 tinyint
);

CREATE TABLE product (
  id serial primary key,
  expiryMonth timestamp,
  apiKey datetime,
  coordinateX datetime,
  depositAmount bigint,
  isSystem text,
  displayOrder enum,
  ipAddress tinyint,
  id point,
  endDate datetime,
  createdAt blob
);

CREATE TABLE rel_audit_div (
  id serial primary key,
  cacheKey real,
  comment decimal,
  id decimal,
  discountCode date,
  deviceId datetime,
  group int,
  languageCode tinyint,
  incidentId time,
  depositAmount enum,
  isHidden float,
  checkOutTime blob,
  productCode real,
  attemptCount boolean,
  hashKey tinyint
);

CREATE TABLE customer (
  id serial primary key,
  customField1 set,
  fileSize serial,
  cacheKey bigint,
  mapId mediumint,
  friendId datetime,
  unit smallint,
  hourlyRate serial,
  hostName tinyint,
  customerId date,
  role datetime,
  integrationId serial,
  username point,
  editedAt enum,
  headerImage smallint,
  apiVersion smallint,
  createdAt mediumint,
  depositAmount bit,
  departmentCode bit,
  feedId decimal
);

CREATE TABLE coreaudit (
  id serial primary key,
  addressLine2 set,
  insuranceId geometry,
  referralCode double,
  costCenter date,
  formatType geometry,
  indexKey blob,
  houseNumber blob,
  fromDate boolean,
  accountStatus real,
  channelId serial,
  floorNumber binary,
  displayName geometry,
  geoLocation set,
  endPoint blob,
  customField1 tinyint
);

CREATE TABLE transaction_2025 (
  id serial primary key,
  deviceToken bigint,
  zipCode tinyint,
  creditCard geometry,
  configId double,
  likeCount tinyint,
  driverLicense set,
  username varchar,
  colorCode double,
  authorId datetime,
  accountStatus point,
  foregroundColor serial,
  emergencyContact blob,
  attemptCount point,
  deviceType boolean,
  status smallint,
  cartId geometry,
  hiddenAt geometry,
  isArchived bigint,
  completionRate smallint,
  taxRate geometry,
  fontFamily decimal,
  birthDate bit,
  buildNumber blob,
  duration blob,
  isDefault geometry,
  iconPath geometry,
  couponCode bigint,
  sessionId date
);

CREATE TABLE app_order_notifications (
  id serial primary key,
  integrationId varchar,
  coverImage real,
  frameRate float,
  channelId smallint,
  licenseKey geometry,
  status time,
  activeDevices timestamp,
  totalAmount set,
  employmentDate datetime,
  creditLimit binary,
  phone bit,
  insertedAt smallint,
  claimId time,
  birthDate binary,
  content enum,
  validUntil text,
  bluetoothId geometry,
  shippingAddress boolean,
  taxRate text,
  version smallint,
  copyRight mediumint,
  likeCount tinyint,
  floorNumber datetime,
  layerId geometry,
  errorCode bit,
  deviceId double,
  education int,
  industryType float,
  couponCode timestamp,
  startDate datetime
);

CREATE TABLE user_status_v1 (
  id serial primary key,
  managerId text,
  modifiedAt mediumint,
  name mediumint,
  listingId double,
  coverImage serial,
  isDeleted real,
  lastSeenAt enum,
  enrollmentDate geometry,
  maxLimit decimal,
  clientId blob,
  dailyLimit mediumint,
  fileSize varchar,
  listId timestamp,
  editedAt bit,
  marketId boolean,
  priority time,
  abandonedCartId binary,
  coordinateX date,
  isBillable text,
  businessType tinyint
);

CREATE TABLE company (
  id serial primary key,
  url serial,
  password date,
  isSystem text,
  fileHash enum,
  browserType datetime,
  enrollmentDate float,
  menuId double
);

CREATE TABLE user (
  id serial primary key,
  phone time,
  documentId datetime,
  fileSize mediumint,
  group text,
  frameRate time,
  groupName binary
);

CREATE TABLE payment2025 (
  id serial primary key,
  deactivatedAt float,
  accountStatus serial,
  domainName set,
  comment boolean,
  departmentCode timestamp,
  fileHash mediumint,
  paymentMethod decimal,
  entryPoint mediumint,
  authMethod bigint,
  countryCode enum,
  companyId time,
  messageId datetime,
  actionType real,
  name mediumint,
  state text
);

CREATE TABLE dstorder (
  id serial primary key,
  orderStatus boolean,
  contactPhone float,
  weight text,
  comment blob,
  handlerId boolean,
  budgetCode tinyint,
  dialCode varchar,
  deliveryDate double,
  clockIn time,
  startDate text,
  attachmentUrl point,
  formatType enum,
  score serial,
  id decimal
);

CREATE TABLE transactionstatus (
  id serial primary key,
  defaultValue time,
  insertedAt geometry,
  blogId timestamp,
  cardHolder bit,
  zipCode real,
  mainImage decimal,
  errorMessage smallint,
  frameRate tinyint,
  authToken text,
  modifiedAt text,
  checkOutTime bigint,
  fileSize date,
  browserType blob,
  timezone smallint,
  completionRate decimal,
  isVerified smallint,
  formatType bit,
  algorithm enum,
  floorNumber boolean
);

CREATE TABLE account (
  id serial primary key,
  dailyLimit serial,
  exportId bit,
  address bit,
  rating set,
  lastSeenAt date
);

CREATE TABLE tmp_payment (
  id serial primary key,
  role float,
  defaultValue float,
  department varchar,
  merchantId point,
  extractId varchar,
  size int,
  modifiedAt datetime,
  longitude geometry,
  entityId blob,
  type set,
  listId smallint,
  fontFamily decimal,
  phone tinyint,
  addressLine1 tinyint,
  name tinyint,
  jobTitle bit,
  shippingAddress binary,
  employeeId blob,
  accountType varchar,
  documentId point,
  clockOut timestamp,
  creditScore double,
  completionRate int,
  monthlyRate decimal,
  geoLocation text,
  authMethod real,
  email time,
  dependentId mediumint,
  campaignId float
);

CREATE TABLE record (
  id serial primary key,
  clockIn float,
  distributorId text,
  creditScore int,
  licenseKey boolean,
  timezone float,
  apiKey int,
  maritalStatus boolean,
  meterNumber mediumint
);

CREATE TABLE transaction (
  id serial primary key,
  moduleId enum,
  signature mediumint,
  domainName mediumint,
  indexKey double
);

CREATE TABLE pub_product_rel (
  id serial primary key,
  duration mediumint,
  comment bigint,
  rating point,
  bluetoothId float,
  algorithm float,
  isEnabled decimal
);

CREATE TABLE core_organization (
  id serial primary key,
  lockoutEnd point,
  departmentCode varchar,
  chatId bit
);

CREATE TABLE userseg (
  id serial primary key,
  companyName time,
  enrollmentDate text,
  address geometry,
  entityId bigint,
  awardDate boolean,
  discount text,
  copyRight datetime,
  category float,
  weight float,
  expiryMonth bit,
  fromDate bit,
  fileName point,
  grade serial
);

CREATE TABLE pub_transaction (
  id serial primary key,
  discountCode decimal,
  enrollmentDate text,
  documentId real,
  businessType bit,
  firstName bigint,
  creditScore smallint,
  messageId point,
  managerId float,
  middleName tinyint,
  attachmentUrl date,
  listingId datetime,
  importId smallint,
  email geometry,
  groupName double,
  unit date,
  referralCode bigint,
  folderPath boolean,
  macAddress real,
  fromDate time,
  endPoint double
);

CREATE TABLE organizationlognew (
  id serial primary key,
  clientId mediumint,
  mainImage binary,
  contentType date,
  accountType tinyint,
  configId float,
  attemptCount time,
  isRequired set,
  companyName set,
  errorCode boolean,
  meterNumber datetime,
  certificateId decimal,
  maxLimit bit,
  contactEmail decimal,
  rating bigint,
  content set,
  weight timestamp,
  loadTime binary,
  displayOrder binary,
  feedbackId binary,
  manufacturerId tinyint,
  discount timestamp,
  url float,
  fingerprint real,
  endPoint blob,
  isEnabled bit,
  chatId decimal,
  handlerId varchar,
  priority mediumint,
  logLevel timestamp
);

CREATE TABLE stg_customer (
  id serial primary key,
  dimension smallint,
  analyticsId bigint,
  token enum
);

CREATE TABLE transaction (
  id serial primary key,
  fontFamily text,
  campaignId bigint,
  domainName binary,
  accessLevel mediumint,
  integrationId datetime,
  street binary,
  industryType blob,
  amount bigint,
  backupEmail real,
  lastSeenAt double,
  metaTitle timestamp,
  currency varchar,
  businessType smallint,
  memberCount varchar,
  isArchived text,
  endPoint double,
  birthDate float,
  keyId point,
  createdAt tinyint,
  orderId set,
  gender set,
  cityName datetime,
  discountCode geometry
);

CREATE TABLE refproduct (
  id serial primary key,
  driverLicense enum,
  creditCard serial,
  address set,
  description double,
  employeeId smallint,
  comment time,
  fontFamily enum
);

CREATE TABLE appauditrel (
  id serial primary key,
  courseId bigint,
  comment date,
  employmentDate time,
  creditScore blob,
  isDraft set,
  departmentCode text,
  coordinateY time,
  exportId bit,
  countryCode time,
  analyticsId time,
  dataSource point,
  name timestamp,
  ipAddress float,
  group double,
  password int,
  fileSize binary,
  creditCard point,
  downloadCount bit,
  loginCount set
);

CREATE TABLE inventoryhist (
  id serial primary key,
  expiryYear mediumint,
  cardHolder point,
  emailStatus enum,
  amount time,
  childId float,
  priority smallint,
  instanceId mediumint,
  firstName date,
  customerGroup set,
  certificateId timestamp,
  status enum,
  billingFrequency decimal,
  country geometry,
  forwardTo binary,
  discountCode set,
  orderStatus tinyint,
  extractId date,
  zipCode blob,
  alertType binary,
  coordinateY bit,
  faxNumber mediumint,
  address enum,
  clockOut bigint,
  inactiveAt bit,
  appVersion mediumint,
  duration binary,
  globalId date
);

CREATE TABLE product_div (
  id serial primary key,
  contactPhone binary,
  accountType real,
  checkOutTime float,
  referralCode binary,
  email set,
  expiryYear timestamp,
  expiryDate date,
  phone tinyint,
  ipAddress set,
  firstName int,
  bannerImage timestamp
);

CREATE TABLE olk_record (
  id serial primary key,
  avatar bigint,
  code decimal,
  sessionId time,
  manufacturerId time,
  endDate real,
  category enum,
  hostName decimal,
  employeeId float,
  status enum,
  contactEmail int,
  folderPath int,
  cityName blob,
  metadata smallint,
  enabledAt date,
  attemptCount datetime,
  indexKey serial,
  likeCount datetime,
  deviceId mediumint
);

CREATE TABLE organization (
  id serial primary key,
  claimId int,
  orderStatus date,
  dataSource bit,
  authToken mediumint,
  companyName set,
  abandonedCartId bit,
  merchantId double,
  audioUrl smallint,
  browserType boolean,
  cardNumber geometry,
  contentType serial,
  avatar tinyint,
  macAddress bigint,
  lastLoginAt float,
  height bigint,
  isLocked set,
  createdAt binary,
  totalAmount tinyint
);

CREATE TABLE account (
  id serial primary key,
  metaDescription binary,
  zipCode timestamp,
  size binary,
  description point
);

CREATE TABLE inventory (
  id serial primary key,
  activeDevices decimal,
  companyLogo real,
  defaultValue decimal,
  zipCode mediumint,
  orderId set,
  age set,
  dateFormat boolean,
  driverLicense timestamp,
  grade serial,
  audioUrl datetime,
  contentType decimal,
  updatedAt datetime,
  shippingAddress bigint,
  rating real,
  levelId set,
  dataSource bigint,
  birthDate real,
  agentId int
);

CREATE TABLE extuser (
  id serial primary key,
  middleName mediumint,
  connectionString tinyint,
  isHidden decimal,
  contactPhone date,
  addressLine2 text,
  alertType text,
  analyticsId int,
  brandId date,
  accessLevel float,
  insertedAt decimal,
  instructorId bigint,
  attachmentUrl binary,
  discount binary,
  metaKeywords text,
  cacheKey timestamp,
  itemCount real,
  updatedAt double,
  title smallint,
  department datetime,
  childId timestamp,
  driverLicense boolean,
  address bit,
  cloudId enum,
  languageCode blob,
  cartId boolean,
  actionType tinyint,
  customerGroup bit,
  backupEmail date,
  age text,
  category bigint
);

CREATE TABLE order (
  id serial primary key,
  fingerprint set,
  isFeatured bigint,
  handlerId boolean,
  username int,
  tags blob,
  fileHash enum,
  updatedAt decimal,
  status datetime,
  linkId bigint,
  homePhone set,
  driverLicense int,
  metaTitle blob,
  weight decimal,
  description tinyint,
  isBillable bigint,
  dialCode blob,
  deviceType real,
  currencyCode varchar
);

CREATE TABLE extcustomerinfo (
  id serial primary key,
  modifiedAt point,
  apiKey enum,
  isBillable time,
  isDeleted double,
  comment binary,
  isFeatured date,
  referralCode datetime,
  totalAmount decimal,
  completionRate float
);

CREATE TABLE core_product (
  id serial primary key,
  importId boolean,
  apiVersion text,
  discount time,
  category set,
  globalId tinyint,
  dimension int,
  lockoutEnd boolean,
  batchId varchar,
  group real,
  coordinateX float,
  feedId int,
  latitude geometry,
  employeeCode blob,
  code int,
  isEnabled boolean,
  moduleId date,
  businessType time,
  channelId boolean,
  geoLocation float,
  deactivatedAt float,
  fingerprint bigint,
  favoriteCount float,
  likeCount geometry,
  duration boolean,
  content decimal,
  unit smallint,
  apiKey blob,
  companyId datetime,
  homePhone int,
  status tinyint,
  endDate double
);

CREATE TABLE product (
  id serial primary key,
  globalId datetime,
  value mediumint,
  street datetime,
  cityName smallint,
  contentType bigint,
  currencyCode geometry,
  errorMessage smallint,
  size blob,
  chargeId geometry,
  keyId boolean,
  description double
);

CREATE TABLE tbl_company (
  id serial primary key,
  status date,
  isEnabled bit,
  createdAt timestamp,
  frameRate time,
  monthlyRate set,
  score tinyint,
  isVerified mediumint,
  completedAt varchar,
  education serial,
  addressLine1 point,
  faxNumber text,
  dataSource varchar,
  accountType float,
  errorCode bigint,
  depositAmount blob,
  name enum,
  layerId decimal,
  foregroundColor float,
  sessionId float,
  lastName varchar
);

CREATE TABLE order (
  id serial primary key,
  awardDate varchar,
  lastLoginAt bit,
  apiVersion datetime,
  unit tinyint,
  title bit,
  hashKey blob,
  cartId decimal,
  bookingDate blob,
  cardHolder serial,
  cvv boolean,
  contentType enum,
  token decimal,
  status enum,
  indexKey blob,
  faxNumber double,
  campaignId blob,
  maxValue bit,
  size real,
  extractId int,
  blogId timestamp,
  depositAmount binary,
  accessLevel tinyint,
  code bit
);

CREATE TABLE auditseg (
  id serial primary key,
  clockOut point,
  alertType date,
  industryType float,
  globalId mediumint,
  bookingDate date,
  mapId serial,
  avatar float,
  attachmentUrl text,
  dueDateAt real,
  lastLoginAt serial,
  metaDescription set,
  hourlyRate enum,
  expiryMonth date,
  localeId blob,
  distributorId point,
  bluetoothId tinyint,
  maritalStatus point,
  budgetCode blob,
  dateFormat set,
  dependentId bigint,
  minValue date,
  courseId time,
  meterNumber smallint,
  duration text
);

CREATE TABLE config (
  id serial primary key,
  emergencyContact mediumint,
  lastLoginAt int,
  isRequired set,
  locationId mediumint,
  isVerified float,
  metadata real,
  accountType boolean,
  category bigint,
  fileHash mediumint,
  name varchar,
  childId double,
  billingFrequency boolean,
  defaultLang mediumint,
  token timestamp,
  postalCode timestamp,
  moveId boolean,
  fileType enum
);

CREATE TABLE priv_transaction_temp (
  id serial primary key,
  listingId double,
  defaultValue boolean,
  fileSize boolean,
  insertedAt bit,
  comment set,
  isVerified varchar,
  shippingAddress mediumint,
  manufacturerId int,
  modifiedAt mediumint,
  category point,
  country point,
  billingFrequency decimal,
  industryType bit,
  isDraft date
);

CREATE TABLE dim_user (
  id serial primary key,
  lastLoginAt binary,
  favoriteCount text,
  title int,
  id decimal,
  meterNumber time,
  coordinateX real,
  maskType date,
  url geometry,
  country decimal
);

CREATE TABLE inventory (
  id serial primary key,
  likeCount serial,
  uuid blob,
  birthDate time,
  campaignId boolean,
  cityName tinyint,
  coverImage enum,
  downloadCount enum,
  billingCycle binary,
  deactivatedAt tinyint,
  accountType float,
  dataSource boolean,
  isLocked point,
  dialCode point,
  filterType bigint,
  loadTime varchar,
  createdAt boolean,
  jobTitle real,
  defaultLang tinyint,
  keyId timestamp,
  formatType tinyint,
  exchangeRate date,
  departmentCode int,
  bankAccount enum,
  bluetoothId mediumint,
  dueDateAt mediumint,
  phone tinyint,
  blogId real
);

