CREATE TABLE priv_order (
  id serial primary key,
  analyticsId time,
  isRequired timestamp,
  coverImage int
);

CREATE TABLE auditextra (
  id serial primary key,
  dimension enum,
  loginAttempts point,
  filterType bit,
  billingCycle bit,
  childId bit,
  attemptCount smallint,
  employeeId smallint,
  title smallint,
  thumbnail bigint,
  shippingAddress binary,
  contactName decimal,
  enrollmentDate bit,
  friendId serial,
  hiddenAt serial,
  employmentDate bit,
  comment real,
  salary tinyint,
  dueDateAt blob,
  department enum,
  minLimit bit,
  token bigint,
  industryType timestamp,
  country tinyint,
  meterNumber int
);

CREATE TABLE companylegacy (
  id serial primary key,
  status tinyint,
  endDate set,
  balance tinyint,
  gender bit,
  foregroundColor datetime,
  thumbnail varchar,
  favoriteCount geometry,
  integrationId real,
  size float
);

CREATE TABLE customer_v1 (
  id serial primary key,
  isAdmin geometry,
  entityId boolean,
  phone smallint,
  loadTime tinyint,
  id boolean,
  fingerprint blob,
  foregroundColor int,
  maskType time,
  updatedAt int,
  startDate int
);

CREATE TABLE ref_account_map_2024 (
  id serial primary key,
  clientId timestamp,
  buildNumber point,
  uuid point,
  addressLine1 enum
);

CREATE TABLE pub_order (
  id serial primary key,
  hiddenAt smallint,
  articleId int,
  isAdmin blob,
  completedAt text,
  role tinyint,
  groupName enum,
  lastName boolean,
  configId tinyint,
  lockoutEnd geometry,
  faxNumber boolean,
  dueDateAt enum,
  isRequired bigint,
  category set,
  algorithm varchar,
  analyticsId float,
  geoLocation varchar,
  authorId text,
  id timestamp,
  accessLevel enum,
  loginAttempts bigint,
  channelId serial,
  state smallint,
  customField1 serial,
  password smallint,
  documentId smallint,
  status mediumint,
  itemCount blob,
  actionType bit
);

CREATE TABLE inventorymap (
  id serial primary key,
  checkOutTime binary,
  group real,
  clientId binary,
  keyId point,
  expiryYear binary,
  certificateId serial,
  longitude text,
  guestId double
);

CREATE TABLE appcustomermap (
  id serial primary key,
  fileName real,
  integrationId bigint,
  birthDate datetime,
  certificateId bigint,
  code date,
  metaKeywords decimal,
  deliveryDate blob
);

CREATE TABLE user (
  id serial primary key,
  signature timestamp,
  appVersion decimal,
  isEnabled datetime,
  clockOut int,
  copyRight bit,
  orderStatus bigint,
  isLocked smallint,
  accessLevel date,
  billingFrequency boolean,
  contactName double,
  paymentMethod varchar
);

CREATE TABLE stgproduct (
  id serial primary key,
  metadata time,
  childId mediumint,
  dailyLimit date,
  instructorId real,
  guestId real,
  departmentCode decimal,
  houseNumber tinyint,
  birthDate smallint,
  mapId binary,
  isBillable set,
  macAddress date,
  floorNumber decimal,
  monthlyRate real,
  totalAmount double,
  group int,
  messageId float,
  defaultLang text,
  companyName double,
  memberCount text,
  distributorId blob,
  duration boolean,
  ipAddress boolean,
  mainImage timestamp,
  fileName blob,
  displayName geometry,
  password geometry,
  customerGroup blob,
  isFeatured datetime,
  indexKey set,
  buildNumber set
);

CREATE TABLE company (
  id serial primary key,
  taxRate decimal,
  coordinateX date,
  id varchar,
  fingerprint decimal,
  orderStatus bigint,
  blogId decimal,
  accountType date,
  alertType enum
);

CREATE TABLE core_record (
  id serial primary key,
  earnedPoints date,
  integrationId float,
  creditCard geometry,
  houseNumber decimal,
  middleName smallint,
  gameId timestamp,
  latitude geometry,
  phone bigint,
  incidentId double,
  customerGroup point,
  loadTime decimal,
  category text
);

CREATE TABLE organizationtemp (
  id serial primary key,
  feedbackId bigint,
  isLocked varchar,
  isHidden point,
  accessLevel geometry,
  weight decimal,
  locationId timestamp,
  hashKey enum,
  description geometry,
  category binary,
  extractId date,
  discountCode binary,
  forwardTo boolean,
  indexKey blob,
  completedAt bit,
  fileSize timestamp,
  childId int,
  editedAt tinyint,
  accountStatus decimal
);

CREATE TABLE src_customer (
  id serial primary key,
  contractId decimal,
  merchantId mediumint,
  entryPoint set,
  deviceType float,
  maritalStatus text,
  dailyLimit date,
  contactEmail time,
  middleName bit,
  dependentId time,
  companyLogo binary,
  mobileNumber real,
  accountStatus enum
);

CREATE TABLE dst_account (
  id serial primary key,
  gameId mediumint,
  rating int,
  accessLevel enum,
  deletedAt serial,
  gender boolean,
  errorCode varchar,
  listingId tinyint,
  isVerified decimal,
  createdAt set,
  actionType point,
  favoriteCount tinyint,
  joinDate smallint,
  loadTime date,
  startDate datetime,
  costCenter float,
  invoiceId boolean,
  validUntil blob,
  dataSource tinyint,
  deliveryDate serial,
  cacheKey serial
);

CREATE TABLE company_hist_new (
  id serial primary key,
  accountStatus enum,
  frameRate boolean,
  customField2 int,
  id mediumint,
  height varchar,
  isEnabled decimal,
  comment float,
  minValue int,
  locationId real,
  grade float,
  displayOrder timestamp,
  lastLoginAt bigint,
  firmwareVersion text,
  manufacturerId decimal,
  creditLimit date,
  ipAddress boolean,
  accountType smallint,
  adminNotes geometry,
  apiKey point,
  channelId text
);

CREATE TABLE order (
  id serial primary key,
  avatar set,
  name decimal,
  customField2 datetime,
  modifiedAt tinyint,
  channelId bit,
  contactEmail time,
  phone bit
);

CREATE TABLE sys_company_div (
  id serial primary key,
  globalId tinyint,
  startDate datetime,
  cloudId binary,
  metaTitle real,
  marketId mediumint,
  apiVersion blob,
  customerId tinyint,
  likeCount time,
  dueDateAt double,
  isDefault serial,
  backupEmail varchar
);

CREATE TABLE user_notifications (
  id serial primary key,
  colorCode geometry,
  birthDate set,
  distributorId smallint,
  contactPhone set,
  listId time,
  dateFormat int,
  latitude smallint,
  loginAttempts double,
  batchId real,
  age text,
  longitude real,
  taxRate enum,
  apiVersion smallint
);

CREATE TABLE organization (
  id serial primary key,
  folderPath decimal,
  endPoint bigint,
  joinDate bigint,
  dealerId mediumint,
  billingCycle datetime,
  invoiceId text,
  isAdmin geometry,
  phone float,
  downloadCount text,
  houseNumber enum,
  iconPath binary,
  score boolean,
  enabledAt timestamp,
  cancelReason time,
  depositAmount enum
);

CREATE TABLE relauditout (
  id serial primary key,
  contentType int,
  cityName mediumint,
  description bigint,
  activeDevices varchar,
  isRequired date,
  isAdmin date,
  nickname double,
  fingerprint mediumint,
  ipAddress binary,
  brandId blob,
  friendId bigint,
  actionType blob,
  configId real,
  role datetime,
  currency time,
  employeeId geometry,
  url date,
  title smallint,
  dateFormat timestamp,
  group geometry,
  mimeType float
);

CREATE TABLE account (
  id serial primary key,
  metadata double,
  messageId point,
  headerImage set,
  floorNumber date,
  firstName set,
  attemptCount bit,
  extractId varchar,
  avatar int,
  completedAt timestamp,
  distributorId datetime,
  companyId datetime,
  rating boolean
);

CREATE TABLE companystatus (
  id serial primary key,
  chargeId varchar,
  mobileNumber decimal,
  authToken serial,
  status geometry,
  foregroundColor text,
  companyName timestamp,
  employeeId timestamp,
  size tinyint,
  moduleId set,
  accountStatus text,
  createdAt point,
  title datetime,
  isRequired point,
  birthDate binary,
  id tinyint,
  isArchived smallint,
  age real,
  groupName blob,
  dueDateAt datetime,
  latitude set,
  billingCycle decimal,
  orderStatus set,
  firmwareVersion enum,
  checkInTime bigint,
  budgetCode boolean,
  connectionString varchar
);

CREATE TABLE order_hist (
  id serial primary key,
  postalCode boolean,
  forwardTo smallint,
  expiryDate float,
  agentId text,
  createdAt blob,
  locationId set,
  meterNumber datetime,
  birthDate real,
  isAdmin tinyint,
  description timestamp,
  groupName float,
  linkId date,
  clockIn text
);

CREATE TABLE tbl_payment_extra (
  id serial primary key,
  latitude bigint,
  dailyLimit geometry,
  dateFormat serial,
  addressLine2 point,
  authToken blob,
  activeDevices date,
  age enum,
  apiKey double,
  appVersion blob,
  category boolean,
  isPublic boolean,
  likeCount binary,
  emailStatus serial,
  moduleId float,
  deliveryDate text,
  status real,
  addressLine1 geometry,
  costCenter set,
  description timestamp,
  claimId blob,
  isSystem double,
  sessionId bit,
  enrollmentDate timestamp,
  coverImage point,
  groupName set,
  cardHolder text,
  localeId geometry
);

CREATE TABLE user (
  id serial primary key,
  group date,
  menuId tinyint,
  accountType boolean,
  createdAt int,
  updatedAt geometry,
  comment bit,
  moveId blob,
  fingerprint point,
  middleName point,
  employmentDate int,
  avatar bit,
  depositAmount datetime,
  isBillable decimal,
  sessionId double,
  joinDate mediumint,
  id set,
  likeCount time,
  labelText smallint,
  loginCount point,
  coverImage boolean,
  dateFormat timestamp
);

CREATE TABLE record (
  id serial primary key,
  billingFrequency smallint,
  lastSeenAt int,
  contactPhone float,
  cardHolder timestamp
);

CREATE TABLE inventory_div (
  id serial primary key,
  countryCode real,
  phone serial,
  flagged bigint,
  batchId boolean,
  alertType time,
  cityName date,
  contactName serial,
  maxValue timestamp,
  category set,
  token real,
  discountCode text,
  isPublic bit
);

CREATE TABLE payment_notifications_v1 (
  id serial primary key,
  expiryMonth geometry,
  ipAddress boolean,
  eventDate tinyint,
  indexKey datetime,
  isEnabled boolean,
  attemptCount timestamp,
  displayOrder serial,
  insertedAt mediumint,
  productCode decimal,
  courseId serial,
  accountType time,
  entityId enum,
  brandId float,
  completionRate timestamp,
  address geometry,
  group serial,
  clockOut set,
  articleId int,
  longitude bigint,
  shippingAddress bigint,
  facilityId decimal,
  alertType serial,
  buildNumber real,
  deletedAt text,
  postalCode time,
  accessLevel time
);

CREATE TABLE product2025 (
  id serial primary key,
  duration decimal,
  cityName varchar,
  costCenter date,
  code enum,
  metaDescription real,
  employeeId serial,
  activeDevices blob,
  age point,
  cvv float,
  courseId tinyint,
  quantity tinyint,
  currencyCode tinyint,
  insertedAt bigint
);

CREATE TABLE dst_product (
  id serial primary key,
  claimId blob,
  orderId boolean,
  cartId datetime,
  cancelReason blob,
  isAdmin point,
  entryPoint double,
  balance float,
  dependentId boolean,
  chatId float,
  companyName decimal,
  likeCount datetime,
  unit geometry,
  bannerImage bit,
  middleName time,
  version enum,
  hashKey enum,
  contractId boolean,
  accountType float,
  isRequired mediumint,
  longitude enum,
  childId bigint,
  contactEmail text
);

CREATE TABLE accountmeta (
  id serial primary key,
  meterNumber serial,
  bannerImage point,
  homePhone serial,
  clientId binary,
  quantity boolean,
  defaultValue enum,
  coordinateY binary,
  creditCard text,
  authorId text,
  isDraft decimal
);

CREATE TABLE olk_audit_temp (
  id serial primary key,
  username timestamp,
  updatedAt tinyint,
  uuid boolean,
  metaKeywords decimal,
  analyticsId double,
  id bigint,
  ipAddress smallint,
  checkInTime varchar,
  gameId enum,
  companyLogo set,
  feedbackId date,
  geoLocation int,
  addressLine2 blob,
  dealerId date,
  integrationId enum,
  displayName double,
  description binary,
  firmwareVersion mediumint,
  name timestamp,
  score double,
  minLimit varchar,
  keyId int,
  certificateId datetime,
  fingerprint date,
  completionRate point,
  audioUrl enum
);

CREATE TABLE tmp_user (
  id serial primary key,
  discount serial,
  address date,
  price float,
  accessLevel bigint,
  countryCode point,
  score double,
  amount mediumint,
  firstName enum,
  fontFamily text,
  customerGroup varchar,
  completionRate blob,
  duration datetime,
  deliveryDate timestamp,
  maritalStatus datetime,
  insertedAt varchar,
  feedId real,
  avatar tinyint,
  loginAttempts text,
  errorMessage enum
);

CREATE TABLE sys_payment_out (
  id serial primary key,
  isFeatured int,
  feedId float,
  fileType time,
  accountNumber blob,
  feedbackId boolean,
  foregroundColor point,
  ipAddress decimal,
  category blob,
  paymentMethod blob,
  id datetime,
  isDraft tinyint,
  awardDate set,
  coverImage double,
  comment set,
  abandonedCartId text,
  customerId float,
  phone enum,
  referralCode double,
  customerGroup enum,
  code serial,
  buildNumber time,
  filterType enum,
  isLocked geometry,
  contactName enum,
  creditScore tinyint,
  authToken real
);

CREATE TABLE stg_customer (
  id serial primary key,
  isRequired date,
  updatedAt int,
  meterNumber point,
  discount time,
  keyId datetime,
  category mediumint,
  errorMessage geometry,
  attachmentUrl timestamp,
  department real,
  itemCount binary,
  forwardTo decimal,
  currency boolean
);

CREATE TABLE organization (
  id serial primary key,
  foregroundColor enum,
  linkId bit
);

CREATE TABLE user (
  id serial primary key,
  duration bigint,
  username set,
  accessLevel blob,
  followCount mediumint,
  ipAddress bigint,
  extractId bigint,
  height date,
  minValue serial,
  cloudId mediumint,
  phone bit,
  fromDate set,
  downloadCount boolean,
  mainImage time,
  itemCount geometry,
  hourlyRate point,
  listingId decimal,
  exportId timestamp,
  fontSize bit,
  street bit,
  status datetime,
  id bigint,
  jobTitle bigint
);

CREATE TABLE company (
  id serial primary key,
  instructorId date,
  entryPoint int,
  balance real,
  code geometry,
  batchId timestamp,
  country float,
  isDefault tinyint,
  connectionString tinyint,
  address bigint,
  companyName blob,
  exchangeRate float,
  configId bigint,
  phone int,
  hourlyRate smallint,
  forwardTo binary,
  clockOut date,
  clockIn geometry,
  loginAttempts datetime,
  isArchived decimal,
  cancelReason bigint,
  username double,
  courseId float,
  avatar bigint,
  editedAt date,
  enrollmentDate set,
  extractId tinyint
);

CREATE TABLE configrel (
  id serial primary key,
  attemptCount real,
  metaDescription text,
  handlerId smallint,
  street decimal,
  sessionId time,
  firmwareVersion boolean,
  bluetoothId geometry,
  extractId enum,
  chatId varchar,
  productCode varchar,
  authorId bigint,
  score date,
  domainName tinyint,
  feedId real,
  department timestamp,
  id enum,
  endPoint serial,
  invoiceId int
);

CREATE TABLE srccompany (
  id serial primary key,
  locationId real,
  isLocked bigint,
  eventDate time,
  paymentMethod bigint,
  contactName serial,
  phone float,
  type smallint,
  levelId date,
  avatar geometry,
  birthDate tinyint,
  documentId varchar,
  merchantId date,
  driverLicense varchar,
  completionRate bit
);

CREATE TABLE account (
  id serial primary key,
  password point,
  bannerImage int,
  deviceId decimal,
  gender time,
  contractId double,
  title bit,
  deviceToken bit,
  joinDate datetime,
  comment enum,
  agentId real,
  birthDate binary,
  isRequired real,
  blogId real,
  version tinyint,
  creditScore serial,
  amount geometry,
  address time
);

CREATE TABLE record (
  id serial primary key,
  folderPath timestamp,
  isPublic text,
  facilityId double,
  courseId datetime,
  longitude float,
  departmentCode point,
  errorMessage point,
  homePhone boolean,
  foregroundColor text,
  alertType blob,
  copyRight double,
  username boolean,
  campaignId smallint,
  createdAt date,
  isDefault text,
  deliveryDate decimal,
  cloudId decimal,
  inactiveAt varchar,
  joinDate bit,
  exchangeRate real,
  addressLine2 geometry,
  displayName double,
  moduleId boolean,
  merchantId bit,
  enabledAt timestamp,
  businessType smallint,
  claimId smallint,
  importId geometry,
  labelText time,
  amount geometry,
  lastLoginAt binary
);

CREATE TABLE customer (
  id serial primary key,
  amount mediumint,
  levelId real,
  age serial,
  clockOut text,
  type decimal,
  bluetoothId float,
  chargeId binary,
  enrollmentDate smallint,
  managerId bit,
  headerImage bit,
  abandonedCartId time,
  discount tinyint,
  dimension bigint
);

CREATE TABLE product (
  id serial primary key,
  appVersion int,
  latitude text,
  clientId int,
  maxLimit double,
  favoriteCount mediumint,
  avatar mediumint
);

CREATE TABLE sysconfig (
  id serial primary key,
  productCode time,
  homePhone time,
  currency tinyint,
  customerId decimal,
  isDeleted bit,
  defaultValue bigint,
  dailyLimit set,
  campaignId double,
  group point,
  copyRight blob,
  uuid decimal,
  orderId text,
  password boolean,
  memberCount time,
  actionType bit,
  discountCode decimal,
  metadata bigint,
  deliveryDate point,
  priority serial,
  companyName bit
);

CREATE TABLE tmptransactiondiv (
  id serial primary key,
  accountType bigint,
  url decimal,
  departmentCode serial,
  headerImage tinyint,
  token binary,
  phone blob,
  timezone tinyint,
  labelText point,
  manufacturerId float,
  audioUrl bigint,
  enabledAt binary,
  customerId timestamp,
  name varchar,
  homePhone boolean,
  formatType real,
  contactName binary,
  chargeId blob,
  exchangeRate geometry,
  orderStatus date,
  fileType datetime,
  startDate bit,
  city timestamp,
  faxNumber binary,
  entityId boolean,
  chatId tinyint,
  isActive boolean,
  discount text,
  hostName serial,
  iconPath text
);

CREATE TABLE auditextra (
  id serial primary key,
  dimension varchar,
  cityName double,
  cardHolder varchar,
  audioUrl datetime,
  chatId bigint,
  height varchar,
  gender enum,
  score boolean,
  headerImage tinyint,
  cancelReason set,
  weight blob,
  expiryMonth bigint,
  longitude geometry,
  creditScore tinyint,
  education geometry,
  balance set,
  fontSize mediumint,
  status enum,
  companyName decimal,
  flagged float,
  unit set,
  middleName varchar,
  mobileNumber bigint,
  faxNumber boolean,
  amount binary,
  claimId serial,
  integrationId text
);

CREATE TABLE customer_seg (
  id serial primary key,
  comment geometry,
  businessType enum,
  gateId decimal,
  minLimit text,
  isDraft set,
  indexKey varchar,
  friendId datetime,
  marketId real,
  username blob,
  password blob,
  cancelReason blob,
  token double,
  maskType bit,
  dealerId real,
  salary serial,
  taxRate datetime,
  unit datetime
);

CREATE TABLE audit (
  id serial primary key,
  minLimit int,
  creditLimit real,
  groupName date,
  rating point,
  contactName datetime,
  feedbackId blob,
  currencyCode int,
  agentId date,
  dashboardId serial
);

