CREATE TABLE priv_product_map (
  id serial primary key,
  languageCode datetime,
  metadata smallint,
  password smallint,
  authToken set,
  departmentCode geometry,
  errorMessage geometry,
  contactPhone point,
  customField2 binary,
  category serial,
  insertedAt varchar,
  cartId tinyint,
  employmentDate float,
  groupName float,
  backupEmail time,
  customerGroup enum,
  address enum,
  budgetCode int,
  indexKey mediumint,
  attachmentUrl blob,
  headerImage binary,
  listingId enum,
  uuid datetime,
  firstName double,
  dueDateAt timestamp,
  defaultValue int
);

CREATE TABLE account_seg (
  id serial primary key,
  content double,
  isBillable varchar,
  comment bigint,
  coordinateY real,
  dataSource binary,
  customerId bigint,
  faxNumber int
);

CREATE TABLE extuser (
  id serial primary key,
  category double,
  meterNumber set,
  favoriteCount real,
  employeeCode serial,
  shippingAddress varchar,
  attemptCount smallint,
  keywords double,
  address bigint,
  group serial,
  discountCode tinyint,
  currencyCode binary,
  moveId serial,
  deviceId real,
  loginCount bit,
  browserType set,
  amount timestamp,
  middleName text,
  dimension binary,
  entityId time,
  filterType time,
  buildNumber blob
);

CREATE TABLE product_type (
  id serial primary key,
  mimeType varchar,
  geoLocation mediumint,
  attemptCount mediumint,
  description mediumint,
  browserType mediumint,
  faxNumber float,
  group time,
  dashboardId tinyint,
  dataSource blob,
  activeDevices geometry,
  startDate bit,
  bannerImage time,
  machineId bigint,
  bookingDate point,
  chargeId varchar,
  deviceToken boolean,
  isDefault timestamp,
  totalAmount mediumint,
  bankAccount datetime,
  customField2 varchar,
  title timestamp,
  isArchived varchar,
  avatar timestamp,
  instructorId point
);

CREATE TABLE order (
  id serial primary key,
  distributorId serial,
  firmwareVersion bigint,
  bankAccount bit,
  chargeId datetime,
  category enum,
  labelText datetime,
  exportId timestamp,
  editedAt mediumint,
  maritalStatus serial,
  earnedPoints int,
  updatedAt set,
  moveId float,
  filterType binary,
  longitude decimal,
  gameId double,
  logLevel bit,
  uuid blob,
  address time,
  defaultLang geometry,
  lockoutEnd varchar,
  country tinyint,
  algorithm geometry,
  timezone boolean,
  username blob,
  childId blob,
  password binary,
  status serial
);

CREATE TABLE transaction (
  id serial primary key,
  contractId point,
  apiVersion boolean,
  likeCount enum,
  balance mediumint,
  addressLine2 varchar,
  country bit,
  cityName point,
  browserType bigint,
  createdAt mediumint
);

CREATE TABLE account_v2 (
  id serial primary key,
  employeeId point,
  deliveryDate double,
  folderPath int,
  claimId boolean,
  completedAt binary,
  instructorId timestamp,
  businessType tinyint,
  latitude enum,
  integrationId mediumint,
  expiryMonth tinyint,
  friendId mediumint,
  dashboardId set,
  domainName smallint,
  isActive enum,
  state mediumint,
  adminNotes bigint,
  gender decimal,
  facilityId serial,
  street text,
  sku time,
  cvv real,
  nickname blob,
  shippingAddress bit,
  lastName datetime,
  activeDevices smallint
);

CREATE TABLE rel_payment (
  id serial primary key,
  browserType enum,
  state date,
  description decimal,
  checkInTime geometry,
  copyRight varchar,
  claimId point,
  firstName timestamp,
  totalAmount blob,
  isPublic tinyint,
  monthlyRate bit,
  analyticsId bigint,
  incidentId timestamp,
  channelId float,
  groupName int,
  version serial
);

CREATE TABLE accountmeta (
  id serial primary key,
  gameId binary,
  colorCode decimal,
  name enum,
  dataSource enum,
  articleId datetime,
  displayOrder boolean,
  tags binary,
  documentId serial,
  dialCode real
);

CREATE TABLE priv_account_extra (
  id serial primary key,
  employeeCode timestamp,
  importId enum,
  downloadCount float,
  productCode bigint,
  balance timestamp,
  clockOut enum,
  customerGroup point,
  facilityId binary,
  algorithm point
);

CREATE TABLE payment (
  id serial primary key,
  checkInTime boolean,
  dealerId boolean,
  completedAt mediumint,
  value double,
  address datetime,
  filterType bit,
  gender double,
  appVersion date,
  paymentMethod serial,
  incidentId real,
  fontFamily float,
  email blob,
  completionRate geometry,
  analyticsId blob,
  cartId text,
  gameId text
);

CREATE TABLE priv_audit_notifications_v1 (
  id serial primary key,
  connectionString point,
  apiKey datetime,
  claimId datetime,
  status boolean,
  browserType blob,
  lockoutEnd text,
  validUntil int,
  completedAt datetime,
  forwardTo smallint,
  accountType boolean,
  faxNumber float,
  earnedPoints mediumint,
  documentId geometry,
  totalAmount mediumint,
  coordinateY tinyint
);

CREATE TABLE config_info_new (
  id serial primary key,
  deviceToken real,
  longitude float,
  lastSeenAt set,
  fileName mediumint,
  score bigint,
  ipAddress timestamp,
  industryType bigint,
  countryCode serial,
  dashboardId serial,
  albumId decimal,
  billingFrequency bit
);

CREATE TABLE ref_product_2024 (
  id serial primary key,
  phone binary,
  validUntil date,
  dealerId date,
  bookingDate blob,
  accessLevel tinyint,
  audioUrl int,
  score float,
  domainName datetime,
  clockOut binary,
  isVerified point,
  sessionId point,
  copyRight serial,
  iconPath decimal,
  monthlyRate datetime,
  managerId timestamp,
  name bit,
  handlerId serial,
  modifiedAt datetime,
  bankAccount float,
  id text,
  ipAddress mediumint,
  cvv blob
);

CREATE TABLE cpycustomer (
  id serial primary key,
  isBillable float,
  group timestamp,
  employeeCode enum,
  sessionId varchar,
  bankAccount enum,
  deactivatedAt datetime,
  name blob,
  salary set,
  instructorId date,
  grade serial,
  feedId date,
  fileName binary,
  referralCode decimal,
  instanceId time,
  accessLevel date
);

CREATE TABLE ver_order (
  id serial primary key,
  memberCount bit,
  currency blob,
  metadata time,
  clientId bit,
  deviceToken int,
  hourlyRate double,
  comment time,
  totalAmount boolean,
  minValue binary,
  endDate bigint,
  likeCount binary,
  incidentId serial,
  cardHolder int,
  department point,
  contractId binary,
  copyRight time,
  editedAt serial,
  extractId text,
  fileHash smallint,
  managerId bit,
  metaTitle timestamp
);

CREATE TABLE payment_div (
  id serial primary key,
  clockOut time,
  feedbackId varchar,
  globalId blob,
  customField1 mediumint,
  accountStatus date,
  url varchar,
  cardHolder date,
  downloadCount float
);

CREATE TABLE ext_company (
  id serial primary key,
  email set,
  fileName tinyint,
  middleName double,
  handlerId timestamp,
  itemCount int,
  cvv geometry,
  backupEmail mediumint
);

CREATE TABLE agg_record (
  id serial primary key,
  firmwareVersion boolean,
  taxRate timestamp,
  duration text,
  cacheKey smallint,
  group text,
  creditScore mediumint,
  hiddenAt serial,
  createdAt tinyint,
  errorCode time,
  defaultValue double,
  handlerId double,
  maxValue real,
  status decimal,
  postalCode date,
  avatar int,
  lockoutEnd text,
  mimeType decimal,
  layerId boolean,
  isAdmin float,
  moveId blob
);

CREATE TABLE rel_account_v2 (
  id serial primary key,
  cancelReason float,
  memberCount mediumint,
  companyName mediumint,
  status tinyint,
  editedAt timestamp,
  exportId set,
  loadTime point,
  connectionString tinyint,
  globalId binary,
  currencyCode decimal,
  dimension set,
  state real,
  sessionId int,
  formatType real,
  activeDevices mediumint,
  title bigint,
  iconPath text
);

CREATE TABLE ver_config_map_2024 (
  id serial primary key,
  companyName point,
  moduleId bigint,
  layerId bigint,
  avatar point,
  startDate mediumint,
  locationId blob,
  isActive decimal,
  guestId bit,
  zipCode enum,
  actionType point,
  metadata varchar,
  cityName enum,
  accountType real,
  certificateId datetime,
  city boolean,
  version binary,
  attachmentUrl float,
  salary float,
  feedId geometry,
  claimId binary,
  billingCycle mediumint,
  dataSource float,
  languageCode text
);

CREATE TABLE transaction_notifications (
  id serial primary key,
  uuid real,
  isEnabled bigint,
  token timestamp,
  metaDescription varchar,
  fromDate decimal,
  isHidden date,
  status serial,
  balance mediumint,
  street bit,
  age serial,
  maxLimit real,
  paymentMethod int,
  enabledAt varchar,
  description serial,
  deviceType int,
  weight varchar,
  industryType binary,
  size smallint,
  maxValue binary,
  version bit,
  bookingDate bigint,
  exportId double,
  manufacturerId time,
  expiryDate boolean,
  thumbnail boolean,
  cardNumber text,
  blogId smallint,
  machineId boolean
);

CREATE TABLE product (
  id serial primary key,
  attachmentUrl float,
  createdAt enum,
  activeDevices timestamp,
  chargeId datetime,
  maritalStatus set,
  metadata time,
  metaTitle blob,
  id text,
  dailyLimit serial,
  updatedAt datetime,
  listId timestamp,
  loadTime boolean,
  listingId datetime,
  fileType serial,
  menuId real,
  creditCard tinyint,
  emailStatus int,
  age mediumint
);

CREATE TABLE account (
  id serial primary key,
  indexKey binary,
  displayOrder int,
  clockIn float,
  contactPhone bit,
  group geometry,
  avatar tinyint,
  isBillable real,
  joinDate smallint,
  facilityId decimal,
  dailyLimit mediumint,
  eventDate float,
  downloadCount point,
  birthDate date,
  domainName date,
  orderStatus bigint,
  createdAt mediumint,
  lockoutEnd varchar,
  expiryYear enum,
  dimension point,
  uuid decimal,
  employeeId timestamp,
  likeCount mediumint,
  apiVersion date,
  fromDate bit,
  paymentMethod binary,
  backupEmail varchar,
  chargeId text,
  value enum,
  metaDescription geometry
);

CREATE TABLE companyextra (
  id serial primary key,
  isRequired double,
  email blob,
  balance set,
  isAdmin date,
  fileSize tinyint,
  group bigint,
  extractId point,
  role int,
  contactPhone datetime,
  isDefault set,
  uuid time,
  comment decimal,
  jobTitle serial,
  localeId decimal,
  attachmentUrl binary,
  endDate text,
  menuId boolean,
  token boolean,
  avatar double,
  feedbackId text,
  handlerId tinyint,
  certificateId decimal,
  version mediumint
);

CREATE TABLE audit (
  id serial primary key,
  education set,
  isLocked tinyint,
  addressLine1 text,
  completedAt double,
  isRequired geometry,
  username mediumint,
  totalAmount date,
  loginAttempts time,
  amount boolean,
  flagged int,
  cartId varchar,
  locationId float,
  dataSource tinyint,
  addressLine2 text,
  group serial
);

CREATE TABLE customer_notifications (
  id serial primary key,
  actionType datetime,
  integrationId timestamp,
  sku float,
  avatar bigint,
  score double,
  extractId double,
  discount enum,
  labelText timestamp,
  mainImage bit,
  iconPath bigint,
  currencyCode tinyint,
  formatType float,
  tags mediumint,
  category serial,
  orderStatus date,
  name boolean,
  age smallint,
  jobTitle binary,
  activeDevices bigint,
  contactPhone boolean,
  entryPoint boolean,
  isLocked text
);

CREATE TABLE config (
  id serial primary key,
  attachmentUrl date,
  city float,
  joinDate serial,
  incidentId binary,
  createdAt serial,
  facilityId set,
  title serial,
  dashboardId point,
  lastName binary,
  likeCount mediumint
);

CREATE TABLE tbl_user_div (
  id serial primary key,
  description smallint,
  lastSeenAt float,
  latitude mediumint,
  isDeleted date,
  invoiceId smallint,
  countryCode mediumint,
  enabledAt bit,
  inactiveAt boolean
);

CREATE TABLE privorganization (
  id serial primary key,
  category binary,
  isDeleted datetime,
  mobileNumber double,
  merchantId binary,
  algorithm float,
  displayName timestamp,
  isRequired binary,
  username point,
  duration bigint,
  isPublic mediumint,
  instructorId varchar,
  discountCode real,
  amount smallint,
  ipAddress bigint,
  fingerprint varchar,
  loginAttempts smallint,
  avatar bigint
);

CREATE TABLE aggrecordtemp (
  id serial primary key,
  downloadCount boolean,
  dependentId set,
  minValue bigint,
  avatar boolean,
  unit decimal,
  depositAmount varchar,
  extractId boolean,
  price timestamp,
  hashKey binary,
  name point,
  errorMessage text,
  fileName serial,
  followCount time,
  connectionString decimal,
  activeDevices varchar,
  dashboardId date,
  expiryMonth decimal,
  colorCode text,
  analyticsId mediumint,
  employeeCode timestamp
);

CREATE TABLE ext_customer (
  id serial primary key,
  fileHash double,
  dataSource mediumint,
  gateId enum,
  deviceType datetime,
  expiryYear date,
  faxNumber datetime,
  countryCode varchar,
  category enum
);

CREATE TABLE account_legacy (
  id serial primary key,
  isEnabled real,
  jobTitle real,
  thumbnail set,
  marketId timestamp,
  entryPoint bit,
  friendId date,
  depositAmount serial,
  isFeatured text,
  billingCycle smallint,
  status binary,
  hourlyRate date,
  fontFamily blob,
  score date,
  dimension blob,
  documentId enum,
  unit bit,
  defaultLang varchar,
  group binary,
  editedAt boolean,
  education bigint,
  loginCount timestamp,
  clientId tinyint,
  longitude date,
  courseId geometry,
  hashKey point,
  connectionString serial,
  blogId blob,
  displayName datetime,
  businessType text,
  attachmentUrl geometry
);

CREATE TABLE company_map (
  id serial primary key,
  sessionId timestamp,
  version datetime,
  coordinateX time,
  dateFormat text,
  emergencyContact real,
  contactName datetime,
  exportId float,
  checkOutTime time,
  type binary,
  brandId mediumint,
  deviceId serial,
  filterType double,
  linkId float,
  paymentMethod binary,
  marketId time,
  completedAt serial,
  accessLevel datetime,
  balance set,
  labelText blob,
  actionType smallint,
  channelId datetime,
  childId geometry
);

CREATE TABLE record_v2 (
  id serial primary key,
  geoLocation boolean,
  loadTime double,
  chatId point,
  billingFrequency boolean,
  password set,
  apiKey time,
  maskType blob,
  mobileNumber int,
  bankAccount timestamp,
  eventDate datetime,
  department bigint,
  countryCode datetime,
  alertType decimal,
  grade binary,
  lastSeenAt datetime,
  actionType serial,
  bannerImage set,
  dateFormat bit,
  isDraft mediumint,
  name date,
  filterType float
);

CREATE TABLE inventory (
  id serial primary key,
  connectionString mediumint,
  minValue geometry,
  fileSize datetime,
  createdAt time,
  sku mediumint,
  customerGroup timestamp,
  isDeleted blob,
  depositAmount float,
  version bigint,
  description double,
  loginCount point,
  authMethod float,
  phone text
);

CREATE TABLE tbl_record (
  id serial primary key,
  companyName decimal,
  status mediumint,
  authToken serial,
  alertType tinyint,
  code point,
  customField1 binary,
  accountType real,
  isRequired datetime,
  contactPhone serial,
  exchangeRate binary
);

CREATE TABLE olk_account (
  id serial primary key,
  customField1 varchar,
  customField2 float,
  businessType set,
  colorCode bit,
  batchId serial,
  description enum,
  loadTime boolean,
  listingId time,
  fontFamily varchar,
  cancelReason set,
  appVersion real,
  name time,
  guestId date,
  buildNumber tinyint,
  contactEmail geometry,
  jobTitle boolean,
  fingerprint geometry,
  id decimal,
  importId tinyint,
  height float,
  phone varchar,
  address geometry,
  lastLoginAt double
);

CREATE TABLE log_audit (
  id serial primary key,
  middleName mediumint,
  email blob,
  guestId geometry,
  incidentId timestamp,
  errorCode smallint,
  brandId smallint
);

CREATE TABLE factorganization (
  id serial primary key,
  mapId timestamp,
  eventDate time,
  checkInTime text,
  followCount float,
  budgetCode smallint,
  tags smallint,
  fileType set
);

CREATE TABLE stginventorymeta (
  id serial primary key,
  accountNumber timestamp,
  claimId blob,
  isHidden geometry,
  signature double,
  minLimit double,
  metaKeywords point,
  keyId tinyint,
  machineId smallint,
  gateId mediumint,
  groupName geometry,
  maskType point,
  authMethod point,
  duration smallint,
  floorNumber bigint,
  employeeCode date,
  foregroundColor tinyint,
  timezone int,
  friendId double,
  importId real,
  expiryMonth int,
  costCenter binary,
  listId timestamp,
  hiddenAt datetime,
  password timestamp,
  domainName bigint,
  iconPath geometry,
  memberCount double,
  accountType geometry,
  fontFamily bigint,
  frameRate enum
);

CREATE TABLE payment_out (
  id serial primary key,
  copyRight bigint,
  jobTitle boolean,
  businessType datetime,
  feedbackId serial,
  password real,
  mobileNumber geometry,
  maxValue decimal,
  cacheKey timestamp,
  machineId time,
  driverLicense serial,
  alertType enum,
  homePhone datetime,
  weight timestamp,
  companyId double,
  shippingAddress blob,
  insuranceId blob
);

CREATE TABLE record (
  id serial primary key,
  abandonedCartId boolean,
  isDeleted time,
  code smallint,
  maskType varchar,
  title float,
  budgetCode enum,
  globalId smallint,
  deviceId enum,
  moduleId real,
  taxRate geometry,
  password binary,
  bannerImage date,
  referralCode real,
  priority binary,
  friendId bit,
  isActive varchar,
  department smallint,
  expiryDate tinyint,
  folderPath geometry,
  menuId smallint,
  feedId bit,
  costCenter bit
);

CREATE TABLE log_transaction_archive (
  id serial primary key,
  accountType geometry,
  billingFrequency int,
  appVersion bigint,
  geoLocation real,
  costCenter datetime,
  albumId bit,
  companyLogo time,
  checkOutTime mediumint,
  ipAddress double,
  driverLicense set,
  isAdmin binary,
  contractId date,
  avatar geometry,
  expiryYear point,
  dimension boolean,
  type time,
  iconPath varchar,
  moveId datetime,
  id double,
  amount float
);

CREATE TABLE log_payment (
  id serial primary key,
  joinDate point,
  coordinateY datetime,
  sku smallint,
  employeeId serial,
  billingFrequency blob,
  iconPath blob,
  accountStatus boolean,
  accessLevel binary,
  cardNumber enum,
  analyticsId bigint,
  dialCode smallint,
  forwardTo serial,
  maxLimit float,
  accountNumber serial,
  latitude date,
  token bigint,
  attachmentUrl enum,
  comment datetime,
  discountCode enum,
  dimension time,
  emergencyContact set,
  displayName bit,
  houseNumber smallint,
  city serial,
  mobileNumber int,
  minLimit bit
);

CREATE TABLE audit (
  id serial primary key,
  creditScore date,
  groupName real,
  domainName binary
);

CREATE TABLE cpy_account (
  id serial primary key,
  age point,
  address time,
  layerId point,
  isBillable time,
  depositAmount boolean,
  exchangeRate double,
  albumId time,
  firstName real,
  algorithm blob,
  globalId blob,
  isEnabled double,
  departmentCode point,
  exportId bit,
  maxLimit enum,
  minLimit bit,
  agentId timestamp,
  geoLocation bigint,
  avatar decimal
);

CREATE TABLE srcuser (
  id serial primary key,
  sessionId set,
  isDefault varchar,
  modifiedAt tinyint
);

CREATE TABLE aggrecord (
  id serial primary key,
  blogId binary,
  marketId enum,
  grade float,
  hiddenAt smallint,
  brandId text,
  url boolean,
  endPoint set,
  lastSeenAt blob,
  status timestamp,
  displayName text,
  comment binary,
  isVerified smallint,
  firmwareVersion double,
  cartId geometry,
  dimension mediumint,
  metadata decimal,
  entityId datetime,
  deliveryDate decimal,
  macAddress date,
  defaultLang varchar,
  token timestamp,
  jobTitle text,
  exchangeRate blob,
  weight set,
  isPublic float,
  dataSource geometry,
  insuranceId point,
  accountStatus time,
  bannerImage double
);

CREATE TABLE vw_organization_new (
  id serial primary key,
  height date,
  articleId enum,
  validUntil int,
  priority int,
  description real,
  deviceId date,
  loginAttempts tinyint,
  firstName text,
  driverLicense text,
  group date,
  contractId real,
  itemCount binary,
  amount tinyint,
  listingId blob,
  lockoutEnd decimal,
  value set
);

