CREATE TABLE config (
  id serial primary key,
  deletedAt enum,
  endPoint binary,
  alertType bigint,
  clockOut tinyint,
  firstName boolean,
  deviceId float,
  enabledAt set,
  errorCode smallint,
  lastName set,
  localeId enum,
  departmentCode bit,
  addressLine2 double,
  accountType int,
  weight mediumint,
  copyRight tinyint,
  cloudId blob,
  keywords bit,
  distributorId real,
  dealerId point,
  longitude smallint,
  importId datetime,
  groupName bit
);

CREATE TABLE cpy_audit_rel (
  id serial primary key,
  taxRate blob,
  fileType serial,
  macAddress double,
  levelId tinyint,
  departmentCode bigint,
  dimension blob,
  moveId tinyint,
  channelId boolean,
  age binary,
  clockOut geometry,
  group bit,
  claimId text,
  fontSize timestamp,
  invoiceId timestamp,
  campaignId double,
  contentType decimal,
  employmentDate set,
  followCount geometry,
  metadata geometry,
  sessionId mediumint,
  productCode int,
  accessLevel decimal,
  fontFamily real,
  checkOutTime int,
  facilityId real,
  ipAddress smallint,
  metaKeywords tinyint,
  listingId serial
);

CREATE TABLE stg_transaction (
  id serial primary key,
  longitude date,
  accountType int,
  maskType int,
  loginCount tinyint,
  zipCode binary,
  accountStatus real,
  deactivatedAt int,
  addressLine2 double,
  costCenter date,
  address text,
  companyId binary,
  completedAt int,
  score bigint,
  avatar double,
  fileHash geometry,
  education point,
  managerId varchar,
  customField1 date,
  middleName mediumint,
  attemptCount float,
  editedAt serial,
  minLimit time,
  brandId time,
  dependentId float,
  name real,
  orderId serial,
  frameRate timestamp
);

CREATE TABLE tbl_product_hist (
  id serial primary key,
  followCount serial,
  password double,
  cancelReason point,
  dimension time,
  logLevel date,
  floorNumber mediumint,
  phone blob,
  address decimal,
  checkInTime tinyint,
  handlerId varchar,
  endPoint real,
  street varchar,
  checkOutTime double,
  mainImage blob,
  updatedAt boolean,
  adminNotes datetime,
  headerImage bigint,
  isPublic bigint,
  joinDate geometry,
  countryCode datetime,
  createdAt varchar,
  category tinyint,
  longitude decimal,
  batchId double,
  fileType time,
  couponCode serial
);

CREATE TABLE ext_payment (
  id serial primary key,
  instructorId binary,
  deletedAt bigint,
  moduleId blob,
  cityName serial
);

CREATE TABLE stgcompany (
  id serial primary key,
  firmwareVersion serial,
  channelId decimal,
  frameRate time,
  activeDevices varchar,
  isAdmin blob,
  amount smallint,
  isDraft geometry,
  comment real,
  size boolean,
  group binary,
  documentId enum,
  taxRate smallint
);

CREATE TABLE company_new (
  id serial primary key,
  completedAt point,
  connectionString int,
  feedbackId smallint,
  localeId timestamp,
  fingerprint tinyint,
  insuranceId double,
  countryCode serial,
  metaDescription text,
  licenseKey decimal,
  loginCount bit,
  value mediumint,
  bannerImage blob,
  creditLimit time,
  brandId serial,
  metadata float,
  accountType mediumint,
  title real,
  cartId varchar,
  cvv geometry,
  expiryDate timestamp,
  maritalStatus datetime,
  maxValue timestamp,
  phone binary,
  dimension point,
  duration tinyint,
  displayOrder datetime,
  comment text,
  gender text,
  fontFamily bigint,
  price double
);

CREATE TABLE ext_customer (
  id serial primary key,
  errorCode text,
  dimension binary
);

CREATE TABLE account_type (
  id serial primary key,
  loginAttempts bit,
  fingerprint boolean,
  fromDate text,
  mimeType timestamp,
  headerImage varchar,
  contractId set,
  jobTitle geometry,
  gameId varchar,
  clientId binary,
  cancelReason timestamp,
  contactName int,
  analyticsId text,
  latitude point,
  grade date,
  dailyLimit boolean,
  courseId datetime,
  description date,
  macAddress smallint,
  groupName set,
  isActive serial,
  mainImage serial,
  accessLevel bigint,
  businessType serial,
  globalId blob,
  billingCycle real
);

CREATE TABLE pub_config_log (
  id serial primary key,
  maxValue date,
  contentType smallint,
  city serial,
  emailStatus decimal,
  comment timestamp,
  group float,
  companyName mediumint,
  filterType smallint,
  email datetime,
  cacheKey int,
  checkInTime bit,
  localeId bit,
  deliveryDate binary,
  friendId binary
);

CREATE TABLE inventory_extra (
  id serial primary key,
  birthDate decimal,
  friendId decimal,
  businessType date,
  contactName serial,
  tags date,
  taxRate geometry,
  apiVersion smallint,
  brandId tinyint,
  dateFormat double,
  startDate decimal,
  handlerId point,
  employmentDate bit,
  status point,
  enabledAt smallint,
  entityId tinyint,
  title date,
  companyId set,
  isDraft smallint,
  salary tinyint,
  macAddress int,
  driverLicense blob,
  deactivatedAt geometry
);

CREATE TABLE account (
  id serial primary key,
  brandId time,
  currency geometry,
  totalAmount set,
  feedbackId time,
  listId bit,
  moveId timestamp,
  endDate smallint,
  orderId time,
  category bigint,
  editedAt time,
  followCount text,
  signature geometry,
  coverImage tinyint,
  bookingDate time,
  size text,
  age set,
  marketId text,
  email datetime,
  companyLogo bigint
);

CREATE TABLE stguserv1 (
  id serial primary key,
  activeDevices varchar,
  copyRight date,
  emergencyContact blob,
  listId real,
  coordinateY smallint,
  documentId decimal,
  expiryMonth real,
  customerGroup set,
  handlerId double,
  maxValue blob,
  frameRate bigint,
  age text,
  balance geometry,
  isDefault date,
  browserType text,
  email time,
  role tinyint
);

CREATE TABLE audit (
  id serial primary key,
  headerImage double,
  orderStatus datetime,
  token time,
  isDeleted enum,
  timezone varchar,
  followCount real,
  address double,
  brandId float,
  attachmentUrl varchar,
  accountType blob
);

CREATE TABLE order_archive_2024 (
  id serial primary key,
  fingerprint date,
  agentId mediumint,
  amount bit,
  isRequired decimal,
  companyId binary,
  rating smallint,
  token binary,
  mobileNumber bigint,
  isFeatured real,
  sku date,
  clockIn double,
  exportId time,
  maskType text,
  displayName smallint,
  fileHash enum,
  country timestamp
);

CREATE TABLE log_audit (
  id serial primary key,
  mimeType set,
  contractId time
);

CREATE TABLE order (
  id serial primary key,
  dailyLimit boolean,
  depositAmount binary,
  linkId decimal,
  abandonedCartId float,
  itemCount mediumint,
  foregroundColor double,
  gender boolean,
  inactiveAt bigint,
  deviceToken mediumint,
  feedbackId serial,
  guestId bigint,
  bannerImage double,
  value binary,
  headerImage set,
  agentId double,
  fingerprint datetime,
  coordinateX decimal,
  endDate text,
  blogId boolean,
  dimension date,
  expiryMonth enum
);

CREATE TABLE product_notifications (
  id serial primary key,
  cityName tinyint,
  industryType decimal,
  comment int,
  albumId boolean
);

CREATE TABLE customerlegacy (
  id serial primary key,
  formatType binary,
  contactEmail boolean,
  companyName float,
  url text,
  metadata int,
  isDeleted double,
  guestId enum,
  algorithm set,
  discountCode decimal,
  emailStatus blob,
  levelId timestamp,
  size smallint,
  state float,
  instructorId binary,
  moveId varchar,
  avatar timestamp
);

CREATE TABLE refrecord (
  id serial primary key,
  category blob,
  countryCode bigint,
  globalId timestamp,
  earnedPoints timestamp,
  metaTitle bigint,
  comment int,
  entityId decimal,
  logLevel set,
  id date,
  moveId datetime,
  fileType timestamp,
  lastSeenAt time,
  country smallint,
  awardDate datetime,
  layerId serial,
  createdAt int,
  authorId datetime,
  sessionId serial,
  firstName date,
  languageCode time,
  orderId tinyint,
  likeCount serial,
  dataSource enum,
  hiddenAt bigint,
  mapId text,
  hostName tinyint,
  creditCard blob
);

CREATE TABLE inventorystatus (
  id serial primary key,
  entityId time,
  eventDate enum,
  listingId decimal,
  metaKeywords double,
  apiVersion point,
  filterType time,
  hiddenAt float,
  macAddress set,
  education text,
  price smallint,
  integrationId double,
  campaignId datetime,
  street mediumint,
  coordinateX tinyint,
  dialCode tinyint,
  phone serial,
  lastName timestamp,
  guestId enum,
  isDraft float,
  middleName int,
  avatar smallint,
  merchantId decimal,
  fontFamily blob,
  dueDateAt timestamp,
  maritalStatus tinyint,
  maxValue date,
  id set
);

CREATE TABLE privorganizationmeta (
  id serial primary key,
  invoiceId text,
  country float,
  city serial,
  fileName point,
  labelText set,
  listingId text,
  isBillable smallint,
  customerGroup datetime,
  incidentId blob,
  foregroundColor smallint,
  employmentDate float,
  formatType date,
  errorCode mediumint,
  levelId varchar,
  createdAt set,
  headerImage binary,
  uuid mediumint
);

CREATE TABLE order (
  id serial primary key,
  instanceId datetime,
  phone real,
  grade int,
  maskType date
);

CREATE TABLE tblinventory (
  id serial primary key,
  timezone varchar,
  adminNotes blob,
  exchangeRate serial,
  locationId real,
  connectionString bigint,
  orderId varchar,
  analyticsId timestamp,
  size text,
  lastSeenAt set,
  title geometry,
  inactiveAt bit,
  dialCode double,
  filterType boolean,
  sessionId bigint,
  feedbackId date,
  isPublic float,
  displayName blob,
  couponCode boolean,
  signature int,
  hiddenAt bigint,
  cvv double,
  deactivatedAt blob,
  channelId point,
  value real
);

CREATE TABLE priv_customer (
  id serial primary key,
  firmwareVersion double,
  distributorId set,
  certificateId point,
  actionType geometry,
  buildNumber set,
  cvv boolean,
  isEnabled smallint,
  phone varchar,
  handlerId smallint,
  bookingDate binary,
  isHidden decimal,
  instanceId boolean,
  coordinateY date,
  unit enum,
  keyId time,
  dealerId float,
  timezone decimal,
  completionRate geometry,
  zipCode decimal,
  metaTitle int,
  exchangeRate double,
  billingFrequency text,
  lockoutEnd mediumint,
  productCode blob,
  balance bit,
  globalId serial,
  dependentId datetime
);

CREATE TABLE tmp_product_map (
  id serial primary key,
  marketId text,
  version set,
  url geometry
);

CREATE TABLE transaction_2024 (
  id serial primary key,
  taxRate text,
  earnedPoints date
);

CREATE TABLE dst_organization (
  id serial primary key,
  insuranceId point,
  meterNumber date,
  companyLogo time,
  fileName point,
  labelText boolean,
  referralCode date,
  value enum,
  metaKeywords boolean,
  completionRate int,
  checkInTime double,
  avatar float,
  clockOut varchar,
  comment bigint,
  authToken time,
  metaDescription timestamp,
  domainName decimal,
  score tinyint,
  isAdmin enum,
  isDeleted double,
  gender real,
  keywords datetime,
  accountType text,
  formatType enum,
  street float,
  licenseKey varchar,
  companyName datetime
);

CREATE TABLE tmp_customer_rel (
  id serial primary key,
  isHidden real,
  deviceType varchar,
  chargeId double,
  coordinateX timestamp,
  integrationId geometry,
  entryPoint tinyint,
  role tinyint,
  companyName serial,
  discount bit,
  isPublic decimal,
  friendId time,
  cancelReason mediumint,
  department decimal,
  metaKeywords point,
  groupName int,
  avatar int,
  dateFormat int,
  clockOut bit,
  enabledAt set
);

CREATE TABLE agg_user (
  id serial primary key,
  contactPhone tinyint,
  companyName datetime,
  longitude int,
  cancelReason bigint,
  token int,
  productCode serial,
  editedAt double,
  cloudId date,
  dateFormat geometry,
  signature serial,
  browserType tinyint,
  campaignId mediumint,
  isActive set,
  code bit,
  logLevel decimal,
  isAdmin mediumint,
  cartId bit,
  comment set,
  category double,
  exchangeRate timestamp,
  status blob
);

CREATE TABLE log_organization (
  id serial primary key,
  lastSeenAt enum,
  balance boolean,
  copyRight set,
  costCenter serial,
  isArchived text,
  companyName set
);

CREATE TABLE ver_record (
  id serial primary key,
  fingerprint boolean,
  id tinyint,
  logLevel time,
  listingId datetime,
  moveId float,
  globalId int,
  deviceId enum,
  dueDateAt geometry,
  geoLocation varchar,
  activeDevices text,
  expiryYear bigint,
  cvv serial,
  checkOutTime binary,
  defaultLang decimal,
  authMethod int,
  billingCycle real,
  weight smallint,
  connectionString text,
  algorithm point,
  dialCode bigint,
  companyLogo binary,
  quantity geometry,
  addressLine2 decimal
);

CREATE TABLE dim_customer (
  id serial primary key,
  businessType int,
  grade smallint,
  size mediumint,
  deletedAt bigint,
  likeCount blob,
  dealerId decimal,
  earnedPoints set,
  quantity date,
  longitude time,
  audioUrl boolean,
  deviceToken date,
  mimeType point,
  countryCode boolean
);

CREATE TABLE factconfig (
  id serial primary key,
  email point,
  cartId mediumint,
  completionRate timestamp,
  enrollmentDate bigint,
  address int,
  maskType timestamp,
  itemCount float,
  weight tinyint,
  guestId blob,
  type int,
  dailyLimit smallint,
  childId float,
  signature timestamp,
  instructorId time,
  modifiedAt tinyint,
  indexKey text,
  currencyCode real
);

CREATE TABLE account (
  id serial primary key,
  entityId geometry,
  abandonedCartId enum,
  departmentCode float,
  completionRate decimal,
  displayOrder bigint,
  thumbnail smallint,
  formatType enum,
  metaKeywords tinyint,
  referralCode enum,
  moveId real,
  isLocked serial,
  dailyLimit geometry,
  fileName decimal,
  bannerImage date,
  deviceToken blob,
  endPoint int,
  cacheKey decimal,
  distributorId set,
  gender timestamp,
  taxRate float,
  endDate tinyint,
  value double,
  checkOutTime decimal,
  maxValue blob,
  balance geometry,
  status mediumint,
  password float
);

CREATE TABLE paymentstatus (
  id serial primary key,
  completedAt datetime,
  frameRate text,
  status binary,
  employeeId tinyint,
  blogId int,
  machineId date,
  maxLimit bigint,
  costCenter binary,
  metaDescription smallint,
  creditLimit bit,
  currency blob,
  authorId tinyint,
  group varchar,
  apiVersion serial,
  addressLine1 enum,
  languageCode datetime,
  cartId date,
  eventDate boolean,
  abandonedCartId timestamp,
  cityName decimal,
  gameId bigint,
  birthDate double,
  countryCode bigint,
  favoriteCount timestamp,
  customerId serial,
  emailStatus decimal,
  moduleId int,
  token bit,
  editedAt real
);

CREATE TABLE inventory_data (
  id serial primary key,
  accountType serial,
  mimeType bit,
  id boolean,
  mobileNumber mediumint,
  foregroundColor smallint,
  isPublic boolean,
  cvv datetime,
  metaDescription tinyint,
  agentId point,
  token tinyint,
  weight int,
  articleId varchar,
  depositAmount tinyint,
  name datetime,
  billingCycle blob,
  eventDate decimal,
  state timestamp,
  address geometry,
  endPoint blob
);

CREATE TABLE dst_account_out (
  id serial primary key,
  emailStatus bit,
  title text,
  alertType tinyint,
  inactiveAt decimal,
  bankAccount bigint,
  grade point,
  clockIn boolean,
  zipCode boolean,
  quantity geometry,
  balance time,
  dashboardId time,
  loginAttempts set,
  browserType binary,
  frameRate serial,
  email text,
  domainName tinyint,
  cvv real
);

CREATE TABLE logproduct (
  id serial primary key,
  companyLogo set,
  cardNumber set,
  claimId mediumint,
  fontSize boolean,
  priority point,
  deletedAt tinyint,
  score int,
  city time,
  checkOutTime bigint,
  cityName int,
  alertType bit,
  analyticsId tinyint,
  jobTitle blob,
  employmentDate date,
  linkId set,
  inactiveAt bit,
  listingId text,
  apiVersion tinyint,
  mapId boolean,
  insertedAt binary,
  agentId tinyint,
  languageCode geometry,
  metaKeywords geometry,
  geoLocation bigint,
  articleId binary,
  category int,
  bluetoothId text
);

CREATE TABLE rel_payment_map (
  id serial primary key,
  currencyCode mediumint,
  ipAddress point,
  bluetoothId bit,
  bankAccount timestamp,
  awardDate double,
  budgetCode smallint,
  creditCard set,
  updatedAt real,
  blogId set,
  isVerified int,
  deviceToken text,
  isHidden int,
  courseId smallint,
  guestId geometry,
  feedbackId bit,
  balance boolean,
  friendId datetime,
  dataSource serial,
  alertType geometry,
  monthlyRate mediumint,
  globalId time,
  deliveryDate text,
  rating time,
  companyId decimal,
  authorId mediumint,
  expiryMonth datetime,
  listingId boolean,
  fromDate boolean,
  coverImage decimal
);

CREATE TABLE ref_account (
  id serial primary key,
  hashKey geometry,
  amount smallint,
  feedId point,
  listingId geometry,
  coordinateY datetime,
  abandonedCartId serial,
  groupName timestamp,
  exchangeRate set,
  accountType mediumint,
  customField2 binary,
  driverLicense blob,
  dialCode serial,
  claimId datetime,
  countryCode point,
  dueDateAt bit,
  levelId point,
  backupEmail double,
  locationId enum,
  instructorId real,
  isLocked decimal,
  fileHash real,
  actionType float,
  keyId bigint,
  latitude tinyint,
  id real,
  importId point,
  height blob,
  incidentId time,
  mainImage time
);

CREATE TABLE src_payment_legacy (
  id serial primary key,
  forwardTo decimal,
  enabledAt enum,
  backupEmail decimal,
  startDate decimal,
  productCode timestamp,
  currency timestamp,
  url time,
  currencyCode bigint,
  itemCount set,
  createdAt tinyint,
  cartId decimal,
  id decimal
);

CREATE TABLE corepaymentlog (
  id serial primary key,
  expiryYear geometry,
  defaultLang datetime,
  bookingDate bit,
  description int,
  contentType bigint,
  middleName double,
  avatar int,
  fileHash mediumint,
  fileSize binary,
  articleId smallint,
  orderId bigint,
  locationId mediumint,
  addressLine2 double,
  dailyLimit mediumint,
  facilityId real,
  type datetime,
  deactivatedAt varchar,
  macAddress timestamp,
  city datetime
);

CREATE TABLE aggconfig (
  id serial primary key,
  deviceType smallint,
  mobileNumber enum,
  phone set,
  attemptCount timestamp,
  keywords set,
  entityId blob,
  meterNumber smallint,
  documentId smallint,
  thumbnail text,
  incidentId point,
  checkOutTime set,
  marketId binary,
  hashKey enum,
  locationId blob,
  formatType double,
  loginAttempts bit,
  fileSize serial,
  certificateId timestamp,
  abandonedCartId timestamp,
  avatar timestamp,
  score bit,
  comment blob
);

CREATE TABLE cpycompanyout (
  id serial primary key,
  paymentMethod boolean,
  memberCount enum,
  customerId bit,
  emergencyContact blob,
  instanceId set,
  category tinyint,
  loginAttempts blob,
  creditLimit int,
  accountType double,
  dueDateAt timestamp,
  endPoint real,
  emailStatus text,
  fingerprint tinyint,
  enabledAt bit,
  contactEmail geometry,
  isRequired decimal,
  fromDate set,
  updatedAt point,
  discountCode point,
  uuid geometry,
  contactPhone text,
  gateId blob,
  importId date,
  currencyCode point,
  filterType varchar,
  amount decimal,
  cardHolder enum,
  cityName date
);

CREATE TABLE payment (
  id serial primary key,
  cancelReason geometry,
  metadata bigint,
  enrollmentDate set,
  name tinyint,
  startDate smallint,
  currencyCode bit,
  fontFamily tinyint,
  contractId geometry,
  completedAt int,
  orderStatus float
);

CREATE TABLE product (
  id serial primary key,
  password blob,
  domainName point,
  postalCode double,
  floorNumber double,
  isRequired timestamp,
  distributorId blob,
  accountStatus serial,
  cardHolder serial,
  houseNumber text,
  category datetime,
  size date,
  colorCode datetime
);

CREATE TABLE company (
  id serial primary key,
  gameId time,
  monthlyRate text,
  enabledAt timestamp,
  latitude double,
  adminNotes serial,
  fileType point,
  size binary,
  isSystem double,
  sessionId time,
  errorMessage tinyint,
  ipAddress smallint,
  isEnabled float,
  email geometry,
  deviceId datetime,
  memberCount text,
  quantity bit,
  uuid bigint,
  messageId set,
  totalAmount timestamp,
  listingId point,
  marketId decimal
);

CREATE TABLE config (
  id serial primary key,
  moduleId mediumint,
  awardDate tinyint,
  createdAt boolean,
  validUntil enum
);

CREATE TABLE fact_payment (
  id serial primary key,
  longitude point,
  companyLogo bit,
  zipCode real,
  createdAt tinyint,
  appVersion smallint,
  attachmentUrl serial,
  abandonedCartId smallint,
  validUntil geometry,
  folderPath set,
  type blob
);

