CREATE TABLE inventory (
  id serial primary key,
  apiVersion time,
  copyRight mediumint,
  description float,
  creditScore bit,
  cacheKey double
);

CREATE TABLE app_user (
  id serial primary key,
  labelText double,
  enrollmentDate decimal,
  moveId bigint,
  employeeCode float,
  loginCount timestamp,
  address int,
  hashKey enum,
  albumId enum,
  checkInTime binary,
  instructorId time,
  globalId bit,
  extractId double,
  title text,
  dimension boolean,
  dailyLimit float,
  lastName smallint,
  age binary,
  isArchived int,
  contactName decimal,
  isDeleted double,
  localeId datetime,
  attachmentUrl bigint,
  accountType real,
  invoiceId boolean,
  endPoint enum,
  salary point,
  accessLevel date
);

CREATE TABLE stg_account_v1 (
  id serial primary key,
  errorCode binary,
  gameId text,
  firstName double,
  value real,
  deletedAt bigint,
  creditCard double,
  referralCode blob,
  comment int,
  category serial,
  cvv boolean,
  linkId float,
  dateFormat tinyint,
  clientId datetime,
  updatedAt point
);

CREATE TABLE product_v2 (
  id serial primary key,
  city boolean,
  isHidden varchar,
  firmwareVersion double,
  fontFamily text,
  salary varchar,
  addressLine1 time,
  manufacturerId decimal,
  meterNumber decimal,
  hiddenAt enum,
  followCount time,
  mimeType geometry,
  deletedAt mediumint,
  backupEmail bigint,
  coverImage set,
  fingerprint set,
  colorCode text,
  lastSeenAt varchar,
  batchId point,
  metaKeywords set,
  fontSize point,
  memberCount set,
  priority serial,
  avatar binary,
  street boolean,
  isAdmin datetime,
  hashKey varchar,
  displayOrder set,
  token varchar,
  locationId binary,
  deviceId real
);

CREATE TABLE account (
  id serial primary key,
  loadTime decimal,
  billingFrequency enum,
  latitude smallint,
  cancelReason binary,
  customerGroup serial,
  cvv geometry,
  dateFormat enum,
  fileName float,
  fileType tinyint,
  fontSize tinyint,
  city time,
  displayName float,
  cardHolder text,
  attemptCount bigint,
  hourlyRate bigint,
  description tinyint,
  addressLine1 mediumint
);

CREATE TABLE stg_transaction_v1 (
  id serial primary key,
  cardHolder mediumint,
  height point,
  dailyLimit varchar,
  forwardTo set,
  authToken float,
  contractId timestamp,
  salary int,
  phone timestamp,
  isPublic set,
  priority datetime,
  title geometry,
  localeId time,
  balance boolean,
  monthlyRate boolean
);

CREATE TABLE olk_customer (
  id serial primary key,
  followCount bit,
  mainImage int,
  tags real,
  longitude smallint,
  dealerId tinyint
);

CREATE TABLE transaction (
  id serial primary key,
  expiryYear double,
  state mediumint,
  keyId geometry,
  isLocked point,
  billingCycle enum,
  password tinyint,
  salary geometry,
  group geometry,
  dialCode real,
  url serial,
  machineId binary,
  amount serial,
  brandId smallint,
  duration text,
  listId float,
  downloadCount smallint,
  bookingDate bit,
  lastName tinyint,
  frameRate point,
  contactEmail boolean,
  gameId real
);

CREATE TABLE sys_user (
  id serial primary key,
  enabledAt bigint,
  departmentCode point,
  metaKeywords float,
  floorNumber geometry,
  depositAmount binary,
  updatedAt blob,
  keyId int,
  customerGroup varchar,
  education serial,
  downloadCount serial,
  lastName binary,
  clockIn double,
  channelId bit,
  category mediumint
);

CREATE TABLE user_v2 (
  id serial primary key,
  age double,
  followCount real,
  fontFamily boolean,
  groupName text,
  signature enum,
  backupEmail point,
  rating smallint,
  cancelReason tinyint,
  apiKey decimal,
  amount bigint,
  messageId varchar,
  jobTitle float,
  content double,
  distributorId set,
  completedAt bit,
  feedId mediumint,
  hashKey blob,
  loginCount smallint,
  mapId point,
  exportId smallint,
  creditCard int,
  customerId set,
  domainName smallint
);

CREATE TABLE record_div (
  id serial primary key,
  chatId real,
  billingFrequency mediumint,
  isEnabled float
);

CREATE TABLE audit (
  id serial primary key,
  insertedAt double,
  name bit,
  errorMessage set,
  token tinyint,
  version time,
  floorNumber text,
  dataSource time,
  isPublic boolean,
  employeeId set,
  addressLine2 text,
  deactivatedAt point,
  albumId int,
  avatar datetime,
  cacheKey boolean,
  folderPath enum,
  forwardTo blob,
  balance bigint,
  exchangeRate smallint,
  headerImage double,
  expiryYear double,
  title set,
  maskType float,
  geoLocation float,
  logLevel text,
  salary text,
  guestId tinyint,
  hiddenAt float,
  monthlyRate float
);

CREATE TABLE rel_user (
  id serial primary key,
  connectionString date,
  formatType datetime,
  fontFamily bigint,
  totalAmount blob,
  attachmentUrl varchar,
  licenseKey point,
  longitude decimal,
  dailyLimit varchar,
  size bit,
  levelId date,
  createdAt timestamp,
  amount tinyint,
  expiryMonth set,
  name varchar,
  machineId binary,
  isDefault point,
  latitude mediumint,
  dialCode enum,
  companyName point,
  deletedAt enum,
  avatar bigint,
  campaignId smallint,
  price tinyint,
  comment time,
  memberCount smallint,
  budgetCode varchar,
  employeeCode point,
  handlerId int,
  colorCode binary,
  depositAmount mediumint
);

CREATE TABLE product_map (
  id serial primary key,
  gender set,
  adminNotes real
);

CREATE TABLE app_payment_log (
  id serial primary key,
  moveId timestamp,
  companyName geometry,
  blogId set,
  loginCount point,
  hostName text,
  timezone serial,
  deviceType bit,
  attachmentUrl real,
  enrollmentDate decimal,
  claimId float,
  emailStatus blob,
  totalAmount smallint,
  metadata timestamp,
  creditScore serial,
  incidentId tinyint,
  latitude bit,
  expiryYear text,
  customerGroup bit,
  validUntil int,
  longitude tinyint,
  customField1 timestamp,
  batchId real,
  status decimal,
  category real,
  fingerprint tinyint,
  group blob,
  isVerified bit,
  lockoutEnd enum
);

CREATE TABLE payment_temp (
  id serial primary key,
  middleName time,
  floorNumber blob,
  accountType blob,
  maritalStatus timestamp,
  zipCode decimal,
  duration tinyint,
  comment float,
  companyName mediumint,
  amount tinyint,
  blogId double,
  fileName mediumint,
  postalCode mediumint,
  fileSize serial,
  geoLocation varchar,
  sessionId serial,
  age double,
  birthDate blob,
  inactiveAt int,
  followCount geometry,
  agentId geometry,
  analyticsId tinyint,
  grade double,
  fingerprint enum,
  isBillable point,
  createdAt text
);

CREATE TABLE account_temp (
  id serial primary key,
  hashKey date,
  companyLogo blob,
  fileHash smallint,
  exchangeRate geometry,
  industryType int,
  createdAt tinyint,
  price double,
  role mediumint,
  budgetCode geometry,
  contactEmail double,
  configId geometry,
  cacheKey int,
  agentId set,
  fileName mediumint,
  enabledAt decimal,
  coordinateX set,
  isFeatured binary,
  cardNumber int,
  joinDate real,
  instanceId point,
  forwardTo boolean,
  password varchar,
  longitude bit,
  managerId text,
  id bigint,
  handlerId float,
  deviceId varchar,
  appVersion tinyint,
  isRequired bigint,
  keyId double,
  description bigint
);

CREATE TABLE tbl_transaction_2024 (
  id serial primary key,
  foregroundColor blob,
  filterType serial,
  dashboardId geometry,
  manufacturerId time,
  homePhone blob,
  departmentCode varchar,
  inactiveAt geometry,
  totalAmount blob,
  coordinateX double,
  hiddenAt decimal,
  authToken decimal,
  invoiceId boolean
);

CREATE TABLE company (
  id serial primary key,
  cityName timestamp,
  loadTime enum,
  bluetoothId boolean,
  marketId decimal,
  createdAt time,
  activeDevices bit,
  isBillable date,
  monthlyRate time,
  displayOrder int,
  globalId blob,
  fileSize date,
  accountNumber decimal,
  completionRate binary,
  cartId enum,
  contactName double,
  colorCode enum,
  appVersion text,
  domainName boolean,
  departmentCode mediumint,
  thumbnail varchar,
  group bigint,
  firstName varchar,
  adminNotes varchar,
  cancelReason enum,
  enrollmentDate decimal,
  batchId double,
  description double
);

CREATE TABLE audit (
  id serial primary key,
  insertedAt blob,
  invoiceId varchar,
  discount set,
  formatType bit,
  customField2 time
);

CREATE TABLE payment (
  id serial primary key,
  extractId text,
  modifiedAt set,
  group bit,
  minLimit real,
  campaignId point,
  category real,
  forwardTo datetime,
  listId bigint,
  contactName real,
  comment int,
  lastLoginAt bigint,
  deletedAt bit,
  marketId datetime,
  clockOut text,
  createdAt tinyint,
  linkId double,
  customField1 enum,
  earnedPoints bigint,
  creditScore boolean,
  ipAddress bigint,
  labelText bigint,
  maxValue text,
  isActive tinyint
);

CREATE TABLE rel_customer (
  id serial primary key,
  itemCount smallint,
  iconPath boolean,
  fileName geometry,
  employeeId real,
  firmwareVersion serial,
  monthlyRate mediumint
);

CREATE TABLE coretransactionseg (
  id serial primary key,
  macAddress bigint,
  role double,
  bannerImage int,
  agentId datetime,
  marketId datetime,
  localeId int,
  city varchar,
  email set,
  attachmentUrl datetime,
  machineId date,
  price text,
  updatedAt smallint,
  abandonedCartId time,
  totalAmount real,
  street binary,
  nickname smallint,
  password decimal,
  filterType float,
  age int,
  meterNumber serial,
  handlerId varchar,
  department timestamp,
  cvv point,
  errorCode serial,
  insuranceId serial,
  paymentMethod smallint,
  industryType text,
  phone int,
  entryPoint binary,
  floorNumber bit,
  extractId boolean
);

CREATE TABLE olk_payment (
  id serial primary key,
  mapId date,
  feedId decimal,
  customerGroup smallint
);

CREATE TABLE product (
  id serial primary key,
  layerId mediumint,
  gender varchar,
  accountStatus int,
  phone varchar,
  apiVersion datetime,
  isDefault real,
  buildNumber serial,
  dashboardId time,
  longitude double,
  sessionId text,
  homePhone point,
  loadTime boolean,
  entityId serial,
  cancelReason tinyint,
  group text,
  balance time,
  checkInTime datetime,
  isFeatured real,
  cvv point,
  priority binary,
  employeeCode float
);

CREATE TABLE inventory (
  id serial primary key,
  clientId timestamp,
  bookingDate tinyint,
  isSystem double,
  brandId blob,
  maritalStatus enum,
  totalAmount bit,
  incidentId int,
  contactName set,
  locationId boolean,
  title varchar,
  name text,
  balance blob,
  creditCard text,
  documentId point,
  discount text
);

CREATE TABLE company_info_v1 (
  id serial primary key,
  expiryMonth int,
  comment timestamp,
  code decimal,
  shippingAddress set,
  geoLocation geometry,
  completionRate tinyint,
  phone date,
  feedId enum,
  type varchar,
  customerId set,
  algorithm tinyint,
  id blob,
  username bit,
  validUntil varchar,
  role int,
  token mediumint,
  languageCode int,
  taxRate text,
  linkId double,
  batchId float,
  fontFamily bit,
  fileSize float,
  sessionId point,
  name binary,
  customerGroup varchar,
  managerId date,
  dataSource binary,
  defaultLang real,
  creditScore enum,
  childId varchar,
  billingCycle set
);

CREATE TABLE record_info (
  id serial primary key,
  fileName point,
  productCode geometry,
  itemCount date,
  password double,
  address bigint,
  couponCode tinyint,
  clockIn mediumint,
  childId datetime,
  thumbnail datetime,
  expiryDate binary,
  completionRate mediumint,
  currencyCode tinyint,
  errorCode enum,
  billingCycle set,
  uuid bit,
  countryCode datetime,
  backupEmail real,
  maskType smallint,
  logLevel boolean,
  floorNumber varchar
);

CREATE TABLE priv_account_log (
  id serial primary key,
  sessionId mediumint,
  orderStatus mediumint,
  manufacturerId decimal,
  longitude geometry,
  name tinyint,
  dateFormat float,
  cartId enum,
  status serial,
  addressLine1 varchar,
  metaKeywords date,
  ipAddress decimal
);

CREATE TABLE app_record (
  id serial primary key,
  brandId boolean,
  id bigint,
  token varchar,
  group bigint,
  completionRate blob,
  articleId set,
  contactEmail time,
  type float,
  firstName real,
  authToken datetime,
  localeId date,
  ipAddress boolean,
  avatar int,
  hourlyRate boolean,
  merchantId binary
);

CREATE TABLE priv_product (
  id serial primary key,
  isFeatured tinyint,
  forwardTo int,
  category point,
  expiryYear timestamp,
  handlerId set,
  firstName float,
  longitude boolean,
  documentId tinyint,
  age tinyint,
  insuranceId blob,
  comment real,
  childId serial,
  isArchived set,
  unit bigint,
  dependentId boolean,
  domainName text,
  filterType date,
  budgetCode int,
  coordinateY enum,
  balance smallint,
  downloadCount float,
  customerId enum,
  inactiveAt binary,
  editedAt serial,
  employeeId bigint,
  maritalStatus text,
  locationId real,
  timezone boolean
);

CREATE TABLE dst_inventory (
  id serial primary key,
  clockOut datetime,
  totalAmount blob,
  isDeleted bit,
  hostName time,
  departmentCode int,
  errorMessage bigint,
  itemCount date,
  birthDate bit,
  loginCount tinyint,
  locationId bigint,
  albumId text,
  actionType serial,
  fromDate smallint,
  integrationId serial,
  messageId serial,
  avatar int,
  costCenter real,
  handlerId point,
  version boolean,
  isEnabled text,
  iconPath float,
  keywords bigint,
  browserType text,
  mainImage timestamp,
  guestId decimal,
  city float,
  invoiceId point,
  isBillable geometry,
  url bit
);

CREATE TABLE config_out (
  id serial primary key,
  documentId decimal,
  companyName text,
  clockIn time,
  businessType time,
  deviceId datetime,
  expiryDate real,
  accessLevel bigint,
  longitude blob,
  productCode tinyint,
  dashboardId geometry,
  menuId point,
  isEnabled bit,
  attemptCount decimal,
  firmwareVersion geometry,
  mapId int
);

CREATE TABLE organization (
  id serial primary key,
  accessLevel blob,
  role geometry,
  algorithm geometry,
  actionType geometry,
  rating enum,
  description serial,
  fontFamily geometry,
  createdAt serial,
  department time,
  discountCode date,
  geoLocation bigint,
  entryPoint serial,
  comment decimal,
  addressLine1 tinyint,
  chargeId boolean,
  ipAddress blob,
  title time,
  awardDate serial,
  defaultValue serial,
  frameRate serial,
  companyLogo datetime,
  email real,
  firstName enum,
  domainName text,
  height float,
  signature mediumint,
  age int,
  maxLimit serial,
  cloudId enum,
  isLocked timestamp,
  isPublic date
);

CREATE TABLE audit (
  id serial primary key,
  maxLimit time,
  shippingAddress text,
  productCode blob,
  paymentMethod real,
  coordinateY float,
  albumId float,
  accessLevel bit,
  countryCode double,
  attachmentUrl binary,
  isAdmin geometry,
  messageId text,
  quantity serial,
  emergencyContact mediumint,
  password tinyint,
  creditLimit smallint,
  clockOut timestamp,
  referralCode serial,
  colorCode varchar,
  dueDateAt int,
  fingerprint mediumint,
  timezone bigint,
  accountNumber datetime,
  instructorId smallint,
  isHidden tinyint,
  cacheKey int,
  fileName tinyint,
  startDate double,
  category set,
  completedAt time,
  filterType set,
  entityId bigint
);

CREATE TABLE priv_organization (
  id serial primary key,
  cacheKey int,
  maxLimit real,
  claimId decimal,
  tags varchar,
  deviceToken real,
  status double,
  isAdmin float,
  accountType tinyint,
  value geometry,
  locationId smallint,
  merchantId blob,
  favoriteCount mediumint,
  foregroundColor time,
  gateId enum,
  longitude decimal,
  customerGroup set
);

CREATE TABLE organization_meta (
  id serial primary key,
  fontFamily real,
  copyRight bigint,
  totalAmount text,
  completionRate set,
  quantity mediumint,
  gateId geometry,
  blogId bit,
  createdAt geometry,
  size point,
  expiryDate date,
  timezone date,
  hiddenAt text,
  indexKey decimal,
  instructorId mediumint,
  awardDate geometry,
  labelText datetime,
  street binary,
  validUntil date,
  gender binary,
  isVerified bigint,
  editedAt bigint,
  height geometry,
  appVersion int,
  isFeatured smallint,
  endDate point
);

CREATE TABLE organization (
  id serial primary key,
  value varchar,
  code serial,
  foregroundColor serial,
  type decimal,
  bannerImage timestamp,
  name timestamp,
  albumId mediumint,
  courseId date,
  moveId datetime,
  algorithm smallint,
  authMethod bigint,
  folderPath int,
  machineId geometry,
  isRequired text,
  locationId time,
  guestId geometry,
  minValue tinyint,
  driverLicense set,
  productCode datetime,
  isLocked datetime,
  chatId serial,
  street timestamp,
  rating binary,
  invoiceId binary,
  marketId tinyint,
  entityId point,
  displayName point,
  maxLimit double
);

CREATE TABLE user_status (
  id serial primary key,
  mainImage float,
  checkOutTime time,
  sessionId binary,
  authMethod tinyint,
  modifiedAt binary,
  depositAmount point,
  emergencyContact text,
  certificateId enum
);

CREATE TABLE cpyorderlog (
  id serial primary key,
  name timestamp,
  adminNotes serial,
  extractId double,
  keywords binary,
  referralCode time,
  insertedAt smallint,
  checkInTime decimal,
  cardNumber bigint,
  folderPath varchar,
  enabledAt timestamp,
  activeDevices text,
  avatar real
);

CREATE TABLE config_temp (
  id serial primary key,
  contractId bigint,
  amount time,
  isDeleted geometry,
  emailStatus text,
  taxRate bigint,
  isVerified smallint,
  maxLimit date,
  weight binary
);

CREATE TABLE order (
  id serial primary key,
  metadata real,
  handlerId float,
  age decimal,
  entityId decimal,
  contractId bigint,
  metaTitle geometry,
  incidentId binary,
  exchangeRate decimal,
  isPublic time,
  channelId int,
  isRequired date,
  sku smallint,
  dealerId bit
);

CREATE TABLE inventory (
  id serial primary key,
  hostName serial,
  completedAt date,
  hiddenAt bigint
);

CREATE TABLE tbl_company (
  id serial primary key,
  employmentDate serial,
  avatar varchar,
  manufacturerId point,
  isVerified float,
  minValue int,
  iconPath timestamp,
  depositAmount double,
  enrollmentDate tinyint,
  latitude varchar,
  companyId bigint,
  isDraft tinyint,
  fileHash datetime,
  dailyLimit int,
  isDeleted tinyint,
  minLimit datetime,
  driverLicense mediumint,
  password point,
  comment binary,
  score bigint,
  campaignId binary,
  startDate enum,
  listingId decimal,
  billingFrequency real
);

CREATE TABLE product (
  id serial primary key,
  createdAt int,
  dialCode time,
  exchangeRate smallint,
  itemCount float,
  backupEmail bigint,
  avatar tinyint,
  completionRate double,
  exportId smallint,
  contractId bit,
  balance enum,
  group text,
  entityId set,
  buildNumber varchar,
  addressLine1 mediumint,
  lastLoginAt datetime,
  token date,
  contactPhone tinyint,
  houseNumber date,
  zipCode binary,
  deactivatedAt boolean,
  bookingDate bigint,
  dashboardId real,
  cacheKey decimal,
  currency date,
  coverImage timestamp
);

CREATE TABLE dstpaymentnew (
  id serial primary key,
  groupName point,
  browserType enum,
  dimension geometry
);

CREATE TABLE record (
  id serial primary key,
  campaignId binary,
  isDeleted int,
  chatId enum,
  createdAt time,
  customField1 int,
  accountType serial,
  clockIn datetime,
  fileHash float,
  keyId varchar,
  clientId float,
  mobileNumber text,
  companyName boolean,
  metadata text,
  dialCode decimal,
  blogId real,
  password bit,
  homePhone boolean,
  adminNotes int,
  cardNumber smallint,
  copyRight int
);

CREATE TABLE tbl_transaction_div (
  id serial primary key,
  cardNumber mediumint,
  category point,
  value double,
  unit boolean,
  description real,
  isDefault double,
  formatType enum,
  channelId time,
  quantity int,
  zipCode smallint
);

CREATE TABLE cpyconfigtemp (
  id serial primary key,
  ipAddress blob,
  email smallint,
  formatType bigint,
  blogId decimal
);

CREATE TABLE ext_customer (
  id serial primary key,
  accessLevel enum,
  validUntil set,
  customerId timestamp,
  billingCycle bigint,
  priority date,
  listId int,
  mapId varchar,
  countryCode datetime
);

