CREATE TABLE customer (
  id serial primary key,
  sku text,
  attachmentUrl time,
  messageId double,
  thumbnail time,
  dailyLimit geometry,
  industryType mediumint,
  feedbackId double,
  companyName bigint,
  mobileNumber timestamp,
  token timestamp,
  status datetime,
  expiryDate serial,
  quantity varchar,
  contactEmail bigint
);

CREATE TABLE transaction (
  id serial primary key,
  defaultValue enum,
  fromDate geometry
);

CREATE TABLE core_customer_v2 (
  id serial primary key,
  gender geometry,
  dateFormat real,
  avatar float,
  guestId boolean,
  distributorId time,
  hiddenAt float,
  companyName real,
  copyRight smallint,
  errorCode int,
  claimId real,
  joinDate text,
  contractId float,
  category date,
  version int,
  bankAccount int,
  cityName float,
  emailStatus date,
  timezone time,
  emergencyContact serial
);

CREATE TABLE tmp_record (
  id serial primary key,
  mobileNumber enum,
  id set,
  maxLimit timestamp,
  layerId time,
  minLimit float,
  deviceToken date,
  employmentDate boolean,
  latitude geometry,
  buildNumber bigint
);

CREATE TABLE tbl_transaction_type (
  id serial primary key,
  appVersion date,
  ipAddress varchar,
  avatar bigint,
  defaultValue point,
  token timestamp,
  quantity text,
  zipCode bigint,
  channelId text,
  cityName enum,
  contactName float,
  latitude text,
  companyName int,
  copyRight time,
  accountStatus time,
  enabledAt timestamp,
  menuId binary,
  accountType datetime,
  indexKey binary,
  isHidden mediumint,
  mainImage int
);

CREATE TABLE cpy_account (
  id serial primary key,
  formatType date,
  monthlyRate boolean,
  isAdmin varchar,
  dimension text,
  globalId date,
  activeDevices decimal,
  clockIn blob,
  metaTitle double,
  appVersion time,
  paymentMethod blob,
  fileHash point,
  size blob,
  keyId binary,
  moveId serial,
  productCode datetime,
  customerId text,
  followCount datetime,
  role tinyint,
  integrationId bigint,
  contactName timestamp,
  token enum,
  fileType date,
  deletedAt text,
  maxValue varchar
);

CREATE TABLE company (
  id serial primary key,
  claimId real,
  accountType blob,
  thumbnail serial,
  shippingAddress int,
  metaTitle int,
  firstName real,
  productCode text,
  fileSize mediumint,
  age bit,
  token blob,
  fingerprint mediumint,
  maskType bit,
  houseNumber bigint,
  timezone text,
  tags bit,
  filterType bit,
  isSystem timestamp,
  paymentMethod bit,
  deactivatedAt serial,
  entryPoint set,
  weight smallint,
  batchId binary,
  phone smallint,
  meterNumber enum,
  address float
);

CREATE TABLE organization_2025 (
  id serial primary key,
  insertedAt real,
  validUntil set,
  deviceId serial,
  colorCode timestamp,
  activeDevices enum,
  email blob,
  comment binary,
  clockOut bit,
  contentType point,
  lastLoginAt float,
  birthDate set,
  businessType mediumint,
  cityName datetime,
  avatar tinyint,
  deletedAt varchar,
  mapId int
);

CREATE TABLE organization_extra (
  id serial primary key,
  city double,
  accountType double,
  meterNumber set,
  dailyLimit smallint,
  departmentCode binary,
  isActive datetime,
  createdAt serial,
  username set,
  clientId bit,
  countryCode tinyint,
  machineId date,
  shippingAddress enum,
  hostName blob,
  levelId date,
  modifiedAt point,
  companyId int,
  enabledAt smallint,
  weight point,
  lastName enum,
  accountStatus date,
  minValue point
);

CREATE TABLE tmpconfig (
  id serial primary key,
  customField1 decimal,
  homePhone blob,
  copyRight decimal,
  memberCount enum,
  ipAddress geometry,
  lockoutEnd text,
  machineId binary,
  totalAmount bit,
  amount set,
  loginAttempts text,
  albumId boolean,
  macAddress bit,
  avatar binary,
  startDate geometry,
  dueDateAt tinyint,
  hiddenAt boolean,
  monthlyRate enum,
  frameRate text,
  contractId set,
  followCount point,
  checkInTime point,
  mimeType tinyint,
  street tinyint,
  instanceId serial,
  department tinyint,
  levelId bit,
  authMethod float
);

CREATE TABLE coreaudit (
  id serial primary key,
  longitude date,
  createdAt boolean,
  contactName set,
  group varchar,
  customerGroup point,
  nickname tinyint,
  agentId text,
  email set,
  audioUrl geometry,
  gameId datetime,
  couponCode tinyint,
  checkInTime varchar,
  size set,
  languageCode datetime,
  maritalStatus text,
  middleName timestamp,
  browserType date,
  deliveryDate text,
  claimId decimal,
  lastLoginAt text,
  hourlyRate real,
  dealerId bigint,
  listId bit,
  moduleId datetime,
  shippingAddress binary
);

CREATE TABLE app_inventory (
  id serial primary key,
  integrationId decimal,
  description mediumint,
  customField2 enum,
  isLocked tinyint,
  endDate int,
  indexKey varchar,
  algorithm datetime,
  insertedAt smallint,
  accessLevel bit,
  employeeId serial,
  phone boolean,
  industryType serial,
  exportId smallint,
  fontSize text,
  type binary
);

CREATE TABLE core_organization_temp (
  id serial primary key,
  gateId geometry,
  metaKeywords binary,
  backupEmail blob,
  filterType tinyint,
  currencyCode point,
  version time,
  hourlyRate mediumint,
  departmentCode enum,
  logLevel geometry,
  customField2 decimal,
  isHidden date,
  orderStatus tinyint,
  invoiceId real,
  clockOut int,
  frameRate int,
  joinDate double,
  awardDate text,
  updatedAt time,
  dependentId timestamp,
  amount serial,
  longitude float,
  errorMessage point,
  creditScore boolean,
  mimeType decimal,
  sessionId point
);

CREATE TABLE transaction_log (
  id serial primary key,
  colorCode enum,
  contactPhone blob,
  courseId point,
  bankAccount datetime,
  merchantId datetime,
  invoiceId geometry,
  languageCode text,
  exportId tinyint,
  addressLine1 bit,
  defaultLang geometry,
  country double
);

CREATE TABLE transaction (
  id serial primary key,
  keywords decimal,
  loginCount real,
  displayOrder binary,
  cardNumber blob,
  indexKey time,
  category varchar,
  businessType bit,
  description point
);

CREATE TABLE dst_payment_div_v1 (
  id serial primary key,
  hostName timestamp,
  algorithm point,
  expiryDate geometry,
  inactiveAt mediumint,
  loginCount tinyint,
  completedAt point,
  salary time,
  sku real,
  lastSeenAt text,
  downloadCount mediumint,
  importId time,
  insuranceId decimal,
  geoLocation blob,
  lastLoginAt bigint,
  deactivatedAt datetime,
  age real
);

CREATE TABLE payment (
  id serial primary key,
  dataSource double,
  title time,
  amount geometry,
  hiddenAt geometry,
  authorId enum,
  coordinateX set,
  instructorId tinyint,
  blogId mediumint,
  cacheKey double,
  rating timestamp,
  firmwareVersion date,
  completionRate decimal,
  validUntil tinyint,
  updatedAt bigint,
  abandonedCartId geometry,
  brandId decimal,
  dialCode binary,
  ipAddress mediumint,
  formatType set,
  departmentCode real,
  accessLevel datetime,
  gateId geometry,
  country smallint,
  uuid date
);

CREATE TABLE tmp_inventory_2025 (
  id serial primary key,
  description set,
  isSystem datetime,
  employeeId smallint,
  facilityId bit,
  modifiedAt serial,
  discount tinyint,
  memberCount bigint,
  state date,
  fileName point,
  accountType float,
  apiVersion enum,
  maxValue tinyint,
  moduleId datetime,
  status date,
  paymentMethod float,
  domainName timestamp,
  filterType tinyint,
  maskType point,
  industryType enum,
  layerId set,
  meterNumber text,
  driverLicense real,
  friendId varchar,
  fontFamily geometry,
  claimId text,
  cvv text,
  id geometry,
  street point,
  salary varchar
);

CREATE TABLE stg_transaction (
  id serial primary key,
  thumbnail varchar,
  fileSize decimal
);

CREATE TABLE fact_audit (
  id serial primary key,
  address text,
  ipAddress decimal,
  feedbackId int,
  flagged int,
  version geometry,
  password bit,
  isDefault int,
  locationId timestamp,
  logLevel bit,
  startDate bigint,
  browserType tinyint
);

CREATE TABLE order_new (
  id serial primary key,
  category varchar,
  browserType tinyint,
  lastLoginAt boolean,
  contractId time,
  faxNumber time,
  clockOut mediumint,
  domainName geometry,
  extractId double,
  distributorId float,
  billingCycle geometry,
  city bit,
  type float,
  comment real,
  signature double,
  cacheKey tinyint,
  height binary,
  childId float,
  metaKeywords point,
  budgetCode mediumint,
  longitude datetime,
  password serial,
  isHidden varchar,
  analyticsId set,
  startDate timestamp
);

CREATE TABLE cpy_config_legacy (
  id serial primary key,
  middleName varchar,
  homePhone serial,
  isBillable int,
  isDeleted int
);

CREATE TABLE pub_product (
  id serial primary key,
  eventDate boolean,
  groupName float,
  shippingAddress time,
  comment time,
  department smallint,
  dimension blob,
  balance datetime
);

CREATE TABLE company (
  id serial primary key,
  jobTitle varchar,
  exportId point,
  headerImage enum,
  messageId decimal,
  token mediumint,
  itemCount mediumint,
  isActive serial,
  dueDateAt double,
  bankAccount binary,
  latitude geometry,
  taxRate mediumint,
  paymentMethod datetime,
  connectionString tinyint,
  uuid bigint,
  id date,
  friendId tinyint,
  updatedAt double,
  couponCode time,
  campaignId float,
  displayOrder text
);

CREATE TABLE inventory_seg (
  id serial primary key,
  facilityId datetime,
  displayOrder point,
  dataSource boolean,
  title time,
  employmentDate bigint,
  frameRate float,
  address set,
  exportId enum,
  moveId mediumint,
  handlerId datetime,
  logLevel point,
  fontFamily varchar,
  value binary,
  id bit,
  driverLicense boolean,
  lockoutEnd tinyint,
  amount double,
  fileHash varchar
);

CREATE TABLE companydata (
  id serial primary key,
  defaultValue timestamp,
  dataSource geometry,
  ipAddress decimal,
  deviceId set,
  courseId int,
  domainName geometry,
  referralCode text,
  monthlyRate boolean,
  creditScore decimal,
  layerId bit,
  feedbackId text,
  errorMessage point,
  managerId datetime,
  deliveryDate enum,
  downloadCount smallint,
  editedAt bit,
  price blob,
  cityName time,
  manufacturerId set,
  authorId geometry,
  isEnabled int,
  feedId blob,
  iconPath tinyint,
  expiryYear date,
  endDate boolean,
  defaultLang smallint,
  email binary,
  dimension tinyint,
  token text
);

CREATE TABLE payment (
  id serial primary key,
  orderId datetime,
  expiryDate point,
  macAddress float,
  albumId real,
  endPoint binary,
  levelId decimal,
  mapId int,
  authMethod bigint,
  tags decimal,
  cloudId double,
  browserType binary,
  contactName datetime,
  deactivatedAt text,
  coordinateY geometry,
  guestId geometry,
  claimId bigint,
  referralCode set,
  analyticsId geometry,
  costCenter real,
  algorithm time,
  hostName datetime,
  orderStatus int,
  budgetCode geometry,
  invoiceId point,
  metadata geometry,
  accountType varchar,
  paymentMethod mediumint
);

CREATE TABLE stg_company (
  id serial primary key,
  errorCode int,
  houseNumber serial,
  cloudId time,
  thumbnail smallint
);

CREATE TABLE inventory (
  id serial primary key,
  coordinateX set,
  floorNumber point,
  folderPath date,
  code serial,
  comment timestamp,
  checkInTime serial,
  clockIn double,
  manufacturerId point,
  isDefault text,
  apiKey geometry,
  adminNotes date,
  linkId double,
  dailyLimit bigint,
  invoiceId binary,
  isActive bigint,
  departmentCode varchar,
  isVerified text,
  endPoint geometry,
  inactiveAt set
);

CREATE TABLE inventory (
  id serial primary key,
  browserType varchar,
  employeeCode int
);

CREATE TABLE record_log (
  id serial primary key,
  updatedAt boolean,
  customField1 double,
  albumId blob,
  street set,
  amount text,
  country point,
  isActive mediumint,
  dependentId bigint,
  loginCount varchar,
  referralCode blob,
  description float
);

CREATE TABLE payment (
  id serial primary key,
  cartId time,
  friendId datetime,
  updatedAt smallint,
  longitude blob,
  favoriteCount smallint,
  endPoint timestamp,
  fontFamily boolean,
  isEnabled geometry,
  sku bit,
  importId blob,
  maskType blob,
  fileType boolean,
  gateId text,
  likeCount point,
  zipCode bigint,
  startDate time,
  appVersion bit,
  size geometry,
  batchId text,
  lockoutEnd int
);

CREATE TABLE cpy_transaction (
  id serial primary key,
  token decimal,
  languageCode bit,
  isRequired point,
  isVerified double,
  homePhone real,
  fontFamily mediumint,
  checkInTime smallint,
  customerGroup real,
  memberCount serial,
  score smallint,
  createdAt varchar,
  title set,
  creditLimit datetime,
  phone datetime,
  maritalStatus smallint,
  expiryDate binary,
  businessType double,
  avatar time,
  expiryMonth point,
  metaDescription blob,
  birthDate smallint,
  chargeId point,
  balance date,
  rating float,
  dialCode enum,
  startDate enum,
  departmentCode int,
  currency bigint,
  completedAt boolean,
  referralCode varchar,
  listId double
);

CREATE TABLE order_type (
  id serial primary key,
  phone time,
  iconPath geometry,
  longitude int,
  globalId enum,
  comment varchar,
  analyticsId varchar,
  addressLine1 varchar,
  enabledAt set,
  foregroundColor set,
  keywords real,
  entryPoint datetime,
  contactName boolean,
  contentType tinyint,
  geoLocation timestamp,
  score datetime,
  country point,
  connectionString decimal,
  blogId real
);

CREATE TABLE stg_transaction (
  id serial primary key,
  expiryDate decimal,
  localeId bit,
  expiryMonth point,
  productCode date,
  houseNumber smallint,
  adminNotes float,
  endDate varchar,
  name text,
  favoriteCount varchar,
  meterNumber serial,
  messageId mediumint,
  incidentId time,
  state binary,
  attachmentUrl bigint,
  completedAt bit,
  authToken date,
  bluetoothId float,
  dataSource boolean,
  actionType binary,
  joinDate boolean,
  addressLine1 int,
  completionRate set,
  departmentCode blob,
  domainName binary,
  referralCode point,
  salary point,
  globalId tinyint,
  isDraft smallint,
  emergencyContact bigint,
  token float,
  cityName set
);

CREATE TABLE core_record (
  id serial primary key,
  couponCode decimal,
  isDeleted time,
  eventDate decimal,
  exchangeRate varchar,
  comment tinyint,
  filterType double,
  dataSource smallint,
  minValue double,
  customField2 set,
  content float,
  budgetCode geometry,
  isAdmin bigint,
  title point,
  agentId mediumint,
  lastSeenAt point,
  dueDateAt bit,
  maxLimit boolean,
  clockOut real,
  deliveryDate point,
  abandonedCartId double,
  houseNumber smallint,
  department real,
  orderId varchar
);

CREATE TABLE payment (
  id serial primary key,
  country binary,
  addressLine1 int,
  longitude float,
  levelId blob,
  coordinateX float,
  isDraft datetime,
  creditLimit bit,
  gateId serial,
  group serial,
  updatedAt blob,
  avatar bigint,
  cloudId real,
  comment decimal,
  createdAt date,
  clientId bit,
  accessLevel timestamp,
  headerImage decimal,
  extractId geometry,
  cartId bigint,
  signature decimal,
  adminNotes int,
  timezone date,
  dailyLimit date,
  isFeatured serial,
  appVersion datetime,
  deviceType timestamp,
  inactiveAt mediumint,
  brandId set,
  discountCode float
);

CREATE TABLE fact_account (
  id serial primary key,
  contractId date,
  uuid datetime,
  creditLimit set,
  cacheKey serial,
  priority real,
  copyRight date,
  accessLevel smallint,
  gender blob,
  salary smallint,
  education datetime,
  completionRate binary,
  department time,
  errorMessage smallint,
  moveId tinyint,
  hourlyRate timestamp,
  isSystem decimal,
  contactName varchar,
  status int,
  mapId float,
  exchangeRate binary
);

CREATE TABLE company (
  id serial primary key,
  middleName smallint,
  height double,
  managerId serial,
  filterType blob,
  totalAmount double
);

CREATE TABLE audit (
  id serial primary key,
  attachmentUrl mediumint,
  guestId point,
  employmentDate tinyint,
  thumbnail binary,
  cancelReason float,
  invoiceId smallint,
  department text,
  loginAttempts text
);

CREATE TABLE organization (
  id serial primary key,
  analyticsId bit,
  minValue mediumint
);

CREATE TABLE coreaccount (
  id serial primary key,
  latitude float,
  dataSource smallint,
  apiKey geometry,
  totalAmount float,
  isArchived smallint,
  contactPhone blob,
  accountType varchar,
  fontSize float
);

CREATE TABLE inventory_type (
  id serial primary key,
  isLocked float,
  contactEmail bigint,
  loadTime int,
  isRequired blob,
  id date,
  deactivatedAt bit,
  token bigint,
  couponCode int,
  isHidden binary,
  value mediumint,
  deliveryDate enum,
  isDeleted int,
  deletedAt datetime,
  integrationId set,
  copyRight text,
  appVersion float,
  accessLevel timestamp,
  audioUrl point,
  size decimal,
  menuId time,
  distributorId bigint,
  fileSize datetime,
  houseNumber boolean,
  state float,
  companyLogo datetime,
  driverLicense bigint,
  bookingDate timestamp
);

CREATE TABLE srcorder (
  id serial primary key,
  shippingAddress tinyint,
  taxRate varchar
);

CREATE TABLE inventorylog (
  id serial primary key,
  iconPath date,
  coverImage point,
  incidentId bigint,
  companyLogo bit,
  displayOrder varchar,
  avatar point,
  hourlyRate decimal,
  expiryYear mediumint,
  metaTitle serial,
  colorCode enum,
  algorithm enum,
  contactPhone double,
  totalAmount float,
  fontSize varchar,
  createdAt bigint,
  balance serial,
  editedAt binary,
  currencyCode float,
  forwardTo mediumint,
  coordinateX binary,
  contactEmail time,
  authorId double
);

CREATE TABLE olkaccount (
  id serial primary key,
  token timestamp,
  managerId varchar,
  backupEmail date,
  attemptCount timestamp,
  employmentDate int,
  licenseKey time,
  firstName mediumint,
  score bigint,
  ipAddress real,
  metaDescription date,
  status boolean,
  title tinyint,
  countryCode point,
  machineId int,
  bluetoothId smallint,
  phone time,
  customField2 smallint,
  unit time,
  monthlyRate blob,
  contactName binary,
  longitude text,
  avatar smallint,
  authMethod date,
  creditLimit decimal,
  channelId bigint,
  childId enum,
  dueDateAt double
);

CREATE TABLE verrecord (
  id serial primary key,
  amount int,
  name int,
  budgetCode date,
  password real,
  validUntil date,
  timezone bit,
  isActive double,
  indexKey int,
  levelId double,
  campaignId datetime,
  claimId float,
  authorId boolean,
  checkInTime int,
  totalAmount text,
  avatar bigint,
  birthDate real,
  labelText float,
  productCode datetime,
  meterNumber int,
  isArchived text,
  maritalStatus enum
);

CREATE TABLE inventory (
  id serial primary key,
  accountType timestamp,
  configId serial,
  lastLoginAt tinyint,
  name binary,
  exportId bigint,
  phone real,
  childId date,
  coverImage bigint,
  faxNumber bigint,
  nickname text,
  mobileNumber tinyint,
  addressLine1 smallint,
  customField1 int,
  fontFamily enum,
  backupEmail bit,
  locationId int,
  maskType text,
  instanceId blob,
  clientId float,
  distributorId set,
  authorId datetime,
  rating decimal,
  isDefault decimal,
  state enum,
  category varchar,
  deactivatedAt time,
  audioUrl boolean,
  dailyLimit binary
);

CREATE TABLE order_archive (
  id serial primary key,
  alertType binary,
  isAdmin time,
  longitude smallint,
  monthlyRate tinyint,
  height timestamp,
  weight bit,
  isDefault double,
  rating varchar,
  sessionId timestamp,
  id int,
  addressLine2 blob,
  bluetoothId enum,
  status text,
  checkOutTime blob,
  managerId set,
  contactName double,
  lastSeenAt bigint,
  moduleId int
);

CREATE TABLE transactionmap (
  id serial primary key,
  invoiceId serial,
  contactPhone float,
  price geometry,
  claimId binary,
  brandId int,
  longitude smallint,
  distributorId set,
  moduleId timestamp,
  billingCycle set
);

