CREATE TABLE core_organization_div_v1 (
  id serial primary key,
  employeeCode binary,
  marketId real,
  loginAttempts enum,
  exportId smallint,
  buildNumber time,
  logLevel binary
);

CREATE TABLE rel_inventory_hist_new (
  id serial primary key,
  locationId double,
  certificateId real,
  moduleId decimal,
  checkOutTime point,
  backupEmail double,
  expiryYear blob,
  layerId binary,
  inactiveAt bigint,
  mobileNumber geometry,
  id blob,
  uuid geometry,
  companyId bit,
  firmwareVersion blob,
  chargeId text,
  gameId decimal,
  budgetCode set,
  cacheKey int,
  email date,
  fileType mediumint
);

CREATE TABLE vworganization (
  id serial primary key,
  articleId double,
  createdAt datetime,
  managerId timestamp,
  claimId time,
  type text,
  isAdmin mediumint,
  levelId text,
  companyId geometry,
  dimension datetime,
  address real,
  completedAt datetime,
  cityName decimal,
  floorNumber float,
  deactivatedAt varchar,
  abandonedCartId float,
  displayOrder boolean,
  groupName set,
  awardDate double,
  billingCycle float,
  hashKey tinyint,
  fingerprint date,
  content smallint,
  cloudId bit,
  instanceId datetime,
  invoiceId blob,
  downloadCount float,
  isBillable mediumint,
  exportId datetime,
  deviceType date,
  dependentId binary
);

CREATE TABLE pub_company (
  id serial primary key,
  url text,
  messageId text,
  isEnabled blob,
  frameRate float,
  contactName set,
  isLocked boolean,
  certificateId set,
  category text,
  accountType bit,
  token tinyint,
  password text,
  value bit,
  geoLocation varchar,
  gameId time,
  moduleId binary
);

CREATE TABLE config (
  id serial primary key,
  name binary,
  contractId set,
  avatar point,
  companyLogo int,
  filterType real,
  enabledAt smallint,
  apiKey float
);

CREATE TABLE dim_customer (
  id serial primary key,
  moveId time,
  deviceId timestamp,
  displayName text,
  accountType blob,
  name boolean,
  addressLine2 real,
  email geometry,
  incidentId tinyint,
  articleId timestamp,
  actionType tinyint
);

CREATE TABLE record (
  id serial primary key,
  title int,
  companyName varchar,
  iconPath blob,
  postalCode boolean,
  exportId time,
  endPoint time,
  fontSize serial,
  entityId serial,
  chargeId int,
  status decimal
);

CREATE TABLE agg_audit (
  id serial primary key,
  balance binary,
  signature decimal,
  employeeId serial,
  comment tinyint,
  distributorId blob,
  cacheKey set,
  cloudId float,
  address bit,
  type date,
  title bit,
  countryCode blob,
  contentType binary,
  isFeatured smallint,
  exportId boolean,
  amount blob
);

CREATE TABLE config (
  id serial primary key,
  address smallint,
  timezone double,
  url text,
  hiddenAt boolean,
  title datetime,
  alertType varchar,
  longitude text,
  firmwareVersion smallint,
  activeDevices real,
  gateId float,
  metadata binary,
  totalAmount enum,
  browserType boolean,
  memberCount double,
  score tinyint
);

CREATE TABLE dstcompany (
  id serial primary key,
  metadata time,
  longitude smallint,
  isDraft datetime,
  cartId double,
  cacheKey varchar,
  integrationId geometry,
  lastName mediumint,
  discountCode boolean,
  depositAmount tinyint,
  loadTime set,
  foregroundColor serial,
  isBillable date
);

CREATE TABLE payment_hist (
  id serial primary key,
  logLevel decimal,
  fontFamily binary,
  contractId point
);

CREATE TABLE inventory_meta (
  id serial primary key,
  ipAddress blob,
  earnedPoints time,
  lastLoginAt geometry,
  joinDate set,
  contactName timestamp,
  displayOrder float,
  name real
);

CREATE TABLE record (
  id serial primary key,
  logLevel point,
  adminNotes text,
  checkInTime time,
  accountStatus binary,
  loginAttempts timestamp,
  shippingAddress decimal,
  metadata timestamp,
  expiryMonth datetime,
  cacheKey blob,
  age time,
  role timestamp,
  hourlyRate tinyint,
  comment boolean,
  dimension set,
  bookingDate point,
  accessLevel date,
  category int,
  actionType binary,
  isLocked bigint,
  priority geometry,
  street tinyint,
  customField2 tinyint,
  deactivatedAt datetime,
  firmwareVersion point,
  isEnabled int,
  maritalStatus double,
  importId serial,
  defaultValue datetime,
  isPublic timestamp
);

CREATE TABLE transactionnew (
  id serial primary key,
  totalAmount binary,
  grade time,
  gender datetime,
  maxValue binary,
  manufacturerId mediumint,
  minLimit time,
  postalCode time,
  apiVersion enum,
  unit enum,
  currencyCode float,
  group point,
  isVerified real,
  mimeType mediumint
);

CREATE TABLE audit (
  id serial primary key,
  analyticsId boolean,
  avatar datetime,
  addressLine2 real,
  email date,
  ipAddress geometry,
  mainImage set,
  contentType double,
  password text,
  alertType blob,
  amount time,
  apiKey geometry,
  distributorId boolean,
  taxRate mediumint,
  cardNumber boolean,
  customField1 blob,
  accountNumber date
);

CREATE TABLE priv_product (
  id serial primary key,
  isSystem smallint,
  referralCode int,
  deviceType time,
  productCode bigint,
  forwardTo bit,
  accountNumber real,
  dueDateAt set,
  comment real,
  updatedAt blob,
  score serial,
  middleName blob,
  loginAttempts point,
  meterNumber float,
  grade smallint,
  lockoutEnd bit
);

CREATE TABLE customer (
  id serial primary key,
  isArchived bigint,
  customerGroup timestamp,
  role bigint,
  algorithm varchar,
  amount bigint,
  accessLevel point,
  languageCode tinyint,
  apiKey geometry,
  phone tinyint,
  contactEmail date,
  uuid bit,
  logLevel bit,
  copyRight tinyint,
  displayOrder boolean,
  downloadCount float,
  dueDateAt serial,
  email double,
  isSystem point,
  code tinyint,
  lastSeenAt decimal,
  referralCode double,
  password int,
  maskType real,
  enabledAt mediumint,
  insuranceId bit,
  businessType binary,
  lastName binary,
  actionType datetime,
  formatType datetime,
  hostName float,
  flagged bigint
);

CREATE TABLE audit (
  id serial primary key,
  accountNumber real,
  adminNotes bit,
  companyName int,
  isDeleted blob,
  tags text,
  zipCode float
);

CREATE TABLE configout2024 (
  id serial primary key,
  checkOutTime blob,
  metadata text,
  deviceId boolean,
  dependentId date
);

CREATE TABLE organization (
  id serial primary key,
  manufacturerId double,
  email decimal,
  bannerImage set,
  levelId bit,
  code set,
  apiKey real,
  entityId set,
  couponCode set,
  exportId tinyint,
  industryType int,
  totalAmount float,
  dashboardId tinyint,
  formatType bit,
  deletedAt time,
  itemCount bit,
  creditLimit time,
  cancelReason bit,
  billingCycle binary,
  phone text,
  deviceToken boolean,
  albumId int,
  category double,
  businessType blob,
  clockOut tinyint,
  zipCode decimal,
  emailStatus varchar,
  alertType double,
  lastSeenAt date,
  isFeatured timestamp,
  ipAddress set,
  title real
);

CREATE TABLE record_temp (
  id serial primary key,
  extractId boolean,
  isPublic blob,
  isAdmin decimal,
  localeId bigint,
  fingerprint date,
  itemCount text,
  lastSeenAt int,
  maritalStatus real,
  gender tinyint,
  avatar smallint,
  birthDate timestamp,
  completedAt smallint,
  couponCode decimal,
  cityName point,
  likeCount boolean,
  floorNumber point,
  cacheKey decimal,
  manufacturerId varchar,
  documentId datetime,
  middleName mediumint,
  deactivatedAt mediumint,
  analyticsId decimal,
  city int,
  discountCode point,
  phone real,
  createdAt binary,
  actionType set,
  followCount binary
);

CREATE TABLE config (
  id serial primary key,
  totalAmount blob,
  earnedPoints time,
  maritalStatus boolean,
  adminNotes decimal,
  attachmentUrl int,
  maxValue tinyint,
  comment datetime,
  orderId varchar,
  price boolean,
  displayOrder datetime,
  clientId serial,
  loginCount serial,
  cloudId int,
  claimId text,
  locationId bit,
  distributorId varchar,
  accountType binary,
  department date,
  shippingAddress time,
  invoiceId serial,
  accountNumber binary
);

CREATE TABLE record (
  id serial primary key,
  quantity time,
  fromDate decimal,
  fontSize date,
  emailStatus binary,
  amount decimal,
  nickname set,
  managerId date,
  creditScore bigint,
  budgetCode time,
  instructorId decimal,
  status timestamp
);

CREATE TABLE account (
  id serial primary key,
  startDate geometry,
  fileName geometry,
  instructorId tinyint,
  comment real,
  password blob,
  maritalStatus datetime
);

CREATE TABLE record (
  id serial primary key,
  mobileNumber binary,
  bookingDate tinyint,
  id point,
  fontFamily blob,
  zipCode varchar,
  mainImage set,
  chatId bit,
  token binary,
  analyticsId time,
  name enum,
  dashboardId binary,
  employeeCode bigint,
  abandonedCartId real
);

CREATE TABLE refrecordsegv2 (
  id serial primary key,
  isEnabled serial,
  deactivatedAt geometry,
  birthDate datetime,
  shippingAddress set,
  title serial,
  sessionId bigint,
  analyticsId tinyint,
  distributorId datetime,
  articleId tinyint,
  accountNumber blob,
  claimId binary,
  lastLoginAt time,
  algorithm boolean,
  thumbnail int,
  cardNumber enum,
  gender time,
  defaultLang text,
  feedId boolean,
  folderPath float,
  category bigint
);

CREATE TABLE dim_payment (
  id serial primary key,
  algorithm decimal,
  ipAddress int,
  discount bigint,
  linkId boolean,
  education datetime,
  campaignId set,
  accessLevel serial,
  state enum,
  firmwareVersion varchar,
  grade binary,
  dependentId date
);

CREATE TABLE product_div (
  id serial primary key,
  monthlyRate point,
  actionType binary,
  machineId enum,
  employeeCode tinyint,
  referralCode date,
  metadata text,
  facilityId float,
  exportId blob,
  formatType float,
  indexKey bigint,
  zipCode point,
  employeeId bigint,
  fileName timestamp,
  companyLogo set,
  updatedAt varchar,
  defaultValue bit,
  birthDate double,
  groupName real,
  favoriteCount date,
  articleId geometry,
  depositAmount binary,
  status datetime
);

CREATE TABLE corerecordnew (
  id serial primary key,
  creditLimit blob,
  nickname tinyint,
  bankAccount tinyint,
  integrationId date,
  addressLine1 float,
  currencyCode int,
  apiKey int,
  authorId varchar,
  batchId double,
  keyId enum,
  enrollmentDate float,
  fingerprint mediumint,
  birthDate blob,
  expiryDate binary,
  value set,
  uuid enum,
  billingCycle datetime,
  houseNumber int
);

CREATE TABLE config_map (
  id serial primary key,
  zipCode point,
  keyId mediumint,
  shippingAddress datetime,
  clockOut blob,
  importId int,
  feedId time,
  dueDateAt datetime,
  street int,
  emergencyContact real,
  locationId decimal,
  feedbackId boolean,
  friendId bigint,
  postalCode serial,
  name smallint,
  defaultLang set,
  education set,
  cacheKey enum,
  fromDate serial,
  emailStatus binary,
  endDate set
);

CREATE TABLE pub_organization (
  id serial primary key,
  bankAccount real,
  messageId float,
  courseId time,
  fileName double,
  labelText bigint,
  couponCode float,
  formatType float,
  type enum,
  businessType enum,
  price boolean,
  joinDate point,
  instructorId float,
  levelId date,
  favoriteCount enum,
  keywords point,
  zipCode double,
  coordinateX set,
  facilityId date,
  contactName point
);

CREATE TABLE orderseg (
  id serial primary key,
  avatar timestamp,
  productCode text,
  audioUrl geometry,
  updatedAt geometry,
  endDate real,
  companyId bigint,
  adminNotes blob,
  referralCode datetime,
  moveId double,
  labelText point,
  isSystem binary,
  lastLoginAt time,
  analyticsId int,
  coordinateX date
);

CREATE TABLE product (
  id serial primary key,
  clockOut boolean,
  isDeleted bigint,
  phone boolean,
  addressLine1 decimal,
  businessType decimal,
  authMethod boolean,
  fromDate serial,
  age binary,
  analyticsId double,
  chatId tinyint,
  accountStatus mediumint,
  keywords varchar,
  enabledAt double,
  email bit,
  alertType blob,
  sku int,
  weight decimal,
  modifiedAt timestamp,
  adminNotes date,
  activeDevices real,
  employeeCode datetime,
  backupEmail bigint,
  managerId point,
  fileSize time
);

CREATE TABLE tbl_transaction (
  id serial primary key,
  createdAt geometry,
  listId tinyint,
  machineId int,
  algorithm date,
  sessionId mediumint,
  balance point,
  linkId point,
  countryCode serial,
  licenseKey serial,
  dateFormat decimal
);

CREATE TABLE rel_config (
  id serial primary key,
  cloudId bigint,
  contactPhone tinyint,
  manufacturerId date,
  lockoutEnd float,
  locationId boolean,
  isVerified date,
  taxRate serial,
  unit smallint,
  address real,
  value serial,
  timezone datetime,
  isDefault double,
  groupName binary,
  comment blob,
  birthDate datetime,
  childId boolean,
  isDeleted timestamp
);

CREATE TABLE rel_product_div (
  id serial primary key,
  role float,
  status text,
  brandId serial,
  forwardTo serial,
  companyId time,
  completedAt geometry,
  validUntil set,
  errorMessage decimal,
  configId int,
  activeDevices serial,
  ipAddress datetime,
  clockOut timestamp,
  machineId double,
  size point,
  address double,
  updatedAt point,
  dashboardId point,
  iconPath double,
  group set,
  displayOrder bigint,
  filterType date,
  emergencyContact date,
  currency tinyint
);

CREATE TABLE ext_audit_new (
  id serial primary key,
  cardNumber double,
  feedId datetime,
  minValue double,
  licenseKey bigint,
  depositAmount decimal,
  accountType datetime,
  configId bit,
  connectionString float,
  token bigint,
  filterType bigint,
  colorCode tinyint
);

CREATE TABLE sys_order (
  id serial primary key,
  role datetime,
  validUntil point,
  group blob,
  algorithm boolean,
  isBillable date,
  discount blob,
  gameId int,
  batchId timestamp,
  state datetime,
  folderPath double,
  appVersion bigint,
  fontFamily enum,
  certificateId varchar,
  lockoutEnd text,
  accountType blob,
  id mediumint,
  driverLicense varchar,
  score int,
  audioUrl text,
  grade date,
  orderStatus tinyint,
  avatar set
);

CREATE TABLE priv_account_temp (
  id serial primary key,
  colorCode mediumint,
  companyId binary,
  cvv set,
  dataSource point,
  couponCode timestamp,
  name datetime,
  fileHash time,
  accessLevel enum,
  endDate tinyint,
  customField1 real,
  cardNumber varchar,
  password bigint,
  customerGroup real,
  isDraft mediumint,
  birthDate text,
  age decimal,
  phone boolean,
  balance tinyint,
  dialCode varchar,
  lastName blob,
  locationId text,
  cartId text,
  nickname boolean,
  levelId binary
);

CREATE TABLE inventory (
  id serial primary key,
  insuranceId text,
  earnedPoints datetime,
  dueDateAt mediumint,
  exchangeRate text,
  grade int,
  validUntil set,
  locationId tinyint,
  creditScore bigint,
  clientId varchar,
  email double,
  content real,
  fontSize float,
  id varchar,
  isVerified mediumint,
  latitude serial,
  expiryMonth serial,
  score decimal,
  comment decimal,
  channelId bigint,
  isDeleted real,
  price boolean,
  clockIn double,
  state bit,
  deviceId real,
  value serial,
  machineId enum,
  attachmentUrl boolean,
  status geometry
);

CREATE TABLE dim_organization_map (
  id serial primary key,
  dealerId float,
  likeCount tinyint,
  timezone set,
  contractId text
);

CREATE TABLE relorganizationrellegacy (
  id serial primary key,
  contactPhone bigint,
  height set,
  createdAt mediumint,
  instructorId varchar,
  earnedPoints bigint,
  globalId double,
  entryPoint tinyint,
  childId serial,
  headerImage varchar,
  sessionId int,
  addressLine1 boolean,
  weight double,
  extractId bit,
  contractId set,
  token varchar,
  version blob,
  defaultValue set,
  channelId enum,
  name blob
);

CREATE TABLE rel_record_2025 (
  id serial primary key,
  folderPath decimal,
  code binary,
  phone varchar,
  fingerprint decimal,
  metaKeywords double
);

CREATE TABLE srcproduct (
  id serial primary key,
  email boolean,
  accessLevel binary,
  completedAt decimal,
  expiryMonth int,
  isBillable mediumint,
  discountCode serial,
  creditLimit datetime,
  contactPhone bigint,
  industryType bigint,
  forwardTo serial,
  connectionString varchar,
  ipAddress int,
  facilityId serial,
  category serial,
  extractId point,
  faxNumber timestamp,
  password double,
  exportId serial,
  customField2 boolean,
  batchId datetime,
  addressLine2 point,
  abandonedCartId blob,
  integrationId set,
  maxLimit blob,
  authToken geometry,
  frameRate geometry,
  homePhone mediumint,
  fontFamily point,
  locationId float,
  role int
);

CREATE TABLE account_extra (
  id serial primary key,
  memberCount varchar,
  feedbackId real,
  price date
);

CREATE TABLE dst_config_div (
  id serial primary key,
  faxNumber double,
  minValue binary,
  isPublic datetime,
  maskType enum,
  minLimit geometry,
  monthlyRate int,
  departmentCode serial,
  createdAt datetime,
  rating geometry,
  fileSize timestamp,
  algorithm binary,
  groupName binary,
  agentId varchar,
  contactName blob,
  expiryMonth float,
  houseNumber binary,
  duration binary,
  analyticsId serial,
  isEnabled double,
  group decimal,
  joinDate smallint,
  isLocked geometry,
  headerImage decimal,
  actionType enum,
  emailStatus point
);

CREATE TABLE audit (
  id serial primary key,
  houseNumber text,
  isHidden smallint,
  id double,
  industryType smallint,
  fromDate serial,
  group mediumint,
  isDefault point,
  errorMessage bigint,
  currencyCode timestamp,
  machineId int,
  clockOut varchar,
  enabledAt geometry,
  followCount point,
  listId timestamp,
  thumbnail timestamp,
  contactPhone text,
  category blob,
  minLimit blob,
  maritalStatus mediumint,
  isFeatured point,
  coverImage smallint,
  adminNotes geometry,
  deletedAt bigint,
  expiryYear point,
  zipCode int,
  feedbackId set,
  dailyLimit binary,
  mobileNumber blob,
  balance geometry,
  customField1 varchar
);

CREATE TABLE record_v1 (
  id serial primary key,
  customField1 text,
  distributorId double,
  attemptCount mediumint,
  enabledAt int,
  url set,
  deletedAt geometry,
  modifiedAt real,
  isDeleted enum,
  updatedAt text
);

CREATE TABLE transaction (
  id serial primary key,
  accountNumber bigint,
  url set,
  thumbnail serial,
  headerImage double,
  enrollmentDate real,
  depositAmount set,
  alertType real,
  extractId double,
  logLevel enum,
  modifiedAt float,
  contentType boolean,
  fontSize timestamp
);

CREATE TABLE pub_inventory_seg_legacy (
  id serial primary key,
  invoiceId enum,
  courseId text,
  entityId date,
  mobileNumber serial,
  accessLevel set,
  cvv varchar,
  isActive text,
  joinDate serial,
  machineId date,
  billingFrequency enum,
  appVersion time,
  timezone time,
  distributorId geometry,
  listId date,
  discountCode boolean,
  productCode mediumint,
  displayName int,
  agentId smallint,
  sku enum,
  phone geometry,
  dealerId double,
  hourlyRate bit,
  category enum,
  metaDescription real,
  monthlyRate real,
  isArchived bigint,
  unit set,
  middleName point
);

