CREATE TABLE record (
  id serial primary key,
  emergencyContact smallint,
  lastSeenAt serial,
  enabledAt smallint,
  filterType smallint,
  uuid bit,
  lastLoginAt blob,
  attachmentUrl date,
  authMethod timestamp,
  age mediumint,
  formatType float,
  errorMessage bit
);

CREATE TABLE ext_product (
  id serial primary key,
  channelId float,
  contactPhone binary,
  inactiveAt real,
  country decimal,
  taxRate varchar,
  customerId tinyint,
  moveId blob,
  accessLevel boolean,
  maxValue set,
  address smallint,
  backupEmail boolean
);

CREATE TABLE vw_inventory (
  id serial primary key,
  costCenter bit,
  expiryDate mediumint,
  token boolean,
  claimId tinyint,
  employeeCode boolean,
  duration smallint,
  adminNotes blob,
  dependentId datetime,
  courseId binary,
  contactName real,
  updatedAt varchar,
  activeDevices real,
  attemptCount boolean,
  messageId enum,
  currencyCode text,
  city serial,
  faxNumber timestamp,
  homePhone tinyint,
  createdAt double,
  fileType bigint,
  moveId time,
  checkInTime int,
  isActive decimal,
  coverImage tinyint
);

CREATE TABLE olk_record (
  id serial primary key,
  isFeatured boolean,
  articleId enum,
  jobTitle time,
  comment tinyint,
  group bigint,
  url binary,
  folderPath timestamp,
  exchangeRate binary,
  category enum,
  unit tinyint,
  name tinyint,
  education enum,
  houseNumber real,
  deliveryDate date,
  expiryDate int,
  loadTime bigint,
  currencyCode blob,
  enabledAt blob,
  avatar smallint
);

CREATE TABLE recordtemp (
  id serial primary key,
  accountNumber binary,
  driverLicense boolean,
  amount enum,
  category smallint,
  addressLine2 binary,
  lastLoginAt blob,
  friendId serial,
  content text,
  joinDate bit,
  checkInTime decimal,
  exchangeRate serial,
  birthDate point,
  longitude binary,
  incidentId float,
  countryCode decimal,
  budgetCode bit,
  maxLimit serial,
  password int,
  customerId geometry,
  firmwareVersion blob,
  defaultLang bit
);

CREATE TABLE sys_account (
  id serial primary key,
  depositAmount set,
  campaignId boolean,
  meterNumber enum,
  birthDate geometry,
  customerId decimal,
  accountType real,
  age set
);

CREATE TABLE app_order (
  id serial primary key,
  amount float,
  entityId bit,
  bankAccount int,
  audioUrl int,
  exportId smallint,
  minValue double,
  version date,
  phone point,
  cvv real,
  deviceId decimal,
  content text,
  token blob,
  comment tinyint,
  activeDevices bit,
  orderStatus mediumint,
  loginAttempts point,
  fingerprint date,
  timezone point,
  incidentId decimal
);

CREATE TABLE tmp_organization (
  id serial primary key,
  category varchar,
  displayOrder double,
  maxLimit boolean,
  feedbackId bigint,
  currencyCode date,
  shippingAddress int,
  layerId real,
  referralCode float,
  backupEmail point,
  quantity timestamp,
  customerId datetime,
  cvv real,
  departmentCode serial,
  depositAmount decimal,
  forwardTo double
);

CREATE TABLE agg_order_div_temp (
  id serial primary key,
  moveId float,
  currency timestamp,
  phone mediumint,
  flagged real,
  timezone binary,
  metaKeywords date,
  code geometry,
  cvv enum,
  description bit,
  isBillable date,
  employeeCode bit,
  creditLimit mediumint,
  mapId time,
  hostName geometry,
  hourlyRate geometry,
  articleId bit,
  dealerId decimal,
  token bigint,
  isHidden smallint,
  uuid float,
  expiryDate enum
);

CREATE TABLE dim_account (
  id serial primary key,
  timezone double,
  invoiceId mediumint,
  algorithm blob,
  billingFrequency varchar,
  houseNumber decimal,
  merchantId tinyint,
  fileHash date,
  email bigint,
  mapId tinyint,
  totalAmount serial,
  clientId boolean,
  friendId smallint,
  coverImage int,
  billingCycle tinyint,
  age datetime,
  nickname varchar,
  lastSeenAt boolean,
  entityId varchar,
  isActive decimal,
  checkInTime decimal,
  itemCount bit,
  feedId boolean,
  expiryDate mediumint,
  coordinateX point,
  distributorId boolean,
  orderStatus mediumint,
  phone int,
  isVerified timestamp,
  hiddenAt binary,
  fileSize mediumint
);

CREATE TABLE account_2024 (
  id serial primary key,
  billingFrequency date,
  menuId geometry,
  iconPath serial,
  itemCount geometry,
  isHidden boolean,
  name geometry,
  bankAccount timestamp,
  dateFormat double,
  discount float,
  education geometry,
  companyName set,
  earnedPoints bigint,
  apiKey bigint,
  isSystem blob,
  deviceId int,
  attachmentUrl point,
  category int,
  isLocked time,
  expiryYear mediumint,
  frameRate int,
  campaignId real,
  amount blob,
  emergencyContact boolean,
  chatId datetime,
  longitude boolean,
  folderPath mediumint,
  feedId bigint,
  connectionString smallint
);

CREATE TABLE olkorganizationlegacy (
  id serial primary key,
  folderPath point,
  value enum,
  token binary,
  linkId double,
  manufacturerId int,
  sessionId point,
  marketId time,
  isActive timestamp,
  fileName bigint,
  gender datetime,
  isSystem decimal,
  downloadCount bigint,
  isHidden smallint,
  faxNumber serial,
  metaTitle decimal,
  updatedAt smallint,
  sku set,
  deletedAt int,
  amount binary,
  department bit
);

CREATE TABLE olktransactionv2 (
  id serial primary key,
  articleId int,
  guestId point,
  taxRate bit,
  algorithm point,
  customField2 date,
  employeeId time,
  birthDate date,
  code text,
  instructorId text,
  incidentId float,
  maxLimit set
);

CREATE TABLE relrecord (
  id serial primary key,
  isRequired blob,
  modifiedAt time,
  maskType geometry,
  billingFrequency int
);

CREATE TABLE dst_user_type (
  id serial primary key,
  deletedAt set,
  ipAddress bigint,
  dependentId time,
  iconPath binary,
  isDraft smallint,
  completionRate datetime,
  fileType tinyint,
  followCount point,
  listId enum,
  apiVersion time,
  insuranceId bit,
  expiryMonth bigint,
  maritalStatus binary,
  contractId timestamp,
  creditCard datetime,
  memberCount tinyint,
  sku enum,
  unit smallint,
  displayName real,
  countryCode varchar,
  hourlyRate set,
  rating time,
  expiryYear tinyint,
  cvv serial,
  isAdmin varchar,
  domainName real,
  manufacturerId date,
  industryType tinyint,
  deviceType tinyint,
  dueDateAt point,
  defaultValue point
);

CREATE TABLE log_record_legacy (
  id serial primary key,
  address bigint,
  certificateId double,
  dataSource float,
  appVersion mediumint
);

CREATE TABLE company_rel_2024 (
  id serial primary key,
  isDefault double,
  longitude point,
  id smallint,
  zipCode serial,
  completedAt blob,
  fingerprint mediumint,
  geoLocation smallint,
  isDraft date,
  isVerified enum,
  lastLoginAt blob,
  amount boolean,
  groupName int,
  avatar timestamp,
  mobileNumber datetime,
  listId bit,
  dateFormat varchar,
  token boolean,
  deliveryDate smallint,
  accountStatus decimal,
  isArchived real,
  forwardTo geometry,
  guestId blob,
  updatedAt time,
  metaTitle varchar,
  emergencyContact time,
  cacheKey blob,
  username smallint,
  localeId real,
  isSystem real,
  filterType timestamp,
  isPublic date
);

CREATE TABLE config (
  id serial primary key,
  productCode bigint,
  expiryMonth decimal,
  audioUrl bigint,
  lastLoginAt time,
  postalCode double,
  username float,
  levelId int,
  coordinateX serial,
  completedAt mediumint,
  abandonedCartId set,
  downloadCount binary,
  category enum,
  dataSource serial,
  frameRate time,
  education enum,
  claimId float,
  metaTitle varchar,
  invoiceId varchar,
  messageId double,
  longitude text,
  status serial,
  gender tinyint,
  guestId tinyint,
  handlerId blob,
  title real,
  loginAttempts text,
  alertType point
);

CREATE TABLE payment_div (
  id serial primary key,
  shippingAddress timestamp,
  managerId datetime,
  importId geometry,
  keywords tinyint,
  geoLocation binary,
  deviceToken bit,
  email time,
  token enum,
  marketId point,
  cancelReason mediumint,
  age binary,
  customField1 point,
  url tinyint,
  globalId set,
  displayOrder text,
  price date,
  bookingDate mediumint,
  content boolean,
  buildNumber varchar
);

CREATE TABLE verpayment (
  id serial primary key,
  isBillable set,
  machineId float,
  browserType serial,
  amount date,
  fingerprint decimal,
  firmwareVersion int,
  alertType binary,
  token datetime,
  creditCard set,
  dimension timestamp,
  id serial,
  locationId text,
  configId boolean,
  thumbnail real,
  earnedPoints datetime,
  score timestamp,
  updatedAt blob,
  education point,
  actionType binary,
  clockOut time,
  orderStatus binary,
  customerId tinyint,
  depositAmount mediumint,
  birthDate varchar,
  feedId point,
  endDate serial,
  monthlyRate date,
  logLevel mediumint
);

CREATE TABLE inventory (
  id serial primary key,
  lockoutEnd serial,
  attemptCount blob,
  comment bit,
  entityId geometry,
  checkInTime double,
  guestId binary,
  username time,
  longitude enum,
  linkId time,
  deliveryDate bigint,
  accessLevel tinyint
);

CREATE TABLE dst_customer (
  id serial primary key,
  postalCode boolean,
  category tinyint,
  itemCount blob,
  feedId serial,
  attemptCount binary,
  isRequired binary,
  minValue datetime,
  industryType smallint,
  couponCode double,
  abandonedCartId geometry,
  hashKey boolean,
  url mediumint,
  isDefault time,
  customField2 bigint,
  keyId text,
  comment tinyint,
  phone decimal,
  code binary,
  cancelReason set,
  driverLicense boolean,
  billingCycle time,
  fingerprint blob,
  meterNumber date,
  maritalStatus set,
  coverImage smallint,
  defaultValue mediumint,
  title datetime
);

CREATE TABLE customer_rel (
  id serial primary key,
  thumbnail smallint,
  businessType binary,
  education enum,
  ipAddress time,
  accountType time,
  unit smallint,
  dashboardId decimal,
  address blob,
  id set,
  avatar double,
  cardHolder tinyint,
  itemCount blob,
  createdAt text,
  coordinateX enum,
  jobTitle float,
  apiVersion text,
  customField2 date,
  authMethod binary,
  invoiceId decimal,
  clockOut boolean
);

CREATE TABLE rel_company (
  id serial primary key,
  birthDate enum,
  languageCode double,
  displayOrder real,
  accountNumber geometry,
  loginCount geometry,
  copyRight int,
  dateFormat point,
  lastSeenAt mediumint,
  salary decimal,
  itemCount smallint,
  isActive mediumint,
  connectionString datetime,
  username enum,
  contactName serial,
  zipCode point,
  addressLine2 date,
  eventDate set,
  weight tinyint,
  password datetime,
  priority bigint,
  amount enum,
  customerId binary,
  paymentMethod decimal,
  group datetime,
  version time,
  completedAt decimal,
  merchantId tinyint,
  street timestamp,
  lastName datetime,
  downloadCount bit
);

CREATE TABLE audit_div_v1 (
  id serial primary key,
  homePhone smallint,
  startDate boolean,
  departmentCode text,
  earnedPoints smallint,
  foregroundColor double,
  driverLicense datetime,
  sku bit,
  campaignId point,
  filterType mediumint,
  contentType mediumint,
  eventDate real,
  addressLine1 bit,
  dataSource date,
  monthlyRate text,
  checkOutTime point,
  companyName point,
  metadata real,
  articleId varchar,
  albumId int,
  paymentMethod point,
  isLocked int,
  editedAt enum,
  cardNumber blob,
  marketId enum,
  state smallint,
  dependentId real,
  channelId text
);

CREATE TABLE orderdiv (
  id serial primary key,
  postalCode decimal,
  minValue double,
  cancelReason boolean,
  fromDate time,
  attemptCount serial,
  albumId boolean,
  unit mediumint,
  audioUrl blob,
  price point,
  contactPhone serial,
  password datetime,
  comment set,
  accessLevel smallint,
  manufacturerId varchar,
  feedId bit,
  blogId decimal,
  cloudId date,
  fileHash enum,
  campaignId varchar,
  minLimit datetime,
  isRequired timestamp,
  insuranceId point,
  rating boolean,
  adminNotes real
);

CREATE TABLE company (
  id serial primary key,
  avatar int,
  age varchar,
  cityName text,
  errorCode point,
  isSystem smallint,
  earnedPoints binary,
  licenseKey int,
  ipAddress decimal,
  hourlyRate tinyint
);

CREATE TABLE config (
  id serial primary key,
  fontFamily serial,
  levelId set,
  latitude double,
  colorCode point,
  address geometry,
  errorCode decimal,
  comment enum,
  handlerId real,
  authMethod mediumint,
  accountType float,
  fromDate text,
  fileSize datetime,
  likeCount float,
  deviceId timestamp,
  signature geometry,
  houseNumber date,
  faxNumber double,
  exportId timestamp,
  lastName enum,
  maxLimit tinyint,
  addressLine1 bigint,
  phone int,
  addressLine2 time,
  logLevel geometry,
  invoiceId date,
  creditLimit bit
);

CREATE TABLE vwpayment (
  id serial primary key,
  coverImage datetime,
  departmentCode float,
  avatar geometry,
  friendId timestamp,
  entryPoint geometry,
  companyName date,
  comment boolean,
  campaignId datetime,
  dashboardId boolean,
  defaultValue date,
  street time,
  maxValue int,
  cvv bigint,
  filterType text,
  appVersion varchar,
  accountStatus varchar,
  age serial,
  birthDate time
);

CREATE TABLE accountv1 (
  id serial primary key,
  deviceType enum,
  paymentMethod date,
  accountNumber time,
  jobTitle binary,
  certificateId text,
  weight real,
  batchId boolean,
  merchantId serial,
  displayOrder boolean,
  age varchar,
  score date,
  employeeCode varchar,
  contactEmail double,
  isArchived point,
  companyLogo blob,
  instructorId binary,
  insuranceId serial,
  isHidden text,
  accountStatus timestamp,
  macAddress blob,
  isAdmin geometry,
  globalId set,
  billingCycle binary,
  bookingDate text,
  adminNotes double,
  contactPhone geometry,
  importId time,
  fileHash int,
  comment timestamp,
  isEnabled bigint,
  avatar int
);

CREATE TABLE order (
  id serial primary key,
  category int,
  meterNumber int,
  maxValue set
);

CREATE TABLE vwcustomerdiv (
  id serial primary key,
  activeDevices point,
  algorithm float,
  localeId bigint,
  balance int,
  coordinateY varchar,
  dateFormat text,
  fileName bit,
  feedbackId datetime,
  fontFamily geometry,
  cardNumber binary,
  groupName int
);

CREATE TABLE organization (
  id serial primary key,
  createdAt bit,
  companyLogo bigint,
  messageId float,
  integrationId serial,
  height datetime,
  ipAddress geometry,
  defaultValue decimal,
  price decimal,
  contractId text,
  comment float,
  copyRight enum,
  countryCode timestamp,
  checkInTime bit,
  formatType blob,
  clockIn binary,
  billingFrequency binary
);

CREATE TABLE config (
  id serial primary key,
  balance time,
  companyName text,
  hiddenAt geometry,
  creditCard float,
  startDate decimal,
  feedbackId tinyint,
  entityId point,
  category tinyint,
  awardDate point,
  gameId timestamp,
  jobTitle mediumint,
  earnedPoints date,
  dueDateAt text
);

CREATE TABLE company (
  id serial primary key,
  inactiveAt mediumint,
  size timestamp,
  loginCount set,
  defaultLang bit,
  age datetime
);

CREATE TABLE product_type (
  id serial primary key,
  deletedAt set,
  instanceId serial,
  claimId text,
  accessLevel datetime,
  keyId mediumint,
  customerGroup blob,
  abandonedCartId double,
  messageId binary,
  contactPhone bigint,
  deactivatedAt tinyint,
  deviceType geometry,
  updatedAt decimal,
  licenseKey point,
  weight mediumint,
  frameRate bigint,
  sessionId boolean,
  brandId double,
  expiryDate float,
  appVersion double,
  cityName set,
  longitude date,
  articleId enum,
  name tinyint,
  isSystem double,
  countryCode double,
  firmwareVersion set
);

CREATE TABLE config_seg (
  id serial primary key,
  errorMessage mediumint,
  domainName time,
  zipCode double,
  createdAt decimal,
  mimeType datetime,
  companyName text,
  accountNumber point,
  campaignId double,
  instructorId int,
  content smallint,
  metadata smallint
);

CREATE TABLE product (
  id serial primary key,
  phone binary,
  cardNumber smallint,
  isDeleted serial,
  brandId varchar,
  itemCount double,
  modifiedAt time,
  dataSource decimal,
  audioUrl datetime,
  awardDate bit,
  headerImage set,
  attachmentUrl decimal,
  sessionId date,
  feedId decimal,
  password binary,
  birthDate set,
  age decimal,
  billingFrequency int,
  minValue smallint,
  metaKeywords point
);

CREATE TABLE src_transaction_status (
  id serial primary key,
  isVerified mediumint,
  adminNotes date
);

CREATE TABLE company_status (
  id serial primary key,
  createdAt int,
  customField1 point,
  dataSource varchar,
  rating double,
  dashboardId point,
  name time,
  accountType serial,
  meterNumber smallint,
  currency real,
  coordinateY boolean,
  filterType datetime,
  analyticsId enum,
  extractId varchar,
  amount float,
  postalCode datetime,
  algorithm serial,
  ipAddress set,
  accountStatus decimal,
  apiKey binary,
  balance blob,
  lastLoginAt text,
  completionRate float,
  deviceType decimal,
  emergencyContact boolean,
  maxValue bigint,
  minValue mediumint,
  channelId set,
  foregroundColor binary,
  downloadCount set,
  updatedAt blob
);

CREATE TABLE cpyconfigarchive (
  id serial primary key,
  machineId decimal,
  token float,
  completedAt boolean,
  modifiedAt serial,
  campaignId mediumint,
  zipCode bit,
  employeeId timestamp,
  isDraft bit,
  isSystem boolean,
  balance date,
  isLocked set,
  courseId varchar,
  groupName float,
  activeDevices point,
  cvv smallint
);

CREATE TABLE tbl_user_notifications (
  id serial primary key,
  handlerId text,
  addressLine1 int,
  followCount timestamp,
  weight geometry,
  domainName real,
  firmwareVersion text,
  title serial,
  url datetime,
  fileType point,
  group tinyint,
  taxRate double,
  creditScore blob,
  email bit,
  locationId smallint,
  salary time,
  deviceId varchar,
  awardDate date,
  education enum,
  unit binary,
  currency point
);

CREATE TABLE agg_user_seg (
  id serial primary key,
  displayOrder date,
  keyId point,
  group text,
  fileHash text,
  gateId double,
  extractId text,
  analyticsId timestamp,
  expiryYear real
);

CREATE TABLE coreuser (
  id serial primary key,
  flagged tinyint,
  childId real,
  employmentDate boolean,
  messageId datetime,
  code int,
  isDraft bigint,
  locationId real,
  insertedAt serial,
  incidentId bit
);

CREATE TABLE inventory (
  id serial primary key,
  folderPath time,
  referralCode varchar,
  validUntil blob,
  floorNumber set,
  title float,
  invoiceId varchar,
  birthDate bigint,
  avatar binary,
  eventDate binary,
  bankAccount datetime,
  metadata datetime,
  algorithm smallint,
  flagged float,
  countryCode blob,
  exportId date,
  companyName decimal,
  checkOutTime boolean,
  loginCount date
);

CREATE TABLE core_organization_log (
  id serial primary key,
  managerId varchar,
  size enum,
  bookingDate time,
  isActive int,
  currency datetime,
  description enum,
  earnedPoints boolean,
  maritalStatus enum,
  companyId datetime,
  completedAt int,
  departmentCode real,
  amount float,
  manufacturerId date,
  longitude date,
  depositAmount date,
  email mediumint,
  contentType varchar,
  price smallint
);

CREATE TABLE companydata (
  id serial primary key,
  companyName varchar,
  albumId text,
  street time,
  integrationId geometry,
  content time,
  accountNumber serial,
  lastSeenAt tinyint,
  displayOrder bit,
  id varchar,
  memberCount text,
  mobileNumber point,
  password binary,
  checkOutTime text,
  sessionId blob,
  signature enum,
  deletedAt datetime,
  middleName point,
  balance point,
  keyId decimal,
  url serial,
  dealerId real,
  enrollmentDate real,
  comment mediumint,
  city bigint,
  followCount time,
  updatedAt boolean,
  address bit,
  industryType bit,
  cardNumber bit,
  metaKeywords bit
);

CREATE TABLE fact_config (
  id serial primary key,
  cancelReason int,
  price binary,
  isRequired serial
);

CREATE TABLE userstatus (
  id serial primary key,
  analyticsId varchar,
  backupEmail time,
  groupName binary,
  batchId datetime,
  deviceType serial,
  emergencyContact binary,
  metaDescription time,
  isArchived bit,
  licenseKey decimal,
  isVerified int,
  dependentId text,
  isDefault bit,
  age double,
  thumbnail geometry
);

CREATE TABLE src_organization (
  id serial primary key,
  chargeId timestamp,
  activeDevices timestamp,
  chatId date,
  id text,
  dashboardId varchar,
  floorNumber text,
  gateId set,
  metaTitle serial,
  appVersion date,
  birthDate varchar,
  cityName tinyint,
  followCount float,
  filterType text,
  foregroundColor boolean,
  dimension timestamp,
  name text,
  keyId float,
  password timestamp,
  currencyCode blob,
  companyName set,
  blogId set,
  metaDescription boolean,
  colorCode text,
  copyRight enum,
  expiryMonth bit,
  deliveryDate boolean,
  updatedAt boolean,
  invoiceId bit,
  bankAccount boolean,
  entityId timestamp
);

