CREATE TABLE log_audit_new (
  id serial primary key,
  balance datetime,
  productCode blob,
  price enum,
  lastName geometry,
  isVerified binary,
  integrationId enum,
  category point,
  companyName decimal,
  middleName smallint,
  phone blob,
  emailStatus text,
  listId enum,
  dialCode boolean,
  firstName float,
  avatar smallint,
  creditScore binary,
  ipAddress date,
  joinDate decimal,
  macAddress text,
  linkId bigint,
  creditCard mediumint,
  updatedAt blob
);

CREATE TABLE factcustomer (
  id serial primary key,
  isEnabled text,
  id double,
  dataSource mediumint,
  employmentDate point,
  insertedAt date
);

CREATE TABLE inventory (
  id serial primary key,
  awardDate varchar,
  logLevel real,
  avatar timestamp,
  fromDate serial,
  geoLocation int,
  endPoint geometry,
  age int,
  dataSource geometry,
  filterType enum,
  floorNumber timestamp,
  expiryYear int,
  employeeId decimal,
  createdAt smallint,
  actionType float,
  discount text,
  eventDate enum,
  fontSize binary,
  connectionString smallint,
  maxLimit serial,
  levelId mediumint,
  costCenter real,
  deviceId varchar,
  weight smallint,
  exportId time,
  locationId int,
  checkOutTime set,
  orderId bigint,
  merchantId decimal,
  defaultValue set
);

CREATE TABLE organizationnew (
  id serial primary key,
  isVerified real,
  balance datetime,
  contractId date,
  flagged tinyint
);

CREATE TABLE cpy_user (
  id serial primary key,
  deletedAt boolean,
  employeeId real,
  actionType bit,
  addressLine2 serial,
  authMethod datetime,
  jobTitle tinyint,
  metaDescription time,
  contentType bit,
  faxNumber date,
  deliveryDate float,
  isLocked real,
  loginAttempts bit,
  maritalStatus blob,
  metadata bit,
  localeId real,
  birthDate blob
);

CREATE TABLE tmporderlognew (
  id serial primary key,
  avatar varchar,
  listingId point,
  metaDescription datetime
);

CREATE TABLE recordlegacy (
  id serial primary key,
  companyLogo blob,
  comment decimal,
  unit blob,
  timezone tinyint,
  metaKeywords bit,
  fontSize datetime,
  isActive text,
  amount varchar,
  version time,
  indexKey point,
  uuid bigint,
  employeeId set,
  browserType int,
  loginAttempts binary,
  group boolean,
  channelId real
);

CREATE TABLE puborganizationdiv (
  id serial primary key,
  currencyCode decimal,
  deliveryDate timestamp,
  industryType datetime,
  coverImage boolean,
  birthDate timestamp,
  phone time,
  currency text,
  defaultValue geometry,
  signature double,
  gameId datetime,
  dialCode set,
  score tinyint,
  faxNumber double,
  accessLevel smallint,
  token int,
  balance enum,
  dealerId text,
  dashboardId smallint,
  creditScore blob
);

CREATE TABLE config_div (
  id serial primary key,
  marketId smallint,
  bankAccount timestamp,
  cvv float,
  description enum,
  homePhone date,
  category set,
  metaDescription datetime,
  friendId tinyint,
  driverLicense text,
  awardDate time,
  extractId boolean,
  tags text,
  budgetCode tinyint,
  forwardTo mediumint,
  value decimal,
  dependentId text,
  title binary,
  copyRight enum,
  validUntil boolean,
  attachmentUrl double
);

CREATE TABLE ref_company (
  id serial primary key,
  metadata real,
  configId float,
  buildNumber bit,
  currencyCode timestamp,
  sessionId float,
  fileSize decimal,
  balance text,
  maskType int,
  shippingAddress bigint,
  dealerId point,
  keywords bit,
  clockOut mediumint,
  phone float,
  keyId blob,
  layerId mediumint,
  address point,
  companyLogo time,
  deletedAt decimal,
  cloudId tinyint,
  globalId set,
  country double,
  mapId timestamp,
  eventDate bigint,
  thumbnail int
);

CREATE TABLE orderout (
  id serial primary key,
  hiddenAt int,
  favoriteCount real,
  indexKey binary,
  completedAt double,
  longitude tinyint,
  budgetCode text,
  frameRate time,
  createdAt binary,
  companyName varchar,
  description bit,
  merchantId bigint,
  url time,
  likeCount geometry,
  birthDate blob,
  isActive point,
  productCode float,
  gender bigint,
  balance enum,
  thumbnail int,
  foregroundColor enum,
  insertedAt tinyint,
  chatId varchar,
  completionRate serial,
  lockoutEnd smallint,
  departmentCode enum,
  hostName tinyint,
  browserType blob,
  updatedAt set
);

CREATE TABLE audit_temp (
  id serial primary key,
  birthDate decimal,
  maxValue blob,
  brandId time,
  headerImage datetime,
  firstName varchar,
  isDeleted decimal,
  metaKeywords set,
  currency bit,
  cancelReason time,
  accountStatus set,
  companyId geometry,
  metadata boolean,
  group serial,
  distributorId boolean,
  score text,
  discountCode boolean,
  zipCode bigint,
  cvv binary,
  expiryYear bigint,
  category binary,
  configId enum,
  guestId varchar,
  accountType enum,
  dueDateAt double,
  browserType text,
  cardNumber bit,
  iconPath time,
  ipAddress point,
  exportId varchar,
  enabledAt bigint,
  createdAt text
);

CREATE TABLE dstcompanydiv (
  id serial primary key,
  creditScore bit,
  cartId timestamp,
  taxRate double,
  age smallint,
  deviceToken binary,
  comment datetime,
  group float,
  copyRight int,
  monthlyRate point,
  sessionId datetime,
  mapId boolean,
  modifiedAt geometry,
  earnedPoints blob,
  deviceId text,
  menuId blob,
  cancelReason binary,
  apiKey blob,
  merchantId geometry,
  isBillable bigint,
  isLocked set,
  address real,
  accountType set,
  costCenter geometry,
  metaDescription varchar
);

CREATE TABLE product_div (
  id serial primary key,
  shippingAddress real,
  createdAt varchar,
  username mediumint,
  id enum,
  metadata tinyint,
  status float,
  listingId bigint,
  dashboardId varchar,
  address bit,
  name point,
  apiVersion bigint,
  avatar time,
  chatId real,
  gender float,
  courseId bigint,
  fileType int,
  cityName blob,
  loginCount text,
  contactEmail float,
  companyName bit,
  lastLoginAt bigint,
  role blob,
  globalId date,
  balance blob,
  phone time,
  isDefault text,
  category smallint,
  exportId binary,
  customerGroup float,
  algorithm text
);

CREATE TABLE tbl_product_data_new (
  id serial primary key,
  deletedAt varchar,
  name tinyint,
  expiryDate int,
  folderPath point,
  maxValue boolean,
  orderStatus bigint,
  loginCount decimal,
  managerId varchar,
  dateFormat enum,
  taxRate point,
  accountType date,
  address serial,
  meterNumber mediumint,
  phone enum,
  isVerified set,
  feedbackId double,
  companyName geometry,
  instanceId point,
  weight bigint,
  firmwareVersion bigint,
  analyticsId binary,
  buildNumber time,
  latitude set,
  marketId real,
  thumbnail float,
  hashKey serial,
  instructorId varchar
);

CREATE TABLE cpyuserlegacy (
  id serial primary key,
  discount bit,
  firmwareVersion geometry,
  comment varchar,
  dashboardId blob,
  incidentId point,
  companyName date,
  updatedAt float,
  metaKeywords timestamp,
  isBillable date,
  phone int,
  feedbackId mediumint,
  domainName bit,
  url float,
  maxValue float,
  extractId serial,
  minValue timestamp,
  shippingAddress varchar,
  mapId date,
  certificateId real,
  dueDateAt boolean,
  errorCode varchar
);

CREATE TABLE tmprecordrel (
  id serial primary key,
  sku bigint,
  completedAt tinyint,
  entryPoint int,
  creditScore double,
  age smallint,
  street text,
  dateFormat varchar,
  address serial,
  buildNumber geometry,
  cacheKey mediumint,
  headerImage double,
  firstName tinyint,
  fontSize point,
  clockIn binary,
  flagged varchar,
  analyticsId set,
  orderId set,
  companyName varchar,
  iconPath int,
  avatar binary,
  emergencyContact date,
  memberCount timestamp,
  errorCode double,
  copyRight bit,
  state enum,
  locationId double,
  thumbnail binary,
  dialCode time,
  score tinyint,
  campaignId set,
  favoriteCount point
);

CREATE TABLE vertransaction (
  id serial primary key,
  startDate bigint,
  audioUrl binary,
  isDeleted int,
  awardDate float,
  layerId text,
  locationId float,
  isLocked int,
  apiVersion bit
);

CREATE TABLE organizationmeta (
  id serial primary key,
  authMethod timestamp,
  apiKey binary,
  industryType bigint,
  maskType datetime
);

CREATE TABLE core_user_out_temp (
  id serial primary key,
  certificateId serial,
  creditLimit decimal,
  isArchived float,
  monthlyRate datetime,
  accessLevel timestamp,
  childId blob,
  languageCode binary,
  emergencyContact datetime,
  hostName set,
  username point,
  enabledAt int,
  documentId bigint,
  channelId geometry,
  guestId boolean,
  balance double,
  phone timestamp,
  sku text,
  gameId bigint,
  comment point,
  entityId geometry,
  group bigint
);

CREATE TABLE account (
  id serial primary key,
  eventDate point,
  longitude binary,
  articleId timestamp,
  lockoutEnd float,
  mainImage float,
  email point,
  browserType tinyint
);

CREATE TABLE privauditnew (
  id serial primary key,
  hostName int,
  address mediumint,
  type float,
  monthlyRate blob,
  defaultLang real,
  code date,
  certificateId decimal,
  facilityId text,
  jobTitle double,
  status set,
  headerImage set,
  lastSeenAt varchar,
  isSystem int,
  forwardTo set,
  addressLine1 serial,
  actionType bit,
  guestId timestamp,
  fingerprint date,
  amount date,
  listId enum,
  floorNumber binary,
  insuranceId tinyint,
  title geometry
);

CREATE TABLE company_new (
  id serial primary key,
  sku tinyint,
  phone set,
  creditCard bit,
  username time,
  latitude tinyint,
  longitude timestamp,
  displayOrder set,
  department time,
  authorId boolean,
  clockOut bigint,
  customerId int,
  street bit,
  faxNumber point,
  isAdmin text,
  agentId point,
  followCount time,
  earnedPoints real,
  moduleId datetime,
  keywords tinyint,
  meterNumber float,
  tags timestamp,
  minValue binary
);

CREATE TABLE verauditlegacy (
  id serial primary key,
  documentId real,
  entityId text,
  currency float,
  configId varchar,
  expiryDate varchar,
  weight binary,
  chatId text,
  insertedAt serial,
  driverLicense datetime,
  group bigint,
  deliveryDate decimal,
  emailStatus smallint,
  menuId mediumint,
  title mediumint,
  state tinyint,
  category boolean,
  type tinyint,
  metaKeywords float,
  avatar varchar,
  campaignId decimal,
  dataSource serial,
  cardHolder mediumint,
  localeId bit,
  homePhone serial,
  downloadCount decimal,
  customField1 smallint,
  copyRight enum,
  billingFrequency blob,
  joinDate datetime,
  nickname serial
);

CREATE TABLE app_inventory_div (
  id serial primary key,
  sessionId double,
  coordinateY geometry,
  checkInTime timestamp,
  deviceId float,
  lockoutEnd point,
  countryCode bigint,
  token serial,
  languageCode float,
  productCode timestamp,
  address set,
  guestId bit,
  mapId datetime,
  clockIn bit,
  orderStatus boolean,
  minLimit bit,
  maxLimit double,
  loadTime bit,
  floorNumber datetime
);

CREATE TABLE stg_organization (
  id serial primary key,
  firstName binary,
  expiryDate varchar,
  longitude text,
  createdAt geometry,
  connectionString point,
  username geometry,
  customField2 bit
);

CREATE TABLE audit_v1 (
  id serial primary key,
  loginCount boolean,
  insuranceId datetime,
  street timestamp,
  minValue mediumint,
  fileType real,
  expiryMonth serial,
  taxRate point,
  employmentDate double,
  certificateId point,
  agentId binary,
  accessLevel smallint,
  cancelReason set,
  maskType tinyint,
  content text,
  isEnabled time
);

CREATE TABLE transaction_archive (
  id serial primary key,
  headerImage double,
  email set,
  country enum,
  sessionId set,
  licenseKey float,
  channelId varchar,
  indexKey double,
  productCode serial,
  awardDate float,
  feedId bigint,
  friendId mediumint,
  deactivatedAt int,
  discountCode geometry,
  agentId timestamp,
  machineId bit,
  clockIn geometry
);

CREATE TABLE user_temp (
  id serial primary key,
  forwardTo smallint,
  accessLevel mediumint,
  amount smallint,
  hourlyRate timestamp,
  mapId decimal,
  updatedAt serial,
  grade geometry,
  claimId text,
  colorCode mediumint,
  currency blob,
  url bigint,
  eventDate point,
  category tinyint,
  email mediumint,
  department float,
  extractId time,
  countryCode serial,
  password serial,
  audioUrl set,
  gateId real,
  completionRate int,
  isVerified geometry,
  chargeId blob,
  paymentMethod bit,
  incidentId decimal,
  dimension date,
  birthDate timestamp,
  jobTitle binary,
  height enum,
  exportId datetime,
  mainImage varchar
);

CREATE TABLE src_account (
  id serial primary key,
  category smallint,
  mapId mediumint,
  inactiveAt double,
  licenseKey boolean,
  latitude mediumint,
  feedId date,
  coordinateY time,
  billingCycle bigint,
  comment serial,
  handlerId point,
  completedAt timestamp,
  email serial,
  agentId int,
  linkId geometry,
  clockIn boolean,
  password smallint,
  iconPath decimal,
  distributorId geometry,
  discountCode bigint,
  name set,
  followCount bit,
  batchId datetime,
  gameId tinyint,
  deviceToken real,
  actionType real,
  logLevel timestamp,
  customerId set
);

CREATE TABLE config (
  id serial primary key,
  frameRate blob,
  apiVersion set,
  lastLoginAt point,
  actionType bigint,
  currencyCode serial,
  isArchived point,
  maxValue timestamp,
  createdAt int,
  title tinyint,
  homePhone text,
  keywords int,
  description bit,
  linkId datetime,
  minLimit enum,
  deviceId point,
  coordinateY float,
  indexKey smallint
);

CREATE TABLE company (
  id serial primary key,
  campaignId double,
  employeeCode float,
  thumbnail datetime,
  dailyLimit point,
  email bit,
  coordinateY geometry,
  isDefault varchar,
  facilityId int,
  cardHolder date,
  description geometry,
  address int,
  updatedAt enum,
  homePhone datetime,
  isEnabled text,
  claimId double,
  feedId serial,
  modifiedAt mediumint,
  maritalStatus real,
  customField2 double,
  businessType float
);

CREATE TABLE priv_config (
  id serial primary key,
  loadTime timestamp,
  hiddenAt binary,
  country datetime,
  deviceType blob,
  balance smallint,
  labelText geometry,
  entityId tinyint,
  postalCode datetime,
  campaignId decimal,
  type geometry,
  avatar blob,
  exportId geometry,
  weight varchar,
  mapId boolean,
  discount bigint,
  deletedAt tinyint,
  followCount enum,
  signature float,
  keywords tinyint,
  middleName enum,
  cvv int,
  tags binary
);

CREATE TABLE user_data (
  id serial primary key,
  companyName bigint,
  friendId datetime,
  buildNumber int,
  loadTime geometry,
  title set,
  state float,
  dimension timestamp,
  referralCode serial,
  name serial,
  chargeId smallint,
  macAddress blob,
  abandonedCartId float,
  coordinateY set,
  clientId tinyint,
  modifiedAt datetime,
  startDate bit,
  mapId time,
  clockIn point,
  score datetime,
  menuId bigint,
  category serial,
  productCode real,
  domainName smallint,
  floorNumber tinyint,
  isArchived float,
  certificateId binary,
  groupName enum,
  isPublic blob,
  billingCycle int
);

CREATE TABLE olk_payment (
  id serial primary key,
  bankAccount float,
  bannerImage time,
  phone enum,
  balance double,
  meterNumber geometry,
  cardNumber blob,
  clientId geometry,
  metaKeywords tinyint,
  contractId blob,
  cartId serial,
  amount set,
  orderId float,
  loginCount point,
  iconPath decimal,
  deviceType double,
  errorCode tinyint,
  authMethod blob,
  createdAt binary,
  cloudId bit,
  frameRate set,
  machineId date,
  sessionId timestamp,
  businessType blob,
  fromDate time,
  modifiedAt boolean,
  accountNumber enum,
  fontSize real,
  flagged decimal,
  customerId text
);

CREATE TABLE veruser (
  id serial primary key,
  keyId real,
  algorithm binary,
  errorCode binary,
  exchangeRate double,
  cardHolder tinyint,
  createdAt set,
  costCenter bit,
  isAdmin decimal,
  avatar double,
  id real,
  sku smallint,
  folderPath varchar,
  nickname time,
  analyticsId int,
  token set,
  dataSource point,
  entryPoint float,
  companyLogo double,
  jobTitle point
);

CREATE TABLE relorder (
  id serial primary key,
  countryCode double,
  longitude int,
  group text,
  jobTitle int,
  indexKey float,
  contactEmail text,
  balance varchar,
  followCount double,
  expiryDate time,
  macAddress datetime,
  downloadCount bit,
  fileHash blob,
  loginCount timestamp,
  customerGroup geometry,
  hostName serial,
  paymentMethod set,
  machineId timestamp,
  isArchived timestamp,
  billingFrequency blob,
  deactivatedAt mediumint,
  fileType set
);

CREATE TABLE ref_payment_data (
  id serial primary key,
  employeeCode binary,
  isHidden enum,
  paymentMethod blob,
  discountCode smallint,
  expiryMonth binary,
  backupEmail time,
  latitude varchar,
  domainName float,
  username int,
  friendId mediumint,
  balance geometry,
  createdAt varchar,
  childId float,
  moduleId smallint,
  blogId time,
  loginCount varchar,
  documentId smallint,
  address point,
  accessLevel int,
  enrollmentDate timestamp,
  title bigint,
  orderStatus set,
  apiKey boolean,
  inactiveAt timestamp
);

CREATE TABLE ref_record (
  id serial primary key,
  defaultLang bit,
  feedbackId float,
  companyId tinyint,
  employeeId time,
  cardHolder enum,
  dueDateAt int,
  insertedAt blob,
  attachmentUrl geometry,
  formatType geometry,
  isDeleted enum,
  cardNumber mediumint,
  balance real,
  departmentCode date,
  tags mediumint,
  mapId blob,
  quantity enum,
  filterType timestamp,
  exportId bigint,
  accountNumber serial,
  height time,
  orderStatus decimal,
  id int,
  salary text,
  copyRight blob,
  address int,
  keyId enum,
  configId serial,
  loginAttempts tinyint
);

CREATE TABLE src_user_type_v2 (
  id serial primary key,
  locationId binary,
  title datetime,
  maxValue point,
  clientId bigint,
  minLimit text,
  faxNumber double,
  insertedAt double,
  ipAddress real,
  cartId binary,
  bankAccount enum,
  documentId geometry,
  discountCode serial,
  accountStatus datetime,
  globalId date,
  businessType time
);

CREATE TABLE config (
  id serial primary key,
  isDefault datetime,
  tags decimal,
  zipCode time,
  licenseKey date,
  accessLevel smallint,
  dealerId int,
  cvv date,
  comment bigint,
  accountStatus double,
  deactivatedAt tinyint,
  houseNumber decimal,
  childId float,
  machineId boolean,
  downloadCount geometry,
  copyRight set,
  endDate enum,
  billingFrequency tinyint,
  billingCycle double,
  clockIn tinyint,
  discountCode float,
  authToken point,
  department point,
  exchangeRate datetime,
  minLimit tinyint
);

CREATE TABLE ver_transaction (
  id serial primary key,
  amount enum,
  updatedAt text,
  handlerId date,
  audioUrl timestamp,
  salary tinyint,
  feedbackId time,
  filterType tinyint,
  priority tinyint,
  duration date,
  levelId binary,
  tags real,
  accountNumber enum,
  menuId blob,
  authorId mediumint,
  coordinateY text,
  latitude double,
  contactName double,
  blogId serial,
  sessionId text,
  username tinyint,
  password timestamp,
  modifiedAt blob,
  metaTitle geometry,
  entityId date
);

CREATE TABLE product (
  id serial primary key,
  taxRate set,
  costCenter serial,
  metaKeywords int,
  mobileNumber int
);

CREATE TABLE customer (
  id serial primary key,
  incidentId tinyint,
  signature double,
  currencyCode float,
  longitude int,
  updatedAt point
);

CREATE TABLE inventory (
  id serial primary key,
  deviceType datetime,
  feedId tinyint,
  email enum,
  brandId mediumint,
  attachmentUrl text,
  integrationId binary,
  merchantId bigint,
  deviceId binary,
  companyLogo tinyint,
  indexKey text,
  lastSeenAt tinyint,
  importId set,
  modifiedAt mediumint,
  deliveryDate enum,
  isFeatured time,
  displayName int,
  authToken decimal,
  depositAmount enum,
  friendId int,
  customField2 bigint,
  score text,
  address bit
);

CREATE TABLE customer (
  id serial primary key,
  lastName varchar,
  billingCycle boolean,
  driverLicense datetime,
  jobTitle bigint,
  middleName smallint,
  adminNotes double,
  deviceToken timestamp,
  duration mediumint,
  macAddress blob,
  category tinyint,
  contentType enum,
  price geometry,
  agentId bit,
  endPoint float,
  instructorId text,
  mimeType geometry,
  timezone set,
  token smallint,
  countryCode blob,
  deviceId decimal,
  insuranceId bigint,
  joinDate mediumint,
  licenseKey geometry,
  productCode timestamp,
  departmentCode set,
  phone binary,
  content datetime,
  integrationId float,
  displayOrder geometry
);

CREATE TABLE fact_record (
  id serial primary key,
  eventDate bigint,
  duration geometry,
  currencyCode binary,
  accountStatus bit,
  activeDevices varchar,
  errorCode blob,
  actionType serial,
  dialCode double,
  coordinateX set,
  channelId enum,
  moduleId time,
  validUntil set,
  contentType bit,
  bookingDate datetime,
  unit serial,
  appVersion set,
  url text,
  dailyLimit real
);

CREATE TABLE tmp_audit (
  id serial primary key,
  cardHolder float,
  category boolean,
  logLevel real,
  url text,
  agentId point,
  invoiceId timestamp,
  faxNumber boolean,
  documentId mediumint,
  errorMessage int,
  customField2 geometry
);

CREATE TABLE product_extra (
  id serial primary key,
  dependentId bigint,
  version datetime,
  managerId mediumint,
  state tinyint,
  employeeId binary,
  globalId tinyint,
  dashboardId int,
  accountType blob,
  cacheKey time,
  claimId decimal,
  currency time,
  metaDescription bit,
  couponCode time,
  comment decimal,
  depositAmount float,
  isVerified mediumint
);

CREATE TABLE dim_organization (
  id serial primary key,
  balance tinyint,
  abandonedCartId bit,
  paymentMethod time,
  connectionString float,
  isVerified real
);

