CREATE TABLE src_organization (
  id serial primary key,
  deviceToken serial,
  layerId bit,
  instructorId double,
  id point,
  weight set,
  formatType bigint,
  updatedAt float,
  timezone tinyint,
  group time,
  department int,
  unit varchar,
  lastSeenAt set,
  moduleId date,
  accountType text,
  connectionString double
);

CREATE TABLE record_status (
  id serial primary key,
  instanceId set,
  domainName enum,
  downloadCount bigint
);

CREATE TABLE audit_v1 (
  id serial primary key,
  certificateId mediumint,
  contractId tinyint,
  state point,
  lastName bit,
  metaKeywords real,
  shippingAddress date,
  height real,
  age decimal,
  managerId text,
  dueDateAt varchar,
  cacheKey serial,
  tags bit,
  avatar real,
  listingId geometry
);

CREATE TABLE rel_config (
  id serial primary key,
  claimId set,
  handlerId blob,
  defaultLang serial,
  agentId mediumint,
  completedAt time,
  memberCount int,
  levelId tinyint,
  updatedAt int
);

CREATE TABLE organization (
  id serial primary key,
  indexKey time,
  isEnabled smallint,
  channelId int,
  errorCode int,
  url datetime,
  latitude point,
  fromDate blob,
  isHidden float,
  albumId boolean,
  licenseKey tinyint,
  insuranceId text,
  minValue set,
  macAddress double,
  exchangeRate smallint,
  coordinateY serial,
  fontFamily point,
  dealerId smallint,
  comment datetime,
  email geometry,
  facilityId point,
  discountCode serial,
  signature double,
  blogId enum,
  taxRate point,
  backupEmail text,
  group varchar,
  content mediumint
);

CREATE TABLE config_info (
  id serial primary key,
  creditLimit mediumint,
  linkId tinyint,
  marketId date,
  budgetCode mediumint,
  avatar text,
  isSystem bigint,
  metaKeywords float,
  isEnabled mediumint,
  isDefault bit,
  type float,
  thumbnail serial,
  dateFormat decimal,
  id set,
  coordinateY point,
  description binary,
  feedId decimal,
  driverLicense mediumint,
  maskType real,
  age enum,
  enrollmentDate set,
  insertedAt real,
  errorMessage float
);

CREATE TABLE transaction (
  id serial primary key,
  phone blob,
  zipCode boolean,
  uuid date,
  thumbnail bit,
  group time
);

CREATE TABLE coreorganization (
  id serial primary key,
  isDeleted varchar,
  displayOrder boolean,
  completedAt mediumint,
  instanceId bit,
  connectionString time,
  employeeId text,
  meterNumber bigint,
  deletedAt smallint,
  fileSize timestamp,
  maskType serial,
  countryCode set,
  gameId set,
  configId smallint,
  incidentId float,
  accessLevel geometry,
  childId time,
  dailyLimit point,
  department point,
  checkOutTime timestamp,
  albumId bigint,
  displayName geometry,
  status int,
  clientId decimal,
  homePhone float,
  createdAt double,
  amount geometry,
  depositAmount varchar,
  merchantId boolean,
  customerGroup varchar
);

CREATE TABLE account (
  id serial primary key,
  street time,
  avatar text,
  isVerified time,
  url set,
  moduleId bit,
  mapId bit,
  maxLimit blob,
  totalAmount int,
  costCenter mediumint,
  headerImage datetime
);

CREATE TABLE fact_company_info (
  id serial primary key,
  dealerId bigint,
  configId tinyint,
  instanceId tinyint,
  labelText set,
  flagged timestamp,
  orderId datetime,
  followCount enum,
  maxValue text,
  linkId geometry,
  createdAt serial,
  username bit,
  documentId double,
  apiVersion smallint,
  avatar enum,
  indexKey set
);

CREATE TABLE customer_extra (
  id serial primary key,
  downloadCount real,
  businessType time,
  duration tinyint,
  campaignId mediumint,
  instanceId geometry,
  phone blob,
  layerId point,
  childId serial,
  likeCount bit,
  menuId bit,
  audioUrl smallint,
  attachmentUrl bit,
  unit int,
  deactivatedAt geometry
);

CREATE TABLE organizationlog (
  id serial primary key,
  loginCount int,
  content time,
  createdAt date,
  defaultValue binary,
  isRequired point,
  height date,
  avatar geometry,
  lastSeenAt float,
  activeDevices bigint,
  paymentMethod timestamp,
  city geometry,
  role serial,
  priority bigint,
  age datetime,
  duration decimal,
  orderStatus varchar,
  authMethod bigint,
  fromDate decimal,
  connectionString int
);

CREATE TABLE record (
  id serial primary key,
  deliveryDate boolean,
  actionType geometry,
  firstName enum,
  couponCode datetime,
  content enum,
  contactPhone mediumint,
  city time,
  blogId real,
  isHidden float,
  grade text,
  managerId double,
  floorNumber point,
  followCount time,
  updatedAt bigint,
  audioUrl text,
  loginCount real
);

CREATE TABLE payment (
  id serial primary key,
  id binary,
  postalCode datetime,
  metadata text
);

CREATE TABLE transaction (
  id serial primary key,
  moveId bit,
  joinDate decimal,
  accountType geometry,
  bankAccount date,
  browserType decimal,
  awardDate varchar,
  agentId serial,
  sku decimal,
  errorCode binary,
  contactPhone set,
  faxNumber blob,
  hashKey geometry,
  emailStatus bit,
  forwardTo serial,
  activeDevices mediumint,
  configId double,
  contentType bit,
  accountStatus bigint,
  macAddress double,
  apiKey bit,
  creditLimit tinyint,
  coordinateY float
);

CREATE TABLE audit_notifications (
  id serial primary key,
  menuId boolean,
  eventDate float,
  ipAddress blob,
  actionType datetime,
  guestId timestamp,
  cacheKey real,
  employmentDate float,
  latitude double,
  insertedAt time,
  deviceType boolean,
  enabledAt point,
  cityName blob,
  companyName point,
  endPoint decimal,
  macAddress enum,
  metaKeywords int,
  contractId binary,
  amount text,
  brandId bit,
  totalAmount smallint,
  grade int,
  documentId geometry,
  filterType binary,
  attemptCount time,
  itemCount geometry,
  algorithm float,
  dialCode double,
  dealerId binary,
  incidentId int
);

CREATE TABLE account_out_v2 (
  id serial primary key,
  gameId date,
  maxLimit binary,
  indexKey varchar,
  forwardTo smallint,
  managerId serial,
  currency text,
  country timestamp,
  brandId bigint,
  height geometry,
  keyId bit,
  age binary,
  cartId varchar,
  insuranceId double,
  authorId bigint,
  dueDateAt date,
  courseId decimal
);

CREATE TABLE vercustomernotifications (
  id serial primary key,
  errorCode int,
  dailyLimit decimal,
  contentType datetime,
  contactPhone geometry,
  accountStatus serial,
  apiKey float,
  foregroundColor int,
  address geometry,
  country text,
  height bigint,
  contactName bit,
  status set,
  zipCode boolean,
  deletedAt geometry,
  hostName enum,
  coordinateY time,
  formatType datetime,
  contactEmail bit,
  cartId double,
  content double,
  moveId geometry,
  completedAt mediumint,
  value float,
  endPoint mediumint,
  defaultValue date,
  bluetoothId real,
  analyticsId serial,
  billingFrequency datetime
);

CREATE TABLE sysaudit (
  id serial primary key,
  languageCode varchar,
  accountStatus smallint,
  costCenter set,
  backupEmail blob,
  contactPhone varchar,
  modifiedAt datetime,
  joinDate bigint,
  accessLevel enum,
  contactName datetime,
  maxValue varchar,
  floorNumber blob,
  thumbnail bit,
  domainName set,
  cartId text,
  apiVersion binary,
  loadTime date,
  token bit,
  groupName date
);

CREATE TABLE tmp_user (
  id serial primary key,
  fromDate boolean,
  errorCode real,
  algorithm double,
  contentType time,
  id geometry,
  metaKeywords real,
  apiVersion tinyint,
  accessLevel smallint,
  linkId serial,
  expiryMonth blob,
  moduleId enum,
  weight tinyint,
  facilityId timestamp,
  actionType text,
  value serial,
  addressLine2 boolean,
  maskType float,
  claimId varchar,
  content smallint,
  status boolean,
  coordinateY serial,
  inactiveAt smallint,
  handlerId varchar,
  colorCode enum,
  editedAt float
);

CREATE TABLE tmp_payment (
  id serial primary key,
  gender time,
  abandonedCartId geometry,
  ipAddress float,
  lastSeenAt date,
  messageId smallint,
  address varchar,
  entityId date,
  longitude float,
  facilityId date,
  weight smallint,
  connectionString date,
  certificateId blob,
  firstName bigint,
  metaDescription bigint,
  bankAccount float,
  isBillable binary,
  flagged varchar,
  cityName int,
  checkOutTime enum,
  houseNumber boolean,
  currencyCode float,
  audioUrl float,
  dateFormat smallint,
  grade datetime,
  industryType serial,
  mapId bit,
  manufacturerId float,
  blogId bit
);

CREATE TABLE ref_company (
  id serial primary key,
  size real,
  forwardTo datetime,
  clockOut smallint,
  isDeleted blob,
  discount double,
  dailyLimit date,
  licenseKey bigint,
  city bigint,
  contentType blob,
  companyName tinyint,
  maskType mediumint,
  mobileNumber bit,
  amount int,
  authMethod datetime,
  country bigint,
  expiryYear smallint,
  tags tinyint,
  id smallint,
  likeCount geometry,
  meterNumber set,
  browserType real
);

CREATE TABLE stg_audit_out (
  id serial primary key,
  certificateId bigint,
  expiryMonth int,
  companyName datetime,
  isBillable int,
  birthDate geometry,
  currencyCode float,
  code tinyint,
  entityId timestamp,
  bannerImage double,
  cardNumber varchar
);

CREATE TABLE account (
  id serial primary key,
  url int,
  displayName text,
  sessionId mediumint,
  checkOutTime time,
  favoriteCount time,
  fontSize date,
  addressLine1 mediumint,
  department varchar,
  ipAddress smallint,
  firstName binary,
  billingCycle datetime
);

CREATE TABLE core_order (
  id serial primary key,
  middleName bit,
  contentType tinyint,
  instanceId timestamp,
  hostName real,
  addressLine2 datetime,
  customerId datetime,
  authMethod timestamp,
  blogId serial,
  isSystem boolean
);

CREATE TABLE transactionlog (
  id serial primary key,
  depositAmount bigint,
  keywords point,
  balance double,
  version int,
  creditLimit varchar,
  priority tinyint,
  birthDate time,
  merchantId real,
  contentType serial,
  deletedAt bit,
  startDate real,
  foregroundColor blob
);

CREATE TABLE dimuserout (
  id serial primary key,
  id blob,
  groupName varchar,
  batchId binary,
  levelId geometry,
  contentType mediumint,
  latitude serial,
  amount decimal,
  isFeatured time,
  companyName varchar,
  macAddress decimal,
  isLocked decimal,
  creditCard bigint,
  countryCode boolean,
  contractId enum
);

CREATE TABLE dim_account (
  id serial primary key,
  totalAmount mediumint,
  uuid timestamp,
  listId varchar,
  exportId decimal,
  displayOrder binary,
  formatType double,
  checkInTime time,
  brandId text,
  insertedAt varchar,
  creditLimit date,
  memberCount mediumint
);

CREATE TABLE user (
  id serial primary key,
  departmentCode datetime,
  comment geometry,
  hashKey varchar,
  url double,
  authMethod time,
  companyLogo int,
  fontFamily enum,
  listingId enum,
  listId text,
  childId binary,
  insuranceId bit,
  fingerprint float,
  headerImage point,
  metadata point,
  ipAddress boolean,
  currency bit,
  description serial,
  longitude bigint,
  couponCode bigint,
  isLocked set,
  levelId date,
  taxRate time
);

CREATE TABLE inventory_hist (
  id serial primary key,
  ipAddress set,
  avatar enum,
  discount geometry,
  balance int,
  amount tinyint,
  accountNumber point,
  departmentCode bigint,
  analyticsId geometry,
  insertedAt double,
  addressLine1 decimal,
  exchangeRate real,
  copyRight time,
  checkOutTime tinyint,
  lastSeenAt real,
  fontSize real,
  metaTitle bit,
  likeCount time,
  forwardTo blob,
  totalAmount blob,
  dailyLimit varchar,
  indexKey real,
  channelId enum,
  eventDate double,
  batchId date,
  bookingDate varchar,
  labelText enum
);

CREATE TABLE payment (
  id serial primary key,
  description point,
  authMethod time,
  fontFamily text,
  discountCode bit,
  enrollmentDate real,
  insertedAt double,
  shippingAddress timestamp,
  comment int,
  deactivatedAt datetime,
  iconPath smallint,
  height varchar,
  checkOutTime decimal,
  gateId float,
  attemptCount smallint,
  itemCount float,
  age binary,
  displayName time,
  macAddress double,
  currency decimal,
  fontSize double,
  friendId varchar,
  emailStatus geometry,
  score real,
  locationId geometry,
  countryCode tinyint,
  isLocked datetime,
  postalCode timestamp,
  duration int,
  bluetoothId double,
  merchantId date
);

CREATE TABLE log_order_notifications_2025 (
  id serial primary key,
  departmentCode double,
  email set,
  cardNumber text,
  department varchar,
  analyticsId decimal,
  dimension boolean,
  referralCode bit,
  title double,
  billingFrequency geometry,
  blogId boolean,
  documentId int,
  invoiceId timestamp,
  expiryDate datetime,
  phone bigint,
  chargeId text,
  adminNotes smallint,
  backupEmail boolean,
  loginCount boolean
);

CREATE TABLE audit (
  id serial primary key,
  version bigint,
  algorithm mediumint,
  exportId float,
  accountType set,
  friendId mediumint,
  entryPoint varchar,
  createdAt varchar,
  flagged set,
  isDeleted bit,
  dateFormat double,
  localeId varchar,
  referralCode float,
  channelId smallint,
  cityName serial,
  exchangeRate mediumint,
  firstName geometry,
  addressLine1 int,
  comment timestamp,
  campaignId boolean,
  invoiceId blob,
  totalAmount bigint,
  username point,
  creditScore binary,
  jobTitle geometry,
  integrationId date,
  globalId set,
  zipCode set,
  minLimit decimal,
  token tinyint,
  deviceType blob
);

CREATE TABLE organization_log (
  id serial primary key,
  status binary,
  emergencyContact varchar,
  accessLevel mediumint,
  customerId time,
  enabledAt set,
  creditScore tinyint,
  companyName text,
  checkInTime tinyint,
  headerImage datetime,
  attachmentUrl geometry,
  exchangeRate double,
  coordinateX set,
  hourlyRate decimal
);

CREATE TABLE src_audit_rel (
  id serial primary key,
  labelText boolean,
  sessionId enum,
  name geometry,
  apiKey bit,
  group serial,
  taxRate decimal,
  languageCode boolean,
  isDefault real,
  folderPath float,
  fileSize double,
  certificateId double,
  bluetoothId time,
  clockIn bigint,
  bannerImage tinyint,
  password int,
  blogId real,
  eventDate float,
  defaultValue smallint,
  loadTime binary,
  zipCode bigint,
  driverLicense decimal,
  messageId datetime,
  gameId decimal
);

CREATE TABLE audit_map (
  id serial primary key,
  customField2 binary,
  type varchar,
  referralCode int,
  enabledAt varchar,
  metaTitle geometry,
  endPoint date
);

CREATE TABLE corerecord (
  id serial primary key,
  forwardTo real,
  signature varchar,
  companyId text,
  countryCode set
);

CREATE TABLE organization (
  id serial primary key,
  contractId boolean,
  comment boolean,
  defaultValue mediumint,
  configId enum,
  likeCount mediumint,
  couponCode serial,
  creditCard serial,
  isDefault real,
  floorNumber tinyint,
  itemCount decimal,
  id timestamp,
  emailStatus set,
  inactiveAt decimal,
  cloudId bigint,
  languageCode date,
  isFeatured real,
  modifiedAt set,
  loadTime varchar,
  algorithm boolean,
  menuId float,
  avatar binary,
  clockIn int,
  accountType text,
  defaultLang serial,
  url set,
  dimension tinyint
);

CREATE TABLE user_temp (
  id serial primary key,
  customField1 boolean,
  campaignId tinyint,
  displayName double,
  updatedAt smallint
);

CREATE TABLE factproductlog (
  id serial primary key,
  mapId bigint,
  facilityId set,
  locationId decimal,
  fileName set,
  fromDate boolean,
  certificateId bigint,
  department timestamp,
  salary time,
  marketId blob,
  firmwareVersion blob,
  frameRate bit,
  albumId set,
  dataSource bigint,
  abandonedCartId mediumint,
  city geometry,
  maritalStatus mediumint,
  address bit
);

CREATE TABLE olkorder (
  id serial primary key,
  costCenter text,
  forwardTo enum,
  fileSize binary,
  maritalStatus smallint,
  phone float,
  merchantId binary,
  mainImage blob
);

CREATE TABLE user (
  id serial primary key,
  lastSeenAt double,
  isLocked point,
  name decimal,
  description serial,
  priority int,
  fileSize date,
  labelText serial,
  modifiedAt bit,
  deliveryDate text,
  firmwareVersion varchar,
  dateFormat real,
  endDate geometry,
  earnedPoints int
);

CREATE TABLE account (
  id serial primary key,
  rating tinyint,
  gateId time,
  firstName serial,
  languageCode date,
  employmentDate varchar,
  dateFormat enum,
  errorMessage boolean,
  feedbackId time,
  status double,
  attachmentUrl varchar,
  mapId varchar
);

CREATE TABLE sys_record (
  id serial primary key,
  rating mediumint,
  hiddenAt timestamp,
  errorCode varchar,
  isRequired geometry,
  coordinateY geometry,
  employeeId timestamp,
  extractId varchar,
  status point
);

CREATE TABLE olk_organization (
  id serial primary key,
  customField1 float,
  url datetime,
  industryType mediumint,
  completionRate set,
  documentId time,
  handlerId time,
  alertType set,
  mainImage int,
  campaignId timestamp,
  feedId boolean,
  marketId float,
  authorId enum,
  manufacturerId double,
  cancelReason mediumint,
  dependentId decimal,
  expiryDate serial,
  birthDate set,
  deliveryDate varchar,
  defaultLang set,
  accountType blob,
  paymentMethod float,
  isDraft time,
  duration time,
  headerImage datetime,
  adminNotes set,
  licenseKey date
);

CREATE TABLE order (
  id serial primary key,
  followCount timestamp,
  height float,
  id blob,
  isPublic bigint,
  currency real,
  email bigint,
  businessType tinyint,
  dialCode mediumint,
  alertType enum,
  groupName float,
  invoiceId tinyint,
  firmwareVersion boolean,
  lastName serial,
  country tinyint,
  age double,
  countryCode bigint,
  instanceId geometry,
  globalId tinyint,
  apiVersion binary
);

CREATE TABLE extaccountnew (
  id serial primary key,
  price blob,
  bankAccount float,
  createdAt date,
  token int,
  dueDateAt double,
  address set,
  group blob,
  category real
);

CREATE TABLE record (
  id serial primary key,
  taxRate boolean,
  rating int,
  filterType enum,
  hourlyRate timestamp,
  marketId bigint,
  sku geometry,
  distributorId binary,
  manufacturerId bigint,
  clockOut real,
  isDefault boolean
);

CREATE TABLE audit_archive (
  id serial primary key,
  homePhone varchar,
  localeId decimal,
  discount double,
  nickname bit,
  memberCount double,
  awardDate varchar,
  editedAt mediumint,
  name int,
  invoiceId timestamp,
  token double,
  address varchar,
  fileType mediumint,
  cacheKey varchar,
  dataSource date,
  fingerprint varchar,
  dueDateAt enum,
  title bigint,
  maritalStatus binary,
  customerGroup serial,
  ipAddress float,
  validUntil float,
  integrationId datetime,
  cardNumber real,
  eventDate bigint,
  driverLicense decimal,
  defaultLang bit,
  formatType tinyint,
  logLevel decimal,
  albumId text,
  feedId tinyint
);

CREATE TABLE dst_inventory_info (
  id serial primary key,
  totalAmount decimal,
  courseId datetime,
  updatedAt enum,
  meterNumber binary,
  homePhone blob,
  chargeId float,
  contractId enum,
  clockOut blob,
  password decimal,
  expiryMonth timestamp,
  creditCard point,
  importId double,
  fromDate date,
  longitude datetime,
  exportId timestamp,
  creditScore tinyint,
  listingId point,
  category timestamp,
  lastSeenAt mediumint,
  nickname bit,
  iconPath boolean,
  enabledAt timestamp,
  size double,
  status varchar,
  postalCode double,
  localeId binary,
  hiddenAt int,
  title binary,
  signature geometry,
  documentId blob
);

