CREATE TABLE record2024 (
  id serial primary key,
  orderStatus text,
  contractId varchar,
  billingFrequency enum,
  integrationId set,
  phone bigint,
  bankAccount binary,
  accountStatus varchar,
  updatedAt timestamp,
  mapId decimal,
  birthDate datetime,
  cloudId real,
  password blob,
  deviceType timestamp,
  countryCode datetime,
  claimId datetime,
  actionType blob
);

CREATE TABLE tmp_company_out (
  id serial primary key,
  accountNumber set,
  moveId serial,
  companyId mediumint,
  iconPath mediumint,
  price enum,
  discount real,
  displayName boolean,
  mainImage smallint,
  customerId point,
  grade set,
  completedAt blob,
  defaultValue smallint,
  dailyLimit boolean,
  distributorId smallint,
  password boolean,
  indexKey binary,
  importId binary,
  deviceId set,
  extractId blob,
  dialCode point,
  geoLocation real,
  headerImage real
);

CREATE TABLE order (
  id serial primary key,
  favoriteCount bit,
  dimension bit,
  chatId float,
  messageId double,
  updatedAt float,
  score boolean,
  gender float,
  clientId timestamp,
  floorNumber boolean,
  companyId smallint,
  password datetime,
  cancelReason datetime
);

CREATE TABLE dst_account (
  id serial primary key,
  addressLine2 decimal,
  birthDate enum,
  dateFormat point,
  cardNumber real,
  isLocked enum,
  insuranceId decimal,
  currencyCode smallint,
  checkInTime decimal,
  configId text,
  levelId timestamp,
  longitude mediumint,
  deviceToken datetime,
  logLevel tinyint,
  courseId bigint,
  firstName varchar,
  filterType int,
  globalId timestamp,
  inactiveAt mediumint,
  fontFamily blob,
  category bit,
  homePhone boolean,
  totalAmount int,
  department tinyint,
  iconPath bit,
  lockoutEnd double,
  isVerified geometry,
  ipAddress bit,
  updatedAt timestamp,
  referralCode date,
  expiryYear tinyint,
  timezone binary
);

CREATE TABLE companyv1 (
  id serial primary key,
  browserType timestamp,
  colorCode timestamp,
  audioUrl float,
  clientId int
);

CREATE TABLE fact_account (
  id serial primary key,
  dueDateAt set,
  documentId bigint,
  claimId date,
  street float,
  channelId real,
  value time,
  country time,
  score serial,
  isDraft binary,
  emergencyContact bigint,
  cityName point,
  formatType bit,
  maxLimit blob,
  batchId geometry,
  defaultLang datetime,
  dealerId double,
  accessLevel time,
  salary float,
  analyticsId serial,
  content boolean
);

CREATE TABLE ver_company (
  id serial primary key,
  alertType bigint,
  machineId point,
  fileType bit,
  size real,
  memberCount tinyint,
  latitude boolean,
  creditLimit binary,
  appVersion real,
  contactName mediumint,
  fileHash bit,
  referralCode datetime,
  inactiveAt mediumint,
  merchantId varchar,
  labelText double,
  dateFormat date,
  jobTitle serial,
  comment binary,
  birthDate real,
  dashboardId geometry,
  discount timestamp,
  name text,
  mobileNumber time,
  eventDate geometry,
  sessionId varchar,
  apiKey bit
);

CREATE TABLE order (
  id serial primary key,
  feedId text,
  deactivatedAt date,
  email text,
  salary int,
  invoiceId set,
  locationId bigint,
  geoLocation point,
  displayName datetime,
  address varchar,
  phone point,
  balance varchar,
  entryPoint serial,
  avatar text
);

CREATE TABLE product (
  id serial primary key,
  configId decimal,
  extractId blob,
  integrationId timestamp,
  minValue text,
  appVersion datetime,
  machineId double,
  apiVersion datetime,
  errorCode bigint,
  instructorId serial,
  earnedPoints timestamp,
  sku serial,
  entityId geometry,
  backupEmail decimal,
  endDate serial,
  cartId decimal,
  balance double,
  status enum,
  ipAddress point,
  email smallint
);

CREATE TABLE organization_out (
  id serial primary key,
  isPublic bit,
  companyName real,
  localeId time,
  keywords date,
  expiryDate mediumint,
  groupName point,
  balance set,
  audioUrl float
);

CREATE TABLE user (
  id serial primary key,
  address set,
  insuranceId serial,
  batchId decimal
);

CREATE TABLE transaction_v1 (
  id serial primary key,
  menuId enum,
  dependentId set,
  paymentMethod bigint,
  moveId double,
  mapId binary,
  validUntil enum,
  extractId bit,
  age datetime,
  description tinyint,
  metaTitle point,
  friendId datetime,
  cartId blob,
  isLocked double,
  salary enum,
  browserType double,
  eventDate serial,
  cardHolder bigint,
  comment blob,
  insuranceId decimal,
  maskType double,
  frameRate varchar,
  token binary,
  zipCode enum,
  contentType date,
  mimeType datetime,
  cancelReason datetime,
  content time,
  status date,
  customField2 set
);

CREATE TABLE payment (
  id serial primary key,
  invoiceId enum,
  importId mediumint,
  name blob,
  apiKey decimal,
  fileHash point
);

CREATE TABLE priv_account (
  id serial primary key,
  companyId enum,
  cardHolder geometry,
  shippingAddress smallint,
  moduleId datetime,
  loginCount geometry,
  moveId serial,
  rating smallint,
  email enum,
  uuid varchar,
  title varchar,
  dialCode geometry,
  deviceToken date,
  ipAddress int,
  orderId int,
  checkOutTime datetime,
  creditScore real,
  cacheKey bigint,
  url real,
  configId blob,
  insertedAt timestamp,
  group time,
  referralCode mediumint,
  dependentId time,
  quantity time,
  couponCode binary,
  category bigint,
  isDeleted time,
  maxLimit blob,
  managerId tinyint,
  employeeId decimal
);

CREATE TABLE tmpproducthist (
  id serial primary key,
  thumbnail geometry,
  listingId decimal,
  licenseKey geometry,
  eventDate varchar,
  fileType int,
  bankAccount datetime,
  state smallint,
  entityId varchar,
  attachmentUrl boolean,
  age blob,
  configId datetime,
  apiVersion varchar,
  friendId time,
  adminNotes serial,
  companyName serial,
  groupName smallint,
  nickname serial
);

CREATE TABLE company_new (
  id serial primary key,
  instructorId timestamp,
  dimension bit,
  filterType blob,
  employeeId mediumint,
  colorCode date,
  cityName bit,
  groupName timestamp,
  username float,
  integrationId boolean,
  companyName double,
  countryCode float,
  channelId smallint,
  keywords tinyint,
  deactivatedAt geometry,
  creditLimit double,
  indexKey int,
  lockoutEnd date,
  contactEmail geometry,
  state date,
  hourlyRate bigint,
  likeCount enum,
  duration geometry,
  checkInTime tinyint,
  shippingAddress timestamp,
  customerGroup varchar,
  lastLoginAt float,
  keyId binary,
  isDeleted smallint,
  domainName geometry,
  errorMessage time,
  forwardTo serial
);

CREATE TABLE product (
  id serial primary key,
  cardHolder text,
  endPoint real,
  maxValue bigint,
  chatId bigint,
  maxLimit decimal,
  algorithm time,
  frameRate date,
  url geometry
);

CREATE TABLE agguserhistlegacy (
  id serial primary key,
  manufacturerId enum,
  instructorId double,
  floorNumber serial,
  category enum,
  iconPath bigint,
  weight date,
  emergencyContact mediumint,
  createdAt time,
  chargeId boolean,
  balance datetime,
  metaTitle timestamp,
  contentType smallint
);

CREATE TABLE dst_audit_new (
  id serial primary key,
  hostName float,
  discount blob,
  age blob,
  dimension binary,
  itemCount bigint,
  certificateId float,
  endDate date,
  configId tinyint,
  productCode smallint,
  name date,
  incidentId bigint,
  extractId serial,
  audioUrl serial,
  articleId serial,
  activeDevices date,
  fromDate text,
  customerGroup time,
  description bit,
  groupName enum,
  phone double,
  priority point,
  insuranceId smallint,
  errorCode varchar,
  cvv boolean,
  isSystem tinyint,
  creditLimit enum,
  coverImage boolean,
  creditScore blob,
  indexKey double
);

CREATE TABLE transaction (
  id serial primary key,
  employeeCode set,
  contactPhone text,
  isVerified decimal,
  handlerId time,
  amount boolean,
  state varchar,
  albumId geometry,
  machineId set,
  feedbackId enum,
  formatType binary,
  metaTitle point,
  checkInTime double,
  isBillable enum,
  companyName double,
  fileHash real,
  firmwareVersion int,
  insertedAt decimal,
  companyLogo serial,
  budgetCode bigint,
  customField1 serial,
  loginCount timestamp,
  checkOutTime set
);

CREATE TABLE stg_user_2025 (
  id serial primary key,
  certificateId bit,
  bankAccount varchar,
  buildNumber geometry,
  logLevel int,
  courseId real,
  fontFamily serial,
  token time,
  loginCount geometry,
  type varchar,
  id geometry,
  insuranceId mediumint,
  creditScore tinyint,
  priority date,
  manufacturerId text,
  employmentDate set,
  discount time,
  fromDate boolean,
  batchId bigint,
  loadTime mediumint,
  feedId decimal
);

CREATE TABLE rel_organization (
  id serial primary key,
  audioUrl geometry,
  iconPath point,
  taxRate real,
  floorNumber enum,
  batchId mediumint
);

CREATE TABLE log_record_status_2025 (
  id serial primary key,
  group smallint,
  jobTitle int
);

CREATE TABLE ext_user (
  id serial primary key,
  editedAt bigint,
  jobTitle enum,
  defaultLang varchar,
  bookingDate float,
  isArchived binary,
  balance geometry,
  actionType double,
  batchId datetime,
  brandId boolean,
  lastLoginAt boolean,
  locationId varchar,
  role tinyint,
  latitude bit,
  departmentCode decimal,
  backupEmail enum,
  expiryYear real,
  exportId bigint,
  isRequired tinyint,
  emailStatus binary,
  logLevel tinyint,
  companyName blob,
  uuid smallint,
  meterNumber geometry,
  avatar bigint,
  cityName bit
);

CREATE TABLE cpyrecord (
  id serial primary key,
  accountType boolean,
  indexKey geometry,
  documentId tinyint,
  expiryYear datetime,
  abandonedCartId varchar,
  endPoint time,
  flagged decimal
);

CREATE TABLE logcompanylegacy (
  id serial primary key,
  isPublic int,
  entryPoint datetime,
  gameId float,
  batchId timestamp,
  apiVersion bit,
  iconPath decimal,
  companyId float,
  isActive enum
);

CREATE TABLE app_account (
  id serial primary key,
  instanceId decimal,
  downloadCount real,
  street bigint,
  defaultLang binary,
  latitude smallint,
  creditCard boolean,
  exportId serial,
  hourlyRate decimal,
  authToken mediumint,
  creditLimit binary,
  jobTitle mediumint,
  referralCode geometry,
  title datetime,
  earnedPoints decimal,
  orderId enum,
  description mediumint,
  courseId bigint,
  depositAmount timestamp,
  chargeId text,
  accessLevel boolean,
  isSystem boolean,
  inactiveAt text
);

CREATE TABLE ref_inventory_v1 (
  id serial primary key,
  birthDate serial,
  loginCount datetime,
  rating set,
  adminNotes binary,
  lastSeenAt timestamp,
  contactName enum,
  name int,
  mobileNumber serial,
  employeeId time,
  employmentDate timestamp,
  authToken bit,
  avatar int,
  deviceId bit,
  totalAmount float,
  dimension int,
  followCount decimal,
  articleId double,
  currencyCode time,
  manufacturerId set,
  logLevel datetime,
  homePhone point,
  foregroundColor serial
);

CREATE TABLE ref_audit (
  id serial primary key,
  authMethod text,
  currency text,
  gameId smallint,
  channelId varchar,
  hashKey boolean,
  bannerImage time,
  contractId mediumint,
  type time,
  activeDevices tinyint,
  audioUrl boolean,
  menuId datetime,
  enrollmentDate double,
  accountNumber enum,
  gender blob,
  birthDate float,
  amount date,
  memberCount binary,
  coverImage date,
  hourlyRate set,
  cardHolder int,
  exportId bit,
  validUntil double,
  labelText boolean,
  role bigint
);

CREATE TABLE vw_inventory_temp (
  id serial primary key,
  updatedAt text,
  uuid timestamp,
  attemptCount serial
);

CREATE TABLE syscustomer (
  id serial primary key,
  headerImage tinyint,
  chatId real,
  address timestamp,
  description enum,
  incidentId smallint,
  isPublic tinyint,
  followCount float,
  campaignId bigint,
  locationId geometry,
  accountNumber bigint,
  customerId set,
  moduleId timestamp,
  duration int,
  indexKey smallint,
  completionRate smallint,
  contractId float,
  industryType point,
  mainImage int,
  analyticsId serial,
  contentType datetime,
  checkInTime decimal,
  managerId binary,
  birthDate point,
  activeDevices set,
  messageId float,
  username smallint,
  isFeatured int,
  lockoutEnd datetime,
  salary int,
  gender timestamp,
  hourlyRate point
);

CREATE TABLE cpy_transaction_new (
  id serial primary key,
  emailStatus bit,
  title bigint,
  email enum,
  employmentDate mediumint
);

CREATE TABLE app_customer (
  id serial primary key,
  category blob,
  feedId decimal,
  inactiveAt serial,
  domainName smallint,
  moveId varchar,
  signature smallint,
  appVersion boolean,
  age text,
  name decimal,
  departmentCode float,
  certificateId binary,
  comment datetime
);

CREATE TABLE record (
  id serial primary key,
  discount time,
  audioUrl time,
  status geometry,
  enabledAt text,
  billingFrequency geometry,
  completedAt varchar,
  category geometry,
  buildNumber set,
  updatedAt decimal,
  marketId tinyint,
  size timestamp,
  layerId serial,
  cloudId varchar,
  displayOrder double,
  employmentDate float,
  comment bigint
);

CREATE TABLE priv_audit_new (
  id serial primary key,
  errorMessage geometry,
  awardDate date,
  priority float,
  houseNumber set,
  orderId tinyint,
  displayName set,
  description time,
  contentType geometry,
  orderStatus varchar,
  duration bit,
  jobTitle bit,
  cacheKey set,
  accountNumber serial,
  size datetime,
  defaultLang timestamp,
  grade blob,
  apiVersion int,
  accountType smallint,
  metadata varchar,
  longitude datetime,
  attachmentUrl datetime,
  hiddenAt mediumint,
  meterNumber boolean,
  maskType text,
  customerGroup varchar,
  rating serial,
  paymentMethod binary,
  deliveryDate timestamp,
  fingerprint point,
  endPoint bigint
);

CREATE TABLE customerseg (
  id serial primary key,
  address enum,
  loginAttempts time,
  budgetCode smallint,
  deliveryDate bigint,
  geoLocation int,
  moduleId timestamp,
  memberCount serial,
  articleId serial,
  managerId point,
  token int,
  status enum,
  lastLoginAt tinyint,
  comment time,
  dealerId real,
  itemCount boolean,
  incidentId bit,
  isAdmin int,
  activeDevices time,
  homePhone varchar,
  isFeatured int,
  entityId varchar,
  createdAt geometry,
  expiryYear mediumint,
  bannerImage tinyint,
  birthDate serial,
  creditScore geometry,
  headerImage point,
  cardHolder enum,
  backupEmail geometry,
  authMethod geometry,
  faxNumber point
);

CREATE TABLE transaction (
  id serial primary key,
  value blob,
  latitude varchar,
  description mediumint,
  category boolean,
  contactPhone enum,
  defaultLang serial,
  errorMessage binary,
  displayOrder datetime,
  localeId tinyint,
  createdAt enum,
  backupEmail time,
  isPublic int
);

CREATE TABLE ext_organization (
  id serial primary key,
  contractId blob,
  customField1 double,
  validUntil blob,
  id serial,
  value real,
  createdAt tinyint,
  isRequired smallint,
  maritalStatus set
);

CREATE TABLE user (
  id serial primary key,
  isDefault real,
  manufacturerId serial,
  memberCount bit,
  creditCard geometry,
  createdAt time,
  exchangeRate mediumint,
  fileHash blob,
  isHidden text,
  defaultLang int,
  countryCode geometry,
  joinDate varchar,
  isArchived geometry,
  analyticsId blob,
  longitude set,
  description set,
  chargeId geometry,
  filterType set,
  dealerId float,
  gateId smallint,
  rating datetime,
  hashKey decimal,
  deviceToken binary,
  cacheKey bit,
  configId serial,
  balance serial,
  dataSource tinyint,
  customerId decimal,
  score varchar,
  avatar real,
  folderPath serial,
  geoLocation date
);

CREATE TABLE organization (
  id serial primary key,
  dateFormat binary,
  hiddenAt tinyint,
  enrollmentDate set,
  guestId boolean,
  endPoint tinyint,
  password bit,
  status binary,
  lockoutEnd datetime,
  department time,
  sku date,
  deactivatedAt point,
  checkOutTime decimal,
  courseId serial
);

CREATE TABLE customer (
  id serial primary key,
  username int,
  macAddress serial,
  accountNumber blob,
  childId point,
  accountType geometry,
  duration float,
  floorNumber date,
  hostName geometry,
  lockoutEnd varchar,
  customField2 set,
  type double,
  languageCode timestamp,
  paymentMethod serial,
  deactivatedAt binary,
  address timestamp
);

CREATE TABLE payment (
  id serial primary key,
  geoLocation bigint,
  maritalStatus time,
  bookingDate varchar,
  maskType bit,
  accessLevel double,
  linkId bigint
);

CREATE TABLE customer (
  id serial primary key,
  localeId real,
  totalAmount bit,
  id bigint,
  facilityId serial,
  country datetime,
  actionType double,
  gameId text,
  errorMessage time,
  followCount serial,
  minLimit float,
  extractId set,
  currency enum,
  enrollmentDate bit,
  bankAccount decimal,
  downloadCount decimal,
  instanceId serial,
  contactPhone datetime,
  createdAt float,
  handlerId varchar,
  dateFormat decimal,
  licenseKey mediumint,
  isVerified binary,
  homePhone enum,
  audioUrl int,
  floorNumber int,
  domainName real
);

CREATE TABLE record_rel (
  id serial primary key,
  copyRight enum,
  loginCount text,
  birthDate boolean,
  discountCode smallint,
  metadata geometry,
  address boolean,
  salary time,
  faxNumber smallint,
  clientId enum,
  code smallint,
  phone smallint,
  dueDateAt binary,
  lastLoginAt bit,
  monthlyRate varchar,
  unit bit,
  menuId bigint,
  defaultLang point,
  moveId varchar,
  incidentId time,
  errorCode text,
  isRequired real,
  indexKey decimal,
  fileType int,
  customerGroup boolean,
  colorCode serial,
  fileHash text,
  importId boolean,
  displayName varchar,
  extractId float,
  tags mediumint
);

CREATE TABLE pub_customer_map (
  id serial primary key,
  accessLevel decimal,
  currency boolean,
  isEnabled mediumint,
  globalId float,
  cardNumber datetime,
  salary date,
  age bit,
  channelId decimal,
  certificateId text,
  keyId float,
  startDate mediumint,
  id bigint,
  birthDate smallint,
  analyticsId boolean,
  customerGroup text,
  createdAt bit
);

CREATE TABLE record (
  id serial primary key,
  status mediumint,
  dealerId int,
  expiryDate binary,
  cardHolder point,
  zipCode point,
  apiKey date,
  updatedAt decimal,
  defaultValue serial,
  moveId tinyint,
  expiryMonth varchar,
  cloudId point,
  indexKey binary,
  address binary,
  guestId varchar,
  currency text,
  minLimit float,
  taxRate datetime,
  floorNumber double
);

CREATE TABLE corecompanyout (
  id serial primary key,
  fromDate int,
  department decimal,
  weight mediumint,
  cancelReason bigint,
  mapId real,
  hashKey decimal,
  articleId time,
  middleName set,
  timezone binary,
  locationId binary,
  deviceId binary,
  postalCode timestamp,
  algorithm varchar,
  errorCode enum,
  homePhone set,
  billingFrequency float,
  loadTime bigint,
  currency date,
  cityName varchar,
  signature mediumint,
  merchantId geometry,
  accountType text,
  type point,
  value time,
  cvv time,
  foregroundColor double,
  loginAttempts set,
  managerId date,
  ipAddress real,
  isActive tinyint,
  clientId decimal
);

CREATE TABLE ref_user (
  id serial primary key,
  ipAddress boolean,
  version serial,
  role int,
  metaTitle decimal,
  analyticsId bigint
);

CREATE TABLE transaction (
  id serial primary key,
  status mediumint,
  cancelReason real,
  contactName binary,
  filterType timestamp,
  clockOut bit,
  completedAt time,
  exchangeRate real,
  downloadCount enum,
  address float,
  content double,
  metaTitle real,
  category double,
  email mediumint,
  isDeleted geometry,
  fontSize bit,
  distributorId mediumint,
  fileType text,
  mapId datetime
);

CREATE TABLE tmp_company (
  id serial primary key,
  name date,
  gameId datetime,
  customerGroup varchar,
  isDefault double,
  coverImage blob,
  analyticsId real,
  employeeCode decimal,
  grade mediumint,
  channelId tinyint,
  dataSource double,
  browserType boolean,
  incidentId text,
  albumId real,
  lastSeenAt serial,
  completedAt smallint,
  maxLimit geometry,
  houseNumber tinyint,
  postalCode decimal,
  itemCount float,
  certificateId varchar,
  uuid binary,
  flagged int,
  authorId mediumint
);

