CREATE TABLE priv_organization_meta (
  id serial primary key,
  enabledAt point,
  apiVersion text,
  emergencyContact time,
  balance tinyint,
  updatedAt point,
  documentId int,
  isSystem timestamp,
  copyRight mediumint,
  listingId text,
  taxRate binary,
  certificateId time,
  isPublic float,
  coordinateY blob,
  score decimal,
  description binary,
  referralCode blob,
  isDraft mediumint,
  cloudId blob,
  accountStatus tinyint,
  dialCode point,
  sessionId double,
  menuId mediumint,
  totalAmount mediumint,
  cartId tinyint,
  metaTitle double,
  billingCycle timestamp,
  version date,
  handlerId smallint,
  managerId enum,
  mainImage geometry
);

CREATE TABLE dst_company_extra_new (
  id serial primary key,
  password int,
  endPoint geometry,
  emergencyContact point,
  isFeatured serial,
  unit double,
  category tinyint,
  flagged int,
  feedbackId timestamp,
  fileHash smallint,
  comment datetime,
  employeeCode enum,
  dateFormat geometry,
  customerGroup blob,
  isEnabled geometry,
  username double,
  duration varchar,
  fileSize set,
  dailyLimit timestamp,
  chatId boolean,
  layerId set,
  messageId real,
  extractId timestamp,
  uuid boolean,
  likeCount float,
  defaultValue datetime,
  dialCode binary,
  deviceToken mediumint,
  displayOrder binary
);

CREATE TABLE customer (
  id serial primary key,
  coordinateX boolean,
  metaTitle time,
  updatedAt int,
  labelText geometry,
  agentId time,
  isRequired blob,
  employmentDate set,
  abandonedCartId datetime,
  startDate enum,
  favoriteCount blob,
  marketId geometry,
  shippingAddress set,
  meterNumber timestamp,
  thumbnail set,
  accountNumber int,
  comment binary,
  billingFrequency bit
);

CREATE TABLE account (
  id serial primary key,
  companyName text,
  isBillable timestamp,
  customerId point,
  attachmentUrl tinyint,
  nickname real,
  agentId date,
  facilityId mediumint,
  hostName mediumint,
  expiryDate float,
  hourlyRate datetime,
  amount double,
  age point,
  isSystem smallint,
  priority bigint,
  bookingDate double,
  phone double,
  latitude bigint,
  taxRate date,
  copyRight enum,
  moveId varchar,
  updatedAt bigint,
  education tinyint,
  accessLevel blob,
  fingerprint bit,
  billingFrequency real
);

CREATE TABLE organization_v2 (
  id serial primary key,
  balance datetime,
  industryType boolean,
  department bit,
  maritalStatus bigint,
  errorCode boolean,
  avatar int,
  dataSource geometry,
  expiryDate varchar,
  age point,
  jobTitle point,
  priority time,
  keywords boolean,
  dateFormat binary,
  completedAt geometry,
  employeeId bigint,
  likeCount timestamp,
  enrollmentDate tinyint,
  attemptCount float,
  education set,
  value set,
  exchangeRate smallint,
  accountNumber real,
  editedAt bit,
  lastSeenAt geometry,
  nickname set,
  orderId geometry,
  longitude varchar
);

CREATE TABLE fact_user (
  id serial primary key,
  maxLimit serial,
  metaDescription binary,
  channelId int,
  priority binary,
  bankAccount float,
  facilityId double
);

CREATE TABLE audit (
  id serial primary key,
  chatId boolean,
  isLocked binary,
  listId enum,
  authorId timestamp,
  nickname geometry,
  linkId real
);

CREATE TABLE vw_customer (
  id serial primary key,
  isDeleted blob,
  role date,
  ipAddress bit,
  colorCode blob,
  address time,
  clockIn decimal,
  layerId set
);

CREATE TABLE dimrecord (
  id serial primary key,
  unit set,
  moveId time,
  keyId decimal,
  cityName timestamp,
  formatType serial,
  latitude serial,
  category bigint,
  currency decimal,
  listingId serial,
  albumId serial,
  editedAt datetime,
  expiryDate tinyint,
  deletedAt datetime,
  documentId double,
  lockoutEnd double,
  instructorId varchar,
  validUntil float,
  group timestamp,
  entityId tinyint,
  isHidden time,
  likeCount time
);

CREATE TABLE tbl_order_div (
  id serial primary key,
  forwardTo float,
  age text,
  role mediumint,
  chatId geometry,
  completedAt bit,
  instructorId varchar,
  insertedAt set,
  isVerified geometry,
  coordinateY time,
  expiryYear tinyint,
  password double,
  flagged smallint,
  contactEmail timestamp,
  isAdmin real,
  creditCard datetime,
  enrollmentDate time,
  fromDate timestamp,
  keywords time,
  merchantId decimal,
  cartId blob,
  manufacturerId mediumint,
  layerId bit
);

CREATE TABLE tmporganization (
  id serial primary key,
  timezone enum,
  indexKey boolean,
  hashKey int,
  enrollmentDate boolean,
  grade text,
  lastLoginAt datetime,
  formatType datetime,
  category point,
  isBillable smallint,
  listingId boolean,
  customField1 date,
  minValue geometry,
  contactPhone smallint,
  dimension datetime,
  brandId bigint,
  dateFormat smallint,
  handlerId smallint,
  isVerified blob
);

CREATE TABLE factorganization (
  id serial primary key,
  lastName geometry,
  tags mediumint,
  importId int,
  birthDate date,
  group bit,
  labelText real,
  hostName enum,
  enabledAt varchar
);

CREATE TABLE config_legacy (
  id serial primary key,
  bookingDate int,
  coordinateY varchar,
  authorId set,
  folderPath mediumint,
  token varchar,
  creditCard boolean,
  balance smallint,
  billingFrequency geometry,
  modifiedAt blob
);

CREATE TABLE vw_company (
  id serial primary key,
  email geometry,
  displayName datetime,
  salary int,
  downloadCount enum,
  importId blob,
  shippingAddress varchar,
  minLimit tinyint,
  addressLine1 time,
  budgetCode real,
  batchId tinyint,
  createdAt timestamp,
  dimension float,
  creditScore float,
  totalAmount int,
  languageCode double,
  birthDate double,
  hostName time,
  employmentDate datetime,
  orderId datetime,
  moduleId text,
  chatId timestamp,
  accessLevel bigint,
  expiryYear point
);

CREATE TABLE src_product_legacy (
  id serial primary key,
  avatar point,
  uuid int,
  brandId int,
  productCode decimal,
  emailStatus binary,
  isActive tinyint,
  cancelReason int,
  configId bit,
  phone binary,
  completionRate time,
  currencyCode blob,
  claimId blob,
  token bigint,
  sku bit,
  chargeId decimal,
  street bit,
  browserType datetime,
  activeDevices int,
  amount text,
  hostName timestamp,
  description boolean,
  flagged tinyint
);

CREATE TABLE dstproductdata (
  id serial primary key,
  apiVersion datetime,
  email float,
  status decimal,
  customField2 double,
  employmentDate int,
  manufacturerId mediumint,
  meterNumber tinyint,
  referralCode binary,
  errorCode mediumint,
  amount blob,
  isVerified bigint,
  homePhone double,
  maskType timestamp,
  errorMessage binary,
  age float,
  facilityId blob,
  logLevel point,
  connectionString smallint,
  dealerId bit,
  orderId enum,
  contractId datetime,
  businessType boolean,
  title double,
  minLimit point
);

CREATE TABLE agg_account (
  id serial primary key,
  earnedPoints serial,
  deviceId datetime,
  dataSource serial,
  loginAttempts bit,
  fontFamily int,
  discountCode boolean,
  blogId int,
  claimId point,
  activeDevices enum,
  monthlyRate text,
  listId bigint
);

CREATE TABLE transaction (
  id serial primary key,
  foregroundColor point,
  sessionId decimal,
  incidentId time,
  licenseKey smallint,
  phone time,
  deviceToken int,
  jobTitle text,
  authorId decimal,
  labelText double,
  industryType set,
  fontSize float,
  headerImage text,
  age datetime,
  manufacturerId blob,
  fileSize time,
  createdAt timestamp,
  invoiceId varchar,
  costCenter varchar,
  state blob
);

CREATE TABLE account (
  id serial primary key,
  billingCycle binary,
  maxValue varchar,
  age boolean,
  gender boolean,
  isVerified decimal,
  colorCode real,
  country serial,
  dataSource decimal,
  abandonedCartId bigint,
  avatar mediumint,
  balance timestamp,
  endDate decimal,
  category bigint,
  completedAt float,
  createdAt bigint,
  enrollmentDate double,
  exportId set,
  attachmentUrl tinyint,
  foregroundColor text,
  deviceType date,
  gateId enum,
  inactiveAt time,
  licenseKey varchar,
  headerImage int,
  followCount text,
  hashKey boolean,
  minValue bit,
  group text,
  deliveryDate varchar
);

CREATE TABLE company_v2 (
  id serial primary key,
  name varchar,
  authMethod set,
  password float,
  configId timestamp,
  hostName boolean,
  clockIn bigint,
  deviceType tinyint,
  insuranceId blob,
  orderId mediumint,
  isDraft point,
  status geometry
);

CREATE TABLE src_record_v2 (
  id serial primary key,
  moveId double,
  group varchar,
  isArchived real,
  eventDate geometry,
  listId datetime,
  maritalStatus boolean
);

CREATE TABLE accountv1 (
  id serial primary key,
  deliveryDate time,
  apiKey tinyint,
  marketId set,
  totalAmount double,
  ipAddress int,
  accountType boolean,
  email datetime,
  certificateId float,
  startDate text,
  url smallint,
  errorMessage float,
  lastLoginAt decimal,
  meterNumber set,
  authToken mediumint,
  title boolean,
  distributorId double,
  description double,
  role text
);

CREATE TABLE product_log_legacy (
  id serial primary key,
  geoLocation binary,
  faxNumber boolean,
  instructorId set,
  monthlyRate double,
  status date,
  merchantId point,
  couponCode serial,
  copyRight point,
  menuId bigint,
  chatId tinyint,
  category set,
  employeeCode set,
  dashboardId tinyint,
  hiddenAt serial,
  customerGroup smallint,
  languageCode float,
  middleName date,
  phone timestamp,
  employmentDate int,
  dueDateAt blob,
  shippingAddress binary,
  minValue boolean,
  deactivatedAt bigint,
  nickname int
);

CREATE TABLE priv_config_new (
  id serial primary key,
  isDraft decimal,
  token time,
  mapId serial,
  floorNumber int,
  metaKeywords mediumint,
  apiVersion real,
  completedAt real,
  billingFrequency geometry,
  followCount point,
  contentType datetime,
  country smallint,
  fileSize date,
  actionType boolean,
  moduleId set,
  loginCount bit,
  enabledAt binary,
  shippingAddress bigint,
  itemCount point,
  expiryMonth smallint,
  hashKey float,
  documentId smallint,
  currency time,
  channelId enum,
  nickname tinyint,
  articleId point,
  dependentId decimal,
  coordinateX boolean,
  maxLimit double,
  handlerId smallint,
  albumId bigint
);

CREATE TABLE record (
  id serial primary key,
  orderStatus decimal,
  headerImage geometry,
  errorCode time,
  isDefault text,
  address timestamp,
  cityName enum,
  listingId text,
  loginAttempts set,
  longitude blob,
  size serial,
  instructorId binary,
  clockOut point,
  earnedPoints set
);

CREATE TABLE olk_record (
  id serial primary key,
  gender date,
  instructorId point,
  incidentId geometry,
  expiryDate mediumint
);

CREATE TABLE customerv2 (
  id serial primary key,
  token time,
  amount float,
  creditCard mediumint,
  completionRate mediumint,
  longitude geometry,
  flagged boolean,
  dialCode time,
  rating set,
  category datetime,
  menuId date,
  insertedAt varchar,
  moduleId boolean,
  layerId decimal,
  score geometry,
  defaultLang text,
  contentType smallint,
  duration point,
  signature date,
  paymentMethod date,
  emailStatus set,
  orderStatus datetime,
  domainName serial,
  cardNumber blob,
  isHidden float,
  maxValue timestamp,
  isVerified serial,
  emergencyContact time,
  coordinateY varchar,
  companyId int,
  updatedAt datetime
);

CREATE TABLE tmp_order_new (
  id serial primary key,
  taxRate serial,
  amount smallint,
  metaDescription enum,
  customField2 datetime,
  status varchar,
  iconPath set,
  department enum,
  metaTitle set,
  abandonedCartId varchar,
  id date,
  email tinyint,
  employeeId double,
  maxLimit tinyint,
  fileType enum,
  attachmentUrl bigint,
  quantity double,
  childId float,
  validUntil bit,
  authorId date,
  ipAddress int,
  sessionId int,
  forwardTo tinyint,
  enabledAt blob,
  mainImage enum,
  dashboardId date,
  maskType real,
  startDate bit,
  isDraft enum,
  avatar point
);

CREATE TABLE sysuser (
  id serial primary key,
  lastLoginAt double,
  activeDevices binary,
  paymentMethod text,
  group binary,
  id geometry,
  itemCount enum,
  postalCode mediumint,
  zipCode geometry,
  grade decimal,
  age binary,
  accountType smallint,
  comment enum,
  errorCode date,
  checkOutTime date,
  bankAccount decimal
);

CREATE TABLE sys_payment_log_v1 (
  id serial primary key,
  id double,
  audioUrl text,
  globalId bit,
  depositAmount mediumint,
  earnedPoints mediumint,
  albumId timestamp,
  isDeleted set,
  avatar bigint,
  amount smallint,
  role tinyint,
  gateId binary,
  accountType set,
  currencyCode geometry,
  balance point,
  chargeId set,
  houseNumber boolean,
  maxLimit serial,
  title double,
  mainImage text,
  backupEmail datetime,
  handlerId bit,
  monthlyRate int,
  companyName point,
  lastLoginAt enum,
  businessType date,
  authToken point,
  bookingDate blob,
  comment int,
  tags real
);

CREATE TABLE inventory (
  id serial primary key,
  authMethod enum,
  keyId timestamp,
  contactEmail mediumint,
  earnedPoints boolean,
  contractId point,
  fingerprint set,
  displayName point,
  importId serial,
  metaKeywords binary,
  id date,
  cancelReason timestamp
);

CREATE TABLE account (
  id serial primary key,
  ipAddress tinyint,
  metaKeywords time,
  itemCount timestamp,
  isRequired serial,
  type geometry,
  languageCode real,
  title bigint,
  authMethod decimal,
  id text
);

CREATE TABLE user (
  id serial primary key,
  updatedAt bit,
  expiryYear datetime,
  startDate bigint,
  homePhone binary,
  macAddress bit,
  value float,
  itemCount datetime,
  isEnabled serial,
  sessionId text,
  timezone date,
  managerId bigint
);

CREATE TABLE organization (
  id serial primary key,
  contactEmail real,
  faxNumber tinyint,
  marketId smallint,
  lastLoginAt varchar
);

CREATE TABLE product_temp (
  id serial primary key,
  audioUrl time,
  instructorId enum,
  homePhone point,
  hashKey mediumint,
  chargeId datetime,
  moveId varchar,
  activeDevices point,
  education real,
  middleName mediumint,
  group float,
  ipAddress serial,
  meterNumber smallint,
  hourlyRate double,
  gameId date,
  budgetCode decimal,
  dialCode point,
  deviceId geometry,
  grade bigint,
  paymentMethod bit,
  fileName double,
  companyId int,
  abandonedCartId enum,
  role blob,
  dueDateAt double
);

CREATE TABLE relaccount (
  id serial primary key,
  chargeId double,
  formatType binary,
  buildNumber tinyint,
  certificateId bigint
);

CREATE TABLE log_audit_data (
  id serial primary key,
  flagged real,
  keywords real,
  lastSeenAt binary,
  duration mediumint,
  companyId bit,
  departmentCode time,
  clockOut serial,
  dueDateAt boolean,
  displayName date,
  displayOrder enum,
  dialCode float,
  discount smallint,
  code point,
  apiVersion serial,
  score varchar,
  creditScore date,
  nickname tinyint,
  courseId double,
  checkOutTime timestamp,
  instructorId text,
  hashKey enum,
  houseNumber mediumint,
  addressLine1 datetime,
  fingerprint blob
);

CREATE TABLE src_transaction_log (
  id serial primary key,
  id boolean,
  gameId enum,
  completionRate bit,
  timezone blob
);

CREATE TABLE config (
  id serial primary key,
  completedAt enum,
  driverLicense datetime,
  paymentMethod double,
  description mediumint,
  mimeType boolean,
  comment decimal,
  avatar bigint,
  logLevel datetime,
  amount binary,
  latitude mediumint,
  loginAttempts date,
  defaultValue int,
  inactiveAt text,
  configId float,
  longitude enum,
  group blob,
  albumId set,
  score binary,
  cacheKey real,
  dailyLimit set,
  accountType int,
  listId float,
  gender tinyint,
  category boolean,
  isLocked double,
  employmentDate point,
  age boolean
);

CREATE TABLE log_product_v1 (
  id serial primary key,
  emailStatus float,
  driverLicense set,
  logLevel datetime,
  merchantId bit,
  childId blob,
  cityName decimal,
  discountCode serial,
  isActive point
);

CREATE TABLE ext_user_seg (
  id serial primary key,
  comment mediumint,
  lastSeenAt date,
  username set,
  category real,
  dailyLimit bit,
  expiryDate date,
  actionType varchar,
  insuranceId set,
  couponCode mediumint,
  metadata decimal,
  isActive timestamp,
  avatar blob,
  fileType time,
  creditScore double,
  loginAttempts float,
  followCount date,
  group double,
  flagged timestamp,
  errorMessage int,
  appVersion float,
  emailStatus geometry,
  middleName varchar,
  entityId datetime,
  downloadCount serial,
  bankAccount float,
  city bigint,
  domainName blob,
  status text,
  machineId decimal,
  isDraft text,
  businessType int
);

CREATE TABLE vw_product_div (
  id serial primary key,
  loadTime binary,
  contactName real,
  description float,
  feedbackId timestamp,
  authorId time,
  dealerId double,
  referralCode enum,
  errorCode smallint,
  companyName date,
  contactPhone geometry,
  countryCode double,
  employeeId decimal,
  type real,
  weight set,
  machineId date
);

CREATE TABLE payment (
  id serial primary key,
  iconPath text,
  dealerId time,
  deviceId bit,
  exchangeRate datetime,
  couponCode real,
  macAddress float,
  updatedAt bit,
  rating bit,
  companyId point,
  isVerified varchar,
  memberCount geometry,
  firstName binary,
  feedbackId float,
  dialCode set
);

CREATE TABLE order_legacy (
  id serial primary key,
  labelText boolean,
  handlerId smallint,
  analyticsId serial,
  phone boolean,
  avatar enum,
  loginAttempts bit,
  indexKey smallint,
  billingFrequency datetime,
  bannerImage smallint
);

CREATE TABLE product (
  id serial primary key,
  totalAmount double,
  state geometry,
  accountStatus binary,
  referralCode blob,
  isHidden int,
  id point,
  dailyLimit time,
  hourlyRate geometry,
  companyId timestamp,
  category serial,
  city datetime,
  status date,
  shippingAddress enum,
  exchangeRate smallint,
  mainImage serial,
  groupName time,
  coordinateX tinyint,
  loginAttempts mediumint,
  address boolean,
  departmentCode real
);

CREATE TABLE inventorytype (
  id serial primary key,
  configId double,
  latitude time,
  headerImage real,
  accountNumber tinyint,
  metaDescription real,
  accessLevel real,
  priority real,
  likeCount bit,
  country datetime,
  earnedPoints bigint,
  courseId real,
  lastSeenAt enum,
  description time,
  coordinateX float,
  chatId set,
  blogId bit,
  cardNumber smallint,
  adminNotes set,
  merchantId point,
  listingId bit,
  loginCount datetime,
  clockIn timestamp,
  actionType tinyint
);

CREATE TABLE user (
  id serial primary key,
  inactiveAt geometry,
  costCenter bigint,
  maritalStatus set,
  bluetoothId boolean,
  enrollmentDate boolean
);

CREATE TABLE record (
  id serial primary key,
  defaultLang serial,
  coverImage binary,
  accountType timestamp,
  dateFormat set,
  employmentDate float,
  instructorId float,
  appVersion boolean,
  zipCode int,
  minLimit serial,
  joinDate double,
  agentId bigint,
  quantity varchar,
  documentId datetime,
  dueDateAt smallint,
  cancelReason double,
  guestId time,
  frameRate mediumint,
  accessLevel int,
  editedAt tinyint,
  floorNumber time,
  deletedAt blob,
  phone datetime
);

CREATE TABLE refproduct (
  id serial primary key,
  discountCode mediumint,
  businessType text,
  minLimit float,
  lastSeenAt varchar,
  state binary,
  billingFrequency geometry,
  comment serial,
  education timestamp,
  quantity point,
  updatedAt tinyint,
  copyRight varchar,
  contactName text,
  completionRate geometry,
  email tinyint,
  cardNumber datetime,
  importId point,
  deactivatedAt tinyint,
  browserType int,
  coordinateX text,
  analyticsId boolean
);

CREATE TABLE dim_organization (
  id serial primary key,
  accountType varchar,
  referralCode bit,
  brandId point,
  balance binary,
  contentType enum,
  depositAmount binary,
  version smallint,
  forwardTo bit,
  batchId mediumint,
  moveId point,
  marketId mediumint,
  groupName decimal,
  discount timestamp
);

