CREATE TABLE srcinventory (
  id serial primary key,
  displayName boolean,
  couponCode enum,
  totalAmount tinyint,
  claimId decimal,
  adminNotes boolean,
  sessionId geometry,
  accountNumber boolean,
  type bit,
  dependentId smallint,
  blogId bigint
);

CREATE TABLE cpy_inventory (
  id serial primary key,
  isRequired double,
  type geometry,
  meterNumber bit,
  isDraft timestamp,
  facilityId tinyint,
  fileName decimal,
  email point,
  jobTitle serial,
  startDate smallint,
  likeCount varchar
);

CREATE TABLE ver_order (
  id serial primary key,
  creditCard blob,
  postalCode decimal,
  longitude bigint,
  billingFrequency bigint,
  expiryMonth set,
  isBillable time,
  hashKey tinyint,
  backupEmail int,
  attachmentUrl tinyint,
  locationId bit,
  zipCode int,
  name smallint,
  sessionId set,
  flagged datetime,
  group double,
  iconPath geometry,
  gateId point,
  currencyCode real,
  metaKeywords set,
  licenseKey set
);

CREATE TABLE organization_data (
  id serial primary key,
  errorMessage set,
  salary date,
  gateId blob,
  downloadCount serial,
  customerGroup date,
  addressLine1 enum,
  colorCode boolean
);

CREATE TABLE vw_record_out (
  id serial primary key,
  nickname enum,
  bluetoothId time,
  currency geometry,
  lastLoginAt tinyint,
  marketId enum,
  metaDescription set,
  inactiveAt date,
  id blob,
  orderStatus tinyint,
  customField2 smallint,
  keyId timestamp,
  enrollmentDate datetime,
  attachmentUrl binary,
  childId double,
  phone datetime,
  isDraft binary,
  backupEmail date,
  deviceId boolean,
  mapId datetime,
  content timestamp,
  messageId text,
  homePhone time,
  password real,
  zipCode date,
  token mediumint,
  postalCode mediumint,
  dateFormat enum,
  quantity float
);

CREATE TABLE organization_rel (
  id serial primary key,
  birthDate smallint,
  downloadCount int,
  certificateId serial
);

CREATE TABLE tmpcompanymap (
  id serial primary key,
  keywords bigint,
  cloudId double,
  metaDescription int,
  longitude geometry,
  dashboardId mediumint,
  attemptCount text,
  accessLevel bit,
  deactivatedAt text
);

CREATE TABLE inventory_new (
  id serial primary key,
  state serial,
  lastSeenAt real,
  comment time,
  avatar timestamp,
  insuranceId geometry,
  content real,
  apiVersion enum,
  mapId time,
  isAdmin binary,
  orderStatus blob,
  joinDate decimal,
  folderPath timestamp,
  accountNumber smallint,
  checkInTime set
);

CREATE TABLE company_out (
  id serial primary key,
  accessLevel real,
  agentId decimal,
  domainName point
);

CREATE TABLE customer (
  id serial primary key,
  blogId int,
  id int,
  orderStatus serial,
  companyLogo set,
  signature bit,
  agentId timestamp,
  education date,
  browserType serial,
  keyId int,
  downloadCount bigint,
  defaultValue binary,
  sessionId int,
  lastName bigint,
  expiryDate date,
  metadata int,
  fileSize double,
  exportId set,
  fontSize blob,
  accessLevel float,
  frameRate varchar,
  certificateId blob,
  isArchived decimal,
  coordinateY serial,
  isVerified point,
  age enum,
  password serial,
  actionType set,
  incidentId bigint,
  abandonedCartId smallint,
  endDate smallint,
  comment datetime
);

CREATE TABLE account (
  id serial primary key,
  documentId double,
  cardHolder point,
  cityName blob,
  emailStatus real,
  guestId set,
  friendId text,
  gameId serial,
  isPublic tinyint,
  creditCard timestamp,
  avatar time,
  creditScore int
);

CREATE TABLE vwconfigarchive (
  id serial primary key,
  dashboardId text,
  billingCycle text,
  chargeId tinyint,
  listId binary,
  customerId datetime,
  enrollmentDate int,
  colorCode timestamp,
  country boolean,
  isHidden int,
  licenseKey int,
  comment timestamp,
  chatId boolean,
  category int,
  entryPoint binary,
  exchangeRate time,
  expiryMonth decimal,
  deviceType date,
  fontSize geometry,
  groupName date,
  street double,
  handlerId blob,
  hashKey bigint,
  hiddenAt mediumint,
  departmentCode mediumint,
  timezone set,
  group blob,
  isEnabled bit,
  indexKey double
);

CREATE TABLE product (
  id serial primary key,
  bluetoothId binary,
  checkOutTime geometry,
  configId datetime,
  abandonedCartId enum,
  managerId int,
  logLevel double,
  cancelReason int,
  salary int,
  dialCode decimal,
  backupEmail tinyint,
  fontSize real,
  name int,
  lockoutEnd double,
  coordinateX timestamp,
  accountType text,
  hashKey binary,
  locationId serial,
  batchId geometry,
  companyName boolean,
  mapId mediumint,
  size point,
  followCount blob,
  address int,
  dashboardId geometry,
  fileType enum,
  faxNumber float,
  deviceId real
);

CREATE TABLE config (
  id serial primary key,
  favoriteCount varchar,
  contractId bigint,
  postalCode point,
  mapId int,
  contactName boolean,
  isDefault boolean,
  id time,
  insertedAt varchar,
  cacheKey bit,
  city time,
  isVerified time,
  cardHolder float,
  buildNumber set,
  companyId enum,
  meterNumber enum,
  grade float,
  exportId serial,
  description smallint,
  weight datetime,
  address tinyint,
  type datetime,
  extractId date,
  fileSize enum,
  clockIn bigint,
  accessLevel smallint,
  discount double,
  avatar date,
  incidentId bigint,
  homePhone date
);

CREATE TABLE company (
  id serial primary key,
  comment int,
  checkInTime timestamp,
  iconPath bigint,
  password real,
  currency set,
  instanceId double,
  longitude decimal,
  size date,
  machineId text,
  metadata time,
  fromDate bigint,
  activeDevices serial,
  completedAt smallint,
  isActive tinyint,
  referralCode varchar,
  agentId tinyint,
  balance geometry
);

CREATE TABLE payment_archive (
  id serial primary key,
  hourlyRate mediumint,
  fileHash serial,
  cancelReason time,
  labelText binary,
  startDate boolean,
  alertType point,
  mapId double,
  score time,
  displayName timestamp,
  dailyLimit varchar,
  city set,
  street tinyint,
  weight enum
);

CREATE TABLE product (
  id serial primary key,
  linkId double,
  id decimal,
  loadTime point
);

CREATE TABLE order_hist (
  id serial primary key,
  fileName geometry,
  flagged set,
  expiryYear enum,
  isPublic mediumint,
  domainName real,
  contentType smallint,
  merchantId tinyint,
  filterType set,
  gateId bigint,
  country blob,
  street real
);

CREATE TABLE user (
  id serial primary key,
  attemptCount bigint,
  macAddress bit,
  contentType smallint,
  createdAt varchar,
  emergencyContact text,
  creditLimit date,
  authToken smallint,
  age bit,
  authorId bigint,
  industryType double,
  isSystem decimal,
  likeCount bigint,
  metadata datetime,
  levelId bigint,
  isRequired float,
  logLevel tinyint,
  billingCycle serial,
  value tinyint,
  isLocked tinyint,
  firmwareVersion enum,
  eventDate bigint,
  claimId geometry,
  phone mediumint,
  timezone decimal,
  bannerImage real,
  avatar decimal,
  firstName float,
  hourlyRate geometry,
  minValue geometry,
  taxRate datetime,
  budgetCode smallint
);

CREATE TABLE config_2025 (
  id serial primary key,
  importId float,
  dailyLimit double,
  colorCode enum,
  lastLoginAt float,
  maxLimit double,
  paymentMethod datetime,
  errorCode timestamp,
  likeCount date,
  deactivatedAt varchar,
  dashboardId float,
  listId varchar,
  currency boolean,
  apiVersion decimal,
  accountNumber double,
  groupName double,
  instanceId mediumint,
  frameRate bit,
  friendId bigint,
  creditCard real,
  gameId enum,
  gender geometry,
  age bit,
  machineId timestamp,
  phone text,
  countryCode tinyint,
  dimension smallint,
  keyId time,
  weight boolean
);

CREATE TABLE core_account (
  id serial primary key,
  mobileNumber enum,
  companyName boolean,
  licenseKey bit,
  longitude timestamp,
  defaultLang binary,
  gateId mediumint,
  exportId datetime,
  favoriteCount varchar,
  isLocked bit,
  apiKey smallint,
  homePhone mediumint,
  cancelReason geometry,
  editedAt double,
  earnedPoints binary,
  downloadCount geometry,
  jobTitle geometry,
  role datetime,
  distributorId int
);

CREATE TABLE recordseg (
  id serial primary key,
  duration serial,
  connectionString serial,
  emailStatus mediumint,
  postalCode enum,
  size int,
  uuid tinyint,
  logLevel timestamp,
  dueDateAt geometry,
  value int,
  billingCycle tinyint,
  listId timestamp,
  city tinyint,
  title bit,
  balance double,
  orderStatus serial,
  clockOut bigint,
  minValue boolean,
  expiryMonth datetime,
  folderPath set,
  contactEmail geometry,
  defaultLang bigint,
  domainName real,
  birthDate boolean,
  fileName tinyint,
  frameRate mediumint,
  filterType binary,
  minLimit mediumint,
  displayOrder mediumint
);

CREATE TABLE inventory (
  id serial primary key,
  locationId varchar,
  emailStatus time,
  completedAt smallint,
  listingId boolean,
  itemCount decimal,
  orderId real,
  cvv real,
  handlerId set,
  id mediumint
);

CREATE TABLE tblpayment (
  id serial primary key,
  houseNumber enum,
  eventDate double,
  costCenter timestamp,
  city boolean,
  machineId decimal,
  adminNotes bit,
  locationId double,
  zipCode timestamp,
  accountType float,
  fileName datetime,
  comment datetime,
  currency time,
  editedAt real,
  longitude varchar,
  manufacturerId tinyint,
  departmentCode time,
  updatedAt enum,
  errorMessage time,
  startDate smallint,
  iconPath double,
  status double,
  firstName geometry,
  isAdmin datetime,
  shippingAddress real
);

CREATE TABLE tmpauditrel (
  id serial primary key,
  companyId serial,
  metaDescription text,
  isDeleted int,
  isRequired bigint,
  password decimal,
  completedAt decimal,
  startDate time,
  chargeId boolean,
  macAddress timestamp,
  buildNumber date,
  geoLocation serial,
  isSystem tinyint,
  errorMessage varchar,
  employmentDate bit,
  gateId tinyint,
  amount blob,
  fileName time,
  facilityId tinyint,
  discountCode tinyint,
  country serial,
  depositAmount bit,
  isDraft int,
  alertType serial,
  coordinateX point,
  longitude geometry
);

CREATE TABLE stg_transaction (
  id serial primary key,
  flagged double,
  isArchived set,
  createdAt binary,
  modifiedAt text,
  username datetime,
  enabledAt tinyint,
  marketId float,
  bookingDate varchar,
  insuranceId timestamp,
  feedbackId datetime,
  customerId text,
  lastName enum,
  dialCode smallint,
  employeeId int,
  editedAt bit,
  contactName timestamp,
  code float
);

CREATE TABLE payment_notifications (
  id serial primary key,
  houseNumber float,
  updatedAt blob,
  maxLimit varchar,
  status date,
  connectionString boolean,
  layerId serial,
  cityName float,
  errorCode text,
  password point,
  group datetime,
  cardHolder datetime,
  inactiveAt serial,
  isPublic bit,
  lockoutEnd boolean,
  mapId real,
  companyLogo bigint,
  expiryMonth int
);

CREATE TABLE payment (
  id serial primary key,
  joinDate timestamp,
  deletedAt mediumint,
  insuranceId point,
  likeCount boolean,
  address datetime,
  actionType mediumint,
  copyRight date,
  group timestamp,
  isAdmin serial,
  isArchived boolean,
  expiryDate text,
  geoLocation decimal,
  unit boolean,
  managerId smallint
);

CREATE TABLE rel_config (
  id serial primary key,
  accountNumber double,
  dialCode datetime,
  bookingDate bit,
  attachmentUrl real,
  id bit,
  longitude timestamp,
  endDate enum,
  gender binary,
  loadTime decimal,
  fontFamily tinyint,
  languageCode mediumint,
  checkInTime bigint,
  height bigint,
  name serial,
  dashboardId varchar,
  balance set,
  displayOrder time,
  configId decimal,
  fontSize tinyint,
  importId mediumint,
  weight mediumint,
  businessType mediumint,
  amount point,
  tags blob
);

CREATE TABLE product (
  id serial primary key,
  flagged binary,
  contactEmail tinyint,
  exchangeRate timestamp
);

CREATE TABLE transaction_meta (
  id serial primary key,
  labelText decimal,
  floorNumber int,
  comment mediumint,
  enabledAt int,
  dimension timestamp,
  cacheKey datetime,
  emailStatus real,
  duration mediumint,
  title bit,
  group date,
  countryCode blob,
  expiryDate enum,
  itemCount geometry,
  accountNumber tinyint
);

CREATE TABLE ext_account_rel (
  id serial primary key,
  expiryYear bigint,
  dataSource timestamp,
  insertedAt int,
  mainImage blob,
  depositAmount varchar,
  lockoutEnd decimal,
  appVersion blob,
  deviceId serial,
  globalId decimal,
  homePhone timestamp,
  floorNumber float,
  weight timestamp,
  joinDate serial,
  birthDate geometry,
  couponCode int,
  customField2 set,
  education serial,
  orderStatus enum,
  cvv time,
  attemptCount enum,
  dialCode datetime,
  totalAmount datetime
);

CREATE TABLE account (
  id serial primary key,
  rating binary,
  minLimit varchar,
  category text
);

CREATE TABLE organization (
  id serial primary key,
  costCenter float,
  maritalStatus real,
  accessLevel smallint,
  paymentMethod decimal,
  browserType date,
  nickname float,
  formatType date,
  isAdmin text,
  phone int,
  extractId varchar,
  albumId text,
  mainImage bit,
  ipAddress double,
  emergencyContact time,
  companyId binary,
  url text,
  hostName set,
  value timestamp,
  integrationId int,
  favoriteCount boolean,
  foregroundColor double,
  colorCode bit,
  courseId decimal,
  creditScore real,
  lastLoginAt bigint,
  isVerified float
);

CREATE TABLE organization_out_2025 (
  id serial primary key,
  enabledAt blob,
  category timestamp,
  coordinateX datetime,
  certificateId point,
  moduleId mediumint,
  languageCode tinyint,
  billingCycle date,
  hostName text,
  dateFormat tinyint,
  age datetime,
  comment mediumint,
  invoiceId geometry,
  deviceType datetime,
  address timestamp,
  education point,
  contactEmail binary,
  faxNumber serial,
  businessType geometry,
  metaDescription decimal,
  metaKeywords tinyint,
  fontSize boolean,
  countryCode enum,
  attachmentUrl geometry,
  avatar set,
  discountCode enum,
  duration timestamp,
  gender date,
  metaTitle mediumint,
  customerId datetime,
  audioUrl double,
  checkInTime double
);

CREATE TABLE audit (
  id serial primary key,
  mapId serial,
  likeCount smallint,
  comment tinyint,
  keyId date,
  state decimal,
  chargeId date,
  postalCode timestamp,
  deviceToken date,
  albumId date,
  abandonedCartId enum,
  bluetoothId text,
  loginAttempts date,
  geoLocation timestamp,
  connectionString boolean,
  browserType smallint,
  deviceId datetime,
  feedbackId smallint,
  title decimal,
  contactPhone date,
  groupName serial,
  dimension double,
  filterType bigint,
  distributorId set,
  hostName text,
  manufacturerId enum,
  meterNumber double,
  isSystem bigint,
  contactName mediumint
);

CREATE TABLE account (
  id serial primary key,
  dateFormat boolean,
  employeeCode enum,
  extractId double,
  contactName geometry,
  formatType datetime,
  appVersion binary,
  geoLocation varchar,
  companyLogo set,
  apiVersion float,
  coordinateY enum,
  exportId double,
  completedAt double,
  url float,
  group point,
  salary text
);

CREATE TABLE account (
  id serial primary key,
  incidentId blob,
  inactiveAt text,
  clockOut real,
  minLimit time,
  maritalStatus blob,
  driverLicense enum,
  audioUrl bigint,
  firstName bit,
  accessLevel tinyint,
  score date,
  authMethod mediumint,
  dateFormat serial,
  linkId bigint,
  group mediumint,
  minValue serial,
  feedbackId boolean,
  street set,
  budgetCode date,
  metaTitle smallint,
  analyticsId smallint,
  nickname smallint,
  attachmentUrl boolean,
  countryCode binary,
  campaignId binary,
  fileType time,
  expiryMonth varchar
);

CREATE TABLE productmapv1 (
  id serial primary key,
  checkOutTime varchar,
  metaKeywords tinyint,
  likeCount decimal,
  latitude bit,
  appVersion float,
  orderId datetime,
  flagged varchar,
  gateId datetime,
  type boolean,
  indexKey set,
  maritalStatus bit,
  linkId binary,
  taxRate smallint,
  title smallint
);

CREATE TABLE priv_organization (
  id serial primary key,
  isPublic set,
  customerGroup datetime,
  formatType bit,
  email enum,
  downloadCount timestamp,
  iconPath float,
  dimension date,
  businessType bigint,
  departmentCode point,
  copyRight point,
  abandonedCartId bit,
  bluetoothId bit,
  couponCode mediumint,
  deviceToken enum,
  status double,
  productCode serial,
  discount date,
  entityId boolean,
  levelId smallint,
  floorNumber point,
  dashboardId bigint,
  attemptCount tinyint
);

CREATE TABLE vw_account_legacy (
  id serial primary key,
  amount double,
  mobileNumber varchar,
  type varchar,
  levelId decimal,
  longitude smallint,
  languageCode smallint,
  url time,
  customField2 enum,
  country serial,
  addressLine1 geometry,
  macAddress timestamp,
  timezone date,
  entryPoint time,
  distributorId real,
  phone enum,
  contentType time,
  employmentDate point,
  eventDate text,
  apiVersion datetime,
  metaKeywords time,
  avatar bit,
  password int,
  salary timestamp,
  meterNumber geometry,
  homePhone double,
  chatId tinyint,
  orderId int,
  address time,
  tags real,
  importId text
);

CREATE TABLE order_v1 (
  id serial primary key,
  authMethod set,
  contactEmail bit,
  dashboardId real,
  city tinyint,
  sku text,
  bannerImage text,
  lastLoginAt decimal,
  checkOutTime point,
  score bigint,
  friendId timestamp,
  enabledAt set,
  formatType blob,
  dialCode varchar
);

CREATE TABLE dst_transaction_extra (
  id serial primary key,
  address mediumint,
  age float,
  completedAt time,
  facilityId float,
  appVersion datetime,
  labelText blob,
  dialCode geometry,
  moduleId enum,
  height mediumint,
  lockoutEnd datetime
);

CREATE TABLE dim_record_v1 (
  id serial primary key,
  paymentMethod boolean,
  machineId point,
  updatedAt set,
  billingCycle enum,
  postalCode boolean,
  category blob,
  employeeId double,
  enrollmentDate point,
  integrationId binary,
  createdAt bigint,
  albumId date,
  monthlyRate bigint,
  courseId timestamp,
  amount point,
  instructorId enum,
  chargeId double,
  fromDate mediumint,
  status decimal,
  joinDate varchar,
  backupEmail binary,
  menuId text,
  clientId text
);

CREATE TABLE company (
  id serial primary key,
  completionRate int,
  frameRate set,
  age double,
  earnedPoints serial,
  department decimal
);

CREATE TABLE record (
  id serial primary key,
  claimId varchar,
  url blob,
  password mediumint,
  cardNumber datetime,
  dataSource timestamp,
  enrollmentDate mediumint,
  deletedAt timestamp,
  integrationId geometry,
  distributorId boolean,
  sku date,
  salary bigint,
  price text,
  exchangeRate datetime,
  accountStatus mediumint,
  fromDate varchar,
  productCode tinyint,
  createdAt timestamp,
  category double,
  firstName time,
  documentId blob,
  algorithm geometry,
  endPoint boolean,
  insertedAt tinyint
);

CREATE TABLE companytype (
  id serial primary key,
  deliveryDate text,
  zipCode date,
  brandId geometry,
  dataSource set
);

CREATE TABLE company (
  id serial primary key,
  addressLine1 blob,
  couponCode double,
  customerGroup smallint,
  longitude float,
  geoLocation set,
  metaDescription time,
  chargeId point,
  faxNumber float,
  contactEmail date,
  createdAt enum,
  countryCode timestamp,
  cartId geometry,
  avatar boolean,
  claimId set,
  isSystem timestamp,
  group decimal
);

CREATE TABLE ref_product_div (
  id serial primary key,
  category serial,
  employeeId real,
  incidentId timestamp,
  enrollmentDate time,
  postalCode int,
  paymentMethod blob,
  fileType geometry,
  middleName bit,
  campaignId binary,
  actionType double,
  emergencyContact boolean,
  duration smallint,
  isSystem geometry,
  name float,
  favoriteCount binary,
  country int,
  isDefault bit,
  dealerId point
);

CREATE TABLE payment (
  id serial primary key,
  audioUrl double,
  id set,
  connectionString varchar,
  cartId int,
  status date,
  chatId float,
  mimeType tinyint,
  enrollmentDate timestamp
);

