CREATE TABLE agg_user_legacy (
  id serial primary key,
  customerId int,
  isPublic tinyint,
  avatar double,
  completedAt boolean,
  favoriteCount bit,
  deactivatedAt bigint,
  nickname boolean,
  signature geometry,
  productCode serial,
  accessLevel binary,
  awardDate decimal,
  middleName bit,
  loadTime date,
  size decimal,
  campaignId time,
  maxLimit float,
  defaultValue bigint,
  distributorId tinyint,
  dueDateAt blob,
  facilityId date,
  thumbnail text,
  manufacturerId set,
  bannerImage serial,
  licenseKey smallint,
  accountType blob,
  version double,
  education serial,
  zipCode tinyint,
  expiryDate varchar
);

CREATE TABLE customer_2025 (
  id serial primary key,
  companyLogo mediumint,
  productCode real
);

CREATE TABLE tmp_record_status_new (
  id serial primary key,
  levelId bit,
  earnedPoints geometry,
  cardHolder point,
  keywords bigint,
  foregroundColor bigint,
  browserType binary,
  employeeId timestamp,
  merchantId blob,
  mapId bigint
);

CREATE TABLE user (
  id serial primary key,
  hashKey binary,
  title smallint,
  isVerified bit,
  paymentMethod tinyint,
  addressLine1 point,
  mapId binary,
  moveId decimal,
  emailStatus datetime,
  hiddenAt smallint,
  earnedPoints boolean,
  employeeId bigint,
  displayName point,
  expiryDate date,
  phone boolean,
  blogId set,
  logLevel serial,
  fileType decimal,
  role timestamp,
  password boolean,
  orderStatus real,
  mainImage blob,
  domainName bit,
  orderId blob,
  businessType bigint,
  avatar int,
  id geometry
);

CREATE TABLE audit_seg (
  id serial primary key,
  avatar boolean,
  memberCount smallint,
  isEnabled binary,
  levelId real,
  timezone smallint,
  businessType smallint,
  menuId serial,
  folderPath point,
  moveId varchar,
  coverImage float,
  merchantId point,
  content int,
  bannerImage bigint,
  metaDescription decimal,
  customerGroup geometry,
  taxRate blob,
  globalId serial,
  mimeType boolean,
  createdAt double,
  sku set,
  category real,
  state binary,
  agentId geometry,
  loginAttempts datetime,
  isHidden binary
);

CREATE TABLE tmporganization (
  id serial primary key,
  labelText decimal,
  copyRight int,
  cancelReason smallint,
  lastSeenAt geometry,
  authToken geometry,
  category real
);

CREATE TABLE cpy_transaction (
  id serial primary key,
  ipAddress boolean,
  adminNotes timestamp,
  metaKeywords set,
  joinDate timestamp,
  languageCode smallint,
  orderStatus smallint,
  integrationId enum,
  logLevel time,
  handlerId real,
  dependentId double,
  completedAt smallint,
  companyLogo double,
  username int,
  isLocked bigint,
  mimeType tinyint,
  startDate boolean,
  totalAmount boolean,
  entryPoint set,
  channelId tinyint,
  coordinateY tinyint,
  expiryDate serial,
  customField1 serial,
  creditCard bit,
  insertedAt decimal
);

CREATE TABLE olk_user_seg (
  id serial primary key,
  size blob,
  couponCode point,
  contentType datetime,
  department decimal,
  endDate bigint,
  isSystem bigint,
  accountType set,
  creditLimit bit,
  authMethod varchar,
  defaultValue mediumint,
  addressLine2 set,
  gateId set,
  code geometry,
  password set,
  insuranceId int,
  description time,
  category boolean,
  nickname binary,
  clientId int,
  score time,
  role blob,
  coverImage boolean,
  price int,
  editedAt float,
  title varchar,
  companyLogo mediumint,
  instructorId binary,
  completedAt float,
  instanceId real,
  keyId varchar
);

CREATE TABLE customer (
  id serial primary key,
  machineId float,
  loadTime mediumint,
  url binary,
  creditLimit float,
  levelId point,
  id bigint,
  attachmentUrl serial,
  fingerprint boolean,
  memberCount varchar,
  expiryYear set,
  costCenter decimal,
  frameRate int
);

CREATE TABLE record (
  id serial primary key,
  gameId varchar,
  groupName set
);

CREATE TABLE tmp_transaction (
  id serial primary key,
  billingFrequency bit,
  duration date,
  country boolean,
  employmentDate real,
  locationId blob,
  manufacturerId set,
  priority date,
  fileHash time,
  completedAt double,
  isAdmin decimal,
  contactName time
);

CREATE TABLE extaccount (
  id serial primary key,
  copyRight boolean,
  comment blob,
  discountCode bigint,
  extractId datetime
);

CREATE TABLE app_payment (
  id serial primary key,
  driverLicense point,
  paymentMethod geometry,
  loginAttempts boolean,
  alertType set,
  browserType float,
  referralCode date,
  dependentId binary,
  username tinyint
);

CREATE TABLE app_product_rel (
  id serial primary key,
  fontSize boolean,
  createdAt tinyint,
  fileType geometry,
  group binary,
  referralCode geometry,
  manufacturerId blob,
  campaignId blob,
  guestId date,
  education double,
  password blob,
  isAdmin bigint,
  menuId serial,
  enabledAt boolean,
  driverLicense binary,
  monthlyRate decimal,
  cardHolder mediumint,
  browserType bigint,
  balance bit,
  cardNumber decimal,
  contractId enum,
  phone enum,
  creditScore double,
  displayName time,
  courseId blob,
  entryPoint serial,
  appVersion geometry,
  licenseKey tinyint,
  abandonedCartId geometry,
  type real,
  maxValue boolean
);

CREATE TABLE refconfig (
  id serial primary key,
  manufacturerId mediumint,
  businessType bit,
  birthDate binary,
  taxRate geometry,
  isAdmin varchar,
  lastName tinyint,
  startDate blob,
  feedId serial,
  priority date,
  content float,
  clockIn text,
  accountNumber real,
  modifiedAt set,
  completedAt timestamp,
  url bigint,
  creditScore bigint,
  blogId date,
  certificateId tinyint,
  claimId mediumint
);

CREATE TABLE company (
  id serial primary key,
  indexKey text,
  fingerprint set,
  customerId bigint,
  orderStatus float,
  industryType int,
  currency enum,
  companyName blob,
  coordinateX timestamp,
  managerId time,
  connectionString enum,
  isBillable real,
  id tinyint,
  creditScore geometry,
  gender geometry,
  address serial,
  machineId varchar,
  tags mediumint,
  version datetime,
  countryCode blob,
  accountType set,
  customField2 bigint,
  lastName datetime,
  attachmentUrl serial,
  description bigint,
  inactiveAt enum,
  colorCode date,
  amount real,
  category decimal,
  chatId serial,
  appVersion enum
);

CREATE TABLE audit_seg_v2 (
  id serial primary key,
  certificateId mediumint,
  coordinateX tinyint,
  shippingAddress text,
  integrationId varchar
);

CREATE TABLE stg_user_status_v1 (
  id serial primary key,
  ipAddress mediumint,
  accountStatus varchar,
  incidentId geometry,
  countryCode bigint,
  configId point,
  childId tinyint,
  departmentCode double,
  contactName tinyint,
  completedAt smallint,
  contactPhone datetime,
  colorCode tinyint,
  grade bit,
  defaultLang enum,
  checkInTime double,
  sessionId real,
  orderStatus enum,
  bankAccount bit,
  category date,
  timezone bit,
  accountType point,
  employeeCode date,
  dependentId binary,
  layerId set,
  role blob,
  errorMessage geometry,
  loginAttempts text
);

CREATE TABLE veruser (
  id serial primary key,
  forwardTo tinyint,
  orderStatus enum,
  creditLimit binary,
  thumbnail text,
  address int,
  creditCard int,
  fromDate boolean,
  clientId double,
  albumId smallint,
  grade float,
  languageCode serial
);

CREATE TABLE fact_product (
  id serial primary key,
  sku time,
  nickname time,
  totalAmount set,
  gateId time,
  folderPath date,
  group text,
  authToken serial,
  dealerId date,
  category text,
  machineId boolean,
  cancelReason blob,
  actionType float,
  addressLine2 set,
  status text,
  bankAccount smallint,
  agentId text,
  industryType binary,
  cartId binary,
  enabledAt enum,
  clientId point,
  discountCode boolean,
  earnedPoints bit,
  coordinateY smallint,
  mapId bit,
  isEnabled point,
  dependentId timestamp
);

CREATE TABLE apporder (
  id serial primary key,
  employeeCode bit,
  expiryYear point,
  amount varchar,
  isDraft time,
  dialCode timestamp,
  earnedPoints geometry,
  creditCard boolean,
  firmwareVersion timestamp,
  audioUrl binary,
  localeId varchar,
  formatType tinyint,
  metaKeywords datetime,
  birthDate date
);

CREATE TABLE account_2024 (
  id serial primary key,
  connectionString text,
  firmwareVersion time,
  machineId time,
  createdAt float,
  deviceId int,
  employeeCode tinyint,
  labelText tinyint,
  loginAttempts binary,
  tags double,
  balance bit,
  headerImage date,
  type set,
  instructorId decimal,
  latitude timestamp,
  keywords smallint,
  creditScore mediumint,
  addressLine2 date,
  isDefault varchar,
  floorNumber boolean,
  companyLogo geometry,
  accountType geometry,
  size varchar,
  orderStatus timestamp,
  feedbackId float,
  insuranceId binary,
  isAdmin double,
  guestId decimal,
  fromDate mediumint,
  costCenter timestamp,
  likeCount boolean,
  category decimal
);

CREATE TABLE olk_product_v1 (
  id serial primary key,
  age binary,
  globalId geometry,
  deletedAt timestamp,
  maritalStatus datetime,
  earnedPoints date,
  dealerId varchar,
  errorMessage set,
  cardHolder geometry,
  fileSize datetime,
  audioUrl serial
);

CREATE TABLE tmp_account_map (
  id serial primary key,
  houseNumber mediumint,
  status blob,
  address binary
);

CREATE TABLE user_v2 (
  id serial primary key,
  monthlyRate blob,
  latitude decimal,
  expiryYear set,
  cvv date,
  title timestamp,
  billingCycle float,
  locationId varchar,
  isFeatured float,
  incidentId bit,
  cityName text,
  cardNumber real,
  modifiedAt binary,
  maxValue int
);

CREATE TABLE refaccount (
  id serial primary key,
  customerGroup decimal,
  firstName geometry,
  createdAt point,
  insuranceId tinyint,
  taxRate bigint,
  street blob,
  token blob,
  coordinateY int,
  maskType set,
  actionType real,
  coordinateX time,
  cardHolder geometry,
  loginCount serial,
  id varchar,
  displayOrder bigint,
  accessLevel real,
  managerId binary,
  indexKey date,
  dimension serial,
  checkInTime mediumint
);

CREATE TABLE audit (
  id serial primary key,
  iconPath varchar,
  rating serial,
  managerId bigint,
  entityId time,
  phone timestamp,
  contentType decimal,
  street float,
  creditScore tinyint
);

CREATE TABLE dim_organization (
  id serial primary key,
  claimId decimal,
  courseId date,
  keywords varchar,
  fontSize datetime,
  email text,
  cvv date,
  group geometry,
  handlerId double,
  isArchived float,
  entityId text,
  maxLimit varchar,
  accountType time,
  hostName set,
  deliveryDate blob,
  id serial,
  middleName int,
  lockoutEnd int,
  enabledAt date,
  exportId datetime,
  actionType date,
  maxValue real,
  jobTitle int,
  feedbackId real
);

CREATE TABLE refinventorydiv (
  id serial primary key,
  insertedAt bit,
  middleName date,
  validUntil real,
  isActive double,
  abandonedCartId double,
  creditLimit decimal,
  insuranceId tinyint,
  machineId timestamp,
  businessType smallint,
  instanceId enum
);

CREATE TABLE inventorylog (
  id serial primary key,
  companyLogo datetime,
  layerId serial,
  expiryDate bigint,
  contactName tinyint,
  dependentId smallint,
  dailyLimit point,
  itemCount binary,
  industryType varchar,
  state enum,
  groupName boolean,
  emergencyContact bigint,
  filterType varchar,
  hiddenAt point,
  levelId date,
  rating int,
  comment smallint
);

CREATE TABLE company (
  id serial primary key,
  copyRight double,
  documentId time,
  birthDate float,
  education binary,
  deliveryDate serial,
  employeeId float,
  longitude decimal,
  modifiedAt float,
  creditLimit decimal,
  mainImage date,
  validUntil serial,
  score timestamp,
  middleName float,
  sessionId int,
  cityName geometry,
  phone varchar,
  frameRate enum,
  group point,
  attachmentUrl date,
  apiKey mediumint,
  macAddress bigint,
  creditCard tinyint,
  algorithm time,
  merchantId date,
  discountCode enum,
  articleId smallint,
  avatar varchar
);

CREATE TABLE stgauditout (
  id serial primary key,
  modifiedAt timestamp,
  validUntil serial,
  favoriteCount set,
  feedId float,
  email real,
  jobTitle real,
  coverImage bit
);

CREATE TABLE inventory (
  id serial primary key,
  deviceType int,
  lockoutEnd bit,
  completionRate double,
  expiryMonth boolean,
  couponCode decimal,
  isFeatured serial,
  orderId decimal,
  createdAt varchar,
  bluetoothId geometry,
  dialCode real,
  formatType decimal,
  phone binary,
  eventDate bigint,
  cardNumber varchar,
  deliveryDate geometry,
  indexKey boolean
);

CREATE TABLE rel_account_2025 (
  id serial primary key,
  lastName datetime,
  gameId bit,
  expiryYear blob,
  linkId bit,
  maskType point,
  moveId geometry,
  address double,
  contactEmail mediumint,
  customField2 enum,
  accountNumber set,
  status real,
  dimension decimal,
  depositAmount text,
  foregroundColor serial,
  courseId decimal,
  postalCode bigint,
  firstName smallint,
  street double,
  minValue boolean,
  hourlyRate set,
  endPoint bit,
  metaTitle float,
  deletedAt varchar,
  agentId timestamp,
  hostName point,
  audioUrl bigint,
  deviceToken int,
  paymentMethod binary,
  dataSource mediumint,
  age blob,
  zipCode binary
);

CREATE TABLE inventory_div_temp (
  id serial primary key,
  messageId bigint,
  couponCode bigint,
  totalAmount datetime,
  metaTitle bigint,
  timezone timestamp,
  group timestamp,
  minLimit geometry,
  floorNumber bigint,
  password serial,
  customerGroup blob,
  dueDateAt timestamp,
  itemCount time,
  joinDate serial,
  unit geometry,
  displayOrder bigint,
  dataSource float,
  dimension blob,
  deactivatedAt bit,
  handlerId int,
  avatar geometry,
  gateId float,
  updatedAt point,
  homePhone datetime
);

CREATE TABLE audit (
  id serial primary key,
  addressLine1 int,
  weight datetime,
  metaTitle decimal,
  longitude varchar,
  companyId date,
  algorithm timestamp,
  middleName smallint,
  errorCode binary,
  managerId bigint,
  city enum,
  lastSeenAt smallint,
  isArchived bigint,
  entryPoint float,
  avatar bigint,
  category geometry,
  isLocked text,
  discount int,
  password geometry,
  entityId point
);

CREATE TABLE agg_config (
  id serial primary key,
  uuid binary,
  phone serial
);

CREATE TABLE record (
  id serial primary key,
  username timestamp,
  instructorId time,
  authMethod set,
  cardNumber set,
  chatId blob,
  isSystem binary,
  mainImage datetime,
  machineId set,
  followCount tinyint,
  address datetime,
  hostName geometry,
  accountType blob,
  coordinateY float,
  blogId int,
  contentType text,
  isActive text,
  description int,
  clockOut set,
  firstName int,
  creditLimit double,
  employmentDate double,
  handlerId bigint,
  groupName binary,
  apiVersion bit,
  taxRate enum,
  deviceToken point,
  cancelReason datetime
);

CREATE TABLE inventory_type (
  id serial primary key,
  latitude set,
  buildNumber decimal,
  deliveryDate decimal,
  timezone enum,
  isBillable tinyint,
  completedAt int,
  ipAddress varchar,
  employmentDate double,
  thumbnail mediumint,
  formatType int
);

CREATE TABLE stg_user (
  id serial primary key,
  isEnabled float,
  comment geometry,
  status text,
  eventDate boolean,
  hostName blob,
  name bigint,
  expiryDate timestamp,
  loadTime smallint,
  timezone datetime,
  monthlyRate int,
  city blob,
  currencyCode smallint,
  department boolean,
  entityId tinyint,
  balance decimal,
  certificateId text
);

CREATE TABLE inventory (
  id serial primary key,
  awardDate point,
  metaTitle double,
  companyId int,
  bookingDate tinyint,
  clockIn int,
  username binary,
  isDeleted binary,
  deviceId time,
  fileName binary,
  category varchar,
  emergencyContact tinyint,
  abandonedCartId blob,
  layerId enum,
  score real,
  cardHolder float,
  validUntil decimal,
  campaignId boolean,
  integrationId tinyint,
  sku date,
  comment int,
  incidentId tinyint,
  dashboardId binary,
  labelText decimal,
  dependentId set,
  managerId decimal,
  middleName smallint,
  country datetime,
  modifiedAt bigint
);

CREATE TABLE config (
  id serial primary key,
  companyName mediumint,
  customField2 smallint,
  moveId date,
  firmwareVersion tinyint,
  dependentId blob,
  levelId double,
  accessLevel int,
  isActive varchar,
  country text,
  lastName text,
  username smallint,
  discountCode varchar,
  jobTitle geometry,
  orderStatus geometry,
  description point,
  labelText real,
  filterType varchar,
  clockIn float,
  quantity binary,
  apiKey geometry,
  maxValue float,
  age boolean,
  sessionId smallint,
  paymentMethod date,
  departmentCode timestamp,
  invoiceId text,
  colorCode enum
);

CREATE TABLE config (
  id serial primary key,
  levelId tinyint,
  value blob,
  size blob,
  adminNotes enum,
  group binary,
  uuid text,
  maxValue text,
  channelId timestamp,
  weight point
);

CREATE TABLE inventory (
  id serial primary key,
  productCode real,
  creditCard geometry,
  entityId blob,
  discount blob,
  fileSize point,
  signature binary,
  keyId geometry,
  salary mediumint,
  updatedAt mediumint,
  analyticsId float,
  mimeType point
);

CREATE TABLE customer (
  id serial primary key,
  mobileNumber bigint,
  isDraft binary,
  department binary,
  isVerified int,
  latitude serial,
  employmentDate tinyint,
  email datetime,
  createdAt set,
  currency binary,
  comment set,
  password text,
  duration blob,
  depositAmount binary,
  errorMessage float,
  content serial,
  expiryYear geometry,
  rating decimal
);

CREATE TABLE companyarchive (
  id serial primary key,
  childId smallint,
  description float,
  apiVersion blob,
  currency serial,
  birthDate binary,
  headerImage decimal,
  instanceId text,
  title mediumint,
  cardHolder set,
  lastName mediumint,
  id date,
  loginCount tinyint,
  alertType tinyint,
  countryCode serial,
  managerId enum,
  expiryDate blob,
  maritalStatus point,
  cvv varchar,
  accountStatus blob,
  importId geometry,
  joinDate bit
);

CREATE TABLE order (
  id serial primary key,
  shippingAddress tinyint,
  content enum,
  bannerImage bigint,
  loginCount datetime,
  alertType varchar,
  size binary,
  articleId geometry,
  addressLine1 decimal,
  age datetime,
  balance timestamp,
  middleName date,
  facilityId datetime,
  dueDateAt bigint,
  username int,
  logLevel serial,
  lockoutEnd bit,
  isRequired varchar,
  handlerId binary,
  phone timestamp,
  metadata serial,
  currency double,
  avatar tinyint,
  documentId float,
  unit timestamp,
  apiKey date,
  category decimal
);

CREATE TABLE extcustomerlegacy (
  id serial primary key,
  group text,
  connectionString blob,
  shippingAddress text,
  employmentDate date,
  contactPhone binary,
  campaignId bigint,
  street geometry,
  zipCode blob
);

CREATE TABLE customer (
  id serial primary key,
  backupEmail text,
  browserType serial,
  guestId int
);

CREATE TABLE corerecord (
  id serial primary key,
  education datetime,
  fontFamily decimal,
  sku varchar,
  configId time,
  description time,
  id set,
  salary bit,
  formatType binary,
  coordinateY double,
  levelId timestamp,
  folderPath serial,
  birthDate smallint,
  updatedAt bigint,
  keywords smallint,
  companyId real,
  defaultValue binary,
  isDefault boolean,
  currencyCode set,
  expiryMonth enum,
  age datetime,
  deliveryDate float,
  itemCount real,
  flagged varchar,
  type smallint,
  isAdmin varchar,
  monthlyRate decimal,
  dimension float,
  fingerprint enum,
  hourlyRate datetime
);

