CREATE TABLE organization (
  id serial primary key,
  url datetime,
  signature time,
  licenseKey mediumint,
  friendId smallint,
  forwardTo point
);

CREATE TABLE usertemp (
  id serial primary key,
  clockIn set,
  keyId datetime,
  facilityId point,
  ipAddress serial,
  insuranceId date,
  feedbackId double,
  appVersion serial,
  exchangeRate blob,
  title float,
  cityName serial,
  billingFrequency tinyint,
  expiryMonth boolean,
  flagged enum,
  isPublic float,
  maxValue bigint,
  sku decimal,
  contentType smallint,
  deviceToken enum,
  authMethod boolean,
  emailStatus float,
  billingCycle enum,
  coordinateY bigint,
  guestId mediumint,
  fontSize serial,
  birthDate int,
  lastLoginAt bigint,
  abandonedCartId geometry
);

CREATE TABLE dstinventory (
  id serial primary key,
  iconPath geometry,
  floorNumber enum,
  abandonedCartId double,
  taxRate real,
  labelText enum,
  orderStatus serial,
  handlerId tinyint,
  minValue bigint,
  category real,
  moduleId tinyint
);

CREATE TABLE dst_transaction_out (
  id serial primary key,
  isFeatured bit,
  loadTime blob,
  customerGroup smallint,
  fileName real,
  fileType set,
  articleId varchar,
  creditScore bigint,
  budgetCode varchar,
  flagged varchar,
  facilityId int
);

CREATE TABLE cpyuserhist2025 (
  id serial primary key,
  discountCode varchar,
  coordinateX datetime,
  metaTitle time,
  city date,
  currencyCode date,
  validUntil binary,
  dailyLimit binary,
  clockOut geometry,
  cacheKey boolean,
  geoLocation set,
  cancelReason double,
  documentId mediumint,
  billingFrequency point,
  completedAt blob,
  enabledAt serial,
  cartId enum,
  dataSource blob,
  enrollmentDate float,
  paymentMethod geometry,
  frameRate mediumint,
  fileName datetime,
  courseId real,
  checkOutTime geometry
);

CREATE TABLE user (
  id serial primary key,
  customField2 bit,
  entryPoint real,
  street enum,
  status geometry,
  rating binary,
  updatedAt date,
  token tinyint,
  city enum,
  moduleId varchar,
  insertedAt geometry,
  geoLocation boolean,
  emailStatus decimal,
  driverLicense blob,
  taxRate binary,
  maxValue datetime,
  hostName blob,
  frameRate binary,
  inactiveAt set,
  customField1 enum,
  lastName float
);

CREATE TABLE fact_account_notifications (
  id serial primary key,
  title enum,
  signature date,
  expiryMonth tinyint,
  phone smallint
);

CREATE TABLE ref_config_temp (
  id serial primary key,
  street blob,
  documentId serial,
  errorCode varchar,
  metaTitle boolean,
  modifiedAt binary,
  merchantId datetime,
  keywords bigint,
  productCode serial,
  title datetime,
  token tinyint,
  depositAmount float,
  isActive boolean,
  industryType smallint,
  addressLine2 bit,
  monthlyRate bigint,
  abandonedCartId decimal,
  loginCount enum,
  ipAddress real,
  listingId datetime,
  budgetCode decimal,
  formatType int,
  entryPoint datetime,
  taxRate set,
  group double,
  instanceId tinyint,
  colorCode blob
);

CREATE TABLE organizationstatusnew (
  id serial primary key,
  deviceToken serial,
  channelId double,
  phone bigint,
  incidentId geometry,
  orderId tinyint,
  code bigint,
  group set,
  entryPoint geometry,
  dailyLimit float,
  marketId geometry,
  url float,
  layerId tinyint,
  budgetCode text,
  status enum,
  username enum,
  friendId bit,
  employeeId timestamp,
  menuId mediumint
);

CREATE TABLE ver_user_map (
  id serial primary key,
  depositAmount bigint,
  isBillable bit,
  category double,
  employeeCode enum,
  gateId timestamp,
  countryCode point,
  lastSeenAt point,
  code float,
  guestId blob,
  deviceId set,
  articleId mediumint
);

CREATE TABLE product (
  id serial primary key,
  score serial,
  monthlyRate real,
  lastName mediumint,
  logLevel mediumint,
  inactiveAt boolean,
  entityId float,
  abandonedCartId boolean,
  deviceId text,
  group mediumint,
  longitude serial,
  updatedAt point,
  dashboardId timestamp,
  cartId float,
  cloudId enum,
  authorId int,
  amount smallint,
  keyId time,
  actionType point,
  title time,
  orderId smallint,
  mapId date,
  latitude int,
  floorNumber blob
);

CREATE TABLE customer (
  id serial primary key,
  mobileNumber smallint,
  formatType smallint,
  addressLine1 geometry,
  maritalStatus datetime,
  filterType real,
  loginAttempts int,
  flagged real,
  orderId date,
  taxRate decimal,
  earnedPoints text,
  insertedAt point,
  category double,
  timezone bigint,
  homePhone set,
  nickname bit,
  creditCard tinyint,
  isLocked point,
  longitude geometry,
  code text,
  headerImage blob,
  discount geometry,
  age timestamp
);

CREATE TABLE log_payment (
  id serial primary key,
  menuId binary,
  fileType datetime,
  defaultLang decimal
);

CREATE TABLE user_log (
  id serial primary key,
  backupEmail date,
  earnedPoints smallint,
  marketId datetime,
  country smallint,
  fromDate real,
  attachmentUrl real,
  buildNumber time,
  batchId smallint,
  integrationId smallint,
  description bigint,
  blogId bit,
  hourlyRate double,
  category date,
  checkOutTime smallint,
  dashboardId mediumint,
  isLocked timestamp,
  dependentId real,
  customField2 serial,
  maxValue date,
  quantity bit,
  password time,
  deletedAt decimal,
  isActive tinyint,
  signature mediumint,
  enabledAt bigint,
  priority bigint,
  isSystem point,
  url smallint
);

CREATE TABLE core_organization (
  id serial primary key,
  longitude timestamp,
  customField2 real,
  isFeatured float,
  localeId boolean,
  quantity real,
  avatar boolean,
  creditCard date,
  instanceId bigint,
  content enum,
  browserType boolean
);

CREATE TABLE company (
  id serial primary key,
  languageCode decimal,
  city geometry,
  integrationId datetime,
  departmentCode int,
  foregroundColor binary,
  metaDescription tinyint,
  faxNumber enum,
  authorId mediumint,
  avatar float,
  abandonedCartId boolean,
  guestId point,
  hiddenAt smallint,
  discount binary,
  billingFrequency set,
  handlerId double,
  marketId set,
  middleName text,
  id serial,
  accountNumber point,
  bankAccount varchar,
  documentId date,
  contactPhone geometry,
  budgetCode date,
  cartId decimal,
  monthlyRate tinyint,
  keywords binary,
  endPoint text,
  cityName set,
  cloudId decimal,
  employeeCode set
);

CREATE TABLE ver_payment_2024 (
  id serial primary key,
  cityName real,
  password geometry,
  channelId geometry,
  height set,
  fileSize datetime,
  id serial,
  levelId date,
  currencyCode tinyint,
  score date,
  mapId int,
  activeDevices smallint,
  layerId decimal,
  dailyLimit bigint,
  businessType time,
  followCount date,
  certificateId real,
  loadTime tinyint,
  deletedAt geometry
);

CREATE TABLE coreaudit (
  id serial primary key,
  modifiedAt geometry,
  moduleId blob,
  itemCount boolean,
  clockIn double,
  deviceType int,
  id enum,
  merchantId text,
  fromDate decimal,
  couponCode int,
  friendId datetime,
  coordinateX boolean,
  category serial,
  dateFormat boolean,
  paymentMethod boolean,
  address boolean,
  uuid decimal,
  minValue timestamp,
  street enum,
  managerId set,
  backupEmail timestamp,
  childId tinyint,
  extractId time,
  isDraft datetime,
  weight blob,
  attemptCount bit,
  companyLogo bit,
  comment set,
  contactName binary,
  discount real,
  authorId geometry,
  accountType double
);

CREATE TABLE rel_config (
  id serial primary key,
  birthDate enum,
  balance geometry,
  dashboardId varchar,
  timezone bigint,
  configId serial,
  mainImage boolean,
  handlerId int
);

CREATE TABLE rel_company_seg (
  id serial primary key,
  fromDate text,
  cardHolder boolean,
  balance text,
  category double,
  lastName boolean,
  mainImage real,
  abandonedCartId mediumint,
  isEnabled smallint,
  description binary,
  couponCode mediumint,
  education geometry,
  customerGroup text,
  fontFamily timestamp,
  title time,
  hiddenAt decimal,
  token int,
  linkId smallint,
  flagged serial,
  phone bit,
  mapId smallint,
  licenseKey bit,
  forwardTo smallint
);

CREATE TABLE inventory (
  id serial primary key,
  isDefault varchar,
  lastLoginAt text,
  isHidden decimal,
  attemptCount timestamp,
  configId real,
  bookingDate binary
);

CREATE TABLE coreauditoutlegacy (
  id serial primary key,
  abandonedCartId time,
  address serial,
  hiddenAt mediumint,
  buildNumber datetime,
  isLocked real,
  documentId boolean,
  taxRate varchar,
  isSystem serial,
  createdAt binary,
  employeeId float,
  coordinateY date,
  mobileNumber bigint,
  billingCycle bigint,
  isPublic real,
  fingerprint point,
  description blob,
  dataSource enum,
  listId varchar
);

CREATE TABLE coreorganization (
  id serial primary key,
  industryType mediumint,
  cancelReason double,
  isEnabled real,
  brandId geometry,
  taxRate set,
  thumbnail smallint,
  inactiveAt date,
  department binary,
  height int,
  id blob,
  balance int,
  bankAccount set,
  email varchar,
  algorithm enum,
  exportId decimal,
  loginAttempts boolean,
  address binary,
  extractId decimal,
  zipCode enum,
  itemCount serial,
  iconPath date
);

CREATE TABLE transaction (
  id serial primary key,
  group timestamp,
  createdAt datetime,
  fileHash geometry,
  isArchived tinyint,
  contractId timestamp,
  category text,
  maxLimit boolean,
  alertType serial,
  attemptCount enum,
  isDraft int,
  defaultValue set,
  friendId decimal,
  minLimit float,
  address double,
  zipCode serial,
  deactivatedAt geometry,
  isPublic set,
  comment text,
  fileName datetime,
  homePhone datetime,
  updatedAt mediumint,
  amount point,
  timezone float,
  facilityId double,
  dailyLimit datetime,
  foregroundColor time,
  buildNumber real,
  modifiedAt timestamp,
  keywords date
);

CREATE TABLE organizationlegacy (
  id serial primary key,
  middleName serial,
  metadata text,
  accountType geometry,
  dueDateAt bigint,
  clientId text,
  inactiveAt set,
  expiryDate enum,
  merchantId point,
  isRequired text,
  likeCount tinyint,
  floorNumber bit,
  minValue geometry,
  metaKeywords smallint,
  instanceId binary,
  moveId boolean,
  sessionId time,
  education bit
);

CREATE TABLE transaction (
  id serial primary key,
  fileType blob,
  authorId boolean,
  manufacturerId bit,
  memberCount text,
  exportId varchar,
  loginCount decimal,
  departmentCode real,
  unit smallint,
  billingCycle serial,
  longitude timestamp,
  defaultLang point,
  companyLogo int,
  likeCount int,
  orderId mediumint,
  maritalStatus varchar,
  name blob,
  maxValue int,
  importId mediumint,
  comment bigint,
  checkInTime boolean,
  score time,
  bannerImage set,
  campaignId smallint,
  isDefault timestamp,
  deviceType boolean,
  orderStatus datetime,
  clockOut smallint
);

CREATE TABLE puborganizationdivv2 (
  id serial primary key,
  campaignId mediumint,
  fileName binary,
  coverImage geometry,
  score set,
  incidentId real,
  memberCount serial,
  childId real,
  version bit,
  comment decimal,
  filterType bigint,
  blogId tinyint,
  age boolean,
  channelId boolean,
  phone serial,
  iconPath set,
  contractId binary,
  createdAt timestamp,
  coordinateY float,
  expiryMonth bit,
  address double,
  completedAt enum,
  buildNumber geometry,
  mimeType double,
  levelId binary,
  department enum,
  facilityId time
);

CREATE TABLE account (
  id serial primary key,
  expiryMonth timestamp,
  score time,
  comment geometry,
  billingFrequency smallint,
  analyticsId time,
  invoiceId geometry,
  code datetime,
  firstName double,
  likeCount datetime,
  apiKey varchar,
  endDate decimal,
  groupName timestamp,
  metaKeywords mediumint,
  amount float,
  lastName serial,
  agentId bit,
  state double,
  balance datetime
);

CREATE TABLE pub_customer (
  id serial primary key,
  incidentId smallint,
  localeId mediumint,
  group boolean,
  department boolean,
  name enum,
  labelText boolean,
  salary smallint,
  childId tinyint,
  firmwareVersion bit,
  claimId text,
  entryPoint enum,
  title timestamp,
  adminNotes time
);

CREATE TABLE account_meta (
  id serial primary key,
  attemptCount tinyint,
  bookingDate text,
  guestId blob,
  batchId varchar,
  clockIn tinyint,
  authToken serial,
  creditScore time,
  thumbnail double,
  tags datetime,
  formatType date,
  mainImage date,
  group binary,
  title tinyint,
  followCount boolean,
  favoriteCount tinyint,
  fingerprint int,
  content boolean,
  longitude varchar,
  mimeType enum,
  balance enum,
  name varchar,
  insuranceId varchar,
  state datetime,
  browserType time,
  creditLimit bit,
  isLocked real
);

CREATE TABLE organization (
  id serial primary key,
  price time,
  isDefault varchar,
  claimId varchar,
  customerId bigint,
  addressLine2 point,
  avatar double,
  firmwareVersion real,
  amount tinyint
);

CREATE TABLE cpy_order (
  id serial primary key,
  uuid boolean,
  metadata bit,
  friendId double
);

CREATE TABLE tmppaymentmeta (
  id serial primary key,
  deviceToken datetime,
  companyLogo decimal,
  completionRate binary,
  contentType date,
  title date,
  employeeId float,
  isVerified varchar,
  cartId set,
  joinDate point,
  businessType enum,
  colorCode geometry,
  linkId real,
  shippingAddress set
);

CREATE TABLE account (
  id serial primary key,
  fileName enum,
  accessLevel enum,
  sessionId smallint,
  brandId time,
  itemCount geometry,
  maskType datetime,
  batchId real,
  metadata serial,
  dateFormat timestamp,
  orderId timestamp,
  clientId binary,
  cloudId date,
  budgetCode int,
  rating datetime,
  category blob,
  blogId datetime,
  dependentId time,
  isAdmin geometry,
  tags decimal,
  feedId bigint,
  courseId mediumint
);

CREATE TABLE transactionv2 (
  id serial primary key,
  metaKeywords serial,
  metaTitle double,
  exportId blob,
  alertType tinyint,
  latitude double,
  id time,
  country point,
  facilityId blob,
  entryPoint point,
  customField1 set,
  contactPhone blob,
  category float,
  cloudId time,
  levelId varchar
);

CREATE TABLE transaction_meta_2025 (
  id serial primary key,
  grade point,
  exchangeRate varchar,
  integrationId time,
  dialCode mediumint,
  backupEmail int,
  deviceToken timestamp
);

CREATE TABLE priv_product (
  id serial primary key,
  defaultValue text,
  signature smallint,
  managerId tinyint,
  bookingDate float,
  lastName point,
  maskType text,
  deletedAt tinyint,
  deliveryDate geometry,
  clockOut bit,
  minValue blob,
  comment float,
  quantity smallint,
  keywords timestamp,
  globalId point,
  dataSource blob,
  insuranceId varchar,
  logLevel float,
  apiVersion real,
  dueDateAt decimal,
  status serial,
  accessLevel geometry,
  feedId decimal,
  loginCount bigint,
  couponCode point,
  billingFrequency varchar,
  mobileNumber enum,
  adminNotes boolean
);

CREATE TABLE inventory (
  id serial primary key,
  description geometry,
  languageCode blob,
  fileHash smallint,
  dailyLimit varchar,
  logLevel date,
  amount time,
  likeCount point,
  content serial,
  birthDate double,
  lockoutEnd decimal
);

CREATE TABLE productarchivetemp (
  id serial primary key,
  score geometry,
  ipAddress tinyint,
  budgetCode binary
);

CREATE TABLE ver_config_v2 (
  id serial primary key,
  machineId bit,
  countryCode binary,
  departmentCode geometry,
  birthDate double,
  email blob,
  downloadCount datetime,
  macAddress real,
  quantity double,
  feedbackId datetime
);

CREATE TABLE payment (
  id serial primary key,
  headerImage geometry,
  couponCode smallint,
  groupName bit,
  dialCode geometry,
  birthDate text,
  lastName varchar,
  licenseKey bit,
  updatedAt double
);

CREATE TABLE payment_log (
  id serial primary key,
  gender binary,
  foregroundColor binary,
  languageCode blob,
  dailyLimit datetime,
  education datetime,
  amount tinyint,
  state decimal,
  blogId varchar,
  courseId double,
  countryCode bigint,
  comment set,
  feedId varchar,
  longitude date,
  email varchar,
  hashKey time,
  insertedAt tinyint,
  guestId int,
  loadTime double,
  addressLine1 smallint,
  fileSize tinyint,
  campaignId varchar,
  name int,
  discount bit,
  clockOut smallint,
  endPoint binary,
  friendId serial,
  floorNumber time,
  indexKey int,
  childId binary,
  rating date
);

CREATE TABLE product (
  id serial primary key,
  email binary,
  contactPhone mediumint,
  dailyLimit geometry,
  checkOutTime boolean,
  amount date,
  bookingDate point,
  fileType timestamp,
  cityName set,
  validUntil decimal,
  name real,
  totalAmount geometry,
  invoiceId bit,
  isHidden int,
  fileHash int,
  authToken double
);

CREATE TABLE configinfo (
  id serial primary key,
  rating varchar,
  bannerImage binary,
  cloudId double,
  grade int,
  appVersion bigint,
  monthlyRate boolean,
  balance varchar,
  keyId double,
  bankAccount point,
  deactivatedAt int,
  country serial,
  accountType boolean,
  metaKeywords blob,
  loadTime datetime,
  dataSource bigint,
  zipCode bigint,
  comment tinyint,
  gameId datetime,
  price point,
  productCode blob,
  addressLine2 geometry,
  birthDate bigint,
  createdAt smallint,
  frameRate enum,
  fileName boolean,
  paymentMethod bigint,
  isDraft bigint,
  dealerId datetime
);

CREATE TABLE inventory (
  id serial primary key,
  isEnabled blob,
  addressLine1 decimal,
  mobileNumber real,
  marketId time,
  fontFamily int,
  cvv boolean,
  globalId serial,
  hourlyRate decimal,
  listId binary,
  maxLimit decimal,
  createdAt geometry,
  grade geometry,
  metaDescription bit,
  lastName varchar,
  isArchived mediumint,
  email time,
  fromDate smallint
);

CREATE TABLE organizationtemp (
  id serial primary key,
  longitude point,
  licenseKey varchar
);

CREATE TABLE app_config (
  id serial primary key,
  dateFormat time,
  domainName mediumint,
  homePhone enum,
  budgetCode geometry,
  frameRate varchar,
  industryType enum,
  contractId enum,
  checkOutTime point,
  connectionString point,
  discount timestamp,
  city point,
  birthDate smallint,
  cartId date,
  indexKey decimal,
  amount timestamp,
  category int,
  latitude blob,
  invoiceId time,
  actionType enum,
  locationId bit,
  ipAddress real,
  addressLine2 int,
  maxValue float,
  hashKey decimal
);

CREATE TABLE auditseg (
  id serial primary key,
  buildNumber time,
  address set,
  maxValue binary,
  manufacturerId point,
  joinDate double,
  dimension tinyint,
  emergencyContact decimal,
  moveId double,
  mainImage double,
  courseId binary,
  displayOrder boolean
);

CREATE TABLE ver_inventory (
  id serial primary key,
  employeeCode bit,
  firmwareVersion time,
  folderPath date,
  downloadCount int,
  shippingAddress date,
  fileSize timestamp,
  merchantId geometry,
  title mediumint,
  dataSource binary,
  age smallint,
  discountCode enum,
  hiddenAt varchar,
  id set,
  bluetoothId blob,
  iconPath serial,
  accountType enum
);

CREATE TABLE extcustomernotifications (
  id serial primary key,
  maskType text,
  mainImage serial,
  marketId point,
  layerId binary,
  metaTitle smallint
);

