CREATE TABLE stg_company_div (
  id serial primary key,
  fileType float,
  isDeleted int,
  accountStatus real,
  couponCode serial,
  checkInTime set,
  phone date,
  postalCode real,
  blogId binary,
  hashKey tinyint,
  token float,
  jobTitle set,
  department bit,
  homePhone int,
  companyName datetime,
  comment date,
  creditScore decimal,
  address smallint,
  startDate time,
  ipAddress text,
  expiryYear set,
  countryCode double,
  attemptCount timestamp,
  gameId tinyint,
  value set,
  nickname timestamp
);

CREATE TABLE ref_payment_status (
  id serial primary key,
  attachmentUrl bit,
  billingCycle timestamp,
  eventDate double,
  localeId binary,
  balance int,
  entryPoint text,
  latitude mediumint,
  marketId varchar,
  incidentId varchar,
  billingFrequency geometry,
  depositAmount smallint,
  avatar geometry,
  loadTime float,
  messageId bit,
  contactEmail double,
  id float,
  authToken bit,
  enabledAt text,
  accountStatus varchar,
  linkId real,
  cloudId smallint,
  bannerImage real
);

CREATE TABLE aggaccount (
  id serial primary key,
  signature time,
  description decimal,
  avatar boolean,
  feedbackId boolean,
  facilityId datetime,
  insertedAt int,
  deletedAt text,
  customField1 text,
  currency float
);

CREATE TABLE customer (
  id serial primary key,
  itemCount tinyint,
  dialCode point,
  keyId smallint,
  coverImage smallint,
  score binary,
  mapId enum,
  colorCode point,
  loadTime boolean,
  geoLocation text,
  analyticsId boolean,
  metadata tinyint,
  errorMessage datetime,
  forwardTo double,
  url serial,
  comment set,
  isAdmin text,
  distributorId float,
  fontSize enum,
  productCode double,
  customField1 binary,
  listingId time,
  code geometry,
  apiKey point,
  addressLine1 serial,
  dimension bit,
  joinDate mediumint,
  billingCycle smallint,
  licenseKey float,
  errorCode time
);

CREATE TABLE dim_payment_log (
  id serial primary key,
  address varchar,
  name boolean,
  age smallint,
  balance bigint,
  productCode varchar,
  contactEmail int,
  audioUrl smallint,
  avatar smallint,
  deactivatedAt set,
  customField2 datetime,
  fromDate int,
  dealerId mediumint,
  completionRate date
);

CREATE TABLE facttransaction (
  id serial primary key,
  coordinateY mediumint,
  category time,
  claimId timestamp,
  longitude time,
  contactPhone timestamp,
  cvv float,
  bookingDate date,
  frameRate smallint,
  timezone timestamp,
  guestId mediumint,
  version time,
  ipAddress geometry,
  latitude datetime,
  activeDevices text,
  tags smallint,
  formatType smallint,
  maxValue serial,
  messageId serial,
  street smallint,
  dueDateAt float,
  isBillable set,
  itemCount time,
  authorId blob,
  id timestamp,
  email serial,
  companyName enum
);

CREATE TABLE order_rel (
  id serial primary key,
  totalAmount serial,
  latitude geometry,
  isLocked bit,
  uuid decimal,
  listingId time,
  cloudId point,
  referralCode datetime,
  entryPoint varchar
);

CREATE TABLE reftransaction (
  id serial primary key,
  appVersion float,
  clockOut blob,
  checkOutTime int,
  cardNumber smallint,
  completionRate date,
  floorNumber set,
  startDate real,
  firmwareVersion varchar,
  age binary,
  timezone real,
  mimeType datetime,
  budgetCode bit,
  inactiveAt binary,
  isRequired set,
  customerGroup mediumint,
  fileName varchar,
  moveId smallint,
  enrollmentDate text,
  zipCode decimal,
  dimension tinyint,
  businessType point,
  feedbackId tinyint,
  defaultValue date,
  macAddress enum,
  isActive time,
  role mediumint,
  address serial,
  isArchived decimal
);

CREATE TABLE dimconfigdiv (
  id serial primary key,
  formatType datetime,
  currencyCode datetime
);

CREATE TABLE product (
  id serial primary key,
  batchId serial,
  deviceId text,
  amount smallint,
  homePhone bigint,
  countryCode smallint,
  folderPath float,
  minLimit time,
  avatar varchar,
  moduleId varchar,
  accessLevel point,
  title float,
  languageCode geometry,
  campaignId text,
  rating real,
  menuId float,
  email binary,
  city smallint,
  password blob,
  apiKey enum,
  customerGroup set,
  name blob,
  lastSeenAt tinyint,
  hiddenAt double,
  isEnabled varchar
);

CREATE TABLE userseg (
  id serial primary key,
  appVersion serial,
  loadTime varchar,
  currencyCode enum,
  referralCode bigint,
  metadata smallint,
  salary date,
  indexKey datetime,
  metaTitle text,
  clientId bigint,
  mainImage enum,
  geoLocation int,
  rating timestamp,
  authorId smallint,
  linkId text,
  billingFrequency time,
  hostName timestamp,
  sessionId point,
  metaDescription smallint,
  chargeId geometry,
  errorCode int,
  languageCode mediumint,
  version float,
  meterNumber point,
  companyName smallint,
  checkOutTime smallint,
  description varchar,
  filterType geometry,
  birthDate datetime,
  phone bit
);

CREATE TABLE log_payment_hist (
  id serial primary key,
  lockoutEnd point,
  birthDate smallint,
  deactivatedAt bigint,
  discountCode point
);

CREATE TABLE aggaccount (
  id serial primary key,
  contentType bigint,
  isHidden varchar,
  taxRate timestamp,
  channelId time,
  distributorId timestamp,
  title double,
  duration date,
  maxValue int
);

CREATE TABLE cpy_customer (
  id serial primary key,
  currencyCode int,
  employmentDate geometry,
  isDeleted text,
  unit geometry,
  hourlyRate tinyint,
  isVerified mediumint,
  licenseKey blob,
  billingFrequency serial,
  totalAmount blob,
  city float,
  keyId time,
  incidentId geometry,
  fileName geometry,
  bankAccount bigint,
  phone bigint,
  isLocked enum,
  cacheKey tinyint,
  itemCount binary,
  costCenter decimal,
  defaultValue int,
  forwardTo enum,
  coverImage point,
  driverLicense set
);

CREATE TABLE src_config (
  id serial primary key,
  authMethod set,
  appVersion boolean,
  dashboardId datetime,
  flagged double,
  dependentId smallint,
  dailyLimit mediumint,
  customerId real,
  likeCount tinyint,
  orderStatus int,
  friendId decimal,
  geoLocation real,
  customField1 bigint,
  frameRate decimal,
  audioUrl mediumint,
  gameId time
);

CREATE TABLE configmap (
  id serial primary key,
  companyLogo enum,
  dealerId varchar,
  cartId mediumint,
  audioUrl int,
  discountCode timestamp,
  latitude date,
  headerImage blob
);

CREATE TABLE organization (
  id serial primary key,
  score smallint,
  expiryYear real,
  dueDateAt float,
  buildNumber decimal,
  integrationId point,
  defaultLang point,
  validUntil real,
  folderPath bit,
  dependentId blob,
  fontSize set,
  addressLine1 varchar,
  hashKey smallint,
  fileType serial,
  indexKey timestamp,
  creditLimit serial,
  dimension real,
  startDate timestamp,
  languageCode enum,
  isVerified bigint,
  gender blob,
  isBillable set,
  copyRight bit,
  country real,
  likeCount serial,
  contactEmail geometry,
  entryPoint varchar,
  emailStatus bigint,
  id date,
  dateFormat timestamp
);

CREATE TABLE logorganization (
  id serial primary key,
  firmwareVersion double,
  deviceToken set,
  orderId decimal,
  checkOutTime geometry,
  contractId time,
  deletedAt double,
  cartId bit,
  linkId smallint,
  creditScore datetime,
  displayName double,
  guestId text,
  instanceId timestamp,
  cvv date,
  balance mediumint,
  browserType text,
  defaultValue text,
  childId date,
  fileName decimal,
  chatId varchar
);

CREATE TABLE extpaymentdiv (
  id serial primary key,
  customerId bigint,
  thumbnail bit,
  linkId bigint,
  activeDevices double,
  description point,
  accountType blob,
  nickname serial,
  firstName blob,
  contactEmail time,
  handlerId decimal
);

CREATE TABLE vwpayment (
  id serial primary key,
  createdAt boolean,
  accountType bigint,
  mobileNumber double,
  orderId boolean,
  score set
);

CREATE TABLE ref_inventory (
  id serial primary key,
  name real,
  updatedAt timestamp,
  accessLevel double,
  cacheKey serial
);

CREATE TABLE app_user_map (
  id serial primary key,
  expiryYear bit,
  accessLevel geometry,
  price bigint,
  inactiveAt varchar,
  ipAddress text,
  messageId varchar,
  creditScore mediumint
);

CREATE TABLE stg_company_v1 (
  id serial primary key,
  agentId boolean,
  budgetCode enum,
  postalCode datetime,
  accountType timestamp,
  dimension bit,
  keyId boolean,
  instanceId point,
  coverImage text,
  customField2 date,
  lastLoginAt datetime,
  cityName decimal,
  joinDate timestamp
);

CREATE TABLE account_rel_2025 (
  id serial primary key,
  flagged point,
  clockIn mediumint,
  gateId bit,
  fileType serial,
  id binary,
  fileName serial,
  employeeCode text,
  layerId tinyint,
  entryPoint blob,
  isBillable float,
  insertedAt tinyint,
  guestId geometry
);

CREATE TABLE stg_customer (
  id serial primary key,
  groupName mediumint,
  latitude timestamp,
  abandonedCartId serial,
  channelId boolean,
  address mediumint,
  distributorId double,
  chatId double,
  itemCount binary,
  configId varchar,
  url binary,
  blogId double,
  campaignId text,
  postalCode point,
  licenseKey date,
  buildNumber boolean,
  albumId bigint,
  lastName int,
  attachmentUrl boolean
);

CREATE TABLE cpy_config_info (
  id serial primary key,
  channelId serial,
  creditLimit time,
  insertedAt mediumint,
  errorMessage decimal,
  moveId bigint,
  businessType bigint,
  id geometry,
  adminNotes binary,
  itemCount geometry,
  isFeatured geometry,
  cartId bit,
  defaultLang blob,
  sku serial,
  domainName smallint,
  creditCard float,
  buildNumber real,
  name float,
  mobileNumber boolean,
  chargeId smallint,
  insuranceId serial,
  contactName blob,
  address serial,
  gateId enum,
  loginAttempts decimal,
  machineId blob,
  entityId binary,
  isBillable varchar,
  metaKeywords decimal,
  couponCode blob,
  homePhone datetime
);

CREATE TABLE audit (
  id serial primary key,
  firstName timestamp,
  coordinateX mediumint,
  creditCard timestamp,
  ipAddress varchar,
  age time,
  grade double,
  accountType binary,
  maxValue time,
  moduleId decimal,
  feedbackId decimal,
  fingerprint text,
  lastName int,
  hiddenAt enum,
  token datetime,
  meterNumber tinyint,
  homePhone geometry,
  feedId float,
  logLevel text,
  contractId smallint,
  fileName float,
  colorCode text,
  locationId int,
  instanceId tinyint,
  likeCount int
);

CREATE TABLE record (
  id serial primary key,
  department text,
  lastLoginAt serial,
  couponCode date,
  uuid serial,
  fileHash time,
  companyId tinyint,
  chargeId decimal,
  amount bigint,
  avatar datetime,
  id timestamp,
  emailStatus binary,
  address serial,
  machineId decimal,
  licenseKey bit,
  activeDevices boolean,
  paymentMethod time,
  localeId timestamp,
  customField2 decimal,
  completedAt datetime,
  fromDate int,
  balance bigint,
  articleId float,
  loginCount blob,
  marketId bit,
  macAddress real,
  joinDate time,
  errorMessage datetime,
  code double,
  importId geometry
);

CREATE TABLE log_record (
  id serial primary key,
  algorithm serial,
  articleId varchar,
  couponCode timestamp,
  alertType smallint,
  ipAddress tinyint,
  hostName blob,
  layerId date,
  dealerId time,
  groupName bit,
  password int,
  meterNumber bigint,
  albumId enum,
  sessionId boolean,
  awardDate boolean,
  joinDate time,
  hiddenAt geometry,
  dialCode int,
  accountType date,
  updatedAt int,
  courseId date,
  memberCount enum,
  username geometry,
  birthDate geometry,
  maxLimit text,
  street text,
  houseNumber real,
  contactEmail date,
  salary boolean,
  linkId bigint,
  firmwareVersion serial,
  localeId int
);

CREATE TABLE payment (
  id serial primary key,
  metaDescription date,
  bankAccount boolean,
  menuId float,
  filterType date,
  companyId text,
  authToken enum,
  value binary,
  downloadCount enum,
  currencyCode set,
  accountType time,
  exportId boolean,
  shippingAddress binary,
  education tinyint,
  licenseKey geometry,
  customField2 text,
  grade int,
  middleName text,
  homePhone decimal,
  connectionString tinyint,
  actionType time,
  loginAttempts decimal,
  completionRate double
);

CREATE TABLE apprecordlog (
  id serial primary key,
  country enum,
  employeeId tinyint,
  timezone int,
  manufacturerId text,
  joinDate point,
  driverLicense boolean,
  depositAmount datetime,
  insuranceId enum,
  contentType double,
  address tinyint,
  startDate set,
  comment double,
  bluetoothId blob,
  description float,
  updatedAt timestamp,
  exchangeRate date,
  algorithm binary,
  groupName blob,
  cityName point,
  accountNumber timestamp,
  paymentMethod blob,
  category time
);

CREATE TABLE user_extra (
  id serial primary key,
  referralCode int,
  homePhone int,
  hostName double,
  bluetoothId boolean,
  avatar real,
  isBillable double,
  instructorId text,
  username text,
  discount real,
  coverImage double,
  url decimal,
  entityId float,
  iconPath decimal,
  rating bigint,
  accessLevel double,
  loadTime datetime,
  birthDate serial,
  keywords binary,
  managerId date,
  copyRight tinyint,
  loginAttempts blob,
  activeDevices date,
  guestId real,
  driverLicense smallint,
  bookingDate tinyint,
  discountCode bigint,
  orderId geometry,
  businessType point,
  dashboardId bit,
  weight real
);

CREATE TABLE inventory_data_v1 (
  id serial primary key,
  amount serial,
  startDate binary,
  currency datetime,
  marketId double,
  mobileNumber float,
  countryCode serial,
  moduleId float,
  connectionString bit,
  feedId real,
  addressLine1 set,
  errorCode boolean,
  address timestamp,
  priority varchar,
  latitude varchar,
  updatedAt time,
  flagged decimal,
  signature set,
  facilityId text,
  cloudId geometry,
  authMethod enum,
  forwardTo tinyint
);

CREATE TABLE tmpinventory (
  id serial primary key,
  addressLine1 point,
  state varchar,
  phone float,
  version binary,
  completionRate int,
  dataSource geometry,
  zipCode geometry,
  age enum,
  balance smallint
);

CREATE TABLE customer (
  id serial primary key,
  licenseKey datetime,
  firmwareVersion varchar,
  guestId point,
  clockOut time,
  accessLevel bigint,
  mainImage varchar
);

CREATE TABLE customer (
  id serial primary key,
  title set,
  memberCount set,
  password geometry,
  formatType timestamp,
  machineId double,
  gender float,
  customerGroup timestamp,
  isActive mediumint,
  isHidden decimal,
  age date,
  deletedAt decimal,
  flagged bigint,
  authToken bigint,
  accountNumber real,
  editedAt bit,
  accessLevel time,
  isPublic point,
  orderStatus varchar,
  exchangeRate boolean,
  completionRate geometry,
  mainImage double,
  dependentId time,
  minLimit tinyint,
  feedId time,
  comment point,
  joinDate real,
  weight int,
  isRequired point,
  group binary
);

CREATE TABLE pubcustomerextra (
  id serial primary key,
  checkInTime point,
  gender binary,
  folderPath datetime,
  fileSize serial,
  group date,
  apiKey boolean,
  logLevel time,
  fileName binary,
  firmwareVersion varchar,
  accountStatus time,
  exportId boolean,
  fontFamily binary,
  hashKey time,
  apiVersion enum,
  clockOut decimal,
  coordinateX bigint,
  companyId tinyint,
  isEnabled text,
  favoriteCount timestamp,
  cacheKey mediumint,
  awardDate geometry,
  documentId bit
);

CREATE TABLE paymentinfo (
  id serial primary key,
  token serial,
  priority binary,
  headerImage double,
  completedAt point,
  followCount real,
  algorithm real,
  copyRight timestamp,
  marketId smallint,
  displayOrder double,
  lastLoginAt time,
  unit time,
  dimension geometry,
  education decimal
);

CREATE TABLE ref_record_log_temp (
  id serial primary key,
  isFeatured text,
  managerId smallint,
  completedAt binary,
  billingCycle blob,
  accountType real,
  avatar tinyint,
  gender timestamp,
  geoLocation bigint,
  gameId int,
  timezone boolean,
  isHidden int,
  discount mediumint,
  costCenter serial,
  entryPoint smallint,
  defaultValue bit,
  title mediumint,
  address point,
  creditScore varchar,
  grade float,
  downloadCount time,
  referralCode set,
  contactName varchar,
  dataSource varchar,
  maxValue blob,
  businessType mediumint,
  manufacturerId bit,
  department int,
  insertedAt serial,
  isEnabled timestamp
);

CREATE TABLE organization_2024 (
  id serial primary key,
  listId double,
  copyRight point,
  cardHolder float,
  dealerId bit,
  loginAttempts timestamp,
  accessLevel bit,
  levelId bit,
  feedId double,
  shippingAddress date,
  listingId boolean,
  modifiedAt boolean,
  longitude serial,
  customerGroup serial,
  age point,
  filterType double,
  completedAt int,
  deviceType int,
  authMethod bit,
  contentType real,
  fontSize mediumint,
  ipAddress time,
  group enum,
  algorithm float,
  type binary,
  avatar date
);

CREATE TABLE inventory (
  id serial primary key,
  accessLevel double,
  guestId timestamp,
  maskType binary,
  orderStatus decimal,
  cloudId enum,
  token int,
  isSystem bigint,
  accountType int,
  editedAt binary,
  jobTitle geometry
);

CREATE TABLE organization_2025 (
  id serial primary key,
  monthlyRate smallint,
  deliveryDate set,
  fontFamily smallint,
  checkOutTime real,
  extractId boolean,
  errorMessage set,
  audioUrl enum,
  companyLogo timestamp,
  title bit,
  discountCode tinyint,
  cardNumber int,
  keyId enum,
  startDate bigint,
  status date,
  memberCount real,
  incidentId double,
  employmentDate point,
  customerGroup text,
  listId point,
  meterNumber real,
  deviceId binary,
  instanceId tinyint,
  quantity geometry,
  joinDate timestamp,
  certificateId point,
  isFeatured float,
  enabledAt enum,
  fileHash real,
  likeCount serial,
  coordinateY varchar
);

CREATE TABLE cpy_inventory (
  id serial primary key,
  colorCode set,
  customField2 boolean,
  incidentId varchar,
  entryPoint varchar,
  token bit,
  domainName serial
);

CREATE TABLE transaction (
  id serial primary key,
  brandId text,
  createdAt binary,
  validUntil bit,
  cancelReason datetime
);

CREATE TABLE product_2024 (
  id serial primary key,
  foregroundColor date,
  title time,
  integrationId blob,
  accessLevel geometry,
  status text,
  fontSize smallint,
  signature boolean,
  metaDescription blob,
  postalCode real,
  coordinateX mediumint,
  maskType text,
  faxNumber blob,
  comment binary,
  importId blob,
  houseNumber bit,
  fileName bit,
  countryCode varchar,
  connectionString decimal,
  bookingDate decimal,
  education enum,
  accountType float,
  category real,
  referralCode bit,
  buildNumber int,
  dateFormat decimal,
  isArchived serial,
  dependentId bit
);

CREATE TABLE order (
  id serial primary key,
  token enum,
  quantity varchar
);

CREATE TABLE ref_inventory_archive (
  id serial primary key,
  birthDate float,
  endDate bigint,
  companyId decimal,
  type real,
  maxLimit tinyint,
  contactPhone real,
  role date,
  bannerImage smallint,
  description serial,
  campaignId float,
  iconPath mediumint,
  filterType bigint,
  username decimal,
  dueDateAt int,
  avatar int,
  group serial,
  dateFormat float
);

CREATE TABLE fact_account (
  id serial primary key,
  businessType float,
  attachmentUrl set
);

CREATE TABLE config (
  id serial primary key,
  type varchar,
  totalAmount blob,
  managerId tinyint,
  listingId decimal,
  currencyCode set,
  colorCode point,
  price boolean
);

CREATE TABLE organization_archive (
  id serial primary key,
  latitude mediumint,
  country date,
  lastSeenAt geometry,
  mainImage smallint,
  state int,
  longitude tinyint,
  isSystem enum,
  status real,
  loginAttempts boolean,
  insuranceId boolean,
  currencyCode geometry,
  comment geometry,
  title mediumint,
  token bigint,
  mapId decimal,
  category double,
  entryPoint blob,
  endPoint decimal,
  group tinyint,
  appVersion datetime,
  address time,
  adminNotes point,
  lockoutEnd float,
  claimId bigint,
  postalCode binary,
  folderPath text,
  levelId varchar,
  contactPhone double,
  customerGroup blob,
  dataSource time,
  department mediumint
);

